### ISSUE TITLE
BulkInsert uses merge approach or insert one (with SetOutputIdentity set to false) without any clear criteria

### ISSUE THREAD

**Issue by matteotrapani** [borisdj/EFCore.BulkExtensions#1008]
Hello everyone!

First of all thank you for your great effort in this library!

I'm facing some issue in understanding how the `BulkInsert` method works, mostly because I see some incoherent behaviors between the code and the actual queries.

The problem I have is that in my application we use bulk insert operation for some background tasks which operates on different tables.
This is the code that should execute the bulk insert:
`await dbContext.BulkInsertAsync(entities, cancellationToken: cancellationToken).ConfigureAwait(false)`

While analyzing the different operation we could see that the same piece of code runs different queries and we don't understand the criteria. 
For example we have some case where the query executed is a simple `INSERT BULK INTO` without the use of temp table
```
insert bulk [dbo].[Table] ([CreatedOn] DateTime, [CreatedBy_UserId] BigInt, [UpdatedOn] DateTime, [UpdatedBy_UserId] BigInt, [Lcid] Int, [Code] NVarChar(200) COLLATE SQL_Latin1_General_CP1_CI_AS, [Value] NVarChar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS, [Key] UniqueIdentifier)
```

And other cases (with different table) where the used approach is the one of inserting data into a temp table and run a merge
```
insert bulk [dbo].[Table2Tempfc9eb42e] ([Id] BigInt, [CreatedBy_UserId] BigInt, [CreatedOn] DateTime, [DisplayName] NVarChar(500) COLLATE SQL_Latin1_General_CP1_CI_AS....)

[....]

MERGE [dbo].[Table2] WITH (HOLDLOCK) AS T USING (SELECT TOP 1000 * FROM [dbo].[Table2Tempfc9eb42e] ORDER BY [Id]) ....

```

I saw into the library code and I saw that the usage of the two operations should be decided based on the option `SetOutputIdentity`
![image](https://user-images.githubusercontent.com/22589546/203534046-83b8a891-2d63-4c88-ba50-1e6ecc2d3d91.png)

In my case I would expect to always have the direct INSERT without the usage of the temp table and merge. I digged a little bit into the code and I couldn't find any point where `SetOutputIdentity` is forced to **true**.

Can you help me in understanding what I am missing? It would be very important for us in order to understand whether always use `SetOutputIdentity=true` or not.

Thanks a lot!

**Comment by borisdj** [comment]
_SetOutputIdentity_ is set in the background when using _IncludeGraph_ or with _BulkSaveChanges_.
