### ISSUE TITLE
Issue in BulkInsertOrUpdateOrDelete

### ISSUE THREAD

**Issue by dineshhp82** [borisdj/EFCore.BulkExtensions#101]
I am facing issue while using BulkInsertOrUpdateOrDelete operation of EFCore.BulkExtension.

While I am digging out your master branch code found that there should be one more OR condition of 
operation.BulkInsertOrUpdateOrDelete in MergeTable Method otherwise your merge query always generate without the insert command.
Please find the link 
https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SqlQueryBuilder.cs#L100

And one more thing I have a case where table has primary key and Identity column in Id and non-key column (Name,Class,DOB) .While, I use Id +Name as key for Update and Delete operation in BulkInsertOrUpdateOrDelete method. Therefore your sqlquerybuilder should generate the merge query i.e.
"MERGE Student bi
USING StudentTemp bo
ON bi.Id= bo.Id and bi.Name=bo.Name".

But the query generated by builder is different b'coz not detect the Identity column at merge operation.

Could you please provide me any example to handle the above case.

Thanks in advance.

**Comment by borisdj** [comment]
You are correct about OR condition, I'll add that fix.

Regarding the second question if you want to Update by custom columns you have to add them into config, so in your case you should add both Id and Name columns:
```C#
var bulkConfig new BulkConfig
{
	UpdateByProperties = new List<string> { nameof(Student.Id), nameof(Student.Name) }
}
```

**Comment by dineshhp82** [comment]
👍

**Comment by borisdj** [comment]
Fix published, try latest NuGet.

**Comment by dineshhp82** [comment]
Thanks Buddy for quick solution.

I think there are some issue in setting of identity column condition and retrive column info. inside code. You use MERGE SQL query for BulkInsertOrUpdateOrDelete operation which need to set Identity OFF.

I face this issue as discuss in above scenario of UpdateByProperty that contain both key{ID} and non-key columns{Name}.

List<string> primaryKeys = tableInfo.PrimaryKeys.Select(k   => tableInfo.PropertyColumnNamesDict[k]).ToList();
//output : {ID,NAME}---Problem here   Id is primary key why Name here

List<string> columnsNames = tableInfo.PropertyColumnNamesDict.Values.ToList();
//output:{ID,NAME,DOB}

List<string> outputColumnsNames   = tableInfo.OutputPropertyColumnNamesDict.Values.ToList();
//output:{ID,NAME,DOB}

List<string> outputColumnsNames   = tableInfo.OutputPropertyColumnNamesDict.Values.ToList();
//output:{ID,NAME,DOB}

List<string> nonIdentityColumnsNames   = columnsNames.Where(a => !primaryKeys.Contains(a)).ToList();
//output:{DOB }—Problem here   column should be {NAME,DOB}

List<string> insertColumnsNames = (tableInfo.HasIdentity && !keepIdentity) ? nonIdentityColumnsNames : columnsNames;
//output:{ID,NAME,DOB}—Problem here column should be {NAME,DOB}

One more tableInfo.HasIdentity is false where as its Identity in DB 

Please have a look.

**Comment by borisdj** [comment]
You are welcome.

Could you write Entity model of this table.
And one question, if you have Id that is PK then why just not do the Sync by that column?
Otherwise if Name is Unique then you could use that column only.
It is little unusual to combine PK with nonPK columns.
Is there a reason for using it together, what's your scenario.

Regarding the `List primaryKeys` in the code that variable is actually used to make MERGE BY Columns so it conatain either PK column or _UpdateByColumns_ if they are set.
Maybe the name of variable could be changed to better describe its function.

**Comment by borisdj** [comment]
There was a bug HasIdentity was not always being read.
I have made a fix and committed it but NuGet is not yet published.
Try the latest source.
