### ISSUE TITLE
When MySQL uses batch operations, an error is reported

### ISSUE THREAD

**Issue by lovexian** [borisdj/EFCore.BulkExtensions#1010]
When MySQL uses batch operations, an error is reported

Version used: 6.5.6
Using the database: MySQL 8.0.28

Usage error:
1. Code:
var save = await _dbContext.SysSetting.Where(u => u.Id > 0). BatchUpdateAsync(p => new SysSetting
            {
                 // req corresponds to the modified field
                SystemName = req. SystemName,
                SystemWebsite = req. SystemWebsite,
                HomePage = req. HomePage,
                Copyright = req. Copyright,
                MenusNumber = req. MenusNumber,
            });

Error: "Length cannot be less than zero. (Parameter 'length')"
2. Code:
var aa = new List<SysSetting>
            {
                new SysSetting
                {
                    Id = req. Id,
                    // req corresponds to the modified field
                    SystemName = req. SystemName,
                    SystemWebsite = req. SystemWebsite,
                    HomePage = req. HomePage,
                    Copyright = req. Copyright,
                    MenusNumber = req. MenusNumber,
                }
            };

_dbContext.BulkUpdate(aa);

Error: Access denied for user 'ilng'@'%' to database 'XXXX'
(ps: database connection and permissions are correct)

What is the reason, please

**Comment by lovexian** [comment]
![image](https://user-images.githubusercontent.com/18639738/205033775-1ac86ab1-cb17-48a3-b5ad-5b31bd4037c9.png)
I'm depressed, is this version sure it's available?

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with ExecuteUpdate/ExecuteDelete, Batch extensions will become Deprecated here. Focus is only on BULK methods which are the main purpose of the lib.
