### ISSUE TITLE
Vulnerability in System.Data.SqlClient

### ISSUE THREAD

**Issue by LeonFreriks-calvi** [borisdj/EFCore.BulkExtensions#1013]
Using EFCore.BulkExtensions now generates a transitive dependency vulnerability warning for our software.
![image](https://user-images.githubusercontent.com/86774361/206004456-a0032cfc-148d-4250-b130-5be366b3477e.png)

We greatly appreciate this extension and would love to keep using it. Would it be possible to update the dependencies in order to fix the security vulnerability?

More information about this vulnerability can be found here:
https://github.com/advisories/GHSA-8g2p-5pqh-5jmc

Thanks in advance!

**Comment by Peter-B-** [comment]
Hi Leon,

you can install can include a fixed version of `System.Data.SqlClient` in your project to get rid of the vulnerability. 

See [the transitive dependencies section](https://github.com/advisories/GHSA-8g2p-5pqh-5jmc#:~:text=Editing%20projects%20to%20fix%20transitive%20dependencies) for more info.

**Comment by borisdj** [comment]
Latest version have all dependencies updated but this transitive one is still with 4.8.3.
For now try the fix @Peter-B- suggested till one of dependent packages that brings this via transition gets updated.

PS
Also to note that License is updated (more info pinned issue: 'LICENSE change notice').
Please check if you qualify for the free one.
(trying to fix the funding and make it sustainable)
