### ISSUE TITLE
postgre, BulkUpdate inserts records that are not in the table

### ISSUE THREAD

**Issue by sandiks** [borisdj/EFCore.BulkExtensions#1014]
can you tell me if this is the correct behavior , when using this method, rows are inserted that are not in the table

**Comment by geis01** [comment]
Hello,

This seems consistent with my experience from #1006

**Comment by borisdj** [comment]
Can you write reproducible example or test.

**Comment by borisdj** [comment]
Actually should be fixed now with v7.0.3
