### ISSUE TITLE
BatchUpdate with different/dynamic type

### ISSUE THREAD

**Issue by puschie286** [borisdj/EFCore.BulkExtensions#1026]
Hi,
we need to update some entities without using the entity class - this is because all entity property setters are internal / private so the repository / updating class cant modify the values ( and cant access the constructor of the entity class ).

our solution would be something like this:
```
List<string> updateColumns = new()
{
	nameof( Layer.ParentId ),
	nameof( Layer.Order )
};
object updateValues = new
{
	ParentId = targetId,
	Order = "+" + increaseValue
};
context.Layers.Where( **** ).BatchUpdateAsync( updateValues, updateColumns );
```

well, this doesnt work ( guess because of the type of updateValues )
The examples from README use updateExpression always, so im not sure how to use the object version of BulkUpdate

Any suggestions how to solve this ?

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with ExecuteUpdate/ExecuteDelete, Batch extensions will become Deprecated here. Focus is only on BULK methods which are the main purpose of the lib.
