### ISSUE TITLE
bug: sql parsing problem

### ISSUE THREAD

**Issue by nrcc** [borisdj/EFCore.BulkExtensions#1028]
In the BatchUtil.cs file, if the field contains ORDER, lines 203 through 206 will generate an incorrect SQL statement。

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with ExecuteUpdate/ExecuteDelete, Batch extensions will become Deprecated here. Focus is only on **BULK** methods which are the main purpose of the lib.
