### ISSUE TITLE
EfCore.BulkExtensions.SqlServer v6.6.3 includes a lot of files as linked items in any solution file

### ISSUE THREAD

**Issue by jonathanhallee** [borisdj/EFCore.BulkExtensions#1038]
**How to reproduce:**

1. Simply create a new Console app from the default VS template.
2. Include EFCore.BulkExtensions.SqlServer v6.6.3 in it.

You now see a lot of linked items that should not be there:
![image](https://user-images.githubusercontent.com/4730257/208502818-1ace3c5e-773e-45be-bb55-de645dbb7bd9.png)

**Note:**
We can remove those linked files but it has to be done manually. The package should not impose those linked items to my solution.

I'm guessing it is probably related to this commit? https://github.com/borisdj/EFCore.BulkExtensions/commit/3bc41acf315b5eaf8145d4b2c1459f31d84b25e9

This does not happen with 6.6.2

**Comment by borisdj** [comment]
try v6.6.4

**Comment by jonathanhallee** [comment]
Hey @borisdj I can confirm it's resolved. Thank you!
