### ISSUE TITLE
NullReferenceException on SqlServer

### ISSUE THREAD

**Issue by edokan** [borisdj/EFCore.BulkExtensions#1039]
Per https://github.com/borisdj/EFCore.BulkExtensions/blob/efb43d0964108832bf55680c6024228f573b86ac/EFCore.BulkExtensions/SqlAdapters/SqlAdaptersMapping.cs#L75 BulkExtension cannot find `SqlServerDbServer` since it is looking for `SqlDbServer`.

**Comment by PaulKamps** [comment]
When will this be merged?
