### ISSUE TITLE
Bulk Select case sensitive

### ISSUE THREAD

**Issue by soetedja** [borisdj/EFCore.BulkExtensions#1043]
Is there any option to ignore the case while using BulkSelect?
e.g.
I'm searching a data that contains in this list ('SKU1', 'SKU2', SKU3') but in the Database, the data was saved with lower-case
(Sku1, Sku2, Sku3)

`List<string> skuPartList = parts.Select(x => x.SKU.Trim()).Distinct().ToList();`
`var partList = skuPartList.Select(sku => new Part() {ModelNumber = sku }).ToList();`
`var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(Part.ModelNumber) } };`

I really appreciate any help you can provide.

**Comment by sommmen** [comment]
Firstly, I'd choose one casing and always stick with that so you won't have this issue,

Secondly you can change the database collation so it will always invoke case-insensitive compares. See: https://learn.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity#database-collation
