### ISSUE TITLE
Strange behavior when adding migrations 

### ISSUE THREAD

**Issue by ahmet-keskin** [borisdj/EFCore.BulkExtensions#1049]
Hi,
After adding reference to EFCore.BulkExtensions nuget package, adding migration adds code as if the system is using Postgresql database even though we are using SQL Server. The example below is taken 

`b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)`

**Comment by mmathias007** [comment]
I'm having the same issue. My project doesn't have any reference for Postgresql and checked the provider name on the DbContext  it is "Microsoft.EntityFrameworkCore.SqlServer"

**Comment by red-man** [comment]
Same for me, there is a bunch of Npgsql references in the migration files.  Running `dotnet ef dbcontext info` verifies I am using SqlServer.

**Comment by borisdj** [comment]
Take per provider package, EFCore.BulkExtensions.SqlServer
