### ISSUE TITLE
How to use the EnableStreaming option?

### ISSUE THREAD

**Issue by LukeBolly** [borisdj/EFCore.BulkExtensions#1054]
Is there any information on how to use EnableStreaming in this library?

The link on microsoft says
"Enables or disables a SqlBulkCopy object to stream data from an IDataReaderobject."

Do I need to create a type that implements IDataReader? or is that done under the hood by this library?

For example, is it enough to simply pass a List<MyType> with EnableStreaming and it is done?

**Comment by borisdj** [comment]
With latest version 7.1.4 _BulkConfig_ now has _**IDataReader**_:

> When configured data is loaded from this object instead of entity list which should be empty

and  **_EnableStreaming_**

> Can be set to True if want to have tracking of entities from BulkRead or when SetOutputIdentity is set.

If data is in memory list then stream has no point
(still list can be mapped t oreader using FastMember - sample `DataReaderTest` but is only for testing)
A stream from file is example of practical usage, and it can be put into this DataReader.
