### ISSUE TITLE
UnderlyingConnection/Transaction support

### ISSUE THREAD

**Issue by pmunin** [borisdj/EFCore.BulkExtensions#106]
Sometimes for tracing purposes we need to use wrapped connection/transaction/command objects - feed it to EF DbContext. In this case BulkExtensions throw null reference exception, since it assume that dbContext.Database.Connection is always SqlConnection.

Please add support for custom connection/transaction objects (e.g. in BulkConfig object)

**Comment by borisdj** [comment]
I'll have to take a deeper look into this and your pull request.

**Comment by borisdj** [comment]
EFCoreBulkUnderlyingTest is throwing
System.InvalidCastException : Unable to cast object of type 'EFCore.BulkExtensions.Tests.MyConnection' to type 'System.Data.SqlClient.SqlConnection'.

**Comment by borisdj** [comment]
Pull merged and NuGet 2.3.5 published

**Comment by pmunin** [comment]
Thanks man!

**Comment by borisdj** [comment]
You're Welcome.
