### ISSUE TITLE
Postgres Bulk Insert does not skip default value properties resulting in npgsql exception

### ISSUE THREAD

**Issue by akonyer** [borisdj/EFCore.BulkExtensions#1061]
With EF7 and NpgSql 7.0.1 I am getting the following exception when trying to bulk insert data:

`System.InvalidOperationException: The binary import operation was started with 7 column(s), but 8 value(s) were provided.
   at Npgsql.ThrowHelper.ThrowInvalidOperationException_BinaryImportParametersMismatch(Int32 columnCount, Int32 valueCount)
   at Npgsql.NpgsqlBinaryImporter.CheckColumnIndex()
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, String dataTypeName, Boolean async, CancellationToken cancellationToken)`

This looks like the same issue described here was was supposedly fixed: https://github.com/borisdj/EFCore.BulkExtensions/issues/769

**Comment by goodstas** [comment]
@akonyer I got this exception too. Did u find a way to by-pass the exception?
@borisdj do you have any suggestions? thank you.

**Comment by akonyer** [comment]
@goodstas no, I have not found a solution. I wound up getting rid of this library in the short term. Will pull it back in when we get a bug fix.

**Comment by goodstas** [comment]
@akonyer I thought to try to use config options. If i remember right, there is option to exclude some properties of your class by providing config options to the BulkInsert method.
My class has Id property which is Auto Incremented  and also has navigation property to another class besides another properties.  So i thought that one of these two properties can make a problem..

**Comment by borisdj** [comment]
Can you try with version 7.

**Comment by akonyer** [comment]
I just tried with version 7.0.1 and I'm still getting the same error.

**Comment by borisdj** [comment]
Take the latest version and if still having issue alter a Test _DefaultValuesTest_ so that the issue would be reproducible.

**Comment by ozgurnevres** [comment]
In my case, the auto-generated Id was causing the problem. I resolved this like this:

    void BulkInsertCampaignAssets(List<InsertCampaignAssetDbServiceRequest> requests, long customerClientId)
    {
        _dbContext.BulkInsert(requests.Select(r => new CampaignAsset
        {
            AssetId = r.AssetId,
            CampaignId = r.CampaignId,
            CreateDate = DateTime.UtcNow,
            CustomerClientId = customerClientId,
            FieldType = r.FieldType,
            IsDeleted = false,
            PrimaryStatus = r.PrimaryStatus,
            PrimaryStatusDetails = r.PrimaryStatusDetails != null && r.PrimaryStatusDetails.Count > 0
                    ? JsonSerializer.Serialize(r.PrimaryStatusDetails) : null,
            PrimaryStatusReasons = r.PrimaryStatusReasons != null && r.PrimaryStatusReasons.Count > 0
                    ? JsonSerializer.Serialize(r.PrimaryStatusReasons) : null,
            ResourceName = r.ResourceName,
            Source = r.Source,
            Status = r.Status,
            UpdateDate = DateTime.UtcNow
        }), new BulkConfig
        {
            PropertiesToExclude = [
                nameof(CampaignAsset.Id)
                ],
        });
    }
