### ISSUE TITLE
Bulk operations with shadow property on postgresql does not work

### ISSUE THREAD

**Issue by gurkanguran** [borisdj/EFCore.BulkExtensions#1065]
Hi, 

I have come across the issue where the shadow property is not saved with the BulkInsertOrUpdate api. 

This is how I set the value of the shadow property :
dbContext.Entry(entity).Property("Data").CurrentValue = json;

This works with native efcore apis(DbSet.Add and SaveChanges operations) but not with BulkInsertOrUpdate.

**Comment by flomindanza** [comment]
Hello

I also noticed this issue working with the library.

Is it possible to handle shadow properties somehow?


Kind regards
Dan

**Comment by danflomin** [comment]
Hello

I also noticed this issue working with the library.

Is it possible to handle shadow properties somehow?

Kind regards
Dan

**Comment by borisdj** [comment]
Shadow Properties for now should be explicitly defined in entity, add it like:
public SomeType Data { get; set; }

**Comment by danflomin** [comment]
Hello, 

Unfortunately this is not possible for me, as I am using entities which are defined in another nuget package I use.
I add the shadow properties on top of them since I can't edit them myself.

I would really appreciate your help with fixing this issue.

Kind regards
Dan

**Comment by borisdj** [comment]
@danflomin fixed with latest v.

**Comment by danflomin** [comment]
Hello

Thank you very much!

I tried to use the latest version and I had an issue working with it.
I'll appreciate your help with it.

I suspect that the fact my DB works with snake case column names, the new code does not set the shadow property value to the column.

For example, the shadow property is named `DanFlomin`, but is being refernced as `dan_flomin` in the DB table.

In the `OnConfiguring` method I use `.UseSnakeCaseNamingConvention()`.


Thanks you very much for your assistance.

Kind regards
Dan

**Comment by borisdj** [comment]
Fix commited, but new nuget will be published with some other change, in 7 10 10 days.

**Comment by borisdj** [comment]
You could load the source instead of nuget and test it.

**Comment by danflomin** [comment]
Hello

I used the main branch and it looks like it is working fine.

Thank you

I'll appreciate if it will be possible to release the nuget 🙏  It will help me a lot.

Kind regards
Dan

**Comment by borisdj** [comment]
v7.1.4

**Comment by borisdj** [comment]
@danflomin v7.1.4

**Comment by danflomin** [comment]
Thank you very much!!
