### ISSUE TITLE
Make DB Connector dependencies optional

### ISSUE THREAD

**Issue by bocca** [borisdj/EFCore.BulkExtensions#1073]
Currently (reported with version 6.5.6) EFCode.BulkExtensions has strong dependencies to packages for all supported DB connectors. But not everybody uses all connectors, so this is a resource waste (disk space, memory, startup time, etc.). It would be nice to make DB connector optional. For example, each DB connector could be in a separate package (for example "EFCore.BulkExtensions.SqlServer") with its own specific dependencies.

These are the assemblies I have identified as DB specific:

For SQL Server (842 Kb):
- Microsoft.EntityFrameworkCore.SqlServer.dll
- Microsoft.Data.SqlClient.dll
- Microsoft.SqlServer.Server.dll
- Microsoft.SqlServer.Types.dll
- EntityFrameworkCore.SqlServer.HierarchyId.dll
- EntityFrameworkCore.SqlServer.HierarchyId.Abstractions.dll

For PostgreSQL (1.60 Mb):
- Npgsql.EntityFrameworkCore.PostgreSQL.dll
- Npgsql.dll

For MySql (0.97 Mb):
- Pomelo.EntityFrameworkCore.MySql.dll
- MySqlConnector.dll

For Sqlite (369 Kb):
- Microsoft.EntityFrameworkCore.Sqlite.dll
- Microsoft.Data.Sqlite.dll

**Comment by borisdj** [comment]
This already exist, for SqlServer just install:
_EFCore.BulkExtensions.SqlServer_

**Comment by bocca** [comment]
🤦‍♂️ Sorry! That's new in 6.6.0. I missed that! Thank you!
