### ISSUE TITLE
Default value resolution of lazy loaded properties results in error on not tracked entities

### ISSUE THREAD

**Issue by Grubana** [borisdj/EFCore.BulkExtensions#1075]
Hello,

I'm fairly new to using this library with PostgreSql adapter and had some issues due to the default value resolution in the GenericHelper class.
The issue occurs while fetching the default values for not tracked entities with lazy loading enabled.
As this also resolves navigation properties, the underlying database adapter tries to lazy load the property, which is not possible for not tracked entities or if the adapter is already disposed.

Also, looking at the code in PostgreSqlAdapter.cs it looks like the default value resolution is not necessary anymore.

**Comment by borisdj** [comment]
PR merged,
Thx for Contrib.
