### ISSUE TITLE
Upgrade Nuget Provider packages from 6.6.2 to 6.6.5

### ISSUE THREAD

**Issue by nk-cmd** [borisdj/EFCore.BulkExtensions#1077]
Hello, 
first of all thanks for the great and performant EF Core extension.

I have searched, but have not found a ticket that corresponds to my current problem. If there is one, please close it.

Currently I have the problem that when upgrading the individual DB Provider Packages from version 6.6.2 to 6.6.5 there are naming conflicts.
The compiler warns that the methods of the individual packages cannot be distinguished.

e.g.
EFCore.BulkExtensions.DbContextBulkExtensions.BulkUpdateAsync

Packages & versions without errors
```
<PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="6.6.2" />
<PackageReference Include="EFCore.BulkExtensions.SQLite" Version="6.6.2" />
<PackageReference Include="EFCore.BulkExtensions.SqlServer" Version="6.6.2" />
```

Packages & versions with error
```
<PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="6.6.5" />
<PackageReference Include="EFCore.BulkExtensions.SQLite" Version="6.6.5" />
<PackageReference Include="EFCore.BulkExtensions.SqlServer" Version="6.6.5" />
```

**Comment by borisdj** [comment]
If you need multiple providers at same time, then just use the main nuget _EFCore.BulkExtensions_ that has all.
With latest changes specific ones are be used as a single.
Will see in the future if they can be changed to work in a combination of 2 or 3.
