### ISSUE TITLE
.Local not updating

### ISSUE THREAD

**Issue by MeGaLoDoN228** [borisdj/EFCore.BulkExtensions#1078]
I use windows froms and i bind data to it using context.Local.ToBindingList, but if i do Bulk Insert or Bulk Delete, context.Local is not updated, so i don't see new data in grid view. My only way is to bind data using context.Set<>, but it does not support sorting in datagridview. What i can do to make Local update?

**Comment by borisdj** [comment]
When using Bulk ops data is not being tracked.
You should just reload the grid.

**Comment by MeGaLoDoN228** [comment]
I know, but sorting works only if bind Local.ToBindingList, is there any workaround to convert _context.Set to binding list?
