### ISSUE TITLE
Foreign Key Constraint

### ISSUE THREAD

**Issue by dnbhatt1991** [borisdj/EFCore.BulkExtensions#108]
hello i have multiple foreign key on child table
and it shows below error
The MERGE statement conflicted with the FOREIGN KEY constraint "[FK_Name]". The conflict occurred in database "[Database_Name]", table "[Table_Name]", column '[Column_Name]'.

i have also see similar post 
https://entityframework-extensions.net/foreign-key-constraint-autodetectchanges-disabled

**Comment by borisdj** [comment]
Could you write simplified models of relevant entities.

**Comment by dnbhatt1991** [comment]
yes

model

public partial class DocumentationOf
    {
        public DocumentationOf()
        {
            Performer = new HashSet<Performer>();
        }

        [Column("ID")]
        public int Id { get; set; }
        [Column("DocumentID")]
        public int? DocumentId { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string ServiceEventClassCode { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string ServiceEventCode { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string ServiceEventType { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string ServiceEventName { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string EffectiveStartDate { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string EffectiveEndDate { get; set; }

        [InverseProperty("DocumentationOfPerformer")]
        public virtual ICollection<Performer> Performer { get; set; }
        [ForeignKey("DocumentId")]
        [InverseProperty("DocumentationOf")]
        public virtual Document Document { get; set; }
    }


public partial class Performer
    {
        [Column("ID")]
        public int Id { get; set; }
        [Column("PerformerID")]
        public int? PerformerId { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string TypeCode { get; set; }
        [Column("CodeID", TypeName = "varchar(200)")]
        public string CodeId { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string PerformerCode { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string PerformerCodeType { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string PerformerTypeName { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Phone { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string PhoneUse { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string EffectiveStartdate { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string EffectiveEndDate { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string OrganizationCodeId { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Name { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string OrganizationPhone { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string OrganizationPhoneUse { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string AddressUse { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string StreetAddressLine { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string City { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string State { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string PostalCode { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Country { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Prefix { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Firstname { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string Lasttname { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string AssignPersonPrefix { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string AssignPersonFirstname { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string AssignPersonLasttname { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string FunctionCodeCode { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string FunctionCodeCodeType { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string FunctionCodeCodeName { get; set; }
        [Column(TypeName = "varchar(200)")]
        public string FunctionCodeOriginalText { get; set; }

        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual DocumentationOf DocumentationOfPerformer { get; set; }

        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual Encounters EncountersPerformer { get; set; }
        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual Immunization ImmunizationPerformer { get; set; }
        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual Medication MedicationPerformer { get; set; }
        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual Payer PayerPerformer { get; set; }
        [ForeignKey("PerformerId")]
        [InverseProperty("Performer")]
        public virtual Procedures ProceduresPerformer { get; set; }
    }

-------------*******************************************************

 private void BulkInsert<T>(IList<T> List) where T : class
        {
            _context.ChangeTracker.AutoDetectChangesEnabled = false;
            _context.ChangeTracker.DetectChanges();
            _context.BulkInsert(List,
                new BulkConfig
                {                    
                    PreserveInsertOrder = true,
                    SetOutputIdentity = true,
                    BatchSize = 4000,
                    UseTempDB = true
                });
        }


  #region DocumentationOf
                var DocumentationOf = new List<DocumentationOf>();
                CCDDocumentlist.ForEach(e =>
                {
                    DocumentationOf.AddRange(
                        e.DocumentationOf.Select(c => { c.DocumentId = e.Id; return c; })                      
                        
                        );
                
                });
                BulkInsert(DocumentationOf);

                var Performer = new List<Performer>();

                DocumentationOf.ForEach(e =>
                {
                    //e.Performer
                    Performer.AddRange(e.Performer.Select(c => { c.PerformerId = e.Id; return c; }));
                });
                BulkInsert(Performer);
                #endregion


error : 
The MERGE statement conflicted with the FOREIGN KEY constraint "FK_Performer_Encounters_PerformerID". The conflict occurred in database "CCD", table "dbo.Encounters", column 'ID'.
The statement has been terminated

**Comment by borisdj** [comment]
You haven't write entire code of other entities that are referenced in this part of code.
Also what I meant by 'simplify' is to remove all extra column that are no connected with the bug so that exception would be easier to isolate, in your case remove all string properties except first maybe and also remove  references of others table, leave 3 tables that are enough to reproduce the bug.
Also please format the code in post for better readability with segment
\`\`\`
\`\`\`C#'

And it would be the best if you could then enter that simplified
