### ISSUE TITLE
Bulk Insert Doesnt work with more records

### ISSUE THREAD

**Issue by rhemasystems** [borisdj/EFCore.BulkExtensions#1082]
Please I dont know why when the records are 2 the bulk insert works but when they are more than 10 records it doesnt insert, and doesnt also give any errors.
I tried adding the `BulkConfig` method and it works but I also need to include the `BulkOperation` option in the `BulkInsert` method,but it doesnt allow me passing both `BulkConfig` and the `BulkOperation`  option parameters into the same `BulkInsert` method.
NOTE: The table has an identity column.
Please help me

`using (var transaction = _context.Database.BeginTransaction())`
 `{`
        `var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };`
                    `await _context.BulkInsertAsync(attendance, option => {`
                        `option.InsertIfNotExists = true;`
                        `option.ColumnPrimaryKeyNames=(new List<string> { "ChurchMemberId", "ChurchEventId" });`
                        `});`
                    `transaction.Commit();`
               `}`

**Comment by borisdj** [comment]
Also BulkConfig can be set either with Object or with Action arg, you can't use both for single bulk method.
Best to put all config in the Object:
```C#
...
var bulkConfig = new BulkConfig
{
  PreserveInsertOrder = true,
  SetOutputIdentity = true,
  InsertIfNotExists = true;
  ColumnPrimaryKeyNames=(new List<string> { "ChurchMemberId", "ChurchEventId" });
};
await _context.BulkInsertAsync(attendance, bulkConfig);
...
```
