### ISSUE TITLE
BulkInsert with one-to-many relationships fails with InvalidOperationsException

### ISSUE THREAD

**Issue by AndrinGautschi** [borisdj/EFCore.BulkExtensions#1084]
Hi

I have to optimize a (Hangfire)Syncjob and for that I plan to use Bulkqueries. Unfortunately I struggle with the first of many operations: the bulk insert. To be exact: I keep running into `System.InvalidOperationException: 'FromSql' or 'SqlQuery' was called with non-composable SQL and with a query composing over it. Consider calling 'AsEnumerable' after the method to perform the composition on the client side.` and I honestly have no idea anymore what to do with that.

What I try: Inserting a list of entities with each having (EntityA) two One-to-Many relationships to other tables. I assume that these linked entities in the other two tables should be stored correctly when storing only the EntityA.

My model builder setup: 
```c#
modelBuilder.Entity<EntityA>()
            .OwnsMany(
                r => r.ListOfEntityB, builder =>
                {
                    builder.HasKey(nameof(ListOfEntityB.KeyPart1), nameof(ListOfEntityB.KeyPart2));
                    builder.WithOwner().HasForeignKey(r => r.FK);
                    builder.ToTable("EntityBTable");
                })
            .OwnsMany(
                s => s.ListOfEntityC, builder =>
                {
                    builder.HasKey(nameof(EntityC.KeyPart1), nameof(EntityC.KeyPart2));
                    builder.WithOwner().HasForeignKey(r => r.FK);
                    builder.ToTable("EntityCTable");
                });
```

My code:
```c#
public async Task BulkInsertAsync(List<EntityA> list)
    {
        await db.BulkInsertAsync(list, config =>
        {
            config.IncludeGraph = true;
            config.SetOutputIdentity = false;
        });
    }
```

What I already tried:
1.  I assumed that somehow there's a problem with mapping results to a query. I made sure that all the properties of each involved entity is listed in my model.
2. The problem comes with the `config.IncludeGraph = true` setting. If I omit it, it works fine and is fast, but it writes only to EntityATable, not to EntityBTable and not to EntityCTable. 

Versions: EFCore.BulkExtensions@7.0.1

If somebody can point me in a direction or has an idea what exactly isn't working, I'd be very happy. 

Regards

**Comment by AndrinGautschi** [comment]
I found [this commented test case ](https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions.Tests/IncludeGraph/OwnedGraph.cs) which indicates, that nested owned lists are not supported.

**Comment by borisdj** [comment]
_IncludeGraph_ was a PR feature and does not works for all complex cases.
For now best go without it and just use pure Bulk ops.
You can use _**SetOutputIdentity**_ to get Id of tableA if need it as FK in tables B and C before sending them in Bulk method.
Check in the ReadMe segment:
`Example of SetOutputIdentity with parent-child FK related tables:` // Option 1
