### ISSUE TITLE
SqliteParameter Issue When Object Parameter Uses HasColumnName After 6.6.5

### ISSUE THREAD

**Issue by corykroll** [borisdj/EFCore.BulkExtensions#1085]
I've been having an issue with any version after 6.6.5.

I have an object in which a parameter is named differently in the POCO than in the database.
Let's say I define my database object with a nullable enum parameter as follows:

```
[Table("PassingRecord")]
public partial class PassingRecord
{
     public PassingType? PassingType { get; set; }
}
```

Then, in the DbContext, note that this is named differently in the database, since I store the enum value as an integer:

```
modelBuilder.Entity<PassingRecord>()
.Property(x => x.PassingType).HasColumnName("PassingTypeID");
```

This used to work.  But after upgrading past 6.6.5 I instead get the following error instead when doing bulk inserts with this model:

`System.IndexOutOfRangeException: 'A SqliteParameter with ParameterName '@PassingType' is not contained by this SqliteParameterCollection.'`

It is as if it doesn't recognize the property mapping anymore.

I am targeting NET 7.
If I use the 6.6.5 NuGet it works again, even targeting NET 7.

**Comment by mtelle** [comment]
Hi, I have found that problem yesterday, i jave created a PR for that fix 
#1086

**Comment by Naveen61097** [comment]
Hi Team, Any updates on this? It would be better if it is fixed ASAP.

**Comment by borisdj** [comment]
PR merged, thx for contrib.
New nuget will be released in a few days.

Btw sql params are created using Property names (@SomeName), but I figure they could be created using Column names.
What would you consider to be better convention and there are special usecases.

**Comment by borisdj** [comment]
v7.0.3 is published
