### ISSUE TITLE
BulkConfig.StatsInfo is null

### ISSUE THREAD

**Issue by LaurasDilys** [borisdj/EFCore.BulkExtensions#1089]
I am using the BulkSaveChangesAsync method and I want to return the affected rows. However, I am unable to do so, because BulkConfig.StatsInfo is null even though `CalculateStats = true` – in the example below '0' is always returned, because bulkConfig.StatsInfo is null. I am using a Postgres database, in case that's relevant.

    public async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        var bulkConfig = new BulkConfig { CalculateStats = true };

        await _context.Database.CreateExecutionStrategy().ExecuteAsync(async () =>
        {
            using var transaction = await _context.Database.BeginTransactionAsync();

            await _context.BulkSaveChangesAsync(bulkConfig: bulkConfig, cancellationToken: cancellationToken);

            await transaction.CommitAsync();
        });

        var rowsAffected =
            bulkConfig.StatsInfo?.StatsNumberInserted +
            bulkConfig.StatsInfo?.StatsNumberUpdated +
            bulkConfig.StatsInfo?.StatsNumberDeleted;

        return rowsAffected ?? 0;
    }

**Comment by Xiaoxin-19** [comment]
I am also using PG and have the same problem

**Comment by borisdj** [comment]
Fixed with latest v.
