### ISSUE TITLE
Significantly slower performance upon adding multiple DBSets

### ISSUE THREAD

**Issue by Siam1205** [borisdj/EFCore.BulkExtensions#109]
While trying out this extension framework I stumbled into a strange issue.

While maintaining only 1 DbSet of ClassA inside the DbContext, I manage to insert 1.000.000 entries in round about 18 seconds to this DbSet of ClassA. But once I add a second DbSet of ClassB which stores a Collection of ClassA, the time to insert the data to the DbSet of ClassA increases significantly.

**Example:**
With 1 DbSet of ClassA storing only some double, int and string properties, 50k entries are inserted in 1,5 seconds to this DbSet. Once I add a second DbSet of ClassB storing an ICollection of ClassA, it takes 26 seconds to insert Tag 50k elements Into the DbSet of ClassA

This happens with the newest version 2.3.4 the same way it does with older versions like 2.0.0.

![image](https://user-images.githubusercontent.com/23073192/49510546-cdfdc080-f888-11e8-9440-dd735d3368ee.png)

**Comment by Siam1205** [comment]
Sadly I didn't save the exact repository where this issue occurred since I have worked around it for now. I could reproduce it and test it but I have not got time for this. But vaguely, this is the code. Note that it is not compilable but should serve as pseudo code for showing you what I did.

I only need to comment out the DataGraveYards-DbSet and I achieve 18 sek  for 1.000.000 DataGraves. If i leave the DbSet inside the context, I need significantly more time.

Indeed, as soon as I have some kind of navigation property inside a model class, this effect occurs. Without having navigation properties, everything works like a charm. This is my workaround btw. I removed all navigation properties and reference everything by an ID. Its not optimal but it works and I can go on.

If you have questions, just ask.


```csharp
    public class DataGraveYard
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; } = "Yard";
    }

    public class DataGrave
    {
        [Key]
        public int Id { get; set; }

        public int DataGraveYardId { get; set; }

        public int IntProp1 { get; set; }
        public int IntProp2 { get; set; }
        public int IntProp3 { get; set; }
        public int IntProp4 { get; set; }
        public int IntProp5 { get; set; }
        public int IntProp6 { get; set; }

        public string StringProp1 { get; set; }
        public string StringProp2 { get; set; }
        public string StringProp3 { get; set; }
        public string StringProp4 { get; set; }
        public string StringProp5 { get; set; }
        public string StringProp6 { get; set; }

        public double DoubleProp1 { get; set; }
        public double DoubleProp2 { get; set; }
        public double DoubleProp3 { get; set; }
        public double DoubleProp4 { get; set; }
        public double DoubleProp5 { get; set; }
        public double DoubleProp6 { get; set; }
        public double DoubleProp7 { get; set; }
    }

    public class EfCoreContext : DbContext
    {
        private const string ConnectionString =
            @"data source=(localdb)\MSSQLLocalDB;initial catalog=EfCorePerformanceTestDb;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework";

        public EfCoreContext() : base()
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(ConnectionString);
            }
        }

        public DbSet<DataGrave> DataGraves { get; set; }
        public DbSet<DataGraveYard> DataGraveYards { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            ICollection<DataGrave> list = listGenerator.GenerateDataGraves(numberRows);
            ICollection<DataGraveYard> yards = new List<DataGraveYard>(1);
            DataGraveYard yard = new DataGraveYard();
            yards.Add(yard);

            WriteToDb(list, 5000);
        }

        public double WriteToDb(ICollection<DataGrave> dataGraves, int chunkSize)
        {
            using (EfCoreContext ctx = new EfCoreContext())
            {
		ctx.Database.EnsureCreated();
                ctx.BulkInsert(dataGraves.ToList(), new BulkConfig { BatchSize = chunkSize });
            }
        }
    }

**Comment by borisdj** [comment]
EFCoreBulkTest contains BulkInsert for 2 lists of entites into 2 DbSet within single Transaction.
There it works fine.
Also Navigation properties are not used at all for Bulk methods.
If you manage sometimes to reproduce the issue in unit Test write it again here.

**Comment by Siam1205** [comment]
That is why I called it "a strange issue". I will provide you the exact code in case I reproduce it again.
