### ISSUE TITLE
Update with OUTPUT query 

### ISSUE THREAD

**Issue by unosbaghaie** [borisdj/EFCore.BulkExtensions#110]
Would you add an extension to do something like the below query !

```
update Users 
set Status = 2
OUTPUT inserted.*
WHERE Status = 1
```

**Comment by borisdj** [comment]
You can achieve this by combining `BatchUpdate` with `BulkRead` in the following way:
```C#
var query = context.Users.Where(a => a.Status = 1);
var list = query.Select(a => new User { UserId = a.UserId }).ToList();
query.BatchUpdate(new User { Status = 2 });
context.BulkRead(list);
```

**Comment by unosbaghaie** [comment]
but here you are making 3 requests to db
but the query I have written is one request

**Comment by borisdj** [comment]
That's true but Selecting Ids and BulkRead are fast from performance point of view so it's should not be a big issue.
I have just made a test updating 1 000 000 rows and compare previously mentioned way with pure sql:
```C#
string sql = "UPDATE Users SET Status = 2 OUTPUT inserted.* WHERE Status = 1";
var list = ctx.Items.FromSql(sql).ToList();
```
and execution times are 14 seconds vs 12 seconds, so very little difference.
What is your use case?
Still I will put Enhancement label on this issue.

**Comment by unosbaghaie** [comment]
That's okay. I use it. But I wanted to fork your code to add some capabilities like that. maybe later 
In some scenarios reducing count of queries, even one request can be helpful. 

Thanks for your response
