### ISSUE TITLE
BulkInsertOrUpdateAsync broken

### ISSUE THREAD

**Issue by stevendarby** [borisdj/EFCore.BulkExtensions#1106]
Upgraded EFCore.BulkExtensions.SQLite from `6.6.2` to `7.0.1` and get this when calling `BulkInsertOrUpdateAsync`:
```
System.NullReferenceException : Object reference not set to an instance of an object.
SqlAdaptersMapping.CreateBulkOperationsAdapter()
SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
```

I saw a possibly related issue (https://github.com/borisdj/EFCore.BulkExtensions/issues/1056) which was closed due to `BatchDeleteAsync` being intentionally deprecated now that EF7 natively supports ExceuteUpdate/ExecuteDelete.

However, EF doesn't natively support an Insert-or-Update, so it will be sad if this is intentionally deprecated in BulkExtensions- it's the main reason I use it. Hope to hear there is a workaround! Thanks

**Comment by borisdj** [comment]
That is not related since your issue is about Bulk operation, while that one was Batch.
As said there BULK methods are in now focus as that was the main purpose of the lib. from the beginning.
Can you write reproducible example for the issue you have.
