### ISSUE TITLE
EFCore.BulkExtensions.SqlServer 7.0.1 - BatchDeleteAsync generates invalid SQL when used on the product of a union with joins

### ISSUE THREAD

**Issue by Dancpaz** [borisdj/EFCore.BulkExtensions#1111]
First, thank you for this wonderful extension--and for making it free.  It is very much appreciated.

Now, on to the issue.  My usage is functionally identical to the following:
```cs
var query1 = context.Set1.Where(x => ids.contains(x.Id));
var query2 = query1.Join(context.Set2, /*etc*/, (_,y) => y).Join(context.Set3, /*etc*/, (_,y) => y);
var query3= query1.Join(context.Set3, /*etc*/, (_,y) => y);
var query4 = query2.Union(query3);
await query4.BatchDeleteAsync(cancellationToken);
```

The generated SQL is very similar to the following, with comments mine:
```tsql
DELETE [h1]
FROM [Set1] AS [h]
INNER JOIN [Set2] AS [h0] ON /*etc*/
INNER JOIN [Set3] AS [h1] ON /*etc*/
WHERE 0 = 1
UNION
SELECT /*all fields from [h3]*/
FROM [Set1] AS [h2]
INNER JOIN [Set3] AS [h3] ON /*etc*/
WHERE
```

The result was an exception complaining of 'invalid syntax near UNION', and the behavior I would expect would be either deleting the results of both constituent queries without exception, or something like NotSupportedException explaining what is not supported.

I can delete query2 and query3 separately for now, but a fix at some point would be appreciated.  If you need more information, please do not hesitate to let me know.

**Comment by borisdj** [comment]
Glad it was useful.
Batch ops will probably be deprecated since EF as of v7 now supports it natively with ExecuteUpdate and ExecuteDelete.
Library focus in now on Bulk (CRUD + SaveCh.) methods.
So best to upgrade to EF7 and try with _ExecuteDelete_.
