### ISSUE TITLE
postgre - Count  Unique constraint - Schema missing

### ISSUE THREAD

**Issue by Maleaume** [borisdj/EFCore.BulkExtensions#1124]
Take A database.
Two schema with same tables. 

Current CountUniqueConstraint Query does not work  properly  with multi schemas: 
`   public static string CountUniqueConstrain(TableInfo tableInfo)
    {
        var primaryKeysColumns = tableInfo.PrimaryKeysPropertyColumnNameDict.Values.ToList();

        var q = $"SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ";
        foreach (var (pkColumn, index) in primaryKeysColumns.Select((value, i) => (value, i)))
        {
            q = q +
                $"INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu{index} " +
                $"ON cu{index}.CONSTRAINT_NAME = tc.CONSTRAINT_NAME AND cu{index}.COLUMN_NAME = '{pkColumn}' ";
        }

        q = q +
            $"WHERE (tc.CONSTRAINT_TYPE = 'UNIQUE' OR tc.CONSTRAINT_TYPE = 'PRIMARY KEY') " +
            $"AND tc.TABLE_NAME = '{tableInfo.TableName}' ";

        return q;
    }`

need to add  `tc.TABLE_NAME = `{tableInfo.TableSchema}` in where clause :  

``   public static string CountUniqueConstrain(TableInfo tableInfo)
    {
        var primaryKeysColumns = tableInfo.PrimaryKeysPropertyColumnNameDict.Values.ToList();

        var q = $"SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ";
        foreach (var (pkColumn, index) in primaryKeysColumns.Select((value, i) => (value, i)))
        {
            q = q +
                $"INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu{index} " +
                $"ON cu{index}.CONSTRAINT_NAME = tc.CONSTRAINT_NAME AND cu{index}.COLUMN_NAME = '{pkColumn}' ";
        }

        q = q +
            $"WHERE (tc.CONSTRAINT_TYPE = 'UNIQUE' OR tc.CONSTRAINT_TYPE = 'PRIMARY KEY') " +
            $"AND tc.TABLE_NAME = '{tableInfo.TableName}' AND `tc.TABLE_NAME = `{tableInfo.TableSchema} ";

        return q;
    }``

**Comment by borisdj** [comment]
Should be fixed with 7.0.4
