### ISSUE TITLE
Temp Tables not deleted in BulkInsertOrUpdate

### ISSUE THREAD

**Issue by Erry91** [borisdj/EFCore.BulkExtensions#1126]
This is the configuration I am using for the transaction. Notice that I have set **UseTempDb** to **true** in the attempt to tell SQL to drop the tables when the operation is complete or if any exception occurs.
![image](https://user-images.githubusercontent.com/6703817/228587808-202ecfa2-a92c-41d4-a88c-9f5fe9c092f1.png)

I wrapped the BulkOperation in a transaction as I saw has been suggested in other related issues. 
![image](https://user-images.githubusercontent.com/6703817/228587687-165c7868-14ae-4ffe-8a28-f2606c1c9634.png)

I have tracked the events related to one instance of this issue: the temporary table is created in my DB, the operation goes on, and at the end this table (TransportDocumentTempxxxx)
I enabled audit on my SQL server and this are the queries I believe are issued by the `BulkInsertOrUpdate`
![image](https://user-images.githubusercontent.com/6703817/228588870-43721c05-5ed7-4a76-a09a-5302bd3869cb.png)

I was wondering why the temp table is not being deleted after the operation is complete. 
Is there any evident issue in how I'm calling the BulkOperation?

thank you,
Enrico

**Comment by borisdj** [comment]
There is a note about _UseTempDB_ in the ReadMe:

> **UseTempDB** when set then BulkOperation has to be inside Transaction.

So even setting it won't have any effect.
Instead table is created ad regular, just with sufix 'Temp' in the name.
Still after operation is finished it executes Drop of that table.
Last query in your log result show the Drop command.

Try to run that sql command manually and see what happens.

**Comment by borisdj** [comment]
There was some improvement made with this, check v7.0.4
