### ISSUE TITLE
Shadow Property Usage With PropertiesToExclude

### ISSUE THREAD

**Issue by stuart-tapson-pinnacle** [borisdj/EFCore.BulkExtensions#1127]
I'm currently in the process of upgrading my NuGet packages to .Net and EF 6.0, as part of this I'm also updating the EFCore.BulkExtensions package from v3.3.1 to v6.6.5.

After performing this update I'm getting the error shown below:
```
Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'PropertyName 'IsDeleted' specified in 'PropertiesToExclude' not found in Properties.'
   at EFCore.BulkExtensions.TableInfo.ValidateSpecifiedPropertiesList(List`1 specifiedPropertiesList, String specifiedPropertiesListName)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
```

After seeing this I found an answered question, #869, which indicates that its due to shadow properties been used. My setup is almost identical to that shown in the answered question, 

Since I previously had no issues with the same implementation while using v3.3.1, I wanted to ask if this is a change introduced in the later version of the package or if maybe I'm missing some kind of config setting that may allow it to continue working? If not will support for the usage of shadow properties with PropertiesToExclude will be added in later versions?

**Update** I've found that if I add the IsDeleted column to the TemporalColumns property of BulkConfig this appears to resolve the issue, allowing my bulk operations to complete successfully. I'm still in the process of testing this, but I thought I'd ask if doing this likely to cause any issues?

Thanks
Stuart

**Comment by borisdj** [comment]
Do you have Shadow Property explicitly defined, and if not can you add it?
