### ISSUE TITLE
Could not load file or assembly EFCore.BulkExtensions

### ISSUE THREAD

**Issue by artnova-david** [borisdj/EFCore.BulkExtensions#1128]
Hi,
I recently upgraded EFCore.BulkExtensions from v 6.5.6 to v 7.0.1 in a .net 7 environment, locally everything works fine, but when deploying to Azure an exception is thrown: Could not load file or assembly EFCore.BulkExtensions Version=7.0.1.0.

I checked on the server and the .dll file is there with the correct version 7.0.1.0. 

I then deleted the nuget package EFCore.BulkExtensions cleared the nuget cache, deleted obj and bin folders and installed the EFCore.BulkExtensions.SqlServer v 7.0.1 package and republished the app, locally all works fine.  But in Azure again an exception is thrown Could not load file or assembly EFCore.BulkExtensions.SqlServer, Version=7.0.1.0

Any help would be appreciated
Kind regards

**Comment by AntonC9018** [comment]
What's the EF version?

**Comment by artnova-david** [comment]
Product version: 7.0.4
File version: 7.0.423.11504

**Comment by borisdj** [comment]
Have you tried taking specific subversion?
If it is SQL Server use latest version of
EFCore.BulkExtensions.SqlServer
