### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by vit-h** [borisdj/EFCore.BulkExtensions#1132]
Today I wanted to start using the lib but found that it requires a ton of other dependencies.
I would suggest getting rid of at least half or making a better split to the core and provider-specific libs.
Now it is a show-stopper because I do not want to inflate my containers and increase the chances of vulnerability.

Here is what I got when tried to install EFCore.BulkExtension to my dotnet 6.0 proj.
Updates:

System.Runtime.CompilerServices.Unsafe.4.7.1 -> System.Runtime.CompilerServices.Unsafe.6.0.0

Installing:

Azure.Core.1.25.0
Azure.Identity.1.7.0
dotMorten.Microsoft.SqlServer.Types.1.5.0
EFCore.BulkExtensions.7.0.1
EntityFrameworkCore.SqlServer.HierarchyId.4.0.0
EntityFrameworkCore.SqlServer.HierarchyId.Abstractions.4.0.0
Microsoft.Bcl.AsyncInterfaces.1.1.1
Microsoft.CSharp.4.5.0
Microsoft.Data.SqlClient.5.1.0
Microsoft.Data.SqlClient.SNI.runtime.5.1.0
Microsoft.Data.Sqlite.Core.7.0.2
Microsoft.EntityFrameworkCore.Sqlite.Core.7.0.2
Microsoft.EntityFrameworkCore.SqlServer.7.0.2
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite.7.0.2
Microsoft.Identity.Client.4.47.2
Microsoft.Identity.Client.Extensions.Msal.2.19.3
Microsoft.IdentityModel.Abstractions.6.24.0
Microsoft.IdentityModel.JsonWebTokens.6.24.0
Microsoft.IdentityModel.Logging.6.24.0
Microsoft.IdentityModel.Protocols.6.24.0
Microsoft.IdentityModel.Protocols.OpenIdConnect.6.24.0
Microsoft.IdentityModel.Tokens.6.24.0
Microsoft.NETCore.Platforms.1.1.0
Microsoft.NETCore.Targets.1.1.0
Microsoft.SqlServer.Server.1.0.0
Microsoft.Win32.Registry.4.7.0
Microsoft.Win32.SystemEvents.6.0.0
MySqlConnector.2.2.5
NetTopologySuite.2.5.0
NetTopologySuite.IO.SqlServerBytes.2.1.0
Pomelo.EntityFrameworkCore.MySql.7.0.0
runtime.native.System.Data.SqlClient.sni.4.7.0
runtime.win-arm64.runtime.native.System.Data.SqlClient.sni.4.4.0
runtime.win-x64.runtime.native.System.Data.SqlClient.sni.4.4.0
runtime.win-x86.runtime.native.System.Data.SqlClient.sni.4.4.0
SQLitePCLRaw.core.2.1.2
System.Configuration.ConfigurationManager.6.0.1
System.Data.SqlClient.4.8.3
System.Diagnostics.DiagnosticSource.7.0.0
System.Drawing.Common.6.0.0
System.Formats.Asn1.5.0.0
System.IdentityModel.Tokens.Jwt.6.24.0
System.Memory.4.5.4
System.Memory.Data.1.0.2
System.Numerics.Vectors.4.5.0
System.Runtime.4.3.0
System.Runtime.Caching.6.0.0
System.Security.AccessControl.6.0.0
System.Security.Cryptography.Cng.5.0.0
System.Security.Cryptography.ProtectedData.6.0.0
System.Security.Permissions.6.0.0
System.Security.Principal.Windows.5.0.0
System.Text.Encoding.4.3.0
System.Text.Encoding.CodePages.6.0.0
System.Windows.Extensions.6.0.0

**Comment by borisdj** [comment]
There are already specific ones, as stated in the ReadMe:

> That is main nuget for all Databases, there are also specific ones with single provider for those who need small packages.
> Only single specific can be installed in a project, if need more then use main one with all providers.

**Comment by vit-h** [comment]
Thanks, that is much better, also when going with the closest version to installed EF, when it does not update all other libs.
EFCore.BulkExtensions.PostgreSql

**Comment by borisdj** [comment]
@vit-h Not sure what you mean by that.
What exactly version are you using ?
Best to take the latest.
