### ISSUE TITLE
BulkInsert with database generated uniqueidentifier fails silently if ID already exists

### ISSUE THREAD

**Issue by MagMar94** [borisdj/EFCore.BulkExtensions#1137]
If the database is responsible for generating the ID but generates a GUID that already exists, the insert will fail silently. The entry will not be inserted into the database and no exception or warning will be raised.

We have a similar setup to the [test written for issue 606](https://github.com/borisdj/EFCore.BulkExtensions/issues/606#issuecomment-894815503). The database generated sequential IDs that already existed in the database, and the new entry was ignored. I expect an error if an entry is not inserted when `BulkInsert` is called.

The generated SQL was something like this:
```sql
MERGE [dbo].[TableA] WITH (HOLDLOCK) AS T USING (SELECT TOP 1 * 
FROM [dbo].[TableATemp123abc4D] 
ORDER BY [Id]) AS S ON T.[Id] = S.[Id] 
WHEN NOT MATCHED BY TARGET THEN INSERT ([Column1], [Column2]) 
VALUES (S.[Column1], S.[Column2]) OUTPUT INSERTED.[Id], INSERTED.[Column1], INSERTED.[Column2] INTO [dbo].[TableATemp123abc4DOutput];
```

**Comment by borisdj** [comment]
What DB are you using, MsSql ?
and how can Db generate double Guid,I thought it being different every time is guaranteed.
Have you tried to configure PK as [SequentialGuid](https://learn.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-ver16).

**Comment by MagMar94** [comment]
> What DB are you using, MsSql ?

We are using an Azure SQL Database.

> and how can Db generate double Guid,I thought it being different every time is guaranteed.

Good question! I should have specified that this is our leading theory. We recently changed from generating the sequential GUIDs in the code to generating them in the database. This worked fine on the developer machine and on the test-server, but in production the entries were not stored in the database. No errors were thrown, so we don't really have much to go on. The generated SQL (see issue description) has a constraint to not insert the entry if the ID already exists, leading us to believe the generated GUID was a conflict. This is slightly more likely because we use the sequential guid and not a random one. According to [the documentation](https://learn.microsoft.com/en-us/sql/t-sql/functions/newsequentialid-transact-sql?view=sql-server-ver16) GUIDs generated by using `NEWSEQUENTIALID` are unique on that computer. Given that the old IDs are generated on another server we might get conflicting IDs. It worked again after changing from `BulkInsert` to the `AddRange`-function built in to EF Core, but we really want to keep the bulk operation.

**Comment by MagMar94** [comment]
> Does this happens always or just sometimes?

It happened for all entries added in the few hours it was out.

> In addition if Db conflicts are possible then that might not be good Db structure.
Have you considered to revert to Code generated if possible, why was it changed? (I've used lib. RT.Combo for SeqGuid).
Another option would be to reGenerate old Guids on current DB with sql script.

Thank you for the input, I'll consider it 🙂 

> As for the issue itself, what would be expected behavior once the conflict occurs?

I expected an exception if `BulkInsert` is called and something doesn't get inserted, but this would introduce a breaking change. Another option would be to return something indicating that one or more rows failed. The developer can more easily detect errors if the number of inserted rows is returned instead of `void`.

> Still even now you should be able to see f there was conflict by setting config CalculateStats to True.
Afterward's check StatsInfo.StatsNumberInserted if it is less than how many was in the input then
TimeStampInfo.EntitiesOutput should contain list of those that passes so skipped ones can be identified by making a Diff with initial list.

Thank you! I was unaware of how to count the number of inserted rows. With this information we should be able to handle it 😊

**Comment by borisdj** [comment]
Glad it helped.

Btw there was some changes recently regarding license.
You can check if your company quality for free version or would need to buy one of tiers.
