### ISSUE TITLE
Owned types in separate table does not work

### ISSUE THREAD

**Issue by StevenRasmussen** [borisdj/EFCore.BulkExtensions#114]
I see that 'Owned' types is listed as supported but perhaps only with table splitting?  When I use an owned type that is in a separate table it doesn't appear to be working.  Here is the code to configure the owned entity:

``` csharp
modelBuilder.Entity<DmTransaction>(entity =>
{
     entity.OwnsOne(x => x.APPayment, a =>
     {
          a.ToTable(nameof(APPaymentExt));
          a.HasForeignKey(f => f.Transaction);
     });
}
```

**Comment by borisdj** [comment]
Yes, currently are supported only 'Owned' types mapped by convention to the same table as the owner.
For now you could change child to be regular 1-1 table instead of being owned type, and then implement method that does 2 BulkInsert, first parent list and then child list.
(there is example in the README of _parent-child FK related tables_).
I will put Enhancement tag for this feature.

**Comment by ChristopherHaws** [comment]
Owned types that have seperate tables currently causes the `BulkInsertOrUpdateOrDeleteAsync` call to fail with a null reference exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=EFCore.BulkExtensions
  StackTrace:
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdateOrDeleteAsync[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
```

Can the library at least ignore the owned type property so that we can do the bulk update as a 2nd call (similar to how it would work if it wasn't an owned type)?

**Comment by IT-CASADO** [comment]
Today, I encountered the same problem. I tired to set BulkConfig.PropertiesToExclude, but this doesn't change anything. I reviewed the code for EF Core 2.2, and can see that PropertiesToExclude/PropertiesToInclude are not applied to Owned Types.

Would help, if at least we can ignore such owned properties by setting PropertiesToExclude/PropertiesToInclude.

**Comment by ctolkien** [comment]
Also hitting this problem here.

**Comment by sandrohanea** [comment]
The same problem happens if OwnsMany is used but in this case, we cannot use @borisdj's approach as we cannot map them in the same table as the relation is 1-to-many.

**Comment by borisdj** [comment]
This can now, v3.4.6+, be achieved with config.
Here is example on entities from the Test, only changed to be owned in separated tables:
```C#
modelBuilder.Entity<ChangeLog>().OwnsOne(p => p.Audit, a => { a.ToTable(nameof(Audit)); });
```
```C#
public class ChangeLog
{
  public int ChangeLogId { get; set; }
  public string Description { get; set; }
  public Audit Audit { get; set; }
}

[Owned]
public class Audit
{
  public string ChangedBy { get; set; }
  public bool IsDeleted { get; set; }
  public InfoType InfoType { get; set; }
}
```
```C#
var entities = new List<ChangeLog>();
for (int i = 1; i <= 1000; i++)
{
  entities.Add(new ChangeLog
  {
    Description = "Dsc " + i,
    Audit = new Audit
    {
      ChangedBy = "User" + 1
      InfoType = InfoType.InfoTypeA
    }
});

var bulkConfig = new BulkConfig
{
  SetOutputIdentity = true,
  PropertiesToExclude = new List<string> {
    $"{nameof(Audit)}.{nameof(Audit.ChangedBy)}",
    $"{nameof(Audit)}.{nameof(Audit.IsDeleted)}",
    $"{nameof(Audit)}.{nameof(Audit.InfoType)}",
  }
};
context.BulkInsert(entities, bulkConfig);

var bulkConfigOwned = new BulkConfig
{
  CustomDestinationTableName = nameof(Audit),
  PropertiesToExclude = new List<string> { nameof(ChangeLog.Description) },
};

context.BulkInsert(entities, bulkConfigOwned);
```

**Comment by crperez5** [comment]
What about One-To-Many relationships? I am getting the Object reference not set to an instance of an object exception using an adapted version of your example above.
