### ISSUE TITLE
PostgreSQL: ON CONFLICT DO NOTHING equivalent

### ISSUE THREAD

**Issue by kuket15** [borisdj/EFCore.BulkExtensions#1141]
Don't know if I'm missing something from the documentation, but it looks like "ON CONFLICT" always includes the primary key [eg. ON CONFLICT(id)].

I'd like to handle every conflict scenarios (or specify ON CONFLICT for a specific UNIQUE constraint).
Any way to achieve it with the current implementation?

Thanks in advance

**Comment by borisdj** [comment]
Have you tried to set _UpdateByProperties_ in the config.
