### ISSUE TITLE
[Feature Request] Insert Ignore method (from mysql)

### ISSUE THREAD

**Issue by bob27aggiustatutto** [borisdj/EFCore.BulkExtensions#1144]

**Comment by bob27aggiustatutto** [comment]
Insert ignore in MySQL works that if the primary key is already present, no operation is performed

There isn't a function for that in this library

If you have any more questions I'm here

**Comment by borisdj** [comment]
Fixed with latest commit, new nuget will published by the end of next week.

**Comment by bob27aggiustatutto** [comment]
Thanks
