### ISSUE TITLE
Loading local data is disabled; this must be enabled on both the client and server sides

### ISSUE THREAD

**Issue by artistotless** [borisdj/EFCore.BulkExtensions#1147]
my connString looks like : $"server={dbServer};port={dbPort};user={dbUser};password={dbPassword};database={dbName};AllowLoadLocalInfile=true";

I also wrote in my.cnf :

[mysqld]
local_infile=1

And it still not works for me

**Comment by borisdj** [comment]
There is a comment in the ReadMe:

> **MySQL** run for the first time execute sql command: *SET GLOBAL local_infile = true;*

It could be run directly on server, or from EF with _ExecuteSqlRaw_
