### ISSUE TITLE
Entities Owned by multiple parents do not work

### ISSUE THREAD

**Issue by zyofeng** [borisdj/EFCore.BulkExtensions#1149]
This arises from an issue with efcore
https://github.com/dotnet/efcore/issues/13338

The owned Entities are ignored because FindEntityType returns null

**Comment by borisdj** [comment]
Can you write a test for this issue or a code snippet sample.

**Comment by zyofeng** [comment]
Alright, I've finally got around to this issue and put in a fix as well as some unit tests for this issue. It's a fairly niche use case but nevertheless it'd be good to fix.

#1542
