### ISSUE TITLE
HasConversion not working with JSON serialization

### ISSUE THREAD

**Issue by roddharris** [borisdj/EFCore.BulkExtensions#115]
I have an class (Transaction) that has a complex object property (Receiver).  In my EF mapping, I do the following:

`
builder.Entity<Transaction>().Property(t => t.Receiver)
   .HasColumnName("receiverdata")
   .HasConversion(v => JsonConvert.SerializeObject(v), v => JsonConvert.DeserializeObject<ReceiverEntity>(v));
`
When I try to do the following:
`_context.BulkInsert(transactions, new BulkConfig { SetOutputIdentity = true});`

I get the following error: `The given value of type ReceiverEntity from the data source cannot be converted to type nvarchar of the specified target column`

The column in the database is defined as nvarchar(MAX) and the conversion mapping does work when I work with EF directly.  Is there something I need to do differently when using `BulkInsert`?

**Comment by borisdj** [comment]
Could you write Entities of Transaction and Receiver class.

**Comment by borisdj** [comment]
What I was asking is to copy here code of these Entity classes so I could reproduce the issue.

**Comment by roddharris** [comment]
Will the [code snippets on my SO post](https://stackoverflow.com/questions/53871289/need-to-speed-up-writing-large-object-graph-to-database-with-entity-framework) do or do?

**Comment by borisdj** [comment]
Partly but it's still missing Receiver property and ReceiverEntity.
So copy them also.

**Comment by borisdj** [comment]
I have just made a test with JsonConvert and it passes successfully.
```C#
    public class Info
    {
        public int InfoId { get; set; }
        public string Message { get; set; }
        public DocExtension DocExtension { get; set; } = new DocExtension();
    }

    public class DocExtension
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
    }
```
```C#
    modelBuilder.Entity<Info>().Property(t => t.DocExtension).HasColumnName("DocExtension")
        .HasConversion(v => JsonConvert.SerializeObject(v), v => JsonConvert.DeserializeObject<DocExtension>(v));
```
```C#
[Fact]
private void InsertWithValueConversion()
{
    using (var context = new TestContext(ContextUtil.GetOptions()))
    {
        var entities = new List<Info>();
        for (int i = 1; i <= EntitiesNumber; i++)
        {
            entities.Add(new Info
            {
                Message = "Msg " + i,
                DocExtension = new DocExtension { Title = "Ti", SubTitle = "St" }
            });
        }
        context.BulkInsert(entities, new BulkConfig { SetOutputIdentity = true });
    }
}
```

Also to note that child entities are not automaticly insert with BulkOps but BulkInsert has to be called for each table.
