### ISSUE TITLE
The MERGE statement conflicted with the FOREIGN KEY constraint

### ISSUE THREAD

**Issue by jackcoral89** [borisdj/EFCore.BulkExtensions#1152]
Hi,
I'm seeing `The MERGE statement conflicted with the FOREIGN KEY constraint "FK_BinaryMeasureEvents_Scans_Scan_Id". The conflict occurred in database "MYDB", table "dbo.Scans", column 'Id'.` when working with this data model:

My models:
```c#
public class ScanModel
{
    public int Id { get; set; }
    public List<BinaryMeasureEventModel> BinaryMeasureEvents { get; set; }
}

public class BinaryMeasureEventModel
{
    public int Scan_Id { get; set; }
    public double Id { get; set; }
    public DateTime Timestamp { get; set; }
}

```

My relationship with fluent API:
```c#
builder.HasOne<Scan>()
            .WithMany(p => p.BinaryMeasureEventModels)
            .HasForeignKey(s => s.Scan_Id);
```

My context updating is:

```c#
context.Scans.AddAsync(scan);
context.BulkSaveChangesAsync();
```

Exception falls in `context.BulkSaveChangesAsync();`

Any ideas ?
Thanks in advance for support.

**Comment by borisdj** [comment]
Instead of FluentApi configure FK with Annotation like:

```C#
public class BinaryMeasureEventModel
{
    [ForeignKey("ScanModel")]
    public int Scan_Id { get; set; }
    public virtual ScanModel ScanModel { get; set; } = null!;

    // ...
}
```

and remove `builder.HasOne<Scan>()...`

Will check later if this can be improved to work also with Fluent config.

**Comment by jackcoral89** [comment]
I confirm that this has worked for me. Do you think it will work with fluent API in the future?
Thanks anyway for support.

Cheers.
@borisdj

**Comment by borisdj** [comment]
Yes, will try later to fix it once other bigger issues gets resolved.
