### ISSUE TITLE
Is data versioning possible?

### ISSUE THREAD

**Issue by petergade** [borisdj/EFCore.BulkExtensions#1153]
Hello,

we download periodically some time-series data from 3rd party apis. These typicaly have some timestamp and several values (for example temperature, humidity etc.). These values are sometimes changed/corrected retrospectively by 3rd party. 

We would like to have entity with Timestamp and Version as primary key and several numeric properties and during InsertOrUpdate command there would be comparison of value columns (temperature, humidity etc.) and if some of them were changed (for the same timestamp), new row with increased version would be created. So we never want to update existing rows, we want to do nothing if there is row with the same values and to insert new row with increased version if some of the values are different.

We use Postgres as database.

Is this scenario possible without reading data first and comparing them in C#?

Our users would like to know which values were changed retrospecively by data vendor.

Thank you

**Comment by borisdj** [comment]
That is too complex scenario for a single method to do all in the Db.
There is option for Insert_if_not_Exist, check config *PropertiesToIncludeOnUpdate* in the ReadMe, but only SqlServer supports this feature. And even there Version would have to be set in memory in advance.

In your case I would use BulkRead, then in memory do the comparison, remove the same ones, set Version for those with changes and then just BulkInsert them.
