### ISSUE TITLE
BulkUpdateAsync  doesn't work in version 6.7.12

### ISSUE THREAD

**Issue by fabiolg82** [borisdj/EFCore.BulkExtensions#1157]
I'm using version 6.7.12. The BulkUpdateAsync method doesn't seem to work but the BulkInsertAsync works normally. When the BulkUpdateAsync method is executed, it does not return (like an infinite loop) and does not write to the database
Here a part of my code

```
public async Task SaveChangementsAsync(List<LigneDO> list)
{
    var linesModification = list.Where(l => l.LigneId > 0).ToList();
    var linesInsert = list.Where(l => l.LigneId == 0).ToList();

    if (linesInsert.Any())
    {
        await _context.BulkInsertAsync(linesInsert);
    } 
    
    if(linesModification.Any())
    {
        await _context.BulkUpdateAsync(linesModification);
    }
}
```

**Comment by borisdj** [comment]
Can you write entire test where the issue would be reproducible.
Or, take a look at _OperationsTestAsync_ call to _RunUpdateAsync_ and try to alter that one.
