### ISSUE TITLE
Child collection objects and security to navigation id

### ISSUE THREAD

**Issue by mweel1** [borisdj/EFCore.BulkExtensions#1158]
I have a company, that has many products, and products, with many attributes.

I'm trying to use your library to post a complex JSON object to my API and update/delete/insert to the database across the entire graph.

My question is does the library ensure a child's navigation property id belongs to the parent before updating?   I would have a vulnerability of someone changed an productId in an attribute and it could get assigned to an entirely different company and product.

Thanks!

**Comment by borisdj** [comment]
Yes, Bulk ops are done in one after another from parent to child, with FK being set on children before sending it to Db.
You can make a test to check first if it works for your use case.
