### ISSUE TITLE
exporting data to sql server table: the given columnmapping does not match up with any column in the source or destination.

### ISSUE THREAD

**Issue by hamedelbhrawy** [borisdj/EFCore.BulkExtensions#1159]
exporting data to sql server table: the given columnmapping does not match up with any column in the source or destination.

**Comment by borisdj** [comment]
Can you write code same or Test where the issue would be reproducible,

**Comment by hamedelbhrawy** [comment]
I use export data from advanced menu in Dax studio 

I think the erorr in column name have "[ ]" in it but I can't change column name case I don't have acess of the source of data

**Comment by borisdj** [comment]
Fixed, will be published with next Nuget.
