### ISSUE TITLE
How to check if the record exists in the database before insert

### ISSUE THREAD

**Issue by raysefo** [borisdj/EFCore.BulkExtensions#1162]
Hi,
In my Blazor Server application, I am inserting a list of data into a SQL database as follows with EF Core 6. There are tens of thousands of data in the database and the list to be compared (List<GameBank> gameBank) might be 5000 records. Is there a more performant way with your extension instead of checking one by one in the loop?

```
public async Task AddStockAsync(List<GameBank> gameBank)
{
   await _oyunPalasContext.GameBanks.AddRangeAsync(gameBank);
   await _oyunPalasContext.SaveChangesAsync();
}

public partial class GameBank
    {
        public int GameBankId { get; set; }
        public Guid ReferenceId { get; set; }
        public string? ProductCode { get; set; }
        public int Quantity { get; set; }
        public string? Version { get; set; }
        public DateTime? RequestDateTime { get; set; } = DateTime.Now;
        public int? CustomerId { get; set; }
        public string? Password { get; set; }
        public DateTime? ResponseDateTime { get; set; } = DateTime.Now;
        public string? InitiationResultCode { get; set; }
        public string? CompanyToken { get; set; }
        public int Used { get; set; }
        public string? ProductDescription { get; set; }
        public string? Currency { get; set; }
        public double UnitPrice { get; set; }
        public double TotalPrice { get; set; }
        public string? ApplicationCode { get; set; }
        public double EstimateUnitPrice { get; set; }
        public string? ValidatedToken { get; set; }
        public string? Signature { get; set; }
        public int Status { get; set; }
        public virtual GameBankPin coupons { get; set; }
        public string? ClientTrxRef { get; set; }
    }
public partial class GameBankPin
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public int GameBankId { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string? Serial { get; set; }
        public string? Pin { get; set; }
        public virtual GameBank GameBanks { get; set; }
    }
```

**Comment by borisdj** [comment]
Yes, that what the extension serves with methods *BulkInsert, BulkInsertOrUpdate*,..
Check the **ReadMe** for more info and BulkConfig options, mainly UpdateByProp if need match not only by PK but by specific column(s)

**Comment by raysefo** [comment]
Hi @borisdj, 
How can I check **Serial** and **Pin** separately or both in BulkInsert? I only want to insert if there is no Serial or Pin or both in the database. Checked the **ReadMe** but still not sure.

**Comment by borisdj** [comment]
You should set UpdateByProperties, but if you add both Serial And Pin it will find it only when both are matched.
You can make it to behave like OR.
What you could do is call 2 Bulk ops, one with Serial and other with Pin.

Also from the ReadMe:

> If we want Insert only new and skip existing ones in Db (Insert_if_not_Exist) then use BulkInsertOrUpdate with config PropertiesToIncludeOnUpdate = new List<string> { "" }

**Comment by raysefo** [comment]
One last question @borisdj, is it possible to return the matching/duplicate values?

**Comment by borisdj** [comment]
Use setting SetOutputIdentity, and if any column has value in DB but not in model those not matched would not be loaded with that value.
Otherwise you could could call BulkRead, with config ReplaceReadEntities.
