### ISSUE TITLE
A SqliteParameter with ParameterName '@WordTemplateId' is not contained by this SqliteParameterCollection.

### ISSUE THREAD

**Issue by rburnashev85** [borisdj/EFCore.BulkExtensions#1189]
SqlLite

```
public class WordTemplate
{
    public int Id { get; set; }
    public WordTemplateType Type { get; set; } //enum
    public string Name { get; set; }
    public string Description { get; set; }
    public List<WordTemplateTranslation> Translations { get; set; }
}

public class WordTemplateTranslation
{
    public int Id
    public string Name { get; private set; }
}
```

```
    public void Configure(EntityTypeBuilder<WordTemplate> builder)
    {
        builder.Property(p => p.Name).HasMaxLength(256);
        builder.Property(p => p.Description).HasMaxLength(512);

        builder.HasMany(x => x.Translations).WithOne().IsRequired().OnDelete(DeleteBehavior.Cascade);
    }

    public void Configure(EntityTypeBuilder<WordTemplateTranslation> builder)
    {
        builder.Property(p => p.Name).HasMaxLength(256);
    }

```
1) BulkSaveChangesAsync() -> the exception
2) BulkInsertAsync(wordTemplates) -> ok, BulkInsertAsync(wordTemplates.SelectMany(x => x.Translations)) -> the exception

**Comment by borisdj** [comment]
Try adding fk property explicitly `public int WordTemplateId { get; set; }` in _WordTemplateTranslation_.

**Comment by rburnashev85** [comment]
@borisdj  Now I get this error 

I also tried 2 options: 

1) Set all ids to 0.
2) Set all ids to 1

Same error

` Message: 
Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'FOREIGN KEY constraint failed'.

  Stack Trace: 
SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
SqliteDataReader.NextResult()
SqliteCommand.ExecuteReader(CommandBehavior behavior)
SqliteCommand.ExecuteReader()
SqliteCommand.ExecuteNonQuery()
DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
SqliteAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
SqliteAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
SqliteAdapter.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IEnumerable`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken)
DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
DbContextBulkTransactionSaveChanges.InvokeBulkMethod(DbContext context, List`1 entities, Type entityType, String methodName, BulkConfig bulkConfig, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken)
DbContextBulkTransactionSaveChanges.SaveChangesAsync(DbContext context, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IEnumerable`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)`

**Comment by borisdj** [comment]
Actually you need also `virtual WordTemplate` so in WordTemplateTranslation to have both:
```C#
public int WordTemplateId { get; set; }
public virtual WordTemplate WordTemplate { get; set; } = null!;
```
and also change _OnDelete_ config to the following:
```
modelBuilder.Entity<WordTemplateTranslation>()
  .HasOne(x => x.WordTemplate)
  .WithMany(a => a.Translations)
  .OnDelete(DeleteBehavior.Cascade);
```

This should make it work.

**Comment by rburnashev85** [comment]
Unfortunatelly, it didn't help.

**Comment by borisdj** [comment]
Could you alter existing test: SaveChangesTest to make the issue reproducible.
Or write another one with your entities.

**Comment by rburnashev85** [comment]
I will create an empty project to reproduce the issue and then I will share it with u.

**Comment by rburnashev85** [comment]
It works very strange. There are 3 scenarios. First one passes. Other 2 throw 2 different exceptions. Could you check it please

[EFCoreBulkExtensionsTestProject1.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/12048600/EFCoreBulkExtensionsTestProject1.zip)
