### ISSUE TITLE
Given ColumnMapping is invalid

### ISSUE THREAD

**Issue by maxmanzero** [borisdj/EFCore.BulkExtensions#12]
I am getting this error and was wondering, do I need to implement every column in the database in my entity for this to work?

I have to craft a series of bulk update services for a project, but I only want to pass in a list of the users ids and the new value all the users will be updated to.

Can I not create an entity that doesn't expose all the columns and have BulkUpdate work?

**Comment by maxmanzero** [comment]
Done a little more reading and I think I am mistaken. It looks like it shouldn't matter if my entity only supports a subset of the columns in the table. It should still work. I will keep working.

**Comment by maxmanzero** [comment]
Yes never mind. I am an idiot

Primary key column in db "id"
Property in my entity "Id"

case mismatch

**Comment by borisdj** [comment]
Glad you sort it out.
