### ISSUE TITLE
Transaction (Process ID xx) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

### ISSUE THREAD

**Issue by derodevil** [borisdj/EFCore.BulkExtensions#1204]
I get the above error occasionally when using the method:
```
await context.BulkInsertOrUpdateAsync(entities);
await context.BulkSaveChangesAsync();
```
I wrap it in a dynamic method and bundle it in a .dll file where the .dll is used in many azure functions and pointing to the same SQL Server database.
```
public async Task<List<TEntity>> UpsertManyAsync(List<TEntity> entities)
{
    await context.BulkInsertOrUpdateAsync(entities);
    await context.BulkSaveChangesAsync();
    return entities;
}
```

**Comment by borisdj** [comment]
There are some references in the ReadMe and issue https://github.com/borisdj/EFCore.BulkExtensions/issues/46 has useful suggestions.
