### ISSUE TITLE
BulkReadAsync skip/take example (question)

### ISSUE THREAD

**Issue by geraldbauer** [borisdj/EFCore.BulkExtensions#1206]
I am looking for a BulkReadAsync example that is comparable with a .Skip() and .Take() Linq statements. I want to try BulkReadAsync to see if I can improve our read performance for more than 1.5 million rows of data on a resource that has limited memory, thus the .Skip() and .Take(). Thank you.

**Comment by borisdj** [comment]
Not sure I understand the question.
BulkRead is useful when need to load from DB large list based on Id or some unique column(s).
If you have for example a million in a list you can split it into say 5 sublists and then call BulkRead 5 times for each chunk, similar to Skip/Take 200 K.

**Comment by borisdj** [comment]
There is no example in Docs for this, it is just something that come to mind.
So for given `list` instead of
```C#
context.BulkRead(list);
```
with chunks it would be like:
```C#
var chunkSize = 200000;
var counter = 0;
var totalNumber = list.Count();
do
{
  var sublist = list.Skip(counter  * chunkSize).Take(chunkSize);
  context.BulkRead(sublist);
  counter ++;
} while (totalNumber > (sublist * counter));
```

**Comment by geraldbauer** [comment]
Thank you. Good to know.
