### ISSUE TITLE
How to implement BulkInsertOrUpdateOrDelete with IncludeGraph and non primary columns

### ISSUE THREAD

**Issue by AshK14** [borisdj/EFCore.BulkExtensions#1207]
Hi,
Thanks for creating this library. I have 2 classes with parent - child relationship,

Parent Class.

```C#
public class OrderEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        [StringLength(100)]
        public string OrderNumber { get; set; }

        [StringLength(100)]
        public string UniqueOrderIdentifier { get; set; }

        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }

        [Column(TypeName = "date")]
        public DateTime EndDate { get; set; }

        [InverseProperty("Order")]
        public virtual ICollection<OrderDetailsEntity> OrderDetails { get; set; }
}
```
Child class,

```C#
public class OrderDetailsEntity
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        public long OrderId { get; set; }

        [StringLength(255)]
        public string OrderItemNumber { get; set; }

        [StringLength(255)]
        public string InternalOrderItemNumber { get; set; }

        [StringLength(2500)]
        public string Description { get; set; }

        [Column(TypeName = "decimal(19,2)")]
        public decimal Price { get; set; }

        [ForeignKey(nameof(OrderId))]
        public virtual OrderEntity Order{ get; set; }
    }
```
So `OrderDetailsEntity.OrderId` is a FK to `OrderEntity.Id`
`OrderEntity.UniqueOrderIdentifier` will always be a unique value.

I am able to do `BulkInsert()` this way
```C#
await Context.BulkInsertAsync(entities, operation => operation.IncludeGraph = true);
```

This works perfectly and inserts into both parent and child tables.

However I am facing issues in `BulkInsertOrUpdateOrDeleteAsync()` since I want to be able to Insert or Delete or Update into both of these tables based on these 3 columns: `OrderEntity.UniqueOrderIdentifier`, `OrderDetailsEntity.OrderItemNumber` and `OrderDetailsEntity.InternalOrderItemNumber`

Also not able to understand how I can use `SetSynchronizeFilter<T>` using these 3 columns mentioned above for deletion. I went through ReadMe and some Test cases but not able to figure this out.

Please guide me on how to achieve this. Your help is deeply appreciated.
Thanks

**Comment by borisdj** [comment]
For custom configs like yours, Graph options is not suitable, instead use 2 Bulk ops, one for each table.

Take a look at ReadMe:
_Example of SetOutputIdentity with parent-child FK related tables // Option 1

As for 3 columns use **_UpdateByProperties_** bulkConfig.

SetSynchronizeFilter is used for Partial Sync on table subset using expression set on config with method, example:
`bulkConfig.SetSynchronizeFilter<Item>(a => a.Quantity > 0);`

**Comment by AshK14** [comment]
@borisdj Thanks for the reply. But it is not possible to have a combination of columns from Parent and Child table in `UpdateByProperties` right?
I can implement 2 separate `BulkInsert()` using SetOutputIdentity for `OrderEntity` and `OrderDetailsEntity` and the insertion works fine.

However, I need to implement:

1.  Update or Delete or Insert into Parent Table (OrderEntity) based on column `OrderEntity.UniqueOrderIdentifier`,
2.  Update or Delete or Insert into Child Table (OrderDetailsEntity) based on `OrderEntity.UniqueOrderIdentifier`, `OrderDetailsEntity.OrderItemNumber` and `OrderDetailsEntity.InternalOrderItemNumber`

I am reading input data from a nested JSON and converting into the above entities before Bulk operations.
Maybe the **first requirement** can be fulfilled by using `BulkInsertOrUpdateOrDeleteAsync()` with `UpdateByProperties  = new List<string>  { nameof(OrderEntity.UniqueContractIdentifier) }` and `PropertiesToExclude = new List<string>  { nameof(OrderEntity.Id) }`

But I am not understanding how to meet the **2nd requirement**

Please help me to handle the requirement of Updation or Deletion or Insertion based on the above logic.

**Comment by borisdj** [comment]
For 1. you also set **_SetOutputIdentity_** in config so that IDs are loaded back in memory, and no need to exclude it, since you want it returned. Then with that info you can set child FK _OrderId_ in _OrderDetailsEntity_.
Lastly call `BulkInsertOrUpdateOrDeleteAsync` with UpdateByProperties  = new List<string>  { nameof(OrderEntity.OrderId), nameof(OrderEntity.OrderItemNumber ), nameof(OrderEntity.InternalOrderItemNumber) }

**Comment by AshK14** [comment]
```JSON
{
            "orderNumber": "IRT-21CVW"
            "uniqueOrderIdentifier": "Eqeyrrw==21"
            "startDate": "2023-01-31",
            "endDate": "2023-08-31",
            "isActiveContract": true,
            "orderDetails": [
                {
                    "orderItemNumber": "004N0001-1",
                    "internalOrderItemNumber": "004N00011",
                    "description": "WASHER",
                    "price": 30.8,
                },
                {
                    "orderItemNumber": "012N5108-2",
                    "internalOrderItemNumber": ""113N5108-4",
                    "description": "SCREW NUT",
                    "price": 314.12,
                },
              ]
}
```
Suppose this is the JSON that I initially consumed and inserted to DB. It has one row of `OrderEntity` and two child rows of `OrderDetailsEntity`

Now assume that I get this JSON in the next request,
```JSON
{
            "orderNumber": "IRT-21CVW"
            "uniqueOrderIdentifier": "Eqeyrrw==21"
            "startDate": "2023-01-31",
            "endDate": "2023-08-31",
            "isActiveContract": true,
            "orderDetails": [
                {
                    "orderItemNumber": "004N0001-1",
                    "internalOrderItemNumber": "004N00011",
                    "description": "WASHER",
                    "price": 50.8,
                },
              ]
}
```
So as per this 2nd request, there are no changes to `OrderEntity`. 
But, I need to update `Price` column of first row of `OrderDetailsEntity` and delete the second row of `OrderDetailsEntity` 
Initially on Deserializing this JSON, the `OrderDetailsEntity.OrderId` will be 0. So, how will the above Update and Delete take place on `OrderDetailsEntity` when using `BulkInsertOrUpdateOrDeleteAsync()`?

**Comment by borisdj** [comment]
Once you deserialaze data into OrderEntity list you will call bulk method for for parent list, and it will set Id even whe ntthere is no changes. Then in a loop set OrderId in child objects based on parent Id.
Finaly add all children into a list of OrderDetailsEntity objects and call second Bulk method.

**Comment by AshK14** [comment]
Ohh that's great.. Got it thank you so much 👍

**Comment by borisdj** [comment]
Yes, all not matched based on _UpdateByProperties_ will be deleted, so those will be ones in DB that are not in the input list.
