### ISSUE TITLE
Update to EF Core 2.2

### ISSUE THREAD

**Issue by ErikEJ** [borisdj/EFCore.BulkExtensions#121]

**Comment by JShawnLooney** [comment]
Q: Is there any timeline for supporting EF Core 2.2?  Doing some planning for a project using EF Core 2.2 and will incorporate any estimated timeline into that planning if it exists.  Btw, thanks for the effort on this extension library.  It's much appreciated.

**Comment by JShawnLooney** [comment]
@ErikEJ Thanks for the quick reply.  I'll do a bit more investigation on my end then.  I'm getting package downgrade errors on publish, but no issues on build or running in Debug mode.  I have a multi-project structure which might be causing the errors then.   I'll post details if I solve it.

**Comment by borisdj** [comment]
Dependencies NuGets updated, from version 2.4.2 using EFCore 2.2.
