### ISSUE TITLE
how can i handle multilevel entity update for an existing entry in parent table a new child entry and a new sub child entry in efcore

### ISSUE THREAD

**Issue by github4ebdy** [borisdj/EFCore.BulkExtensions#1210]

**Comment by borisdj** [comment]
Best to use BulkUpdate for each table separately.
Can you write code snipped with example of the use case.

**Comment by github4ebdy** [comment]
> Best to use BulkUpdate for each table separately. Can you write code snipped with example of the use case.

    private Country ModelToEntity(CountryDto model)
        {
            return new Country
            {
                Id = model.Id,
                Code = model.Code,
                CountryName = model.Name,
                Active = model.isActive ?? true,
                StateList = model.StateList == null ? null : model.StateList.Select(x => new State
                {
                    Id = x.Id,
                    Country_Id = model.Id, //FK
                    Code = x.Code,
                    StateName = x.Name,
                    Active = x.isActive ?? true,
                    DistrictList = x.DistrictList == null ? null : x.DistrictList.Select(y => new District
                    {
                        Id = y.Id,
                        State_Id = x.Id, //FK
                        Code = y.Code,
                        DistrictName = y.Name,
                        Active = y.isActive ?? true,
                        CityList = y.CityList == null ? null : y.CityList.Select(z => new City
                        {
                            Id = z.Id,
                            District_Id = y.Id, //FK
                            Code = z.Code,
                            CityName = z.Name,
                            Active = z.isActive ?? true
                        }).ToList(),
                    }).ToList()

                }).ToList()
            };
        }


  var country = ModelToEntity(model);
   updateResponse = await _countryRepository.InsertUpdate(country);

**Comment by borisdj** [comment]
You could try it this way by setting config _InsertGraph_,

but faster would be to call Bulk ops for each table:
await _countryRepository.InsertUpdate(country);
await _countryRepository.InsertUpdate(country.StateList);
var districts = country.StateList.Select(a => a.DistrictList) // join all
await _countryRepository.InsertUpdate(country.StateList);
