### ISSUE TITLE
Does IncludeGraph NOT work with one-to-one relationships?

### ISSUE THREAD

**Issue by pagner** [borisdj/EFCore.BulkExtensions#1211]
```
class GolfCart 
{
        [ForeignKey("FloorPlan")]
        public long? FloorPlan_Id { get; set; }
        public virtual FloorPlan FloorPlan { get; set; }

        // The list works just fine!
        public virtual IList<InventoryLine> InventoryLines { get; set; }
}
```
I do not have any Fluent API configured.
PK's are autogenerated

If I instantiate FloorPlan and run: 

`await _dbContextProvider.GetDbContext().BulkInsertAsync(entities, b => b.IncludeGraph = true);`

I get the error: The MERGE statement conflicted with the FOREIGN KEY constraint "FK_GolfCarts_FloorPlans_FloorPlan_Id". The conflict occurred in database "mydatabase", table "dbo.FloorPlans", column 'Id'.
The statement has been terminated.

If I don't instantiate FloorPlan, InventoryLines are populated and everything is inserted just fine! What am I missing here?

Is there a better approach than using IncludeGraph for one-to-one relationship? 

Thanks!

**Comment by pagner** [comment]
I was able to get this figured out. I didn't see #217 earlier.

I had to BulkInsert FloorPlan first then use the OutputIdentity to set FloorPlan_Id on GolfCart before BulkInserting GolfCart.

Thanks for this awesome library! Closing

**Comment by borisdj** [comment]
Glad you sorted it out.
