### ISSUE TITLE
Not compatible with latest .Net 8 previews

### ISSUE THREAD

**Issue by philipag** [borisdj/EFCore.BulkExtensions#1217]
I tried using this library with the latest .Net 8 preview 7 and am getting some runtime errors.  Is this something supported?  .Net 8 RC is around the corner...

e.g.:  The following runtime error:

Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.EntityFrameworkCore.Metadata.IProperty> Microsoft.EntityFrameworkCore.Metadata.IEntityType.GetProperties()'.

**Comment by Webreaper** [comment]
Also seeing this. Look forward to an 8-compatible version.

**Comment by borisdj** [comment]
Tried to make Prev. with v 8.0.0-preview.7.23375.4
With few changes build passes but can not run test, throws:

> System.MissingMethodException
>   HResult=0x80131513
>   Message=Method not found: 'Void CoreTypeMappingParameters..ctor(System.Type, Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer, System.Func`3<Microsoft.EntityFrameworkCore.Metadata.IProperty,Microsoft.EntityFrameworkCore.Metadata.IEntityType,Microsoft.EntityFrameworkCore.ValueGeneration.ValueGenerator>)'.
>   Source=EntityFrameworkCore.SqlServer.HierarchyId

**Comment by borisdj** [comment]
Have found the issue, entity _HierarchyId_ with prop type **_HierarchyId_** was the cause.

**Comment by borisdj** [comment]
Published **8.0.0-preview.7**
Added multitarget:
_<TargetFrameworks>net8.0;net7.0;net6.0</TargetFrameworks>_

**Comment by Webreaper** [comment]
Thanks!

**Comment by borisdj** [comment]
published v rc.1.2

**HierarchyId** is using _Microsoft.EntityFrameworkCore.SqlServer.HierarchyId_ 
instead of _EntityFrameworkCore.SqlServer.HierarchyId_

MySql now also works since they have released 8.0.0-beta.1
