### ISSUE TITLE
Postgres CREATE INDEX CONCURRENTLY issue

### ISSUE THREAD

**Issue by Puhplant** [borisdj/EFCore.BulkExtensions#1218]
I am trying to BulkInsertOrUpdate some data using Postgres, but I am coming up against the exception below.
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/48070969/3109b988-01b2-42a0-b174-471e3bb3aa3d)
I see in the documentation it says that this will occur if I don't have unique index in my Db on the fields specified with UpdateByProperties already.

> Also with PostgreSQL when matching is done it requires UniqueIndex so for custom UpdateByProperties that do not have Un.Ind., it is temporarily created in which case method can not be in transaction (throws: current transaction is aborted; CREATE INDEX CONCURRENTLY cannot run inside a transaction block).

However, I do have a unque index on these fields.
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/48070969/c47472ec-508a-49f2-a05d-98b0c2985b3c)
 I was wondering what I am doing wrong here?

**Comment by Puhplant** [comment]
So a bit more information. I am using Postgres 15.3, EF Core 7.0.10, Npgsql 7.0.4 and EfCore.BulkExtensions 7.1.5.  From doing a little digging in the source code the issue seems to be located in the way that EF Core is creating the unique index. It is just doing that (creating the unique index), but not also creating a unique constraint so when BulkExtensions is looking for an existing constraint, one does not exist despite a perfectly valid unique index being there. 
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/48070969/9d425dc0-fbac-42e7-973c-08c491c2f593)

**Comment by Puhplant** [comment]
Perhaps something like this could for the bases for a unique index check?

`	select idx.relname as index_name, 
       insp.nspname as index_schema,
       tbl.relname as table_name,
       tnsp.nspname as table_schema,
	   a.attname as column_name
from pg_index pgi
  join pg_class idx on idx.oid = pgi.indexrelid
  join pg_namespace insp on insp.oid = idx.relnamespace
  join pg_class tbl on tbl.oid = pgi.indrelid
  join pg_namespace tnsp on tnsp.oid = tbl.relnamespace
  Join pg_catalog.pg_attribute a on idx.oid = a.attrelid
where pgi.indisunique --<< only unique indexes
  and tnsp.nspname = 'public'
  and tbl.relname = 'TransmissionGroups'`

**Comment by borisdj** [comment]
Firstly as mentioned in the ReadMe cant be used inside a transaction.
Explicit Constrain is also required for matched to be done, so you should have both set UniqueIndex and Constrain.
So you should create constrain if one does no exist in order to use it this way.

**Comment by Puhplant** [comment]
I am a little disappointed that you won't consider supporting having a Unique index without a Constraint since this is now the default approach from entity framework. It seems to me that having to write custom SQL to managed the creating of constraints outside of the standard entity framework migration building is quite onerous considering that it could be fixed fairly easily within the EF Bulk Extensions library. 

I would be willing to make the required changes if you are open to contributions?

**Comment by borisdj** [comment]
The issue is not willingness for support but feasibility.
As I recall pure Sql with OnConflict on Postgres requires both being set.

**Comment by borisdj** [comment]
Or did you mean it to work in a way that it temporarily creates only Constrain?
That might be the solution.
Always open for contribs, try to fix it, write/extend Test also, and make a PR.
