### ISSUE TITLE
IncludeGraph with BulkInsertOrUpdateOrDelete

### ISSUE THREAD

**Issue by Felipe379** [borisdj/EFCore.BulkExtensions#1226]
So, I have a 1:N relationship and I wanted to use the "BulkInsertOrUpdate" to fill the database.

An example is
**CarsManufacturers** 1 - N **CarsInproduction**

If I need to fill those tables, from what I've read all I would need to do is to set the option `IncludeGraph = true`.
However, the data to fill those tables needs to be read from several files and due to their size, they need to be read in chunks.

So say as in the first the ManufacturerA have the cars X1, Y1, Z1 and ManufacturerB have the cars X2, Y2, Z2 in production this year.
In next year the cars X1 from ManufacturerA and X2 from ManufacturerB are no longer in production and I need those to be removed from the table.

Using "BulkInsertOrUpdate" won't remove those from the database. The solution would be to use "BulkInsertOrUpdateOrDelete" to remove those entries from the table "CarsInproduction", but since there are multiple files to read the data from and I need to read those in chunks, I often keep getting the error
`The MERGE statement conflicted with the FOREIGN KEY constraint`. From what I could understand (please correct me if I'm wrong), this happens because neither of the Manufacturer or any of it's cars from the database are present in the current chunk that's being read.

When there is data on the database, changing all of the CarsInproduction from a specific Manufacturer, you can also get the error `The given key 'EFCore.BulkExtensions.PrimaryKeysPropertyColumnNameValues' was not present in the dictionary.` using the "BulkInsertOrUpdateOrDelete".

Is there a way to accomplish what I need using this package? In short it would be an Insert/Update the main table, while the relationship would need to be an Insert/Update/Delete

**Comment by borisdj** [comment]
You can't mix method when using Graph option, so it's best to call Bulk ops separately for each table.
Check out ReadMe segment: _Example of SetOutputIdentity with parent-child FK related tables - Option 1 (recommended)_

**Comment by altso** [comment]
@borisdj I am also looking for an ability to mix and match Insert/Update with Insert/Update/Delete operations based on the type of the relationship. Would be nice to have this available.
