### ISSUE TITLE
Differences using separate bulk commands vs combined.

### ISSUE THREAD

**Issue by gijsstrik** [borisdj/EFCore.BulkExtensions#1228]
**Switched back to version 7.13. All my issues where gone!!!!!!!**

Use .net 7 console app with sql database.

These are 2 examples of encountered problems.
Sometimes I can prevent errors by not using BulkInsertOrUpdateOrDeleteAsync but separate BulkDeleteAsync and BulkInsertOrUpdateAsync.
But with other tables it is the opposite.

Simple table1 of 2 columns with a key named Idx but not an identity key.

var records = await dbSource.table1.AsNoTracking().ToListAsync(cancellationToken: stoppingToken);

await dbTarget.BulkDeleteAsync(records, cancellationToken: stoppingToken);
await dbTarget.BulkInsertOrUpdateAsync(records, cancellationToken: stoppingToken);
Cannot insert the value NULL into column 'Idx', table 'PortalWebTestSync.dbo.ControlType'; column does not allow nulls. UPDATE fails.

await dbTarget.BulkInsertOrUpdateOrDeleteAsync(records, cancellationToken: stoppingToken);
No errors!

Simple table2 of 4 columns and a composite key of 2 varchars.
For the test I added a record in the target table that should be deleted after a bulkdelete.

Record is not deleted in separate bulkdelete but is deleted in combination of bulk insert,update,delete.

Count before source :1694
Count before target :1695

var records = await dbSource.table2.AsNoTracking().ToListAsync(cancellationToken: stoppingToken);

await dbTarget.BulkDeleteAsync(records, cancellationToken: stoppingToken);
await dbTarget.BulkInsertOrUpdateAsync(records, cancellationToken: stoppingToken);

Count after bulkdelete and bulkinsertorupdate source :1694
Count after bulkdelete and bulkinsertorupdate target :1695

await dbTarget.BulkInsertOrUpdateOrDeleteAsync(records, cancellationToken: stoppingToken);

Count after bulkinsertorupdateordelete source :1694
Count after bulkinsertorupdateordelete target :1694

**Comment by borisdj** [comment]
Can you write entire test for table1 usecase.
