### ISSUE TITLE
BatchDelete throw exception with datatime conversion

### ISSUE THREAD

**Issue by sonphnt** [borisdj/EFCore.BulkExtensions#123]
Hi,

I am trying to use BatchDelete with the code like this and get exception "onversion failed when converting date and/or time from character string."

```
DateTime compareDate = DateTime.Now.AddDays(-7);
await _logRepo.TableNoTracking.Where(x => x.Logged < compareDate).BatchDeleteAsync();
```

What is the correct way of using BatchDelete without loading data?

Thanks

**Comment by borisdj** [comment]
Could you give more info of this Entity and test code for reproducing the Exception.
I have changed _EFCoreBatchTestAsync.cs_ in the following way it passed successfully:

In _BatchTestAsync_ method Replaced:
`Assert.Equal(500, context.Items.LastOrDefaultAsync().Result.ItemId);`
`Assert.Equal("Updated", context.Items.LastOrDefaultAsync().Result.Description);`
with
`Assert.Equal(500, context.Items.Count());`

And in RunBatchDelete replaced:
`await context.Items.Where(a => a.ItemId > 500).BatchDeleteAsync();`
with
`DateTime compareDate = DateTime.Today.AddDays(1);`
`await context.Items.Where(a => a.TimeUpdated > compareDate).AsNoTracking().BatchDeleteAsync();`

Also in _RunInsert_
`TimeUpdated = DateTime.Now.AddDays(i / 501),`

**Comment by sonphnt** [comment]
Hi. Sorry for forgetting this. Error Detail:
"Conversion failed when converting date and/or time from character string."

`"   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)\r\n   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)\r\n   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)\r\n   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)\r\n   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.ExecuteSqlCommandAsync(DatabaseFacade databaseFacade, RawSqlString sql, IEnumerable`1 parameters, CancellationToken cancellationToken)\r\n   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync[T](IQueryable`1 query)\r\n"`

**Comment by sonphnt** [comment]
I am not sure what extension does but I guess BatchDeleteAsync must have done something with DateTime conversion. Maybe region issue?. I am not using US region?
