### ISSUE TITLE
Deprecated dependency

### ISSUE THREAD

**Issue by sofiyanguyen** [borisdj/EFCore.BulkExtensions#1232]
EntityFrameworkCore.SqlServer.HierarchyId is a direct dependency of this package and is shown as deprecated on nuget.org: [HierarchyId](https://www.nuget.org/packages/EntityFrameworkCore.SqlServer.HierarchyId)

 Microsoft.EntityFrameworkCore.SqlServer.HierarchyId has been suggested by the package owner as a maintained alternative.

**Comment by borisdj** [comment]
Fixed with v8
