### ISSUE TITLE
Provider type is passed where .NET type is expected

### ISSUE THREAD

**Issue by ArneMancofi** [borisdj/EFCore.BulkExtensions#1262]
In [`BatchUtil.GetSqlSetSegment()`](https://github.com/borisdj/EFCore.BulkExtensions/blob/89e3ff2d0516a0d1e640758830b9826a451228e5/EFCore.BulkExtensions/Batch/BatchUtil.cs#L352C25-L352C45) around line 352, the value to update to is converted to the provider type:
```c#
propertyUpdateValue =
  tableInfo.ConvertibleColumnConverterDict[columnName]
    .ConvertToProvider.Invoke(propertyUpdateValue);
```
Later, around [line 363ff](https://github.com/borisdj/EFCore.BulkExtensions/blob/89e3ff2d0516a0d1e640758830b9826a451228e5/EFCore.BulkExtensions/Batch/BatchUtil.cs#L363C1-L367C36), this value is passed to `TryCreateRelationalMappingParameter()`:
```c#
IDbDataParameter? param = TryCreateRelationalMappingParameter(
  columnName,
  parameterName,
  propertyUpdateValue,
  tableInfo);
```
which around [line 689](https://github.com/borisdj/EFCore.BulkExtensions/blob/89e3ff2d0516a0d1e640758830b9826a451228e5/EFCore.BulkExtensions/Batch/BatchUtil.cs#L689) is passed to `RelationalTypeMapping.CreateParameter()`:
```c#
return relationalTypeMapping?.CreateParameter(
  dbCommand, parameterName, value, propertyInfo?.IsNullable);
```

**Question:** Shouldn't the value passed to `.CreateParameter()` be of the .NET type, rather than of the provider type?

Note: The [`.CreateParameter()`](https://github.com/dotnet/efcore/blob/77bca9996f1f987ac6207b6d5d8a998f1000f06f/src/EFCore.Relational/Storage/RelationalTypeMapping.cs#L565C1-L569C1) method contains this code:
```c#
if (Converter != null)
{
  value = Converter.ConvertToProvider(value);
}
```

**Comment by borisdj** [comment]
Not sure, did you get any exception because of this.
Also to note that Batch ops are Deprecated from EF8 since EF7+ has native Execute-Up/Del.

**Comment by ArneMancofi** [comment]
Thanks for responding, and thanks for your good work!

Yeah, unfortunately, we won't be using EF7, and upgrading to EF8 is some time in the future for us 😢 

My problem is that we cannot use batch update for fields of type NodaTime.Instant, that map to the SQL type DateTime2, I think, and probably transported as a DateTime .NET type.

**Comment by borisdj** [comment]
Can you write a test for this.
Also if you think to have a fix make a PR as well.

**Comment by ArneMancofi** [comment]
OK, so I had another look at this 😃 

## Unit test

It turns out there already is a unit test of batch updating field types configured with value converters: `ValueConverterTests.BatchUpdate_EntityUsingBuiltInEnumToStringConverter_UpdatesDatabaseWithEnumStringValue()`.

If you run it in the debugger, breaking on exceptions, you will find that an exception is thrown from the call to `CreateParameter()` in `BatchUtil.TryCreateRelationalMappingParameter()` around line 689:
```c#
try
{
    var relationalTypeMapping = propertyInfo?.GetRelationalTypeMapping();

    using var dbCommand = new SqlCommand();
    return relationalTypeMapping?.CreateParameter(dbCommand, parameterName, value, propertyInfo?.IsNullable);
}
catch (Exception) { }
```
with the text
> System.InvalidCastException: Invalid cast from 'System.String' to 'EFCore.BulkExtensions.Tests.ValueConverters.VcEnum'

This is caught by the `catch` block and ignored.

The reason why the unit test succeeds is because `null` is then returned, and the calling code then creates a parameter manually:
```c#
if (sqlParameter == null)
{
    sqlParameter = new SqlParameter(paramName, value ?? DBNull.Value);
    var columnType = columnName is null ? null : tableInfo?.ColumnNamesTypesDict[columnName];
    if (value == null
        && (columnType?.Contains(DbType.Binary.ToString(), StringComparison.OrdinalIgnoreCase) ?? false)) //"varbinary(max)".Contains("binary")
    {
        sqlParameter.DbType = DbType.Binary; // fix for ByteArray since implicit conversion nvarchar to varbinary(max) is not allowed
    }
}
```

## Suggested remedy

In `BatchUtil.AddSqlParameter()`, you could remove the lines around 641ff:
```c#
if (columnName != null && (tableInfo?.ConvertibleColumnConverterDict.TryGetValue(columnName, out var valueConverter) ?? false))
{
    value = valueConverter.ConvertToProvider.Invoke(value);
}
```
If you do this, the exception will no longer be thrown (and ignored).

**Comment by borisdj** [comment]
Trying to add this fix, is your suggestion to remove the IF clause, or ?
Maybe batter to extend it for this use case if you know the condition.

**Comment by ArneMancofi** [comment]
It has been some time since I took a look at this code, but I seem to remember the suggestion was to remove the `if` statement and its body.

**Comment by borisdj** [comment]
You can't just comment out IF line since there _valueConverter_ is instantiated.

**Comment by ArneMancofi** [comment]
Ah, well if it is needed elsewhere, you could instead just remove the body of the `if` statement.

**Comment by borisdj** [comment]
I have made some workaround for this, new v. will be published tomorrow.
