### ISSUE TITLE
Does not set identity

### ISSUE THREAD

**Issue by gijsstrik** [borisdj/EFCore.BulkExtensions#1263]
I have a table with a identity column that is not the key. The table has a Guid key.
Bulkconfig.SetOutputIdentity = false
bulkConfig.SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity

Insert (BulkInsertOrUpdateOrDeleteAsync) terminates with error: Cannot insert explicit value for identity column in table '...' when IDENTITY_INSERT is set to OFF.

If I exclude the identity column (bulkConfig.PropertiesToExclude = ....) the insert does not fail but a new identity is generated.
But I need the identity value from the source table??
How??

**Comment by borisdj** [comment]
Can you write a test sample where the issue would be reproducible.
I have made this entity for it:

```C#
public class ItemTest
{
    [Key]
    public Guid ItemTestGid { get; set; }

    public int ItemTestIdent { get; set; } // with fluent Api: modelBuilder.Entity<ItemTest>().Property(p => p.ItemTestIdent ).ValueGeneratedOnAdd();

    [MaxLength(50)]
    public string? Name { get; set; }
}
```

**Comment by videokojot** [comment]
@gijsstrik  I have added test scenario for you issue to MIT fork of this repository (where I fixed multiple issues fixed in original).

GitHub: https://github.com/videokojot/EFCore.BulkExtensions.MIT
NuGet: https://www.nuget.org/packages/EFCore.BulkExtensions.MIT

and following test passes (so I either fixed your issue or  I am unable to replicate).
If you provide failing example I think I can fix it.
``` csharp

// Used example entity from borisdj's comment above:
public class Entity_KeyDifferentFromIdentity
{
    [Key] public Guid ItemTestGid { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int ItemTestIdent { get; set; } // with fluent Api: modelBuilder.Entity<ItemTest>().Property(p => p.ItemTestIdent ).ValueGeneratedOnAdd();

    public string? Name { get; set; }
}
```
Passing test scenario:
``` csharp

    /// <summary>
    /// Covers: https://github.com/borisdj/EFCore.BulkExtensions/issues/1263
    /// </summary>
    [Theory]
    [InlineData(DbServerType.SQLServer)]
    public void IUD_KeepIdentity_IdentityDifferentFromKey(DbServerType dbType)
    {
        var item = new Entity_KeyDifferentFromIdentity()
        {
            ItemTestGid = Guid.NewGuid(),
            ItemTestIdent = 1234,
            Name = "1234",
        };

        using (var db = _dbFixture.GetDb(dbType))
        {
            var items = new[] { item, };
            db.BulkInsertOrUpdateOrDelete(items, c => { c.SqlBulkCopyOptions = SqlBulkCopyOptions.Default | SqlBulkCopyOptions.KeepIdentity; });
        }

        using (var db = _dbFixture.GetDb(dbType))
        {
            var insertedItem = db.EntityKeyDifferentFromIdentities.Single(x => x.ItemTestGid == item.ItemTestGid);
            Assert.Equal(1234, insertedItem.ItemTestIdent);
        }
    }


```
