### ISSUE TITLE
BulkInsert with SetOutputIdentity doesn't set entities ID's

### ISSUE THREAD

**Issue by MauriceChocoSwiss** [borisdj/EFCore.BulkExtensions#1270]
Hi, 
After a long search I've found that the commit https://github.com/borisdj/EFCore.BulkExtensions/commit/27407aae3e24ee337fc916bd1d653045c54cb066 that change the IList to IEnumerable, especially in TableInfo.cs method "UpdateEntitiesIdentity" (and consequences, the .Clear() on IList isn't available on IEnumerable) broke the updating of entities list ID's. 
The entities = new List<T>() broke the reference of entities list.

Can you make a fix for this, by returning the entities list of this method for exemple or go back on IList ?

**Comment by MauriceChocoSwiss** [comment]
Your test don't pass on EFCore 7.0 for SqlServer (I use) because of "gen_random_uuid" is not a valid integrated function name. 

This is the bulkInsertAsync with options I've used.
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/23436049/552c2ab0-d4a9-4ad0-b59f-8bc378c2e7b9)

If i debug your extension with my case, after the UpdateEntitiesIdentity in the TableInfo.cs, I can clearly see the enties hasn't ID's after the method when the entitiesWithOutputIdentity has ID's.

Maybe it's a async BulkInsert method related only ?

**Comment by borisdj** [comment]
The issue is caused with combination _PreserveInsertOrder = false;_
Why do you not leave it True ?

Anyway fix would be change `entities = new List<T>();` to `((List<T>)entities).Clear();`

And "gen_random_uuid" config is under IF: _if (Database.IsNpgsql())_

**Comment by MauriceChocoSwiss** [comment]
Yes I know in case of PreserveInsertOrder, it pass by the IF statement. I set it to false to make a Merge instead of Insert and prevent table locking from my memory. I've tried many config and this one work like we want :) 

Ok, I let you do what you this is the best for. (It work for my case ;) )

Ok for the SQL method ;)

Anyway, you can fix your test too ? To be sure to not set ItemId before insert it and check it was correctly set ?

**Comment by borisdj** [comment]
When you configure SetOutputIdentity to True then Merge is used, so no need to change PreserveInsertOrder.
 
And Test does not set ItemId prior to call.

**Comment by MauriceChocoSwiss** [comment]
Ok maybe. I've made that months ago and if I remember well it's because of my case as children of same type as parent but didn't set the parentId property (from my own) properly. 

![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/23436049/f16c94ec-9d16-4b62-b75b-0fadae0ad49b)
here is the picture of the test I run, it set the ItemId if bulk. (it was true during the test of bulk insert)

**Comment by borisdj** [comment]
Yes, I looked at non Async but in async one it was being set, will comment out that also.

**Comment by MauriceChocoSwiss** [comment]
Be careful, you set the ItemId in other tests in non async too. 

Thank you for your help
