### ISSUE TITLE
compatibility with .net 7

### ISSUE THREAD

**Issue by gawronCode** [borisdj/EFCore.BulkExtensions#1272]
Hi i was having a problem with your library when used in .net 7 project with entity framework core 7.
Every time i used method BulkInsertAsync i was getting exception: "could not load type 'microsoft.data.sqlclient.server.ibinaryserialize' from assembly 'microsoft.data.sqlclient, version=5.0.0.0, culture=neutral, publickeytoken=23ec7fc2d6eaa4a5"

This problem was mentioned before in this thread:
https://github.com/borisdj/EFCore.BulkExtensions/issues/934

I downloaded your code and find out that the problem is occuring because of InnerGetDataTablemethod in SqlServerAdapter.cs
It seems that there is a problem with code that deal with property type HierarchyId. When i comment this code out everything works fine.

**Comment by borisdj** [comment]
Latest version is multitarget: .net 8/7/6 ,
v7 is using _EntityFrameworkCore.SqlServer.HierarchyId_ while
v8 is using Microsoft.EntityFrameworkCore.SqlServer.HierarchyId
