### ISSUE TITLE
EntityFrameworkCore.SqlServer.HierarchyId is deprecated for net 6.0 and net 7.0

### ISSUE THREAD

**Issue by RiantoFK** [borisdj/EFCore.BulkExtensions#1277]
Hi, we are using BulkExtensions in our application running NET 6.

There is an issue with the EntityFrameworkCore.SqlServer.HierarchyId in NET 6 and NET 7.
I saw you fix for NET 8, can you please update the library reference targeted for NET 6 and NET 7.

Thanks a lot!

**Comment by borisdj** [comment]
Are you sure .Net 6 is compatible with new version?
There is only version 8 in existance from this year:
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer.HierarchyId/8.0.0-preview.5.23280.1

**Comment by RiantoFK** [comment]
You are right. We cannot use Microsoft.EntityFrameworkCore.SqlServer.HiercarchyId for NET 6 or 7. Thanks for checking!
I will find alternative library for NET 6.
