### ISSUE TITLE
PostgersSqlAdapter adds "public" scheme prefix to temp table

### ISSUE THREAD

**Issue by MIKron1991** [borisdj/EFCore.BulkExtensions#1283]
Hello!

I want BulkInsertAsync to temp table generated before (in same transaction), for example, #my-temp (dbcontext setup for entity, table name specified to #my-temp). But when i call BulkInsertAsync i received sql with "INSERT [pubic].[#my-temp] ..." and then error. Is there any way to solve my case ?

**Comment by borisdj** [comment]
When using temp tables you need transation:
```C#
using var transaction = context.Database.BeginTransaction();

var config = new BulkConfig { CustomDestinationTableName = "#my-temp" };
context.Database.ExecuteSqlRaw(sqlCreateTableCopy);
context.BulkInsert(entities, config);

transaction.Commit();
```
