### ISSUE TITLE
Batch Size

### ISSUE THREAD

**Issue by jculverwell** [borisdj/EFCore.BulkExtensions#13]
Thank you kindly for this library.  

Previously I was using http://entityframework-extensions.net/?z=codeplex which had the ability to specify a batchSize.  I found this was essential for my project as sometimes we need to insert millions of records which will fail unless we can batch them up.  Any chance of adding BatchSize to this library?

**Comment by borisdj** [comment]
Yes, since it already has BatchSize internally, I just have to expose it in BulkConfig.
I will do it in a few days.

**Comment by jculverwell** [comment]
Thanks Boris,  really appreciate your help.

**Comment by borisdj** [comment]
BatchSize added in Config.

**Comment by jculverwell** [comment]
Thank you
