### ISSUE TITLE
BulkRead throw exception "There is already an object named '#TableTemp78fdb037' in the database"

### ISSUE THREAD

**Issue by alansousa** [borisdj/EFCore.BulkExtensions#130]
When I tried to use BulkRead to my class `Order`, like this, its works:
```c#
public class Order
{
    public int StatusId {get;set; }
    public DateTime StatusUpdated {get;set;}
}
```

But when I change to use a ValueObject, like this:

```c#
public class Order
{
    public Status Status {get;set; }
}

public class Status
{
    public int StatusId {get;set; }
    public DateTime StatusUpdated {get;set;}
}
```

BulkRead throw exception "There is already an object named '#TableTemp78fdb037' in the database"

I've tried with TempDB true and false, and got the same exception.

**Comment by borisdj** [comment]
For reproducing the issue easier, please write entire code of these Entity classes, than code of OnModelCreating method if columns have some custom config there and also code how you called BulkRead.

When using TempDB  you should put BulkRead inside transaction:
There is remark about this in README:
> For _BulkInsertOrUpdate_ when **UseTempDB** is set then BulkOperation has to be inside [Transaction](https://github.com/borisdj/EFCore.BulkExtensions/issues/49).

**Comment by alansousa** [comment]
I posted the example with TempDB, but I tried with and without tempDB and got the same error.

**Comment by borisdj** [comment]
Then post all code for reproducing this:

> If the issue still remains for reproducing it, please write entire code of these Entity classes, than code of OnModelCreating method if columns have some custom config there and also code how you called BulkRead.
