### ISSUE TITLE
.NET 8 NuGet support

### ISSUE THREAD

**Issue by Liebeck** [borisdj/EFCore.BulkExtensions#1316]
.NET 8 has been released. At the moment, the latest version of EFCore.BulkExtensions is 8.0.0-rc.1.2 which is on a prerelease channel.

Could you please release a .NET 8 compatible stable release on NuGet? Thank you!

**Comment by LeDahu22** [comment]
Hi @borisdj , 
Any update on this topic ? 
Thank you for your work !

**Comment by marklagendijk** [comment]
We have chosen to replace this library with our own custom code.
I think the real power of this library is performance when working with really large datasets (I haven't tested this, but I assume it outperforms EF greatly for such cases).

For a lot of other cases it is often quite simple to replace this library with regular EF code.

Take this example for doing an insert or update of a list of (untracked) entities:
```c#
public interface IEntityWithId
{
    int Id { get; set; }
}

public static class EntityWithIdDbSetExtensions
{
    public static void AddOrUpdateRange<T>(this DbSet<T> dbSet, List<T> entities)
        where T : class, IEntityWithId
    {
        var ids = entities.Select(entity => entity.Id).ToList();
        var existingIds = dbSet.WhereIdIn(ids).Select(entity => entity.Id).AsNoTracking().ToList();
        entities.ForEach(entity =>
        {
            if (existingIds.Contains(entity.Id))
                dbSet.Update(entity);
            else
                dbSet.Add(entity);
        });
    }
}
```

Updating specific properties can be done by first calling `Attach` and then setting `IsModified` for the specific properties. This could even be done in a similar generic way:

```c#
public static class EntityWithIdDbSetExtensions
{
    public static void UpdateIncludedPropertiesOfRange<T>(this DbSet<T> dbSet, List<T> entities, List<string> propertiesToInclude)
        where T : class, IEntityWithId
    {
        entities.ForEach(entity =>
        {
            var entry = dbSet.Attach(entity);
            propertiesToInclude.ForEach(property => entry.Property(property).IsModified = true);
        });
    }
}
```

It is always good to review now and then whether you actually need a certain dependency.
When we did this, we found out that this library was not worth it for us.

**Comment by LennardF1989** [comment]
There is a prerelease NuGet package that works fine with .NET 8.

**Comment by Xor-el** [comment]
> There is a prerelease NuGet package that works fine with .NET 8.

@LennardF1989  That is the main NuGet for all Databases, the specific ones with single providers like `EFCore.BulkExtensions.SqlServer` are yet to be updated.

**Comment by borisdj** [comment]
New Nuget published v8.0.0 for each provider
And for only MySQL it is named: 8.0.0-beta.1 because mysql provider is still in beta version.

**Comment by LeDahu22** [comment]
@borisdj  now that Pomelo.EntityFrameworkCore.MySql has been release as GA for .NET 8, can you update your package to use the latest version ?
Thank you !

**Comment by borisdj** [comment]
Published production nuget for MySQL as well.
