### ISSUE TITLE
Provider separation

### ISSUE THREAD

**Issue by WinInsider** [borisdj/EFCore.BulkExtensions#1318]
While this project provides a lot value to many, there are many database providers, currently BulkExtensions supports four (SQL, SQLite, MySQL and PostgreSQL).  Most consumers are on one database engine, while this package pulls in a lot dependencies for all other database engines.  Would it be a lot of effort to separate codebase into provider specific assemblies/nuget packages?  This way, if there was necessary code architecture, others in the community could make BulkExtensions work for currently not supported database engines.

**Comment by Xor-el** [comment]
Hello @WinInsider I think this is already possible. 
Please see here
https://github.com/borisdj/EFCore.BulkExtensions#installation
