### ISSUE TITLE
Is there a way to use only Date in BulkRead?

### ISSUE THREAD

**Issue by alansousa** [borisdj/EFCore.BulkExtensions#133]
Hi,

I'm using a DateTime property as parameter in BulkRead, but I need to compare only Date of a property.
Is it possible?

**Comment by borisdj** [comment]
I not sure I understand your requirement, could you give example of what and how you want to read data.
BulkRead works in a way that you send entity list with UniqueKey values.
Those UniqueKey values can be one PK column or several other columns that usually have UniqeIndex but you need exact value for each of those columns.
So if one of those columns is DateTime type, it can have value with time part 00:00 but that's not ignored.
If you need rows with datatime in a period, for example in one day, that you need to use WHERE
`Where(a => a.Date >= today && a.Date < today.AddDays(1))`, and not BulkRead.

**Comment by alansousa** [comment]
In my scenario I need to get a list by columns like a **DateTime**, **Price** and **CustomerCode** as unique, and check with data in another system where seconds value are never equal, but checking only Date part works for me.
