### ISSUE TITLE
Link to license page is broken.

### ISSUE THREAD

**Issue by aniliht** [borisdj/EFCore.BulkExtensions#1338]
In README.md and LICENSE.txt a link is listed for licensing.  But it returns a Not Found page.

https://www.codis.tech/efcorebulk/

![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/15676195/fb4120ef-fa8e-42cf-b30d-d741a0c01906)

**Comment by borisdj** [comment]
Try
[https://codis.tech/efcorebulk/](https://codis.tech/efcorebulk/)
