### ISSUE TITLE
 BatchUpdateAsync<T>(this IQueryable<T> query, Expression<Func<T, T>> updateExpression）change to efcore 8

### ISSUE THREAD

**Issue by ByZhouhang** [borisdj/EFCore.BulkExtensions#1339]
in my project ,i use like this:

`
 await _repository.BatchUpdateAsync<Subejct>(t => t.SiteId== siteId, u => new Subejct() { xx= xxx});
`

i want to use  .net 8  but found  [Obsolete("As of EF 7 there are native method ExcuteUpdate.")]
 efcore 8  official write like this

`
context.Blogs
    .Where(b => b.Rating < 3)
    .ExecuteUpdate(setters => setters.SetProperty(b => b.IsVisible, false));
`

How can I switch to a new way of writing without affecting the code I wrote before?( change BatchUpdateAsync  to ExecuteUpdate )

**Comment by borisdj** [comment]
You can still technically _BatchUpdate_, just ignore Deprecated comment.
And if want to change to _ExecuteUpdate_ then need to refactor.
