### ISSUE TITLE
Bulk upsert fails with BulkConfig.UpdateByProperties and another identity column

### ISSUE THREAD

**Issue by paillave** [borisdj/EFCore.BulkExtensions#134]
With such a table

```SQL
create table MyTable(
     Id int identity(1,1) not null primary key,
     BusinessKey nvarchar(50) null,
     IrrelevantPropertyHere nvarchar(50) null,
)
```

I make the following:
```CSharp
dbContext.BulkInsert(toSave, new new BulkConfig
{
     PreserveInsertOrder = true,
     SetOutputIdentity = true,
     BatchSize = items.Count,
     UpdateByProperties = new []{"BusinessKey"},
     TrackingEntities = false
});
```
I get an exception saying the the `Id` property cannot be set.

After reviewing the code, it seem that it is because the system assumes that no other property except what is mentioned in `UpdateByProperties` can be an `identity`:

https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/TableInfo.cs#L85

https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/TableInfo.cs#L232

Moreover the query builder doesn't seem to take this situation in consideration:
https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/SqlQueryBuilder.cs#L83-L87

Maybe I am missing something?
For now I will try to work on a fix at my side, but if you can solve it faster than me, or tell me that I'm an idiot because I didn't read correctly the documentation I'd be very happy.

**Comment by borisdj** [comment]
Set also PropertiesToExclude = new List { nameof(Student.Id) }

**Comment by paillave** [comment]
This workaround works, but I made an amendment at my side on a fork that takes it in consideration automatically. FYI, instead of doing this:
https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/TableInfo.cs#L214

you could do this instead:
string IdentityColumn = entityType.GetProperties().FirstOrDefault(i => i.SqlServer().ValueGenerationStrategy == SqlServerValueGenerationStrategy.IdentityColumn)?.Name;
