### ISSUE TITLE
IncludeGraph and CalculateStats: StatsInfo returns only counts of last processed batch

### ISSUE THREAD

**Issue by fretje** [borisdj/EFCore.BulkExtensions#1340]
When using BulkImportOrUpdate with both IncludeGraph and CalculateStats set to true, the stats aren't calculated right.
They seem to only return the stats of the last processed batch.

I've updated the Test `IncludeGraphTests.BulkInsertOrUpdate_EntityWithNestedObjectGraph_SavesGraphToDatabase` and added CalculateStats = true, and the resulting `bulkConfig.StatsInfo.StatsNumberInserted` equals 4, while it should be 12.

I think I know how to tackle this one... I'll create a pull request shortly...

**Comment by borisdj** [comment]
PR merged, thx for contrib.
