### ISSUE TITLE
[.NET 8] Using two providers packages in the same project

### ISSUE THREAD

**Issue by LeDahu22** [borisdj/EFCore.BulkExtensions#1342]
Hi,

My .NET 8 MAUI project uses two kind of databases (SQL Server for remote, and SQLite for local).

I'm currently using EFCore.BulkExtensions main nuget package.

I've tried to replaced it by both EFCore.BulkExtensions.SqlServer and EFCore.BulkExtensions.Sqlite packages (as I don't care about MySQL or PostgreSQL). 

When trying to use both in the same service, I ran into a namespace conflict issue, when using BulkConfig (as this class is present in both package).

So my guess is that unless I separate both contexts in different projects (which doesn't suit my needs), I won't be able to use these specific packages and I have to keep on using the main one.

The other issue is that the .NET 8 main version of the package still uses Pomelo.EntityFrameworkcore.Mysql for .NET 7 (this package won't be fully migrated to .NET 8 until the end of the month, at least).

This is preventing the AOT compilation of my MAUI app in Release mode, and I'm unable to fully migrate to .NET8.
What if I install manually Pomelo.EntityFrameworkcore.Mysql v8 beta ? Will EFCore.BulkExtensions handle it ? (I don't intend to use MySQL anyway).

I hope my question is clear.

Thank you.

**Comment by borisdj** [comment]
Yes, for multiple usage main package with all providers needs to be used.
Until mysql is fully release for .Net8 you could import entire Bulk project with source code in your project, and there update mysql to beta. Once it gets updated then just replace source with nuget.
