### ISSUE TITLE
What should be the maximum number of rows be passed to BulkInsertAsync?

### ISSUE THREAD

**Issue by ShaonDey** [borisdj/EFCore.BulkExtensions#1344]
Specifiaction:
```
<TargetFramework>net6.0</TargetFramework>
<PackageReference Include="EFCore.BulkExtensions" Version="6.5.6" />
<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="6.0.10" />
````

I have a HUGE (1,000,000 Rows) amount of data that needs to be inserted into the database (`SQL Server`). I wish to do it in batches. What should be each batch size?

**Comment by ShaonDey** [comment]
`context.BulkInsertAsync(list, new BulkConfig { BatchSize = batchSize }, cancellationToken: cancellationToken);`

So this is good enough? Or should I consider any more configurations?

**Comment by borisdj** [comment]
Actually first idea was to call BulkInsert a few times:
```C#
context.BulkInsertAsync(list1);
context.BulkInsertAsync(list2);
//...
```
But this probably is not needed for 1 million rows.

As for the config BatchSize is has default values of 2000, you could try with 5000 or 10000.
https://stackoverflow.com/questions/779690/what-is-the-recommended-batch-size-for-sqlbulkcopy

**Comment by ShaonDey** [comment]
@borisdj After inserting data with the `.BulkInsertAsync(list1)` method, and before calling the `SaveChangesAsync()` if I need to discard all those added changes via `BulkInsertAsync` how can that be achieved?
