### ISSUE TITLE
I am getting an error at runtime for licensing

### ISSUE THREAD

**Issue by aumang** [borisdj/EFCore.BulkExtensions#1365]
I am getting the below error at runtime saying the below.

System.Exception: ERROR_005: The monthly trial period is expired (date: 2024-01-01, version: 7.101.1.0). You can extend your trial by downloading the latest version as the beginning of every month.

I have tried reinstalling the EFCore.BulkExtensions multiple time but am unable to find any solution to it.

**Comment by Xor-el** [comment]
Hello @anumang, you are in the wrong project. 
The package throwing that error is the ZZZ EntityFramework Bulk Extensions (https://zzzprojects.com/knowledge-base/67/what-is-the-error-005-in-the-zzz-projects-library-#:~:text=Accepted%20Answer,contains%20another%20month%2Dlong%20trial.)  which requires a license.
This particular package in this repo does not require any paid license.

**Comment by borisdj** [comment]
@aumang this library _EFCore.BulkExtensions_ does not have any trial period.
Also it open source and free to use in most cases (cFOSS), and only requires license to be paid for companies with over 1 million $ revenue per year (more in the ReadMe).
