### ISSUE TITLE
Extension methods not available on derived dbcontext class?

### ISSUE THREAD

**Issue by Kelzling** [borisdj/EFCore.BulkExtensions#138]
I am using EF Core, using a context that is derived from the base DbContext class. I have installed the nuget package, but when I try and call BulkInsert on my context it says it does not have a definition for the method, and the best extension method overload needs the receiver to be of type DbContext. Can these only be called on an instance of the base version of DbContext or have I gone wrong somewhere?

**Comment by Kelzling** [comment]
I managed to discover the issue! Somehow my DbContext had ended up using System.Data.Entity instead of Microsoft.EntityFrameworkCore, so it was a DbContext, but not the right sort of DbContext. Thank you for pointing me to the test project, because that helped me figure it out. :)

**Comment by borisdj** [comment]
You are welcome, glad you sorted the issue.
