### ISSUE TITLE
[Question] EF.Functions Ambiguous Call Between Providers

### ISSUE THREAD

**Issue by pedrosanguineti** [borisdj/EFCore.BulkExtensions#1386]
Hello,

I have to following issue:

When I include in our project the library EFCore.BulkExtensions, an error shows up in one method that is using EF.Functions.DateDiffDay(...).

This is the description of the error:
> The call is ambiguous between the following methods or properties: 'Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffDay(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)' and 'Microsoft.EntityFrameworkCore.MySqlDbFunctionsExtensions.DateDiffDay(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)'[CS0121](https://msdn.microsoft.com/query/roslyn.query?appId%3Droslyn%26k%3Dk%28CS0121%29)

The solution I have implemented is not to use EFCore.BulkExtensions, but only the library of the provider that we use, ie. EFCore.BulkExtensions.SqlServer.

An alternative solution is to speficify the provider in a using clause.

Question:  is there's an alternative to do it more dynamically, for example depending on the configuration of the provider configured for the DbContext in the Startup.cs file or DependencyInjection.cs file.

**Comment by borisdj** [comment]
One solution is to use specific provider, as you already stated.
You can keep it that way.
OTherwise several other options were disscsed here prior to adapter separation:
[69/conflict: ambiguous reference for IndexBuilder](https://github.com/borisdj/EFCore.BulkExtensions/issues/669)
