### ISSUE TITLE
Support for navigation properties

### ISSUE THREAD

**Issue by Thaval** [borisdj/EFCore.BulkExtensions#139]
Hi,

stated from you documentation, it's said that "for mapping FKs explicit Id properties have to be in entity. Having only Navigation property is not supported."
Do you plan to support navigation properties or is there a possibility to make a PR?

**Comment by borisdj** [comment]
I have added that to the future feature list but at the moment don't have specific timeframe for it.

**Comment by Thaval** [comment]
Thx for the hint!

**Comment by borisdj** [comment]
Navigation only is now supported, Shadow FKs added, version 3.2.1+
