### ISSUE TITLE
Postgres constraint check is not considering the schema

### ISSUE THREAD

**Issue by paulohumberto42** [borisdj/EFCore.BulkExtensions#1396]
If I have two tables in different schemas with same name, the validation goes wrong.
The query is not filtering the table schema
https://github.com/borisdj/EFCore.BulkExtensions/blob/1289ab42c824eedca1e2e380af20a1274a56af65/EFCore.BulkExtensions/SqlAdapters/PostgreSql/PostgreSqlQueryBuilder.cs#L289

**Comment by paulohumberto42** [comment]
Fixed it: https://github.com/borisdj/EFCore.BulkExtensions/pull/1397

**Comment by borisdj** [comment]
Merged, thx for contrib.

**Comment by paulohumberto42** [comment]
Can you publish it for EF 7.X and EF 8.X?
