### ISSUE TITLE
Need To be careful when using BulkInsertOrUpdate With Composite Key

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#14]
When using the BulkInsertOrUpdate operation, you have to be careful if your primary key is a Composite key, let's say you pass in a list of records, some of them are new and need to be created (Inserted), one part of the key is same as an existing key (i.e. Part of the composite key), the operation will treat it as an existing record and will overwrite it, instead of inserting a new on, I got burned by that and spent hours banging my head.

**Comment by borisdj** [comment]
Composite PKs are not currently supported.
I will temporary add Remark about it in README.
It is already on my ToDo list and will try to add that feature soon.

**Comment by nafberger** [comment]
Big Thanks
  ----- Original Message -----

**Comment by nafberger** [comment]
Borris let me ask again, composite keys not working even with a plain bulkUpdate, I thought it's only not working when using BulkInsertOrUpdate. So, can you use bulkUpdate with composite key, please reply

**Comment by borisdj** [comment]
No, Composite keys are not yet supported in General.
There is no difference in that regard between BulkUpdate and BulkInsertOrUpdate.

**Comment by borisdj** [comment]
I have added support for CompositeKeys, also made test for it and they are passing.
Can you test it on your example and confirm if it works. Take the latest source of library because nugget is not yet updated.
If all is good I will publish new nugget version as well.

**Comment by borisdj** [comment]
New nugget publish.

**Comment by nafberger** [comment]
Big Thanks
  ----- Original Message -----

**Comment by nafberger** [comment]
Thanks Borris I tried it and it works
