### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'

### ISSUE THREAD

**Issue by boomgetchopped** [borisdj/EFCore.BulkExtensions#1429]
Using version 8.0.1. I get this error when saving sub entities. The FK is a long. I'm wondering that has anything to do with it?

It fails at the bulk insert subEntities line with this error:

`			executionStrategy.Execute(
			() =>
			{
				//_db.BillingHeaders.AddRange(headerstoInsert);
				//_db.BulkSaveChanges();

				using (var transaction = _db.Database.BeginTransaction())
				{
					_db.BulkInsert(headerstoInsert, new BulkConfig { SetOutputIdentity = true });
					var subEntities = new List<BillingDetail>();
					foreach (var entity in headerstoInsert)
					{
						foreach (var subEntity in entity.BillingDetails)
						{
							subEntity.BillingId = entity.BillingId; // sets FK to match its linked PK that was generated in DB
						}
						subEntities.AddRange(entity.BillingDetails);
					}
					_db.BulkInsert(subEntities);
					transaction.Commit();
				}

			});`

**Comment by borisdj** [comment]
Can you write full code snippet or entire  test the for reproduction of the issue, so Entity class, and context config if any.
Try yo strip ti to minimum components that still throws the exception.
