### ISSUE TITLE
Bad bulk insertion on Many to Many relations

### ISSUE THREAD

**Issue by diecamdia** [borisdj/EFCore.BulkExtensions#143]
Hi,
I'm not sure if it's a problem but this is happening: I have 3 tables with many to many relationship, for example I have Avws, Titles and Avws_Titles. All with an Identity column. First insert Avws to get the value of the id, then insert Title to get the id for the title and at the end insert Avws_Titles with id of avws and id of titles. I've done it following the example in the Readme, but this is what happens:

  Before CommitTransaction:
    
     Avws: id> 60353
     Title: id> 61759
               value> "Origina Title"
      Title: id> 61760
               value> "Alternate Title"

      Avws_Title: id> 56001
                        avwsid> 60353
                        original> true
                        titleid> 61759
     Avws_Title: id> 56002
                          avwsid> 60353
                          original> false
                          titleid> 61760
      
    After CommitTransaction:

      Avws: id> 60353
     Title: id> 62176
               value> "Origina Title"
      Title: id> 62175
               value> "Alternate Title"

      Avws_Title: id> 56001
                        avwsid> 60353
                        original> **true** wront value, must be false
                        titleid> **62175** Change order

     Avws_Title: id> 56002
                          avwsid> 60353
                          original> **false** wrong value, must be true
                          titleid> **62176** Change order

I've been using EF Core 2.1 and EFCore.BulkExtensions 2.4.0. I've used BulkInsertAsync with Bulkconfig PreserveInsertOrder = true, SetOutputIdentity = true. When I check de results in the database de Ids are diferentes after transaction and without transaction that I see in debug.

Thanks.

**Comment by borisdj** [comment]
I have made the following Test and it works fine:

```C#
public class Avw
{
    public int AvwId { get; set; }

    public string Code { get; set; }
}
public class Title
{
    public int TitleId { get; set; }

    public string Name { get; set; }
}
public class AvwTitle
{
    public int AvwTitleId { get; set; }

    public int TitleId { get; set; }
    public Title Title { get; set; }

    public int AvwId { get; set; }
    public Avw Avw { get; set; }

    public string Description { get; set; }
}

using (var context = new TestContext(ContextUtil.GetOptions()))
{
    var entitiesAvw = new List<Avw>();
    var entitiesTitle = new List<Title>();
    int countAvw = 10;
    for (int i = 0; i < countAvw; i++)
    {
        var entityAvw = new Avw
        {
            AvwId = i - countAvw, // set to negative value for mutual order because of PreserveInsertOrder
            Code = "A" + i
        };
        entitiesAvw.Add(entityAvw);

        if (i % 2 == 0)
        {
            var entityTitle = new Title
            {
                TitleId = i - countAvw,
                Name = "Nm" + i
            };
            entitiesTitle.Add(entityTitle);
        }
    }
    context.BulkInsert(entitiesAvw, new BulkConfig() { SetOutputIdentity = true, PreserveInsertOrder = true });
    context.BulkInsert(entitiesTitle, new BulkConfig() { SetOutputIdentity = true, PreserveInsertOrder = true });

    var entitiesAvwTitle = new List<AvwTitle>();
    for (int i = 0; i < countAvw; i++)
    {
        var entityAvwTitle = new AvwTitle
        {
            AvwId = entitiesAvw[i].AvwId,
            TitleId = entitiesAvw[i/2].AvwId,
            Description = "D" + i
        };
        entitiesAvwTitle.Add(entityAvwTitle);
    }
    context.BulkInsert(entitiesAvwTitle);
}
```

**Comment by diecamdia** [comment]
Yes, it is working fine if a negative identification is established before insertion.

Thanks for your help.
