### ISSUE TITLE
MySQL adapter ignores UseTempDb flag

### ISSUE THREAD

**Issue by ivanbiljan** [borisdj/EFCore.BulkExtensions#1434]
What exactly is the rationale behind this?
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/7541476/af1d1bf9-8caa-47a9-a052-079fa78177ab)

 I would prefer not having to give CREATE permissions unless absolutely necessary.

**Comment by borisdj** [comment]
Seems like a bug, will remove that line.

**Comment by ivanbiljan** [comment]
Thanks @borisdj . 

#1446 addresses this. There was an issue where merge tables would remain in the database because the wrong flag was passed in. That's been fixed as well
