### ISSUE TITLE
Unit Tests DFailing [.Net 8.0]

### ISSUE THREAD

**Issue by DynConcepts** [borisdj/EFCore.BulkExtensions#1453]
Is this expected?

![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/9969889/4c05d7c4-56c5-409c-8315-ec80d5dd525c)

BACKGROUND:  I was having problems with getting some of my code working, so I pulled the source and tried build/test as part of being able to reproduce my problem in a fashionI could submit... but then I hit the above and am wondering Why???

Commit:  9fa9bd9576e14561cc5a6f0a302d6eb452ae92ad

**Comment by borisdj** [comment]
Fixed
