### ISSUE TITLE
InMemory provider support

### ISSUE THREAD

**Issue by bo100nka** [borisdj/EFCore.BulkExtensions#146]
If I need to write unit tests for some features, i cannot use the Bulk operations due to the fact that I use the InMemory db provider.

So I am forced to extract the dbContext.BulkXxx() function calls in a separate virtual function that can be mocked by my test class.
It would be more convenient if the InMemory provider would be supported.

**Comment by borisdj** [comment]
InMemoryProvider does not support Relational-specific methods so it can't be used.
There is a comment about this in one Test:
https://github.com/borisdj/EFCore.BulkExtensions/blob/e2eb1e35efccd751d44170a8920f8d8d1c44b6f6/EFCore.BulkExtensions.Tests/TestContext.cs#L55

**Comment by calebickler** [comment]
Shoot, thanks for your help though
