### ISSUE TITLE
Replace IList<> with IEnumerable<>

### ISSUE THREAD

**Issue by acordmike** [borisdj/EFCore.BulkExtensions#147]
I did not see any specific IList<> functionality (at least for the bulk insert). It would be helpful to change this the bulk input parameters to IEnumerable<> to prevent having to wrap collections into List objects to use the methods.

**Comment by borisdj** [comment]
Implemented with 2.4.2

**Comment by borisdj** [comment]
Reverted to IList with 2.4.3 because of UpdateEntitiesIdentity(SetOutputIdentity).
Related to https://github.com/borisdj/EFCore.BulkExtensions/issues/76
Reference of List is required:
https://github.com/borisdj/EFCore.BulkExtensions/blob/c0b9aa5476d607e0a6279c275d4f94d0cbc30d2c/EFCore.BulkExtensions/TableInfo.cs#L458-L462

**Comment by Mithras** [comment]
Having IList for bulk operations doesn't make much sense to me. If I need to insert millions of rows, am I supposed to load them all in memory? I guess I can still split rows in reasonable chunks and call bulkInserts multiple times but it's kinda weird that I have to do that.

**Comment by cojocaru-dragos-alexandru** [comment]
> Reverted to IList with 2.4.3 because of UpdateEntitiesIdentity(SetOutputIdentity).
> Related to #76
> Reference of List is required:
> https://github.com/borisdj/EFCore.BulkExtensions/blob/c0b9aa5476d607e0a6279c275d4f94d0cbc30d2c/EFCore.BulkExtensions/TableInfo.cs#L458-L462

Can't you just assign entities = entitiesWithOutputIdentity ?

**Comment by Numpsy** [comment]
> 
> `entities = entitiesWithOutputIdentity`
> 

It needs to update the callers view of the elements rather than just the local reference?

**Comment by borisdj** [comment]
Bulk methods are now receiving **IEnumerable**.
