### ISSUE TITLE
Update Microsoft.Data.SqlClient to avoid SqlGuidCaster error

### ISSUE THREAD

**Issue by blackflys** [borisdj/EFCore.BulkExtensions#1471]
Can you build a new package with the new version (5.2.0) of Microsoft.Data.SqlClient so there is no more the error of SqlGuidCaster while running multiple unit tests at once.

It has been fixed in other packages using this nuget (it is explained [here](https://github.com/dotnet/SqlClient/issues/1930 ) and has been fixed recently, [see this comment](https://github.com/dotnet/SqlClient/issues/1930#issuecomment-1971425200) )

Edit: I made a PR here: https://github.com/borisdj/EFCore.BulkExtensions/pull/1473
Thanks

**Comment by borisdj** [comment]
Thx for contrib.

**Comment by borisdj** [comment]
8.0.3 published
