### ISSUE TITLE
Bad performance / Very slow bulk insert

### ISSUE THREAD

**Issue by aloene** [borisdj/EFCore.BulkExtensions#148]
Hi,

I have 4217 records to insert or update using BulkInsertOrUpdateAsync(). When trying to write them using the default timeout, I get a timeout Exception.
So I have disabled the timeout (set BulkCopyTimeout to 0) and the BulkInsertOrUpdateAsync() call now returns after 15 minutes. This is **very slow** : I do not understand what is going on. The .NET core process (A windows service) and the Database are on the same server.
While waiting, the SQL Server activity monitor shows me the bulk insert statement is waiting (wait type=  ASYNC_NETWORK_IO). It seems like my .NET core process is not sending data fast enough to SQL Server. (?)

If it helps the BulkInsertOrUpdateAsync() call is part of a transaction : 
```CSharp
using (var dbTransaction = _dbContext.Database.BeginTransaction())
{
	// [...] (Multiple simple selects)

	await _dbContext.BulkInsertOrUpdateAsync(
		dbActivities,
		new BulkConfig
		{
			BulkCopyTimeout = 0,
			SetOutputIdentity = true,
			UpdateByProperties = new List<string> { nameof(Activity.PublicId), nameof(Activity.ActivityTypeId) },
			PropertiesToExclude = new List<string> { nameof(Activity.Id), nameof(Activity.ParentId) }
		});
```
NOTE: There is an index on Activity(ActivityTypeId + BusinessId) and 6-7 small fields are part of each record (to be inserted/updated) but the MERGE SQL statement is issued to the database after 15 minutes 
only and is quite fast / confirmed with SQL Server profiler.

Any idea ?
Thank you.

**Comment by borisdj** [comment]
When making issue write all relevant details so that it can be reproduced, in this case Class model of this Entity and it's config whether it's Attributes or ModelBuilder options.
Even better make a Test, similarly to existing tests, with it and try to reproduce it there, then post entire code of test.
From the info you currently gave in the issue I have a question regarding your PropertiesToExclude.
If some of these records are to be inserted then how can you exclude those columns?

**Comment by aloene** [comment]
Thank you for your answer. I will try to reproduce the issue using a test (tomorrow or next week).
Regarding the properties to include :
* `Id` is the auto-incremented/identity identifier so I do not need/cannot set it for a new record
* `ParentId` is optional (nullable in DB) and cannot be set at this stage (and a following statement will update it using custom rules, from `PublicId` columns)

The Entity looks like this :
```CSharp
public partial class Activity
{
	public Activity()
	{
		Children = new HashSet<Activity>();
		TimesheetDetails = new HashSet<TimesheetDetail>();
	}

	public int Id { get; set; }
	public int? ParentId { get; set; }
	public int? ApplicationId { get; set; }
	public string PublicId { get; set; }
	public string Name { get; set; }
	public ActivityTypeEnum ActivityTypeId { get; set; }
	public DateTime UpdatedOn { get; set; }
	public DateTime? ClosedOn { get; set; }
	public DateTime? DeletedOn { get; set; }

	public virtual ActivityType ActivityType { get; set; }
	public virtual Application Application { get; set; }
	public virtual Activity Parent { get; set; }
	public virtual ICollection<Activity> Children { get; set; }
	public virtual ICollection<TimesheetDetail> TimesheetDetails { get; set; }
}
```

And has been defined using ModelBuilder :
```CSharp
modelBuilder.Entity<Activity>(entity =>
{
	entity.ToTable("Activity");

	entity.HasIndex(e => new { e.ActivityTypeId, e.PublicId })
		.HasName("UQ_Activity_ActivityTypeId_PublicId")
		.IsUnique();

	entity.Property(e => e.ClosedOn).HasColumnType("datetime");
	entity.Property(e => e.DeletedOn).HasColumnType("datetime");

	entity.Property(e => e.Name)
		.IsRequired()
		.HasMaxLength(500)
		.IsUnicode(false);

	entity.Property(e => e.PublicId)
		.IsRequired()
		.HasMaxLength(36)
		.IsUnicode(false);

	entity.Property(e => e.UpdatedOn)
		.HasColumnType("datetime")
		.HasDefaultValueSql("(getdate())");

	entity.HasOne(d => d.ActivityType)
		.WithMany(p => p.Activities)
		.HasForeignKey(d => d.ActivityTypeId)
		.OnDelete(DeleteBehavior.ClientSetNull)
		.HasConstraintName("FK_Actitvity_ActivityType");

	entity.Property(e => e.ActivityTypeId)
		.HasConversion(new EnumToNumberConverter<ActivityTypeEnum, byte>());

	entity.HasOne(d => d.Application)
		.WithMany(p => p.Activities)
		.HasForeignKey(d => d.ApplicationId)
		.HasConstraintName("FK_Activity_Application");

	entity.HasOne(d => d.Parent)
		.WithMany(p => p.Children)
		.HasForeignKey(d => d.ParentId)
		.HasConstraintName("FK_Activity_Activity_Parent");
});
```

**Comment by aloene** [comment]
Hi,

I have reproduced the issue in a test project available [here](https://github.com/aloene/EFCore.BulkExtensions.Tests).
The behavior is weird since I face the problem ONLY when I add a reading query BEFORE the bulk update/insert statement. See [here](https://github.com/aloene/EFCore.BulkExtensions.Tests/blob/82ea4ea3ec6a90ca72906d282bd77af6db857a41/EFCore.BulkExtensions.Tests/BulkInsertTest.cs#L34).

The issue could be on my side but I do not understand the root cause...
Any idea ?

Thanks.

**Comment by aloene** [comment]
In my case, profiling the test indicates that 94% of the execution time is spent in `ObjectReaderEx[string]` indexer on  `var currentValue = context.Entry(current).Property(name).CurrentValue;` [here](https://github.com/borisdj/EFCore.BulkExtensions/blob/829cc26b60b91e59078ff2fdac0460d487cf5f5e/EFCore.BulkExtensions/ObjectReaderEx.cs#L47)
I suppose I could workaround the issue by removing my int/enum converter on my entity but I would like to keep it.
Precisely, the EFCore `DbContect.Entry(object)` method is slowing down whole process.
Removing the reading query in my code make it a lot faster for 4,000 records but the time spent on `DbContect.Entry(object)` is still very high (near 75%).

**Comment by borisdj** [comment]
Issue is caused by FastMember. Another way is already implemented, using DataTable instead of FastMember and currently it is used in 2 situations:
DataTable  is used with OwnedTypes since library FastMember can not (https://github.com/mgravell/fast-member/issues/21)
With Shadow prop. Discriminator (TPH inheritance) also because FastMember is slow for Update (https://github.com/borisdj/EFCore.BulkExtensions/pull/17)

Your issue is similar to Issue17 althought I'm not sure what is the reason in your case if you don't have Shadow properties. Probably some other specific can cause the same problem to arise.
Anyway try on your fork to change
https://github.com/borisdj/EFCore.BulkExtensions/blob/8fb0a4665f2fcbf5eef81460d1f6ad93a722e689/EFCore.BulkExtensions/SqlBulkOperation.cs#L40-L51
By replacing line 40 with: ```if (false)```
If ti solves the issue I will add `bool UseDataTable` as optional setting in _BulkConfig_ so you can configure it.

**Comment by aloene** [comment]
Indeed, based on your code, I think my case is not using FastMember with shadow properties but with value conversions which leads the the same issue (as stated in Issue #17).
If I get it right, maybe you could force using the DataTable method when entity has convertible properties :
```CSharp
bool useFastMember = tableInfo.HasOwnedTypes == false
  && tableInfo.ShadowProperties.Count == 0
  && tableInfo.ColumnNameContainsSquareBracket == false
  && !tableInfo.ConvertibleProperties.Any();
```
I have tested it (on my case only) with success.

For now, without altering your library code, I will simply do not keep entities in my DbContext before running the bulk operation to workaround the issue (In fact, I do not need them).

**Comment by borisdj** [comment]
Interesting that it passes successfully.
With DataTable I got:

> The given ColumnMapping does not match up with any column in the source or destination.

Which was expected considering (read the commented section):
https://github.com/borisdj/EFCore.BulkExtensions/blob/829cc26b60b91e59078ff2fdac0460d487cf5f5e/EFCore.BulkExtensions/SqlBulkOperation.cs#L331-L334
I think here should be added ```"tinyint"``` with ```typeof(int)``` for _EnumToIntConverter_, temporary fix extension.

**Comment by aloene** [comment]
I got the same exception when using tour initial proposal (`if (false)`) but not with the code snippet I included in my latest comment.

**Comment by aloene** [comment]
I confirm the fix works well. The DataTable method is used and the created DataTable is correctly populated with integer values matching the Enum ones without specific code. I have forked your lib and comitted the fix [here](https://github.com/aloene/EFCore.BulkExtensions).

**Comment by borisdj** [comment]
I have just checked it and the fix works. Will merge it.
Reasons why IF segment with  ```"tinyint"``` is not necessary is because Enum is by default mapped to _int_ and when _EnumToNumberConverter_ is used then Db type is _tinyint_ but it is still integer and doesn't need casting.

**Comment by borisdj** [comment]
Still there is another problem.
DataTable work well with EnumToNumberConverter or EnumToStringConverter where only Type is different.
However if there are ValueConverters (where Value is changed) then using DataTable do not work correctly, because I still haven't found DataConvertersInfo anywhere in Relational.
Run Test InsertWithValueConversion with your change and it will fail.
```C#
modelBuilder.Entity<Info>(e => { e.Property(p => p.ConvertedTime).HasConversion((value) => value.AddDays(1), (value) => value.AddDays(-1)); });
```
What could be done maybe as workaround is to check ConvertibleProperties for type and switch to DataTable when Convertibles are Type only and if there are no Value ones.

**Comment by borisdj** [comment]
I have manged to find ConvertersInfo, they are not in Relation object but directly in entityProperty as ConvertibleProperties.
So now it is fixed for all Convertibles.
New NuGet will be published soon.

**Comment by aloene** [comment]
Thank you. I was about to implement nearly the same thing except I wanted to use `ValueConverter.ConvertToProvider` which seems to be the conversion **compiled** expression. For a performance perspective, it will prevent from re-compiling expression for each entity without the need of implementing a custom function cache. Have you already tried it ?

**Comment by borisdj** [comment]
Nope, but will check it.
Or if you have already made it work with that write the code.

**Comment by borisdj** [comment]
Reimplemented with ConvertToProvider.
Nuget 2.4.1 published.
