### ISSUE TITLE
BulkConfig PreserveInsertOrder = true orders on Id not entitiesList order

### ISSUE THREAD

**Issue by SRQcoder** [borisdj/EFCore.BulkExtensions#149]
First off, your extension works great. Thanks!!

I have a question about BulkInsert not inserting records into SQL Server in the same order as the entitiesList. It does, however, insert them in the order of the Id (Identity field). But that's not what I was looking to do.  

So, for example, assume a simple list of US states and possessions. Just before running BulkInsert, the entitiesList is ordered by name (Alabama comes first). Running in debug mode confirms entitiesList is in alpha-order by state name. But when BulkInsert is run, the SQL table  ordering scheme is based on the Identity string (guid), not the Name. 

I'm not sure if `PreserveInsertOrder = true` is supposed to support the behavior I'm expecting; or, does it only work for putting Identity column data in sequential order? 

![image](https://user-images.githubusercontent.com/8331811/52752623-7f278200-2fc1-11e9-9b53-9d77e0e15b4b.png)

**Comment by borisdj** [comment]
You are welcome.
Since your Id is Guid and it seems it is generated in memory for keeping order you should use SequentialGuid: [RT.Comb](https://www.nuget.org/packages/RT.Comb/)
PreserveInsertOrder is only used for order when Id is generated in database.

**Comment by SRQcoder** [comment]
Thanks!!
