### ISSUE TITLE
Class structures with Discriminator aren't supported

### ISSUE THREAD

**Issue by Alexx999** [borisdj/EFCore.BulkExtensions#15]
Trying to do BulkInsert with a structure that maps several types to one table using some Discriminator field results in the IndexOutOfRange exception in FastMember.
This is obviously due to fact that Discriminator isn't present in instances.

**Comment by borisdj** [comment]
You can bypass this problem by making custom Discriminator, which you probably have do to anyway in order to set value of Discriminator column, so you need real Discriminator property.
Example:
```
public abstract class Person
{
    public int Id { get; set; }

    public string Discriminator { get; protected set; }
	
    ...
}

public class Instructor : Person
{
    public Instructor()
    {
        Discriminator = nameof(Instructor);
    }
	
    ...
}

public class Student : Person
{
    public Student()
    {
        Discriminator = nameof(Student);
    }

    ...
}
```

And in DbContext.cx
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Person>().HasDiscriminator<string>("Discriminator")
        .HasValue<Instructor>(nameof(Instructor))
        .HasValue<Student>(nameof(Student));
}
```

**Comment by Alexx999** [comment]
Well, problem is that I don't need to set any values there - EF Core is quite happily doing that for me and saving that into DB. However, it's impossible to save such entities with BulkExtension as there's no shadow property support.

**Comment by borisdj** [comment]
Configuration from the example above Does work with BulkExtension since here Discriminator is real property and not shadow, so there is no issue with FastMember either.

Table-Per-Hierarchy inheritance model can be set in 2 ways.
One is when EF does it automatically by Convention in which case you have shadow Property.
And second is like in this example where you explicitly define Discriminator property in Entity and configure it with _.HasDiscriminator()_.

**Comment by Alexx999** [comment]
I wonder if there are more cases where EF Core uses shadow properties. At least they can be freely added by a user so having some support for them (at least throwing NotSupportedException to let user know that they're not supported) is clearly required.
Because now it requires some debugging to figure out why the hell objects are not saving which isn't cool.

**Comment by borisdj** [comment]
I agree that Shadow support is good and I will integrate it, just to figure the cleanest way.
Comment was to add info that TPH can be done with explicit config so without Shadow properties.

**Comment by Alexx999** [comment]
Yeah, probably my initial message isn't very clear - I know that you can do that explicitly, however, by default EF Core will do that implicitly if your PK configuration allows that.

**Comment by borisdj** [comment]
I have integrated Discriminator support, cleaned up code a little bit, remove some lines that were not being used and optimized it by checking first is Table has Shadow field.
I have also added test for it and are passing.
So check the latest source and if all works for the situation you have I will publish new version of nugget.

**Comment by borisdj** [comment]
New nugget publish.

**Comment by Alexx999** [comment]
Sorry for late reply - test runs are quite long for me as DB size is over 100GB :)
So far it works fine - I guess it's okay.

**Comment by borisdj** [comment]
No rush, if something comes up it can always be fixed with another nugget version.
