### ISSUE TITLE
Bulk insert not as performant, any Tips to increase speed?

### ISSUE THREAD

**Issue by rklar3** [borisdj/EFCore.BulkExtensions#150]
Hi,

I am trying to insert 100,000 records and reach under 5 seconds. As of now it takes around 20 seconds
I have turned off auto detect changes.

`  _dbContext.DbContext.ChangeTracker.AutoDetectChangesEnabled = false; `  

This is my object:
      `  public int ID { get; set; }  `                         
      `  public string PartIdentifier { get; set; }&nbsp;`
     `   public int CountBatch { get; set; }`
      `  public IdentifierType Type { get; set; }`
     `   public Guid InventoryID { get; set; } `

This is my insert statement 
` await _dbContext.BulkInsertAsync(lookupsListBulkInsert, new BulkConfig { BatchSize = 20000 }); `

Any tips or help?
Thanks

**Comment by borisdj** [comment]
When you say 'As of now' what did change before Insert become slower?
Did this table become really large, containing several millions records?
Also make a Test for your scenario so that it can be reproducible.
