### ISSUE TITLE
Performance with small data sets

### ISSUE THREAD

**Issue by sandersaares** [borisdj/EFCore.BulkExtensions#151]
The benchmarks in the readme are nice. It would be even better to also know how this library compares when dealing with small data sets (e.g. 10 items). Is there some overhead, where it might lose out to plain EF? Or is it always better, even with small data sets?

I request this be added to the documentation in the readme.

**Comment by borisdj** [comment]
There is an overhead with small sets, since most Bulk ops needs to create Temp table and also Drop it after finish. My practice is to use Bulk for sets greater then 1000.
Eill this note in Readme.
