### ISSUE TITLE
`SharedTypeEntity` don't work with bulk operations

### ISSUE THREAD

**Issue by paulrostorp** [borisdj/EFCore.BulkExtensions#1520]
https://github.com/borisdj/EFCore.BulkExtensions/blob/580e0c3f26159d080fc7482d827a6c7024d52fd1/EFCore.BulkExtensions/TableInfo.cs#L154-L164

The usage of `FindEntityType` breaks bulk operations on [SharedTypeEntity](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.modelbuilder.sharedtypeentity?view=efcore-8.0).

Possible solutions: 
1. Allow passing a specific `IEntityType` via parameters or bulkconfig
2. Allow running bulk methods on a specific DB Set instead of just the context; this aligns with official EF core behavior: https://learn.microsoft.com/en-us/ef/core/change-tracking/miscellaneous#dbcontext-versus-dbset-methods

**Comment by borisdj** [comment]
Bulk methods has parameter Type as last argument of function.
`BulkInsert<T>(this DbContext context, IEnumerable<T> entities, BulkConfig? bulkConfig = null, Action<decimal>? progress = null, Type? type = null)`
