### ISSUE TITLE
[MySql/MariaDb] Insert an boolean type has invalid result (Always insert true in a bit column)

### ISSUE THREAD

**Issue by Cyril12740** [borisdj/EFCore.BulkExtensions#1521]
Hi,

With the following code, i have 2 different behaviours when the column's type is bit or tiny(1).

```C#
var items = new List<ConsoleApp1.BooleanBulkInsertDbContext.TestClass>()
{
    new()
    {
        Name = "Is active is true",
        IsActive = true,
    },
    new()
    {
        Name = "Is active is false",
        IsActive = false,
    }
};


DbContext context = GetDbContext();

context.BulkInsert(items);
```

When the column's type is tinyint(1), the inserted result is :
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/11708704/283ddcee-00e5-4691-bc85-325b7f14323d)

When the column's type is bit, the inserted result is :
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/11708704/48a39a2b-4589-4629-8490-b2fbeb5b4590)

**Comment by borisdj** [comment]
Closing this for now, if you manage to make it reproducible, write it here and will reopen.

**Comment by chasse20** [comment]
Open this back up please. This is reproduceable.

MySQL: 8.0.25
EFCore.BulkExtensions: 8.1.0
EFCore: 8.0.8

DTO:
```
public class DailyOption
{
	public int DailyOptionId { get; set; }
	public DateOnly Time { get; set; }
	public bool IsCall { get; set; }
}
```

Database Table:
```
CREATE TABLE `DailyOption` (
  `DailyOptionId` int NOT NULL AUTO_INCREMENT,
  `Time` date NOT NULL,
  `IsCall` bit(1) NOT NULL,
  PRIMARY KEY (`DailyOptionId`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
