### ISSUE TITLE
Unable to cast object of type 'System.Int64' to type 'System.Nullable`1[System.Int32]'

### ISSUE THREAD

**Issue by boomgetchopped** [borisdj/EFCore.BulkExtensions#1523]
Hello, I have an entity with a nullable long. I believe this property is not supported by your bulk insert method and this is the cause of my error.

Using ms sql server:

public long? BillingId { get; set; }

**Comment by borisdj** [comment]
I am unable to reproduce it, can you write a Test, or alter some exiting one to make it occur.
