### ISSUE TITLE
PostgreSQL Table-Per-Hierarchy Inheritance Is Not Working

### ISSUE THREAD

**Issue by Genide** [borisdj/EFCore.BulkExtensions#1524]
### Problem Overview
When trying to work with TPH inheritance with PostgreSQL, I tried following the README instructions to explicitly call the `HasDiscriminator` function inside DbContext. I expected that BulkExtensions would determine the discriminator value from the DbContext. 

From the README, it implies that BulkExtensions should be able to determine discriminator values if explicitly specified inside DbContext.
> TPH ([Table-Per-Hierarchy](https://docs.microsoft.com/en-us/aspnet/core/data/ef-mvc/inheritance)) inheritance model can can be set in 2 ways.
First is automatically by Convention in which case Discriminator column is not directly in Entity but is [Shadow](http://www.learnentityframeworkcore.com/model/shadow-properties) Property.
And second is to explicitly define Discriminator property in Entity and configure it with .HasDiscriminator().
Important remark regarding the first case is that since we can not set directly Discriminator to certain value we need first to add list of entities to DbSet where it will be set and after that we can call Bulk operation. 

However, I ran into errors on BulkInsertOrUpdate operations. These errors indicated that the discriminator value was `null`. I looked into PostgreSqlAdapter.cs to see how it would determining the discriminator value. From a simple search, I don't believe that PostgreSQL support TPH inheritance at all. **PostgreSqlAdapter has no code to get the discriminator values**, unlike the Sql Server, MySQL, and Sqlite adapters.

### Expected Behavior
I expected that the Discriminator value would be automatically added for me by BulkExtensions if TPH is set up explicitly.
``` csharp
        // Example DbContext configuration
        modelBuilder.Entity<FinancialInstitution>(entity =>
        {
            // Omitted other configuration for brevity...
            entity.HasDiscriminator<string>("Discriminator")
                .HasValue<FinancialInstitution>("FinancialInstitution")
                .HasValue<BankFinancialInsitution>("BankFinancialInstitution");
        });

        // In some other code
        await DbContext.BulkInsertOrUpdateAsync(newBankFinancialInstitutions);
```

### Actual Behavior
Received an error when calling `context.BulkInsertOrUpdate`
```
Exception data:
    Severity: ERROR
    SqlState: 23502
    MessageText: null value in column "Discriminator" of relation "FinancialInstitution" violates not-null constraint
    Detail: Failing row contains (Redacted, Redacted, 2024-07-05 20:08:55.222201+00, null).
    SchemaName: public
    TableName: FinancialInstitution
    ColumnName: Discriminator
    File: execMain.c
    Line: 2003
    Routine: ExecConstraints
```

### Proposed Solution
Add code to PostgreSqlAdapter.cs that get discriminator values like the other Sql adapters.

**Comment by borisdj** [comment]
I have tried this on Test _**DiscriminatorShadowTest**_, just added option for PG: `[InlineData(SqlType.PostgreSql)]` add it works.
Take the latest source and try to alter it to reproduce your issue.

class Person also has commented property:
`//public string Discriminator { get; set; } = null!;`
and DbConext config hascommented segment:
`//modelBuilder.Entity<Person>().HasDiscriminator<string>("Discriminator").HasValue<Student>("Student").HasValue<Teacher>("Teacher"); // name of classes are default values`

Both ways work fine, implicit and explicit settings when I uncomment those.
