### ISSUE TITLE
Truncate method with custom table name

### ISSUE THREAD

**Issue by bugejakurt** [borisdj/EFCore.BulkExtensions#1527]
The truncate method on the `DbContextBulkExtensions` class currently doesn't expose a `BulkConfig` parameter to customize the table name which we should truncate. For example, by specifying `CustomDestinationTableName` on a `BulkConfig` instance we can customize the truncated table name. Thanks.

**Comment by borisdj** [comment]
Fixed, new nuget will be published soon.
