### ISSUE TITLE
BulkInsert generic abstract class issue

### ISSUE THREAD

**Issue by NicolaPicoli** [borisdj/EFCore.BulkExtensions#153]
I have an abstract class (`Register`) whose inheritance in all my entities. This way I created a generic repository to make a bulk insert. The dynamics of the code is as follows: I get a text document, where each line represents an entity. I map each entity and save all these entities in a generic `ICollection<Register> RegisterList`. To save to the database, I group these entities by type and try to save with bulk insert. But I get the following error: 

![error_bulkinsert](https://user-images.githubusercontent.com/18726543/53335070-3b921980-38d9-11e9-9b5c-49702dc7c2b5.png)

Here is the code if u would like to reproduce the error...

```c#
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using EFCore.BulkExtensions;

public class Program
{
    public static void Main()
    {
        var context = new EntityContext();
        var doc = new Document();
        for (int i = 0; i < 500; i++)
        {
            doc.RegisterList.Add(new RegisterA($"0000_{i.ToString("0000000")}"));
            doc.RegisterList.Add(new RegisterB($"0150_{i.ToString("0000000")}"));
        }

        var groupList = doc.RegisterList.GroupBy(p => p.GetType());
        foreach (var register in groupList)
           context.BulkInsert(register.ToList());
    }

    public class EntityContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlServer("Server=.\\SQLEXPRESS;Database=TEST;Trusted_Connection=True;");

        public DbSet<RegisterA> RegisterA { get; set; }
        public DbSet<RegisterB> RegisterB { get; set; }
    }

    public class Document
    {
        public Document() => RegisterList = new List<Register>();
        public ICollection<Register> RegisterList { get; set; }
    }
    public abstract class Register
    {
        public Register() => Id = Guid.NewGuid();
        public Guid Id { get; set; }
    }
    public class RegisterA : Register
    {
        public RegisterA(string name) => Name = name;
        public string Name { get; set; }
    }
    public class RegisterB : Register
    {
        public RegisterB(string title) => Title = title;
        public string Title { get; set; }
    }
}
```

**Comment by borisdj** [comment]
For Bulk ops you need specific type of the list, it can't be parent type.
But you can Cast it:
```C#
foreach (var register in groupList)
{
    string typeName = register.ToList()[0].GetType().Name;

    if (typeName == nameof(RegisterA))
        context.BulkInsert(register.ToList().Cast<RegisterA>().ToList());
    else if (typeName == nameof(RegisterB))
        context.BulkInsert(register.ToList().Cast<RegisterB>().ToList());
}
```

**Comment by NicolaPicoli** [comment]
Even though I have 154 Entities? It would be a very dull code ...
I reported the same error to the Z.EntityFramework.Extensions.EFCore, and they reported it as a factual error... Was there some other way around this?

**Comment by borisdj** [comment]
The architecture you implemented is somewhat unusual.
I do not consider this an error, more like specific usage(feature) that is not supported.
Bulk extension methods are receiving Generic arguments and they require explicit the type.
It would not be an easy task to change this.

**Comment by borisdj** [comment]
To do it easier you could write in Excel formula for these 154 lines:

> ="if (typeName == nameof("&A2&")) context.BulkInsert(register.ToList().Cast<"&A2&">().ToList());"
which would generate:
```C#
if (typeName == nameof(RegisterA)) context.BulkInsert(register.ToList().Cast<RegisterA>().ToList());
if (typeName == nameof(RegisterB)) context.BulkInsert(register.ToList().Cast<RegisterB>().ToList());
...
```

**Comment by NicolaPicoli** [comment]
Sorry, but for me, It does not sound like a clean code.
Houever, I made the code with a generic repository, containing two methods:

> `public void AddRange<TEntity>(IEnumerable<TEntity> entityList) where TEntity : class`
> `public void BulkInsert<TEntity>(IEnumerable<TEntity> entityList) where TEntity : class`

`AddRange` which is native to EFCore, works perfectly (of course, with very low performance), while `BulkInsert` has the same problem. Faced with this, I still think it's a **bug**
As already mentioned, the [Z.EntityFramework.Extensions.EFCore](https://entityframework-extensions.net/) are already repairing this issue.

Here is the new code...
```c#
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using EFCore.BulkExtensions;

public class Program
{
    public static void Main()
    {
        var context = new EntityContext();
        var repository = new Repository(context);
        var doc = new Document();
        for (int i = 0; i < 500; i++)
        {
            doc.RegisterList.Add(new RegisterA($"0000_{i.ToString("0000000")}"));
            doc.RegisterList.Add(new RegisterB($"0150_{i.ToString("0000000")}"));
        }

        var groupList = doc.RegisterList.GroupBy(p => p.GetType());
        foreach (var registerList in groupList)
        {
            repository.AddRange(registerList);
            context.SaveChanges();
            repository.BulkInsert(registerList);
        }
    }

    public class Repository
    {
        protected DbContext _context;
        public Repository(DbContext context) => _context = context;
        public void AddRange<TEntity>(IEnumerable<TEntity> entityList) where TEntity : class
            => _context.Set<TEntity>().AddRange(entityList);
        public void BulkInsert<TEntity>(IEnumerable<TEntity> entityList) where TEntity : class
            => _context.BulkInsert<TEntity>(entityList.ToList());
    }
    public class EntityContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            => optionsBuilder.UseSqlServer("Server=.\\SQLEXPRESS;Database=TEST;Trusted_Connection=True;");
        public DbSet<RegisterA> RegisterA { get; set; }
        public DbSet<RegisterB> RegisterB { get; set; }
    }
    public class Document
    {
        public Document() => RegisterList = new List<Register>();
        public ICollection<Register> RegisterList { get; set; }
    }
    public abstract class Register
    {
        public Register() => Id = Guid.NewGuid();
        public Guid Id { get; set; }
    }
    public class RegisterA : Register
    {
        public RegisterA(string name) => Name = name;
        public string Name { get; set; }
    }
    public class RegisterB : Register
    {
        public RegisterB(string title) => Title = title;
        public string Title { get; set; }
    }
}
```

**Comment by borisdj** [comment]
Didn't say it was clean, just a way to make it work.
Also I don't find it good practice to use shared parent List for different children, better to have them separated.
As for the error I am using the term 'bug' for something that is stated in Docs(README) that should work but doesn't. This is not the case here, this is a feature that is not supported.
Still I will tag it with an Enhancement label, but can't put any time frame to it.
You can fork the source and try implement this feature, and if successful make a Pull Request.

**Comment by borisdj** [comment]
Implemented, NuGet 2.4.5

**Comment by Snazzie** [comment]
Using insert on Base class is very common in metrics ingesting. If you're casting or creating insert for every metric type. you've got yourself a load of duplicate code handling each type.

**Comment by borisdj** [comment]
@Snazzie can you elabore more the issue, what metric are you using and how.
Maybe write a code snipped with a sample.
