### ISSUE TITLE
BulkInsertAsync is assigning negative values to inserted entries' primary keys

### ISSUE THREAD

**Issue by cjohnson57** [borisdj/EFCore.BulkExtensions#1534]
I have the following code inserting values into the database:

```cs
using (var transaction = Database.BeginTransaction())
{
    BulkConfig bulkConfig = new BulkConfig { SetOutputIdentity = true };
    await this.BulkInsertAsync(entries, bulkConfig);
    transaction.Commit();
}
returnValue = entries.Select(x => x.ConsolidatedTBRowId).ToList();
```

However, after committing the transaction, every item in `entries` gets a negative `ConsolidatedTBRowId`, although the actual database contains the correct values. The last entry in `entries` has an ID of -1, and it goes up to -(however many entries are in the list).  The weird thing is that this didn't start happening until today. My only guess is that the values for `ConsolidatedTBRowId` started getting too large, as they're currently over 1M.

The column in the DB is set as Primary Key, Identity(1,1), Auto Increment.

I also tried adding the following annotations to this ID to see if it would help:
```cs
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int ConsolidatedTBRowId { get; set; }
```

Edit: Probably obvious but changing to the non-async version of BulkInsert does the same thing.

Edit2: I think adding `UseTempDB` to the config may have fixed it, but that caused the insert to be unacceptably slow

**Comment by borisdj** [comment]
What Db are you using, MsSql ? and what nuget version of Bulk package.
I have made a test with 3 mil row and it works, unable to reproduce the issue.

There is info in the ReadMe about the operational steps:

> PreserveInsertOrder is true by default and makes sure that entities are inserted to Db as ordered in entitiesList.
> When table has Identity column (int autoincrement) with 0 values in list they will temporary be automatically changed from 0s into range -N:-1.

In DB they would get regular numbers that should be loaded back when SetOutputIdentity is set to True, as you have did.
If you can not issolare the issue, maybe you could make a conditional test, to check is first row has negative Id, in which case call  reload them again, using select Where Id Or Date > then previous Max or with BulkRead if you have some other unique combination of columns.

**Comment by borisdj** [comment]
@cjohnson57 also seems that the code is not valid in regards to Async, you must use it consistently, transation Begin and Commit should also be Async:
```cs
using (var transaction = await Database.BeginTransactionAsync())
{
    BulkConfig bulkConfig = new BulkConfig { SetOutputIdentity = true };
    await this.BulkInsertAsync(entries, bulkConfig);
    await  transaction.CommitAsync();
}
returnValue = entries.Select(x => x.ConsolidatedTBRowId).ToList();
```

**Comment by cjohnson57** [comment]
Thank you, I will try changing the transaction to be Async and see if it helps.

The DB is MS SQL Server and the version is 6.8.1

**Comment by cjohnson57** [comment]
@borisdj Ok, tried running it with the same code you posted most recently (but on a different table having the same issue) after changing some DB permissions around and it didn't error, however the insert ran for 15 minutes before I gave up and killed it (inserting 39k rows, for reference). Unfortunately if it runs that slow it won't work for my purposes and it'd be better to just re-query after doing the normal insert. 

Specifically, the output was here for about 5 minutes (which is about how long it takes to insert normally
![image](https://github.com/user-attachments/assets/790e0466-94c7-432f-95cb-af4ac527ca69)

And then after that 5 minute period it went to this where it hung for about 10 minutes before I mercy killed it.
![image](https://github.com/user-attachments/assets/47aea10f-ddea-43f1-9e53-ba28e4d38ad4)


Also, it seemed like it locked the DB while running this?
![image](https://github.com/user-attachments/assets/a1373f6d-2677-456e-bf5f-278bae724340)

All that being said, I feel like even without SetOutputIdentity it should be giving the correct ID values, it seems strange that it would be doing that unexpected behavior in the first place.

**Comment by cjohnson57** [comment]
Should I perhaps try upgrading to a more recent version? I think 6.8.1 is the latest version that supports .NET 6.0, though, which is what I'm using.

**Comment by borisdj** [comment]
It should be much much much faster.
If you can make an update to EF 8.
Otherwise can you write entire test for your use case, try to make it as simple as possible but that would still reproduce the issue.

**Comment by bridlynch** [comment]
FWIW, I had a similiar issue and it turned out to be a filtered index was failing to be created once the record count reached a certain number of records.  

I pulled the SQL generated by the extension library out of Visual Studio, created a SQL Query that populated a temp table with a large amount of records from my source table, zero'ed out the ids in the temp table, ran the merge statement generated from the library and saw that the records were inserted but the OUTPUT wasn't updated with the correct ids.  Ran the script again to grab the query execution plan and saw the index was failing to update which prevented the temp table from being updated with the inserted data.

I recommend taking the library out of the equation to troubleshoot and evaluating what you're trying to do directly in the database prior to upgrading everything, you may land up in the same spot.

**Comment by cjohnson57** [comment]
@bridlynch Thank you for the insight. Do you happen to recall what you ultimately did to solve the issue?

I don't do anything else to the tables in the code before doing the insert. However, I often run a delete on the tables directly through SSMS before running the code.

**Comment by cjohnson57** [comment]
Upgraded to .NET 8.0 and the latest versions of EF (8.0.7) and BulkExtensions (8.1.0) and still having the same issue.

I also don't think it used to take 5 minutes to do the initial bulk insert, so the issues are probably related?
