### ISSUE TITLE
Error when using BulkInsert/BulkUpdate on a list of TPC/TPH entities with SQLServer

### ISSUE THREAD

**Issue by SandraS41** [borisdj/EFCore.BulkExtensions#1566]
Hello

We encountered an issue when using TPC inheritance with entities (with SQLServer)

We have entities like this

```csharp
public class Vehicle 
{
  public string Name {get; set;}
}
```
```csharp
public class Car : Vehicle  
{
  public double Horsepower {get; set;}
}
```
```csharp
public class Bus: Vehicle 
{
  public int NumberOfSeats {get; set;}
  public int Capacity {get; set;}
}
```
```csharp
public class ApplicationDContext: DbContext
{

  public DbSet<Vehicle> Vehicles => Set<Vehicle>();
  public DbSet<Car> Cars => Set<Car>();
  public DbSet<Bus> Buses => Set<Bus>();


  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    modelBuilder.Entity<Vehicle>().ToTable("Vehicles");
	modelBuilder.Entity<Car>().ToTable("Cars");
	modelBuilder.Entity<Bus>().ToTable("Buses");  
  }
}
```

In our case, we want to insert a list of `Vehicle` objects, where the elements can be either `Vehicle`, `Car` or `Bus`
However, when attempting to use `applicationDbContext.BulkInsertAsync(elements)`, we encountered the following error :

> Using 'FromSqlRaw' on DbSet of 'Vehicle' is not supported since 'Vehicle' is part of hierarchy and does not contain a discriminator property.

To resolve this, we added a shadow property `Discriminator`  to all entities in `ApplicationDContext`

```csharp
public class ApplicationDContext 
{

  public DbSet<Vehicle> Vehicles => Set<Vehicle>();
  public DbSet<Car> Cars => Set<Car>();
  public DbSet<Bus> Buses => Set<Bus>();


  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
   modelBuilder.Entity<Vehicle>(entity =>
   {
     entity.HasDiscriminator<string>("Discriminator")
      .HasValue<Vehicle>("Vehicle")
      .HasValue<Car>("Car")
      .HasValue<Bus>("Bus");
   });
  
  
    modelBuilder.Entity<Vehicle>().ToTable("Vehicles");
	modelBuilder.Entity<Car>().ToTable("Cars");
	modelBuilder.Entity<Bus>().ToTable("Buses");  
  }
}
```

However, this resulted in a new error:

> System.AggregateException: One or more errors occurred. (Invalid column name 'Capacity'.
> Invalid column name 'NumberOfSeats'. Invalid column name 'Horsepower'.) ---> Microsoft.Data.SqlClient.SqlException: Invalid column name 'Capacity'.
> Invalid column name 'NumberOfSeats'. Invalid column name 'Horsepower'

The same error occurs when using TPH (e.g. removing the `.ToTable` lines from `ApplicationDContext`)

Is there any way to successfully use `BulkInsert` on a list in this case?

Thanks in advance for your assistance.

**Comment by borisdj** [comment]
First you do should not call _SaveChangesAsync_ when using BulkMethods.

Secondly you need to have 'Discriminator' column set.
One way would be ne expose that property and set it to appropriate table name before calling BulkMethod.
And another option, if you want it to remain Shadow property, than you need first to add list into DbSet with _AddRange_, which will set Disct.col. automatically, after that call _BulkInsertAsync_ (do Not call SaveChangesAsync)

You can take at DiscriminatorShadowTest for sample:
https://github.com/borisdj/EFCore.BulkExtensions/blob/770f46f59f90cd8ff96e0c7988a0a7d81db689a8/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L469-L470
