### ISSUE TITLE
Dictionary error when bulk inserting using TPT, when derived type has converters

### ISSUE THREAD

**Issue by Entroper** [borisdj/EFCore.BulkExtensions#1570]
Using the strategy described here: https://github.com/borisdj/EFCore.BulkExtensions/issues/493

When doing the BulkInsertAsync for the base type, I'm getting an error that says "An item with the same key has already been added. Key: "  The key is the empty string.

I've traced this to [this line of code](https://github.com/borisdj/EFCore.BulkExtensions/blob/9cd5b3a9367780c8b2e9cccb296d016eca5e758e/EFCore.BulkExtensions.Core/TableInfo.cs#L467).  Despite that we've specified PropertiesToInclude in the bulkConfig, this seems to be looping over all properties of the object.  Our derived type has more than one column with a converter defined, so it tries to insert the empty string key twice, and throws.

**Comment by borisdj** [comment]
I have added condition to check if key already exist, can you load the latest library source and if that solves this issue, before I publish new nuget.
