### ISSUE TITLE
BulkInsert does not populate StatsInfo even when CalculateStats = true

### ISSUE THREAD

**Issue by timbapci** [borisdj/EFCore.BulkExtensions#158]
We're trying to BulkInsert new data (that we have already verified to be unique) and need to know how many rows were inserted.
We can see that the BulkInsertOrUpdate uses the Merge command that has the option to return how many rows were inserted/updated, but we need that for a plain insert.
Are we missing something?

**Comment by borisdj** [comment]
I don't the point of StatsInfo with Insert since all would be inserted and you know size of List to be inserted.
But you could still use it, just also need to configure SetOutputIdentity because Merge have to be used.
```C#
var bulkConfig = new BulkConfig { SetOutputIdentity = true, CalculateStats = true };
context.BulkInsert(entities, bulkConfig);
```

**Comment by timbapci** [comment]
Okay, so does that mean that BulkInsert is "all or nothing" then? Even when batching records, if one insert fails within a batch, the whole statement (all batches) is aborted and nothing gets inserted?

**Comment by borisdj** [comment]
BulkInsert forwards data to SqlBulkCopy.
And according to
[SO/does-sqlbulkcopy-upload-any-data-upon-failure](https://stackoverflow.com/questions/22176359/does-sqlbulkcopy-upload-any-data-upon-failure)
If it is not encapsulated in external transaction then each Batch will be one transaction.
You are correct, if BatchSize is set and one Batch fails previous will remain.
