### ISSUE TITLE
Soft Deleted Records Are Incorrectly Marked as Newly Deleted During Each Sync When They Don’t Come from the Source

### ISSUE THREAD

**Issue by TrueGandalf** [borisdj/EFCore.BulkExtensions#1595]
Hello!

I hope this is the right place to ask for guidance, but please feel free to redirect me if there’s a better channel to discuss this.

We regularly sync data into our tables from an external source, and we have a column called UpdatedAt where we store the current DateTime when a record is updated.

Here's an example of how we handle incoming records:

```
foreach (var record in incomingRecords)
{
    record.UpdatedAt = FreezedCurrentDateTime;
    record.CreatedAt = FreezedCurrentDateTime;
}
```

Additionally, we have a column IsDeleted that we use for soft-deleting records that don't come from the source. Our current setup looks like this:

`config.SetSynchronizeSoftDelete<Employee>(x => new Employee { IsDeleted = true, UpdatedAt = _currentDateTimeHandler.FreezedCurrentDateTime });`

The issue we’re facing is that whenever a record isn't received from the source, the library marks it as deleted and updates the UpdatedAt column with the new DateTime, even if it was already soft deleted before. This behavior causes the UpdatedAt value to always get updated, which is not what we need.

Expected Behavior: We’d like to be able to only update the UpdatedAt column if the record wasn’t marked as deleted previously (IsDeleted == false before the sync). However, if the record was already marked as deleted (IsDeleted == true), the UpdatedAt column should remain unchanged.

We tried this simpler approach:

`config.SetSynchronizeSoftDelete<Employee>(x => new Employee { IsDeleted = true });`

But the problem with this is that while it changes the IsDeleted value, it doesn’t update the UpdatedAt column when switching from false to true.

Could you please advise on how to solve this? Is it possible to achieve this using the current configuration mechanisms in the library, or would this require changes? If it’s not possible with the current setup, I’d be happy to explore contributing a pull request—just need some guidance on where to start.

Thank you in advance for your help!

**Comment by borisdj** [comment]
Check in ReadMe **_PropertiesToExcludeOnCompare_** to add into it _FreezedCurrentDateTime_, but not sure if it will solve this case, you have to test it or some variation.
As for adding specific the feature you would have to figureout how to do it using Sql and/or combining exiting extension methods, then implementing it wouldn't ba a big issue. But I am not sure what sql can achieve such behaviour.

**Comment by TrueGandalf** [comment]
Thank you for your response!

I appreciate your insights regarding the PropertiesToExcludeOnCompare; however, I want to clarify that I have already implemented it, including the UpdatedAt field, in my configuration:

```
public BaseTransBulkConfig(List<string> updateByProperties)
{
    base.PropertiesToExclude = new List<string>// don't update those even on insert
    {
        nameof(BaseTransactionalEntity<int>.Id),
    };
    PropertiesToExcludeOnUpdate = new List<string>// those are insert-only columns
    {
        nameof(BaseTransactionalEntity<int>.Id),
        nameof(BaseTransactionalEntity<int>.CreatedAt),
        nameof(BaseTransactionalEntity<int>.CreatedBy),
    };
    PropertiesToExcludeOnCompare = new List<string> // can insert/update those but don't compare
    {
        nameof(BaseTransactionalEntity<int>.Id),
        nameof(BaseTransactionalEntity<int>.CreatedAt),
        nameof(BaseTransactionalEntity<int>.UpdatedAt),
        nameof(BaseTransactionalEntity<int>.CreatedBy),
        nameof(BaseTransactionalEntity<int>.UpdatedBy),
    };
    UpdateByProperties = updateByProperties;

    BatchSize = 4000;
}
```

Given this setup, relying solely on PropertiesToExcludeOnCompare does not address my request.

I plan to explore how to achieve my goal using SQL/Merge. The main concept is to compare not only the incoming record data but also the corresponding data already present in the database, to inform decision-making.

For example, the following approach is not effective, even in theory:

```
config.SetSynchronizeSoftDelete<Employee>(
    x => x.IsDeleted == false // but it will only work if we take isDeleted from db and not from incoming data
        ? new Employee
        {
            IsDeleted = true,
            UpdatedAt = new DateTime(2222, 02, 02, 02, 02, 02, 02) //_currentDateTimeHandler.FreezedCurrentDateTime
        }
        : new Employee
        {
            IsDeleted = true
            // Don't set UpdatedAt at all when IsDeleted is true.
        }
    );
```

I would greatly appreciate any suggestions or guidance on how to effectively implement this comparison logic. Thank you for your assistance!

**Comment by borisdj** [comment]
One more idea, there is also config **_SetSynchronizeFilter_**:
-_A method that receives and sets expresion filter on entities to delete when using BulkInsertOrUpdateOrDelete. Those that are filterd out will be ignored and not deleted._

You could combine both methods, so that SyncFilter makes already Deleted to be ignored, that way they their Date would not be altered.
`config.SetSynchronizeFilter<Employee>(a => a.IsDeleted == false);`
