### ISSUE TITLE
PostgreSQL BulkInsertAsync doesn't set value to columns which have default value set

### ISSUE THREAD

**Issue by Sharpeli** [borisdj/EFCore.BulkExtensions#1597]
### **Z.EntityFramework.Extensions.EFCore 8.103.6 **

When we use `await Context.BulkInsertAsync(list);`
Looks it only set values to columns which don't have a default value set.
For all columns which have default values set, it only insert the default value.
For example.
`   entity.Property(e => e.PropertyA)
       .HasPrecision(18, 2)
       .HasDefaultValueSql("0");`
It set all value of `PropertyA` to 0 even different values are provided.

For columns that don't have a default vaue, it works fines.
This works fine, all PropertyB has value in the database.
`entity.Property(e => e.PropertyB).HasPrecision(15, 4);`

**Comment by Sharpeli** [comment]
Wrong place

**Comment by UrosBgd** [comment]
@Sharpeli I can confirm that this issue is still relevant in the lastest package version. Why did you close it?
