### ISSUE TITLE
Using parallel BulkInsertAsync fails

### ISSUE THREAD

**Issue by obriankevin11** [borisdj/EFCore.BulkExtensions#160]
Hi,

I try to insert a user and its collections of groups, projects and ideas.

For now I'm using this:

            await _context.Users.AddAsync(user);
            await _context.SaveChangesAsync();

Thing is it's super slow (12 sec, user has 4000 groups and 4000 projects), so I try to use your lib which seems great 🥇 

This works:

    var list = new List<User> {userEntity};
    await _context.BulkInsertAsync(list, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true });

    user.Groups.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id; });
    user.Projects.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id;  });
    user.Ideas.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id; });

    await _context.BulkInsertAsync(user.Groups.ToList());
    await _context.BulkInsertAsync(user.Projects.ToList());
    await _context.BulkInsertAsync(user.Ideas.ToList());

This doesn't work:

    using (var transaction = _context.Database.BeginTransaction())
    {
        var conf = new BulkConfig {PreserveInsertOrder = true, SetOutputIdentity = true};
        var list = new List<Entities.User> {user};
        await _context.BulkInsertAsync(list, conf);

        user.Groups.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id; });
        user.Projects.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id; });
        user.Ideas.ToList().ForEach(p => { p.Id = Guid.NewGuid(); p.UserId = userEntity.Id; });

        var taskProjects = _context.BulkInsertAsync(user.Projects.ToList(), conf);
        var taskGroups = _context.BulkInsertAsync(user.Groups.ToList(), conf);
        var taskIdeas = _context.BulkInsertAsync(user.Ideas.ToList(), conf);

        await Task.WhenAll(taskProjects, taskGroups, taskIdeas )
            .ContinueWith(p => transaction.Commit());
    }

1/ Why do I have to explicitly set p.Id = Guid.NewGuid() while those Id properties have their HasDefaultValueSql set to "newid()"?

2/ why does the parallel insert of Projects, Groups and Ideas doesn't work?

> [10:03:57 ERR] An error occurred using a transaction.
> System.InvalidOperationException: This SqlTransaction has completed; it is n
> nger usable.
>    at System.Data.SqlClient.SqlTransaction.ZombieCheck()
>    at System.Data.SqlClient.SqlTransaction.Commit()
>    at Microsoft.EntityFrameworkCore.Storage.RelationalTransaction.Commit()

3/ I wrote InMemory tests that work with the 2 lines of code way. They fail with BulkInsertAsync. Any idea?

Thanks!

**Comment by borisdj** [comment]
1. Only Identity column, when used, is created in Db.
Guid, even with HasDefaultValueSql has to be set, that's how it's currently implemented.

2. Not sure, but what I can notice is that for async method you should probaly use TransactionAsync:
```using (var transaction = await context.Database.BeginTransactionAsync())```
If problem remains try make a test similar to one EFCoreBulkTestAsync, where it can be reproduced.

3. Bulk Tests can not have UseInMemoryDb because InMemoryProvider does not support Relational-specific methods.

**Comment by obriankevin11** [comment]
1. ok
2. depends on 3. If I cannot write tests I can't use the lib.
3. My existing tests are using Microsoft.EntityFrameworkCore.Sqlite and InMemory mode, which is a In memory Relational db provider in (https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite). Do you think it'd be achievable?

**Comment by borisdj** [comment]
3. I don't think so. It comes down to the fact that SqlBulkCopy is only for SQL Server.
But here is an interesting idea:
To make a wrapper around SqlBulkCopy for testing purposes only (last post):
[SO/connecting-to-a-sqllite-db-with-sqlbulkcopy](https://stackoverflow.com/questions/47190192/connecting-to-a-sqllite-db-with-sqlbulkcopy)

**Comment by jcasale** [comment]
```cs
var taskProjects = _context.BulkInsertAsync(user.Projects.ToList(), conf);
var taskGroups = _context.BulkInsertAsync(user.Groups.ToList(), conf);
var taskIdeas = _context.BulkInsertAsync(user.Ideas.ToList(), conf);
```

> 2/ why does the parallel insert of Projects, Groups and Ideas doesn't work?

You cannot skip the await in the lines above. Since you don't await the calls, the second and third continue to run before the first is complete (exactly what you want), however this is not supported by ef:

[Asynchronous Queries](https://docs.microsoft.com/en-us/ef/core/querying/async)
[Asynchronous Saving](https://docs.microsoft.com/en-us/ef/core/saving/async)

Either await them all, or remove the async operation.

**Comment by borisdj** [comment]
SQLite is now also supported, from version 2.6.0

**Comment by sonnd92** [comment]
> ```cs
> var taskProjects = _context.BulkInsertAsync(user.Projects.ToList(), conf);
> var taskGroups = _context.BulkInsertAsync(user.Groups.ToList(), conf);
> var taskIdeas = _context.BulkInsertAsync(user.Ideas.ToList(), conf);
> ```
> 
> > 2/ why does the parallel insert of Projects, Groups and Ideas doesn't work?
> 
> You cannot skip the await in the lines above. Since you don't await the calls, the second and third continue to run before the first is complete (exactly what you want), however this is not supported by ef:
> 
> [Asynchronous Queries](https://docs.microsoft.com/en-us/ef/core/querying/async)
> [Asynchronous Saving](https://docs.microsoft.com/en-us/ef/core/saving/async)
> 
> Either await them all, or remove the async operation.

`await Task.WhenAll(taskProjects, taskGroups, taskIdeas )
        .ContinueWith(p => transaction.Commit());`
This line of code await them all.

Btw, I have met same issue when try to do BulkInsertAsync parallelly. The library throw the exeption:
`System.InvalidOperationException: Invalid operation. The connection is closed`
And I'm using Entity Framework Core 3.1.0 and MSSQL Server 2014.

**Comment by Numpsy** [comment]
As the linked MS docs say, EFCore contexts aren't thread safe, so you can't use one context from several tasks in parallel:

```
EF Core doesn't support multiple parallel operations being run on the same context instance. 
```
