### ISSUE TITLE
Postgres UNLOGGED TABLE support?

### ISSUE THREAD

**Issue by MSandro** [borisdj/EFCore.BulkExtensions#1601]
UNLOGGED TABLE could lead to highly accelerated inserts in some cases, but to my knowledge it is not yet supported by EFCore.BulkExtensions

https://andyatkinson.com/blog/2021/09/29/unlogged-tables-bulk-inserts-returning

**Comment by borisdj** [comment]
Support added with new config **UseUnlogged**, changes are commited.
Will be released with new nuget in a few days, you can use source if you want to test it now.
