### ISSUE TITLE
Signing the nuget package

### ISSUE THREAD

**Issue by wowyzga** [borisdj/EFCore.BulkExtensions#161]
Could you please sign the nuget package.  I'm getting errors when including your package in a project:
Error	CS8002	Referenced assembly 'EFCore.BulkExtensions, Version=2.4.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by SailorTurkey** [comment]
I have this problem reversed. My project is NOT signed, nor ise EFCore.BulkExtensions. But God knows why, its referencing FastMember SIGNED, Please release a nuget package referencing UNSIGNED FastMember package too, thank you.

**Comment by borisdj** [comment]
In latest Nuget FastMember.Signed is replaced with FastMember.
As for the signed verison of lib. I couldn't find a Certificate to Sign it properly.

**Comment by danstur** [comment]
@borisdj Would you accept a PR that handles this? The idea would be to fix the AssemblyVersion and only increase it when the major version is increased (i.e. when breaking changes are introduced).

This gives what I'd consider the best experience: You get a warning if you try to use incompatible versions, which you can explicitly ignore with binding redirects. For minor versions if two NuGet packages require different versions, NuGet resolves the higher version which is then installed. No binding redirects are needed and everything just works as it should.

I'd simply add an additional csproj, but share all the relevant information between the two projects to avoid duplication.

**Comment by 304NotModified** [comment]
Please sign this package. All MS packages are signed and other large OSS projects are doing this. (e.g. Json.NET)

If we are doing semver here, it's recommend to use only the major version name in your assembly. (so 1.0.0.0, 2.0.0.0 and currently 3.0.0.0) - also others are doing that (like Json.NET)

**Comment by flensrocker** [comment]
@borisdj You don't need a certificate.

- Call `sn -k EFCore.BulkExtensions.snk` in the directory `EFCore.BulkExtensions` to create a key pair.
- Add this file to the repository
- Edit the properties of the project on the signing tab: activate signing and select the snk-file
- Use `FastMember.Signed` instead of `FastMember`

Diff of the project file:
```
diff --git a/EFCore.BulkExtensions/EFCore.BulkExtensions.csproj b/EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
index 5422d85..49d2d53 100644
--- a/EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
+++ b/EFCore.BulkExtensions/EFCore.BulkExtensions.csproj
@@ -14,10 +14,12 @@
     <PackageReleaseNotes>Nugets updated; Fixes: TimeStamp column, Abstract base type, Contains query, BatchUpdate Sqlite</PackageReleaseNotes>
     <AssemblyVersion>3.1.1.0</AssemblyVersion>
     <FileVersion>3.1.1.0</FileVersion>
+    <SignAssembly>true</SignAssembly>
+    <AssemblyOriginatorKeyFile>EFCore.BulkExtensions.snk</AssemblyOriginatorKeyFile>
   </PropertyGroup>

   <ItemGroup>
-    <PackageReference Include="FastMember" Version="1.5.0" />
+    <PackageReference Include="FastMember.Signed" Version="1.5.0" />
     <PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.1" />
     <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3" />
     <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.3" />
```

**Comment by borisdj** [comment]
5.0.6 is now Strong named.
What I got from [sign assembly](https://www.myoddweb.com/2020/06/21/strong-name-signing-your-assemblies/) is that generated private key should be committed into repository, is that correct approach?
At [strong-named](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named) it is stated : '_If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system._'
Also [SO-WhyIncludePK](https://stackoverflow.com/questions/36141302/why-is-it-recommended-to-include-the-private-key-used-for-assembly-signing-in-op)

**Comment by flensrocker** [comment]
Yes, just check in the generated snk without a password.  
With this, forkers can build an own assembly with the same key, so they can drop it in as an replacement.

**Comment by borisdj** [comment]
Finished

**Comment by flensrocker** [comment]
Thanks for this package! 👍

**Comment by flensrocker** [comment]
For those who need a signed assembly for an older version (in my case 2.4.1 because of EF Core 2.1), execute the following commands in an empty temp-directory (adjust):
```
nuget install -OutputDirectory . -Version 2.4.1 EFCore.BulkExtensions
ildasm EFCore.BulkExtensions.2.4.1\lib\netstandard2.0\EFCore.BulkExtensions.dll /out:EFCore.BulkExtensions.il
ilasm EFCore.BulkExtensions.il /resource=EFCore.BulkExtensions.res /dll /key=path\to\EFCore.BulkExtensions.snk
```
add the dll to your repository and then reference it in all projects where you need it:
```
  <ItemGroup>
    <Reference Include="EFCore.BulkExtensions">
      <HintPath>..\relative\path\to\EFCore.BulkExtensions.dll</HintPath>
    </Reference>
  </ItemGroup>
```
