### ISSUE TITLE
Any way to exclude unused connectors?

### ISSUE THREAD

**Issue by nikriaz** [borisdj/EFCore.BulkExtensions#1614]
Hi, many thanks for your excellent package!

There is a small issue. `Microsoft.EntityFrameworkCore.Relational` was updated to the version 9.0 (even for Net 8) but `Pomelo.EntityFrameworkCore.MySql` which you use as a connector to mySQL requires 8.0.x and their beta requires Net 9 so I have a little hope from their side to resolve the warning. 

I only use MS SQL and I believe most of users use single DB as well. Maybe there is a way to exclude unused dependencies? 

P.S. I suppressed warning so far like this:
```
<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.0" NoWarn="NU1608" />
```

**Comment by borisdj** [comment]
For the moment you can use specific adapter nuget instead of the main one, so for MS SQL it would be **_EFCore.BulkExtensions.SqlServer_**
https://www.nuget.org/packages/EFCore.BulkExtensions.SqlServer
