### ISSUE TITLE
TableInfo:GetPropertyUnambiguous always return null

### ISSUE THREAD

**Issue by martosource** [borisdj/EFCore.BulkExtensions#1621]
Hi,

I have add an issue with Bulk Insert with PreserveInsertOrder and SetOutputIdentity set to true.  

The output is not sorted by the primary key due to TableInfo:GetPropertyUnambiguous always returning null.

Line 709 in TableInfo.cs needs to be changed to:

`
var property = type.GetProperty(name, BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.Instance);
`

https://stackoverflow.com/questions/1544979/using-getproperties-with-bindingflags-declaredonly-in-net-reflection

Thanks

**Comment by martosource** [comment]
This is linked to issue #1604

**Comment by Zinoberous** [comment]
This has also caused problems with default values: [#1622](https://github.com/borisdj/EFCore.BulkExtensions/issues/1622)

**Comment by borisdj** [comment]
PR with proposed fix is merged, will be published with next nuget version.
