### ISSUE TITLE
batch modification

### ISSUE THREAD

**Issue by hailang2ll** [borisdj/EFCore.BulkExtensions#163]
UpdateBulk<TEST>(q => new TEST
                    {
                        Flag =0,
                        Status = 0,
                        PayPrice = (payStatusFlag == (int)EnumPayStatusFlag.Complete ? q.OrderPrice : q.OrderPrice * summaryOrderMst.Discount),
                    }, q => q.No == No);

Operator evaluation is not supported for batch modification

**Comment by hailang2ll** [comment]
Message=variable 'q' of type 'Order.Repository.Models.OrdOrder' referenced from scope '', but it is not defined，StackTrace=   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node,

**Comment by borisdj** [comment]
I'm not sure I understand the question.
BatchUpdate should be called like this:
```C#
query.Where(q => q.No == No).BatchUpdate(q => new TEST
{
  Flag =0,
  Status = 0,
  PayPrice = (payStatusFlag == (int)EnumPayStatusFlag.Complete ? q.OrderPrice : q.OrderPrice * summaryOrderMst.Discount)
});


```

**Comment by hailang2ll** [comment]
You can try the following methods, thank you。

service.GetQueryable<SysJobLog>().Where(q => q.JobLogId <= 10).BatchUpdate(q => new SysJobLog
            {
                Message = q.Message + 333,
                Name = (q.JobLogType * 2) + "",
            });
System.Data.SqlClient.SqlException:“在将 nvarchar 值 '我是被跟踪的6' 转换成数据类型 int 时失败。”

=======================================
 service.GetQueryable<SysJobLog>().Where(q => q.JobLogId <= 10).BatchUpdate(q => new SysJobLog
            {
                Message = q.Message + 333,
                Name = Utility.Ex4s5R(q.JobLogType * 2) + "",
            });

System.InvalidOperationException:“variable 'q' of type 'DMS.EntityFrameworkCore.Repository.Models.SysJobLog' referenced from scope '', but it is not defined”

**Comment by hailang2ll** [comment]
int status = 0;
            int a = service.GetQueryable<SysJobLog>().Where(q => q.JobLogId <= 10).BatchUpdate(q => new SysJobLog
            {
                Message = q.Message + "33",
                Name = status == 0 ? (q.JobLogType * q.JobLogId) + "77" : "uuuuu",
            });

System.InvalidOperationException:“variable 'q' of type 'DMS.EntityFrameworkCore.Repository.Models.SysJobLog' referenced from scope '', but it is not defined”

**Comment by borisdj** [comment]
You can't use external function like _Utility.Ex4s5R_, nor Conditional(Ternary) operator _? :_
I have updated previous answer with possible solution.
