### ISSUE TITLE
Upsert increases value of one column

### ISSUE THREAD

**Issue by tomnagly** [borisdj/EFCore.BulkExtensions#165]
Hi,

I love your extension and it works great for me.

I'm just curious, is there any way to use a previous column value with BulkInsertOrUpdate method, to not update with fixed value, but adding it to existing one?

Here's simple explanation : 
Imagine that I've got a product table:
`----PRODUCT-----`
`--ID---QUANTITY-`
`---1-------5--------`
`---2-------5--------`
`---3-------3--------`

Now I want to either insert new product or add quantity value to existing record, so upserting with following:

`----PRODUCT-----`
`--ID---QUANTITY-`
`---1-------1-----`
`---4-------2-----`

Would result with:
`----PRODUCT-----`
`--ID---QUANTITY-`
`---1-------6-----`
`---2-------5-----`
`---3-------3-----`
`---4-------2-----`

I want an update to look something like this: 
`UPDATE Product SET Product.Quantity = Product.Quantity + 5`

Is it possible with your bulk extension?

**Comment by borisdj** [comment]
It is by using also BulkRead.
Here is how it could be done:
```C#
using (var context = new TestContext(ContextUtil.GetOptions()))
{
    var entities = new List<Item>
    {
        new Item() { ItemId = 1, Quantity = 1 }, // this one exist in Db and has Q. 1 (1 + 1 will become 2)
        new Item() { ItemId = 2, Quantity = 3 }, // this one is New
    };

    var entitiesToLoad = entities.Select(a => new Item { ItemId = a.ItemId, Quantity = -1 }).ToList();
    context.BulkRead(entitiesToLoad); // Those where Quantity remains -1 are New
    var dict = entitiesToLoad.Where(a => a.Quantity > 0).ToDictionary(a => a.ItemId, a => a.Quantity);

    foreach (var entity in entities)
    {
        if (dict.ContainsKey(entity.ItemId))
        {
            entity.Quantity += dict[entity.ItemId];
        }
    }

    context.BulkInsertOrUpdate(entities);
}
```
