### ISSUE TITLE
SetOutputIdentity composite primary key when a part of the primary key is auto incremented

### ISSUE THREAD

**Issue by Detzito** [borisdj/EFCore.BulkExtensions#166]
I can't find a way to bulkInsert entities and subentities using SetOutputIdentity when using composite primary keys.

I have the following classes : 

```
public class MainEntity {

    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
  
    [Key]
    public int TenantId { get; set; } // set manually, reference to a Tenant table

    public List<SubEntity> SubEntities { get; set; }
}

public class SubEntity {
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
  
    [Key]
    public int TenantId { get; set; }

   public MainEntity Parent { get; set; }

   public int ParentId { get; set; } // FK is defined in mobelbuilder as { ParentId, TenantId }
}
```

I try to insert one MainEntity but I get this exception :

`Cannot insert explicit value for identity column in table 'MainEntity' when IDENTITY_INSERT is set to OFF.`

with the following code : 

```
List<MainEntity> entities = new List<MainEntity>();
entities.Add(new MainEntity { TenantId = 1 });
_context.BulkInsert(entities, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true });
```

If i don't use the SetOutputIdentity, MainEntity is created, but the Id is not Database Generated (keep 0 after the bulkInsert) so if I create subEntities, setting their ParentId to the MainEntity.Id, they are orphan...

Any solution ?

**Comment by borisdj** [comment]
Having Composite Key and using one of them also as Identity is unusual.
If _Id_ column is Identity then why not just have _TenantId_ as regular ForeignKey.
Using both is not supported, but I will put enhancement Tag.

**Comment by ptfuller** [comment]
I'm working on a legacy db where there are many tables which have composite keys where one of them is Identity.  I've submitted above PR for this reason.

Thanks for the great tool!
