### ISSUE TITLE
Stream BulkInsert

### ISSUE THREAD

**Issue by devel112** [borisdj/EFCore.BulkExtensions#168]
Q: Is it possible to stream insert data from an enumerable with unknown length?

Use case would be importing data from another database, transforming it, and bulkinserting it without batching and using memory

**Comment by borisdj** [comment]
I'am not sure how you want to use it.
SqlBulkCopy has _bool property [EnableStreaming](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy.enablestreaming?view=netframework-4.7.2)_
Check if setting this would work for your situation and if it does it could be exposed in BulkConfig.

**Comment by devel112** [comment]
Ok I'll make an example soon

**Comment by devel112** [comment]
EnableStreaming worked perfectly! I didn't bother to check what part of the IList interface was used when bulkinserting, but it seems only Count and IEnumerable interface is used in my case, sry.

[Example using EnableStreaming to transfer data from one db to another without batching](https://github.com/devel112/streamingbulkinsert)

**Comment by jammehcow** [comment]
Hey @devel112, are you either able to restore that repository or create a gist from it (or I can create a gist if you don't want to upload it)? This is the only example I could find in this repo's issues and the link is dead :\

**Comment by borisdj** [comment]
@devel112 do you still have this example to repost it ?
