### ISSUE TITLE
Remove new() constraint from IQueryable.Batch* extensions

### ISSUE THREAD

**Issue by SzymonKatra** [borisdj/EFCore.BulkExtensions#169]
I'd like to use Batch* extension methods on types which don't provide a public parameterless constructor. Is it possible to remove `new()` generic constraint?

For now, I'm forced to implement public constructor which I don't want to use anywhere.
I'm using `BatchUpdate` like that:
`queryable.BatchUpdate(x => new MyEntity(null) { Something = true })`

  
My other proposition is to add an extension method which accepts anonymous types, like: `queryable.BatchUpdate(x => new { Something = true })`
But in this case, we lose compile-time check for correctness of property name.

**Comment by borisdj** [comment]
new() is required because of:
https://github.com/borisdj/EFCore.BulkExtensions/blob/18cc1501cc39aa512b36d7d9ba4570ed633b2dde/EFCore.BulkExtensions/BatchUtil.cs#L80

**Comment by borisdj** [comment]
`new()` removed from BatchUpdate with Expression.
NuGet 2.4.5
