### ISSUE TITLE
Contains clause not works as well in BatchUpdate

### ISSUE THREAD

**Issue by igorbmaciel** [borisdj/EFCore.BulkExtensions#170]
I tried to use contains in where no save expected when converted to a query, that query using IN clause, but this is not work, when convert to a SQL query, it's not using WHERE clause.

My Code:

 Context.PropertyCurrencyExchanges
             .Where(p => quotationCurrencyDtoList.Select(x => x.Id).Contains(p.Id))
             .IgnoreQueryFilters()
             .BatchUpdate(p => new PropertyCurrencyExchange { ExchangeRate = 1 / (oldPropertyExchangeRate / p.ExchangeRate) * newPropertyExchangeRate });

SQL tranformation:

exec sp_executesql N'UPDATE [p] SET  [p].[ExchangeRate] = @param_0 / @param_1 / [p].[ExchangeRate] * @param_2 
FROM [PropertyCurrencyExchange] AS [p]',N'@param_0 decimal(1,0),@param_1 decimal(4,4),@param_2 decimal(3,2)',@param_0=1,@param_1=1,@param_2=4.10

**Comment by borisdj** [comment]
Can you reproduce it in BatchTest.
In RunBatchUpdate I have replaced following code (line 48):
```C#
var query = context.Items.Where(a => a.ItemId <= 500 && a.Price >= 0);`
```
with
```C#
var listId = context.Items.Where(a => a.ItemId <= 500 && a.Price >= 0).Select(a => a.ItemId).ToList();
var query = context.Items.Where(a => listId.Contains(a.ItemId));
```
And the test passed successfully.
