### ISSUE TITLE
BulkInsert on Nested one-to-many relationship

### ISSUE THREAD

**Issue by ddavidtran** [borisdj/EFCore.BulkExtensions#176]
I'm currently working on a ASP.NET Core project which uses Entity Framework Core with database provider SQL Server. I have multiple entities with multiple relationships between them, and I want to learn how to insert these entities using EFCore.BulkExtensions

Examples of my entities (simplified, not real entities in my project):

__Student__:
```cs
public class Student
{
 public int StudentId {get;set;}
 public string StudentName {get;set;}
 public List<Course> Course{ get; } = new List<Course>();
}
```

__Course__:
```cs
public class Course
{
 public int CourseId {get;set;}
 public string CourseName {get;set;}

 public int StudentId {get;set;}
 public Student Student {get;set;}

 public List<Grade> Grades{ get; } = new List<Grade>();
}
```

__Grade__:
```cs
public class Grade
{
 public int GradeId {get;set;}
 public string GradeValue{get;set;}

 public int CourseId {get;set;}
 public Course Course {get;set;}
}
```

Student has a _one-to-many_ relationship with Course.

Course has a _one-to-many_ relationship with Grade.

It works when mapping one student to many courses, a simple parent-child relationship with the following code:
```cs
int i = 0;
foreach (var student in students)
{
 student.StudentId = ++i;
}
using (var transaction = context.Database.BeginTransaction())
{
 context.BulkInsertOrUpdate(students, new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true});

 var courses= new List<Course>();
 foreach(var student in students)
 {
   foreach (var course in student.Courses)
   { 
     course.StudentId= student.StudentId;
   }
   courses.AddRange(student.Courses);
 }

context.BulkInsertOrUpdate(courses);
transaction.Commit()
}
```

However, when trying to add grades into context, it gets more complicated. I have tried an approach but it crashes. Here is the updated code:

```cs
int i = 0;
foreach (var student in students)
{
 student.StudentId = ++i;
}
using (var transaction = context.Database.BeginTransaction())
{
 context.BulkInsertOrUpdate(students, new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true});

 var courses= new List<Course>();
 foreach(var student in students)
 {
   foreach (var course in student.Courses)
   { 
     course.StudentId= student.StudentId;
   }
   courses.AddRange(student.Courses);
 }

context.BulkInsertOrUpdate(courses, new BulkConfig{ SetOutputIdentity = true, PreserveInsertOrder=true });

int index = 0;
foreach (var course in courses)
{
 course.CourseId= ++index;
}

 var grades = new List<Grade>();

 foreach(var course in courses)
 {
   foreach (var grade in course.Grades)
   { 
     grade.CourseId= course.CourseId;
   }
   grades.AddRange(course.Grades);
 }
context.BulkInsertOrUpdate(grades); //Crashes here.
transaction.Commit()
}
```

Is there any simpler/better approach to insert nested one-to-many entities?
I have an implementation where I have a dictionary of Student as key and a student's associated courses as value. `Dictionary<Student,List<Course>>`. Each course has elements of Grade. If it helps during insertion

EDIT: After some debugging, I noticed that after `context.BulkInsertOrUpdate(courses, new BulkConfig{ SetOutputIdentity = true, PreserveInsertOrder=true });` the `List<Grade>` in each class Course where magically deleted. In other words, each course initally had elements of grades, after calling BulkInsertOrUpdate, it got removed.

EDIT 2: I managed to solve this by adding a count to Courses in order to adhere to *PreserveInsertOrder*. If you have any other approach, feel free to edit my approach! 

Updated code:
```cs
int i = 0;
foreach (var student in students)
{
 student.StudentId = ++i;
}
using (var transaction = context.Database.BeginTransaction())
{
 context.BulkInsertOrUpdate(students, new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true});

 var courses= new List<Course>();
 int j = 0; //Added this!
 foreach(var student in students)
 {
   foreach (var course in student.Courses)
   { 
     course.CourseId = ++j; //Added this!
     course.StudentId= student.StudentId;
   }
   courses.AddRange(student.Courses);
 }

context.BulkInsertOrUpdate(courses, new BulkConfig{ SetOutputIdentity = true, PreserveInsertOrder=true });

 var grades = new List<Grade>();

 foreach(var course in courses)
 {
   foreach (var grade in course.Grades)
   { 
     grade.CourseId= course.CourseId;
   }
   grades.AddRange(course.Grades);
 }
context.BulkInsertOrUpdate(grades); 
transaction.Commit()
}
```
EDIT 3: After more debugging and testing, when inserting from a new database, it works everytime. However, when using `BulkInsertOrUpdate` a second time, it usually skips the whole transaction. Is it the expected behaviour when using `BulkInsertOrUpdate` with exactly the same data as the previous insertion?

Thanks,

**Comment by borisdj** [comment]
In ReadMe there is info about BulkOps with parent-child tables, and remarks about usage *PreserveInsertOrder* and *SetOutputIdentity*.
But I see that you have figured that already.
As for the InsertOrUpdate-ing same data again, it will update all but since it is the same there is no change in Db.

**Comment by ddavidtran** [comment]
Thanks for the reply. Great extension!
One question, sometimes either my transaction just skips (it gets to `context.BulkInsertOrUpdate()` and kicks out from the transaction scope and sometimes I get _Win32Exception: The wait operation timed out._ during `BulkInsertOrUpdate()` (it didn't happen before). Do you know the reason as of it just skips the bulk ops? For the time out I guess I need to increase the timeout value, however I did not get that before.
