### ISSUE TITLE
Batch operations: Inner query parameters are passed in the clear

### ISSUE THREAD

**Issue by vladhorby** [borisdj/EFCore.BulkExtensions#177]
When the original query used for the Batch operation contains parameters, they are passed in the clear (as values instead of query parameters) to the generated SQL query.
Example:
`var now = DateTimeOffset.UtcNow;`
`var query = context.Items.Where(x => x.Id <= maxBatchId);`
`await query.BatchUpdateAsync(new Item() { LastSeenOn = now });`

Expected query:
`UPDATE [item] SET [LastSeenOn] = @LastSeenOn
FROM [Items] AS [item]
WHERE [x].[Id] <= @__maxBatchId_0`

Actual query:
`UPDATE [item] SET [LastSeenOn] = @LastSeenOn
FROM [Items] AS [item]
WHERE [x].[Id] <= CAST(1000 AS bigint)`

This is a bigger problem when trying to optimize queries on Sql Server, because it doesn't recognize the queries as being the same.

I managed to find a solution, by modifying IQueryable.ToSql() to extract and pass the original parameters back to the Batch query generators.

`var parameterExpression = modelGenerator.ExtractParameters(diagnosticsLogger, query.Expression, parameterValues);`
`var queryModel = modelGenerator.ParseQuery(parameterExpression);`

I'll submit a PR with my changes.

**Comment by borisdj** [comment]
Published NuGet 2.4.8

**Comment by borisdj** [comment]
There is an issue with _ToParametrizedSql()_ when having Contains https://github.com/borisdj/EFCore.BulkExtensions/pull/203
I have made a temporary fix, in a way that ToParametrizedSql() in not used when having Contains (which maps to ' IN ' in sql):
https://github.com/borisdj/EFCore.BulkExtensions/blob/8e72267a5e1b0b08c7c3f977805dbf5e540aad31/EFCore.BulkExtensions/BatchUtil.cs#L66-L71
If you can take a look.
