### ISSUE TITLE
Bulk Insert SetOutputIdentity keep child properties without using PreserveInsertOrder

### ISSUE THREAD

**Issue by kakins** [borisdj/EFCore.BulkExtensions#179]
I have tried very hard to read, follow, and understand the documentation as well as other issues submitted in this repo.  I'm still having a lot of trouble.

BulkInsert with PreserveInsertOrder and SetOutputIdentity is not returning me the actual database-generated identity of the entity, but some other number.
![image](https://user-images.githubusercontent.com/14915247/56619543-871c2780-65eb-11e9-9593-3fde079bcf84.png)

Here we can see that the db CostingAllocationIntervalID does not match the one returned in the object.
![image](https://user-images.githubusercontent.com/14915247/56619678-fa259e00-65eb-11e9-98af-7060d9e113a9.png)

If I try `PreserveInsertOrder = false`, the actual database generated identities are returned, however my list of related `Details` is cleared. 

Is there a way I could **keep** my child `Details` list without using PreserveInsertOrder?

**Comment by vslee** [comment]
Might need to increment your PK prior to insertion, such as here #164

**Comment by kakins** [comment]
@vslee Thanks for the response.  I found this out sometime after creating the issue.  I think it needs to be more clearly documented.  I read over the docs for bulk insert probably 10-15 times before I finally stumbled upon the fact that I need to manually increment the identity PK in _code_ to try and "match" the actual PK generated by the db.

**Comment by kakins** [comment]
I'll close this for now because the underlying issue has been resolved, I need to manually "track" db generated identities of parent objects when inserting child objects into the db.

**Comment by vslee** [comment]
Just to clarify, you don't need to set the PK in code to be the same as it is in the DB. That would defeat the whole purpose of SetOutputIdentity. Instead, what you do is set the PKs to be in sequential order prior to insertion. Then, assuming that your PK is Identity (set by DB), after insertion, BulkExtensions will set the PK correctly. (as long as you also do PreserveInsertOrder)

**Comment by kakins** [comment]
@vslee I'm still not quite following.  

This is what ended up working for me.   Is this correct?

1. Get the count of existing parent items from the db, and increment the "nextId", or PK "order" in this case 
2. Loop through my new parent items and set the PK to the nextId.
3. Insert my parent items.
4. Loop through my child items of each parent and set the child item FK to the PK of the parent.
5. Insert the child items.

![image](https://user-images.githubusercontent.com/14915247/56831899-026e1b00-6830-11e9-898c-ed2ede8e4ce5.png)

**Comment by vslee** [comment]
Sure, you can do it that way. But I think you're making it a lot more complicated than it needs to be. 
First, you don't need to start the nextId incrementing from CostingAllocationIntervals.Count(). You can start from zero. Sounds weird like it might have a collision, but when you insert, it knows that it's a new one and will assign it an appropriate Id anyhow. 
Second, I don't think you need to do the last line (BulkUpdateAsync), but try it and see if I'm right.

**Comment by borisdj** [comment]
@kakins you can simplify code as @vslee stated.
From README:
> **PreserveInsertOrder**
> But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300.
> Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.

And no need for last line (BulkUpdateAsync).
Also when doing Bulk Insert to multiple tabels it is good practice to have them in Transaction scope like:
```C#
using (var transaction = context.Database.BeginTransaction())
{
    var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };
    context.BulkInsert(entities, bulkConfig);
    foreach (var entity in entities)
    {
        ...
    }
    context.BulkInsert(subEntities);
    transaction.Commit();
}
```
