### ISSUE TITLE
Bulk Insert into multiple tables  concurrently

### ISSUE THREAD

**Issue by manojkumaraut** [borisdj/EFCore.BulkExtensions#180]
Hi Team,
Is there any way to bulk Insert into multiple tables  concurrently using EFCore.BulkExtensions?

Thanks and appreciate your help

**Comment by borisdj** [comment]
I have tested concurrently Inserts.
But you can try it, more info here:
https://www.adathedev.co.uk/2011/01/sqlbulkcopy-to-sql-server-in-parallel.html
And it seems that this can be done only into an unindexed table:
[Importing Data in Parallel with Table Level Locking](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms186341(v=sql.90))

Also deadlock can be an issue:
[deadlock-when-using-sqlbulkcopy-to-concurrently-insert-rows-into-a-single-nonempty-table](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/932cd26c-53fc-49c0-b082-e7f5f05a9801/deadlock-when-using-sqlbulkcopy-to-concurrently-insert-rows-into-a-single-nonempty-table?forum=sqldatabaseengine)
Useful info: https://github.com/borisdj/EFCore.BulkExtensions/issues/46
