### ISSUE TITLE
How to get the number of rows affected after called BulkInsert()?

### ISSUE THREAD

**Issue by ZhangGaoxing** [borisdj/EFCore.BulkExtensions#185]
In EF, `SaveChanges()` returns a int value, why `BulkInsert()` has no return value?

**Comment by borisdj** [comment]
Insert should insert all so you already know the size of list.
And secondly number can be obtained from _BulkConfig.StatsInfo_ if you set _CalculateStats_ to True.
More info is in the README.
For InsertOrUpdate there are 2 numbers so they can not be returned with one int value.
That is why this Object has _StatsNumber-Inserted/Updated_.
