### ISSUE TITLE
comprehensive progress reporting

### ISSUE THREAD

**Issue by vslee** [borisdj/EFCore.BulkExtensions#186]
Bulk insertion is a two step process. First, inserting into a temp staging table. And then merging that table with the target table. Currently, the progress parameter of BulkInsertAsync() only reports the progress of the first part (inserting into the temp table). However, if the target table is very large and/or has a lot of constraints, the second step (merging) can take a significant amt of time. Sometimes even more time than the first step. Thus, if the progress parameter/callback could also report the progress of the second step, it would be helpful.

**Comment by borisdj** [comment]
Insert uses SqlBulkCopy from where Progress is obtained.
Merge operation is pure SQL which has no progress feature.
[MSDN: get-merge-statement-progress-when-running](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/bb1a7b67-f5fa-4c0a-9aa8-e9ffc4edacb0)
