### ISSUE TITLE
Insert locks database completely

### ISSUE THREAD

**Issue by uhfath** [borisdj/EFCore.BulkExtensions#192]
No idea where to look.
Here is my code:

```c#
using (var transaction = dbContext.Database.BeginTransaction())
{
    try
    {
        dbContext.BulkInsert(records.ToList(), new BulkConfig
        {
            BulkCopyTimeout = 0,
            WithHoldlock = false,
            SqlBulkCopyOptions = SqlBulkCopyOptions.CheckConstraints | SqlBulkCopyOptions.FireTriggers,
        });

        transaction.Commit();
    }
    catch (Exception ex)
    {
        transaction.Rollback();
        throw;
    }
}
```
I need to insert a lot of separate tables (with foreign keys and without) and do this inside one single transaction, because if one insert fails, the entire transaction has to be aborted.
Number of records vary from thousands to hundreds of thousands and makes no difference at all.
When this code starts, the entire database gets locked. Even tables which are not touched on inserting. Tried all combinations of isolation levels. No changes.
That's on MS SQL 2016 with all settings set to defaults. EF Core 2.1
What am i missing?

**Comment by borisdj** [comment]
Not sure.
SqlBulkCopyOptions also has property TableLock, but that is false by default.
Try finding more info [issue/46](https://github.com/borisdj/EFCore.BulkExtensions/issues/46).
