### ISSUE TITLE
Multi Key problem

### ISSUE THREAD

**Issue by chpo69** [borisdj/EFCore.BulkExtensions#194]
I have a problem with bulkinsert and multi key table.

I have a table : 

` [Table("Table", Schema = "Org")]
    public partial class Table
    {
        [Key]
        public int Id1 { get; set; }
        [Key]
        public int Id2 { get; set; }
        [Key]
        public int Id3 { get; set; }

        [ForeignKey("Id3")]
        [InverseProperty("Table")]
        public virtual Table3 Id3Navigation { get; set; }
        [ForeignKey("Id1")]
        [InverseProperty("Table")]
        public virtual Table1 Id1Navigation { get; set; }
        [ForeignKey("Id2")]
        [InverseProperty("Table")]
        public virtual Table2 Id2Navigation { get; set; }
    }`

When i  insert with bulkinsert i get the error message below:

> BlukInsert Error : Value cannot be null.
> Parameter name: key

What needs to be done to solve this problem?

**Comment by QuanTran91** [comment]
An Entity cannot have multiple keys, in order to specify composite key you have to use fluent api:
https://www.learnentityframeworkcore.com/configuration/data-annotation-attributes/key-attribute

**Comment by borisdj** [comment]
Take a look at Test [_InsertAndUpdateWithCompositeKey_](https://github.com/borisdj/EFCore.BulkExtensions/blob/9a729e5a5057fa3081ff3e0e70f2d2c970aa364c/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L41), where entity _UserRole_ with composite Key is used.
