### ISSUE TITLE
Db Schema Not recognised from DB User schema . If I hardcode  Schema in DBContext  everything works fine.

### ISSUE THREAD

**Issue by nirmaldeol** [borisdj/EFCore.BulkExtensions#196]
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ProcessAsync ---> System.Data.SqlClient.SqlException: Invalid object name

**Comment by borisdj** [comment]
Could you write example of Entity class and how is this schema configured.

**Comment by nirmaldeol** [comment]
Schema is not configure on entity or dbcontext level but on DB user level . That why we had this issue.

**Comment by nirmaldeol** [comment]
It will be great in this extension supports passing custom schema to methods or some initialization logic .
