### ISSUE TITLE
BulkInsertOrUpdateOrDelete does not work as expected when given an empty set

### ISSUE THREAD

**Issue by srowan** [borisdj/EFCore.BulkExtensions#197]
Example:  

* Target table has 5 records
* Call BulkInsertOrUpdateOrDelete() with zero records
* Expected result: all 5 records are removed
* Actual result: existing records remain

**Comment by borisdj** [comment]
When list is empty then no action is done:
https://github.com/borisdj/EFCore.BulkExtensions/blob/ad8a3449ffb8d241ae52cf57c2fd298859cd1aaf/EFCore.BulkExtensions/DbContextBulkTransaction.cs#L10-L15
In your case you can check list Length and if it is 0 then just call _BatchDelete()_
