### ISSUE TITLE
DateTime.Kind needs to be unspecified

### ISSUE THREAD

**Issue by calebickler** [borisdj/EFCore.BulkExtensions#198]
Similar to #123 

If a datetime has a kind set other than unspecified when using to filter the base query I get an error: `"Conversion failed when converting date and/or time from character string."`

````
        public async Task BulkInvalidate(DateTime? invalidateBefore, string updatedBy, string notes)
        {
            var query = Context.Entity.Where(c => c.PortalId == PortalId);

            if (invalidateBefore.HasValue)
            {
                query = query.Where(c => c.AwardDate < invalidateBefore.Value);
            }

            await query.BatchUpdateAsync(c => new Entity
            {
                Valid = 0,
                DateUpdated = DateTime.UtcNow,
                Notes = notes,
                UpdateBy = updatedBy
            });
        }
````

if I pass `2019-07-01T21:41:50Z` to my controller, its deserialized with the datetime kind set to local, and the error is thrown. If I pass `2019-07-01T21:41:50` the kind is unspecified and it works fine. If I am using regular EFCore functions it doesn't matter

**Comment by calebickler** [comment]
Temp fix is this: `var invalidDate = DateTime.SpecifyKind(invalidateBefore.Value, DateTimeKind.Unspecified);`

**Comment by borisdj** [comment]
Could you make test for reproducing the issue by altering current example or adding new one in Test project.
