### ISSUE TITLE
BukInsert slower than AddRange

### ISSUE THREAD

**Issue by aline-almeida** [borisdj/EFCore.BulkExtensions#199]
Hi,
I'm evaluating whether to use your extension in a project I'm developing, but I'm facing a slow performance. Here's my scenario: I'm working with ef core 2.2.4 and a sqlserver db.
When trying to add a list of entities (all to the same table) with BulkInsert, I get worse times than with AddRange... In fact, AddRange is taking about 55% of BulkInsert timing!
I was wondering if I'm missing any configuration, so here's what I'm doing:
In my context, I have this method (so I can override it in tests - using Sqlite, so can't use Bulk)
```
        public virtual void DSBulkInsert<T>(IList<T> entities) where T : class
        {
            this.BulkInsert<T>(entities);
        }
```

When saving:
```
                using (var transaction = context.Database.BeginTransaction())
                {
                    try
                    {
                        context.DSBulkInsert(lst);
                        transaction.Commit();
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback();
                    }
                }
```
When using AddRange, I do this:
```
                await context.Exits.AddRangeAsync(lst);
                try
                {
                    await context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex);
                }
```

Am I missing something? My model is quite simple, it has half a dozen properties and all related data is set by FK properties.

**Comment by brentlyjdavid** [comment]
@aline-almeida, The library owner might want to weigh in, but I'll provide our experience.  When we've used this, we haven't wrapped our calls in transactions like you did in your first example.  Try just doing context.DSBulkInsert(1st) without the transaction explicitly being created.  We've been doing it that way and see the same performance numbers as the readme does for this project.

**Comment by borisdj** [comment]
It should also work correctly within Transaction.
But you can try without it to see if the problem remains.
From the code you have written I don't see anything wrong.
You can download the source and make new Test in .Test project.

**Comment by borisdj** [comment]
SQLite is now also supported for Bulk Ops, from version 2.6.0
