### ISSUE TITLE
Temp Table Delete issue

### ISSUE THREAD

**Issue by brentlyjdavid** [borisdj/EFCore.BulkExtensions#202]
I, like others, have had similar issues where the temp tables aren't being deleted.  #60, #23 are along the same lines but in our case, we actually have deadlocks happening.

Situation:
We are first Bulk-Inserting 7-12 million rows into sql in the raw file formats using sql's bulk insert.  We then use Hangfire (another github project) to process batches of 50k with 5 concurrent jobs.  One of our c# calls is` _context.BulkInsert(items, new BulkConfig() { PreserveInsertOrder = true, BulkCopyTimeout = 0, SetOutputIdentity = true});`  This is the line that occasionally results in this error: 
![image](https://user-images.githubusercontent.com/7902547/60935052-261cfb00-a28e-11e9-8473-d0f1f9307a4e.png)
Hangfire has a built in re-try mechanism for failed jobs, so eventually this works and that bulk insert code does finish and run.  However, the jobs that create these (or any job that fails with the bulk insert call being made) leaves me with temp tables like this:
![image](https://user-images.githubusercontent.com/7902547/60935260-e73b7500-a28e-11e9-846e-ae4823f44a09.png)

Proposed Solution:
Now with that being said, i'm not here to ask for a solution to the deadlock or any other exception caused by something unrelated to your library.  I also don't expect the bulk insert call to understand that it failed and clean up any previous attempts.  What I would like to see as a suggestion is another method on the context that I could call myself. Such as `_context.CleanAndRemoveTempTables();` or something, that would run a process that does a clean up, but simply assumes all temp tables created by the same pattern as this library does today, can be removed, and does so.  Regardless of if there's data still in those temp tables or not.

Reason:
It would be impossible for the library to know when all temp tables _should_ be done being used i suspect.  In my case, i'm even doing concurrent jobs across multiple instances of websites accessing the same DB.  Hangfire already allows me to run something 'after all other items are complete', but I don't have enough knowledge to understand how to 'clean up all temp tables that might have been created by bulk extensions library that are still here'.

Does that make sense?  Let me know what you think or if I can help provide more information.

Thanks!

**Comment by softwarebybrent** [comment]
A little more insight, the reason we chose to batch out in groups of 50k, is because we do a significant amount of processing from a few other tables before inserting them into the final table (which is the one we are calling _context.BulkInsert(...); for.  We had memory issues trying to do all 7-12 million in a list, so that was where we ended up.  I did see you have a batching process built into the library, but it just wasn't a single table that we needed to update with, so it didn't fit the needs of our items at the time.

**Comment by borisdj** [comment]
Hae you tried setting `UseTempDB_`to **true** in _BulkConfig_?
That way Temp tables are created in temporary Db section and SqlServer would clean it up even after exception.

**Comment by brentlyjdavid** [comment]
I'll try that tonight and let you know.

**Comment by brentlyjdavid** [comment]
This seems to solve the problem, after adding the transaction around it, with the UseTempDb.   I re-ran it and got a few deadlocks and the temp tables where gone from both the DB i'm inserting and the tempdb one from the system tables.

Thanks.

**Comment by borisdj** [comment]
Glad it solved the issue you had.
