### ISSUE TITLE
GitHub sponsors

### ISSUE THREAD

**Issue by vslee** [borisdj/EFCore.BulkExtensions#205]
Please sign up for [this ](https://github.com/sponsors)(or get on the waitlist). Paypal (and bitcoin) charge transaction fees. Specifically, even if I choose on PayPal to "send to a friend" vs "paying for an item or a service", it still charges a $1 transaction fee because your account is not in the US.

**Comment by borisdj** [comment]
Still on the wait list, once approved will remove Paypal.
BTC lightning set.

**Comment by vslee** [comment]
Your BTC lightning on phoenix wallet QR appears to be expired.
