### ISSUE TITLE
Use BulkUpdate like EFCore Attach method

### ISSUE THREAD

**Issue by OculiViridi** [borisdj/EFCore.BulkExtensions#206]
I'm wondering how the `BulkUpdate` method works, since I'd like to use it like the `Attach` method of EF Core.
The `Attach` method allows you to mark as `Changed` each field of the entity individually, and so then it generates accordingly a more compact UPDATE SQL command.

I need to update a `List<Entity>` where just a subset of fields for each entity have to be updated. That's because I get **only the IDs of the entities that needs to be updated** and then those are mapped to new `Entity` objects with values set for just the ID and the 2-3 fields which value has to be changed, others are `null`. Then I mark as Changed just those 2-3 fields and the `Attach` method makes its work.

I suppose that if I cannot use an approach like the `Attach` method, I will end with all the fields updated and so also others that should not be, will be set to `null`.

Is it possible by using `BulkUpdate`?

**Comment by borisdj** [comment]
You can specify which columns to update with **PropertiesToInclude** from _BulkConfig_.
There is more info in the [ReadMe](https://github.com/borisdj/EFCore.BulkExtensions#bulkconfig-arguments) (BulkConfig arguments)
You can find examples in _EFCoreBulkTest/RunUpdate._

**Comment by OculiViridi** [comment]
@borisdj Thanks!
I should have read the README more calmly... I gave it just a quick read.

Finally, this is my implementation:

```csharp
await ResilientTransaction.New(Context).ExecuteAsync(async () =>
{
    metas = await Context.Anomalies
        .Where(a => request.Ids.Contains(a.Id) && a.Closed == null)
        .Select(a => new AnomalyMeta
        {
            Id = a.Id,
            Machine = a.Machine,
            SelectedAction = a.SelectedAction,
            Closed = a.Closed,
        })
        .AsNoTracking()
        .ToArrayAsync(cancellationToken);

    DateTime now = DateTime.Now;

    var anomalies = metas.Select(m => new dom.Anomaly { Id = m.Id, SelectedAction = request.Action, Closed = now }).ToList();

    await Context.BulkUpdateAsync(anomalies, new BulkConfig
    {
        PropertiesToInclude = new List<string>
        {
            nameof(dom.Anomaly.SelectedAction),
            nameof(dom.Anomaly.Closed),
        }
    });
});
```

But `BulkUpdate` seems to ignore the `ConcurrencyToken` set on the 2 fields in the Entity Configuration of EF Configure method.

```csharp
public void Configure(EntityTypeBuilder<Entities.Anomaly> builder)
{
    builder.Property(e => e.Id)
        .ValueGeneratedOnAdd();

    builder.HasOne(e => e.Machine);

    builder.Property(e => e.ItemCode)
        .HasMaxLength(50);

    builder.Property(e => e.ItemType)
        .HasMaxLength(50);

    builder.Property(e => e.Domain)
        .HasMaxLength(50)
        .IsRequired();

    builder.Property(e => e.Code)
        .HasMaxLength(50)
        .IsRequired();

    builder.Property(e => e.Data)
        .HasColumnType("text");

    builder.Property(e => e.SelectedAction)
        .IsConcurrencyToken();

    builder.Property(e => e.Closed)
        .IsConcurrencyToken();
}
```

While debugging, if I make a manual update in SQL to on one of the previously selected entities, **just before** calling `await Context.BulkUpdateAsync()`, the execution continues without any Exception, instead of failing with a `DbConcurrencyException`, since the values of one of the involved entites are changed.
