### ISSUE TITLE
IncreaseTimeout to more then 30 seconds

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#21]
I am running into timeout problems when inserting thousands of records, how do I increase timeout, will that help?

**Comment by borisdj** [comment]
Try the 2.0.1 version.
If it still happens there is now **BulkCopyTimeout** optional parameter in _BulkConfig_ that you can set.
But in test Insertion of 100 000 rows happens within the default time frame so you should not be getting this with just few thousands.
