### ISSUE TITLE
BulkUpdate, BulkDelete, BulkInsert and BulkRead doesn't resets change tracking in the object context

### ISSUE THREAD

**Issue by VCuzmin** [borisdj/EFCore.BulkExtensions#211]
BulkUpdate, BulkDelete, BulkInsert and BulkRead doesn't resets change tracking in the object context. 
As a workarround, I created this method which resets change tracking in the object context: 

 private void DiscardContextChanges() =>
             _dbContext.ChangeTracker.Entries<OfferTaskWork>().Where(uan => uan.State != EntityState.Unchanged).AsParallel().ForAll(uan => uan.State = EntityState.Unchanged);

This behavior exists in EF: https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.core.objects.objectcontext.savechangesasync?view=entity-framework-6.2.0 (SaveChangesAsync resets change tracking in the object context )

**Comment by borisdj** [comment]
You can set _BukConfig_ with _**UseTempDB = true**_ if you can't give CREATE permission.

**Comment by VCuzmin** [comment]
Ok. Thx.

**Comment by kiersche** [comment]
@borisdj if you do, please make it optional or at least don't make existing code change its behavior. In some cases, I use the regular DbContext change tracker and your BulkExtensions side by side. Within a transaction, I BulkInsert new entities that aren't tracked by the context *and* at the same time I update tracked entities via SaveChangesAsync. I wouldn't want to lose that tracking info.

**Comment by borisdj** [comment]
I've decided not to add this directly because Bulk methods are not tracking changes.
When needed it can simply be called after Bulk operation since it's just one line of code.
But I do plan to use _ChangeTracker_ with _BulkSaveShanges_, new method still being developed.
