### ISSUE TITLE
BulkInsert throws InvalidCastException when entity has shadow property

### ISSUE THREAD

**Issue by jobinpa** [borisdj/EFCore.BulkExtensions#213]
Given the following setup
```
-- Database schema
CREATE TABLE [dbo].[RootEntity]
(
    [Id] [UNIQUEIDENTIFIER] NOT NULL PRIMARY KEY
)

CREATE TABLE [dbo].[LeafEntity]
(
    [Id] [UNIQUEIDENTIFIER] NOT NULL PRIMARY KEY,
    [RootEntityId] [UNIQUEIDENTIFIER] NOT NULL,
    CONSTRAINT FK FOREIGN KEY ([RootEntityId]) REFERENCES [RootEntity]([Id])
)
```
```
// Entities
public class RootEntity
{
    public Guid Id { get; set; }
    public List<LeafEntity> Leaves { get; set; }
}

public class LeafEntity
{
    public Guid Id { get; set; }
}
```
```
// DbContext
public DbSet<RootEntity> RootEntities { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    EntityTypeBuilder<RootEntity> rootBuilder= modelBuilder.Entity<RootEntity>();
    rootBuilder.ToTable("RootEntity");
    rootBuilder.HasKey(e => e.Id);
    rootBuilder.Property(e => e.Id).IsRequired();
    rootBuilder.HasMany(e => e.Leaves).WithOne().HasForeignKey("RootEntityId");

    EntityTypeBuilder<LeafEntity> leafBuilder= modelBuilder.Entity<LeafEntity>();
    leafBuilder.ToTable("LeafEntity");
    leafBuilder.HasKey(e => e.Id);
    leafBuilder.Property(b => b.Id).IsRequired();
}
```
Aggregate root ``RootEntity`` has zero or many ``LeafEntity`` instances. ``LeafEntity`` references ``RootEntity`` through the ``RootEntityId`` column which is not exposed by the model, but configured through a shadow property.

Now consider the following snippet:
```
var rootEntity = new RootEntity { Id = Guid.NewGuid(), Leaves = new List<LeafEntity>() };
var leafEntity = new LeafEntity { Id = Guid.NewGuid() };
rootEntity.Leaves.Add(leafEntity);

using (var ctx = new RootEntityContext(options))
{
    ctx.RootEntities.Add(rootEntity);
    ctx.BulkInsert(new[] { rootEntity });
    // Next statement throws "InvalidCastException: 
    // Invalid cast from 'System.String' to 'System.Guid'".
    ctx.BulkInsert(rootEntity.Leaves);
}
```
Executing the code above throws an ``System.InvalidCastException`` exception.

I traced the code against commit [2f98b75c](https://github.com/borisdj/EFCore.BulkExtensions/commit/2f98b75c247e3c8d8822696064892a4224393343), but I have the same issue with NuGet EFCore.BulkExtensions v2.5.2. I think the problem is caused by the following line https://github.com/borisdj/EFCore.BulkExtensions/blob/2f98b75c247e3c8d8822696064892a4224393343/EFCore.BulkExtensions/SqlBulkOperation.cs#L329
This piece of logic assumes the first shadow property is always a discriminator column which, in this case is not true.

I am attaching [SampleProject.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/3463202/SampleProject.zip) to illustrate the issue.

**Comment by borisdj** [comment]
I have lookup into the issue.
DiscriminatorColumn could be isolated the following way:
`var discriminatorColumn = tableInfo.ShadowProperties.Count == 0 ? null : tableInfo.ShadowProperties.Where(a => a == "Discriminator").FirstOrDefault();`
However there is another problem, to get the value of FK Shadow property.
Until this gets solved, the easiest solution for the issue would be to simply in `LeafEntity` add FK property:
```C#
public Guid RootEntityId { get; set; }
public virtual RootEntity RootEntity { get; set; }
```

**Comment by Thepriestdude** [comment]
I also have this problem, our logic is almost the same. I have updated @jobinpas example to match my code.
```
// Entities
public class RootEntity
{
    public Guid Id { get; set; }
    public List<LeafEntity> Leaves { get; set; }
}

public class LeafEntity
{
    public Guid Id { get; set; }
    public RootEntity Root { get; set; }
}
```
```
// DbContext
public DbSet<RootEntity> RootEntities { get; set; }

protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    EntityTypeBuilder<RootEntity> rootBuilder= modelBuilder.Entity<RootEntity>();
    rootBuilder.ToTable("RootEntity");
    rootBuilder.HasKey(e => e.Id);
    rootBuilder.Property(e => e.Id).IsRequired();
    rootBuilder.HasMany(e => e.Leaves).WithOne().HasForeignKey("Root");

    EntityTypeBuilder<LeafEntity> leafBuilder= modelBuilder.Entity<LeafEntity>();
    leafBuilder.ToTable("LeafEntity");
    leafBuilder.HasKey(e => e.Id);
    leafBuilder.Property(b => b.Id).IsRequired();
}
```

Is there any information about when this might be fixed?

**Comment by 304NotModified** [comment]
Same problem here. So +1 to fix this

**Comment by samneefs** [comment]
The fix from @borisdj  works for me.

We have a Shadow property that isn't a discriminator. This causes the exception, but with this it is fixed.
To bad I now can't use the package (until I manage to rid the shadow property from our model).

Could you please include this fix in the EfCore2.2 branch?

**Comment by pajacz** [comment]
I have the same issue.. 
btw why are you setting value of this column to entity type name?

`columnsDict.Add(discriminatorColumn, type.Name);`

Should be better to have default null? :)

Or is expected to get an Invalid cast exception?

Thanks for any feedback!

**Comment by borisdj** [comment]
FK Shadow Property is now supported, version 3.2.1+
