### ISSUE TITLE
Columns not equal to property name not working (SQLite)

### ISSUE THREAD

**Issue by AMCON-Gerst** [borisdj/EFCore.BulkExtensions#215]
I have named a database column about an annotation differently than the property. At BulkInsert I now get a System.ArgumentOutOfRangeException. The error is thrown in the method "LoadSqliteValues" in the class "SqlBulkOperation" (line 717).

I tested it only with SQLite and only with the annotation. I don't think changing the column name via the Flutent API would work better.

Is the different naming of columns to properties generally not supported or is this an error from the SQLite implementation?

**Comment by AMCON-Gerst** [comment]
Fixed with commit 49022d86f2fc1b727753e927dbe63bfe03995a92

**Comment by borisdj** [comment]
It was a bug.
Also new NuGet published v2.6.0 which is full release.

**Comment by borisdj** [comment]
It was a bug.
Also new NuGet published v2.6.0 which is full release.
