### ISSUE TITLE
BulkInsert Not returning Id when SetOutputIdentity = true

### ISSUE THREAD

**Issue by dougwalden** [borisdj/EFCore.BulkExtensions#222]
I have started using the **BulkInsert** on several tables while doing a migration from database to another. It has worked very well up until this table (a Bridge table) where my PK is made up of two columns both FK to two separate tables. The Id column is an Identity column (but again...Not the PK).

Table Script:
CREATE TABLE [wvc].[Pbli](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PbldId] [int] NOT NULL, --FK to Detail table
	[ImageId] [int] NOT NULL, --FK to Image Table
	[IsImageLocked] [bit] NOT NULL,
	[HasHistory] [bit] NOT NULL,
 CONSTRAINT [PK_Pbli] PRIMARY KEY CLUSTERED 
(
	[PbldId] ASC,
	[ImageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_Pbli_Id] UNIQUE NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

Insert Code:
![image](https://user-images.githubusercontent.com/53903332/64787326-7b031900-d53e-11e9-8fcf-252c6edf6ac5.png)

As you can see in the code, there are two **BulkInserts** that work as expected, but the third one does the Insert, but does NOT bring back the ID's.
For logging purposes I have a Migration table that logs the OldId(from the source table) and the NewId (from the target table...The One I am trying to populate from the **BulkInsert** in the loop below the **BulkInsert** line.)
How do I get the Id?  Thanks in advance for any help.

**Comment by borisdj** [comment]
Try the latest NuGet, should be fixed now.

**Comment by dougwalden** [comment]
Thanks I will Try it. 
As a side note I got around my issue of needing the Id by immediately after the BulkInsert doing a BulkRead, feeding it the list that was just inserted. By doing this I got back the same list with the Id populated and was able to do the for loop to get the Ids in the order I needed them.
