### ISSUE TITLE
Testing in UseInMemoryDb EFCore.

### ISSUE THREAD

**Issue by mingyao23** [borisdj/EFCore.BulkExtensions#226]
Hello and Good day! is there any work around when using BatchDelete() in UseInMemory in ef core dbcontext?
![InvalidCastException](https://user-images.githubusercontent.com/6753371/65007307-47f2c800-d938-11e9-900d-8900b06b15f7.png)

**Comment by borisdj** [comment]
Bulk Tests can not have UseInMemoryDb(usually used for Tests), because InMemoryProvider does not support Relational-specific methods.
You could try using SQLite with In-Memory mode instead, since SQLite is also supported.
Duplicate of https://github.com/borisdj/EFCore.BulkExtensions/issues/24
