### ISSUE TITLE
Support for SQLite database encryption 

### ISSUE THREAD

**Issue by Marmotor** [borisdj/EFCore.BulkExtensions#227]
Hi! I'm currently working on a project for which the client requires the database file to be encrypted, and unlocked when used. This is done using the `System.Data.SQLite.SQLiteConnection` class. Unfortunately, the `Microsoft.Data.Sqlite.SqliteConnection` class that is currently used as the underlying connection doesn't support encryption. Since both these classes inherit from `System.Data.Common.DbConnection`, is it possible that in a future release to use `DbConnection` as the underlying connection, to support both sqlite conection classes?
Currently I'm getting this exception :
`Exception thrown: 'System.InvalidCastException' in EFCore.BulkExtensions.dll
Unable to cast object of type 'System.Data.SQLite.SQLiteConnection' to type 'Microsoft.Data.Sqlite.SqliteConnection'.`

Thank you!

**Comment by borisdj** [comment]
Will look into it, but I think it can be done.

**Comment by borisdj** [comment]
I have tried it and can replace Conn./Tran. from Sqlite to SQLite in the library but then when code in Test (RunInsert operation) changed from:
`using (var connection = (SqliteConnection)context.Database.GetDbConnection())`
to:
`using (var connection = (System.Data.SQLite.SQLiteConnection)context.Database.GetDbConnection())`
I got the following exception:
> Message: System.InvalidCastException : Unable to cast object of type 'Microsoft.Data.Sqlite.SqliteConnection' to type 'System.Data.SQLite.SQLiteConnection'.

**Comment by Marmotor** [comment]
Thank you for your effort!
What if instead of `SQLiteConnection` you use directly the result of `GetDbConnection()`, which is `System.Data.Common.DbConnection`? Both SqliteConnection classes inherit from it and it would still be compatible with your previous approache, using the SqliteConnection from Microsoft.

**Comment by borisdj** [comment]
That won't work either.
DbConnection needs to be cast to specific provider (Lite)Connection, otherwise you get:
> Message: System.InvalidOperationException : SqliteConnection does not support nested transactions.

**Comment by Marmotor** [comment]
Thank you for taking your time. I'm sorry it's not working... :(
