### ISSUE TITLE
SqLite dependencies are downloaded although I'm using Sql Server

### ISSUE THREAD

**Issue by CSharpBender** [borisdj/EFCore.BulkExtensions#228]
I've tried this package and it downloaded a ton of packages for SQLite but not the one that I needed most on the DbContextOptionBuilder: SqlServer.
I removed SQLite and received an error although I'm not using it.

I can't have dependencies in my project that are not used.

In my opinion this issue could be solved with some abstractions and dependency injection. Based on the configuration only the required provider should be injected the rest should be null/dummy and throw an exception when called.

Please share your thoughts on this.

**Comment by borisdj** [comment]
I don't see what is the issue having library that has several Nugets, but not uses all always.
That being said, I am also not sure how to use NuGet in Project and not have it installed ?
Can NuGet be 'dynamical' referenced? and if so is there there some example with explanation.

**Comment by CSharpBender** [comment]
You can create a base package with all the logic and depending packages that are targeting specific DB types.
You can look at EF and see how it supports multiple db types without downloading all the adapters.

**Comment by guillaumesp** [comment]
Hello, Since I have updated the package from 3.0.3 to 3.1.0 I have an error on execution time : Could not load file or assembly 'Microsoft.Data.Sqlite, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
I'm not sure but I think related packages are not referenced dynamically

**Comment by v-zubritsky** [comment]
+1 here for not having Sqlite as a dependency by default. It adds unnecessary burden to my project dependencies, while is not needed. 

Not critical, but would be very nice.

**Comment by 3ldar** [comment]
+1 here. But it is actually critical for us, as it breaks the build because of the ambiguity between multiple EF providers 

![image](https://user-images.githubusercontent.com/20445388/160599803-65d653fb-694a-4295-9641-8f7dcbe3d488.png)

As Nuget is not that versatile enough to exclude some dependencies dynamically this is causing so much pain as we are trying to upgrade from Net5 to Net6.  In Net5 Hilo methods had provider prefixes like `ForSqlServer` and in Net6 all has the same method name.

**Comment by v-zubritsky** [comment]
@3ldar Not related to the issue discussed, but it looks like you could merely qualify the extension method name explicitly, aren't you?

```
ExtensionType.ExtensionMethod(target, arguments);
``` 
instead of
```
target.ExtensionMethod(arguments);
```

**Comment by 3ldar** [comment]
@v-zubritsky nope it is exactly the same reason. It includes all the providers that `EFCore.BulkExtensions` supports. So when any extension method like `UseHilo` is implemented by multiple providers you will eventually get these kinds of errors. Your suggestion should work but for the existing code base, it is really a pain. And if you are trying to support multiple providers you have to have conditional compilation which is also unpleasant (The more providers the more `#if` preprocessors). We actually applied another ugly workaround which is to add the  `EFCore.BulkExtensions.dll` to the source control and directly reference it from the project.

**Comment by borisdj** [comment]
Task moved to issue https://github.com/borisdj/EFCore.BulkExtensions/issues/669

**Comment by borisdj** [comment]
New Structure (as of verion 6.6.0):
| Num | Project | References | NuGet |
| - | - | - | - |
| [0] | EFCore.BulkExtensions                     |      | - |
| [1] | EFCore.BulkExtensions.SQLServer    | [0] | EFCore.BulkExtensions.SQLServer |
| [2] | EFCore.BulkExtensions.PostgreSQL  | [0] | EFCore.BulkExtensions.PostgreSQL|
| [3] | EFCore.BulkExtensions.MySQL         | [0] | EFCore.BulkExtensions.MySQL |
| [4] | EFCore.BulkExtensions.SQLite          | [0] | EFCore.BulkExtensions.SQLite |
| [5] | EFCore.BulkExtensions.Common      | [1,2,3,4] | EFCore.BulkExtensions

[0] | _EFCore.BulkExtensions_ is shared core project that has no Nuget.
Instead project [5] _EFCore.BulkExtensions.Common_ references all other projects thereby includes all providers and it has NuGet with base name: **EFCore.BulkExtensions** to keep full compatibility with previous versions.
