### ISSUE TITLE
Temp tables staying in database

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#23]
Hi Borris. I noticed periodically in my code that the temp tables the Bulk insert creates end up not being dropped. the thing that bothers me, is that I now have a piece of code where it happens every time, what is the solution?

**Comment by nafberger** [comment]
![screenshot_14](https://user-images.githubusercontent.com/26122027/33103621-48db4650-cef1-11e7-960b-bf09081ba0f5.png)

**Comment by borisdj** [comment]
I need example of it.
Can you add full snipped code where it is happening or maybe create some small test project with that code, share it somewhere and send a link.
Btw when creating an issue it should include steps to reproduce behavior:
[creating-an-issue](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
[how-we-write--issues](https://wiredcraft.com/blog/how-we-write-our-github-issues/)

**Comment by nafberger** [comment]
Okay I will
