### ISSUE TITLE
Issue when upgrading to 2.6.0 throws error: Value cannot be null. Parameter name: key when using composite key

### ISSUE THREAD

**Issue by tonkymm** [borisdj/EFCore.BulkExtensions#230]
I've upgraded the EFCore.BulkExtensions to version 2.6.0 and I am getting "Value cannot be null. Parameter name: key" error when I try to do a bulk insert on an entity with a composite primary key.
I dug into the code and can see that for tableinfo IdentityColumnName is null when using a composite key. The code below is looking for properties isPrimaryKey and ValueGenerated.OnAdd. The keys in my entity are not auto incremented keys. Is there a way I can get around this issue?

IdentityColumnName = allProperties.SingleOrDefault(a => a.IsPrimaryKey() && a.ClrType.Name.StartsWith("Int") && a.ValueGenerated == ValueGenerated.OnAdd)?.Name; // ValueGenerated equals OnAdd even for nonIdentity column like Guid so we only type int as second condition

**Comment by tonkymm** [comment]
Actually it looks like if I check for IdentityColumnName != null in UpdateEntitiesIdentity function 
if (BulkConfig.PreserveInsertOrder && IdentityColumnName != null)
{

**Comment by tonkymm** [comment]
Didnt mean to close.

**Comment by borisdj** [comment]
Try the latest NuGet, should be fixed now.

**Comment by tonkymm** [comment]
Hi,
Thank you for the patch. The reported issue is gone but unfortunately, when I upgrade to version 2.6.3, I get another error. 

"The MERGE statement conflicted with the FOREIGN KEY constraint \"FK_JRN_Journals_REC_Assignments\". The conflict occurred in database \"H7_hf2\", table \"dbo.REC_Assignments\", column 'PKId'."
{"Value cannot be null.\r\nParameter name: key"}
2.4.7

I've been trying to debug and see why this issue is happening but have not found why the exception is being thrown. I'm able to insert records using EF Core AddRange but when I try to use EF Core BulkExtensions insert, I get the above error. My team is looking at the EF Core mappings and automapper on our end but if you can provide any suggestions, it would be greatly appreciated. 

As a side note, I tried to upgrade from EFCore BulkExtension 2.4.5 to 2.4.7 but I get error:
{"Value cannot be null.\r\nParameter name: key"}

**Comment by borisdj** [comment]
If you can make a test where it would be reproducible.

**Comment by tonkymm** [comment]
Hi,
I'll try to get you a test project by the end of my day (US Pacific time) tomorrow. 
Thanks

**Comment by jwisener** [comment]
:-( same issue.
