### ISSUE TITLE
Update the library to be .NET Core 3 compatible

### ISSUE THREAD

**Issue by LPeter1997** [borisdj/EFCore.BulkExtensions#231]
According to #193, the library doesn't function under .NET Core 3 because of breaking changes and the fix wasn't planned until .NET Core 3 stabilized. Since .NET Core 3 is released. I'd love to see the fix happen,

I love the library, thank you for all your work!

**Comment by borisdj** [comment]
Version 3.0.0-rc published.
All BulkOps work but Batch(Update/Delete) do not because in v3.0 there are no classes '_QueryModelGenerator_' and '_RelationalQueryModelVisitor_'.
Those where used for implementing `.ToSql()` method, and I haven't yet found an alternative way of re-implementing this.
https://github.com/borisdj/EFCore.BulkExtensions/blob/d61027330695083f657e44d125959232f760c1d0/EFCore.BulkExtensions/IQueryableExtensions.cs#L29-L50

**Comment by domagojmedo** [comment]
@borisdj maybe ask on official repo what APIs and types replaced the 'QueryModelGenerator' and 'RelationalQueryModelVisitor'.

**Comment by borisdj** [comment]
I already have: https://github.com/aspnet/EntityFrameworkCore/issues/18029

**Comment by Wasseratem** [comment]
Well, breaking changes for me now too... Sitting here on 3.0 without bulking x.x

**Comment by domagojmedo** [comment]
@Wasseratem  Bulking works, batching is broken

**Comment by borisdj** [comment]
3.0.0 RTM published.
Got [here](https://gist.github.com/rionmonster/2c59f449e67edf8cd6164e9fe66c545a) the solution for `ToSql`.
However `ToParametrizedSql` is still an issue so as a workaround BatchOps now have argument _parametersDict_.
More info in ReadMe / [Usage](https://github.com/borisdj/EFCore.BulkExtensions/blob/master/README.md#usage) / Batch (under code segment IMPORTANT)

**Comment by borisdj** [comment]
3.0.0 RTM published.
Got [here](https://gist.github.com/rionmonster/2c59f449e67edf8cd6164e9fe66c545a) the solution for `ToSql`.
However `ToParametrizedSql` is still an issue so as a workaround BatchOps now have argument _parametersDict_.
More info in ReadMe / [Usage](https://github.com/borisdj/EFCore.BulkExtensions/blob/master/README.md#usage) / Batch (under code segment IMPORTANT)

**Comment by wxpxzdj** [comment]
`           ......
            var sqlGenerator = factory.Create() as SqlServerQuerySqlGenerator;
            var command = sqlGenerator.GetCommand(selectExpression);
            var sql = command.CommandText;
            List<SqlParameter> parameters = new List<SqlParameter>();

            if (command.Parameters?.Any() == true)
            {
                var relationalQueryContextFieldName = "_relationalQueryContext";
                var relationalQueryContextFieldInfo = enumeratorType.GetField(relationalQueryContextFieldName, bindingFlags);
                var relationalQueryContext = (RelationalQueryContext)relationalQueryContextFieldInfo.GetValue(enumerator);

                var parameterType = typeof(TypeMappedRelationalParameter);
                var nullablePropertyInfo = parameterType.GetProperty("IsNullable", bindingFlags);
                var namePropertyInfo = parameterType.GetProperty("Name");

                foreach (var p in command.Parameters)
                {
                    var name = (string)namePropertyInfo.GetValue(p);
                    var value = relationalQueryContext.ParameterValues[p.InvariantName];
                    parameters.Add(new SqlParameter(name, value));
                }
            }`

**Comment by RosiOli** [comment]
@borisdj have a look here mate: https://gist.github.com/rionmonster/2c59f449e67edf8cd6164e9fe66c545a#gistcomment-3059688

**Comment by borisdj** [comment]
I have seen it, and will try to integrate it soon.
Thx

**Comment by borisdj** [comment]
`ToParametrizedSql` fixed with 3.0.1 and _parametersDict_ removed.
