### ISSUE TITLE
BulkUpdateAsync to return the number of rows affected

### ISSUE THREAD

**Issue by HelloValue** [borisdj/EFCore.BulkExtensions#235]
**How do I get BulkUpdateAsync to return the number of rows affected?**

 public async Task BulkUpdateAsync(List<T> entitiesList)
        {
            await _context.BulkUpdateAsync(entitiesList);
        }

**Comment by borisdj** [comment]
Use `Count()` on your query.
It can be called before or after calling BatchUpdate, example with after:
```C#
var query = context.Items.Where(a => a.ItemId <= 500);
query.BatchUpdateAsync(new Item { Description = "Updated" });
int count = await query.CountAsync();
```
