### ISSUE TITLE
Release notes/GitHub Releases

### ISSUE THREAD

**Issue by chris5287** [borisdj/EFCore.BulkExtensions#236]
Great project, many thanks :)

Just wondering if you are publishing release notes anywhere or whether you could use GitHub releases to indicate when new versions are out, as we can set alerts on this :)

**Comment by borisdj** [comment]
Releases are only published on NuGet, where there is a list with Number and Description.
On GitHub there is only in the ReadMe number of last version. along with version numbers of releases with .Net targeting changes (Standard 1/2/2.2 and Core 1/2/3).
But I am now planing from 3.0 to be adding mayor Release 3.X in GitHub releases as well.

**Comment by chris5287** [comment]
Thanks for the info and great that you will start populating GitHub Releases :)

**Comment by borisdj** [comment]
You are welcome.
Also in VS NugetManagement you can see Update option if library has newer version.
