### ISSUE TITLE
BulkInsertAsync left FK value = 0 while inserting into DB.

### ISSUE THREAD

**Issue by jinnguyen1200** [borisdj/EFCore.BulkExtensions#237]
I'm using 3.0.0-rc version for my EFCore3.0. 
I tried not to set FK value in a list, then I used BulkInsertAsync() method to insert it into DB, it left FK columns = 0 and no error message was returned. This breaks SQL FK rules.
But when I tried to update it by BulkUpdateAsync(), it returned "The MERGE statement conflicted with the FOREIGN KEY constraint ... etc" message.
It seems like BulkInsertAsync() method has some troubles.
Btw, sorry for my English, it's not my native language.

**Comment by borisdj** [comment]
_BulkConfig_ has property _SqlBulkCopyOptions_ which has _**CheckConstraints**_ as one of it's Flags.
By default it is False, and you can set it to True.

**Comment by jinnguyen1200** [comment]
> _BulkConfig_ has property _SqlBulkCopyOptions_ which has _**CheckConstraints**_ as one of it's Flags.
> By default it is False, and you can set it to True.

Thank you, I fixed it.
