### ISSUE TITLE
Does BatchUpdate Work With Top/Take?

### ISSUE THREAD

**Issue by Coder3333** [borisdj/EFCore.BulkExtensions#238]
The Batch update code looks like it does not work when the query has a Take commandin it.  Take generates a first line that looks something like this:

"SELECT TOP(@__p_0) [d].[ColumnName]"

which cause GetBatchSql to not be able to correctly determine the tableAlias, plus, the entire Top statement will get cut out of the final Update Sql.

```
                string escapeSymbol = (databaseType == DbServer.SqlServer) ? "]" : "."; // SqlServer : PostrgeSql
                tableAlias = sqlQuery.Substring(8, sqlQuery.IndexOf(escapeSymbol) - 8);

```

I think there needs to be code to look for Top and produce the correct Update statement.  If Skip and Take are used together, it will result in entirely different Sql, so that should also be addressed.

**Comment by sky-daniel-paula** [comment]
I have the same problem, but in BatchDelete. The 'TOP(100)' statment is not complete, this is the result: "DELETE [OP(100) [table_alias]
FROM..."

**Comment by sky-daniel-paula** [comment]
@borisdj I made this if you want to check it, this could inspire you for the enhancement:
` private static Task<(string TopStatement, string TableAlias, string Sql)> GetBatchSql<T>(IQueryable<T> query) where T : DomainEntity
        {
            var sqlQuery = query.ToSql();
            var selectStmLength = "SELECT".Length;
            var escapeSymbolEnd = "]";
            var escapeSymbolStart = "[";
            string tableAliasEnd = sqlQuery.Substring(selectStmLength, sqlQuery.IndexOf(escapeSymbolEnd) + 1 - selectStmLength).Trim(); // "TOP(10) [table_alias]" / "[table_alias]"
            int tableAliasStartIndex = tableAliasEnd.IndexOf(escapeSymbolStart);
            string tableAlias = tableAliasEnd.Substring(tableAliasStartIndex); // "[table_alias]"
            string topStatement = tableAliasEnd.Substring(0, tableAliasStartIndex); // "TOP(10) " / if TOP not present in query this will be a Substring(0,0) == ""

            int indexFROM = sqlQuery.IndexOf(Environment.NewLine);
            string sql = sqlQuery.Substring(indexFROM, sqlQuery.Length - indexFROM);
            sql = sql.Contains("{") ? sql.Replace("{", "{{") : sql; // Curly brackets have to be escaped
            sql = sql.Contains("}") ? sql.Replace("}", "}}") : sql;

            return Task.FromResult((topStatement, tableAlias, sql));
        }`

**Comment by borisdj** [comment]
@sky-daniel-paula
I have accepted your commit and new NuGet 3.0.3 is published.
Thx for contribution.
