### ISSUE TITLE
Does it support the InMemory provider?

### ISSUE THREAD

**Issue by vdabnishka** [borisdj/EFCore.BulkExtensions#24]
I want to move away from our current solution (a combination of temp tables, SqlBulkCopy and merge statements) to increase testability. The majority of the tests are already using the InMemory provider. Will this library support it?

**Comment by borisdj** [comment]
The library uses some methods that are relational-specific code (example: _Database.ExecuteSqlCommand_ ) and In-memory provider does not support that, so you can not have tests with non-relational db, you need relational one.
It is mentioned in comment(line 41):
`https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions.Tests/TestContext.cs`

More info:
[Exception when trying to use InMemoryDatabase for unit testing](https://github.com/aspnet/EntityFrameworkCore/issues/6080)
[using In Memory Database not working nicely with ASP.Net Core TestServer and Startup.cs](https://github.com/aspnet/EntityFrameworkCore/issues/5150)
