### ISSUE TITLE
Related Entity Not Inserted

### ISSUE THREAD

**Issue by jeffgbradley2** [borisdj/EFCore.BulkExtensions#240]
In EF Core 3.0, related entities to the aggregate are not inserted. So, when inserting lists of Parent objects with one or more Child objects, only the Parents are inserted into the database. The related entities have foreign keys defined in the model. The Children have a foreign key pointing to the Parent, and both Parent and Children have navigation properties. The navigation relationships are wired up in code both ways, i.e. child.Parent = parent and paent.Children.add(child). Is this by design?

**Comment by jeffgbradley2** [comment]
Reading into the docs I determined how to accomplish this. I suggest making this more clear in the docs, but other than that I really like this package.

**Comment by finsharp** [comment]
@jeffgbradley2 Can you point to your solution?
