### ISSUE TITLE
BulkRead doesn't work with RowVersion column

### ISSUE THREAD

**Issue by abakumovoleg** [borisdj/EFCore.BulkExtensions#243]
If you try to update entities with column of RowVersion type you will get an exception 'The required column 'RowVersion' was not present in the result of a 'FromSql''

**Comment by gouse-shaik** [comment]
For me, when I am inserting database entities which have a RowVersion defined, even though the transaction has completed the RowVersion property is not updated in the RAM(but was generated and saved in DB). This updation of the rowversion from null to a value is what I would get while using normal efcore commits.

**Comment by borisdj** [comment]
Try now with version 3.0.1
