### ISSUE TITLE
Timestamp/RowVersion is not updated for in-memory objects when BulkInsert is performed

### ISSUE THREAD

**Issue by gouse-shaik** [borisdj/EFCore.BulkExtensions#244]
I am trying to insert entities with BulkInsert. I have a simple table with a RowVersion enabled i.e., a Timestamp property of type byte[]. When I insert into the database, saving works but the entities which are just inserted are **not** updated to have the latest Timestamp. However, the newly generated Ids are updated into the in-memory objects.

When I put the BulkConfig flag "SetOutputIdentity = true", Timestamp does populate but when I put the other flag "PreserverInsertOrder = true" then Timestamp doesn't popuate into the in-memory objects after the bulkinsert has finished its operation.

To reproduce the issue, please check out this mock-repo:
https://github.com/gouse-shaik/TimestampIssueEFBulk/

**Comment by gouse-shaik** [comment]
I have a pull request open for this issue. Please verify if this can be the fix for this issue.
https://github.com/borisdj/EFCore.BulkExtensions/pull/250

**Comment by borisdj** [comment]
I have integrated this fix into current EF 3 branch and published nuget 3.0.1.
Can you upgrade to it.

**Comment by gouse-shaik** [comment]
I am using EF 2.4 version. I will not be able to use 3.0.1. Can you also merge this fix with 2.x package?
