### ISSUE TITLE
License shows expired after one month of use

### ISSUE THREAD

**Issue by ashcse** [borisdj/EFCore.BulkExtensions#245]
I have been using this extension for one month with dotnet core 2.2 . It shows MIT license but after one month of use it prompted me that license expired. Can you please confirm if its free or purchase required??

**Comment by borisdj** [comment]
Licence is MIT, as stated in ReadMe segment [Contributing](https://github.com/borisdj/EFCore.BulkExtensions#contributing), and it is Free.
