### ISSUE TITLE
Return number of updated records after using BulkUpdateAsync

### ISSUE THREAD

**Issue by HeshamW8** [borisdj/EFCore.BulkExtensions#247]
I am using the BulkUpdateAsync method to update a large number of records at once and it works fine, but I can't figure out how to know the number of records that have actually been updated. Is there a way to know the number of affected records by the operation. I need this info to be logged.

**Comment by borisdj** [comment]
Yes, there is info about this in ReadMe:

> When **CalculateStats** is set to True the result is return in `BulkConfig.StatsInfo` (_StatsNumber-Inserted/Updated_)

**Comment by HeshamW8** [comment]
@borisdj Thanks for the reply. But this does not seem to work with the method BulkInsertAsync. The StatsInfo is null even when I set CalculateStats to true. Also I don't think the numbers are very accurate. After a call to the "BulkInsertOrUpdateAsync" The StatsInfo.StatsNumberInserted was negative. What do you think is the issue? I am using version 2.6.3

**Comment by borisdj** [comment]
Can you please make a test where this would be reproducible.
