### ISSUE TITLE
BatchUpdate with non-public setters and/or nested owned types?

### ISSUE THREAD

**Issue by adr-v** [borisdj/EFCore.BulkExtensions#248]
I have DDD-style entity class with non-public default constructor and non-public property setters (can't use property initializers). Any way I can use BatchUpdate in this scenario?
Instantiating the entity using the "business" constructor in the update expression generates the following argument exception: "No mapping exists from object type ... to a known manager provider native type"
Same question for nested owned types, are these supported for BatchUpdate?

**Comment by borisdj** [comment]
Not sure, can you give an example with source code and make a Test for it.
