### ISSUE TITLE
Performance in ObjectReaderEx.cs (override object this[string name] - remove context.Entry())

### ISSUE THREAD

**Issue by karta95** [borisdj/EFCore.BulkExtensions#249]
Hi, is there any reason why context.Entry() is used instead of just base[name] in ObjectReaderEx?

So instead of :
`var current = this.current.GetValue(this); `
`var currentValue = context.Entry(current).Property(name).CurrentValue; `
 `return converter.ConvertToProvider(currentValue);`

something like this:

 `if (base[name] != DBNull.Value)`
 `{`
    `   return converter.ConvertToProvider(base[name]);`
 `}`

Am I missing some case?

**Comment by borisdj** [comment]
I actually think this method is no longer used, essentially deprecated since with Shadow properties DataTable is used instead of FastMember.
Reason being FastMember is slow for Update:
https://github.com/borisdj/EFCore.BulkExtensions/pull/17 - last 6 comments

**Comment by borisdj** [comment]
FastMember dependency is now removed.
Version 3.2.0+
