### ISSUE TITLE
BulkInsert/BulkUpdate throws InvalidOperationException: The given value of type String from the data source cannot be converted to type datetime2 of the specified target column

### ISSUE THREAD

**Issue by VBonapartov** [borisdj/EFCore.BulkExtensions#251]
-- Database schema
CREATE TABLE [dbo].[Authors](
	[AuthorId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[UpdatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

-- Entity
public class Author
{
     public int AuthorId { get; set; }
     public string FirstName { get; set; }
     public string LastName { get; set; }
}

-- Entity Configuration
public void Configure(EntityTypeBuilder<Author> builder)
{
            builder.HasKey(e => e.AuthorId);
            builder.Property(e => e.FirstName)
                .HasColumnName("FirstName")
                .IsRequired(false)
                .IsUnicode(true)
                .HasMaxLength(50);
            builder.Property(e => e.LastName)
                .IsRequired(true)
                .IsUnicode(true)
                .HasMaxLength(50);
            // Shadow properties
            builder.Property<DateTime>("CreatedDate");
            builder.Property<DateTime>("UpdatedDate");
}

Author author = new Author()
{
      FirstName = "FirstName",
      LastName = "LastName"                
};
 this.db.BulkInsert(new List<Author>() { author });

Executing the code above throws:
FormatException: The string 'Author' was not recognized as a valid DateTime. There is an unknown word starting at index '0'.
System.DateTimeParse.Parse(ReadOnlySpan<char> s, DateTimeFormatInfo dtfi, DateTimeStyles styles)

FormatException: Failed to convert parameter value from a String to a DateTime.
Microsoft.Data.SqlClient.SqlParameter.CoerceValue(object value, MetaType destinationType, out bool coercedToDataFeed, out bool typeChanged, bool allowStreaming)

InvalidOperationException: The given value of type String from the data source cannot be converted to type datetime2 of the specified target column.
EFCore.BulkExtensions.SqlBulkOperation.Insert<T>(DbContext context, IList<T> entities, TableInfo tableInfo, Action<decimal> progress)

--Platform
Visual Studio 2019
.NET Core 3.0
EFCore.BulkExtensions 3.0.0

**Comment by borisdj** [comment]
Add these Properties into Entity:
```C#
public DateTime? CreatedDate { get; set; }
public DateTime? UpdatedDate { get; set; }
```
