### ISSUE TITLE
Sqlite does not support nested transactions

### ISSUE THREAD

**Issue by matthiasJust** [borisdj/EFCore.BulkExtensions#252]
Hello,

i like to add a lot of items to an SqliteDB via EFCore.BulkExtensions.
My table look like this and has a **composite key**  and also an **foreign key**.
 
``` csharp
public class User
{
         // PrimaryKey via fluent api
        public int UserId { get; set; }
        // PrimaryKey via fluent api
        public string ServerNumber { get; set; }
        [ForeignKey("Adress_FK")]
        public Adress adress{ get; set; }
        public DateTime TimeStamp { get; set; }
        // and others ...
    }

public class Adress
    {
       [Key]
       public int Adress{ get; set; }
       public string Street{ get; set; }
       public string Number{ get; set; }
       // and others ...
       public DateTime TimeStamp { get; set; }
    }
``` 

I´m using this for my bulk action:
``` csharp
using (var transaction = db.Database.BeginTransaction())
                {
                    var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };
                    db.BulkInsert(Adress, bulkConfig);
                    db.BulkInsert(User, bulkConfig);
                    transaction.Commit();
                }
``` 

So i got this exception: 
>Sqlite does not support nested transactions

It´s not possible to use nested transactions with sqlite and EFCore.BulkExtensions?
Is there a workaround to fix this issue?

 im using:
- Microsoft.EntityFrameworkCore.Sqlite  2.2.6
- EFCore.BulkExtensions  2.6.3
- Microsoft.EntityFrameworkCore  2.2.6

**Comment by borisdj** [comment]
It is possible but for SQLite procedure is little specific.
Explanation is in [ReadMe/BulkInfo](https://github.com/borisdj/EFCore.BulkExtensions#bulk-info) **SQLite** segment.

**Comment by Will-I-Am-7** [comment]
I still get this exception even when using it as described in the readme.
