### ISSUE TITLE
sub entites are not in right structure

### ISSUE THREAD

**Issue by damirci** [borisdj/EFCore.BulkExtensions#254]
I'm using version 2.6.3 and I have this transaction
`            using (var transaction = DbContext.Database.BeginTransaction())
            {
                DbContext.BulkInsert(availables, bulkConfig);
                foreach (var available in availables)
                {
                    foreach (var hotel in available.Hotels)
                    {
                        hotel.AvailableId = available.Id;
                    }
                    hotels.AddRange(available.Hotels);
                }
                DbContext.BulkInsert(hotels, bulkConfig);

                foreach (var hotel in hotels)
                {
                    foreach (var room in hotel.Rooms)
                    {
                        room.HotelId = hotel.Id;
                    }
                    foreach (var suggest in hotel.SuggestedRooms)
                    {
                        suggest.HotelId = hotel.Id;
                    }
                    rooms.AddRange(hotel.Rooms);
                    suggests.AddRange(hotel.SuggestedRooms);
                }
                DbContext.BulkInsert(rooms);
                DbContext.BulkInsert(suggests);

                transaction.Commit();
            }`
but hotels available id change to another available in DB.
I have to say hotels in Available objects are ICollection.

**Comment by damirci** [comment]
I changed 
`        private static Expression<Func<DbContext, IQueryable<T>>> OrderBy<T>(Expression<Func<DbContext, IQueryable<T>>> source, string ordering)
        {
            Type entityType = typeof(T);
            PropertyInfo property = entityType.GetProperty(ordering);
            ParameterExpression parameter = Expression.Parameter(entityType);
            MemberExpression propertyAccess = Expression.MakeMemberAccess(parameter, property);
            LambdaExpression orderByExp = Expression.Lambda(propertyAccess, parameter);
            MethodCallExpression resultExp = Expression.Call(typeof(Queryable), "OrderBy", new Type[] { entityType, property.PropertyType }, source.Body, Expression.Quote(orderByExp));
            return Expression.Lambda<Func<DbContext, IQueryable<T>>>(resultExp, source.Parameters);
        }`

to =>
`        private static Expression<Func<DbContext, IQueryable<T>>> OrderBy<T>(Expression<Func<DbContext, IQueryable<T>>> source, string ordering)
        {
            Type entityType = typeof(T);
            PropertyInfo property = entityType.GetProperty(ordering);
            ParameterExpression parameter = Expression.Parameter(entityType);
            MemberExpression propertyAccess = Expression.MakeMemberAccess(parameter, property);
            LambdaExpression orderByExp = Expression.Lambda(propertyAccess, parameter);
            MethodCallExpression resultExp = Expression.Call(typeof(Queryable), "OrderByDescending", new Type[] { entityType, property.PropertyType }, source.Body, Expression.Quote(orderByExp));
            return Expression.Lambda<Func<DbContext, IQueryable<T>>>(resultExp, source.Parameters);
        }`

And it's work fine.
any Comment?

**Comment by snowpl** [comment]
Hello,
I am having the same issue. Could you please write where had you changed the code? And maybe why changing orderBy into OrderByDescending is fixing this?
thanks

**Comment by greghunterSainsburys** [comment]
I've just raised a new issue https://github.com/borisdj/EFCore.BulkExtensions/issues/264 but it might be the same problem you are experiencing.

**Comment by greghunterSainsburys** [comment]
> Hello,
> I am having the same issue. Could you please write where had you changed the code? And maybe why changing orderBy into OrderByDescending is fixing this?
> thanks

In the file tableinfo.cs, towards the end in the method called OrderBy<T>

**Comment by borisdj** [comment]
I have added comment to issue 264.
Check if that solves this issue as well.
