### ISSUE TITLE
For Query with parameterized variable BatchOperation requires argument 'parametersDict'

### ISSUE THREAD

**Issue by sstalder** [borisdj/EFCore.BulkExtensions#256]
Getting this error when trying a BatchDelete after upgrading to dotnet core 3.

Switching to BulkDeleteAsync does work however, just wanted to report the issue.

`await _ctx.Errors
                .Where(x =>
                    x.BillingCycleId == billingCycleId &&
                    x.PropertyId == propertyId
                )
                .BatchDeleteAsync();`

System.InvalidOperationException: For Query with parameterized variable BatchOperation requires argument 'parametersDict' (Name and Value). Example in library ReadMe. SourceMessage: Must declare the scalar variable "@__billingCycleId_0".
Incorrect syntax near 'b'.
Incorrect syntax near 'b'.)
   at EFCore.BulkExtensions.BatchUtil.ExecuteSqlAsync(DbContext dbContext, String sql, List`1 sqlParameters, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync[T](IQueryable`1 query, Dictionary`2 parametersDict, CancellationToken cancellationToken)

Any suggestions are appreciated, thanks!

**Comment by borisdj** [comment]
Try v3.0.1. where the '_parametersDict_' is now removed.

**Comment by alexb5dh** [comment]
Getting the same error in 3.0.1

**Comment by borisdj** [comment]
Fix v2 NuGet 3.0.2
