### ISSUE TITLE
InsertOrUpdate Violation of PRIMARY KEY constraint

### ISSUE THREAD

**Issue by derodevil** [borisdj/EFCore.BulkExtensions#257]
public class Parent
	{
		public Parent()
		{
			Children = new List<Child>();
		}
		
		[Key]
		public string ParentId { get; set; }
		public string Name { get; set; }
		public DateTime Dob { get; set; }
		
		public List<Child> Children { get; set; }
	}

	public class Child
	{
		[Key]
		public string ChildId { get; set; }
		public string ParentId { get; set; }
		public int Age { get; set; }
		public string Name { get; set; }
		
		[ForeignKey("ParentId")]
		public Parent Parent { get; set; }
	}

	public void Test()
	{
		var listOfParent = new List<Parent>();
		
		for(var i=0;i<1000;i++)
		{
			var parentId = "P"+ i.ToString();
			
			var children = new List<Child>();
			for(var c=0;c<4;c++)
			{
				var child = new Child
				{
					ChildId = parentId + "-" + c.ToString(),
					ParentId = parentId,
					Age = i + 10,
					Name = "Name Child " + i.ToString()
				};
				children.Add(child);
			}
			
			var parent = new Parent
			{
				ParentId = parentId,
				Name = "Name Parent "  + i.ToString(),
				Dob = DateTime.Now,
				Children = children
			};
			
			listOfParent.Add(parent);
		}
		
		using(var context = new MyContext())
		{
			context.BulkInsertOrUpdate(listOfParent);
		}
		
		listOfParent[0].Name = "EDITED";
		var additionalParent = new Parent
		{
			ParentId = "P-Additional",
			Name = "Name Additional",
			Dob = DateTime.Now
		};
		listOfParent.Add(additionalParent);
		using(var context = new MyContext())
		{
			context.BulkInsertOrUpdate(listOfParent);
		}
	}

How to achieve the above scenario? I have two problems with this scenario
1. `BulkInserOrUpdate` acts like` BulkInsert` where it doesn't update existing data. I think it would update existing data based on primary key but it didn't. The first execution was successfully inserted into database (if I exclude `Children` property) but the second execution generates error of primary key violation.
2. How to include `Children` property without any errors that I don't need to insert twice (parent and children)?

**Comment by borisdj** [comment]
1. I have run your test and this works fine.
2. Make list of all child entities and then Insert them:
```C#
var listOfParent = new List<Parent>();
var listOfChildren = new List<Child>();

for (var i = 0; i < 1000; i++)
{
	var parentId = "P" + i.ToString();

	for (var c = 0; c < 4; c++)
	{
		var child = new Child
		{
			ChildId = parentId + "-" + c.ToString(),
			ParentId = parentId,
			Age = i + 10,
			Name = "Name Child " + i.ToString()
		};
		listOfChildren.Add(child);
	}

	var parent = new Parent
	{
		ParentId = parentId,
		Name = "Name Parent " + i.ToString(),
		Dob = DateTime.Now
	};

	listOfParent.Add(parent);
}

using (var context = new TestContext(ContextUtil.GetOptions()))
{
	context.BulkInsertOrUpdate(listOfParent);
	context.BulkInsertOrUpdate(listOfChildren);
}
```

**Comment by derodevil** [comment]
> 1. h
For question no.1 I resolve the issue by myself, I have duplicate key in the list. For example, I have two ParentId with value "ABC" in the list. When I remove the duplicate keys the code runs well. This case was solved. Thank you.

**Comment by ajeyaprakash148** [comment]
If we use Db Identity, PreserveInsertOrder = true, SetOutputIdentity = true works well with bulk insert for both parent and child with Transaction.
