### ISSUE TITLE
How to log the queries and will it update only modified fields in DB?

### ISSUE THREAD

**Issue by Yajuvender** [borisdj/EFCore.BulkExtensions#260]
Hi,

How can i log the sql queries which get executed when BulkUpdate() is called?

In EF Core, we can setValues like "context.Entry(existingStudent).CurrentValues.SetValues(student);" to Update only the modified fields back into the database. How does BulkExtension ensure that only modified fields are saved back in the database?

Thanks.

**Comment by borisdj** [comment]
In ReadMe there is info about config _PropertiesToInclude_ and _PropertiesToExclude_ that can be used to specify which only properties to change.
