### ISSUE TITLE
Add Truncate method

### ISSUE THREAD

**Issue by KLuuKer** [borisdj/EFCore.BulkExtensions#261]
i'm using your very handy bulk updater, to do some bulk cleanup
and i noticed the truncate command is not available

would be nice if you could add it so i don't have to manually write the sql for it anymore

**Comment by Adam-STaC-Solutions** [comment]
Seconded. I was looking for a bulk delete that doesn't require me to get the full table first.

**Comment by borisdj** [comment]
Added with 3.0.4.
