### ISSUE TITLE
Rollback multiple transactions?

### ISSUE THREAD

**Issue by Asugusto** [borisdj/EFCore.BulkExtensions#262]
Hi, i was wondering how this will deal with multiple commands if one of them fails, for example:

await _repository.BulkDeleteAsync(currentRecords);
await _repository.BulkInsertOrUpdateAsync(model);

what if the BulkInsertOrUpdateAsync fails? it will rollback the BulkDeleteAsync? 
should i wrap this in a transaction? 

Thanks

**Comment by borisdj** [comment]
Yes it should be in Transaction as stated in ReadMe.
