### ISSUE TITLE
Bulk Insert to SQL Server with PreserveInsertOrder and SetOutputIdentity assigns Id's in reverse order

### ISSUE THREAD

**Issue by greghunterSainsburys** [borisdj/EFCore.BulkExtensions#264]
Hi,

I've found that when adding a list of entities that get assigned Identities by the Db the bulk insert assigns the Id's in reverse order.

IE, add three entities to a list with Name and Id field, names set to One, Two, Three, Id's left at zero, then add to the context using bulk insert with PreserveInsertOrder and SetOutputIdentity both set to true.

Id's assigned when returning from the call are:
One 1
Two 2
Three 3

However looking on the Db itself you get:
Three 1
Two 2
One 3

The problem seems to be in the file TableInfo.cs, line2 512-514, where the two lists of entities passed into:
                UpdateEntitiesIdentity(entities, entitiesWithOutputIdentity);
are in a reverse order to each other.

I have created a simple test project to demonstrate the issue which is attached. To see the issue load the project in VS 2019, run the update Db command in powershell (example in the file MigrationCommands.txt), once the local Db is created run the app, and compare the output in the console window to the actual results on the local Db.

[EFBulkInsertProblem.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/3911128/EFBulkInsertProblem.zip)

**Comment by greghunterSainsburys** [comment]
Might be linked to this other issue?

https://github.com/borisdj/EFCore.BulkExtensions/issues/254

**Comment by borisdj** [comment]
You should also 'temporarily' set Ids to proper order as explained in ReadMe ([BulkConfig arguments](https://github.com/borisdj/EFCore.BulkExtensions#bulkconfig-arguments)):

> When using PreserveInsertOrder with SetOutputIdentity Id value does matter.
> If it's BulkInsertOrUpdate method for those that will be updated it has to match Id.
> And if we need to sort those for insert(BulkInsert/OrUpdate) and not have conflict with existing Id-s, there are 2 ways:
> One is set Id to really high values, order of magnitude 10^10, and another even better setting them to negative values.
> So if we have list of 8000, say 3000 for update (they keep the real Id) and 5000 for insert then Id-s could be (-5000:-1).
