### ISSUE TITLE
Different collation in DB and Temp DB

### ISSUE THREAD

**Issue by abakumovoleg** [borisdj/EFCore.BulkExtensions#274]
Methods like BulkInsertOrUpdate, or BulkInsertOrUpdateOrDelete doesn't work when collation in temp DB differs from collation in main DB. I think that varchar columns in temp tables should be created with keyword COLLATE DATABASE_DEFAULT.

**Comment by piotrczyz** [comment]
I face the same problem. Any workaround?

**Comment by borisdj** [comment]
Can you first give example on how to reproduce the issue.
And secondly Where could Collation be defined.
Temp tables are created with sql:
```SQL
SELECT TOP 0 T.[ItemId], T.[Description], T.[Name], T.[Price], T.[Quantity], T.[TimeUpdated] -- All columns: SELECT TOP 0 Source.*
INTO [dbo].[ItemTemp1234] FROM [dbo].[Item] AS T
LEFT JOIN [dbo].[Item] AS Source ON 1 = 0; -- removes Identity constrain
```
I have tried adding at the bottom line:
`COLLATE DATABASE_DEFAULT` ([from here](https://stackoverflow.com/questions/21332105/temp-table-collation-conflict-error-cannot-resolve-the-collation-conflict-be))
but it's not valid sql.
