### ISSUE TITLE
Rowversion column isn't retrieved on BulkRead

### ISSUE THREAD

**Issue by phil-marino** [borisdj/EFCore.BulkExtensions#275]
Hi - I don't have a simple repro case because I've added this library to a larger application, but I wanted to report what seems like an issue with the rowversion logic.

I'm attempting to do a bulk read with a set of objects that contain properties that I'm using to search - this is a duplicate check on a set of columns.  

My entity looks something like:

```
public class EntityBase
{
    [Key]
    public long ID { get; set; }

    public DateTime CreatedOn { get; set; }
    (... other audit columns)

    [Timestamp]
    public byte[] RowVersion { get; set; }
}

public class MyEntity : EntityBase
{
    public string Field1 { get; set; }
    public string Field2 { get; set; }
    public string Field3 { get; set; }
}

```

I'm doing a BulkReadAsync like this:

```
var existing = entities.Select(e => new MyEntity
{
    Field1 = e.Field1,
    Field2 = e.Field2, 
    Field3 = e.Field3
});

```

None of these are primary keys.

I then do the bulk read:

```
await context.BulkReadAsync(existing, 
    new BulkConfig
    {
        UpdateByProperties = new List<string> 
        {
             nameof(MyEntity.Field1),
             nameof(MyEntity.Field2),
             nameof(MyEntity.Field3),    
        }
    });

```

I see the select returning every column in MyEntity except for RowVersion.  This causes an exception:

System.InvalidOperationException: The underlying reader doesn't have as many fields as expected.
I think this is because it's missing RowVersion

Note that I did try removing the rowversion column from the base entity and put it in the derived entity, but this also didn't work.

The other audit columns are retrieved correctly.

Edit: the difference is between Read and ReadAsync:

Read:

tableInfo.PropertyColumnNamesDict = tableInfo.OutputPropertyColumnNamesDict;

ReadAsync:

tableInfoPropertyColumnNamesDict = previousPropertyColumnNamesDict;

These should both be OutputPropertyColumnNamesDict, right?

**Comment by borisdj** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/issues/243

**Comment by phil-marino** [comment]
I'm sorry to be a pain here, but this isn't the same as #243.  That deals with Updates.  This issues deals with Reading.  I tried with the latest version (3.1.1), and encountered the same problem.  Again, Read and ReadAsync have a lot of the similar code, but Read has this at line 464:

tableInfo.PropertyColumnNamesDict = tableInfo.OutputPropertyColumnNamesDict;

ReadAsync has this at line 536:

tableInfo.PropertyColumnNamesDict = previousPropertyColumnNamesDict;

It looks like this is a copy/paste error, and it's not including the RowVersion column.
