### ISSUE TITLE
Inserting entities with abstract base type

### ISSUE THREAD

**Issue by NQuirmbach** [borisdj/EFCore.BulkExtensions#278]
Hello,

I came accross an issue when inserting a list of entities with an abstract base type (TPH pattern) and the enumerable passed into the function is of the base type.

The problem here is that none of the derived properties are filled only the ones from the base type.

I've created a repo to reproduce the error: 
https://github.com/NQuirmbach/BulkTest

Is this an inteded behaviour?

**Comment by NQuirmbach** [comment]
I found a solution and created a pull request:

https://github.com/borisdj/EFCore.BulkExtensions/pull/279

**Comment by borisdj** [comment]
Merged and NuGet 3.1.1 published.
