### ISSUE TITLE
Support INSERT INTO FROM by new extension method

### ISSUE THREAD

**Issue by yang-er** [borisdj/EFCore.BulkExtensions#282]
Thanks for your good BatchUpdate(Async) and BatchDelete(Async) functions, it helped a lot.

What about adding new extension method `IQueryable<T1>.BatchInsertTo(DbSet<T2>, Expression<T1, T2>)` to support queries like `INSERT INTO [MyDb1] ([AAA], [BBB]) SELECT [a].[CCC] AS [AAA], [b].[DDD] AS [BBB] FROM [ASet] AS [a], [BSet] AS [b]` or so on?

**Comment by borisdj** [comment]
For insert from one table to another you can use BulkRead with BulkInsert, or just pure SQL.
