### ISSUE TITLE
Update only Not Null fields in BulkUpdate

### ISSUE THREAD

**Issue by Yajuvender** [borisdj/EFCore.BulkExtensions#285]
Hi,

My idea is to use BulkUpdate to update only the modified fields. If i am passing only modified fields then its updating 'null' for remaining fields in the rows. Also PropertiesToExclude is excluding the column from all the rows.

Is there a way to update only the modified fields?

Note: each row data will have different modified fields/columns. 

Can someone please guide on this issue?

Regards,
Yaju

**Comment by kKen94** [comment]
+1

**Comment by borisdj** [comment]
Such a combination is not supported.
You can either Update some columns and skip other using _PropertiesToExclude_.
Or when you want to update different fields in the same List then _BulkRead_ can be used, make changes and call _BulkUpdate_.
