### ISSUE TITLE
BulkInsert with SetOutputIdentity = true reverses Ids if 100 or less rows inserted

### ISSUE THREAD

**Issue by goodoldgrim** [borisdj/EFCore.BulkExtensions#286]
Not doing anything fancy. I insert a list of rows:

```
var bulkConfig = new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity = true };
await context.BulkInsertAsync(newRows, bulkConfig);
```

At this point, the Ids of newRows are filled, but in reverse order from how they are filled in the database. If there's more than 100 rows it works fine (tested with ~150, ~200, ~1400), if there's less than 100 rows, the Ids are reversed (tested with about 10 different sizes).

For clarity, if I insert rows: 
```
[
  { Id = 0, Content = A},
  { Id = 0, Content = B},
  { Id = 0, Content = C},
]

```
They are updated to:
```
[
  { Id = 1, Content = A},
  { Id = 2, Content = B},
  { Id = 3, Content = C},
]

```
But the rows in the database end up being:
```
[
  { Id = 3, Content = A},
  { Id = 2, Content = B},
  { Id = 1, Content = C},
]
```

**Comment by msarvankmr** [comment]
Hi,
I have also faced the same issue, using version 3.1.0, any fix or workaround for this issue?

**Comment by sergioprates** [comment]
Same here

**Comment by tamirzamo** [comment]
same problem here,
i saw this post https://github.com/borisdj/EFCore.BulkExtensions/issues/264 
thats say to give temporary ids and i checked and  its work.
this question is if its temporary  solution or they gonna fix it ?

**Comment by borisdj** [comment]
There is now explanation in this issue: https://github.com/borisdj/EFCore.BulkExtensions/issues/299
