### ISSUE TITLE
Unable to form nuget packages when referencing 3.1.0 EfCore.BulkExtensions

### ISSUE THREAD

**Issue by AlexEngblom** [borisdj/EFCore.BulkExtensions#289]
When referencing latest EFCFore.BulkExtensions, we are unable to create packages via NuGet pack. This happens because of EFCore 3.1.0 sub dependencies inside bulkextensions package. This on the other hand is due to known issues within NuGet itself, which were handled in EFCore 3.1.1 packages.

More information can be found from here:
https://github.com/dotnet/efcore/issues/19542

NuGet pack exception 'The DateTimeOffset specified cannot be converted into a Zip file timestamp.' seems to be thrown because of following assemblies:
- Microsoft.Data.Sqlite.dll
- Microsoft.EntityFrameworkCore.Sqlite.dll

**Comment by borisdj** [comment]
Lib updated to 3.1.1.
