### ISSUE TITLE
 Must declare the scalar variable "@__id_0"

### ISSUE THREAD

**Issue by toralux** [borisdj/EFCore.BulkExtensions#292]
I'm doing a update that used to work in BulkExtenisions 2.x:

`await _dbContext.Objects.Where(x => x.Id == id).BatchUpdateAsync(x => new Data.Entities.Objects.GeneralObject { VisitCount = x.VisitCount + 1 });
`

Now it's broken in BulkExtenisions 3.1.0.0 after upgrading...

`UPDATE o SET  [o].[VisitCount] = [o].[VisitCount] + @param_0
FROM [Objects] AS [o]
WHERE [o].[ObjectDiscriminator] IN (0, 1, 2, 3, 4) AND ([o].[Id] = @__id_0)
2020-02-08 23:20:54 [ERR]   Microsoft.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@__id_0".
`

This could be caused by using Inheritance? Did you test this with 3.x?
https://docs.microsoft.com/en-us/ef/core/modeling/inheritance

**Comment by seiroga** [comment]
same issue :(, I am also trying to update entity through base class

**Comment by borisdj** [comment]
Try now with version 3.1.1

**Comment by seiroga** [comment]
It works! Thanks!
