### ISSUE TITLE
SqliteConnection option usage and relevance

### ISSUE THREAD

**Issue by Manny651** [borisdj/EFCore.BulkExtensions#305]
Every time BulkInsert is used in a Sqlite transaction, whe have to set the BulkConfig.SqliteConnection = (SqliteConnection)context.Database.GetDbConnection()

This seems redundant. Is there a case where BulkConfig.SqliteConnection isn't the current context connection?

**Comment by borisdj** [comment]
When using Sqlite I couldn't read SqliteConnection properly unless it's passed directly, and BulkConfig is used for it.
