### ISSUE TITLE
Is there an option to specify the target table name?

### ISSUE THREAD

**Issue by KuhnEDV** [borisdj/EFCore.BulkExtensions#311]
Is there an option to specify the target table name, if the entities collection should be inserted into another table than the entity type name?

**Comment by borisdj** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/issues/67

**Comment by borisdj** [comment]
No, the library is extension of EFCore, so you need Entity of the source table.
If you don't have it already in code just make the Entity and add a collection.

**Comment by KuhnEDV** [comment]
My question was not about the source but the target table. This is a property of SqlBulkCopy.

Why not adding a property named DestinationTableName to BulkConfig and using that in SqlBulkOperation like this:
`                        if (!String.IsNullOrWhiteSpace(tableInfo.BulkConfig.DestinationTableName))
                            sqlBulkCopy.DestinationTableName = tableInfo.BulkConfig.DestinationTableName;
`

I tried that already on a clone and it works fine.

**Comment by borisdj** [comment]
Correction, I've meant the destination table.
Because you need Entities to read all properties and meta info, I don't see he significant benefit in adding feature that can target any table, outside ones in DbSet.
What's you use case, why not have the Entity of the target table?

**Comment by KuhnEDV** [comment]
For creating an extraction of the data in the source table and saving this after modifications to a separate but similar destination table for use in another program with a its own DbContext.

**Comment by borisdj** [comment]
Still can't you just add Entity in the first program.
And if you have more then one table like this and also want to isolate them then maybe make separate context for this copying.

**Comment by KuhnEDV** [comment]
This sounds cumbersome and DestinationTableName is a normal property of SqlBulkCopy. The relation to entities is only relevant on the source and not on the destination.

**Comment by borisdj** [comment]
Of SqlBulkCopy yes, but this is EF extesion.
It somewhat goes against its definition to skip Entity, and also then there is no validation if target table has all the required fields.
I understand your use case, and will consider whether this feature could be added.
