### ISSUE TITLE
Rowversion column isn't retrieved on ReadAsync (reopen)

### ISSUE THREAD

**Issue by phil-marino** [borisdj/EFCore.BulkExtensions#313]
Hi - not sure if this is the right way to handle this.  Issue #275 was closed as a duplicate, but I don't think it's exactly the same problem.  If you could look at my suggestion for the fix, I would appreciate it.

Problem:
When doing ReadAsync on a table with RowVersion, an exception is generated:  

System.InvalidOperationException: The underlying reader doesn't have as many fields as expected.

I think this is because it's missing RowVersion

I updated to 3.1.1, and this is still happening.

I'm pretty sure it's not setting the PropertyColumnNamesDict correctly.  Read and ReadAsync have a lot of the same code, but there's one important difference.

Read, SqlBulkOperations.cs, line 464: 
tableInfo.PropertyColumnNamesDict = tableInfo.OutputPropertyColumnNamesDict;

ReadAsync, SqlBulkOperations.cs, line 536:
tableInfo.PropertyColumnNamesDict = previousPropertyColumnNamesDict;

It looks like Read is setting the value for what to expect correctly, while ReadAsync does not.  

When I change this code locally, and reference the downloaded source project instead of the Nuget package, ReadAsync works.  When I put it back to the original source, it fails with the above exception.

Please refer to issue #275 for an outline of the repro case; I don't have a simple case at the moment.
Please consider the fix that I mentioned above.  Thanks.

**Comment by borisdj** [comment]
Fixed
