### ISSUE TITLE
StatsInfo Not Populating When SetOutputIdentity and CalculateStats are set to true.

### ISSUE THREAD

**Issue by kcmdavid** [borisdj/EFCore.BulkExtensions#316]
I'm trying to use the following code to insert entities into an SQLite database.

```
  var config = new BulkConfig
            {
                SetOutputIdentity = true,
                CalculateStats = true,
                StatsInfo = new StatsInfo()
            };
            _dbContext.BulkInsertOrUpdate(humanList, config);

            return config.StatsInfo.StatsNumberInserted; 
```

I've read the readme and setting CalculateStats to true should populate StatsInfo with the amount inserted and updated, but after debugging, both of those values are set to 0. Is this a bug or am I missing something?

**Comment by borisdj** [comment]
Your code seems fine.
You can check that **StatsInfo** work if you download the Project and run _BulkTest_.
(put breakpoint in method _RunInsertOrUpdate_ on line 207)

**Comment by kcmdavid** [comment]
I ran the test and I noticed that the StatsInfo object is still null at line 207. How do you access the information inside the StatsInfo object if you don't set it to a new instance of a StatsInfo object? Isn't it supposed to populate when CalculateStats is set to true?

**Comment by borisdj** [comment]
I only now see that this issue is for Sqlite, I was testing it for SqlServer.
On Sqlite this feature is not supported since it is implemented as part of MERGE-Table statement which exist only for SqlServer, there when CalculateStats is set then StatsInfo is automatically instantiated,
On Sqlite Merge is done with raw Sql.

**Comment by kcmdavid** [comment]
Is there a workaround for this that can work with Sqlite? The issue is that my database could be inserting entities, so I can't compare the entities before and after the operation because new data is always being pushed to the database, but I need to know how much data was imported so I know how successful my import operation was.

**Comment by kcmdavid** [comment]
I tried using BulkRead. However a MethodIsNotImplementedError is thrown. I've followed the example and I have included sample code below.

```
  var config = new BulkConfig
            {
                UpdateByProperties = new List<string> { nameof(HumanEntity.Id) },
            };
            _dbContext.BulkRead(humanList, config);
            _dbContext.BulkInsertOrUpdate(humanList, config);
```
 Is there something I'm missing for specifcally Sqlite that prevents BulkRead from working?

**Comment by borisdj** [comment]
You are right, that's still not implemented for Sqlite.

**Comment by kcmdavid** [comment]
Ahh okay I see know. So is there a workaround that would work for Sqlite or would I not be able to calculate the amount of entities imported with BulkInsertOrUpdate() ?

**Comment by borisdj** [comment]
You could try with regular Read(Select), if there isn't too much rows in Db.
Otherwise no other option at the moment.

**Comment by borisdj** [comment]
BulkRead is now implemented for Sqlite, v5.0.8.+

**Comment by KevinSebastin** [comment]
I am using 8.0.0 in an Azure Function (dotnet-isolated) against Azure SQL DB (elastic pool).
StatsInfo doesnt seem to populate nor be instantiated.

I have tried reading statsinfo inside the strategy execution as well (see example) - its always null.

I tried to find where it is being set with little luck. Seems like only the graph part uses StatsInfo? 
But even with IncludeGraph, StatsInfo is always null.

Is there any other way to get affected records / inserts count like the int result from SaveChanges (besides counting before after or comparing unique ids)?

Kind Regards

*********
          bulkConfig = new BulkConfig 
          { 
              BatchSize = 10000, 
              CalculateStats = true, 
              SetOutputIdentity = true, //tried with this as well
              IncludeGraph = true, //tried with this as well
              SetOutputNonIdentityColumns = true //tried flipping this as well
          }; 

*********
            await _strategy.ExecuteAsync(
                async () =>
                {
                    using var transaction = await context.Database.BeginTransactionAsync(IsolationLevel.Snapshot);

                    await context.BulkDeleteAsync(context.SowRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.FarrowingRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.MatingRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.MedicineusageRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.WeaningRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.BackFatSowsRows.Where(x => x.farmId == farmId), bulkConfig);
                    await context.BulkDeleteAsync(context.PigletDeathRows.Where(x => x.farmId == farmId), bulkConfig);

                    await transaction.CommitAsync();
                });
            totalRowsDeleted = bulkConfig.StatsInfo.StatsNumberDeleted;

**Comment by L-Sypniewski** [comment]
@KevinSebastin Have you tested whether it works against a local SQL Server container?
The following `BulkConfig` have `StatsInfo` populated for a local instance of SQL Server 2022:
```csharp
    var bulkConfig = new BulkConfig
        {
            BatchSize = batchSize,
            SetOutputIdentity = true,
            CalculateStats = true,
        };
```
I'm using version `8.0.1` of BulkExtensions with a strategy execution:
```csharp
      var executionStrategy = dbContext.Database.CreateExecutionStrategy();
        return executionStrategy.ExecuteAsync(async () =>
        {
            await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken).ConfigureAwait(false);
            try
            {
                await saveData(dbContext, data, batchSize, logger, cancellationToken).ConfigureAwait(false);
                await transaction.CommitAsync(cancellationToken).ConfigureAwait(false);
                await onSuccessfulSave().ConfigureAwait(false);
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken).ConfigureAwait(false);
                throw;
            }
        });
```
