### ISSUE TITLE
Does BatchSize helps the performance for insert/update

### ISSUE THREAD

**Issue by santosh-kh** [borisdj/EFCore.BulkExtensions#317]
My Scenario: 
I'm using BulkInsert. 
Parent entity has 2 children. Number of records for child 1 in range 20 - 200. For child 2  it's between 100 -1000. Average entity columns - 12.  
Does BatchSize helps the performance?
What's the batch size, i should use to get the better performance? 
I tried BenchmarkDotNet - i didn't see any performance gain for BatchSize = 1000 for records 2000 & 5000.

**Comment by borisdj** [comment]
I think batch size has effect only on big number of row, scale hundreds of thousand or more.

**Comment by santosh-kh** [comment]
My thought was as records were high with children, as in my test it was 200 child-1 records and 1000 child-2 records per parent. 
For 5000 parent records it was almost 6,000,000 records to insert.
Do we have any guideline here?

**Comment by borisdj** [comment]
https://www.sqlbi.com/wp-content/uploads/SqlBulkCopy-Performance-1.0.pdf

**Comment by santosh-kh** [comment]
Thanks for the reference.

**Comment by gojanpaolo** [comment]
@borisdj Why is the default `BatchSize` set to `2000`? In the reference you mentioned, it says:

> the best thing to do with BatchSize is to leave it to zero, which is its default value, since any value different from that will decrease the performance of the load process.
