### ISSUE TITLE
How bulkinsert without PK

### ISSUE THREAD

**Issue by rafaelcanto** [borisdj/EFCore.BulkExtensions#318]
Hi,

How can I bulk insert without PK? Tried it, but I'm receiving an Object reference exception.

**Comment by borisdj** [comment]
It didn't work without PK, but there is easy fix.
However it's not published yet. Will see to do it soon.
https://github.com/borisdj/EFCore.BulkExtensions/issues/291

**Comment by borisdj** [comment]
Fixed with Nuget 3.1.2
