### ISSUE TITLE
How bulkinsert in #TempTable

### ISSUE THREAD

**Issue by vnikopol** [borisdj/EFCore.BulkExtensions#319]
I want to use bulk insert in temp table (#TempTable). I am creating TempTable in OneConnection like:
` CREATE TABLE #TempTable (Id primary UNIQUEIDENTIFIER)` Next i do bulk insert, but after that
if i want to select from this table i will get error: Invalid object name '#TempTable'. AddRange is work fine. 

As I understand it, the problem is that I have database CurrentTransaction = null (use TransactionSope) and after Insert connection closes. (see class **SqlBulkOperation** -> method **Insert** -> block **finally**

Is there use bulkinsert possible for temp table without db transaction?

**Comment by borisdj** [comment]
Bulk ops require Entity so you can't insert into TempTable that is dynamically created since there is no mapping Entity.
Or more precisely TempTable can not be end table but is only used as one through which data goes for update operation.
