### ISSUE TITLE
Avoid unique temp table names

### ISSUE THREAD

**Issue by MrkNavratil** [borisdj/EFCore.BulkExtensions#326]
In some cases, it's beneficial not to create unique table names in TempDb (i.e use #MyTableTemp instead of '#MyTableTempad1e4btb'). When you use bulk operations in a repetitive way on same data structures then you are doing 'same' queries/operations but you are forcing DB engine to create new execution plans over and over again because the name of the temp table changes with every query/operation.

**Comment by borisdj** [comment]
I have merged your pullRequest and made some changes, UniqueTableNameTempDb is now directly in BulkConfig.
Another class for one property was redundant.

**Comment by MrkNavratil** [comment]
Thank you. When can I expect these changes to be released?

**Comment by ramafmgl** [comment]
Its already released

**Comment by dasariramacharan** [comment]
Already released..
