### ISSUE TITLE
Bulkinsert with one to one relationship

### ISSUE THREAD

**Issue by mangalord** [borisdj/EFCore.BulkExtensions#328]
I'm trying to use bulkinsert in .NET Core 2.1 with one to one relationships. I have 2 Database Entities

```
public partial class Entity1
{
    public int ID { get; set; }
    public virtual Entity2 Entity2Obj { get; set; }
}
```
```
public partial class Entity2 
{
    public int ID { get; set; }
    public int Entity1_ID{ get; set; }
    public virtual Entity1 Entity1Obj { get; set; }
}
```
The navigation properties are automatically created during Scaffold-DbContext (database first)

```
entity.HasOne(d => d.Entity1 )
    .WithOne(p => p.Entity2)
    .HasForeignKey<Entity2>(d => d.Entity1_ID)
    .OnDelete(DeleteBehavior.ClientSetNull)
    .HasConstraintName("FK_Entity1_Entity2");
```

Then I insert a list of Entity1 Items

` _context.BulkInsert(Entity1ItemsList);`

This only works and inserts Entity1 objects in my database. The associated Entity2 items are not inserted. Is there a way to achieve that? When I insert the entities with the default context.savechanges() all navigation properties are saved successfully.

**Comment by borisdj** [comment]
There is no BulkSaveChanges at the moment, so you need to call BulkInsert for each table.
