### ISSUE TITLE
SqlException when IQueryable has TagWith comments 

### ISSUE THREAD

**Issue by RyanThomas73** [borisdj/EFCore.BulkExtensions#333]
The BatchUtil.GetBatchSql(..) logic is hard coded under the assumption that the parameterized sql begins with a string in the form "SELECT ...". This is not the case when the queryable has leading comment lines from the IQueryable TagWith(..) extension methods.

In such cases, the GetBatchSql(..) incorrectly parses the base sql from EF and attempts to execute invalid sql.

e.g.
```
var updatedRecordCount = await testDataContext.Set<Person>()
                    .TagWith("From: {someCallSite} in {someClassName}")
                    .Where(person => targetPeopleIds.Contains(person.Id))
                    .BatchUpdateAsync(person => new Person() { Notes = updatedNote })
                    .ConfigureAwait(false);
```

The sql generator will output initial sql something like this:
``` 
-- From: MyAutomatedTestMethod in MyAutomatedTestSuite

SELECT [p].[Id], [p].[AlternateId], [p].[FirstName], [p].[IsJedi], [p].[LastName], [p].[Notes]
FROM [Person] AS [p]
WHERE [p].[Id] IN (1, 2, 3)
```

A basic workaround would be to first separate the leading comments and whitespace from the portion that is parsed.

**Comment by borisdj** [comment]
I have added the following segment at the end of `RunBatchUpdateAsync` method in `BatchTestAsync` class:
```C#
var updatedCount = await context.Set<Item>()
                                .TagWith("From: {someCallSite} in {someClassName}") // To test parsing Sql with Tag leading comment
                                .Where(a => list.Contains(a.Description))
                                .BatchUpdateAsync(a => new Item() { Description = "Updated2" })
                                .ConfigureAwait(false);
```

And after running the Test still get the exception:

>  Input string was not in a correct format.

The issue is this line:
`
var resultQuery = $"{leadingComments}UPDATE {topStatement}{tableAlias}{tableAliasSufixAs} SET {sqlColumns} {sql}";
`
because `leadingComments` containing _"-- From: {someCallSite} in {someClassName}\r\n\r\n"_
is prefixed to resultQuery.
Why is `leadingComments` here ?

**Comment by RyanThomas73** [comment]
Leading comments needs to be prepended back to result query or the comment won't be in the executed sql which is the purpose of the `.TagWith(..)` with method.

Is the test code above literal, e.g. are you actually putting in `{` `}` characters? If so I believe the problem in your test case is those characters are not valid in an `.ExecuteSqlRaw(..)` call. If you remove those and put a `.TagWith("From: SomeCallSite in SomeClassName")` call, does the test pass?

**Comment by borisdj** [comment]
Without '{' it passed.
NuGet 3.1.5 published
Thx for Contrib.
