### ISSUE TITLE
Incompatibility with NetTopologySuite

### ISSUE THREAD

**Issue by RoryMcCrossan** [borisdj/EFCore.BulkExtensions#337]
I'm trying to bulk insert a `List<>` of entities in to MS SQL Server which contain a `NetTopologySuite.Geometries.Point` property. 

When I call `BulkInsert()` providing this list as an argument I receive a `AggregateException`:

>System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (The given value of type Point from the data source cannot be converted to type udt of the specified target column.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Automate.Importer.Program.Main(String[] args) in D:\Project\Program.cs:line 20
>This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:

>InvalidOperationException: The given value of type Point from the data source cannot be converted to type udt of the specified target column.

Inner Exception 2:

>ArgumentException: Specified type is not registered on the target server. NetTopologySuite.Geometries.Point, NetTopologySuite, Version=2.0.0.0, Culture=neutral, PublicKeyToken=f580a05016ebada1.

Am I missing a configuration option, or is this currently unsupported? If the latter, do you have any plans to support it?

**Comment by ntziolis** [comment]
Same issue, would be nice to call out if this is not supported. Also it be interesting to know if this is a limitation of this lib or sql bulk copy.

**Comment by borisdj** [comment]
Duplicate
https://github.com/borisdj/EFCore.BulkExtensions/issues/88
