### ISSUE TITLE
Unable to Delete custom records in BulkInsertOrUpdateOrDeleteAsync

### ISSUE THREAD

**Issue by F0b0s** [borisdj/EFCore.BulkExtensions#338]
Hello, i use BulkInsertOrUpdateOrDeleteAsync method for merge detached graph of objects. BulkInsertOrUpdateOrDeleteAsync compiles into a MERGE statement like this:
```
MERGE [dbo].[Lots] WITH (HOLDLOCK) AS T
USING [dbo].[LotsTemp9f67e449] AS S ON T.[Id] = S.[Id]
WHEN NOT MATCHED BY TARGET THEN INSERT ([Id], [AuctionId], [EndDate], [IsSpecificationRequired], [SortOrder]) VALUES (S.[Id], S.[AuctionId], S.[EndDate], S.[IsSpecificationRequired], S.[SortOrder]) 
WHEN MATCHED THEN UPDATE SET T.[Id] = S.[Id], T.[AuctionId] = S.[AuctionId], T.[EndDate] = S.[EndDate], T.[IsSpecificationRequired] = S.[IsSpecificationRequired], T.[SortOrder] = S.[SortOrder] 
WHEN NOT MATCHED BY SOURCE THEN DELETE;
```
My table Lots has lots from multiple auctions. So when i update lots for one auction, i want to delete lots only for that auction, the query instead has `WHEN NOT MATCHED BY SOURCE THEN DELETE;` it deletes all lots from all auctions that not matched by `T.[Id] = S.[Id]`. I need Merge clause like `WHEN NOT MATCHED BY SOURCE AND T.[AuctionId] = 1234 THEN DELETE;` 
Or maybe merge a subset of target table as it described here https://dba.stackexchange.com/questions/30633/merge-a-subset-of-the-target-table

Example of problem:

```
CREATE TABLE #TestLots(Id int, Name nvarchar(max), AuctionId int)
insert into #TestLots values(1, N'Test1', 1), (2, N'Test2', 1), (3, N'Test', 1), (4, N'Test2', 2)
CREATE TABLE #MergeLots(Id int, Name nvarchar(max), AuctionId int)
insert into #MergeLots values (4, N'Test2Updated', 2), (5, N'New lot', 2)

select * from #TestLots
select * from #MergeLots

MERGE #TestLots WITH (HOLDLOCK) AS T
USING #MergeLots AS S ON T.[Id] = S.[Id]  
WHEN NOT MATCHED BY TARGET THEN INSERT ([Id], [AuctionId], [Name]) VALUES (S.[Id], S.[AuctionId], S.[Name]) 
WHEN MATCHED THEN UPDATE SET T.[Id] = S.[Id], T.[AuctionId] = S.[AuctionId], T.[Name] = S.[Name]
WHEN NOT MATCHED BY SOURCE THEN DELETE;
```
Merge statement the same as it in BulkInsertOrUpdateOrDeleteAsync, i expect that Lots from auction with Id=1 will be untouched after merge . In fact they are deleted.

EFCore.BulkExtensions 3.1.1
.NET Core 3.1
MS SQL Server Microsoft SQL Server 2017

**Comment by timvandesteeg** [comment]
Also looking for exactly this feature, but I don't think it's implemented in this library?
It's like the ColumnSynchronizeDeleteKeySubsetExpression option of Entity Framework Extensions (see: https://entityframework-extensions.net/column-synchronize-delete-key-subset-expression).

**Comment by borisdj** [comment]
There is no option for conditional 'OrDelete'.
You could do this in 2 steps, first do BulkInsertOrUpdate, then BulkRead from which filter ones that should be deleted and with that list call BulkDelete.
