### ISSUE TITLE
BulkInsert with non-abstract-base TPH classes doesn't set derived class properties

### ISSUE THREAD

**Issue by ccruden-shookiot** [borisdj/EFCore.BulkExtensions#339]
Given a class hierarchy like
`class Base {`
`  public string Name {get;set;}`
`  public string Discriminator {get;set;}`
`}`
`class Derived : Base {`
`  public string Value {get;set;}`
`}`

and a DbContext like:

`class MyContext : DbContext {`
`  public DbSet<Base> Bases {get;set;}`
`  public DbSet<Derived> Deriveds {get;set;}`
`  protected override void OnModelCreating(ModelBuilder modelBuilder) {`
`    modelBuilder.Entity<Base>().HasDiscriminator<string>("Discriminator");`
`  }`
`}`

and a call to something like:
`// stuff contains a combination of Base and Deriveds`
`void AddThings(IList<Base> stuff) {`
`  Db.Bases.AddRange(stuff);`
`  Db.BulkInsert(stuff);`
`}`

The BulkInsert call does not result in the Value field being set in the database for Derived entries, even though the Discriminator field correctly identifies them as Derived and not Base. In order for this to work, it seems like Base must be an abstract class. However, if I replace Db.BulkInsert(stuff) with a call to Db.SaveChanges(), the entries are all inserted correctly.

**Comment by ccruden-shookiot** [comment]
As a side note, when I change the base class to be abstract, performance of BulkInsert goes from considerably faster than SaveChanges to somewhat slower.

**Comment by borisdj** [comment]
Can you make a Test where this would be reproducible.

**Comment by vladop** [comment]
@ccruden-shookiot Did you find solution. I am also experiencing problem where some of my fields are not set in TBH scenario:

  ```
foreach (var entity in eCUIdentificationReports)
            {
                foreach (var subEntity in entity.DIDDataObjectValues)
                {
                    subEntity.ECUIdentificationReportId = entity.Id;
                }
                dIDDataObjectValues.AddRange(entity.DIDDataObjectValues);
            }
  await dbContext.BulkInsertAsync(dIDDataObjectValues, bulkConfig);
```
Here ECUIdentificationReportId field is not set

**Comment by borisdj** [comment]
Base class should be abstract, and I can't reproduce slow performance.
There is Test _InsertWithDiscriminatorShadow_ which you could alter according to your scenario.
If you manage to reproduce the problem there open the new issue.
