### ISSUE TITLE
Feature: Include source and symbols in nugets

### ISSUE THREAD

**Issue by generik0** [borisdj/EFCore.BulkExtensions#344]
Hi..
Great package. Thanks.!!

Can you please
<IncludeSource>True</IncludeSource>
<IncludeSymbols>True</IncludeSymbols>

In the package? sometimes get deep issues. e.g. now facing:
"Input string was not in a correct format." which doesn't give meaning. Need debugging..
Easiest I symbols / source exported with the package..

**Comment by borisdj** [comment]
Nuget 3.1.2 published
