### ISSUE TITLE
2.x, Inconsistent transaction behavior

### ISSUE THREAD

**Issue by Prinsn** [borisdj/EFCore.BulkExtensions#345]
This is on 2.x latest as of posting this

using 
```
            using (var d = dbContext.Database.GetDbConnection())
            {
                d.Open();
                using (var t = d.BeginTransaction())
                {
                    foreach (var type in deleting.Values)
                    {
                        //We're manually removing these so detach them.
                        var deletingType = deleting[type];

                        var deletingentities = deletingType.Select(e => e.Entity);

                        //May need a bulk config
                        dbContext.BulkDelete(deletingentities.ToList());

                        //remove deleted enti
                        deletingType.ToList().ForEach(g => g.State = EntityState.Detached);
                    }

                    dbContext.Database.UseTransaction(t);
                    dbContext.SaveChanges();
                    t.Commit();
                }
            }
```

the `dbContext.BulkDelete(deletingentities.ToList());` intermittently fails with

```
System.InvalidOperationException: 'ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.'
```
Which, per documentation, appears to only be for SqlLite transactions, so it appears to inconsistently detect if it's a Sql or SqlLite DB.

I had it happen, I kept changing code to try to fix it, i randomly stopped, and then I tried to figure out how to get the external transaction to continue without an issue, and in the midst of debugging runs to fix that, the error came back with no changes to the using scopes.

**Comment by Numpsy** [comment]
Have you tried using the connection/transaction properties in BulkConfig when using Sqlite?

example from the readme:

```c#
using (var connection = (SqliteConnection)context.Database.GetDbConnection())
{
    connection.Open();
    using (var transaction = connection.BeginTransaction())
    {
        var bulkConfig = new BulkConfig() { SqliteConnection = connection, SqliteTransaction = transaction };
        context.BulkInsert(entities, bulkConfig);
        context.BulkInsert(subEntities, bulkConfig);
        transaction.Commit();
    }
}
```

**Comment by Prinsn** [comment]
To clarify, are you suggesting acting as if I'm using SqlLite instead of
Sql?

**Comment by borisdj** [comment]
@Prinsn could you make a Test where this would be reproducible.

**Comment by Prinsn** [comment]
Itd be difficult.  It's intermittent as is,  and in propriety code, so it'd
require a rather larger effort to produce a similar project just to have
the confidence that I didn't remove the property(s) that were the culprit.

It's running in an azure function, on a DB with authentication that's being
bypassed and auditing in EFC and in the DB separately, the schema contains
a TPH table, there's a number of model builder specified things, the
deleting entity set is determined by diffing a document import set against
prior imported data,  there are cascade deletes in the DB.

I don't mean to be difficult in any way, but I don't think it's feasible to
do anything short of trying a minimal project and just hoping it happens at
least once and running it manually (because who knows that it's not a build
step issue)
