### ISSUE TITLE
Operations on empty Lists.

### ISSUE THREAD

**Issue by aodpi** [borisdj/EFCore.BulkExtensions#347]
https://github.com/borisdj/EFCore.BulkExtensions/blob/2db2f909925d456ba49214f7bbc1e07ca04426c5/EFCore.BulkExtensions/SqlBulkOperation.cs#L46

If the entities list is empty is it still relevant to do all that processing ? Maybe just return and that's it.

**Comment by borisdj** [comment]
It's not relevant but when it's empty there is only metadata reading.
Also you can check if List is empty before calling Bulk methods.

**Comment by aodpi** [comment]
Ok then. Closing.
