### ISSUE TITLE
[SQLite] always insert values for auto generated identity column

### ISSUE THREAD

**Issue by knalinne** [borisdj/EFCore.BulkExtensions#349]
Hello, 

I've an issue with the identity column: BulkInsert always try to insert a 0 for my ids, event with a key configured correctly.

https://github.com/borisdj/EFCore.BulkExtensions/blob/2db2f909925d456ba49214f7bbc1e07ca04426c5/EFCore.BulkExtensions/SqlQueryBuilderSqlite.cs#L19-L23

I think the problem come from line 21.
The `tableInfo.IdentityColumnName` contains the property name as defined in the model (in my case BoundingBoxId)

![Screenshot 2020-06-15 at 15 15 33](https://user-images.githubusercontent.com/5163782/84663664-c3ac9000-af1d-11ea-9a2a-d60691a24233.png)

In the column list, we have the columns name, as defined in database.
![Screenshot 2020-06-15 at 15 16 06](https://user-images.githubusercontent.com/5163782/84663834-fbb3d300-af1d-11ea-9613-e5ad12129895.png)
As my database is in snake_case, the filter do not find the "BoundingBoxId" column from the list

I think we can fix this by filter on `tableInfo.PropertyColumnNamesDict[tableInfo.IdentityColumnName];` instead, as the dictionary contains the mapping between model properties name and database columns name.

Thanks for your help !

**Comment by borisdj** [comment]
Nuget 3.1.2 published
