### ISSUE TITLE
Facing issue on Bulk Update of a table(has table splits)

### ISSUE THREAD

**Issue by Bhargavi88** [borisdj/EFCore.BulkExtensions#352]
I have an entity Order which has a table split as in (https://docs.microsoft.com/en-us/ef/core/modeling/table-splitting).  

public class Order
{
    public int Id { get; set; }
    public OrderStatus? Status { get; set; }
    public DetailedOrder DetailedOrder { get; set; }
}

public class DetailedOrder
{
    public int Id { get; set; }
    public OrderStatus? Status { get; set; }
    public string BillingAddress { get; set; }
    public string ShippingAddress { get; set; }
    public byte[] Version { get; set; }
}

modelBuilder.Entity<DetailedOrder>(dob =>
{
    dob.ToTable("Orders");
    dob.Property(o => o.Status).HasColumnName("Status");
});

modelBuilder.Entity<Order>(ob =>
{
    ob.ToTable("Orders");
    ob.Property(o => o.Status).HasColumnName("Status");
    ob.HasOne(o => o.DetailedOrder).WithOne()
        .HasForeignKey<DetailedOrder>(o => o.Id);
});

When I try to perform BulkUpdate as  _context.BulkUpdate(orders), I am seeing issue "The specified schema name "dbo" either does not exist or you do not have permission to use it.
Microsoft.Data.SqlClient.SqlException (0x80131904): The specified schema name "dbo" either does not exist or you do not have permission to use it".

Does this support table splits or Is there any way to configure for splits?

**Comment by borisdj** [comment]
Table splits are not currently supported.

**Comment by borisdj** [comment]
This can be achieved with 2 calls to BulkUpdate, configuring DestinatilName and PropsToExclude.
Similar to Owned type in separate tables: https://github.com/borisdj/EFCore.BulkExtensions/issues/114#issuecomment-803462928
