### ISSUE TITLE
Update only when certain conditions are met

### ISSUE THREAD

**Issue by dafunkphenomenon** [borisdj/EFCore.BulkExtensions#353]
Hi
I have list of objects that are generated by another system:

```
class Client {
    public string ClientId { get; set; }
    public int Version { get; set; }
    etc....
}
```

Currently I'm simply passing this list to my DB Context which updates or inserts based on the ClientID

```
List<Client> clientList = blahblah;
dbContext.BulkInsertOrUpdate(clientList);
```

What I want to be able to do is insert if the record doesn't exist as it does now, but only update an existing record if the incoming Version is higher than the number in the corresponding database record. If it's the same, or lower I want to ignore it.

How would I do this? Thanks

**Comment by borisdj** [comment]
You could use BulkRead to load existing one and separate List for update.
