### ISSUE TITLE
SQL Sever implementations use the existing transaction while Sqlite does not

### ISSUE THREAD

**Issue by gandhis1** [borisdj/EFCore.BulkExtensions#356]
@borisdj 

In all of the SQL Server operations, the ambient transaction will be used. For example:

https://github.com/borisdj/EFCore.BulkExtensions/blob/1d24af75300eb053a19cf4c2487172d94dc7cf09/EFCore.BulkExtensions/SqlBulkOperation.cs#L60-L66

However in the Sqlite branches, if a `SqliteTransaction` is not specified, a new one is created:

https://github.com/borisdj/EFCore.BulkExtensions/blob/1d24af75300eb053a19cf4c2487172d94dc7cf09/EFCore.BulkExtensions/SqlBulkOperation.cs#L112-L119

1) Why doesn't it use the existing transaction? Making use of the extension method, this would be the following line of code:

`var transaction = (SqliteTransaction)dbContext.Database.CurrentTransaction.GetUnderlyingTransaction()`

2) If, per 1, it can sniff out the ambient `SqliteTransaction`, under what circumstances are the config parameters needed?

3) Sqlite notoriously cannot handle nested transactions, so if you are mocking a SQL Server connection with a Sqlite in-memory database, which I believe will be a very common application, and you wrap your bulk operations in a DbContext transaction, then you will hit this issue and will have to make your code aware of the Db provider. Which totally undermines the whole point of entity framework, in that the db context is dependency injected so your code does not need to be intelligent / coupled.

Generally speaking, I'm trying to understand why the special Sqlite configuration parameters are needed. I would ideally like to be able to switch seamlessly between SQL Server and Sqlite without any code changes needed.

**Comment by borisdj** [comment]
1. Initially I wasn't able to make it work properly with internal transaction, probably did wrong cast or something like that.
So it was exposed via config.
I see you have manage to integrate it successfully, so I have merged your PullRequest.
Will see now to clean the code and remove it from BulkConfig.
Thx for contrib.
