### ISSUE TITLE
Can it be modified to be able to select which columns to update

### ISSUE THREAD

**Issue by nafberger** [borisdj/EFCore.BulkExtensions#36]
Hi Boris, 

Can the code be modified to be able to select which columns to update? This would be a huge help for us, willing to pay, please contact me by email. thanks

**Comment by nafberger** [comment]
Hi Borris. Sleeping? why no answer, please reply, Naftaly, 40-year-old, 185 pounds, Monroe, NY, USA in trumpland

**Comment by borisdj** [comment]
I have been on vacation.
You can contact me on Email that can be found in contact info of LinkedIn (link for it in Github profile)

**Comment by borisdj** [comment]
Duplicate:
[issue25(It would be nice to specify columns)](https://github.com/borisdj/EFCore.BulkExtensions/issues/25)

**Comment by nafberger** [comment]
Thanks for responding, glad you are still with us. tried to find your email
but can't find, I am not too familiar with linked-in can you please post
your email here, I promise not to abuse it. thanks, where was the vacation,
hope somewhere warm, its brutally cold now in Bosnia, not so

**Comment by borisdj** [comment]
I have send you a message to your gmail, did you got it ?

**Comment by nafberger** [comment]
Yes, I am waiting on my boss for a decision, I will be in touch with you
soon, big thanks for replying
