### ISSUE TITLE
BulkRead example failure

### ISSUE THREAD

**Issue by brentbordelon** [borisdj/EFCore.BulkExtensions#360]
BulkRead example is flawed and confusing.
second-to-last line on BulkRead example cannot work.

1. Item.Name can't be used (Item is a type)
2. Missing a closing }

I am trying to use BulkRead, but can't figure out how to use it.  Also, the call to BulkRead itself is bad (BulkRead should be called on dbcontext, not dbset)

**Comment by borisdj** [comment]
1. It can
2. '}' Added
Also ReadMe Example corrected so that BulkRead is called on context.
PS Working example could be found in Tests as well.
