### ISSUE TITLE
Support bulk operations extension methods on DbSet instead of just DbContext

### ISSUE THREAD

**Issue by gandhis1** [borisdj/EFCore.BulkExtensions#361]
The standard EF Core `AddRange()` and `RemoveRange()` methods are available on either the `DbSet` or `DbContext` classes. Is there a compelling reason to not offer both interfaces for bulk operations as well?

**Comment by borisdj** [comment]
Not particularly.
Methods naming are Insert, Read, Update, Delete so CRUD convention, except Create->Insert.

**Comment by gandhis1** [comment]
Sorry, I don't really mean the naming of the methods - I mean that because `BulkInsert()` is available on `DbContext` it should be available on `DbSet` as well. This makes the bulk operations consistent with the standard EF operations which can be invoked on either object.

So I should be able to do:

```
dbContext.BulkInsert(entities);
dbContext.BulkDelete(entities);
```

As well as:

```
dbContext.SomeTable.BulkInsert(entities);
dbContext.SomeTable.BulkDelete(entities);
```

Would you accept a PR to add this interface?

**Comment by gandhis1** [comment]
Any further comment? Here's an example from EF core itself, on `AddRange()`:

https://github.com/dotnet/efcore/blob/ec3df8fd7e4ea4ebeebfa747619cef37b23ab2c6/src/EFCore/Internal/InternalDbSet.cs#L289-L290

https://github.com/dotnet/efcore/blob/ec3df8fd7e4ea4ebeebfa747619cef37b23ab2c6/src/EFCore/DbContext.cs#L1497-L1502

**Comment by cwilby** [comment]
Looking into this.  I'd also like to be able to access `Bulk*` methods from a DbSet, rather than via DbContext.

This is because we split our DataContext collections across repositories, where each Repository class has a DbSet that it performs operations (including bulk operations) on.

**Comment by cwilby** [comment]
Doesn't look promising.  The static methods exposed by `DbContextBulkExtensions.cs` use a `DbContextBulkTransaction` which depends on DbContext to function.

I had a go at adding a new `DbSetBulkExtensions` class, you'd have to just pass in the context anyway making it redundant/pointless to implement.

**Comment by gandhis1** [comment]
Does anything here work? https://stackoverflow.com/a/50864373

**Comment by borisdj** [comment]
Library already has it's method for getting DbContext.
So implementation could be like this (example for one method):
```C#
public static class IQueryableBulkExtensions
{
    public static void BulkInsert<T>(this IQueryable query, IList<T> entities, BulkConfig bulkConfig = null, Action<decimal> progress = null, Type type = null) where T : class
    {
        var context = BatchUtil.GetDbContext(query);
        context.BulkInsert(entities, bulkConfig, progress, type);
    }
    
    / ...
}
```
