### ISSUE TITLE
Exception when using null-coalescing operator in BatchUpdate(/BatchUpdateAsync)  (Incorrect syntax near ...)

### ISSUE THREAD

**Issue by metallserge** [borisdj/EFCore.BulkExtensions#363]
I faced with exception in BatchUpdate(/BatchUpdateAsync)
EFCore.BulkExtensions 3.1.5
netcoreapp3.1

Executed linq code:
```
using (var context = new Context())
{
    string newName = null;

    context.Examples
        .Where(x => x.Id == 1)
        .BatchUpdate(x => new Example
        {
            Name = newName ?? x.Name
        });
}

```
Exception: `Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'e'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)`

Note null-coalescing operator: newName ?? x.Name

With SQL profiler I found that executed query is: 
```
exec sp_executesql N'UPDATE e SET  [e].[Name] = @param_0 [e].[Name] 
FROM [Example] AS [e]
WHERE [e].[Id] = 1',N'@param_0 nvarchar(4000)',@param_0=NULL
```

Note: @param_0 [e].[Name] <- there is no ISNULL or CASE WHEN ... 

If I update sentence to `Name = newName != null ? newName : x.Name`
code will give me exception: `Unhandled exception. System.InvalidOperationException: variable 'x' of type 'ConsoleApp1.Example' referenced from scope '', but it is not defined`

**Comment by borisdj** [comment]
Null-coalescing is not supported.
You could refactor the code in the following way to achieve this:
```C#
using (var context = new Context())
{
  string newName = null;
  var query = context.Examples.Where(x => x.Id == 1);
  if(newName == null)
  {
    query.BatchUpdate(x => new Example { Name = x.Name });
  }
  else
  {
    query.BatchUpdate(x => new Example { Name = newName });
  }
}
```
