### ISSUE TITLE
Error - Could not load file or assembly 'EFCore.BulkExtensions

### ISSUE THREAD

**Issue by edspicer** [borisdj/EFCore.BulkExtensions#364]
Hi people,

I installed this extensions in my project (my projet have CQRS with EFCore - 2.2, I installed in my Domain Project), when I publish (deploy) in release, in execution I recieve this message : "Could not load file or assembly 'EFCore.BulkExtensions, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null'. O sistema não pode encontrar o arquivo especificado." Have ayone ideia how I can resolve this issue? Thanks.

**Comment by borisdj** [comment]
Version after 3.0.0, including the latest one 3.1.6 are using EF Core 3.1.
Last version with EF Core 2.2 was 2.6.4, as stated in the ReadMe.
But I suggest updating project to latest versions.

**Comment by edspicer** [comment]
@borisdj 
I updated all versions for latest, including .netcore versions, and I forget .deps file, when contais references to dlls. extensions.
after including these files, the problem was resolved.
Thank you. :)

**Comment by edspicer** [comment]
P.S the Bulk Extensions are very fast!! :)

**Comment by borisdj** [comment]
Glad you sorted it out. 👍
