### ISSUE TITLE
BulkInsertOrUpdateAsync Inserted/Updated date column

### ISSUE THREAD

**Issue by mehmetaltuntas** [borisdj/EFCore.BulkExtensions#366]
Hi,

This is ultimately questions of finding out whether a feature is available or not.
I have recently used `BulkInsertOrUpdateAsync` and could not be able to insert DateAdded or update DateUpdated column in the table. These fields were not exposed in the Entity class and the assumption that BulkInsertOrUpdateAsync will handle it. Any chance to have those field handled/populated while the execution occurs? 

Another question is that does BulkInsertOrUpdateAsync handle many-to-many relationships? 

Thanks

**Comment by borisdj** [comment]
To manipulate the columns you need to define them in Entity.
Onyl exception are [ComputedColumn](https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties?tabs=data-annotations#computed-columns)

As for Bulk ops to multiple tables you need to do it one by one, so set lists and then Bulk each table.
Also it should be done in a transaction.
