### ISSUE TITLE
Library does not work on Xamari.iOS

### ISSUE THREAD

**Issue by MartinLeist** [borisdj/EFCore.BulkExtensions#367]
The option with UseOnlyDataTable does not work on SQLite.

On Xamarin.iOS one usually uses SQLite. The SQLite path uses FastMember no matter what. The way without fastmember is only included on SQL Server. So the cominbation Xamarin.iOS and SQLite does not work.

_Originally posted by @MartinLeist in https://github.com/borisdj/EFCore.BulkExtensions/issues/320#issuecomment-669924588_

**Comment by borisdj** [comment]
SQLite does not use ObjectReaderEx at all, for which DataTable was alternative.
However it does use TypeAccessor from FastMember.
But it could be done without it, using plane Reflection.

**Comment by MartinLeist** [comment]
My solution was removing the FastMember reference completely and changing the TypeAccessor to the type.
`var typeAccessor = typeof(T); //TypeAccessor.Create(type, true);`

`value = typeAccessor.GetProperty(propertyColumn.Key).GetValue(entity) ?? null;`
`//value = typeAccessor[entity, propertyColumn.Key] ?? DBNull.Value;`

That way I was able to use it in my Xamarin.Forms project. I suppose removing the reference would not have been necessary, but it was the fastest way to find all usages.

**Comment by borisdj** [comment]
That was the idea, I see you have already implemented it.
I have been considering to remove FastMember completely, since it is not necessary, and there have been more then one issue with it. Will see to clean it as soon as I find the time.

**Comment by borisdj** [comment]
FastMember dependency is now removed.
Version 3.2.0+
