### ISSUE TITLE
Inclusion of Timestamp column in bulk operations

### ISSUE THREAD

**Issue by kyletinsley** [borisdj/EFCore.BulkExtensions#371]
How can we intentionally include timestamp columns in bulk operations?

We need to one-way synchronize two databases and are dependent on the timestamp/rowversion column for efficiently determining what's changed.  These tables have hundreds of millions of records and we need to only process records in the source database that are newer than the target database (via timestamp compare).  In order to perform this comparison, we have to preserve timestamps in the source database and into them into target database.

SELECT * FROM [SourceTable] WHERE [Timestamp] > SELECT MAX(Timestamp) FROM [TargetTable]

**Comment by borisdj** [comment]
Not sure how to achieve this.

**Comment by borisdj** [comment]
There are now separated config for
`PropertiesToIncludeOnUpdate`
`PropertiesToExcludeOnUpdate`
Maybe they can be used for this.
More info in the README.
