### ISSUE TITLE
[Feature Request] Possibility to give table name as parameter/config

### ISSUE THREAD

**Issue by SpaceOgre** [borisdj/EFCore.BulkExtensions#372]
Hi,

I need to write a pretty advanced merge operation so I do that manually but I would still like to use this extension for the Bulk insert that the merge need. So I would like to be able to provide the BulkInsert operation my temporary table name instead of directly inserting to the Entity table. Eg:

`new BulkConfig { DestinationTable = "dbo.MyTempTable" }`
or
`context.BulkInsert("dbo.MyTempTable", entities)`

Regards Daniel

**Comment by SpaceOgre** [comment]
Oh and if you think this would be a good fit for this extension then I would be happy to try and add it my self and do a Pull-Request with it.

**Comment by borisdj** [comment]
You can try to implement it and do PullRequest

**Comment by borisdj** [comment]
In Config there is now `CustomDestinationTableName` that can be set with 'TableName' only or with 'Schema.TableName'.<br>
