### ISSUE TITLE
[Feature Request] Possiblity to add extra checks to WHEN MATCHED in merge

### ISSUE THREAD

**Issue by SpaceOgre** [borisdj/EFCore.BulkExtensions#373]
Hi,

This is the second part I need to not have to write all the code myself ;)

I need to write a merge that looks something like this:

```sql
MERGE MyTable WITH (HOLDLOCK) AS TARGET
USING TempTable AS SOURCE 
ON (TARGET.[Id] = SOURCE.[Id]) 
WHEN MATCHED AND SOURCE.Time > TARGET.Time 
THEN UPDATE SET TARGET.Value= SOURCE.Value, TARGET.Time = SOURCE.Time
WHEN NOT MATCHED BY TARGET 
THEN INSERT(Id, Value, Time) VALUES (SOURCE.Id, SOURCE.Value, SOURCE.Time);
```
Meaning I would need to be able to specify the `AND SOURCE.Time > TARGET.Time` some how for the BulkInsertOrUpdateAsync method.

One way could be to add a new list with parameter and operation:
`new BulkConfig{ UpdateWhen = new List<WhenOperation> { new WhenOperation<Entity>(x => x.Time, OperationType.SourceGreaterThen) } }`

Regards Daniel

**Comment by borisdj** [comment]
This seems too custom, and out of this library scope.
