### ISSUE TITLE
SQL Server bulk operation create a lot of temp tables

### ISSUE THREAD

**Issue by SamazoOo** [borisdj/EFCore.BulkExtensions#374]
Hi all, I'm using efcore.bulkextensions with SQL Server and it's creating a lot of temp tables that it isn't dropping. ¿is it necessary? ¿How we can avoid to create temp tables? ¿should it drop temp tables automatically?
<img width="486" alt="image" src="https://user-images.githubusercontent.com/17595240/91436776-11703d80-e869-11ea-88d2-c7f833c262c7.png">

**Comment by borisdj** [comment]
IT should drop automatically, you might be having some exception that occurs before dropping.
Try setting UseTempDB in BulkConfig, but that you also need to wrap Bulk operation in explicit transaction.

**Comment by MARKUSER** [comment]
@borisdj 
I am also having the same issue with temp tables and they are not deleting automatically. I am using BulkRead ,BulkUpdate, BulkInsert in the same thread and invoking this thread up until my job is completed. 
Let say I am fetching 3000 records as batch through BulkRead and process them and Inserting the results through BulkInsert and updating the statuses through BulkUpdate. Its all one thread for me and it is a unitofwork if i wrap all this in one transaction then  i was worried transaction may time out or not work as expected. Please let me know your thoughts.
Any other way to call some BulkExtension method and delete temp table created for that operation in try catch block ?

**Comment by borisdj** [comment]
For **UseTempDB** explicit transaction is required.
Try it first and see if manages to finish in time.
