### ISSUE TITLE
Bulk insert performance issue

### ISSUE THREAD

**Issue by vpusarla-incomm** [borisdj/EFCore.BulkExtensions#379]
I have inserted 1 million records using Bulk insert and it is taking 2 minutes 36 seconds.
you performance stats say it should take around 18 seconds.
I am using .net core console app and Sql server. 
Please help me improving performance

**Comment by borisdj** [comment]
Could you make the Test for it.
Also run the library BulkTest on your computer, leave only BulkInsert and comment the other Bulks, then check the time it takes.
