### ISSUE TITLE
BulkInsertOrUpdateAsync failure : Microsoft.Data.SqlClient.SqlException 'Syntaxe incorrecte vers ')'.'

### ISSUE THREAD

**Issue by clementhervy** [borisdj/EFCore.BulkExtensions#385]
Using 3.1.5 I get the following exception when trying to insert or update a list of very simple items made of two `int` properties, and another `int` and a nullable `DateTime` that are both ignored:
`'Microsoft.Data.SqlClient.SqlException' in (...).dll ("Syntaxe incorrecte vers ')'.")`

Translated, the French part of the message means "Incorrect syntax near '('" -- I know, it's pretty self-explanatory :)

Here is the code calling BulkExtensions (with member names amended):
```
public async Task InsertItemsAsync(IEnumerable<Item> items) =>
            await this.BulkInsertOrUpdateAsync(items.ToList(),
                        new BulkConfig
                        {
                            BatchSize = 10000,
                            EnableStreaming = true,
                            PropertiesToExclude = new List<string> { nameof(Item.RelatedItemId), nameof(Item.SentDate) },
                            SqlBulkCopyOptions = Microsoft.Data.SqlClient.SqlBulkCopyOptions.UseInternalTransaction
                        });
```

And the model declaration:
`modelBuilder.Entity<Item>().ToTable("ItemTable", "SchemaName").HasKey(_ => _.ItemId);`

I checked the list of items and there are no incorrect values for the properties being inserted.

**Comment by borisdj** [comment]
Could you please make the Test where this would be reproducible.

**Comment by clementhervy** [comment]
Hi, thank you for your answer. I will try and update a quick something to show you, but I won't be able to until the end of the week. Meanwhile, is there a way to see the BulkExtensions generated SQL? It could give us pointers on how to solve the problem. I tried [default EntityFramework Core logging](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging?tabs=v3), but alas, no luck.

**Comment by borisdj** [comment]
You could load the source of library as Project and reference that instead of NuGet, then put break points in SqlQueryBuilder, and run it in Debug mode.
