### ISSUE TITLE
Updating entities without their primary key

### ISSUE THREAD

**Issue by AmirhosseinSA** [borisdj/EFCore.BulkExtensions#386]
Is there a way to bulk-update a list of entities without having their primary keys? My entity has one primary key and one unique index on another property. I want to update a specific property in all entities in a given list. I do not want to have to do a bulk-read first in order to obtain entities that have the primary key.

Thanks in advance.

**Comment by AmirhosseinSA** [comment]
I solved it:

            var bulkConfig = new BulkConfig
            {
                UpdateByProperties = new List<string> { nameof(UNIQUE_PROPERTY) },

                PropertiesToInclude = new List<string> { nameof(PROPERTY_TO_BE_UPDATED) }
            };

_dbContext.BulkUpdate(entities, bulkConfig);

**Comment by borisdj** [comment]
👍
