### ISSUE TITLE
Not able to use BulkRead method

### ISSUE THREAD

**Issue by dev07git** [borisdj/EFCore.BulkExtensions#388]
I'm using EFCore.BulkExtensions[3.1.6] in .Net Core 3.1 Web API to perform bulk operations. Bulk insert and update are working fine but I'm not able to use BulkRead method to get the bulk data.

I refer this link https://github.com/borisdj/EFCore.BulkExtensions#read-example and tried it but I'm not getting data. Maybe I didn't understand the example.

Here is the code which I've tried:

IList<VehicleSubModel> submodels = new List<VehicleSubModel>(); // VehicleSubModel is the domain Entity

        var result = submodels.Select(s => new VehicleSubModel() { Id = s.Id, Name = s.Name }).ToList();
        var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(VehicleSubModel.Id), nameof(VehicleSubModel.Name) } };

        await Task.Run(() => Context.BulkRead(result, bulkConfig));

I want to get Id and Name of all VehicleSubModel but it's not returning any record. Could anyone please explain how we can use the BulkRead method of EFCore.BulkExtensions. I spend several hours to get it done, search many links but not getting its solution. Can anyone please help?

**Comment by borisdj** [comment]
BulkRead is used to read certain rows from DbTable based on matching with some unique criteria.
Say you have table User with Sequence number and you want all those which Sequence is in given List.
So we have entity
```C#
public class User
{
  public int Id { get; set; }
  public int Sequence { get; set; }
  public string Name { get; set; }
}
```
then
```C#
var sequenceList = new List<int>() { 123, 563, 654, 1236 , 4326, 7565 };
var users = sequenceList.Select(a => new User { Sequence = a });
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(User.Sequence) } };
context.BulkRead(users, bulkConfig); // properties, in this case Id and Name, are loaded/read from Db based on Sequence
```

**Comment by dev07git** [comment]
Okay, that means in order to get all users data, first I've to get their database sequence values. And using the sequence-List only I can get all users detail.

But how about this, if we don't have any matching criteria, and want to get all users details? Can't it possible?


Actually, in my case I'm having one million data in the subModel table. As per this method if I need to get one million subModels (Id, Name) first I've to pull all one million Ids from the database then only I can get other details.  This is what I understand, Am I correct?

**Comment by borisdj** [comment]
IF you need all data from the table then there is no need for BulkRead, just use plain Select.
BulkRead is for big subset by certain criteria.

**Comment by dev07git** [comment]
Okay, thanks for the clarification.

One more doubt, if I want to get all Models and submodel detail with some particular where condition, can it be possible ?
Below is my linq query, Can I convert it using BulkRead?
 List<Contracts.Model> result1 = await Task.Run(() => Context.Model.Where(x => x.Maker.MasterId==null)
                .Select(s => new Contracts.Model
                {
                    ModelId = s.Id,
                    Model = s.Model,
                    MakerName = s.Maker.MakerName,
                    MakerId = s.Maker.Id,
                    Body = s.Body,
                    SubModels = s.SubModels.Select(sm => new Contracts.SubModel()
                    {
                        Id = sm.Id,
                        SubModel = sm.SubModel,
                    }).ToList()

                }).ThenBy(o => o.MakerName).ThenBy(o => o.Model).ToList());

**Comment by borisdj** [comment]
Bulk read can read only one table, not submodels.
But for this example you don't need BulkRead at all.
BulkRead is only useful for WhereIN with Contains from a List.

**Comment by nikriaz** [comment]
> ```cs
> context.BulkRead(users, bulkConfig);
> ```

I'm trying to repeat this example and getting compiler Error CS0411 in `context.BulkRead(users, bulkConfig);`
The type arguments for method 'DbContext.BulkExtensions.BulkRead' cannot be inferred from the usage.

**Comment by ManiRV909** [comment]
Hi, I am getting error "CREATE TABLE permission denied in database" when reading with BulkRead. Is it that we need to use UseTempDB property ? @borisdj 
![snapshot](https://user-images.githubusercontent.com/89966105/133086163-a89660ff-d659-4d89-819e-73052779cc5d.png)

**Comment by borisdj** [comment]
@ManiRV909 that's correct.

**Comment by ManiRV909** [comment]
> @ManiRV909 that's correct.
So the UseTempDB property should be wrapped in a transaction right ? 
But for reading data do we really need a transaction ?

**Comment by borisdj** [comment]
In this case you do, because without Create permission, _UseTempDB_ is required and for that transaction is necessary.

**Comment by ManiRV909** [comment]
Thank you so much @borisdj
