### ISSUE TITLE
Support for custom ValueConverters (EF Core 2.1)

### ISSUE THREAD

**Issue by SimplerSoftware** [borisdj/EFCore.BulkExtensions#39]
EF Core 2.1 introduces the concept of converters that allow you to convert to/from different data types in the DB.  Do you have plans to incorporate these into the bulk extensions? See [here](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) for more information.

**Comment by borisdj** [comment]
I will look into it.

**Comment by SimplerSoftware** [comment]
Any updates on this?  Wondering if I should take a crack at a PR for this. Thanks!

**Comment by borisdj** [comment]
I have read the concept and figure it can be added.
But plan to do it once EF Core 2.1 is full release, which I expect to be sometimes in June.
There is also issue for [Owned Types](https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities) support so then both features can be implemented.
But if you want this sooner you can try to add it and send a PR.

**Comment by SimplerSoftware** [comment]
@borisdj - FYI - dotnetcore 2.1 was officially released today: [Net Core 2.1](https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/)

**Comment by borisdj** [comment]
Merged and Nuget 2.1.0 published
