### ISSUE TITLE
BulkInsertOrUpdateOrDelete delete all data of Table instead of Primary Key Pair Values

### ISSUE THREAD

**Issue by hintsofttech** [borisdj/EFCore.BulkExtensions#391]
Dear Team,

First of all thanks a lot for such a great library.

Further, we have countered issue with BulkInsertOrUpdateOrDelete command 
which is **deleting entire** non-existing data of the Table instead of **Primary Key Pair Values**...

i.e. 
suppose we have a table of three field primary keys where we can send this command 
and it should check bulk of only **three field primary keys rows**.

and do operation like:
1. if exists =then update
2. if don't exist=then insert
3. if extra in that **Primary Key Pair Valued Rows**=then delete

kindly suggest...

Regards-
Sanjeeb

**Comment by borisdj** [comment]
BulkInsertOrUpdateOrDelete can not be Filtered on subset. It is for entire table.
You can call separately BulkInsertOrUpdate and BulkDelete or BulkRead before BulkDelete if necessary.
