### ISSUE TITLE
BatchUpdate failed for string.Replace update operation

### ISSUE THREAD

**Issue by yeyisxp** [borisdj/EFCore.BulkExtensions#392]
BatchUpdate method is failed for case: 
BatchUpdateAsync(a => new T { Name = a.Name.Replace("OldStr", "NewStr") });

**Comment by borisdj** [comment]
Replace method is not supported in Batch.

**Comment by yeyisxp** [comment]
@borisdj Is it possible  to make use of EF core related functions to implement this kind of expression functions?

**Comment by borisdj** [comment]
Not sure.
Maybe to make a custom parser (add extra parameter), or special method, since required sql is:
`UPDATE myTable SET somelCol = REPLACE(somelCol , 'desc', '.info2')`.`
