### ISSUE TITLE
Exception "Value cannot be null. (Parameter 'method')" - BulkInsertAsync or BulkUpdateAsync

### ISSUE THREAD

**Issue by RossHNPC** [borisdj/EFCore.BulkExtensions#393]
Having updated packages from 3.1.6 to 3.2 I've started getting the following exceptions being thrown.

`Inner exception 
Value cannot be null. (Parameter 'method')

System.Linq.Expressions
________________________________________
Stack trace: 

at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression arg0)
at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
at EFCore.BulkExtensions.FastProperty.InitializeSet()
at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
at NaturalPower.Forecasting.Infrastructure.Data.ForecastingContext.BulkUpdateSamples() in D:\a\1\s\src\Infrastructure\Data\ForecastingContext.cs:line 1386
`

I don't believe we have made any other changes in our code base.

**Comment by borisdj** [comment]
Version 3.2.+ had some significant changes.
Can you write code sample where this exception would be reproducible, or write a test for it.

**Comment by RossHNPC** [comment]
Cool, here's the code that uses the extension methods; there's nothing particularly exciting in it.
The `DbContext` has a `dbSet<Sample>` and `dbSet<Signal>`.

I traced things through with the decompiled code, but couldn't immediately see anything.

We don't use `BulkConfig`, so these will all be default values, perhaps this is the issue...?

        public async Task UpdateAsync(IEnumerable<T> entities)
        {
            var samples = new List<Sample>();

            foreach (var entity in entities)
            {
                this.DbContext.Entry(entity).State = EntityState.Modified;
                samples.AddRange(entity.Signals.SelectMany(s => s.Samples));
            }

            var addedSamples = new List<Sample>();
            var updatedSamples = new List<Sample>();

            // Pre-selecting entities we know that will have changed between database calls
            var modifiedEntityEntries = this.DbContext.ChangeTracker
                .Entries()
                .Where(x => x.State == EntityState.Modified || x.State == EntityState.Added)
                .ToList();

            // Sort out added from updated
            foreach (var sample in samples)
            {
                var internalEntity = modifiedEntityEntries.Find(m => m.Entity == sample);

                if (internalEntity != null)
                {
                    if (internalEntity.State == EntityState.Added)
                    {
                        addedSamples.Add(sample);
                        internalEntity.State = EntityState.Detached;
                    }
                    else if (internalEntity.State == EntityState.Modified)
                    {
                        updatedSamples.Add(sample);
                        internalEntity.State = EntityState.Detached;
                    }
                }
            }

            // Carry out our bulk operations
            await this.DbContext.BulkInsertAsync(addedSamples);
            await this.DbContext.BulkUpdateAsync(updatedSamples);

            await this.DbContext.SaveEntitiesAsync();
        }

**Comment by borisdj** [comment]
You should also write code snippet of these 2 entity classes, and their modelBuilder config if there are some specific settings.
Then add some dummy data with `for` loop into List for test purposes.
Take a look at **EFCoreBulkTest.cs** _OperationsTestAsync_, methods _RunInsertAsync_ and _RunUpdateAsync_.

**Comment by sethsteenken** [comment]
I also received this exception on version 3.2.2. I don't have a code sample handy, but I was able to pinpoint and address the exception after digging through some of the source.

Entities in my projects typically have properties with private or protected sets. It seems this bug occurs on entities with one or properties having a non-public set.

The fix may be as simple as passing true for parameter nonPublic on PropertyInfo GetSetMethod on FastProperty.cs Line 23 - 
`SetDelegate = Expression.Lambda<Action<object, object>>(Expression.Call(instanceCast, this.Property.GetSetMethod(nonPublic: true), valueCast), new ParameterExpression[] { instance, value }).Compile();`

**Comment by borisdj** [comment]
Fixed with 3.2.3

**Comment by RossHNPC** [comment]
Thanks @borisdj we probably had the same issue as @sethsteenken 
We're using a DDD approach and have both a public GuidId and a private Id on the entities.
I'll update to 3.2.3 and hopefully be able to use some of the new features.

**Comment by StefanoWork4Me** [comment]
Just tried version 3.2.4 and same issue here.

**Comment by borisdj** [comment]
@StefanoWork4Me can you write snippet or test where that issue would be reproducible.

**Comment by borisdj** [comment]
@StefanoWork4Me actually first try now 3.2.5

**Comment by StefanoWork4Me** [comment]
> @StefanoWork4Me actually first try now 3.2.5

Just tested and same issue. I tested with only 1 record, but that's not the issue. 
I'll find the time to create a small project to reproduce the issue.

**Comment by StefanoWork4Me** [comment]
> @StefanoWork4Me actually first try now 3.2.5

I had some time to debug it. The problem in my case is here:

File: EFCore.BulkExtensions\EFCore.BulkExtensions\FastProperty.cs
Line 23-24

var setter = Property.GetSetMethod(true) ?? Property.DeclaringType.GetProperty(Property.Name).GetSetMethod(true); // when Prop from parent it requires DeclaringType
            SetDelegate = Expression.Lambda<Action<object, object>>(Expression.Call(instanceCast, setter, valueCast), new ParameterExpression[] { instance, value }).Compile();

What happens is that setter is null as I have a Property with no setter in my Class.

So the call Expression.Call(instanceCast, setter, valueCast) is failing throwing that exception. 

Hoping this helps.
