### ISSUE TITLE
Child entity not saved when using BulkInsert

### ISSUE THREAD

**Issue by fdahlberg** [borisdj/EFCore.BulkExtensions#394]
Hi,

I'm using version 3.2.3 of bulk extension and I have a problem getting BulkInsert to save a child entity to the database. 
I have a very simple model that looks like this:

```
    public class Parent
    {
        public Guid Id { get; set; }

        public Guid ChildAId { get; set; }

        public Child ChildA { get; set; }
    }
```

```
    public class Child
    {
        public Guid Id { get; set; }

    }
```

I create a parent with a child like this:

```
            var childA = new Child
            {
                Id = Guid.NewGuid()
            };

            var parent = new Parent
            {
                Id = Guid.NewGuid(),
                ChildAId = childA.Id,
                ChildA =  childA
            };
```

I then try to save this entity to the database using the following code:

```
            using(var context = new MyDbContext())
            {
                context.BulkInsert(new List<Parent> { parent });
            }
```

When i look in the database the parent has been created but not the child. 

I think I'm doing something wrong, but I can't understand what it is. 

If I use the following for saving it works as expected:

```
            using(var context = new MyDbContext())
            {
                context.Add(parent);
                context.SaveChanges();
            }
```

Kind Regards 
Fredrik Dahlberg

PS Thanks for an excellent library!

**Comment by borisdj** [comment]
You need second BulkInsert call with childList.
Take a look at ReadMe segment:
_Example of SetOutputIdentity with parent-child FK related tables_
