### ISSUE TITLE
UseOnlyDataTable parameter is gone

### ISSUE THREAD

**Issue by jasenf** [borisdj/EFCore.BulkExtensions#395]
Hi, I may be missing some new documentation somewhere but the following code no longer works:

` await _context.BulkInsertAsync(myObject, new BulkConfig   {UseOnlyDataTable = true  });`

Error: CS0117	'BulkConfig' does not contain a definition for 'UseOnlyDataTable'	

We've had this in place for over a year with no issue.  

Apologies if there is some release update that I can't seem to find.

jasen

**Comment by borisdj** [comment]
FastMember is removed and now DataTable is used always, so that param was removed.
