### ISSUE TITLE
Update property value on BulkInsertOrUpdate

### ISSUE THREAD

**Issue by kevinwout** [borisdj/EFCore.BulkExtensions#396]
Is het possible to change a property value of an item only if it is an update on BulkInsertOrUpdate?

**Comment by borisdj** [comment]
No, what you could do is separate it into BulkInsert and BulkUpdate.
And if you don't know which ones are for update BulkRead can be used to read them first.

**Comment by kevinwout** [comment]
Ok, thanks. 
I will use BulkRead first.
