### ISSUE TITLE
EnumToString not working in BatchUpdateAsync

### ISSUE THREAD

**Issue by IeuanWalker** [borisdj/EFCore.BulkExtensions#397]
Hi,

I have this table - 
```csharp
[Table("Settings")]
public class SettingsTbl
{
    [Key]
    public SettingsEnum Setting { get; set; }
    [Required]
    [MaxLength(20)]
    public string Value { get; set; }
}
```
and this in the database context - 
```csharp
modelBuilder
    .Entity<SettingsTbl>()
    .Property(e => e.Setting)
    .HasConversion<string>();
```

Calling this method -
```csharp
public async Task UpdateSetting(SettingsEnum setting, object value)
{
    await dbSet
        .Where(x => x.Setting == setting)
        .BatchUpdateAsync(x => new SettingsTbl
        {
            Value = value.ToString()
        })
        .ConfigureAwait(false);
}
```

Throws the following error - 
![image](https://user-images.githubusercontent.com/6544051/94444888-b64ea500-019e-11eb-9582-6fd7c13aea50.png)

Using NuGet version - 3.2.3

**Comment by borisdj** [comment]
Conversion is not currently supported for Batch.

**Comment by IeuanWalker** [comment]
@borisdj thanks, is this being planned?

Not too familiar how this package works, but if I figure out how to add this feature ill create a PR for it.

**Comment by borisdj** [comment]
If you manage to do it, you can send PR.

**Comment by borisdj** [comment]
Solved with latest version.
However for it to work name of parameter has to same as Property name (Case-insensitive), example:
_context.Settings.Where(x => x.**Settings** == **settings**).BatchUpdate(x => new Setting { Value = value.ToString() });_

**Comment by borisdj** [comment]
As of Now it works even with different named params.
