### ISSUE TITLE
ArgumentOutOfRangeException when using BatchDeleteAsync and BatchUpdateAsync

### ISSUE THREAD

**Issue by IeuanWalker** [borisdj/EFCore.BulkExtensions#398]
Getting the same error whether i use BatchDeleteAsync or BatchUpdateAsync

Example - 
```csharp
public virtual async Task UpdateBulkQuery(Expression<Func<T, bool>> query, Expression<Func<object, object>> updateExpression)
{
    await dbSet.Where(query).BatchUpdateAsync(updateExpression).ConfigureAwait(false);
}
```
```csharp
await _emailTbl.UpdateBulkQuery(x => x.Id.Equals(email.Id), _ => new EmailTbl
{
    HangfireJobId = jobId
}).ConfigureAwait(false);
```

Error -
![image](https://user-images.githubusercontent.com/6544051/94452232-3a0c8f80-01a7-11eb-8f94-ced18e6a2229.png)

**Comment by borisdj** [comment]
Can you write entire code sample for reproducing this, take a look at existing Tests.

**Comment by IeuanWalker** [comment]
@borisdj ye, ill look at making a quick project in the next few weeks.

**Comment by IeuanWalker** [comment]
@borisdj re-implemented and working fine now. Not sure what was different. Sorry :)

**Comment by borisdj** [comment]
Glad you sort it out.
