### ISSUE TITLE
Code Exception when insert, but data inserted into db

### ISSUE THREAD

**Issue by natnike** [borisdj/EFCore.BulkExtensions#40]
Hi,
I have two problems and was hoping someone can point me to the right direction. I am trying to insert and get the Id populated by using the 'SetOutputIdentity = true' flag with v2.0.7.

1. I got an exception 'There is already an open DataReader associated with this Command which must be closed first.' The data was inserted into SQL Server with the exception.
![image](https://user-images.githubusercontent.com/34728028/38833347-da0d90b8-418a-11e8-9002-5b699a703d21.png)

2. I am having the same issue as the below where the Id property does not change to reflect the Id on the table.
[https://github.com/borisdj/EFCore.BulkExtensions/issues/18](url)

Any suggestions?

Thanks,
ED

**Comment by borisdj** [comment]
Check this first and see if it is of any help.
[https://stackoverflow.com/questions/6062192/there-is-already-an-open-datareader-associated-with-this-command-which-must-be-c](https://stackoverflow.com/questions/6062192/there-is-already-an-open-datareader-associated-with-this-command-which-must-be-c)

Your Domain model, is it EF DB model and does it have more Properties?
It would be best if you could put entire code snipped that can reproduce your issue, or even make Test project with it. You can make a new project, zip it and put it online (drive or dropbox).
Other option would be to download (or make a Fork) the library and try to reproduce it in _EFCore.BulkExtensions.Tests_ project
In _RunInsert_ method there is already test example:
`context.BulkInsert(entities, new BulkConfig { PreserveInsertOrder = true, SetOutputIdentity =true });`

**Comment by borisdj** [comment]
Can not reproduce.
If you manage to isolate the problem in the test, reopen the issue.
