### ISSUE TITLE
NullReferenceException when using BulkInsert() if relationship properties arent explicitly defined in both entities.

### ISSUE THREAD

**Issue by KingOfAraby** [borisdj/EFCore.BulkExtensions#400]
I ran into this problem today and thought I would share.

I had only defined an 
ICollection<ChildEntity> ChildEntities { get; set; }

but had no FK-property in ChildEntity, EF-core creates the FK-column for me in the DB even though it's not defined anywhere in the code.
This caused a NullReferenceException in GetTable() on the line:
 var entityShadowFkPropertiesDict = entityType.GetProperties().Where(a => a.IsShadowProperty() && a.IsForeignKey()).ToDictionary(x => x.GetContainingForeignKeys().First().DependentToPrincipal.Name, a => a);

Again EF-core managed to handle this and I had to download the source-code and debug it to understand what was wrong so posting it here if anyone else runs into the same problem.

**Comment by borisdj** [comment]
With latest versions of library FK property itself is no longer required, but virtual Parent object in Child Entity still is.
So just add it and it should work.

**Comment by rachael-ross** [comment]
Are you saying we need to set the navigation property value to an object rather than setting a foreign key value for this to work?

**Comment by borisdj** [comment]
Nope, no need to set it, it just needs to exist.
