### ISSUE TITLE
BulkInsert with SetOutputIdentity do not insert data any data

### ISSUE THREAD

**Issue by KondzioSSJ4** [borisdj/EFCore.BulkExtensions#401]
Hi,

Today I tried a new version of this plugin,
but I realize when I set:
```
SetOutputIdentity = true,
PreserveInsertOrder = true
```
or just:
`SetOutputIdentity = true,`
then I don't have any new record at the end of `BulkInsert` or `BulkInsertAsync` operation in my table

but...
When I using `null` or new instance of `BulkConfig` I have as much as I expect items in the database

so...
Could you tell me if that is a bug? or I miss something?

Example of code what I use:
```
            using (var context = new DatabaseContext())
            {
                var id = context.Parent.FirstOrDefault().Id;

                var sites = Enumerable.Range(0, 1000).Select(i => new Child()
                {
                    Name = "test",
                    Parent = id,
                    Active = true
                }).ToList();

                context.BulkInsert(sites, new BulkConfig()
                {
                    SetOutputIdentity = true,
                    PreserveInsertOrder = true // with or without that setting
                });
            }
```

EF Core version: 3.1.8
EF Core BulkExtensions version: 3.2.3

**Comment by borisdj** [comment]
Can you write entire code sample for reproducing this, take a look at existing Tests.

**Comment by KondzioSSJ4** [comment]
@borisdj 

I tried to do that some sample for you, but every my try is success 
except for my real schema...

e.g.
![image](https://user-images.githubusercontent.com/7957247/95084423-266ca600-071e-11eb-98d3-ef8cc4f37b42.png)

and problematic case:
![image](https://user-images.githubusercontent.com/7957247/95084542-52882700-071e-11eb-8445-a361246004ed.png)

as you can see the 2nd image shown that count in context wasn't change
and difference is only in `BulkConfig`

I already checked:
- database compatibility (2016)
- database options
- schema differences in EF Core definition


My tries ends only on the case when I didn't get back PK IDs back to the model
so updating the referred model is not possible

https://github.com/KondzioSSJ4/EFCoreExtensions__Issue401

@borisdj Do you have some thoughts what is wrong?
(that model works correctly in EF Core without any problem)

**Comment by borisdj** [comment]
In ReadMe take a look at segments:

> PreserveInsertOrder makes sure that entites are inserted to Db as they are ordered in entitiesList.
> ...
> When using PreserveInsertOrder with SetOutputIdentity Id value does matter.
> ...

Most practical is to temporarily set IDs to negative values

**Comment by KondzioSSJ4** [comment]
@borisdj 

> Most practical is to temporarily set IDs to negative values
Not always is good idea, because what if some of negative IDs was already taken?
(if somebody turns off/on `identity`)

but ok, I have no another way to fix that :/

**Comment by borisdj** [comment]
For only BulkINSERT you don't even need negatives, they can be 1, 2, ... and Db will change them.
But for BulkUPDATE or BulkINSERTorUPDATE if those for Update are matched by Id column, then remaining ones for Update need different values for sorting and those values also have to be difeerent for existing in Db.
As stated that can either be big numbers or negative, I prefer the second option since out convention for int ID is that they are always positive, SQL default is from 1 ++.
