### ISSUE TITLE
Problem with BulkUpdate if Identity Column and Identity Property have different names

### ISSUE THREAD

**Issue by digitaltoolsinc** [borisdj/EFCore.BulkExtensions#404]
Say you have an identity column in the database name Product_ID. And then your property name is ProductID.

When you use BulkUpdate you will get an error complaining about inserting into the identity field.

After looking through the code this is what I came up with.

Line 131 TableInfo.cs. This just gets the properties of the entity, not the actual table

```cs
var allProperties = entityType.GetProperties().AsEnumerable();
```

LIne 149 TableInfo.cs Thus when you get the IdentityColumn name, you just get the name of the property on the C# object, not the column name

```cs
 IdentityColumnName = allProperties.SingleOrDefault(a => a.IsPrimaryKey() && a.ClrType.Name.StartsWith("Int") && a.ValueGenerated == ValueGenerated.OnAdd)?.Name; 
```
Thus then in SQlQueryBuilder.cs on line 109, it picks up the identity column as a nonidentity column

```cs
 List<string> nonIdentityColumnsNames = columnsNames.Where(a => !a.Equals(tableInfo.IdentityColumnName, StringComparison.OrdinalIgnoreCase)).ToList();
```
So that on line 130 in SqlQueryBuilder.cs when it actually tries to do the merge it tries to set the IdentityColumn

```cs
q += $" WHEN MATCHED THEN UPDATE SET {GetCommaSeparatedColumns(nonIdentityColumnsNames, "T", "S")}";
```
My work around was in EF Core to rename the ProductID field to Product_ID (have the column name and the entity property match), but obviously lots of databases have different naming conventions than C# applications and it would be nice if we could be able to not have to use the same name.

Thanks!

**Comment by borisdj** [comment]
Fixed with 3.2.4
