### ISSUE TITLE
Bulk Insert : missing entries on bulk insert

### ISSUE THREAD

**Issue by sks2141** [borisdj/EFCore.BulkExtensions#406]
Hello all,

@borisdj - Thanks for a great library. 

I have been facing a 'data inconsistency' issue lately, which is hard to reproduce. I am trying to write more than 200,000 rows in a dataset which is highly hierarchical. The inserts occur in less than 20 seconds; however, I have noticed that some of the tickets data is missing in few cases. I was not able to reproduce this scenario via code and am looking for advice, before I take the step to re-gut the persistence layer.

The graph is 5 levels deep. The graph looks like below: (since the data and code is sensitive, I don't have a throwaway code)

1. Level 1: Run 
2. Level 2: Tickets, linked to a run 
3. Level 2: Month, linked to a run 
4. Level 3: Generated money linked to a month
5. Leve 3: 6 Bank Accounts linked to a month
6. Level 4: Generated money breakdowns linked to Generated money (Level 3) 
7. Level 4: Bank account details linked to each of '6' Bank accounts (Level 3) 
8. Level 5: Generated money breakdown details linked to Generated money breakdowns (level 4) and Tickets (Level 2)

`using (var transaction = context.Database.BeginTransaction()) // DbCommandTimeOut is 5 minutes
{
      await Add(context, run); // run is the 'Level 1' run object
}`

Add() : pseudo code

```
  // bulkConfig -> BatchSize = 50,000; BulkCopyTimeout = 0 // no limit, PreserveInsertOrder = true, SetOutputIdentity = true
  // I assume that the bulk config will be affected by DbContext's DbCommandTimeOut of 5 minutes, but the entire operation happens within 20-30 seconds; so we're fine here!

   // Level 1
   await context.BulkInsertAsync(new Collection<Run> { run }, bulkConfig); // run is the DbEntity

   // Level 2
   await AddTickets(run, context, bulkConfig);

   // Level 2 
   await AddMonths(run, context, bulkConfig);
```

AddTickets() : pseudo code 

```
   var index = -run.Ticket.Count; // run is dbEntity saved above.
   foreach(var ticket in run.Ticket)
   {
        ticket.RunId = run.Id; // Setting Fk to match run Id generated by Level 1 await insert 
        ticket.Id = index++; // To preserve the insertion order in database
   }

   await context.BulkInsertAsync(run.Ticket.ToList(), bulkConfig);

```

I follow the above pattern for other levels; the tertiary linkage between tickets (level 2) and Generated money breakdown details (Point **8** above) is tackled using a dictionary that gets the ticket Ids (from the uncommitted db), when 'await context.BulkInsertAsync(run.Ticket.ToList(), bulkConfig) is executed. 

This all works well; however, I noticed that some of the tickets are missing in the database - I noticed that the batchSize of 50,000 might have a role in this; but I am not sure. Any other db entities are not affected, since the number of entities is less than 50k and a Sql bulk insert is called for each of them.

I notice this issue more frequently when I run my Asp.Net core 3.1 hosted service inside a linux container. Per https://github.com/borisdj/EFCore.BulkExtensions/issues/281, I upgraded the EntityFramework libraries to use the same version (3.1.8) as that used by EfCore.BulkExtensions version 3.1.1 - This internally uses Microsoft.Data.SqlClient version 1.1.3.(earlier I was using version 1.0.19269.1 of Microsoft.Data.SqlClient). However, this did not solve the above issue.

Do you think I need to call the divide-and-conquer the calls to BulkInsertAsync on Tickets? If yes, what will be the pattern, such that the Tickets are properly persisted to the database and have the correct Ids (Identity Keys), which can be later fed to hydrate Level 5's data sets?

Appreciate your help and response.

**Comment by sks2141** [comment]
(based on above assumption) Or should I selectively modify the batch size to consider the entire db set, before insertion ?

**Comment by sks2141** [comment]
My bad - there was an issue in the code that bloated the dbContext: issue was related to few registrations that were accidentally set for 'singleton scope' - and bubbled only in subsequent runs, non-deterministically.

I realized this by adding alerts to help collect forensics for
1. when "Number of persisted entities" <> "Number of entities in the object graph before persistence"
2. when "Number of persisted entities" <> "Number of other entities being persisted that logically should equal the number of persisted entities"
And noticed that these alerts were never triggered at all, in any subsequent troubled executed runs.

**Comment by borisdj** [comment]
Glad you solved it :)
