### ISSUE TITLE
IQueryableExtensions.ToParametrizedSql Always Returns Microsoft.Data.SqlClient.SqlParameter

### ISSUE THREAD

**Issue by Coder3333** [borisdj/EFCore.BulkExtensions#407]
No matter whether my sql connection is made using Microsoft.Data.SqlClient or System.Data.SqlClient, the parameters returned by IQueryableExtensions.ToParametrizedSql are always of type Microsoft.Data.SqlClient.SqlParameter.  I expect the extension method to switch to the correct parameter type depending on the connection type.

**Comment by borisdj** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/issues/408
