### ISSUE TITLE
DbContextBulkExtensions.BulkInsert fails when used with System.Data.SqlClient.SqlConnection

### ISSUE THREAD

**Issue by Coder3333** [borisdj/EFCore.BulkExtensions#408]
SqlBulkOperation.cs contains multiple references to Microsoft.Data.SqlClient.SqlConnection and tries to cast the incoming connection to this type.  Most of the hard casts seem to be around the use of SqlBulkCopy.  Much like there is separate code to handle SQLLite, I believe there needs to be branching code to handle Microsoft.Data.SqlClient and System.Data.SqlClient separately, depending on the connection type.  I also found hard coded uses of Microsoft.Data.SqlClient.SqlParameter in TableInfo.cs.  This should also use different parameter types depending on the connection type.

**Comment by Coder3333** [comment]
I submitted a pull request that addresses this issue.  The internal logic will decide at runtime which structures to use, so consumers can continue to use Microsoft.Data.SqlClient or if they have legacy code that is coded against System.Data.SqlClient, that will also work.

[https://github.com/borisdj/EFCore.BulkExtensions/pull/418](url)

**Comment by Numpsy** [comment]
Would that mean that the lib would depend on both of the SqlClient packages/libs so you need to deploy both? (just wondering, as it already depends on both SqlClient and Sqlite even if you only care about one of them (#228), which isn't ideal).

(actually, just out of interest, i'm also not sure when an EFCore 3.1 context would use the ```System``` version, or if that would differ with EFCore 5 which doesn't support .NET 4.x any more)

**Comment by Coder3333** [comment]
Yes, I added back the reference to the System.Data.SqlClient package that you removed when you added Microsoft.Data.SqlClient.  I understand how it would be more ideal if the BulkExtensions library did not have these direct references and could be extensible in a way that allowed anyone to build an extension to use their provider of choice, but I do not see that being a quicky refactor, and it would absolutely break existing code.  This change just adds back a reference and functionality that was present for years, but was removed 6 months ago.  This is a major blocking issue for us and is preventing our entire enterprise from moving to EF 3, so I really hope you will consider integrating this update.

On your second point we always instantiate our DBContext from an existing SQLConnection.  This way, if the application is using System or Microsoft, that is the type of SQLConnection that will get used.  Over time, we will move to the Microsoft version, but for now, I still need to be able to support the System version without mandating that every product stop what it is doing and re-test everything with a different data access provider.

The code looks something like this:
`
            // options builder allows us to manually provide the connection to the DBContext
            var optionsBuilder = new DbContextOptionsBuilder<TContext>();
            var typedConnection = connection as DbConnection;
            if (typedConnection == null)
            {
                throw new Exception("'connection' parameter is expected to be of type DbConnection");
            }
            optionsBuilder.UseSqlServer(typedConnection);

            // Create DBContext using the options builder
            var context = (T)Activator.CreateInstance(typeof(T), options.Options);
`

**Comment by borisdj** [comment]
Merged https://github.com/borisdj/EFCore.BulkExtensions/pull/418
Thx for contrib.

**Comment by borisdj** [comment]
Lib is now upgraded to v5.0.0 with support for .Net 5 for EF Core 5.
Target in v5 is .NetStandard 2.1.
Also to note here that for v5.0.1 I plan to remove System.Data.SqlClient, so only Microsoft.Data.SqlClient will be used.
Hope that's fine.

**Comment by Coder3333** [comment]
@borisdj : As much as I hate it, I understand the update to Standard 2.1, because Microsoft.EntityFrameworkCore also requires 2.1; however, why do you feel the need to remove System.Data.SqlClient after we already spent the time to implement it?  Every other library I use supports both versions of SqlClient.  I can understand refactoring it to allow a more “plug and play” method that would also support non-SQL Server based clients, but I do not see the point in completely removing the option of allowing System.Data.SqlClient .

I appreciate that you let me know about these changes.  I hope that the library will continue to release bug patches on the 3.x line, because I do not think our enterprise will be able to update all of our projects to .Net 5 anytime soon.  Thank you.

**Comment by borisdj** [comment]
I was doing some refactoring and wanted to simplify and clean code, also to remove extra dependencies.
In addition my understanding was that .Net 5 can work only with Microsoft.Data.SqlClient.
So if you are not migrating to Net 5 then keep using latest v3, and once you do migrate then I think you will also need to switch dependency away from System to Microsoft.
