### ISSUE TITLE
Update to EFCore.BulkExtensions v3.2.4 breaks a self-contained .NET Core 3.1 ServiceFabric service

### ISSUE THREAD

**Issue by WTobor** [borisdj/EFCore.BulkExtensions#411]
I have a ServiceFabric service, which is running the latest .NET Core 3.1. I published & deploy it as self-contained. It references _EFCore.BulkExtensions_. For version 3.1.4 everything worked great, but after update to version 3.2.4, there is an error during deployment on service fabric:

```There was an error during CodePackage activation. The process/container terminated with exit code:2147516556.```

After research, I found out that there is a problem with _Microsoft.Data.SqlClient_ version (update from v1 to v2).

It is known issue for Microsoft.Data.SqlClient v2 [SqlClient issue](https://github.com/dotnet/SqlClient/issues/644)

Fix is still not ready. The temporary solution is to use _EFCore.BulkExtensions_ v3.1.4

**Comment by borisdj** [comment]
Thx for info.
At the moment, as you have suggested, the older version can be used.
Hope they will fix it soon so we can update to newer version.
If not we could downgrade that package until it gets solved.

**Comment by borisdj** [comment]
Latest version 3.3.6 of the Bulk library is now referencing 2.1.2 Microsoft.Data.SqlClient
