### ISSUE TITLE
CreatedBy, UpdatedBy, Created and UpdatedDate

### ISSUE THREAD

**Issue by rdasgupta7141** [borisdj/EFCore.BulkExtensions#415]
How can I accomplish these values when using BulkInsertOrUpdate feature?

**Comment by borisdj** [comment]
You can first use BulkRead, compare it to your list based on unique column, to find which are New.
After for those that already exist set UpdatedBy and UpdatedDate, and for the remaining set CreatedBy, Created.
Then you can call BulkInsertOrUpdate.
