### ISSUE TITLE
Error in column of  varbinary(max)

### ISSUE THREAD

**Issue by kohzadi1395** [borisdj/EFCore.BulkExtensions#416]
hi, my friends,
I use this wonderful extension but it has Error in varbinary(max) column

Error:
Implicit conversion from data type varchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.

Generated Query:

UPDATE u
SET    [Id] = '00000000-0000-0000-0000-000000000001' /* @Id */,
       [CreateDate] = '2020-10-02T22:41:26' /* @CreateDate */,
       [Email] = 'kohzadi_hossein@yahoo.com' /* @Email */,
       [FirstName] = 'Hossein' /* @FirstName */,
        [LastName] = 'Kohzadi' /* @LastName */,
       [ProfileImage] = '0xFFD8FFE000104A46494600010101009600960000FFDB004300080606070605080707070909080A0C140D0C0B0B0C1912130F141D1A1F1E1D1A1C1C20242E2720222C231C1C2837292C30313434341F27393D38323C2E333432FFDB00430...00145145001451450014514500145145001451450014514500145145007FFFD9' /* @ProfileImage */
FROM   [Users] AS [u]
WHERE  [u].[Id] = '00000000-0000-0000-0000-000000000001' /* @__entity_Id_0 */

**Comment by borisdj** [comment]
What type is that field in Entity and what in Db?
Can you also write entire code snipped where the issue can be reproduced.
In Test project I have tried adding to class `Item` property
`public byte[] Note { get; set; }`
And following BatchTest passed:
`context.Item.Where(a => a.ItemId = 1).BatchUpdate(new Item { Note = new byte[] { 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x22 } });`
