### ISSUE TITLE
Private properties ignored

### ISSUE THREAD

**Issue by Morcatko** [borisdj/EFCore.BulkExtensions#417]
Hello
I tried to use `BulkInsertOrUpdate` (I assume other calls are affected as well) with entity that has a private required string property that is mapped to SQL column in `OnModelCreating` and accessed using specialized Getter/Setter

something like this:
```
class Entity 
{
   ...
   [Requried]
   private string JsonData {get; set;}
   ...

   public TData GetData() => Json.Deserialize(this.JsonData);
   public void SetData(TData data) => this.JsonData = Json.Serialize(data);
}

onModelCreating(ModelBuilder builder) 
{
   builder.Entity<Entity>().Property<string>("JsonData");
}
```

InsertOrUpdate fails with `Cannot insert the value NULL into column 'JsonData', table 'tempdb...'; column does not allow nulls. INSERT fails.` in `EFCore.BulkExtensions.SqlBulkOperation.Insert`

I think the isue is caused by the way how `GetDataTable<T>` method works. It gets all properties (only public by default) from the T type.

I was able to fix it with following change (works for my use case however I have not tested any other calls)
```
var properties = type.GetProperties();
>>>
var properties = type.GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
```
Do you think this is a proper fix?

Thanks

Thanks for this great library

**Comment by borisdj** [comment]
Yes it seems good, I will test it and make the change if all works fine.

**Comment by borisdj** [comment]
Fixed

**Comment by IT-CASADO** [comment]
I'm also using this great library and have the same pattern as Morcatko.

The only difference is that I'm using a private **field** instead of a property:

```
class Entity 
{
   ...
   [Requried]
   private string JsonData;
   ...

   public TData GetData() => Json.Deserialize(this.JsonData);
   public void SetData(TData data) => this.JsonData = Json.Serialize(data);
}

onModelCreating(ModelBuilder builder) 
{
   builder.Entity<Entity>().Property<string>("JsonData");
}

```

Would be nice to see also support for private fields!

**Comment by borisdj** [comment]
Entity model are usually mapped to Properties by default.
But if you still need private field what you could do is make a Property around it with explicit getter/setter:
```C#
class Entity 
{
   ...
   [Requried]
   private string jsonData; // first letter lowercase
   [Requried]
   protected string JsonData { get { return jsonData; } set { jsonData = value; } }
   // is access modifier is protected to keep it from direct access
   // if it would be public  fluent api would not be required
   ...

   public TData GetData() => Json.Deserialize(this.JsonData);
   public void SetData(TData data) => this.JsonData = Json.Serialize(data);
}

onModelCreating(ModelBuilder builder) 
{
   modelBuilder.Entity<Info>(e => { e.Property("JsonData").HasColumnName("JsonData"); });
}
```

**Comment by IT-CASADO** [comment]
usually, but not always ;)

It's our own code, so for now we are using a Property.
