### ISSUE TITLE
BulkRead with multiple column criteria

### ISSUE THREAD

**Issue by rachael-ross** [borisdj/EFCore.BulkExtensions#419]
Hi there, 

I have hundreds of thousands of records in a table "FundData" and the ability to mass import around 135,000 at a time. Some will be inserts, updates and deletes. However, the deletes will be by specific criteria and only after the inserts and updates have occurred - so I can't use the BulkInsertOrUpdateOrDelete since I'm not performing a full table sync. So I'm using the BulkInsertOrUpdate and then determining which ones need to be removed from that dataset (from a previous import).

I've successfully completed the insert and update (BulkInsertOrUpdate) and then the delete operation using:

```
await context.FundData.Where(d => !fundDatasToSave.Keys.Contains(d.SecId)
                                    && d.PeriodYear == reportingPeriod.Year
                                    && d.PeriodQuarter == reportingPeriod.Quarter
                                    && !d.IsPublished
                                    && d.Version == 0).BatchDeleteAsync();

```

However, I'm wondering if it would be more efficient to use the BulkRead and BulkDelete instead?

If you believe it would be, how would I perform a BulkRead on multiple column values to then hand off to BulkDelete?

**Comment by rachael-ross** [comment]
Actually, I got it from 34 seconds to 1 second for the deletion by not using the "NOT IN" in the query and then filtering in the app.

```
 List<FundData> allUnpublishedFundDataForPeriod = context.FundData
                                    .Where(d =>                                         
                                        d.PeriodYear == reportingPeriod.Year
                                        && d.PeriodQuarter == reportingPeriod.Quarter
                                        && !d.IsPublished
                                        && d.Version == 0)
                                    .AsNoTracking()
                                    .Select(f => new FundData 
                                    { 
                                        PeriodQuarter = f.PeriodQuarter, 
                                        PeriodYear = f.PeriodYear, 
                                        SecId = f.SecId, 
                                        Version = 0 
                                    })
                                    .ToList();

                        List<FundData> fundDatasToDelete = allUnpublishedFundDataForPeriod.Where(f => !fundDatasToSave.Keys.Contains(f.SecId)).ToList();                       

                        if (fundDatasToDelete.Any())
                            await context.BulkDeleteAsync<FundData>(fundDatasToDelete);
```

But, still - is there a way to perform a BulkRead with multiple columns or is it only used for Joins? (like an Includes)

**Comment by borisdj** [comment]
If you didn't have `Contains` BatchDelete would be enough, even better then BulkDelete, since no need for loading data.
However since you do have it, good idea was to move it in memory because that can be bottleneck in Db.
And when part of 'Where' moved outside of Query then BulkDelete is only option.
In you case you can not use BulkRead but there is no need for it, normal Select is fine.
BulkRead is only used when want to load large data list by some specific info, either PK or some unique column.

**Comment by rachael-ross** [comment]
Agreed! The difference was significant.

However, my question about BulkRead is more general - for example:

If I want to retrieve 100K objects and that type is defined like so:

Composite PK
  short Quarter
  short Year
  string SecId
  short Primary

Property 
  IsPublished

but I want only the objects that meet the following criteria:

  Quarter = 4
  Year = 2020
  Primary = 1
  IsPublished = 0

Can I achieve this with BulkRead?

BTW...Thanks for such a quick response!

**Comment by borisdj** [comment]
No, you need unique columns.
But as previously stated for that kind of Where pure Select is always faster then BulkRead.

BulkRead is more efficient only when having a list of unique values and want to Load all those entities that match.
Regular way for this would be with Contains(WhereIN) which would TimeOut if List is more then several thousand.
Another way is to use JOIN in Memory but that loads entire table.
So for that case BulkRead is better.
