### ISSUE TITLE
Why I need to set Id to 0?

### ISSUE THREAD

**Issue by vladop** [borisdj/EFCore.BulkExtensions#421]
I figured out that when I am inserting and Id is set it will work until there is no same Id already in the database. It is strange because I thought that Id is ignored and database generate it especially when this settings are used: ( I am using this settings)
:
```
 var bulkConfig = new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true };`
`:
```
This is from documentation
PreserveInsertOrder makes sure that entites are inserted to Db as they are ordered in entitiesList.
However for this to work Id column needs to be set for the proper order.
For example if table already has rows, let's say it has 1000 rows with Id-s (1:1000), and we now want to add 300 more.
Since Id-s are generated in Db we could not set them, they would all be 0 (int default) in list.
But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300 (for BulkInsert).
Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.

And this is my code:

     ```
       var bulkConfig = new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true };
            var didDataObjectValues = new List<ECUDIDDataObjectValue>();
            try
            {
                using (var transaction = await _databaseContext.Database.BeginTransactionAsync())
                {
                    await _databaseContext.BulkInsertAsync(eCUIdentificationReports, bulkConfig);

                    eCUIdentificationReports.ForEach(eCUIdentificationReport =>
                    {
                        eCUIdentificationReport.DIDDataObjectValues.ToList().ForEach(didDataObjectValue => didDataObjectValue.ECUIdentificationReportId = eCUIdentificationReport.Id);
                        didDataObjectValues.AddRange(eCUIdentificationReport.DIDDataObjectValues);
                    });
                    await _databaseContext.BulkInsertAsync(didDataObjectValues, bulkConfig);

                    await transaction.CommitAsync();
                }
            }
```

There should be no big deal here,but with Id set to zero I am getting complex data (multiple child entities have multiple child entities) inserted wrongly (wrong connections, although I manually made connections). I need to figure out this

**Comment by borisdj** [comment]
If you set PreserveInsertOrder then there you should also set IDs for sorting.
PreserveInsertOrder will not work if all IDs are left to defualt 0.
Good practice is to use negative values, more info in ReadMe.
