### ISSUE TITLE
Update to .NET 5 and EF Core 5

### ISSUE THREAD

**Issue by EduardoLariosGE** [borisdj/EFCore.BulkExtensions#425]
Hello just wondering if the project will have a release for .NET 5 eventually? 
As I understand it's a .NET Standard 2.0 project so it should work with the new version of dotnet and EF Core?

I'm still kind of confused about the required changes, so this is mostly to clarify the future of the project.

**Comment by Numpsy** [comment]
It should work with .NET 5, but I think EFCore 5 now only supports .NET Standard 2.1, so this lib would need to be changed to target that in order to use EFCore 5 instead of 3.

**Comment by Dylan-Erskine** [comment]
Yeah I gave it ago, it seemed to work but most of the bulk operations were running significantly slower compared to EF Core 3.1. So I just ended up reverting back to 3.1 for now.

**Comment by borisdj** [comment]
From reading some compatibility info on .Net 5 understanding was that it should work without changes.
And @Dylan-Erskine confirmed it with a test.
As for the speed will check that in the near future.

**Comment by EduardoLariosGE** [comment]
Alright, thanks for the info @borisdj and everyone else. We'll probably stay on 3.1 for a while then and I'll keep checking for any changes meanwhile.

**Comment by yangzhongke** [comment]
I have created a library to implement this on EF Core 5.

await ctx.DeleteRangeAsync(b => b.Price > n || b.AuthorName == "zack yang");

await ctx.BatchUpdate()
.Set(b => b.Price, b => b.Price + 3)
.Set(b => b.Title, b => s)
.Set(b=>b.AuthorName,b=>b.Title.Substring(3,2)+b.AuthorName.ToUpper())
.Set(b => b.PubTime, b => DateTime.Now)
.Where(b => b.Id > n || b.AuthorName.StartsWith("Zack"))
.ExecuteAsync();

Github repository: https://github.com/yangzhongke/Zack.EFCore.Batch
Report: https://www.reddit.com/r/dotnetcore/comments/k1esra/how_to_batch_delete_or_update_in_entity_framework/

**Comment by borisdj** [comment]
Lib is upgraded  to v5.0.0 with support for .Net 5 for EF Core 5.
Target in v5 is .NetStandard 2.1

**Comment by borisdj** [comment]
@ErikEJ I've noticed that with .Net 5 simple BulkInsert is around 2 times slower then with .Net 3.1
Am I correct to assume that there were some significant changes that had effect on efficiency.
Secondly is there anything that can now be configured to speed it up more.
If not, is this how it will remain, or are some improvements planed in new minor versions, or at least in next mayor release .Net 6

**Comment by ErikEJ** [comment]
just using SqlBulkCopy you see this?

Is the slowness in EF Core part, or in SqlBulkCopy?

**Comment by ErikEJ** [comment]
Or in other words: which components does .NET 3.1 imply, and what components does .NET 5.0 imply?

EF Core version, Microsoft.Data.SqlClient version?

**Comment by borisdj** [comment]
Haven't done detailed inspection yet.
Just compared same Test before and after switching to .Net 5.
Previously lib. was targeting **.NetStandard 2.0** and had nuget dependencies:
_Microsoft.EntityFrameworkCore 3.1.13_ 
Now it is targeting **.NetStandard 2.1** and using _Microsoft.EntityFrameworkCore 5.0.4_ 
And also some sitax had to be changed for new version, example:
`GetTargetType() -> TargetEntityType`
`IsDependentToPrincipal() -> ParentNavigation.IsOnDependent`
`GetColumnName() -> GetColumnName(ObjectIdentifier)`

Compared Test was following (on 3.1 just under 2s, and with 5.0 took little over 4s):
```C#
var entities = new List<Item>();
for (int i = 1; i < 100000; i++)
{
	var entity = new Item
	{
		Name = "name " + i,
		Description = "info " + Guid.NewGuid().ToString().Substring(0, 3),
		Quantity = i % 10,
		Price = i / (i % 5 + 1),
		TimeUpdated = DateTime.Now
	};
	entities.Add(entity);
}
context.BulkInsert(entities);
```

Also to note that Test project itself was changed,
Target:  **netcoreapp3.1** -> **net5.0**
Nugets:
Microsoft.EntityFrameworkCore.SqlServer 3.1.13 -> 5.0.4
Microsoft.Extensions.Configuration.Json 3.1.13 -> 5.0.0
NET.Test.Sdk 16.9.1 -> 16.9.4

**Comment by borisdj** [comment]
Did some more digging.
Operation `sqlBulkCopy.WriteToServer(dataTable)` runs the same aroud 1s on both version.
So it seems slow neck is in some of prepare method of the library, either extension code itself or one of EFCore methods that are used.

**Comment by ErikEJ** [comment]
@andrysvyrid @ajcvickers

**Comment by borisdj** [comment]
Found the problem, one inner method of lib had inside a loop the call to .GetColumnName() instead of using Dictionary.
