### ISSUE TITLE
Sqlite operations do not work when column names contains spaces or other parameter-incompatible characters

### ISSUE THREAD

**Issue by gandhis1** [borisdj/EFCore.BulkExtensions#426]
When preparing the Sqlite statement, the following code uses the raw column names as the parameter name for the `VALUES` section of an insertion:

https://github.com/borisdj/EFCore.BulkExtensions/blob/c08737fbf18c2ef0af4fe2b5980e45bf3bedb302/EFCore.BulkExtensions/SqlQueryBuilderSqlite.cs#L27-L31

However if your otherwise legitimate column name has a space, a question mark, a pound sign, or similar, then this would fail. Such characters - in particular a space - would not work for Sqlite operations.

This is not isolated to the insertion command generation. This also applies to all of the other ones which make use of parameters to pass in values.

In addition to the other command text preparation methods, here is the other section that would need to get updated:

https://github.com/borisdj/EFCore.BulkExtensions/blob/c08737fbf18c2ef0af4fe2b5980e45bf3bedb302/EFCore.BulkExtensions/SqlBulkOperation.cs#L931

This line similarly assumes that the column name is the parameter name. However, once the first issue mentioned above is fixed, that would no longer be the case.

I believe a good assumption is to use the C# property name as the parameter name, since C# likewise prohibits characters such as spaces and question marks.

**Comment by borisdj** [comment]
Fixed as proposed with property names for sql parameters.
Published NuGet v.3.4.1
