### ISSUE TITLE
How do I insert records with specific Id values?

### ISSUE THREAD

**Issue by berendengelbrecht** [borisdj/EFCore.BulkExtensions#428]
HI,

When I insert an object with Id == 1000 in an empty table,, its Id is changed to 1 when BulkInsert returns. Actually, the inserted Id values are always equal; to the row number of the inserted record.

How do I accomplish that the Id of the inserted object is what I specify? The Ids in my table have meaning and are used as foreign keys in other tables. Please help!

Best regards,

Berend

**Comment by berendengelbrecht** [comment]
I found the answer to my own question after reading the code for SQL Server.
The software behaves as per my expectations when I use this BulkConfig
   
    private static readonly BulkConfig _bulkConfig = new BulkConfig()
    {
      SqlBulkCopyOptions = Microsoft.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity
    };

**Comment by borisdj** [comment]
Glad you sort it out.
