### ISSUE TITLE
BulkUpdate update all columns

### ISSUE THREAD

**Issue by fatemehramezani** [borisdj/EFCore.BulkExtensions#429]
I pass the list of updated columns as updatedColumns to BulkUpdate like this:

`Source.BulkUpdate(entities, new BulkConfig { PropertiesToInclude = updatedColumns.ToList(), UpdateByProperties = updatedColumns.Intersect(columnNames).ToList() });
Source.CustomSources.UpdateRange(entities);
Source.SaveChanges();`

But it updates all columns on the SQL server side which is:
`UPDATE [CustomSources] SET [CreatedByUserId] = @p0, [CreatedOn] = @p1, [DataSourceId] = @p2, [DescriptionId] = @p3, [GroupId] = @p4, [ModifiedByUserId] = @p5, [ModifiedOn] = @p6, [Name] = @p7, [TypeId] = @p8
WHERE [Id] = @p9;`

But updatedColumns is {'Name'}

**Comment by borisdj** [comment]
When using Bulk ops you don't need following code segment:
`Source.CustomSources.UpdateRange(entities); Source.SaveChanges();`

**Comment by fatemehramezani** [comment]
I removed them then BulkUpdate is  not working and it does not update values
