### ISSUE TITLE
Support for Owned Types (EF Core)

### ISSUE THREAD

**Issue by tjackadams** [borisdj/EFCore.BulkExtensions#43]
**Class configuration**

```
    public class CentraStageAlert : Entity<string>
    {
        public CentraStageAlert()
        {
            AlertMonitorInfo = new CentraStageAlertMonitorInfo();
            AlertSourceInfo = new CentraStageAlertSourceInfo();
        }

        public CentraStageAlertMonitorInfo AlertMonitorInfo { get; set; } // owned type

       // rest of props
    }
```

```
    public class CentraStageAlertMonitorInfo
    {
        public bool SendsEmails { get; set; }
        public bool CreatesTicket { get; set; }
    }
```

**Entity Configuration**

```
    public class CentraStageAlertConfiguration : IEntityTypeConfiguration<CentraStageAlert>
    {
        public void Configure(EntityTypeBuilder<CentraStageAlert> builder)
        {
            builder
                .Property(p => p.Id)
                .ValueGeneratedNever();

            builder
                .OwnsOne(p => p.AlertMonitorInfo);
        }
    }
```

The following exception is thrown when using the InsertOrUpdate method.

> SqlException: Cannot insert the value NULL into column 'AlertMonitorInfo_CreatesTicket', table 'PortalCore.dbo.CentraStageAlerts'; column does not allow nulls. UPDATE fails.
> The statement has been terminated.

After a bit of investigating myself, i think its this line which is part of the problem https://github.com/borisdj/EFCore.BulkExtensions/blob/cd4ce33ce394c37cf91f31e939dd3e710df49cc6/EFCore.BulkExtensions/TableInfo.cs#L75

As the `GetProperties()` method does not return the Navigation properties that are present. I think a combination of `GetNavigations()` and `IsOwned()` would be needed to get all the required properties.

Is adding support for Owned Types be something you're interested in? If so i can have a crack at a PR, i'm just not overly familiar with the SqlBulkCopy side of things.

**Comment by borisdj** [comment]
I think support for this can be added, so you if you want you can try to add it and send a PR.
But since  from EF version 2.1 there is also attribute `[Owned]` as another way to configure this I would wait for EF 2.1 release, which will probably be next month.
Also there is another issue with request for feature [ValueConverters](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) (EF Core 2.1) so than it can be added together when switch would be made.

**Comment by borisdj** [comment]
I am now trying to analyse details about implementation and one issue seems to be that FastMember library does not support Nested properties:
[https://github.com/mgravell/fast-member/issues/21-How hard would it be to add nested property access?](https://github.com/mgravell/fast-member/issues/21)

**Comment by borisdj** [comment]
What could be done to bypass the problem with FastMember is not to use it, instead to implement it with DataTable, only when Entity has OwnedTypes.

**Comment by borisdj** [comment]
Added and Nuget 2.1.1 published.
