### ISSUE TITLE
Where have the contributors gone?

### ISSUE THREAD

**Issue by Coder3333** [borisdj/EFCore.BulkExtensions#430]
I am used to this project moving at a very fast pace with regular feedback from the contributors, but it looks like @borisdj has posted very infrequently in the past 2 months.  The reason why I noticed is because I am up against a wall on a feature that was removed from BulkExtensions.  I added it back with a Pull Request, but I have not received any feedback as to whether the request will be accepted.  I would just like to know if this is a temporary condition or if I need to start making long term plans to remove our references to BulkExtensions in our applications.

I apologize for posting this question here, but I just didn't know where else to make this inquiry.  Thank you.

**Comment by borisdj** [comment]
Still here, but have been quite busy lately.
Will see to check and merge Requests and sort some other issues till end of this week.

**Comment by borisdj** [comment]
Merged and NuGet 3.2.6 published
