### ISSUE TITLE
EnumToStringConverter value converter not being applied for BatchUpdate

### ISSUE THREAD

**Issue by marcin2x** [borisdj/EFCore.BulkExtensions#432]
Related to #241.
Issue seems to be back again.
BatchUpdate sets properties with EnumToStringConverter without converting them.
In DB we see "1" instead of converted value.
When reading, it's converted to value proper enum value, but when using Where statement, it doesn't work as db holds "1" instead of "Processing" which is expected enum value.

**Comment by marcin2x** [comment]
Version 3.2.5

**Comment by marcin2x** [comment]
Closing as we've managed to make it work.

**Comment by brandonsmith86** [comment]
> Closing as we've managed to make it work.

What did you do to work around this?  I am having a similar issue with `BulkInsert`.  I've already created an issue (#438).

**Comment by fiegam** [comment]
It is still not working in version 3.2.7. BatchUpdate stores enums values instead of names.

**Comment by villaflaminio** [comment]
It is still not working in version 3.6.6.
