### ISSUE TITLE
What's the state of UTs?

### ISSUE THREAD

**Issue by popojargo** [borisdj/EFCore.BulkExtensions#433]
I was finally able to run the units and saw a bunch of failures. Is that normal? Is there a special way of running the tests?

**Comment by borisdj** [comment]
Regarding the Tests, there are some for Sqlite that are not passing at the moment.

Firstly _BulkRead_() is Not supported for Sqlite but there the test skips it so it does no fail.

Second _InsertWithForeignKeyShadowProperties_() also is not supported in Sqlite.

And for the _BatchTest_ (and its Async version) some queries throws error when Sqlite, for example
This fails:
`var query = context.Items.Where(a => a.ItemId <= 500 && a.Price >= price);`
But this passes
`var query = context.Items.Where(a => a.ItemId <= 500);`

_BulkTestAsync_ also had bug but that one is now fixed.
