### ISSUE TITLE
Does EFCore.BulkExtensions support in-memory database?

### ISSUE THREAD

**Issue by PeterChang2013** [borisdj/EFCore.BulkExtensions#436]
Hi there,

I am working on a unit test project in which we decided to use in-memory database, however when I inject my test database context and use it to call code like this _orderDbContext.BulkInsertAsync(addrList, bulkConfig), the logic will always return to its caller and not continue to run through. 

My question is that does this extensions support in-memory database?

Below is the code that I use to create a in-memory database.

        public OrderDbContext CreateContextForSQLite()
        {

            _connection = new SqliteConnection("DataSource=:memory:");

            _connection.Open();

            var option = new DbContextOptionsBuilder<OrderDbContext>().UseSqlite(_connection).Options;

            var context = new OrderDbContext(option);

            if (context != null)
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }

            return context;
        }

Thanks a bunch for the help in advance. 
Peter

**Comment by borisdj** [comment]
As  stated in the ReadMe:

> Bulk Tests can not have UseInMemoryDb because InMemoryProvider does not support Relational-specific methods.
