### ISSUE TITLE
EnumToStringConverter Not Working with BulkInsert

### ISSUE THREAD

**Issue by brandonsmith86** [borisdj/EFCore.BulkExtensions#438]
This same issue (not necessarily the same cause) was created last year (issue #140).  It seems to be back; using version 3.2.5 with EF Core 3.1. I specify the converter using the pre-defined conversion method documented [here](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#pre-defined-conversions).  Configuration is applied using [IEntityTypeConfiguration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.ientitytypeconfiguration-1?view=efcore-3.1) in same assembly as the context, and calling `modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly())` in`DbContext.OnModelCreating()`. Records are inserted with integer representation of enum.  Changing code back to `SaveChangesAsync` causes everything to work again.

**Comment by brandonsmith86** [comment]
Any update on this?  It's been four weeks since I opened.

**Comment by msioen** [comment]
We're also hitting this issue.
