### ISSUE TITLE
Bulk insert without C# class

### ISSUE THREAD

**Issue by mzgnr** [borisdj/EFCore.BulkExtensions#44]
Is it possible to bulk insert `List<object>` When I know its table name?

**Comment by borisdj** [comment]
Could you elaborate more the question and situation you have.
It is expected that you have EF model of entire database which includes table you want to insert to.
So after calling BulkInsert with List of that model library itself will read table name from EF metadata and do the insert.

**Comment by mzgnr** [comment]
@borisdj I dont want to create Model class for each bulk import types. I just want to give it `List<object>`and table name

**Comment by borisdj** [comment]
Currently you can not set custom table name.
Still It could be added as a additional feature, but I don't see real case scenario for this feature.
Also it is not only Table name that is being read from EF models Relational meta data, but also other DB info like Shema name, Columns names, PK(s), etc.

This is EFCore Extension library, so it goes without saying that you are using EFCore.
In which case you should have Entity objects. If you already have existing DB, you can create Entity models automatically by doing Reverse engineering with `Scaffold-DbContext` command. That way you don't need to create your own object that you wanted to insert, you can just used generated ones.
