### ISSUE TITLE
BulkInsertorUpdate: I would like to update the record only if there is any changes in the record

### ISSUE THREAD

**Issue by msatyabhaskar** [borisdj/EFCore.BulkExtensions#442]
Hi, I am using BulkInsertorUpdate for storing some data to SQL DB. It working well, but my requirement is if the record is already exits in DB then it should update the record only if there are any changes in the values otherwise it should ignore the update also. Can you please confirm if I can achieve this using BulkInsertOrUpdate ?

**Comment by borisdj** [comment]
Not directly.
You could have the same effect with one of two ways.
First is to let it update since if they are the same it won't make a change.
And second way  would be to use BulkRead to load all from the list then omit the same ones and update only ones that do differ.
