### ISSUE TITLE
BulkInsertorUpdateAsync would timeout 3 out of 5 times for very large set of data

### ISSUE THREAD

**Issue by rdasgupta7141** [borisdj/EFCore.BulkExtensions#445]
We are trying to upload large number of data from an excel sheet.<300k.
It works only 2 out of 3 times. It times out. I am guessing some timing out issue. Any ideas what might be up or if there is any setting in BulkConfig setting that we need to set values for. I set timeout =0 but still it does not help. I do see some deadlock in the sql profiler.

**Comment by borisdj** [comment]
You test different BulkConfig settings, specifically
`BatchSize, BulkCopyTimeout, TrackingEntities, WithHoldlock`;
_**`SqlBulkCopyOptions`**_ Flags with one or more options:
`Default, KeepIdentity, CheckConstraints, TableLock, KeepNulls, FireTriggers, UseInternalTransaction`

Also here is more info on DeadLock https://github.com/borisdj/EFCore.BulkExtensions/issues/46
