### ISSUE TITLE
3.2.7 "Cannot update identity column 'Identity Column Id'" bug reintroduced

### ISSUE THREAD

**Issue by schil227** [borisdj/EFCore.BulkExtensions#448]
Opening a separate issue on this to gain traction, but it appears that the bug referenced in https://github.com/borisdj/EFCore.BulkExtensions/issues/403 has cropped up again in 3.2.7. Downgrading my nuget package back it to 3.2.4 resolved the issue.

**Comment by erikdahlin** [comment]
Can confirm, same issue when running 3.2.7 with net5. Downgrading to 3.2.4 worked for me aswell

**Comment by borisdj** [comment]
Fixed with 3.3.1
