### ISSUE TITLE
Received an invalid column length from the bcp client for colid x

### ISSUE THREAD

**Issue by auserx** [borisdj/EFCore.BulkExtensions#449]
I understand this error is thrown when the length of a column is larger than its database length when we do "BulkInsert"

Is there a way to identify the row and column where it fails?

**Comment by borisdj** [comment]
When the value in String field is longer then Max defined in Db, then the exception throw gives detailed info.

It can be tested from the Project id entity `Item` property `Description` would be configured with attribute `[MaxLength(50)]`.
And then add in BulkTest in method RunInsert code
```C#
if (i == 10000) entity.Description = new String('-', 51);```
Throw exception would be:
