### ISSUE TITLE
BulkUpdate updates primary key

### ISSUE THREAD

**Issue by seiroga** [borisdj/EFCore.BulkExtensions#450]
Hi,

I am investigating of transaction log size issues on my DB (we are using SQL Server 2015) and I have found that code below updates also primary key:
```C#

public class Entity1
{
	[Key]
	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
	public Guid ID { get; set; }; //<-- this is clustered primary key

	public string FirstName { get; set; }
	public string LastName { get; set; }
}

// suppose we have some collection of Entity1 instances which exist in DB, so theirs ID property filled with existing id from DB

var bulkConfig = new BulkConfig { PropertiesToInclude = new [] {nameof(Entity1.FirstName), nameof(Entity1.LastName)}, BatchSize = batchSize };
await context.BulkUpdateAsync(entities, bulkConfig);
```
`await context.BulkUpdateAsync(entities, bulkConfig);` generates next SQL statement:
`MERGE [dbo].[Entities1] WITH (HOLDLOCK) AS T USING [dbo].[Entities1Tempd7983123] AS S ON T.[ID] = S.[ID] WHEN MATCHED THEN UPDATE SET T.[ID] = S.[ID], T.[LastName] = S.[LastName], T.[FirstName] = S.[FirstName];`

The problem is that MERGE statement also updates ID key field: **UPDATE SET T.[ID] = S.[ID]**, this update forces clustered primary key index to be recalculated, as a result these changes are put into transaction log.

The question is how can I prohibit to update ID field?

Thanks!

**Comment by borisdj** [comment]
Fixed with 3.3.2
