### ISSUE TITLE
InsertOrUpdate with SetOutputIndentity is returning wrong ids every now and thewn

### ISSUE THREAD

**Issue by rdasgupta7141** [borisdj/EFCore.BulkExtensions#454]
I am doing a bulkInsertOrUpdate and most of the times the ids are not matching with what's in the DB. 
I have set the preserveInsertOrder=true and SetOutputIdentity=true. I do have an alternate key and the primary identityKey.

**Comment by andygjp** [comment]
Hi,

I have the same issue with BulkInsert, although I do not have an alternative key. It seems as if the order of the entities is reversed before insert. I'm using version 3.2.7.

I tried downgrading a few versions, but it didn't help.

The specific overload I'm using is: 
```
public static void BulkInsert<T>(
      this DbContext context,
      IList<T> entities,
      BulkConfig bulkConfig = null,
      Action<Decimal> progress = null)
      where T : class
```

**Comment by borisdj** [comment]
Could you write entire code snipped for test where it would be reproducible.
