### ISSUE TITLE
BulkInsert method won't insert records

### ISSUE THREAD

**Issue by Maxmyd** [borisdj/EFCore.BulkExtensions#458]
Hi,

I'm using BulkInsert method like this
```c#
public void Insert<T>(List<T> values) where T : class
        {
                this.BulkInsert(values, config =>
                {
                    config.SetOutputIdentity = true;
                    config.BulkCopyTimeout = 180;
                });
        }
```
I have new table and new entity type to insert. When I call Insert<T>, app will not go after that line just like there's a caught exception within your package, which will not allow the exception itself to be caught from my code. App is not crashing or breaking, it just continues running.

Table is simple, no FKs or anything.
```sql
[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[JobId] [int] NOT NULL,
	[BatchId] [int] NOT NULL,
	[SkuCode] [uniqueidentifier] NULL,
	[ResultHash] [binary](16) NULL,
	[Result] [nvarchar](4000) NULL,
	[BvName] [nvarchar](500) NULL,
	[BvCode] [nvarchar](50) NULL,
	[BgName] [nvarchar](500) NULL,
	[BgCode] [nvarchar](50) NULL,
	[BfName] [nvarchar](500) NULL,
	[BfCode] [nvarchar](50) NULL,
	[BmName] [nvarchar](500) NULL,
	[BmCode] [nvarchar](50) NULL,
	[CategoryCode] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)
```
Is there a way to understand what is happening there?
Thanks

**Comment by sks2141** [comment]
Hi Maxmyd,

I am assuming that this.BulkInsert resolves to DbContext.BulkInsert(values, bulkConfig). Do you call the Insert<T> wrapped within Db Transaction as : 

`using (var transaction = context.Database.BeginTransaction())
{
    //Insert<>() ...
     transaction.Commit();  
}`

**Comment by Maxmyd** [comment]
Hi,
I don't use explicit transactions as there's no need for the single bulk operation. I've found something else. 

1. Looks like BulkInsert creates temporary tables in database. And in my case records will not copy from temp tables to target table. Also temp tables remain in database.
2. When I set config.SetOutputIdentity = false, records will insert and save. So is this a reason? Why? It's been working for a while and exactly now it is stopped.

**Comment by sks2141** [comment]
Hi Maxmyd,

#1 is correct 
#2 - the documentation mentions that:
"PreserveInsertOrder and SetOutputIdentity have purpose only when PK has Identity (usually int type with AutoIncrement), while if PK is Guid(sequential) created in Application there is no need for them.
Also Tables with Composite Keys have no Identity column so no functionality for them in that case either."

> PreserveInsertOrder makes sure that entites are inserted to Db as they are ordered in entitiesList.
```
However for this to work Id column needs to be set for the proper order.
For example if table already has rows, let's say it has 1000 rows with Id-s (1:1000), and we now want to add 300 more.
Since Id-s are generated in Db we could not set them, they would all be 0 (int default) in list.
But if we want to keep the order as they are ordered in list then those Id-s should be set say 1 to 300 (for BulkInsert).
Here single Id value itself doesn't matter, db will change it to (1001:1300), what matters is their mutual relationship for sorting.
Insertion order is implemented with TOP in conjuction with ORDER BY. stackoverflow:merge-into-insertion-order.
This config should also be used when we have set SetOutputIdentity on Entity containing NotMapped Property. issues/76

When using PreserveInsertOrder with SetOutputIdentity Id value does matter.
If it's BulkInsertOrUpdate method for those that will be updated it has to match Id.
And if we need to sort those for insert(BulkInsert/OrUpdate) and not have conflict with existing Id-s, there are 2 ways:
One is set Id to really high values, order of magnitude 10^10, and another even better setting them to negative values.
So if we have list of 8000, say 3000 for update (they keep the real Id) and 5000 for insert then Id-s could be (-5000:-1).

SetOutputIdentity is useful when BulkInsert is done to multiple related tables, that have Identity column.
After Insert is done to first table, we need Id-s that were generated in Db because they are FK(ForeignKey) in second table.
It is implemented with OUTPUT as part of MERGE Query, so in this case even the Insert is not done directly to TargetTable but to TempTable and then Merged with TargetTable.
When used if PreserveInsertOrder is also set to true Id-s will be updated in entitiesList, and if PreserveInsertOrder is false then entitiesList will be cleared and reloaded.
```

Can you try setting the PreserverInsertOrder to true, when you're setting the SetOutputIdentity to true

**Comment by Maxmyd** [comment]
Yes, your sample makes sense and setting PreserveInsertOrder to true worked for me. 
Thank you very much!

**Comment by sks2141** [comment]
You're welcome !

**Comment by borisdj** [comment]
@sks2141 thx for resolving the issue.
