### ISSUE TITLE
How to use BulkInsertOrUpdateOrDeleteAsync when unit testing with Sqlite

### ISSUE THREAD

**Issue by kljuco** [borisdj/EFCore.BulkExtensions#459]
So the premise is that in the code (because my real database is SQL server) I want to use BulkInsertOrUpdateOrDeleteAsync  but when I run unit tests that have Sqlite as data source this one throws an exception because Sqlite cannot use BulkInsertOrUpdateOrDeleteAsync.

**Comment by borisdj** [comment]
At the moment not supported.
