### ISSUE TITLE
BulkUpdate and BulkUpdateAsync aren't working for decimal and numeric identity columns

### ISSUE THREAD

**Issue by fagnercarvalho** [borisdj/EFCore.BulkExtensions#463]
If I use the `BulkUpdateAsync` or `BulkUpdate` methods with a model where the identity data type is decimal or numeric (allowed data types for identity columns) I get the following error message:

```
'Cannot update identity column 'Id'.'
```

Model with decimal data type (it could be numeric too):
```csharp
[Table("Test")]
public class Test
{
    [Key]
    [Column(TypeName = "decimal")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public decimal Id { get; set; }

    public string Description { get; set; }
}
```

Sample:
```csharp
static async Task Main(string[] _)
{
    var serviceProvider = new ServiceCollection()
         .AddDbContext<Context>(options => options.UseSqlServer("CONNECTION STRING"))
         .BuildServiceProvider();

    var context = serviceProvider.GetService<Context>();

    context.Database.EnsureCreated();

    await context.Test.BatchDeleteAsync();

    var tests = new List<Test>
    {
        new Test { Description = "test 1" },
        new Test { Description = "test 2" }
    };

    await context.BulkInsertAsync<Test>(tests);

    var savedTests = await context.Test.ToListAsync();

    foreach(var savedTest in savedTests)
    {
        savedTest.Description += " updated";
    }

    await context.BulkUpdateAsync(savedTests);
}
```

My solution would be to change the `TableInfo` class to consider the `Decimal` type when getting the identity column name, like this:

```csharp
IdentityColumnName = allProperties.SingleOrDefault(a => a.IsPrimaryKey() 
&& (   a.ClrType.Name.StartsWith("Byte") 
    || a.ClrType.Name.StartsWith("SByte") 
    || a.ClrType.Name.StartsWith("Int") 
    || a.ClrType.Name.StartsWith("UInt")
    || (isSqlServer && a.ClrType.Name.StartsWith("Decimal"))
   ) 
&& !a.ClrType.Name.EndsWith("[]") 
&& a.ValueGenerated == ValueGenerated.OnAdd)?.Name;
```

Since `AUTOINCREMENT` columns in Sqlite only allow integers I'm restricting this to SQL Server.

Let me know if you need any additional details, thanks!

**Comment by RamenTurismo** [comment]
So we're talking about [this line](https://github.com/borisdj/EFCore.BulkExtensions/blob/964d435598e3e5ee0f29bd5d157987d8e790b998/EFCore.BulkExtensions/TableInfo.cs#L153), and it needs some indentation.

I would use `nameof` instead of strings.
But I think something is amiss. There should be a method that returns the list of compatible types for each provider in this case.

Maybe I could propose my first pull request ?

**Comment by borisdj** [comment]
Fixed with latest version.
