### ISSUE TITLE
How to get the related entities wiuth BUlkInsertOrUpdate

### ISSUE THREAD

**Issue by rdasgupta7141** [borisdj/EFCore.BulkExtensions#464]
Is there a way to load the new id and the get the related entities populated as well with BulkInsertOrUpdate...some kind of config such as includeGraph=true? Or even with BulkRead.

**Comment by borisdj** [comment]
On BulkInsert/BulkInsertOrUpdate with with `BulkConfig` `SetOutputIdentity` can be configred.

BulkRead is used for situation when have lagre import to Db and you first wont to load from Db those that already exist in Db by some Unique column(s), either ID as PK or some unique code or combination of several coumns. And then existing ones can be changed, or omit for update or moved to BulkUpdate only.
