### ISSUE TITLE
Project should be multitarget and NuGets should accept a wider range of versions 

### ISSUE THREAD

**Issue by RamenTurismo** [borisdj/EFCore.BulkExtensions#465]
- The project should target `netstandard2.0` alongside `netstandard2.1` and `net5` : It'll be easier to update it in the near future
- The used versions of `Microsoft.EntityFrameworkCore` should target versions above 3.1 (e.g. `3.1.*`, [following documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#floating-versions))

In one of my recent projects, we came across performances issues regarding entity framework core, and saw this project.
The fact that the version is locked made us forced to upgrade to at least `3.1.8`. I think it would be neat to let more margin for other projects that are using this one, by allowing more versions and frameworks.

I can propose a pull request if needed.

**Comment by borisdj** [comment]
I wouldn't' like to make it too complicated for maintainance and also somewaht confusing having several nugets.
So far the practice was some time after full release framework version the library would be updated along with the Nuget (First digit incremented).
For prior versions previous nugets can be installed and used.
In the README is list of EF version and their Nuget numbers (1.x, 2.0 , 2.1, 3.0, 3.1)

Still you can make a PR of your suggestion and give more detail explanation of the proposition, so we can consider it.
