### ISSUE TITLE
WHEN MATCHED AND EXISTS does not work with spatial types

### ISSUE THREAD

**Issue by miloszskalecki** [borisdj/EFCore.BulkExtensions#484]
https://github.com/borisdj/EFCore.BulkExtensions/commit/fde3d32cfd1045b6a444b5f2e064654e1c27db4e#diff-12a2fa739c4c786c3bad3f9208853b485dfd9622f9a81867d0b049c6a0679eb3

this commit expanded MERGE with "AND EXISTS (SELECT ...)" which won't work with spatial types u.e. geography::point 

 q += $" WHEN MATCHED THEN UPDATE SET {GetCommaSeparatedColumns(nonIdentityColumnsNames, "T", "S")}";
                q += $" WHEN MATCHED AND EXISTS (SELECT {GetCommaSeparatedColumns(compareColumnNames, "S")}" +
                     $" EXCEPT SELECT {GetCommaSeparatedColumns(compareColumnNames, "T")})" +
                     $" THEN UPDATE SET {GetCommaSeparatedColumns(updateColumnNames, "T", "S")}";

Sql server will throw errors: "The data type geography cannot be used as an operand to the UNION, INTERSECT or EXCEPT operators because it is not comparable." Could we have some kind of setting to switch above matching optimization off please?

**Comment by borisdj** [comment]
Fixed with latest version

**Comment by miloszskalecki** [comment]
> Fixed with latest version

Lemme give it a spin

**Comment by miloszskalecki** [comment]
Hi Boris,

Great change, however the code only works fine if the spatial property declared on entity is Geography (which is abstract class), i.e. 
class Entity1
{
   public Geography Property1 { get; set; }
}

For number of reasons we have to use Point (which inherits from Geography) in declarations 
class Entity1
{
   public Point Property1 { get; set; }
}

so the special handling of bulk insert/update for the spatial types you guys delivered in last few releases won't work. **To fix it once and for all ** I suggest to change the SqlServerAdapter.cs line 501 from
```
if (propertyType == typeof(Geometry) && isSqlServer)  
```
to

```
if (isSqlServer && (propertyType == typeof(Geometry) || propertyType.IsSubclassOf(typeof(Geometry))))
```
Please let me know what you think

Best Regards
