### ISSUE TITLE
Geometry vs Point

### ISSUE THREAD

**Issue by miloszskalecki** [borisdj/EFCore.BulkExtensions#486]
Hi Boris,

Great release 3.3.8, however the code only works fine if the spatial property declared on entity is Geometry (which is abstract class), i.e.
class Entity1
{
public Geometry Property1 { get; set; }
}

For number of reasons we have to use Point (which inherits from Geometry) in declarations
class Entity1
{
public Point Property1 { get; set; }
}

so the special handling of bulk insert/update for the spatial types you guys delivered in last few releases won't work. To fix it once and for all, I suggest to change the SqlServerAdapter.cs line 501 from

if (propertyType == typeof(Geometry) && isSqlServer)  
to

if (isSqlServer && (propertyType == typeof(Geometry) || propertyType.IsSubclassOf(typeof(Geometry))))
Please let me know what you think

Best Regards

**Comment by borisdj** [comment]
Fixed with 3.3.9
