### ISSUE TITLE
Default value on column of datetime but on model is not nullable

### ISSUE THREAD

**Issue by thamathar** [borisdj/EFCore.BulkExtensions#488]
Hello!

While using the EFCore to insert normally my models works without any problem because on the column I have a default value of  `getdate()` so even if I don't set any value for the property of type DateTime on the model , it will use the default value that the column as AKA `getdate()`

But when using the method BulkInsert of the same list I must require to still set a value, if not, I will get this error:

`SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.`

While on BulkInsert should he still use the default values that are defined for the columns?

**Comment by borisdj** [comment]
Should be fixed now with 3.4.4
DUPE: https://github.com/borisdj/EFCore.BulkExtensions/issues/145
