### ISSUE TITLE
Having column named "index" causes failure beginning with version 3.4.0

### ISSUE THREAD

**Issue by slubowsky** [borisdj/EFCore.BulkExtensions#490]
I have a column (unfortunately) named "Index". In previous versions of EFCore.BulkExtensions this did not cause problems. Begining with version 3.4.0 BulkInsertAsync fails with following error:
`Incorrect syntax near 'Index'. If this is intended as a part of a table hint, A WITH keyword and parenthesis are now required. See SQL Server Books Online for proper syntax.`

Looking at the diffs in https://github.com/borisdj/EFCore.BulkExtensions/commit/7912e2e7cd60365b5d5fee278cb96f46bd67e211 looks like like SQL generated in SqlQueryBuilder GetCommaSeparatedColumnsAndTypes might be to blame. It should probably wrap each column in [brackets] in case name is a problem...

**Comment by borisdj** [comment]
I have just check it, in Test for class Item renamed property 'Description' to 'Index' and is passes, so it not just that.
Columns are already wrapped with brackets [ ] in that method.
Can you check any other specific config you might have there, or try to reproduce it in the Test.
All **_GetCommaS..._** do have brackets [ ], and method _GetCommaSeparatedColumnsAndTypes_ is not even used.
Btw are you using Sql Server or Sqlite?

**Comment by slubowsky** [comment]
Ok sorry, looked too quickly at diff. 
I captured the bad sql in debugger:
`ALTER TABLE [dbo].[#BillTemp83e76a8fOutput] ALTER COLUMN Index int;`

I think its AlterTableColumnsToNullable line 35
`q += $"ALTER TABLE {tableName} ALTER COLUMN {columnName} {columnType}; ";`
no brackets there.

I am using sql server.

**Comment by borisdj** [comment]
Can you check again with v3.4.2

**Comment by slubowsky** [comment]
@borisdj Yes its fixed. Thank you!
