### ISSUE TITLE
BulkInsertOrUpdateAsync example needed?

### ISSUE THREAD

**Issue by metatechsoftware** [borisdj/EFCore.BulkExtensions#492]
I tried the below example but unfortunately, I could not achive my goal:

- The job is done via Quartz (I used the [DisallowConcurrentExecution] attribute in order not to have conflicts)
-  the entity is 

public class CallRecord: Entity<string>
{
public override string Id { get; set; }
public virtual string CallId { get; set; }
public virtual int ServerId { get; set; }
public virtual string CallState { get; set; }
}

- OnModelCreating I added the below line
                       modelBuilder.Entity<CallRecord>(b =>
			{
				b.HasIndex(e => new { e.CallId,e.ServerId }).IsUnique();
			});

- On my Quartz Job every 30 seconds, I tried several versions but received error
                                       PropertiesToIncludeOnCompare = new List<string> 
						{ 
							nameof(CallRecord.CallId),
							nameof(CallRecord.ServerId) 
						}
					// insert
					await _activeCallRepository.BulkInsertOrUpdateActiveCallsAsync(records,bulkConfig);

I appreciate if you can supply a working example... 

Exception:

Violation of PRIMARY KEY constraint 'PK_AppCallRecords'. Cannot insert duplicate key in object 'dbo.AppCallRecords'. The duplicate key value is (92822207-3825078396-743495910@TcomNextoneSBC3-DRC.mydomain.com-onnet_1).
The statement has been terminated.

**Comment by borisdj** [comment]
You did not write entire code snippet for exception to be reproduced, but it is clear that you have PK conflict.
Did you change UpdateByProperties with bulkConfig, also tour PK is string which is not usual.

**Comment by metatechsoftware** [comment]
I chose PK as string to test direct bulkinsertorupdate since my key property is string. I tried several versions but could not achive what I wanted until now. I will try little bit more. 

To clarify, my scenario is below:

The entity has two keys that which should be assumed unique together other then PK. So I would like to update in case my key values together already exists and insert otherwise.

**Comment by borisdj** [comment]
Instead of `PropertiesToIncludeOnCompare` config you should use `UpdateByProperties`.
As said:
> Did you set UpdateByProperties with bulkConfig

Example:
```C#
var bulkConfig = new BulkConfig
{
    UpdateByProperties = new List<string> { nameof(CallRecord.CallId), nameof(CallRecord.ServerId) }
};
await _activeCallRepository.BulkInsertOrUpdateActiveCallsAsync(records,bulkConfig);
```
