### ISSUE TITLE
BulkInsert using TPT (table-per-type)

### ISSUE THREAD

**Issue by patahl** [borisdj/EFCore.BulkExtensions#493]
Is it possible to do a BulkInsert if using TPT?
https://docs.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-type-configuration

I've tried but came up short. We have a base log-table and derived log-tables from that.
Example: 

```
public abstract class Log
    {
        public int LogId { get; set; }
        public int PersonId { get; set; }
        public int RegBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Person Person { get; set; }
    }

 public class LogPersonReport : Log
    {
        public int ReportId { get; set; }
        public int LogPersonReportTypeId { get; set; }

        public virtual Report Report { get; set; }
        public virtual LogPersonReportType LogPersonReportType { get; set; }
    }
```

```
modelBuilder.Entity<Log>().ToTable("Logs");
modelBuilder.Entity<LogPersonReport >().ToTable("LogPersonReports");
```

So with that class I'm able to write:
```
var logPersonReport = new LogPersonReport
{
  PersonId = xx,
  LogPersonReportTypeId = xx,
  RegBy = xx,
  CreatedDate = DateTime.Now
}
```

So, I want to do a BulkInsert with a list of LogPersonReports but I just get errors á la:

> Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> SELECT TOP 0 T.[LogId], T.[CreatedDate], T.[PersonId], T.[RegBy], T.[LogPersonReportTypeTypeId] INTO [dbo].[LogPersonReportsTempddc62ff7] FROM [dbo].[LogPersonReports] AS T LEFT JOIN [dbo].[LogPersonReports] AS Source ON 1 = 0;
> Invalid column name 'CreatedDate'.

I understand why, because CreatedDate is a member of Log but I just don't know how to work around it? I've tried to first BulkInserted the base-entities which works but not when I set negative values for LogId and use SetOutputIdentity = true so that I can use LogId for LogPersonReport. When I use SetOutputIdentity I get errors like LogPersonReportTypeId is invalid even though I specify PropertiesToInclude.

So, I'm stuck and I'm not sure it's supported so I thought I should ask before I try more.

**Comment by borisdj** [comment]
Not out of box, but you could try to configure what you need.
From Bulk perspective you should look it like they are separate entities with a relationship.
So do the _BulkInsert_ into first table **Log** with _OutputIdentity_ and then use it to set PK with other values in list of **LogPersonReport**, after on second BulkInsert set BulkConfig with PropertiesToExclude { nameof(CreatedDate), ... }
Also note that is BulkConfig there is field DestinationTable should you need to manualy set table name for any of the methods.

**Comment by patahl** [comment]
Thanks for the reply.

```
_context.BulkInsert(logPersonReportLogs.Cast<Log>().ToList(), new BulkConfig
{
    SetOutputIdentity = true,
    PropertiesToExclude = logInsertExcludedProperties
});
```

When I use OutputIdentity on the first BulkInsert  I revieve a lot of errors about Invalid column names for derieved Log-classes (a bout 5 derived classes today but will increase later). I can manage to get it to work but then I have to exlude a lot of properties and as soon as we create another derived base class the BulkInsert will fail again until I manually add it to the excluded list which makes it hard to maintain.
I think the problem is that Log is an abstract class.

**Comment by borisdj** [comment]
It should be something like this:
```
var entities = new List<ChangeLog>();
for (int i = 1; i <= 1000; i++)
{
  // load data into list
}

var bulkConfigBase = new BulkConfig
{
    SetOutputIdentity = true,
    CustomDestinationTableName = nameof(Log),
    PropertiesToExclude = new List<string> { nameof(LogPersonReport.ReportId), nameof(LogPersonReport.LogPersonReportTypeId) }
};
var bulkConfig = new BulkConfig
{
    CustomDestinationTableName = nameof(Log),
    PropertiesToExclude = new List<string> { nameof(LogPersonReport.PersonId), nameof(LogPersonReport.RegBy), nameof(LogPersonReport.CreatedDate) }
};
context.BulkInsert(entities, bulkConfig);
```

However I see now that TPT is only supported from EF 5.0.
Lib is still using EF 3.1, although it probably can work for 5.0 already.
Still I do plan to update it soon, but until then I can't test this.

**Comment by patahl** [comment]
Yes, that is the workaround to get it to work but like I said, at the moment we have 5 derived log-classes with different properties and they will all have to be excluded which makes maintaining the code a hazzle, especially when we'll add a new log-class.
Shouldn't PropertiesToInclude be a better option? But atm it still includes not included properties.
I think at the moment we will use EF for our maintaining jobs containing TPT-tables and hopefully this will be handled in the future! Thanks for your support and awesome library!

**Comment by borisdj** [comment]
EF 5 is now supported, and partially TPT, use v5.0.2.
Example in previous post is updated on how to make it work.
Also config are made with _PropertiesToInclude_.

**Comment by aceniko** [comment]
public abstract class Log
{
    public int LogId { get; set; }
    public int PersonId { get; set; }
    public int RegBy { get; set; }
    public DateTime CreatedDate { get; set; }
}

public class LogPersonReport : Log
{
    public int ReportId { get; set; }
    public int LogPersonReportTypeId { get; set; }
}

public class LogAnimalReport : Log
{
    public int ReportId { get; set; }
    public int LogAnimalReportTypeId { get; set; }
}

The LogAnimalReport class also has a ReportId property. When performing a BulkInsert operation, I encounter the following error:

System.ArgumentException: An item with the same key has already been added. Key: ReportId

The problem seems to be located within the TableInfo.LoadData method. If I skip the following code block, the BulkInsert operation succeeds:


if (entityType.IsAbstract())
{
    foreach (var derivedType in entityType.GetDirectlyDerivedTypes())
    {
        foreach (var derivedProperty in derivedType.GetProperties())
        {
            if (!allProperties.Contains(derivedProperty))
            {
                allProperties.Add(derivedProperty);
            }
        }
    }
}

Do you have any ideas on how to resolve this issue?
