### ISSUE TITLE
BulkUpdate generating one query per entity

### ISSUE THREAD

**Issue by kg** [borisdj/EFCore.BulkExtensions#496]
Hi, I'm calling ```BulkUpdate``` with a list of entity instances in an SQLite database, and while BulkExtensions is properly updating the instances, it's generating and executing one entire SQL query per entity. I can't figure out why it would be doing this. The table schema (generated by EF core) is pretty simple:

```sql
CREATE TABLE Operations (
    UniqueId            INTEGER NOT NULL
                                CONSTRAINT PK_Operations PRIMARY KEY AUTOINCREMENT,
    PlayerId            INTEGER NOT NULL,
    OperationId         TEXT,
    AccumulatedProgress TEXT    NOT NULL,
    StartedWhen         TEXT,
    IsComplete          INTEGER NOT NULL
);
```

and the generated entity model from EF core is also simple:
```C#
b.Property<long>("UniqueId")
  .ValueGeneratedOnAdd()
  .HasColumnType("INTEGER");
```

The queries look like this:
```sql
UPDATE "Operations" SET "StartedWhen" = @p0
WHERE "UniqueId" = @p1;
SELECT changes();
UPDATE "Operations" SET "StartedWhen" = @p0
WHERE "UniqueId" = @p1;
SELECT changes();
UPDATE "Operations" SET "StartedWhen" = @p0
WHERE "UniqueId" = @p1;
SELECT changes();
```

I would have expected it to be able to batch these updates by feeding a list of (id, value) pairs into the query and doing a single update. Is this just an unavoidable constraint of how things work such that an ```UPDATE``` is required per item? Is this a limitation that only applies to SQLite, so I don't need to worry about it when running against a pgsql or mssql server in production/staging?

P.S. When attempting to make this stuff work, I constantly get mystery KeyNotFound exceptions from various bits of code in this library that feed column/property names into dictionaries without doing checks. I have yet to figure out how to use ```PropertiesToExclude``` or ```UpdateByProperties``` without just getting exceptions, but thankfully it seems like I don't need them... It would be cool if at some point BulkExtensions was updated to check the configuration to make sure the exclude/updateby settings you're passing in make sense so it's not just a mystery exception that's hard to debug.

**Comment by kg** [comment]
EDIT:
Realized after messing around some more (naturally right after I hit submit on this issue...) that these queries appear to be coming from Entity Framework even though I've already used BulkUpdate to update the records. Do I need to stop using Entity Framework's other APIs entirely for this to work correctly? I haven't had this problem with BulkInsert.

**Comment by borisdj** [comment]
Bulk ops does send entire list to Db, not one by one, but you already figured that.
You should load entities for update with '.AsNoTracking()' so that EF does not updated them one by one.

Currently library supports only SqlServer (using SqlBulkCopy) and Sqlite (with raw sql), more info the README.
PropertiesList from BulkConfig do have name validation in the latest versions.

**Comment by kg** [comment]
Thanks! Appreciate the help.

**Comment by borisdj** [comment]
You are welcome.
