### ISSUE TITLE
Problem with BulkRead and match on multiple columns

### ISSUE THREAD

**Issue by flensrocker** [borisdj/EFCore.BulkExtensions#498]
First: Thank you for your great work!

My usecase:
I have two systems with the same kind of entity/table like:
```
public class EventEntity
{
  public Guid Id { get; set; }
  public string Source { get; set; }
  public Guid SourceId { get; set; }
  public string Data { get; set; }
}
```
"system-1" is storing events in its table with `Source = "system-1"`, the other system is storing events with `Source = "system-2"` in its table.

What I like to do is to synchronize these tables, which means basically:
- "system-1" pulls records from "system-2"'s table (with some kind of filter to get mostly only "new" ones, fields are omitted here)
- Since some of these records may be already present in "system-1"'s table, only non existent should be inserted
- Existing records must not be updated

What I try to do is a `BulkRead` with a `BulkConfig` with
```
UpdateByProperties = new List<string>
{
  "Source",
  "SourceId",
}
```
My entity-list contains `EventEntity` with only `Source` and `SourceId` filled.

After the `BulkRead` none of the other fields (`Id` and `Data`) are filled even if they should, so I can't identify, which records already exist, so I can remove them from the list to do a `BulkInsert`.

I also tried `PropertiesToIncludeOnUpdate = new List<string> { "" }` but that raises an exception that the property "" can not be found in the entity.

It only works, if I fill the `Id` with the right value (e.g. I use the `SourceId` of the other system as `Id` on the local system - but that conflicts if both systems generate the same `Id`) and use no `BulkConfig` at all.

What am I missing?

**Comment by borisdj** [comment]
There was an error with {` "" }` that is now fixed with latest version.
Code should be something like this:
```C#
var bulkConfigRead = new BulkConfig
{
	CustomDestinationTableName = "system-2",
	UpdateByProperties = new List<string> { nameof(EventEntity.SourceId) },
};
context.BulkRead(entityList, bulkConfigRead);

foreach (var entity in entityList)
{
	entity.Id = Guid.NewGuid(); // If Guid is generated in Db do not set it here
	entity.Source = "system-1";
}

var bulkConfigInsert = new BulkConfig
{
	CustomDestinationTableName = "system-1",
	UpdateByProperties = new List<string> { nameof(EventEntity.SourceId) },
	PropertiesToIncludeOnUpdate = new List<string> { "" },
	//PropertiesToExclude = new List<string> { nameof(EventEntity.Id) }, // For option when Id DbGenerated if Empty Guid not auto ommited try manual exclude
};
context.BulkInsertOrUpdate(entityList, bulkConfigInsert);
```

**Comment by flensrocker** [comment]
Thank you! In my minimal example this works now.

Now I have to dig through my real project, why it doesn't work there. But that's my problem... 😊

**Comment by borisdj** [comment]
Glad you sold it, and good luck with solving it also the project.

**Comment by flensrocker** [comment]
I found it (but I don't understand it)...

I use a static `BulkConfig` instance for `BulkRead`, because I only set `UpdateByProperties` and this list will never change.

If I use a local `BulkConfig` directly created before the `BulkRead` everything works as expected - even with version 2.4.1 (which I need for some old .Net 4.6.1/EF Core 2.1 projects). That's a bit surprising... 😎

I will try to reproduce this with my minimal project.

**Comment by flensrocker** [comment]
It seems to be a problem if I use the same `BulkConfig` object again.

On the first `BulkRead` everything works, if I do a second `BulkRead` on a new `DbContext` the existing records are not read.

**Comment by borisdj** [comment]
Create new BulkConfig. also you could make a method that copies relevant properties into new one.

**Comment by flensrocker** [comment]
Yes, I will create always a new BulkConfig, for me this issue is solved.

Thank you!
