### ISSUE TITLE
Columns with spaces cause BulkInsertOrUpdate to fail

### ISSUE THREAD

**Issue by gm112** [borisdj/EFCore.BulkExtensions#5]
**How to reproduce: ** Create a table that has a column name with spaces in it. Then, try to run a query.

This can actually be easily fixed by detecting whitespace in the Column names and wrapping them with brackets [] when whitespace is detected. 

NOTE: This does not occur on a mere BulkInsert, but a BulkInsertOrUpdate call.

**Comment by borisdj** [comment]
I have just updated repository with this fix.
Nuget library is not yet published, but you can test it from code first...

**Comment by gm112** [comment]
I can confirm that your fixed seems to work! Nice job

**Comment by borisdj** [comment]
Nuget 1.0.4 published, closing this issue.

**Comment by borisdj** [comment]
NuGet 1.0.4 published, closing this issue.
