### ISSUE TITLE
BulkDelete throws NullReferenceException in 2.0.9

### ISSUE THREAD

**Issue by kendtimothy** [borisdj/EFCore.BulkExtensions#50]
After upgrading from 2.0.8 to 2.0.9, I started getting NullReferenceException from some of my tests which use the BulkDelete functionalities. It works fine when I reverted the package back to 2.0.8.

**Exception:**
System.NullReferenceException: 'Object reference not set to an instance of an object.'

**Stack trace:**
>    at EFCore.BulkExtensions.TableInfo.<LoadData>b__65_2[T](IProperty a)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Boolean loadOnlyPKColumn)
>    at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
>    at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
>    at EFCore.BulkExtensions.DbContextBulkExtensions.BulkDelete[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
>    at MyService.SqlService.BulkCopy.SqlBulkCopyService`1.BulkDelete[TEntity](Expression`1 deleteFilter)
>    at MyService.PerfTests.Search.SearchLiveDbFixture..ctor()

Here's my service wrapper which uses the BulkDelete functionality:
```
public void BulkDelete<TEntity>(
    Expression<Func<TEntity, bool>> deleteFilter)
    where TEntity : class
{
    var dbSet = _dbContext.Set<TEntity>();
    IQueryable<TEntity> entitiesToDelete;
    if (deleteFilter != null)
    {
        entitiesToDelete = dbSet.Where(deleteFilter).AsNoTracking();
    }
    else
    {
        entitiesToDelete = dbSet.AsNoTracking();
    }

    _dbContext.BulkDelete(entitiesToDelete.ToList());
}
```

**Additional info:**
- _dbcontext.Model doesn't seem to be null
- entitiesToDelete is not null, the exception is thrown whether the list is empty / not

Any ideas?

**Comment by borisdj** [comment]
Fixed with Nuget version 2.1.0. but this v. is now using EF Core 2.1
So either upgrade to EF 2.1 of use Nuget 2.0.8.
