### ISSUE TITLE
BulkInsert raises exception "No parameterless constructor defined for type 'System.String'" if table contains strings with default value defined.

### ISSUE THREAD

**Issue by hutterd** [borisdj/EFCore.BulkExtensions#500]
Thanks for your excellent work.

With the upgrade from 3.4.2 to 3.4.8 (together with SqLite) I get now an exception  "No parameterless constructor defined for type 'System.String'." System.MissingMethodException.

This happens in the case, where the table definition contains string data with a default value configured.

The exception occurs  in TableInfo.cs, line 196, var instance = Activator.CreateInstance(propertyType);
```
            foreach (var propertyWithDefaultValue in propertiesWithDefaultValues)
            {
                var propertyType = propertyWithDefaultValue.ClrType;
                var instance = Activator.CreateInstance(propertyType);
```

**Comment by borisdj** [comment]
Fixed with latest version.
