### ISSUE TITLE
BulkInsert and BulkInsertAsync bypass sql Foreign key validation

### ISSUE THREAD

**Issue by KimberlyPhan** [borisdj/EFCore.BulkExtensions#502]
We're seeing BulkInsert and BulkInsertAsync bypass sql Foreign key validation, the bad data somehow is inserted there.  
When we go to the db and try to edit the inserted rows, resave the row, it will validate the FK and won't let you save. 
When we add one record at a time, the bad data is not inserted, so we know that this is a bug in bulk insert, not our db set up.
When we slightly edit the test to violate PK, then the test will pass as expected... 

Test:
public async Task Given_Sentiment_AlreadyExisted_When_Replace_FailInsert_ViolateFK_Then_Throws_NotDeleted_NotCommited()
        {
            // Given
            var setup = SetupInteractionAndTranscript(2, 2);

            IUnitOfWork unitOfWork = setup.serviceProvider.GetService<IUnitOfWork>();
            var sentiments = new List<Sentiment>();
            setup.segmentTranscripts.ForEach(s => sentiments.Add(GetValidSentiment(s, 1234)));

            await unitOfWork.SentimentRepository.BulkInsertOrReplaceAsync(sentiments);
            var sentimentFromDB = unitOfWork.SentimentRepository.Find(s => setup.interactions.Select(i => i.Id).ToList().Contains(s.InteractionId.Value)).ToList();
            Assert.Equal(4, sentimentFromDB.Count());
            sentimentFromDB.ForEach(s => Assert.Equal(1234, s.Offset));

            // When
            sentiments.RemoveAt(0);
            sentiments.ForEach(s => s.Offset = 5436);
            // deliberately cause a FK violation
            sentiments.Last().InteractionId = -33;

            unitOfWork = setup.serviceProvider.GetService<IUnitOfWork>();

            // EXPECT to throw here but it isn't because BULK INSERT has a bug where FK violation was not checked and data was inserted in to DB.
            var exception = await Assert.ThrowsAsync<Microsoft.Data.SqlClient.SqlException>(() => unitOfWork.SentimentRepository.BulkInsertOrReplaceAsync(sentiments));
            unitOfWork.Complete();

            // Then
            unitOfWork = setup.serviceProvider.GetService<IUnitOfWork>();
            sentimentFromDB = unitOfWork.SentimentRepository.Find(s => setup.interactions.Select(i => i.Id).ToList().Contains(s.InteractionId.Value)).ToList();
            Assert.Equal(4, sentimentFromDB.Count());
            sentimentFromDB.ForEach(s => Assert.Equal(1234, s.Offset));
        }

**Comment by borisdj** [comment]
In _BulkConfig_ set `SqlBulkCopyOptions` enum with **_CheckConstraints_** flag
```
var bulkConfig = new BulkConfig { SqlBulkCopyOptions = SqlBulkCopyOptions.CheckConstraints } );
await unitOfWork.SentimentRepository.BulkInsertOrReplaceAsync(sentiments, bulkConfig);
```
