### ISSUE TITLE
Getting SqlException when using SQL Always Encrypted starting with version 3.4.1

### ISSUE THREAD

**Issue by taxx** [borisdj/EFCore.BulkExtensions#503]
Hi,

I am using your awesome library to import data to a table on a regular basis in a .NET Core console app.
In a recent maintenance of the application I updated EFCore.BulkExtensions from 3.3.1 to 3.4.9 and started getting SqlException when calling `BulkInsertOrUpdateAsync`.

I am using SQL Server in Azure with "Always Encrypted" enabled on two columns.
One of them being primary key _('ColumnName' below)_, both using "Deterministic" type of encryption.

Full exception _(with changed column and database name)_:
`
Microsoft.Data.SqlClient.SqlException: 'Encryption scheme mismatch for columns/variables 'ColumnName'. The encryption scheme for the columns/variables is (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK1', column_encryption_key_database_name = 'DatabaseName') and the expression near line '1' expects it to be PLAINTEXT.'
`

Application uses .NET 5.0. Here is a partial sample code of where the exception happen:
```csharp
 var bulkConfig = new BulkConfig
 {
     BulkCopyTimeout = 0,
 };

 context.BulkInsertOrUpdateAsync(dataToAdd, bulkConfig, null, cancellationToken);
```
`dataToAdd` being a list containing only one item to simply troubleshooting _(and this item doesn't exist in the table from before)_.

I've tested all the versions from 3.3.1 to latest 3.4.9 _(as of writing)_ to try to track down when it stopped working.
The version I start getting this error is 3.4.1, until that one it worked without issues.

Tried figuring out what commit caused this issue, but having problems mapping Nuget version number with code.

**Comment by borisdj** [comment]
3.4.10 and 3.4.1 were published between 2021-03-15 and 2021-03-17 in which period there were several commits, so you could take a look at those.
Maybe it's easier to try make a test and reproduce the issue on the latest version, or load lib. source code into your project and debug it directly.

**Comment by taxx** [comment]
Did some debugging as suggested and I found the cause of the error I was having.

It's this [commit](https://github.com/borisdj/EFCore.BulkExtensions/commit/a150819ab5b0746a73fa097c53f332d88d96f773) that changed the `PreserveInsertOrder` to default to `true`.

Tried setting `PreserveInsertOrder` to `false` in my `BulkConfig` and using latest version of your package (3.5.0) and it now works with SQL Always Encrypted on.

Saved the two queries (true vs false) to analyze further, but for now I am happy.
If you want you could add something about this somewhere if someone else encounters the same issue :-)

**Comment by borisdj** [comment]
_PreserveInsertOrder_ was changed to default True, and it temporary sets Identity column to negative values -N to -1 (it is explained in the ReadMe)
But I don't see hos that makes this error.
If you can debug it further to find what exactly is the cause.
Also I did not yet upgrade lib. to use directly .Net5 but plan to do it soon.

**Comment by borisdj** [comment]
Also try with version 3.5.1, I have made some change, but that probably wont have any affect on the issue you had.

**Comment by borisdj** [comment]
Give it a go with latest v5.0.0, it is upgraded to support .Net 5
