### ISSUE TITLE
BulkInsertOrUpdate on Table with PrimaryKey that is not an Identity column throws SqlException "Cannot insert the value NULL into column..."

### ISSUE THREAD

**Issue by stevekirks** [borisdj/EFCore.BulkExtensions#505]
When calling the method BulkInsertOrUpdate() on a table with a PrimaryKey that is not an Identity column, the MERGE statement throws a SqlException with message "Cannot insert the value NULL into column '{PrimaryKeyColumnName}', table '{TableName}'; column does not allow nulls. UPDATE fails."

Steps to reproduce:
The table SQL DDL:
```
CREATE TABLE [dbo].[test_table_1](
	[Id] INT NOT NULL,
	[Notes] [varchar](50) NULL,
    CONSTRAINT [PK_test_table_1] PRIMARY KEY ([Id])
);
```
The EF class:
```
[Table("test_table_1")]
public class TestTable1Model
{
    [Key]
    public int Id { get; set; }
    public string Notes { get; set; }
}
```
The test code:
```
var toAddOrUpdate = new List<TestTable1Model>
{
	new TestTable1Model
	{
		Id = 1,
		Notes = note1
	}
};
await ctx.BulkInsertOrUpdateAsync(toAddOrUpdate);
```

This throws the SqlException "Cannot insert the value NULL into column 'Id', table 'targetdb.dbo.test_table_1'; column does not allow nulls. UPDATE fails.".

It's because the MERGE statement that is generated is this:
```
MERGE [dbo].[test_table_1] WITH (HOLDLOCK) AS T USING [dbo].[test_table_1Temp84571cc2] AS S ON T.[Id] = S.[Id] 
WHEN NOT MATCHED BY TARGET THEN INSERT ([Notes]) VALUES (S.[Notes]) 
WHEN MATCHED THEN UPDATE SET T.[Notes] = S.[Notes];
```
When it should include the Id in the INSERT. Thatis:
```
MERGE [dbo].[test_table_1] WITH (HOLDLOCK) AS T USING [dbo].[test_table_1Temp84571cc2] AS S ON T.[Id] = S.[Id] 
WHEN NOT MATCHED BY TARGET THEN INSERT ([Id], [Notes]) VALUES (S.[Id], S.[Notes]) 
WHEN MATCHED THEN UPDATE SET T.[Notes] = S.[Notes];
```

Tested using: SQL Server 2019, EF 3.1 and 5, and EFCore.BulkExtensions 3.1 and 3.4.9

I notice there is a `SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity` setting, but when set the test also fails as it tries to turn IDENTITY OFF on a table that doesn't have an IDENTITY on it.

If this is a bug then I think to fix, the MERGE statement should include PrimaryKey columns in the INSERT section if those columns are not Identity columns.

Thanks

**Comment by borisdj** [comment]
I can't reproduce the issue directly.
However this error does come if Table in Db is set not to have Identity but that is not defined on Model in context.
Since column name 'Id' is by default considered to be PK and Identity, you need explicitly to define it with NoIdentity:
`modelBuilder.Entity<TestTable1Model>().Property(et => et.Id).ValueGeneratedNever();`

**Comment by stevekirks** [comment]
Thanks Boris! You're right, the table id column did not have the ValueGeneratedNever() config setting applied. Sorry for thinking this was an issue with this library, thanks for your help.

**Comment by borisdj** [comment]
Glad to help and that you solved it.
