### ISSUE TITLE
BatchUpdate effect other columns

### ISSUE THREAD

**Issue by skywshing** [borisdj/EFCore.BulkExtensions#506]
I have an entity named "Member"

`public class Member{
    public virtual MemberState State { get; set; }
   public virtual MemberApiState ApiState { get; set; }
}`

`public enum MemberState {
   Close=0,
   Open
}`

`public enum MemberApiState{
   Close=0,
   Open
}`

If I use BatchUpdateAsync to update member's State, Member's ApiState has been also set to it's default value.
`public async Task UpdateStateAsync(List<int> ids, MemberState state)
 {
        var query = _memberRepository .Where(o => ids.Contains(o.Id));
         await query.BatchUpdateAsync(o=>new Member{State = state});
}`

**Comment by borisdj** [comment]
I have just tested this and it works correctly.
For model:
```C#
public enum MemberState { Close = 0, Open }
public enum MemberApiState { Close = 0, Open }

public class Member
{
	public int Id { get; set; }
	public virtual MemberState State { get; set; }
	public virtual MemberApiState ApiState { get; set; }
}
```
this Test:
```C#
[Fact]
public async Task BatchMemberTestAsync()
{
	using (var context = new TestContext(ContextUtil.GetOptions()))
	{
		var ids = new List<int> { 1, 2 };
		MemberState state = MemberState.Close;
		var query = context.Members.Where(a => ids.Contains(a.Id));
		await query.BatchUpdateAsync(a => new Member { State = state });
	}
}
```
generates Sql (cached in Profiler):
```sql
--DECLARE @param_0 int; SET @param_0 = 0;
UPDATE m SET  [m].[State] = @param_0 
FROM [Member] AS [m]
WHERE [m].[Id] IN (1, 2)
```
