### ISSUE TITLE
Bulkread returns Entities with all properties not set

### ISSUE THREAD

**Issue by yotthani** [borisdj/EFCore.BulkExtensions#507]
For me in all versions after 3.5.0 (3.5.1, 3.5.2) ..
"Example:
var items = cdmids.Select(a => new CDMSheetData { Id = a }).Distinct().ToList();
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(CDMSheetData.Id) } };
context.BulkRead<CDMSheetData>(items, bulkConfig);"

returns a List with the right amount of items, but all item Properties are set to default values and not loaded from db.
When i switch back to 3.5.0 all works again as usual.

**Comment by borisdj** [comment]
Fixed with 3.5.3

**Comment by yotthani** [comment]
thx
