### ISSUE TITLE
BulkUpdate: Owned types are not updated anymore

### ISSUE THREAD

**Issue by langebangen** [borisdj/EFCore.BulkExtensions#509]
Hi.

Owned types are not updated anymore when using BulkUpdate API. However, it works with BulkInsert.

I have upgraded to .NET 5. This has worked previously so I am not sure if this issue is related to .NET 5 or this project.

The following fix in `TableInfo` (Line 404) fixes the issue, but I am not sure if this is the correct way to fix it.

```diff
if (doAddProperty)
{
    string columnName = ownedEntityPropertyNameColumnNameDict[ownedProperty.Name];
    PropertyColumnNamesDict.Add(ownedPropertyFullName, columnName);
    OutputPropertyColumnNamesDict.Add(ownedPropertyFullName, columnName);
+   PropertyColumnNamesUpdateDict.Add(ownedPropertyFullName, columnName);
}

```

**Comment by borisdj** [comment]
It was a problem in the lib, and you've already made a fix.
Published v3.5.8
