### ISSUE TITLE
BulkInsert Performance Degradation 

### ISSUE THREAD

**Issue by sigdave** [borisdj/EFCore.BulkExtensions#511]
Using the following code to insert about 2 million records into a database table.

var bulkConfig = new BulkConfig { PreserveInsertOrder = false, SetOutputIdentity = false, BatchSize = BATCH_SAVE_SIZE };
using var transaction = Database.BeginTransaction();
this.BulkInsert(entities, bulkConfig);
transaction.Commit();

We're currently on version 3.1.4 but upgrading to any newer versions of the extension slows the insert time down dramatically.

**Comment by borisdj** [comment]
How long exactly in seconds do they last, meaning what is the difference.
And secondly can you confirm that the degradation  is right after 3.1.4, did you test with 3.1.5 as well and found it to be slower ?

**Comment by sigdave** [comment]
Saves go from about 30seconds to 2minutes.
I'm working on putting together something to check which version causes the issue.

**Comment by borisdj** [comment]
Also are you using Ef Core 3, and initially upgraded Bulk to v3.5.8.
Or you are using now EF Core 5 and tried with the latest version 5.0.2.

**Comment by sigdave** [comment]
Yes, we were using EF Core 3.1 and upgraded from 3.1.4 to 3.5.8. This is when we noticed the performance degradation. We then upgraded to EF Core 5 and upgraded to 5.0.2 and saw the same slowness. We dropped back down to 3.1.4 and started to see old performance (30 seconds).

**Comment by borisdj** [comment]
Try to find Version when the performance issue started.
There were 40 version in between and with binary(half-interval) search it could be isolated in several test attempts.

**Comment by borisdj** [comment]
Found the change.
On version [3.2.0](https://github.com/borisdj/EFCore.BulkExtensions/commit/4e3744849b665065e07c32b3b52e6dde18481885) FastMember dependency was removed.

Reason was to simplify and and uniform method since it couldn't be used for certain Entity models that had specific configuration in which case DataTables were used.
https://github.com/borisdj/EFCore.BulkExtensions/blob/23b047e3a45780c91c6000d4613aefe27baa8209/EFCore.BulkExtensions/SqlBulkOperation.cs#L70-L75

And now DataTable is used always but it is somewhat slower because of reading properties values with reflection.

I'll check if that segment of preparing values can be optimized using internal FastProperty class that was later added.
If it can't than will consider returning FastMember.

**Comment by borisdj** [comment]
I've done some optimization.
Try with v3.6.1

**Comment by sigdave** [comment]
Optimizations didn't seem to improve the problem. Will roll out code back to use 3.1.6 (which I confirmed runs fine).

**Comment by borisdj** [comment]
I have tested it after applying the change and 2 mil rows gets inserted in 40 s.
Here is test example:
```C#
private void RunInsert2mIL(bool isBulkOperation)
{
  using (var context = new TestContext(ContextUtil.GetOptions()))
  {
    var entities = new List<Item>();
    var dt = DateTime.Now;
    for (int i = 1; i <= 2000000; i++)
    {
      var entity = new Item
      {
        ItemId = 0,
        Name = "name " + i,
        Description = "info " + i,
        Quantity = i % 10,
        Price = ((decimal)i) / 10,
        TimeUpdated = dt
      };
      entities.Add(entity);
    }

    using (var transaction = context.Database.BeginTransaction())
    {
      var bulkConfig = new BulkConfig
      {
        BatchSize = 10000,
        PreserveInsertOrder = false,
        SetOutputIdentity = false,
      };
      context.BulkInsert(entities, bulkConfig);

      transaction.Commit();
    }
  }
}
```

**Comment by sigdave** [comment]
For version 3.6.1 my entire process took 11min 50sec. I'm generating tons of records and saving them of to various tables. Drilling into a specific save I can see 2min 2sec for 5,377,484 records.

I rolled back to 3.1.6 and my entire process shifted to 8min 44secs (almost all the time difference in the BulkInsert calls). Drilling into the same save for 5,377,484 records, I can see that call took 1min 24seconds.

**Comment by sigdave** [comment]
I'm going to rerun using version 3.2.0 to confirm that's where the time breaks.

**Comment by borisdj** [comment]
Try running the test from previous post using nuget 3.1.6 and then with 3.6.1, and compare timing.

**Comment by sigdave** [comment]
Using the test code provided above.
Version 3.1.6 took 9.5 seconds and version 3.6.1 took 21.3 seconds.

My test object looked like this:

`public class Output
    {
        public long ID { get; set; }

        public Guid Guid1 { get; set; }
        public int Int1 { get; set; }
        public long Long1 { get; set; }
        public bool Bool1 { get; set; }
        [Column(TypeName = "decimal(12,8)")]
        public decimal? Decimal1 { get; set; }
        public string Str1 { get; set; }
        public Guid? NGuid1 { get; set; }
        public int? NInt1 { get; set; }
        public long? NLong1 { get; set; }
        public bool? NBool1 { get; set; }
        [Column(TypeName = "decimal(12,8)")]
        public decimal? NDecimal1 { get; set; }
    }`

**Comment by borisdj** [comment]
Can you write entire test, analog to the RunInsert2M, where those timings would be reproducible.

**Comment by sigdave** [comment]
`using System;
using System.Collections.Generic;
using System.Diagnostics;
using BulkInsertPerf.Lib.Context;
using BulkInsertPerf.Lib.Entities;
using EFCore.BulkExtensions;

namespace BulkInsertPerf
{
    public class App
    {
        private readonly TestContext _db;

        public App(TestContext db)
        {
            _db = db;
        }

        public void Run(string[] args)
        {
            try
            {
                // Generate Bogus data
                var entities = new List<Output>();
                for (var i = 1; i <= 2000000; i++)
                {
                    var entity = new Output
                    {
                        ID = 0,
                        Guid1 = Guid.NewGuid(),
                        Int1 = i,
                        Long1 = i,
                        Bool1 = true,
                        Decimal1 = 1.2m,
                        Str1 = "test" + i
                    };
                    entities.Add(entity);
                }

                // Make call
                var sw = new Stopwatch();
                sw.Start();
                using (var transaction = _db.Database.BeginTransaction())
                {
                    var bulkConfig = new BulkConfig
                    {
                        BatchSize = 10000,
                        PreserveInsertOrder = false,
                        SetOutputIdentity = false,
                    };
                    _db.BulkInsert(entities, bulkConfig);

                    transaction.Commit();
                }
                sw.Stop();

                // Notify of call
                Console.WriteLine($"Process took: {sw.Elapsed.TotalSeconds}");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
}`

**Comment by sigdave** [comment]
Starting the app looks like this

public static void Main(string[] args)
        {
            var services = ConfigureServices();
            var serviceProvider = services.BuildServiceProvider();

            // calls the Run method in App, which is replacing Main
            try
            {
                Console.WriteLine("Running...");
                serviceProvider.GetService<App>().Run(args);
                Console.WriteLine("Process complete.");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }

        private static IServiceCollection ConfigureServices()
        {
            IServiceCollection services = new ServiceCollection();

            var config = LoadConfiguration();
            services.AddSingleton(config);

            // required to run the application
            services.AddTransient<App>();

            // dependency injections
            services.AddDbContext<TestContext>(options =>
                options.UseSqlServer(config.GetConnectionString("TestContext"))
                    .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking));

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            return services;
        }

**Comment by borisdj** [comment]
I've just run your test on my computer and the results are:
-with v3.1.6 duration 22 s
-with v3.6.1 duration 25 s
Not significant difference.
Interestingly I'am not sure how you mange to have it under 10 s with first version, is it some big server?

**Comment by sigdave** [comment]
I ran the test a few more times and consistently get under 10seconds for version 3.1.6.

v3.1.4 - v3.1.6 ~9.5seconds
v3.2.0 ~43seconds
v3.6.1 ~21seconds

The code is running locally: Windows 10, intel(r) xeon(r) cpu-e3-1245 v5 @ 3.50GHz, 32GB RAM.
Sql Server is hosted: Windows Server 2019 Standard (10.0)
I'll get the sql server specs shortly.

**Comment by borisdj** [comment]
Looks like optimization did help, from 43s with v3.2.0 to 21s with 3.6.1
However obviously it's not completely equal to when using FastMember v3.1.6
And it seems that the stronger (cpu/RAM/Disk) is, the difference is bigger, since on my machine (i7-10510U/16GB, 512SSD) it's only 10% while on your it is double.

**Comment by sigdave** [comment]
Yes optimization helped in 3.6.1, but we'll likely stay on 3.1.6 for the performance boost.

**Comment by borisdj** [comment]
I'll consider later if it is worth returning FastMember dependency which usage would be configurable for versions 5+
