### ISSUE TITLE
Updates the table with the same data

### ISSUE THREAD

**Issue by zabihrajaie** [borisdj/EFCore.BulkExtensions#512]
If the entity values were the same as the table values, The update operation is performed again

**Comment by borisdj** [comment]
How did you check this, and can you write code snippet for to test it.

**Comment by zabihrajaie** [comment]
I have a field called CurrentVersion in the table that increases with each update by sql trigger.

![c#](https://user-images.githubusercontent.com/50627937/113680279-e9d23500-96d5-11eb-90e6-19b111c8cc29.jpg)
![sql](https://user-images.githubusercontent.com/50627937/113680304-f191d980-96d5-11eb-90a4-dbf404401b60.jpg)
![sql2](https://user-images.githubusercontent.com/50627937/113680768-77158980-96d6-11eb-8afc-b33597ae2f90.jpg)

**Comment by zabihrajaie** [comment]
I have a field called CurrentVersion in the table that increases with each sql trigger update.
![sql](https://user-images.githubusercontent.com/50627937/113681223-f5722b80-96d6-11eb-8eb3-8df440c2974c.jpg)
![sql2](https://user-images.githubusercontent.com/50627937/113681230-f7d48580-96d6-11eb-8748-1052117b0f5b.jpg)
![c#](https://user-images.githubusercontent.com/50627937/113681239-fb680c80-96d6-11eb-9e31-2eae8b13a038.jpg)

**Comment by borisdj** [comment]
Batch Update updates all records found filtered in the query, just like pure Sql does.
BulkUpdate is able to skip updating row if it has the same all values or only specified (In ReadMe there is info about PropertiesTo-Include/Exclude-OnCompare)
