### ISSUE TITLE
System.NotSupportedException: 'Sqlite supports only UPSERT(analog for MERGE WHEN MATCHED) but does not have functionality to do:  'WHEN NOT MATCHED BY SOURCE THEN DELETE 'What can be done is to read all Data, find rows that are not in input List, then with those do the BulkDelete.'

### ISSUE THREAD

**Issue by SofiyaDSRC** [borisdj/EFCore.BulkExtensions#514]
System.NotSupportedException: 'Sqlite supports only UPSERT(analog for MERGE WHEN MATCHED) but does not have functionality to do:
 'WHEN NOT MATCHED BY SOURCE THEN DELETE
'What can be done is to read all Data, find rows that are not in input List, then with those do the BulkDelete.'

In my project I need to insert if any new data is added or have to update if any modifications in api or else to delete the data in sqlite when its not presented in api call. But BulkInsertOrUpdateOrDeleteAsync not working. Do you have any alternate ways for this

**Comment by borisdj** [comment]
Alternative way is given in the exception.
Read all data, split list into 2 lists _InsertOrUpdate_ and _Delete_ then with those call `BulkInsertOrUpdate` and `BulkDelete`.
