### ISSUE TITLE
how do you load child entities with bulk read

### ISSUE THREAD

**Issue by imaadzahmed** [borisdj/EFCore.BulkExtensions#515]
I have an entity that represents a shop. This entity has a property, which is a list of child entities that represent the opening hours of the shop. When I do my bulk read for the shop using the country, the opening hours collection does not get loaded in with the bulk read but remain null. This data is stored in another table so I'm not sure if you can load child entity data with bulk read like you can with a normal efcore query. I have tried initialising the collection and adding the elements for each of the days of the week but none of the rest of the data gets populated. Furthermore, I have tried to add the property in the "PropertiesToInclude" in the bulk config but this just throws an exception which can be seen below. 

```
System.InvalidOperationException: The underlying reader doesn't have as many fields as expected.
  Stack Trace: 
    BufferedDataRecord.InitializeFields()
    BufferedDataRecord.Initialize(DbDataReader reader, IReadOnlyList`1 columns)
    BufferedDataReader.Initialize(IReadOnlyList`1 columns)
    RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
    Enumerator.InitializeReader(DbContext _, Boolean result)
    ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`3 operation, Func`3 verifySucceeded, TState state)
    ExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
    Enumerator.MoveNext()
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)
    SqlBulkOperation.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
    SqlBulkOperation.ReadAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
    SqlBulkOperation.ReadAsync[T](DbContext context, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken)
```

Is there any way to load the child entities with the bulk read or do I have to load them separately then do the matching in code. Any help would be much appreciated.

```
 public class Shop: Entity
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string StreetNumber { get; set; }
        public string StreetAddress1 { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string IsoCountry { get; set; }

        public double Latitude { get; set; }
        public double Longitude { get; set; }

        public string Description { get; set; }
        public string Directions { get; set; }

        public List<OperationalHours> OperationalHours { get; set; }
    }

public class OperationalHours : Entity
    {
        public Guid Id { get; set; }

        [JsonIgnore]
        public Shop Shop{ get; set; }

        public Shop ShopId { get; set; }

        public DayOfWeek DayOfWeek { get; set; }
        public bool Closed { get; set; }
        public TimeSpan OpeningHours { get; set; }
        public TimeSpan ClosingHours { get; set; }
    }

```

**Comment by borisdj** [comment]
BulkRead can not load child entities from parent list, they work on single table.
You need to BulkRead child entities separately.

**Comment by imaadzahmed** [comment]
ok thanks for your help. Out of interest are you planning on updating it to load child entities or will this sacrifice the speed of the bulk read

**Comment by borisdj** [comment]
No plans for that, but do plan to add BulkSaveChanges which will have similar result.
However that would be slower because of context tracking info.

**Comment by borisdj** [comment]
There is now config **ReplaceReadEntities** that works as _Contains/IN_ and returns all which match the criteria (not unique).
Useful when need to BulkRead child entities after BulkReading parent list.
