### ISSUE TITLE
Cannot install on a Xamarin Android projet 

### ISSUE THREAD

**Issue by nbelley** [borisdj/EFCore.BulkExtensions#516]
I'm using netstandard 2.1 in my data access project, so everything installs fine. The database I'm using is sqlite, but when try to install the package on the android app project, it doesn't work: 

`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Data.SqlClient.SNI.runtime 2.1.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v11.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I would be nice to have a package that can be used in mobile apps!

**Comment by borisdj** [comment]
This seems to be problem because of _Microsoft.Data_ component, so they would have to address the issue.
In the meanwhile what you could do is replace `Microsoft.Data.SqlClient`  with `System.Data.SqlClient` and rebuid the library as another user have done: DUPE of [Xamarin.iOS build failed with Link Sdk Assembliies](https://github.com/borisdj/EFCore.BulkExtensions/issues/332)

**Comment by nbelley** [comment]
Just to conclude, I did what was recommended in the linked post. I also had to remove the packages NetTopologySuite and direct references to it (in Sql server adapters anyway, which won't be used on mobile).

Right now I'm in final tests and it seems to work perfectly for SQLite. 

Thanks for you help!

**Comment by borisdj** [comment]
So eventually you made it with work with `Microsoft.Data` ?
And besides removing _NetTopologySuite_ what else exactly did you do that you said was recommended in the linked post?

**Comment by nbelley** [comment]
Replace nuget package Microsoft.Data.SqlClient with System.Data.SqlClient!

Commentend the code that could not be translated, with netpopolgy, mostly geometry stuff only for sql server anyway.
