### ISSUE TITLE
RowVersion checks crashes bulk insert, no way to disable

### ISSUE THREAD

**Issue by zinvob** [borisdj/EFCore.BulkExtensions#517]
I have entities with two Concurrency fields, and one that have both Concurrency and 

[MessagePackObject]
    public abstract class VersionEntity
    {
        [Key(0)]
        public long RowVersion { get; set; }
        [Key(1)]
        public string SyncDeviceId { get; set; } = "";
        [Key(2)]
        public bool Deleted { get; set; }
    }
}
Property(o => o.RowVersion).HasDefaultValue(0).IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().Metadata.SetBeforeSaveBehavior(PropertySaveBehavior.Save);
Property(o => o.SyncDeviceId).IsRequired(true).IsConcurrencyToken().HasDefaultValue("");

I use these for a synchronizer, and the bulk updates must also update the concurrency fields.

I get errors that RowVersion is not a binary type when trying to bulk insert.

I've proposed a fix in your component for this to be able to disable your RowVersion detection. See my patch file.
[0001-Need-the-ability-to-turn-of-RowVersion-check-for-spe.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/6291818/0001-Need-the-ability-to-turn-of-RowVersion-check-for-spe.zip)

It will add IgnoreRowVersion on BulkConfig.

Hope you can look into this soon, I would like to use your component instead of a local fork.

**Comment by zinvob** [comment]
https://github.com/borisdj/EFCore.BulkExtensions/pull/519

**Comment by borisdj** [comment]
Will take a look.

**Comment by borisdj** [comment]
Can you also write entire code snipped of Test where this crash would be reproducible.

**Comment by zinvob** [comment]
I've included tests for you now

**Comment by borisdj** [comment]
Published v5.0.7
Thx for contrib.
