### ISSUE TITLE
With BulkInsertOrUpdate: do not use "Table Attribute"

### ISSUE THREAD

**Issue by metatechsoftware** [borisdj/EFCore.BulkExtensions#523]
We find out that we could not use BulkInsertOrUpdateAsync since you are looking to Entity name directly; but, we are using "Table Attribute".

It works as expected when:

[Table("CallDetail")]
public class CallDetail: Entity<long>
{
...
}

but it does not work when:

[Table("AppCallDetail")]
public class CallDetail: Entity<long>
{
...
}

Note: if you can work on this , it will be great...

**Comment by borisdj** [comment]
Table name does not have to match entity, that is already supported.
If you still have issue can you write reproducible test for it.
