### ISSUE TITLE
bandwith problem with SetOutputIdentity = true

### ISSUE THREAD

**Issue by Spirch** [borisdj/EFCore.BulkExtensions#526]
when the  `SetOutputIdentity = true`  is set, it create a lot of traffic over the wire.

My understanding there is a select * being done on the output table to get the new identity value to be assigned to the object.

Imagine if the bulk insert was to insert 100 megs of data, 100 meg just got sent to sql server and for only a primary key, the process read back that 100 megs.

this could be reduced by simply doing a **select PrimaryKey** from the output table.

**Comment by maitlandmarshall** [comment]
Looking into this.

**Comment by borisdj** [comment]
Redundant Columns could be removed (leaving only Identity, TimeStamp, Computed, DefaultVal.) from _SelectFromOutputTable_ method that makes Query text, but the problem is that used reader `context.Set<T>().FromSqlRaw(sqlQuery)` requires all columns in query otherwise it can't load data, exception thrown:

> The required column '...' was not present in the results of a 'FromSql' operation.

**Comment by huer12** [comment]
I'm not sure, but I think If you extend it to 
`context.Set<T>().FromSqlRaw(sqlQuery).Select(e=> e.Id)`
then it only selects the id and should not throw the exception

**Comment by borisdj** [comment]
Added config **SetOutputNonIdentityColumns** used only when *SetOutputIdentity* is set to true, and if this remains True (which is default) all columns are reloaded from Db.
When changed to false only Identity column is loaded to reduce load back from DB for efficiency.
