### ISSUE TITLE
list is collection of two classes with 1-to-1 relations. BulkInsert(list) does not fill table for child class.

### ISSUE THREAD

**Issue by nikriaz** [borisdj/EFCore.BulkExtensions#527]
I have very simple model (POCO) of two classes `Message `and `MessageDetail` with 1-to-1 relationships. That is, each class has a navigation property which is pointing out to another class. I create collection of these classes like `list = List<Message>` where each `Message ` contains `Message.MessageDetail`. In terms of DB, Messages is regular SQlite table and MessageDetails is virtual FTS5 SQLite table. 

So,
```
            context.BulkInsert(list); 

```
just does not fill MessageDetails table, it remains empty, while 

```
            foreach (var message in list)
            {
                context.Add(message);
            }
            context.SaveChanges();
```
works well (but slow, of course).

Have no idea how to trace it down. Could you please help?

**Comment by nikriaz** [comment]
Oh, I found that I have to do something like 

```
context.BulkInsert(list, b => b.IncludeGraph = true);
```
but it leads to exception: "Sqlite is not currently supported due to its BulkInsert implementation.". Is this dead end?

**Comment by borisdj** [comment]
Use 2 BulkInsert methods, one for parent and then for child as explained in ReadMe.
