### ISSUE TITLE
is branch for EF 3.1 still supported?

### ISSUE THREAD

**Issue by Spirch** [borisdj/EFCore.BulkExtensions#529]
first thanks a lot again for the fix for the includeGraph. 

My repo currently use EF core 3.1 and I cannot upgrade to 5.0 since I can only use LTS version of .net core 

would it be possible to backport changes to the 3.1 branch when possible?

**Comment by borisdj** [comment]
It's not actively supported, meaning new feature will not be integrated there, only some mayor bug fixes.

**Comment by Spirch** [comment]
in this case, the includeGraph had a bug and without this fix, it's not working

hopefully the fix will get merged in 3.1 branch and I can start using the nuget package

right now i have a copy of 3.1 branch and i manually applied the fix, it's an "ok-ish" workaround but it mean that if there is any other nuget update, i will not be aware

I'm pretty sure I'm not alone using LTS release only, knowing the 3 years support vs 15 months support.

**Comment by borisdj** [comment]
LTS will be EF 6, in 6 months, and I don't expect much changes on v3.
Still if @maitlandmarshall is willing to make this PR also for v3 branch I can publish new 3.x nuget, currently last is v3.6.1.

**Comment by Thom3189-coder** [comment]
We've also ran into this issue yesterday on the 3.1 branch, so would be greatly appreciated if this could be merged into that branch!

**Comment by sebharskamp** [comment]
> We've also ran into this issue yesterday on the 3.1 branch, so would be greatly appreciated if this could be merged into that branch!

We're facing the same problem. It would be appreciated it could be merged! Thanks!

**Comment by maitlandmarshall** [comment]
Hi all, once issue #547 is resolved I will look into merging the fixes into the 3.1 branch.
