### ISSUE TITLE
Parent child relationship

### ISSUE THREAD

**Issue by NimeshDhruve** [borisdj/EFCore.BulkExtensions#53]
I have quick question, does parent child relationship work while saving the data?

For example, I have following classes:

```
public partial class Application
{
    public Application()
    {
        Stations = new HashSet<Station>();
    }

    public int ApplicationId { get; set; }
    public string ApplicationName { get; set; }

    public ICollection<Station> Stations { get; set; }
}

public partial class Station
{
    public Station()
    {
        TestResults = new HashSet<TestResult>();
    }

    public int StationId { get; set; }
    public string StationName { get; set; }
    public int ApplicationId { get; set; }

    public Application Application { get; set; }
    //other properties removed for brevity
}
```
Below code is inside `OnModelCreating`
```
modelBuilder.Entity<Application>(entity =>
{
    entity.Property(e => e.ApplicationName)
        .IsRequired()
        .HasMaxLength(50);
});

modelBuilder.Entity<Station>(entity =>
{
    entity.HasIndex(e => e.StationName)
        .HasName("IX_Stations")
        .IsUnique();

    entity.Property(e => e.StationName)
        .IsRequired()
        .HasMaxLength(50);

    entity.HasOne(d => d.Application)
        .WithMany(p => p.Stations)
        .HasForeignKey(d => d.ApplicationId)
        .OnDelete(DeleteBehavior.ClientSetNull)
        .HasConstraintName("FK_Stations_Applications");
});
```
Following is my input for seeding the `Applications` and `Stations` table.

```
void SeedApplications()
{
	using (var repository = RepositoryFactory.GetRepository())
	{
		var applications = repository.SeedApplications(new Application[] {
			new Application
			{   ApplicationName = "Front EOL", ApplicationId = 0, Stations = new Station[]
				{
					new Station{ StationName = "1600N" ,StationId = 0, ApplicationId = 0 },
					new Station{ StationName = "1600S" ,StationId = 0, ApplicationId = 0 },
					new Station{ StationName = "1700S" ,StationId = 0, ApplicationId = 0 },
				}
			},
			new Application
			{   ApplicationName = "FAM", ApplicationId = 0, Stations = (new Station[]
				{
					new Station{ StationName = "1650N",StationId = 0, ApplicationId = 0  },
					new Station{ StationName = "1700N",StationId = 0, ApplicationId = 0  },
					new Station{ StationName = "1750N",StationId = 0, ApplicationId = 0  }
				}
				)
			}			
		});
	}
}
```
Following is a class to create a Repository instance:
```
static class RepositoryFactory
{
	public static Repository GetRepository()
	{
		DbContextOptionsBuilder b = new DbContextOptionsBuilder();
		b.UseSqlServer(System.Configuration.ConfigurationManager.ConnectionStrings["TestResultServer"].ConnectionString);
		return new Repository(b.Options);
	}
}
```
Actual repository class:
```
public partial class Repository : DbContext
{
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Station> Stations { get; set; }

	public IEnumerable<Application> SeedApplications(IEnumerable<Application> data)
	{
		///This code was auto generated, if you make any change in this method then next time when the code is regenerated your changes will be overwritten 
		if(data.Any() == false)
			return data;
		var items = data.ToList();
		using (var transaction = Database.BeginTransaction())
		{
			Applications.AddRange(items);
			this.BulkInsert(items, new BulkConfig {  SetOutputIdentity = true });
			transaction.Commit();
			return items;
		}		
	}
}
```

I was hoping that after inserting Applications records, Stations records will be inserted too. But that never happens. Following is my debug window output which shows after insert Stations  property is cleared.

Before bulk insert:
![beforeinsert](https://user-images.githubusercontent.com/7783989/41633777-7427f9ee-740e-11e8-86da-3d45a9c6323b.png)

After bulk insert:
![after](https://user-images.githubusercontent.com/7783989/41633798-90f83836-740e-11e8-9bc8-8855be0d40da.png)

If use regular Insert from EF Core it just works fine (code which is commented in the above screen shot). The problem only occurs if I use BulkInsert method. 

I am wondering if you can please clear up my doubt and let me know if this is possible or not :)

Thanks.

**Comment by borisdj** [comment]
Saving related(child) data in not done by automatically.
However you can save them explicitly.
In README.md there is following info:

> **SetOutputIdentity** is useful when BulkInsert is done to multiple related tables, that have Identity column.
> So after Insert is done to first table, we need Id-s that were generated in Db becasue they are FK in second table.
> It is implemented with OUTPUT] as part of MERGE Query, so in this case even the Insert is not done directly to TargetTable but to TempTable and then Merged with TargetTable.
> When used if **PreserveInsertOrder** is also set to *true* Id-s will be updated in entitiesList, and if *PreserveInsertOrder* is *false* then entitiesList will be cleared and reloaded.

So you should first use *PreserveInsertOrder = true* in order for Items to be updated and that way SubItems won't be cleared, and then just call another BulkInsert for SubItems:
```C#
using (var transaction = Database.BeginTransaction())
{
    //Applications.AddRange(items); // this is not required
    this.BulkInsert(items, new BulkConfig {  SetOutputIdentity = true, PreserveInsertOrder = true });
    var subItems = new List<Station>();
    foreach(var item in items)
    {
        foreach(var station in item.Stations)
            station.ApplicationId = item.ApplicationId; // setting FK to match its PK that was Db generated
        subItems.AddRange(item.Stations)
    }
    this.BulkInsert(subItems);
    transaction.Commit();
    return items;
}	
```

PS
Also in SeedApplications method Id (int) is 0 by default so you don't need = 0, setting just StationName is enough:
```C#
new Application
{   ApplicationName = "Front EOL", ApplicationId = 0, Stations = new Station[]
    {
        new Station{ StationName = "1600N" },
        new Station{ StationName = "1600S" },
        new Station{ StationName = "1700S" },
    }
}
```

**Comment by borisdj** [comment]
You can make a test with these scripts.
First create EFCoreBulk Test DB:
[EFCoreBulkTestDB.sql](https://drive.google.com/file/d/1muCRNz5IZd06hP0g4FG4S35a_W6dmpIQ)
Then Run this Sql script.
[EFCoreBulkTestSQL.sql](https://drive.google.com/file/d/1Zwm9DTHrnGPd_O7HCHEvqobox4XFJa8B)
It should give you correct error and then refresh it and check it Temp table remaind in DB.
