### ISSUE TITLE
No Extension Methods

### ISSUE THREAD

**Issue by atrancandoris** [borisdj/EFCore.BulkExtensions#531]
Error:

`/workspaces/MyApp App/Controllers/MyAppController.cs(49,22): error CS1061: 'MyAppContext' does not contain a definition for 'BulkInsertOrUpdate' and no accessible extension method 'BulkInsertOrUpdate' accepting a first argument of type 'MyAppContext' could be found (are you missing a using directive or an assembly reference?) [/workspaces/MyApp App/MyApp App.csproj]`

`MyAppContext` extends `DbContext`:

`public class MyAppContext : DbContext`

Packages:

```
  <PackageReference Include="EFCore.BulkExtensions" Version="5.0.9" />
  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.5" />
```

Any ideas? Thanks!

**Comment by borisdj** [comment]
Haven't seen this error before.
Try making a test where the issue would be reproducible.

**Comment by atrancandoris** [comment]
Here is a complete repo for reproducing the issue:

https://github.com/atrancandoris/EFGetStarted-Bulk-Issue

You can can use vscode Remote Containers to recreate the entire environment (even at the OS-level).

**Comment by borisdj** [comment]
I've tried added your code into test and first thing is that code is not valid.
You are BulkInsertorUpdate-ing _posts_ without FK **BlogId** being set, which throws exception:

> Microsoft.Data.Sqlite.SqliteException : SQLite Error 19: 'FOREIGN KEY constraint failed'.

And secondly when code is made valid and if still fails with the issue you stated that the problem is probably not inside library but might have something to do with Containers. Haven't used them much so I'll have to investigate.

**Comment by atrancandoris** [comment]
You're right about the code issue, but I really didn't even get that far since the extension methods aren't found. 

I've also tried Visual Studio for Mac and am receiving the same issue.

Is there anything other than dotnet restore I need to do to pull the dependencies? Any troubleshooting recommendations are welcome. Thanks.

**Comment by borisdj** [comment]
Personally I have used it only on Windows with Visual Studio.
Still since it's .Net Standard library it should work on others OS and should be able to run it with VS Code.
Try google-ing the exception you have, also test to load the source code of library instead of nuget and check if that works.

**Comment by atrancandoris** [comment]
So the issue was that I did not include:

`using EFCore.BulkExtensions;`

I thought this wasn't necessary, since I thought the extension applied to the DbContext. I admit I don't really understand what's going on under the hood.

Hopefully this issue can at least help others.

Thanks so much!

**Comment by borisdj** [comment]
Glad you solved it.
