### ISSUE TITLE
ArgumentOutOfRangeException on simple batch delete query

### ISSUE THREAD

**Issue by ImoutoChan** [borisdj/EFCore.BulkExtensions#532]
I have a simple query with one `where` condition like this:

```csharp
_context.Table.Where(
                x => x.Source == fileTag.Source
                     && x.TagId == fileTag.Tag.Id
                     && x.FileId == fileTag.FileId
                     && x.Value == fileTag.Value)
                     .BatchDeleteAsync();
```

but every execution throws this exception:

```
"ClassName": "System.ArgumentOutOfRangeException",
  "Message": "Length cannot be less than zero. (Parameter 'length')",
  "Source": "System.Private.CoreLib",
  "StackTraceString": "   
  at System.String.Substring(Int32 startIndex, Int32 length)\r\n   
  at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlServerDialect.GetBatchSqlReformatTableAliasAndTopStatement(String sqlQuery)\r\n   
  at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)\r\n   
  at EFCore.BulkExtensions.BatchUtil.GetSqlDelete(IQueryable query, DbContext context)\r\n   
  at EFCore.BulkExtensions.IQueryableBatchExtensions.GetBatchDeleteArguments(IQueryable query)\r\n   
  at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchDeleteAsync(IQueryable query, CancellationToken cancellationToken)
```

I tried to investigate and it seems that `SplitLeadingCommentsAndMainSqlQuery` method returns an empty string as the first result item.

This is query generated by query.ToParametrizedSql();
```
SELECT f."Id", f."AddedOn", f."FileId", f."ModifiedOn", f."Source", f."TagId", f."Value"
FROM "FileTags" AS f
WHERE (((f."Source" = @__fileTag_Source_0) AND (f."TagId" = @__fileTag_Tag_Id_1)) AND (f."FileId" = @__fileTag_FileId_2)) AND (f."Value" = @__fileTag_Value_3)
```

And the same query is returning from the second item from `SplitLeadingCommentsAndMainSqlQuery`.

**Comment by borisdj** [comment]
From looking at this, maybe the problem is in sub-property `fileTag.Tag.Id`, try assigning value to another variable.
If still does no work write entire code snippet for Test where the issue would be reproducible.

**Comment by ImoutoChan** [comment]
Thank you. I tried assigning Tag.Id to a variable, but nothing changed. The query is valid though and executing fine as select with ToList(); 
 
I will try to create a reproduction example in my free time, but anyway I don't think that the library should throw such exceptions even for invalid queries. I think maybe there is something wrong and the library assumes that the generated query would always contain some leading comments? But in my case there is none.

**Comment by fschick** [comment]
The exception occurs when using a PostgreSQL or MySQL database. Not sure, if you like to support databases other than SqlServer and Sqlite. At least, there is a comment in the code SqlServerDialect.cs, line 36:
`var isSqlServer = true;  // SqlServer : PostrgeSql; // TODO change to specific type`
A minimal example to reproduce the exception: [EFCore.BulkExtensions.ReproduceIssue532.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7019954/EFCore.BulkExtensions.ReproduceIssue532.zip)
