### ISSUE TITLE
After using BulkInsertOrUpdateAsync, I can't get entity status  by  DbContext.ChangeTracker because of throwing exception

### ISSUE THREAD

**Issue by xiafeicn** [borisdj/EFCore.BulkExtensions#535]
After use `await DbContext.BulkInsertOrUpdateAsync(new List<XXXentity> { entity }, bulkConfig);`;
then i use ` DbContext.ChangeTracker.Entries()` to get entity status ,it will throw exception 
` Microsoft.EntityFrameworkCore.ChangeTracking: Debug: The unchanged property 'xxxEntity.Id' was detected as changed and will be marked as modified. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see property values.
'DbContext.ChangeTracker.Entries().ToList().Count' threw an exception of type 'System.InvalidOperationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233079
    HelpLink: null
    InnerException: null
    Message: "The property 'xxxEntity.Id' is part of a key and so cannot be modified or marked as modified. To change the principal of an existing entity with an identifying foreign key, first delete the dependent and invoke 'SaveChanges', and then associate the dependent with the new principal."
    Source: "Microsoft.EntityFrameworkCore"`
but it works well for ef core.
can you help me ?thanks.

**Comment by borisdj** [comment]
Entities in Bulk ops are not tracked.
