### ISSUE TITLE
BulkRead list of not Unique Prop./Column

### ISSUE THREAD

**Issue by jsuag** [borisdj/EFCore.BulkExtensions#537]
I'm trying to do a bulk read using a list of not unique prop/column but it causes an exception "ThrowAddingDuplicateWithKeyArgumentException".

It happens in the line 634 of TableInfo << existingEntitiesDict.Add(uniqueProperyValues, existingEntity); >>
it's not an error because a unique value is expected, but maybe with a flag this new feature could be added.

if (AllowNotUniqueValues)
{
    existingEntitiesDict.TryAdd(uniqueProperyValues, existingEntity);
}
else
{
    existingEntitiesDict.Add(uniqueProperyValues, existingEntity);
}

**Comment by borisdj** [comment]
Logic of _BulkRead_ is to have some way of identifying Entites you want to Load, so you need either PK or some combination of columns to set in UpdateByProperties. How would you resolve the conflict if they are not unique?, to take the first one or last one or something else, and what would that decision be base on, it seems to undetermined.

**Comment by jsuag** [comment]
In my case is just the first one I need... it could be solved adding a flag (parameter) to handle it depending on it. What do you think?

**Comment by borisdj** [comment]
I suppose the first would be fine, will see to integrated it.

**Comment by borisdj** [comment]
Fixed with v5.1.3
