### ISSUE TITLE
Partial sync with InsertOrUpdateOrDelete

### ISSUE THREAD

**Issue by mikechoinoski** [borisdj/EFCore.BulkExtensions#540]
Just wondering if any thought has been put in to allowing a partial sync on the merge statement for InsertOrUpdateOrDelete. So basically allowing a conditional delete in the merge statement.

As a really simple way of doing it, I think I'm going to have a property in the BulkConfig to allow a custom delete condition. 

So instead of just having:
 "WHEN NOT MATCHED BY SOURCE THEN DELETE"

We could have something like:
$"WHEN NOT MATCHED BY SOURCE AND {targetTable}.SourceId = 1 THEN DELETE"

My way is probably not the best or most elegant way of handling it but I think for my needs it will work pretty well. The concept of a partial sync may be something others need too so I thought I'd bring it up.

**Comment by borisdj** [comment]
It would need to be more generalized and not sure how to implement it.
There was a discussion here: https://github.com/borisdj/EFCore.BulkExtensions/issues/424

**Comment by borisdj** [comment]
Implemented with v5.1.4
BulkConfig now has method **_SetSynchronizeFilter_**.
Example: 
https://github.com/borisdj/EFCore.BulkExtensions/blob/0b91335d6d2a82d8528f815c8cdbf07a144c2d49/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs#L279
