### ISSUE TITLE
`IQueryable<Scalar>` to "insert into AnyTableName (Scalar) select scalar from {queryable}"

### ISSUE THREAD

**Issue by springy76** [borisdj/EFCore.BulkExtensions#542]
The only thing I need seems not to be supported, neither bei EFCore itself or this lib (or I just did not find):

By building any complex query which ends with `.Select(x => x.Id)` I would have an `IQueryable<long> scalars` which I just want to feed into a **custom named** and **unmapped** (temp) table as such:
`scalars.InsertInto("tableName", "scalarFieldName");`

At SQL this just should result in the original SQL of the query (including parameters of course) just prefixed with 
`insert into "tableName" ("scalarFieldName") ` followed just by the query itself.

**Comment by borisdj** [comment]
```C#
// It could be achieved the following way (for example entity is "Item")
var query = q.Select(x => x.Id);
var entitiesToInsert = query.Select(a => new Item { Id = a }).ToList(); // creating list of Objects where only Id is set
var bulkConfig = new BulkConfig
{
  PropertiesToInclude = new List<string> { nameof(Item.Id) },
  CustomDestinationTableName = tableName
};
context.BulkInsert(entitiesToInsert, bulkConfig);
```
If your class does not have property with name _scalarFieldName_ then make class just with that:
``` class ScalarTable { public int scalarFieldName } ``` and create a list of that.

**Comment by springy76** [comment]
Thanks for your very quick answer.

But:
I want to create one SHORT query, not a huge string of numbers (can be 1 million). `IQueryableExtensions.ToParametrizedSql` looks promising but is SqlServer only, my primary focus is SQLite.

**Comment by borisdj** [comment]
I am assuming your Id values are not all the same, in which case you need some list of values.
So code above would be pretty fast since it's only one column and SqlBulkCopy is used directly.
I don't think it can be more optimized with any tool.

**Comment by springy76** [comment]
The values should not round-trip to the client at all - I just need one (not two) single query which is executed entirely on the server.

**Comment by borisdj** [comment]
Then using `context.Database.ExecuteSqlRaw` is probably good option.

**Comment by springy76** [comment]
If have no problem with ExecuteSqlRaw, but for that I need the accurate SQL representation of the `IQueryable<long>` including all parameters (there might be many joins involved) - I think your lib already did most of that part.

**Comment by borisdj** [comment]
`ToParametrizedSql` is used both for SqlServer and Sqlite, so try using it if you can make it work by appending you sql sufix and calling RawSql.

**Comment by springy76** [comment]
I wonder if your code could create virtual DbParameter/DbCommands there, requesting the provider in place to create its derived classes?
(because ExecuteSqlRaw now complains "Unable to cast object of type 'Microsoft.Data.SqlClient.SqlParameter' to type 'Microsoft.Data.Sqlite.SqliteParameter'.".

**Comment by borisdj** [comment]
Not sure about that.

**Comment by springy76** [comment]
Thank you again for your instant effords and pushing me into the right directions.

Thats what I ended up for now: working 👍

```
var conn = context.Database.GetDbConnection();
var factory = DbProviderFactories.GetFactory(conn);
DbParameter Transform(DbParameter p)
{
	var result = factory.CreateParameter();
	result.ParameterName = p.ParameterName;
	result.DbType = p.DbType;
	result.Value = p.Value;
	return result;
}

var (idSql, parameters) = EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(idQuery).Dump("sql");
context.Database.ExecuteSqlRaw(
		$"INSERT INTO [temp].[#JustInMemoryIDs]\r\n{idSql}\r\nON CONFLICT DO NOTHING;", 
		parameters.Select(Transform).Dump("transformed"))
	.Dump("affected rows");
```

**Comment by borisdj** [comment]
Glad it helped.
