### ISSUE TITLE
BatchUpdate fails due to classifying varbinary(max) column as nvarchar(4000)

### ISSUE THREAD

**Issue by ognamala** [borisdj/EFCore.BulkExtensions#548]
Hi all, I have been using the library quite successfully - recently I needed to make a change where I would set a varbinary(max) column to null using the statement as follows:

```
await context.Entities
                        .Where(x => entityid.Contains(x.EntityId) && x.Col1 != EntityStatus.Status.Id)
                        .BatchUpdateAsync(x => new Entity { Col1 = EntityStatus.Status.Id, ByteArray = null}, cancellationToken);
```

However the above fails with 

```
Msg 257, Level 16, State 3, Line 1
Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
```
I have taken a look at the profiler and the generated SQL and I can see that the ByteArray (which has type byte[] in dot net core) is somehow being converted to nvarchar(4000) and not varbinary(max) in the generated SQL

```
exec sp_executesql N'UPDATE c SET [ByteArray] = @ByteArray, [Col1] = @Col1
FROM [dbo].[Entities] AS [c]
WHERE ([c].[EntityId] IN (1) AND ([c].[Col1] <> @__EntityStatus_Id_1))',N'@__EntityStatus_Id_1 int, @ByteArray nvarchar(4000),@Col1 int',@__EntityStatus_Id_1=3,@ByteArray=null,@Col1=3
```
As you can see ByteArray above has been assigned type nvarchar(4000) in the generated SQL

The good news is, I have switched my code to a BulkUpdateAsync and is behaving as expected, generated code also makes sense and the type assigned is VarBinary(max)

Hope this helps!

**Comment by borisdj** [comment]
Pretty peculiar bug.
The issue was that Batch ops for default value parameters are using implicit conversion _nvarchar_ to destination type, and in this case it's _**varbinary(max)**_ which is not allowed.
I've made a fix for it with explicitly setting DbType but it works only when called with simple object and not expression since there no access to property for type check.
WORKs:
```C#
var updateCols = new List<string> { nameof(File.DataBytes) };
query.BatchUpdateAsync(new File { DataBytes = null }, updateCols); // requires explicit updateCols for update to default
```
NOT WORKing
```query.BatchUpdateAsync(a => new File { DataBytes = null });```

**Comment by borisdj** [comment]
Managed to make it work with expression as well, v5.2.0.

**Comment by ognamala** [comment]
Amazing, thanks !
