### ISSUE TITLE
Having issue on insert, without any specific error

### ISSUE THREAD

**Issue by mfahadi** [borisdj/EFCore.BulkExtensions#55]
I am trying to bulk insert some data according to example given on here but it is throwing exception that I can't trace. 

Here is the code

```
using(var tr = await _context.Database.BeginTransactionAsync())
            {
                await _context.BulkInsertAsync(model);
                await _context.SaveChangesAsync();
                tr.Commit();
            }
```
It throws exception on _context.BulkInsertAsync

Below is the stack trace

  ```
{System.NullReferenceException: Object reference not set to an instance of an object.
 
 at EFCore.BulkExtensions.TableInfo.<LoadData>b__65_2[T](IProperty a)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress)
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertAsync[T](DbContext context, IList`1 entities, BulkConfig bulkConfig, Action`1 progress)
   at AccountService.<model>d__17.MoveNext() in C:\Project\AccountService.cs:line 303
--- End of stack trace from previous location where exception was thrown ---`

Thanks

**Comment by borisdj** [comment]
Please write more info:
Entity class definition your are trying to Insert and
example of values in the model list.
You could also download the library, add that code into test, and try to reproduce and debug it there.

**Comment by mfahadi** [comment]
Thanks for the prompt response. 

My mistake, was using version 2.0.9 with e.f core version 2.0, installed the 2.0.8 version and it seems to go through alright. 

Found a bug while debugging this. When using a namespace with tables the extensions don not add square brackets with namespace. For namespace [Payment] it sends the query as Payment.[UserTransaction] which would break if some one is using a keyword as namespace name.

**Comment by borisdj** [comment]
Could you explain more what do you mean by Namespace in the SQL sense?
Db schema or something else ?

**Comment by mfahadi** [comment]
Yes, db schema
________________________________

**Comment by borisdj** [comment]
Added brackets [ ] around DbSchema, NuGet 2.1.3

**Comment by mfahadi** [comment]
Great, thanks. 

I was wondering if it is possible for you to add and example on how one might save related entities, both with bulk insert. 

For example, we have a "Parent" entity and "Child" entity.

class Parent { int id , string name }
class Child  { int id, int name, int ParentId }

Both have one to one relationship.

Both collections are populated, with child referring to Parent but no ParentId yet, as Parent is not saved.
First we insert a list of "Parent" with bulk insert, with setoutputidentity config set to true. 
Parent collection is saved in db and Id property gets updated. Now the question is how do this change can be propagated to Child. I have tried adding them both to DbContext as AddRange() but still the foreign key of Child is not populated. 

Thanks

**Comment by borisdj** [comment]
In the following issue there is an example:
[https://github.com/borisdj/EFCore.BulkExtensions/issues/53](https://github.com/borisdj/EFCore.BulkExtensions/issues/53)
I will see to copy part of this into README so that it's more visible.
