### ISSUE TITLE
[A]System.Data.SqlClient.SqlConnection cannot be cast to [B]System.Data.SqlClient.SqlConnection

### ISSUE THREAD

**Issue by CollabGuy** [borisdj/EFCore.BulkExtensions#550]
Tried to include the latest pkg into an azure functions project using entity framework 6.4.4.

When calling insert - 

[A]System.Data.SqlClient.SqlConnection cannot be cast to [B]System.Data.SqlClient.SqlConnection. Type A originates from 'System.Data.SqlClient, Version=4.6.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location netcoreapp2.1/System.Data.SqlClient.dll. Type B originates from 'System.Data.SqlClient, Version=4.6.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' in the context 'Default' at location AppData\Local\AzureFunctionsTools\Releases\3.24.2\cli_x64\System.Data.SqlClient.dll.

not sure why these are different and how to resolve. debugging now and will post back if I figure it out.

**Comment by borisdj** [comment]
This lib. if for EF Core only.
