### ISSUE TITLE
BulkInsertOrUpdate not setting Ids automatically

### ISSUE THREAD

**Issue by jrobsondev** [borisdj/EFCore.BulkExtensions#556]
I am having an issue using the BulkInsertOrUpdate functionality whilst trying to insert a list of records into a sqlite database.

```csharp
public async Task BulkInsertOrUpdate(List<TEntity> entities)
{
    var bulkConfig = new BulkConfig
    {
        SetOutputIdentity = true,
        PreserveInsertOrder = false
    };
    await _context.BulkInsertOrUpdateAsync(entities, bulkConfig);
}
```

The list contains a basic list of entities with the following properties:
```
Id - int
Version - byte[]
FirstName - string
LastName - string
```

When the entities are created, they do not have an Id set i.e. Id=0. When I use BulkInsertOtUpdate, only 1 record is added to the database. This record is generally the last item in the list and it has an Id of 0.

When I use the BulkInsert method, the records are inserted correctly and their Ids are automatically set.
I can also insert the entities if I manually set the Id myself, however, I would like to avoid this as it will crreate a large overhead for me if I had to do this for the more complex entities.

**Comment by borisdj** [comment]
You should leave _PreserveInsertOrder_ to _true_

**Comment by jrobsondev** [comment]
> 
> 
> You should leave _PreserveInsertOrder_ to _true_

I have set this to true as you suggested and tried it with a list of 709 items. The problem still persists and only one item was added to the database.

![image](https://user-images.githubusercontent.com/46603916/119130474-34163800-ba30-11eb-9f6a-06a96736d862.png)

(ignore the column names, this is a different entity to the one in the first post).

**Comment by borisdj** [comment]
It's actually up to Sqlite itself, which does not have full MERGE capabilities like SqlServer.
It only supports simple Upsert with `ON CONFLICT` command.
So you can either:
a) split list into 2 lists, and call separately BulkInsert and BulkUpdate or
b) if want to keep all in single method then you would need to read last Id and for news ones set Id from that number incrementally.
I would use chose option a), it's simpler.

**Comment by jrobsondev** [comment]
Thanks for the clarification. This is what I have ended up doing for the meantime, so I will just stick with that.
