### ISSUE TITLE
Insert if exists together with IncludeGraph

### ISSUE THREAD

**Issue by NoWayOut4u** [borisdj/EFCore.BulkExtensions#557]
Hi,

I'm using IncludeGraph = true to insert data (BulkInsertAsync) to parent and several child tables and this works well.
By changing method to BulkInsertOrUpdateAsync and specifying PropertiesToIncludeOnUpdate = new List<string> { "" } I can achieve functionality that data will be inserted only if not exists. 
What I want also is to specify other than PK for comparison. I've tried to use UpdateByProperties = new List<string> { "Code1", "Code2" } but I got an error "Sequence contains no matching element" and I guess this is because these fields aren't present in child tables (if IncludeGraph = false than it works).

Imagine I have one parent table and one child table. Also I have unique index on parent table which consists of two columns [Code1] and [Code2].
I want to to insert data to parent and child table if combination of [Code1] and [Code2] is not present in parent table.

CREATE TABLE [dbo].[Product]
(
	[ProductId] INT NOT NULL IDENTITY(1,1)
	,[Code1] VARCHAR(50) NOT NULL
	,[Code2] VARCHAR(50) NOT NULL
	CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED ([ProductId] ASC)
)

CREATE UNIQUE NONCLUSTERED INDEX [UIX-Product]
	ON [dbo].[Product] ([Code1] ASC, [Code2] ASC) WITH (IGNORE_DUP_KEY = ON, DATA_COMPRESSION = PAGE);

CREATE TABLE [dbo].[ProductDetails]
(
	[ProductDetailsId] INT NOT NULL IDENTITY(1,1)
	,[ProductId] INT NOT NULL
	,[Description] VARCHAR(1000)
    ,CONSTRAINT [PK_ProductDetails] PRIMARY KEY CLUSTERED ([ProductDetailsId] ASC)
    ,CONSTRAINT [FK_ProductDetails_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([ProductId])
)

Maybe I'm doing something wrong?
Thanks!

**Comment by borisdj** [comment]
@maitlandmarshall any thoughts?

**Comment by saulosag** [comment]
I've had a similar problem: I want to decide to insert or not based on an alternate key in the graph parent. I didn't manage to make it work that way and ended up doing BulkRead before to find already present parent entities, but it's not ideal.

**Comment by lcaaroe** [comment]
I'm experiencing the same issue when using BulkInsertOrUpdate with IncludeGraph = true and custom UpdateByProperties.

I can work around it by splitting it into two separate Insert calls as @saulosag mentioned, but it seems less than ideal (although I won't claim to have full understanding of the performance difference).

**Comment by borisdj** [comment]
Graph was not intended for this use case, only for multiple list with simple config.
Also method can be called with only one BulkConfig and separate entities could need different ones.
Calling separately BulkInsertOrUpdate for each table is way to go, with SetOutIdentity and setting FKs for next list if required.
And all calls be be encapsulated inside single transaction.

**Comment by Tyler-V** [comment]
Hey @borisdj to confirm the above statement, if we have two tables...

```
public class Blog
{
    public int BlogId { get; set; }
    public string Url { get; set; }

    public List<Post> Posts { get; set; }
}

public class Post
{
    public int PostId { get; set; }
    public string Title { get; set; }
    public string Content { get; set; }

    public int BlogId { get; set; }
    public Blog Blog { get; set; }
}
```

And we need to perform a bulk update or insert on a request of 1000 Blogs with N number of Post and some of the Blog's have a BlogId of 0 and some of the Post's have a PostId of 0 (but not all) the best strategy to insert/update Blogs and Posts where we need to IncludeGraph would be to separate these into two distinct transactions while just using BulkInsertOrUpdate for Blog and BulkInsertOrUpdate for Post?

Thanks, nifty library!

**Comment by borisdj** [comment]
One way is to use Graph config:
`context.BulkInsertOrUpdate(blogs, bc => bc.IncludeGraph = true);`
Blogs should have their sublist of Post populated, and in all lists those with ID 0 would be added and others matched with existing ones updated.

Other way without using Graph would be to use SetOutputIdentity on parent list, then manually set FK Ids on child list and call second Bulk for subentity.
Entire procedure would be in single transaction. Example of this is in ReadMe (for Item and ItemHistory):

> Example of SetOutputIdentity with parent-child FK related tables

**Comment by Tyler-V** [comment]
I was trying that before... this makes more sense after updating to v3.6.3 thanks!
