### ISSUE TITLE
Bulk deleting pivot records

### ISSUE THREAD

**Issue by cwilby** [borisdj/EFCore.BulkExtensions#558]
What is the best way with this library to bulk remove pivot records?

Say I have `Contact` and `Tag` entities, which have a many-to-many relationship through `Contact_Tag`.

There is a job that deletes `Contact_Tags` for 1000+ contacts that I'm looking to optimize.

It looks a bit like this:

```csharp
public void RemoveTag(int[] contactIds, ContactTags tag)
{
    using (var db = new AcmeDataContext())
    {
        var contacts = db.Contacts.Where(c => contactIds.Contains(c.Id));

        var deleteTagList = new List<ContactTag>();

        foreach (var contact in contacts)
        {
             // adds to deleteTagList based on extra C# logic
        }

        db.ContactTags
            .Where(ct => deleteTagList.Any(ctd => ctd.ContactId == ct.ContactId && ctd.TagId == ct.TagId))
            .DeleteFromQuery();
    }
}
```

This currently throws the following error:

```
-- Failed with error: Exception has been thrown by the target of an invocation.
-- Inner Exception: Unable to create a constant value of type 'Acme.Core.Domain.Contact.ContactTag'. Only primitive types or enumeration types are supported in this context.
```

I understand this is likely because this expression cannot be processed by linq-to-sql, but I'm stuck finding alternatives.

Is this something that's come up before?

**Comment by borisdj** [comment]
Not sure if I fully understand the question.
In your example I don't see BulkDelete being used.
Anyway is should be something like:
```
var deleteList = db.ContactTags.Delete(deleteList);
```

**Comment by cwilby** [comment]
Ah I'm sorry, I confused this library with https://entityframework-extensions.net/update-from-query.

I ultimately ended up going with a sproc so I could do

```sql
CREATE TYPE ContactTagsParams TABLE (ContactId int not null, TagId int not null);

CREATE PROCEDURE p_Contacts_RemoveTags
  @contactTags ContactTagsParams
AS
BEGIN
  DELETE FROM Contact_Tag
  WHERE (ContactId, TagId) in (select (ContactId, TagId) from @contactTags);
END
```

**Comment by borisdj** [comment]
Besides BulkDelete, example being:
`db.ContactTags.BulkDelete(deleteList);`
library also has extension for BatchDelete, example:
`context.ContactTags.Where(a => a.TagId = tagId).BatchDelete();`
More Info in the ReadMe.
