### ISSUE TITLE
Better error message when encountering Received an invalid column length from the bcp client for colid XXXX

### ISSUE THREAD

**Issue by RubberChickenParadise** [borisdj/EFCore.BulkExtensions#559]
The issue is because of a data field that is too long for a column.  However, with out access to the raw bulk copy instance getting a more useful error message than the column ID is impossible.

With access to the Bulk Copy something like the following could be used to determine which column number is at fault:

```

try
{
    bulkCopy.WriteToServer(importTable);
    sqlTran.Commit();
}    
catch (SqlException ex)
{
    if (ex.Message.Contains("Received an invalid column length from the bcp client for colid"))
    {
        string pattern = @"\d+";
        Match match = Regex.Match(ex.Message.ToString(), pattern);
        var index = Convert.ToInt32(match.Value) -1;

        FieldInfo fi = typeof(SqlBulkCopy).GetField("_sortedColumnMappings", BindingFlags.NonPublic | BindingFlags.Instance);
        var sortedColumns = fi.GetValue(bulkCopy);
        var items = (Object[])sortedColumns.GetType().GetField("_items", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sortedColumns);

        FieldInfo itemdata = items[index].GetType().GetField("_metadata", BindingFlags.NonPublic | BindingFlags.Instance);
        var metadata = itemdata.GetValue(items[index]);

        var column = metadata.GetType().GetField("column", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).GetValue(metadata);
        var length = metadata.GetType().GetField("length", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).GetValue(metadata);
        throw new DataFormatException(String.Format("Column: {0} contains data with a length greater than: {1}", column, length));
    }

    throw;
}

```

(copied from https://stackoverflow.com/questions/10442686/received-an-invalid-column-length-from-the-bcp-client-for-colid-6).

Would it be possible to incorporate this error handling logic (with the table name as well as the column) to help users of the library better track down the field that is too long?

**Comment by borisdj** [comment]
How to reproduce this exception?

I just made a Test where string property has value with more chars then column in Db and it throws:

>     System.InvalidOperationException : The given value 'info f7a01234567890123456789' of type String from the data source cannot be converted to type nvarchar for Column 2 [Description] Row 127.
>     ---- System.InvalidOperationException : String or binary data would be truncated in table '[dbo].[Item]', column 'Description'. Truncated value: 'info f7a012345678901'.

It gives all needed info.
