### ISSUE TITLE
Create extension method

### ISSUE THREAD

**Issue by Inlustris** [borisdj/EFCore.BulkExtensions#56]
I'm trying to create an override for the BulkInsert function. In my dbcontext I use an override on SaveChanges() where i edit several properties of the object and return the base.SaveChanges();

Is it possible to create this for the bulklinsert?

**Comment by borisdj** [comment]
BulkOps are not calling `SaveChanges()` method so overriding it won't have any effect.
You could override extension methods, I use that for setting AuditInfo
Example:
```C#
public static class MyContextBulkExtensions
{
    public static Task BulkInsertAsync<T>(this CoreContext context, IList<T> entities, BulkConfig bulkConfig = null, Action<decimal> progress = null) where T : class
    {
        context.SetAuditInfo<T>(entities);
        return ((DbContext)context).BulkInsertAsync(entities, bulkConfig, progress);
    }

    public static Task BulkUpdateAsync<T>(this CoreContext context, IList<T> entities, IList<T> previousEntities, BulkConfig bulkConfig = null, Action<decimal> progress = null) where T : class
    {
        context.SetAuditInfo<T>(entities, previousEntities);
        return ((DbContext)context).BulkUpdateAsync(entities, bulkConfig, progress);
    }
}
```
SaveChanges, that is call when regular EF is used, has it's own logic for setting AuditInfo.
For example on Update it's using ChangeTracker modified Entries and Metadata Property.OriginalValue.

**Comment by Inlustris** [comment]
Hi Borisdj

Thank you for your information. With those statics i can set the properties i want to set before the items get saved to the database. 

The change tracking in EF is indeed a problem that's why i started using EFCore.BulkExtensions.
