### ISSUE TITLE
5.2.2 BulkInsert Guid field wrong value

### ISSUE THREAD

**Issue by kgamecarter** [borisdj/EFCore.BulkExtensions#560]
5.2.2 BulkInsert Guid field wrong value
rollback to 5.2.1 will fine.

**Comment by borisdj** [comment]
What is your use case and could you make a Test, or alter the following one, where it would be reproducible.
Take a look at https://github.com/borisdj/EFCore.BulkExtensions/blob/1a9c62a792d299bdc9326ce84df3c4e6335e1237/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L19
Lines
https://github.com/borisdj/EFCore.BulkExtensions/blob/1a9c62a792d299bdc9326ce84df3c4e6335e1237/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L49-L54
In 5.2.2 change was
from
```
if (listHasAllDefaultValues)
{
    DefaultValueProperties.Add(propertyWithDefaultValue.Name);
}
```
to
```
if (listHasAllDefaultValues || PrimaryKeysPropertyColumnNameDict.ContainsKey(propertyWithDefaultValue.Name))
{
    DefaultValueProperties.Add(propertyWithDefaultValue.Name);
}

// it is not feasible to have in same list simultaneously both entities groups With and Without default values,
// they are omitted OnInsert only if all have default values or if it is PK (like Guid DbGenerated)
```

**Comment by kgamecarter** [comment]
Yes, my PK has default value.
```C#
var order = builder.Entity<Order>();
order.Property(o => o.Id).HasDefaultValueSql("newsequentialid()"); // Id is Guid
```
But I want to BulkInsert my value.
seems like #563. But `SqlBulkCopyOptions.KeepIdentity` not work for me

**Comment by borisdj** [comment]
I'm still not able to reproduce your issue.
Previously mentioned Test _ComputedAndDefaultValuesTest_ has **_BulkInsert_** of **Document** entity list where property **DocumentId** `.HasDefaultValueSql("NEWID()")`; // same is with newsequentialid()
And it passes successfully.
Try to alter that test and make your case reproducible.
