### ISSUE TITLE
How to modify only specified fields？

### ISSUE THREAD

**Issue by kinglinglive** [borisdj/EFCore.BulkExtensions#561]
![image](https://user-images.githubusercontent.com/50543168/120162002-87f00080-c22a-11eb-8a22-995216de71f8.png)
I specified it like this, but it didn't work. The enumerated value in the entity will still appear in the modified field.

**Comment by kgamecarter** [comment]
try
```C#
.BatchUpdateAsync(o => new OwnerInfo { FollowState = dto.FollowState, PayState = dto.PayState });
```

**Comment by kinglinglive** [comment]
@kgamecarter thank you
