### ISSUE TITLE
Cannot update identity column error after update EFCore.BulkExtensions version

### ISSUE THREAD

**Issue by lesianocmn** [borisdj/EFCore.BulkExtensions#562]
Hello,

I updated EFCore.BulkExtensions version to the latest one and now when I try to do a BulkInsertOrUpdate I receive this message:

Cannot update identity column "id"

Before the update it was working.
On OnModelCreating function it is created like this:

```
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
          modelBuilder.Entity<PlannedBudgetByPtypo>(entity =>
            {
                entity.HasKey(e => new { e.idS, e.idP});
                entity.ToTable("InfoTable");
                entity.HasIndex(e => e.id).HasDatabaseName("IX_ID").IsUnique();
                entity.Property(e => e.idS).HasColumnName("idS");
                entity.Property(e => e.idP).HasColumnName("idP");
                entity.Property(e => e.id) .ValueGeneratedOnAdd();
            });
}
```

Was something changed? I was using the 3.1.0 version and it was working. How to solve this?

Thanks

**Comment by borisdj** [comment]
Can you write Test example with code snipped where the issue would be reproducible.

**Comment by lesianocmn** [comment]
Hi @borisdj ,
Thanks for trying to help me.
The table has two primary keys (idS, idP), id is a identity field and it's not primary. When I try to update it the id value is 0. (Also tried to do the update with the correct value but still giving the same error).

**Comment by lesianocmn** [comment]
Hi @borisdj 

Adding the id field to the PropertiesToExclude seems to work:
```

   var bulkConfig = new BulkConfig()
    {
         PropertiesToExclude= new List<string> { "id" }          
    };

  context.BulkInsertOrUpdate(changeIds, bulkConfig);
```

Testing in the 3.1.0 version still working without the PropertiesToExclude configuration.

**Comment by borisdj** [comment]
There've been some changes and now Ident. col, that is not PK is not Excluded by default, it needs explicit Exclude as you have already done.
