### ISSUE TITLE
Keep identity id for a Bulk insert

### ISSUE THREAD

**Issue by jona-1993** [borisdj/EFCore.BulkExtensions#563]
Hi,

I would like to create an import method for copy each tables to another databases (sqlite or sqlserver). 
It works fine but I have an issue. When I call BulkInsert, each 
identifiers change.  So, when I have a foreign key, I have an exception because my identifiers doesn't exists.

How can I keep my Ids values ?

```
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int MyID { get; set; }
```

```
public BulkConfig options = new BulkConfig() { SetOutputIdentity = true };

 for (int i = 0; i < MaxElem; i += Math.Abs(Math.Min(Temporisation, MaxElem - i)))
                        {
                            var insert = Enumerable.Take(Enumerable.Skip(enumerable, i), Math.Abs(Math.Min(Temporisation, MaxElem - i))); // My entities are dynamic

                            DbContextBulkExtensions.BulkInsert(this, Enumerable.ToList(insert), options); // My Ids are overwrite

                            //this.AddRange(insert); // I keep my ids

                            //this.SaveChanges();

                            this.DetachAllEntities(true);

                            dbContext.DetachAllEntities(true);

                            this.WaitForResources();
                        }
                    }
```

**Comment by borisdj** [comment]
Did you try to leave `SetOutputIdentity` to *false*, that should keep IDs unchanged in memory after Insert.

**Comment by jona-1993** [comment]
Same issue with SetOutputIdentity = false.

ERROR: SQLite Error 19: 'FOREIGN KEY constraint failed'.

I verified that with sqlite studio and I have the issue.

**Comment by jona-1993** [comment]
I found my issue. We have to use SqlBulkCopyOptions = Microsoft.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity;

It's great now.

Have a nice day !

**Comment by borisdj** [comment]
Glad you sorted it.

**Comment by Montago** [comment]
> I found my issue. We have to use SqlBulkCopyOptions = Microsoft.Data.SqlClient.SqlBulkCopyOptions.KeepIdentity;
> 

I wish that this was highlighted somewhere in the documentation for EFCore.BulkExtensions ... took me quite some time to find !

**Comment by borisdj** [comment]
It is stated in the ReadMe:

> If need to set Identity PK in memory, Not let DB do the autoincrement, then need to use **KeepIdentity**:
`var bulkConfig = new BulkConfig { SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity };`

**Comment by Montago** [comment]
Yeah i see that now. 

I was searching for "Identity Insert" because that's what its called in SQL Sever.
