### ISSUE TITLE
Unable to use bulk read with owned type

### ISSUE THREAD

**Issue by sandeepk87** [borisdj/EFCore.BulkExtensions#566]
Hi,
I am trying to use bulk read filter by owned type value in MSSQL.

  `
        
       public class User : Entity
       {
        protected User (){}
        public User(string name, EmailAddress email)
        {
            Name = name;     
            Email = email;
        }
        public void Update(string name, EmailAddress email)
        {
          Name = name;
          Email = email;
        }

        public string Name { get; private set; }
        public  EmailAddress Email { get;  set; }
       }

        [Owned]
       public class EmailAddress :ValueObject
       {
        public string Value { get; }

        public EmailAddress(string value)
        {
            if (EmailValidator.IsValid(value) == false)
                throw new  EmailAddressIsNotValidException( value);
            Value = !string.IsNullOrWhiteSpace(value) ? value.ToLowerInvariant() : value;
        }

        protected EmailAddress()
        {

        }
        public override string ToString()
        {
            return Value;
        }

        protected override IEnumerable<object> GetEqualityComponents()
        {
            yield return Value;
        }
        }

   `
  
  I am trying to query User Table filter by email list - 
  
    ` var entities = emailList.Select(f => new User(null, new EmailAddress(f))).ToList();
      var bulkConfig = new BulkConfig() { UpdateByProperties = new List<string>() { nameof(User.Email) } };
      await _context.BulkReadAsync(entities, bulkConfig);
   `
 
  I am getting error - "**Sequence contains no matching element**"
  
  Is there any other config to be set while using owned type? 

  Library Version -
   "EFCore.BulkExtensions" Version="5.1.8" 
   "Microsoft.EntityFrameworkCore" Version="5.0.5"

**Comment by borisdj** [comment]
Not supported currently.

**Comment by borisdj** [comment]
Should be fixed with v6.5.5.
