### ISSUE TITLE
Snapshot isolation level

### ISSUE THREAD

**Issue by YuliaCher** [borisdj/EFCore.BulkExtensions#567]
Hello,
Is it possible to use Your lib with snapshot isolation level transaction?
During out test (with bulk update) we had such exception:

Microsoft.Data.SqlClient.SqlException: 'Transaction failed because this DDL statement is not allowed inside a snapshot isolation transaction. Since metadata is not versioned, a metadata change can lead to inconsistency if mixed within snapshot isolation.'

**Comment by borisdj** [comment]
Some Sql Commans used in Bulk ops are not allowed inside snapshot isolation
[SE_why-is-it-not-possible-to-create-indexes-on-temp-tables-in-snapshot-isolation](https://dba.stackexchange.com/questions/206804/why-is-it-not-possible-to-create-indexes-on-temp-tables-in-snapshot-isolation)

**Comment by YuliaCher** [comment]
Thank you for your explanation.
