### ISSUE TITLE
UpdateByProperties with join condition on parent table

### ISSUE THREAD

**Issue by qvsmith** [borisdj/EFCore.BulkExtensions#570]
Hope I'm not missing something glaringly obvious.

I'd like to do a bulk update and add a condition that limits rows based on parent table column value. I'm assuming entries are added to a temp table and then updated based on either **ID** column or specified properties in `UpdateByProperties`.

How can I add a condition like `childEntity.ParentEntity.ColumnA = "value"` so that the update will end up something like example below?

Example:
```sql
UPDATE ChildTable
    SET IncludedProperty = tmp.IncludedProperty
FROM ChildTable c
JOIN TmpChildTable tmp ON c.UpdateByProperty = tmp.UpdateByProperty
JOIN ParentTable p ON c.ParentFk = p.Id
WHERE p.ColumnA = 'value';
```

Btw thanks for a great lib 👍

**Comment by borisdj** [comment]
You can't combine Bulk ops with Join from another table as in your example.
What you could try, is load needed data in memory, using either regular Select or BulkRead, then Filter your list before calling BulkUpdate.
You are welcome.
