### ISSUE TITLE
Return all existing entities from BulkRead

### ISSUE THREAD

**Issue by JiriRichter** [borisdj/EFCore.BulkExtensions#571]
Hi,
This is a suggestion, not an issue.
In our project, we needed a function very similar to BulkRead but a version which would return all matching entities. Basically, a method that would under the hood call a copy of the SQL adapter ReadAsync method, skip the tableInfo.UpdateReadEntities and return existingEntities. The BulkRead, in its current implementation, is not really an alternative to using .Contains/IN which will return all entities matching the criteria while BulkRead will only return the first.

**Comment by borisdj** [comment]
Will consider it but I'm not sure how to implement it.
Can you write example of what you want you need to achieve and also if you feel up to it could try to make a PR.

**Comment by JiriRichter** [comment]
I have this functionality implemented on top of EFCore.BulkExtensions lib. Luckily all the key classes are public. I'll try to make a PR with the proposed changes to the BulkRead operation.

**Comment by Innotech-Ameen-Alqattow** [comment]
Hi 
I have the same logic needed and i do same like @JiriRichter 
and i have a suggestion to make GetDataTable public because i needed with custom logic

**Comment by Tyler-V** [comment]
This sounds like it would be useful :)

**Comment by ignj** [comment]
just found this issue. would be great to have this feature

**Comment by borisdj** [comment]
`GetDataTable` was made public, and will review any PR made regarding this proposal.

**Comment by borisdj** [comment]
PR was merged.
BulkConfig now has _**ReplaceReadEntities**_.
