### ISSUE TITLE
BulkReadAsync does not update GUID property

### ISSUE THREAD

**Issue by fscavo** [borisdj/EFCore.BulkExtensions#573]
Since the version 3.4.4 the following code is no longer working:

await dbContext.BulkReadAsync(logs, new BulkConfig { UpdateByProperties = new List<string> { nameof(ReplicationLogDbEntity.EventName) } });

The property Id (GUID) in the logs does not get updated by the operation BulkReadyAsync. It works fine in previous versions.

**Comment by borisdj** [comment]
Did you try with latest version.
Also are you using SqlServer or Sqlite?
I've made changes to _EfCoreBulkTest_ **_RunRead_** method that passes for this use case, so try to alter that test or make a new one where the issue would be reproducible.
