### ISSUE TITLE
Update using join

### ISSUE THREAD

**Issue by Oion71** [borisdj/EFCore.BulkExtensions#576]
Hi

I am wondering if there is a way to update using join, e.g., some like below SQL

UPDATE	TA
SET		Col2 = TB.Col2
FROM	dbo.TableA TA
		INNER JOIN dbo.TableB TB ON TB.Col1 = TA.Col1

**Comment by borisdj** [comment]
Not directly.
You could try to use first **_BulkRead_** and get List from _TableA_ but it would need to have uniqee values for match.
And then make second call to _**BulkUpdate**_ for _TableB_.

Other option would be custom method called with `ExecuteSqlRaw` like:
```C#
public string GetSqlUpdateJoin(string table1 string table2, string columnUpdate, string columnMatch)
{
  var q = $"UPDATE T1 " +
          $"SET T1.{columnUpdate} = T2.{columnUpdate} " +
          $"FROM {table1} T1 " +
          $"INNER JOIN {table2} T2 ON T1.{columnMatch} = T2.{columnMatch}";
  return q;
}
```
If columns do not have same names, then replace columnUpdate with 2 args string _columnUpdate1, string columnUpdate2_.
Same for _columnMatch_ if requried.
