### ISSUE TITLE
User import use case with Bulk Insert

### ISSUE THREAD

**Issue by mkgn** [borisdj/EFCore.BulkExtensions#578]
I have the user table with 35 columns. Out of those, 3 columns are foreign keys to other tables. There is a need for me to insert about 50,000 users to this table. These data comes from an XL and users will be uploading it to our application with a given UI. Since I am using hangfire, I can do a background insert. But I am wondering whether I should break down the 50,000 entities to about 100 or so at a time.

Do you have any guidelines that I should think about?

**Comment by borisdj** [comment]
If you want to use BulkInsert method for that, then no need to split it. For Bulk ops 50K is not too big, it should be done in few seconds.
Also to note that SqlBulkTool has internal BatchSize config with default value of 2000.
