### ISSUE TITLE
BulkInsertOrUpdate with another comparison column

### ISSUE THREAD

**Issue by SelakaKithmal** [borisdj/EFCore.BulkExtensions#579]
My data table : **AspUser (Id, UserName, Email, NormalizedEmail)** Where Id is auto generated guid. 
Im using  BulkInsertOrUpdate method. 

**What I need to archieve :** 

In my case I want to add data if not exsisting in the database. But the comaparison should be done using Id column as well as 
UserName column. 

in that case if the BulkInsertOrUpdate method passed with changed data for NormalizedEmail field it should update it accordingly without adding a new record.

**Snap shot of the table:**

![image](https://user-images.githubusercontent.com/22972311/123399950-da6ed380-d5c2-11eb-8c96-9f21b0740aa4.png)

**Code:**

```
List<AspNetUser> aspUserList = new List<AspNetUser>();

            foreach(var user in usersList)
            {
                var usr = new AspNetUser { Email = user.Email, NormalizedUserName = user.NormalizedUserName, UserName = user.UserName, Id = Guid.NewGuid().ToString() };
                aspUserList.Add(usr);
            }

            using (var transation = _context.Database.BeginTransaction())
            {

                var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { "NormalizedUserName", "Email", "UserName" }, PropertiesToExcludeOnUpdate = new List<string> { "Id"  } };
                _context.BulkInsertOrUpdate(aspUserList, bulkConfig);
                transation.Commit();
            }
```

Is it archievable using the BulkConfig properties? 
If Yes what should be the ideal combination which in need to specify in config?

**Comment by borisdj** [comment]
You should just set _UpdateByProperties_ with those 2 columns:
`UpdateByProperties = new List<string> { "NormalizedUserName", "Email", "UserName" }`

**Comment by SelakaKithmal** [comment]
Can you provide me the actual config which needs to be passed to it?

**Comment by borisdj** [comment]
`var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { "Id", "UserName" } };`
and this should be enough.
With that config _BulkInsertOrUpdate_ will update those that match both columns in list and others will be Inserted.

**Comment by SelakaKithmal** [comment]
Thanks it worked..
