### ISSUE TITLE
Bulk insert not working if the column type is boolean with default value

### ISSUE THREAD

**Issue by alphaCoder** [borisdj/EFCore.BulkExtensions#580]
Effected version: [3.6.1](https://www.nuget.org/packages/EFCore.BulkExtensions/3.6.1)

Hi All,

I am unable to bulk insert data when one of my column type is boolean with default value as **true** and my data has the value as **false**. Please find below are the steps/setup to reproduce this issue. I appreciate any help and please let me know if you need any additional information.

I have the following table structure:
```
CREATE TABLE [dbo].[Location](
	   LocationId BIGINT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Location_LocationId PRIMARY KEY (LocationId), 
           LocationString VARCHAR(100) NOT NULL,
	   IsEnabled BIT NOT NULL CONSTRAINT DF_Location_IsEnabled DEFAULT (1),
)
GO
```

EF Entity:
```
public class Location {
  public long LocationId {get; set;}
  public string LocationString {get; set;}
  public bool IsEnabled {get; set;}
}
```
sample data:
```
var locations = new List<Location>{ new Location { LocationString="Abc123", IsEnabled=false}};
_database.BulkInsert(locations, new BulkConfig { IncludeGraph = true });  // I do have dependent entities, I am not including it here to keep my example simple
```
I am getting the following exception:
System.InvalidOperationException: 'PropertyName 'IsEnabled' specified in 'PropertiesToExclude' not found in Properties.'

Upon further investigation I found the below line in the TableInfo.cs file caused the issue:

```
bool listHasAllDefaultValues = !entities.Any(a => a.GetType().GetProperty(propertyWithDefaultValue.Name).GetValue(a, null)?.ToString() != instance?.ToString());
```
The above line is returning true when IsEnabled set to **false** and when the below lines are executed the validation fails and getting the above exception

```
if (AreSpecifiedPropertiesToExclude)
                {
                    properties = properties.Where(a => !BulkConfig.PropertiesToExclude.Contains(a.Name));
                    ValidateSpecifiedPropertiesList(BulkConfig.PropertiesToExclude, nameof(BulkConfig.PropertiesToExclude));
                }
```
**Note:** I am able to insert data successfully if the IsEnabled flag is set to true.

**Comment by borisdj** [comment]
I have created table Location and added it's entity and it works.
Can you write entire Test to reproduce the issue.

**Comment by alphaCoder** [comment]
Sorry for the delayed response. I have the following config as part of the model builder in my context class. If I remove HasDefaultValueSql line everything started working. Do you have a similar setup like this when you tried to reproduce the issue?
```
modelBuilder.Entity<Location>(entity =>
            {
                entity.Property(e => e.IsEnabled)
                    .IsRequired()
                    .HasDefaultValueSql("((1))"); // It works if this line is removed
                //... other properties
            }
```
Thank you for all the help.

**Comment by borisdj** [comment]
Still unable to reproduce it, issue could be due to those dependent entities.
Try write entire Test and include those as well.
