### ISSUE TITLE
Working with ApiAuthorizationDbContext and EFCore.BulkExtensions

### ISSUE THREAD

**Issue by MARKUSER** [borisdj/EFCore.BulkExtensions#581]
I have an applicationDBcontext derived from ApiAuthorizationDbContext class (Not regular DbContext class). May i know how to call BulkInsert method from BulkExtensions framework ? I am using EF Core 5.0.7, BulkExtensions 5.2.5 version.

public class AppDbContext : ApiAuthorizationDbContext<ApplicationUser>, IAppDbContext
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IDateTime _dateTime;

       
        public AppDbContext (
            DbContextOptions options,
            IOptions<OperationalStoreOptions> operationalStoreOptions,
            ICurrentUserService currentUserService,
            IDateTime dateTime) : base(options, operationalStoreOptions)
        {
            _currentUserService = currentUserService;
            _dateTime = dateTime;
        }
//this is for EF core save.
public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
        {
            
            var result = await base.SaveChangesAsync(cancellationToken);

            return result;
        }

Please advise.

**Comment by borisdj** [comment]
**ApiAuthorizationDbContext** is also derived has from **_DbContext_** class in its enheretance hierarchy.
So there is no difference there.
Regarding usage of Bulk info is in the ReadMe and its as simple as:
`context.BulkInsert(entitiesList);`

**Comment by MARKUSER** [comment]
Thank you so much for your prompt help.

Sorry i didn't mentioned what i tried before. As mentioned in ReadMe I have implemented like below in **AppDbContext** class but is throwing exception. Please note that i am trying to invoke from **base** class.

![image](https://user-images.githubusercontent.com/17166706/124131436-cc4f0600-da4d-11eb-9726-94d7696c4599.png)

If it is a normal save (without bulkinsert library) then i am doing like below as mentioned in my initial request.

public override async Task SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken())
{

        var result = **await base.SaveChangesAsync(cancellationToken);**


        return result;
    }


Handler in application layer will call SaveChangesAsync through interface (IAppDbContext). IAppDbContext looks like below.

    public interface IAppDbContext 
    {
        DbSet<Product> productlists { get; set; }    

        Task<int> SaveChangesAsync(CancellationToken cancellationToken);

        Task BulkInsert();
    }

Please kindly let me know if i am still missing some thing here.

**Comment by borisdj** [comment]
If you already didn't set **using** you need to add
`using EFCore.BulkExtensions;`
Then call from Context class would be:
`await this.BulkInsertAsync(list);`

**Comment by MARKUSER** [comment]
Thank you so much borisdj for your help. I had used using statement before but i was trying to invoke through base class. Now it is working with "this".
