### ISSUE TITLE
BulkInsertOrUpdate inserts wrong value into discriminator column

### ISSUE THREAD

**Issue by maxkoshevoi** [borisdj/EFCore.BulkExtensions#582]
I have a table that stores values from two child classes `C1` and `C2` of parent class `P`. It has a discriminator column:

```cs
builder.HasDiscriminator<string>("ClassType")
    .HasValue<C1>("Type1")
    .HasValue<C2>("Type2");
```

When I insert rows in a regular way `DbSet.Add()` value in `ClassType` is set correctly (either `Type1` or `Type2`), but when I use `BulkInsertOrUpdate` it always sets it to `P` (name of the base class).
 
**Update**: 

Found the reason why type name is inserted: https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs#L603

As for why it's base type instead of real (child) type. `context.Model.FindEntityType(type)` returns `P Abstract` (not null), so `HasAbstractList` is set to `false`, and `typeof(T)` is `P` since `BulkInsertOrUpdateAsync` was called in a method that processes both child classes.
- https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/TableInfo.cs#L101
- https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs#L442

**Comment by borisdj** [comment]
Thx for Contrib.
5.2.6 published
