### ISSUE TITLE
using IncludeGraph leads to stackoverflow exception - probably relates to #520

### ISSUE THREAD

**Issue by AlexSapple** [borisdj/EFCore.BulkExtensions#585]
Hi, 

**v 3.6.1 of bulk extensions** in a .net core 3.1 environment.
 
just tried to use IncludeGraph option. Had a set of entities with relational data/child entities  and previously was doing something along the lines of to handle a bulk set of modifications;

    await _dataContext.Instance.BulkUpdateAsync(meetingEntities, options =>
    {
        options.SetOutputIdentity = true;
        options.PreserveInsertOrder = true;
    }, cancellationToken: cancellationToken);

    //clear the participants before adding back in again.
    List<Participant> bulkParticipants = new List<Participant>();
    foreach (var meeting in meetingEntities)
    {
        foreach (var participant in meeting.Participants)
        {
            participant.MeetingId = meeting.Id;
            bulkParticipants.Add(participant);
        }
    }

    await _dataContext.Instance.BulkDeleteAsync(participantsForDelete, cancellationToken: cancellationToken);
    await _dataContext.Instance.BulkInsertAsync(bulkParticipants, cancellationToken: cancellationToken);

I recently saw the includeGraph option and if I understood correctly, allows me to skip a bunch of this. So I tried;

    await _dataContext.Instance.BulkInsertOrUpdateAsync(meetingEntities, options =>
    {
         options.IncludeGraph = true;
    }, cancellationToken: cancellationToken);

(whether this does the update in the way that I intend is neither here nor there) - but trying this out brings down the process with a stackoverflow exception. I expected this to be something to do with recursive child entities -  I have fully defined relationships i.e. I have a Meeting that has 0 to many Participants, where the relationship between them is fully defined (see https://docs.microsoft.com/en-us/ef/core/modeling/relationships?tabs=fluent-api%2Cfluent-api-simple-key%2Csimple-key#fully-defined-relationships). 

I've nullified the cyclic bits in the entities before calling `BulkInsertOrUpdateAsync()` but I'm still getting the stackoverflow ex. Am I missing something? Any advice would be really appreciated.

**Comment by borisdj** [comment]
Can you make a Test, or to adapt existing one to reproduce this issue.

**Comment by AlexSapple** [comment]
Thanks for the reply @borisdj  - the code I'm running is quite convoluted and part of a complex set of stuff - When I get a moment, I'll try to strip it down to a simple runnable example.
