### ISSUE TITLE
Getting type mismatch when trying to do a BulkInsertOrUpdateOrDeleteAsync on table that contains a geometry column

### ISSUE THREAD

**Issue by magoicochea** [borisdj/EFCore.BulkExtensions#591]
Hello

I have a table that has a column of type geometry on the database (Azure SQL), which stores a coordinate. On my C# code the property of the class is of type NetTopoogySuite.Geometries.Point.

```
        [Column(TypeName = "geometry")]
        public Point LocationPoint { get; set; }
```

I have the following code that calls BulkInsertOrUpdateOrDeleteAsync

```
            var bulkConfig = new BulkConfig
            {
                SRID = 27700,  //British National Grid
                PropertiesToIncludeOnCompare = propertiesToIncludeOnCompare,
                PropertiesToIncludeOnUpdate = propertiesToIncludeOnUpdate
            };            

            await _myDbContext.BulkInsertOrUpdateOrDeleteAsync(assetsToMerge, bulkConfig);
```

After the call is made I get the following error:

_Type of value has a mismatch with column typeCouldn't store <System.Byte[]> in LocationPoint Column.  Expected type is Point._

With the following stack trace

> at System.Data.DataColumn.set_Item(Int32 record, Object value)
>    at System.Data.DataTable.NewRecordFromArray(Object[] value)
>    at System.Data.DataRowCollection.Add(Object[] values)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InnerGetDataTable[T](DbContext context, Type& type, IList`1 entities, TableInfo tableInfo)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDataTable[T](DbContext context, Type type, IList`1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__3`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__3`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__13`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__11`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at MyNamespace.Infrastructure.Repositories.AssetRepository.<MergeAssets>d__3.MoveNext()

Am I missing something on the configuration of the class?

I  am using the following:

- EFCore.BulkExtensions 3.3.3
- EF Core 3.1.17
- .NET Core 3.1
- Azure SQL Server

I tried to update to version 3.61 of EFCore.BulkExtensions, but then I started getting this error

_System.NullReferenceException: 'Object reference not set to an instance of an object.'_

>   ```
>  at EFCore.BulkExtensions.TableInfo.<>c__DisplayClass131_1`1.<LoadData>b__40(T a)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
>    at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
>    at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at MyNamespace.Infrastructure.Repositories.AssetRepository.<MergeAssets>d__3.MoveNext() 
> ```
> 

EDIT:

After updating to 3.4.3 the exception message changed to

_OnCompare properties Config can not be set for Entity with Spatial types like 'Geometry'_

 

>   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InnerGetDataTable[T](DbContext context, Type& type, IList`1 entities, TableInfo tableInfo)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.GetDataTable[T](DbContext context, Type type, IList`1 entities, SqlBulkCopy sqlBulkCopy, TableInfo tableInfo)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__3`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__3`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<InsertAsync>d__3`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__13`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__11`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__2`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at MyNamespace.Infrastructure.Repositories.AssetRepository.<MergeAssets>d__3.MoveNext() 

However, even after removing the spatial column from the list I still get the same exception.

**Comment by borisdj** [comment]
Can you make it reproducable in Test, take a look at
https://github.com/borisdj/EFCore.BulkExtensions/blob/aca2fd786eb46a33b06d2d4ae59ff57d615e6c52/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L591

**Comment by magoicochea** [comment]
Hi

I will take a look and try to reproduce it on a test.

On the meantime I found that the workaround was to load the table in memory, do the comparisons using LINQ and then using the BulkUpdate/BulkInsert/BulkDelete when necessary. This was possible because this table will rarely grow and 99% of the time we are just doing updates.

**Comment by magoicochea** [comment]
I tried to reproduce the bug, but I was not able. It might be something related to my project. You can close this and I will open a new issue if I manage to reproduce it.
