### ISSUE TITLE
Setting multiple columns into UpdateByProperties breaks SetOutputIdentity

### ISSUE THREAD

**Issue by dsidedp** [borisdj/EFCore.BulkExtensions#592]
If BulkConfig looks like the one below, and Prop1 is not unique(but Prop1+Prop2 is unique), then with `SetOutputIdentity = true` identities will be messed up.
```
SetOutputIdentity = true,
UpdateByProperties = new List<string>
{
    nameof(Prop1),
    nameof(Prop2),
}
```
The issue seems to be in TableInfo.GetQueryExpression where only first property is used for ordering in the identity retrieval query
```
expression = ordered 
     ? OrderBy(entityType, expression, PrimaryKeysPropertyColumnNameDict.Select(a => a.Key).First()) 
     : expression;
```

I would assume addition of ThenBy will fix this.

v 5.2.8

**Comment by borisdj** [comment]
I've made a fix for this, take the latest source and check if it works for your case, then I'll publish the NuGet.

**Comment by borisdj** [comment]
v5.2.9 published
