### ISSUE TITLE
BulkInsertOrUpdate - SetOutputIdentity for updated items

### ISSUE THREAD

**Issue by KapoCRO** [borisdj/EFCore.BulkExtensions#595]
Hi,

I'll try my best to explain a situation that we have so, hopefully, someone can suggest us a proper solution to it. To be clear I am not entirely sure that what we need is actually possible with library.

USE CASE
We receive a CSV file from a supplier with a list of products - some of the columns in a CSV are **ProductId**, **ProductName**...

In our DB we have **Products** table that has **Id** (our internal identity, PK) and also it has **ProductId** (one from CSV - basically identifier in a supplier system), **ProductName** etc...

What we would like to do is **BulkInsertOrUpdate**  products from CSV, but in a way that after this method is executed and products are merged in our DB, it fills IDs on both _inserted_ and _updated_ products from a collection cause we need that information later on in process. What we've managed to achieve is to fill IDs only on _inserted_ products and _updated_ products got removed from collection.

```
var bulkConfig = new BulkConfig
{
    UpdateByProperties = new List<string> { $"ProductId" },
    SetOutputIdentity = true,
    PreserveInsertOrder = false
};

var products = new List<Product> 
{
    new Product { ProductId = 1, Name = "Product A" },
    new Product { ProductId = 2, Name = "Product B" }
    //...
}

await _context.BulkInsertOrUpdate(products, bulkConfig);
```

Is this possible without having to do a second call to DB to return all items from collection and acquire their IDs?

**Comment by borisdj** [comment]
Your code seems fine for what you want to achieve.
BulkInsertOrUpdate will **update** those matched by _ProductId_ and others will be **inserted**.
Also since you have configured `SetOutputIdentity` then column **Id** that was generated in Db will be loaded and set in the list for new ones that were inserted.
It works just as you need it, so I'm not sure what exactly is the question.

**Comment by KapoCRO** [comment]
As you mentioned `SetOutputIdentity` loads **Id** of newly _inserted_ products back to the collection. 
Can the same be done for _updated_ products also? 
Cause when we call **BulkInsertOrUpdate** we don't know IDs of products in our DB, we just know ProductId and ProductName from CSV file.

**Comment by borisdj** [comment]
It should load **Id** even of updated.

**Comment by KapoCRO** [comment]
@borisdj It works fine now, for some reason it wasn't working yesterday. Maybe there were some changes I reverted at some point. Anyway thanks for help, great library btw! 👍

**Comment by borisdj** [comment]
Glad you solved it.

**Comment by duszekmestre** [comment]
@borisdj how it works for you? I have same issue and it not working for me :/
