### ISSUE TITLE
BatchUpdate - Use Correct Sql Parameter Type

### ISSUE THREAD

**Issue by RyanThomas73** [borisdj/EFCore.BulkExtensions#596]
When using the `.BatchUpdate(..)` / `.BatchUpdateAsync(..)` the update body sql parameters should have the same .DbType / .SqlDbType that EF uses for queries against the column.

Example:
```
public class Something
{
    private string _phoneNumber;
    public string PhoneNumber { get => _phoneNumber; set => _phoneNumber = value; }
}

public class TestDbContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var somethingEntityBuilder = modelBuilder.Entity<Something>();
        somethingEntitybuilder.Property(something => something.PhoneNumber)
                .HasColumnType("varchar(12)").HasMaxLength(12).HasField("_phoneNumber").IsRequired();
    }
}

public class SomethingService
{
    private readonly TestDbContext _testDbContext;
    
    public async Task DoSomethingAsync(CancellationToken canclleationToken)
    {
        var oldPhoneNumber = "7756789999";
        var newPhoneNumber = "3606789999";
        
        _ = await _testDbContext.Set<Something>()
            // The sql parameter for oldPhoneNumber will be of the correct type (DbType.AnsiString) / SqlDbType.VarChar)
            .Where(something => something.PhoneNumber == oldPhoneNumber) 
            .BatchUpdateAsync(
                 // The sql parameter for newPhoneNumber will not match, and instead will be DbType.String / SqlDbType.NVarChar
                something => new Something { PhoneNumber = newPhoneNumber),
                cancellationToken
            )
            .ConfigureAwait(false);
    }
}

```

@borisdj 
I have a working update ready for the EFCore3.1 branch. It wasn't clear though what your merge strategy is between the 3 different version branches.

Do you update each branch `EFCore2.2`, `EFCore3.1`, and `master` independently? Or do you apply the fix into one branch and then merge the changes from there to the other branches?

**Comment by borisdj** [comment]
Prior branches were created when switch to next versions was made.
They are not actively supported, meaning new features not be integrated there, only some mayor bug fixes.
2.2 is deprecated and on 3.1 there been several commit since split.
So should there be need for updates into both master and 3.1 then separate commits have to be made.
I'll check this PR on 3.1 but if same issue if on 5.0 then changes should copied there also.

**Comment by RyanThomas73** [comment]
Thanks much. I did 3.1 first as that's the version that we require for the time being.

I'll put together a 2nd PR with the equivalent update for the master branch.

**Comment by borisdj** [comment]
Merged,
Thx for Contrib.
