### ISSUE TITLE
IncludeGraph=true within TransactionScope throws 'An ambient transaction has been detected. The ambient transaction needs to be completed before beginning a transaction on this connection.'

### ISSUE THREAD

**Issue by RedBlack** [borisdj/EFCore.BulkExtensions#598]
Hi

We are having an issue with the IncludeGraph=true option within a TransactionScope throwing 'An ambient transaction has been detected. The ambient transaction needs to be completed before beginning a transaction on this connection.'

We are in the process of moving from .Net Framework 4.7.1/EF6.2 to .Net Core3.1/.Net Standard 2.0 and EFCore 3.1.13. I have installed version 3.6.1 of your Bulk Extensions as that is most recent version that targets .Net Standard 2.0.

Our repositories use a Unit of Work so that multiple operations can be looped through and committed in one transaction across different DataContexts and if there are any errors it rolls back everything to a known state

I can replicate the issue in simple terms by doing something like

```c#
using (var scope = new TransactionScope(TransactionScopeOption.Required, new TransactionOptions() { IsolationLevel = IsolationLevel.ReadCommitted },
                TransactionScopeAsyncFlowOption.Enabled))
{
    using (var dataContext = new DataContext(connectionString))
    {
        var bulkConfig = new BulkConfig()
        {
            IncludeGraph = true
        };

        dataContext.BulkInsert(parents, bulkConfig);
    }

}
```
I believe it is related to DbContextBulkTransactionGraphUtil.cs and line:

```c#           
var transaction = context.Database.CurrentTransaction ?? (isAsync ? await context.Database.BeginTransactionAsync() : context.Database.BeginTransaction());
```

I am not sure if there is a way round it currently to get it to work within a TransactionScope? I dont know if it is possible to have a BulkConfig option to not start a transaction when using IncludeGraph=true and let the TransactionScope handle it?

**Comment by borisdj** [comment]
Not sure, IncludeGraph feature was PR, maybe @maitlandmarshall can give more info.
Meanwhile try using BulkOps directly without IncludeGraph.

**Comment by RedBlack** [comment]
Thanks. I downloaded the version and changed it to check for if there is a TransactionScope and then didnt start a new Transaction. This got past the AmbientTransaction issue. 

However it then threw an exception "This platform does not support distributed transactions.". Turns out that .Net Core doesnt support distributed transactions, it is a feature they plan to add in the future. https://github.com/dotnet/runtime/issues/715

We only use the bulk insert for a couple of things so I might have to look into getting it to work outside of our unit of work in this instance

**Comment by borisdj** [comment]
Good idea also.

**Comment by DaveVdE** [comment]
The problem is that the `Transaction.Current` is not checked, which is then used by `RelationalConnection.EnsureNoTransaction()` to verify that no ambient transaction is present. I'd like to see this issue reopened so that at it can be a known issue.

**Comment by DaveVdE** [comment]
I humbly submit https://github.com/borisdj/EFCore.BulkExtensions/pull/988 to deal with this.
