### ISSUE TITLE
Temp Table Clean-Up Question

### ISSUE THREAD

**Issue by altmank** [borisdj/EFCore.BulkExtensions#60]
Hello,

I'm using BulkInsertOrUpdate and unrelated to this library I am sometimes running to data scenarios that cause the operation to fail and then an exception is thrown in my code. Is there a setting I can enable to ensure that this library cleans up any tables that were created in the event of an exception during the operation?

**Comment by borisdj** [comment]
You could set UseTempDB to True in BulkConfig so that SQL itself will do do Drop.
Did you try this already, and are you having situation that some tables are not being dropped?
