### ISSUE TITLE
Bulk Insert Case sensitivity problem with column names

### ISSUE THREAD

**Issue by mzgnr** [borisdj/EFCore.BulkExtensions#61]
bulk insert treats column names case sensitive somewhere
therefore if there is even a single case difference in column name in modelBuilder, the Bulk Inser fails.
for example userID vs userId fails immediately

```
entity.Property(e => e.userId)
                    .HasColumnName("userID")
                    .HasMaxLength(100);
 ```

database column name is `userId`.
C# code refers as `userID`

**Comment by borisdj** [comment]
You have something wrongly configured here.
From what you have written in code snippet PropertyName in Entity is `userId` and method `.HasColumnName("userID")` defines ColumnName in Db as `userID`.
So BulkOps correctly sets that name.
Your comment that 
> database column name is `userId`.

is either incorrect or your Dd does not match EF ModelBuilder configuration.
