### ISSUE TITLE
Question: Should BulkReadAsync be considered for less than 1k rows?

### ISSUE THREAD

**Issue by el2iot2** [borisdj/EFCore.BulkExtensions#613]
There is guidance to only use the bulk inserts/update routines with more thank 1k entities. This makes sense as the cost of creating temporary tables must be considered.

Is this also true for the bulk read? Or can it be used without significant penalty for less than 1k entities? Is there a temporary table involved in this method as well?

**Comment by borisdj** [comment]
BulkRead is done with MERGE, using Temp tables, just like Update so overhead is the same.
