### ISSUE TITLE
How to handle unique index related exceptions with bulk insert?

### ISSUE THREAD

**Issue by mkgn** [borisdj/EFCore.BulkExtensions#614]
Happy scenerio is when doing bulk insert all are new data so it all works fine. Then if we update another list with BulkInsertOrUpdate there may be records already in the table (ex:- Cannot insert duplicate key row in object 'dbo.AspNetUsers' with unique index 'IX_AspNetUsers_Email' ). In this case same email is already in the database and it fails.

Is there any option where we can say not to insert if there are duplicates? Or at least ignore the exceptions and continue with possible inserts/updates?

If not I will have to do lot of data validation queries which may remove the advantage of bulk operations...

Any thoughts?

**Comment by borisdj** [comment]
When doing BulkInsertOrUpdate and having some Unique column, then you could set:
`var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(AspNetUsers.Email) } };`
That way new ones will be inserted and those matched with mail will be updated.

Other option, if you do not want to update existing ones but only insert new, would be to set:
`PropertiesToIncludeOnUpdate = new List<string> { "" }`
This means that no properties are changed on update.

All this with more info is explained in the ReadMe.

**Comment by mkgn** [comment]
Thanks @borisdj . I did went through the ReadMe, but the properties related to this area (PropertiesToIncludeOnUpdate , PropertiesToExcludeOnUpdate  etc..) documentation is a bit confusing. May be a line of code would save lot of your time having to answer similar questions 

So, I tried what you said and it works. One clarification I would need is about the logic if I do something like;

    var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { "prop1", "prop2" } };

In this case, does it compare both columns having unique indexes and update any changes except these two columns? Reason I asked is, I tried two columns, and added a duplicate entry to prop1 column just to see the behavior. In this case it throw an exception saying that you can't insert duplicate values.

Is this the intended behavior?

**Comment by borisdj** [comment]
It's this segment in readme:

> If we want Insert only new and skip existing ones in Db (Insert_if_not_Exist) then use BulkInsertOrUpdate with config `PropertiesToIncludeOnUpdate = new List<string> { "" }`
> 
> Additionaly there is **UpdateByProperties** for specifying custom properties, by which we want update to be done.

I'll extend it with example.

As for having multiple props in `UpdateByProperties` it means that match is done by both columns, effectively like unique constrain based on those 2 columns.
So if in your case you have 2 separate unique indexes, and not combined one, then you should put only one property in this config.
