### ISSUE TITLE
Is there a way to insert the rest of the batch if a foreign key violation occurs?

### ISSUE THREAD

**Issue by snydesc** [borisdj/EFCore.BulkExtensions#615]
When doing a bulk insert if 1 of the entries fails a foreign key constraint the rest of the batch is thrown out.  Is there a way to insert the entries in the batch that do pass the foreign key constraints and just not insert the ones that fail?

**Comment by borisdj** [comment]
Not directly.
You could either load or BulkRead foreign table PKs into memory and remove those that do not exist.
Or another option would be to set config **SqlBulkCopyOptions** with flag _CheckConstraints = false_ that would insert it and after delete those that do not have valid constraint.
