### ISSUE TITLE
BulkInsert with given Identity references to Exception "Value cannot be null. Arg_ParamName_Name"

### ISSUE THREAD

**Issue by SchroeerM** [borisdj/EFCore.BulkExtensions#616]
Hi,

I created an database-copy tool and used the bulk extension for large datasets. Unfortunately tables which have an autoincrement int as primary key cant be inserted with bulkinsert. If I set the config for SetOutputIdentity = true I receive the Exception "Value cannot be null. Arg_ParamName_Name". Do I miss any necessary parameter or sth?

Thanks, Michael

**Comment by borisdj** [comment]
If Identity PKs are already set in memory then you should configure _SqlBulkCopyOptions_ with **KeepIdentity**:
`var bulkConfig = new BulkConfig { SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity };`
