### ISSUE TITLE
Bulk InsertOrUpdate with conditional matching?

### ISSUE THREAD

**Issue by aloksharma1** [borisdj/EFCore.BulkExtensions#617]
Hello,

In My Scenario I have the following table :

```
public new Guid Id { get; set; } = Guid.NewGuid();
public string Question { get; set; }
public string Answer { get; set; }
public int SortOrder { get; set; }
public Guid GroupId { get; set; }
public Guid OrganizationId { get; set; }
public string UniqueOrgName{ get; set; }
public bool IsActive{get;set;}
```

Here Organizations can differ but some unique properties will be same for these organizations, i want to update or insert record only when it filters correctly on the basis of UniqueName+Id [Sql already have filter column composit key] only when `isActive=true`.

how to do this with `bulkconfig`
awaiting your reply.

**Comment by borisdj** [comment]
As stated in the ReadMe:

> Additionaly there is UpdateByProperties for specifying custom properties, by which we want update to be done.
> When setting multiple props in UpdateByProps then match done by columns combined, like unique constrain based on those cols.

So if your case you can use:
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { "Id", "UniqueOrgName", "IsActive" } };

**Comment by aloksharma1** [comment]
@borisdj one question this should only match if isactive is true and not otherwise [isactive false means we have to insert record as new].

**Comment by borisdj** [comment]
Bulk ops do not have directly analogy for filtered index.
One thing you could try is to insert only IsActive:TRUE
