### ISSUE TITLE
Sqlite is not currently supported due to its BulkInsert implementation.

### ISSUE THREAD

**Issue by jsuag** [borisdj/EFCore.BulkExtensions#618]
I'm trying to execute the BulkInsertOrUpdateAsync function over a Sqlite but it doesn't work.
This is how I'm creating the context:
![image](https://user-images.githubusercontent.com/79586393/129819061-5be84fdc-81a9-417c-976b-e15eb473effc.png)

Does SQLite support these bulk operations?

**Comment by borisdj** [comment]
What exactly is the exception, and can you write a test where the issue would be reproducible.

**Comment by jsuag** [comment]
This is the exact exception; System.NotSupportedException: 'Sqlite is not currently supported due to its BulkInsert implementation.' It happens when executing the BulkInsertOrUpdateAsync function whit the IncludeGraph option.

**Comment by jsuag** [comment]
using EFCore.BulkExtensions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System;
using System.Data.Common;
using System.Linq;
using System.Threading.Tasks;

namespace NetCoreConsole
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var connection = await CreateConnectionAsync();
            var dbContext = await CreateContextAsync(connection);
            var states = Enumerable.Range(1, 10).Select(x => new State 
            {
                Id = x,
                Code = $"st-{x}",
                Name = $"state-{x}",
                City = new City
                {
                    Id = x,
                    Code = $"ct-{x}",
                    Name = $"city-{x}",
                }
            });

            await dbContext.BulkInsertOrUpdateAsync(states.ToList(), new BulkConfig { IncludeGraph = true });
            Console.WriteLine($"There are {dbContext.States.Count()} State rows!");
        }

        public static async Task<DbConnection> CreateConnectionAsync()
        {
            var connection = new SqliteConnection("Filename=:memory:");
            await connection.OpenAsync();

            return connection;
        }

        public static async Task<TestDbContext> CreateContextAsync(DbConnection connection)
        {
            var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();
            optionsBuilder.UseSqlite(connection);
            SQLitePCL.Batteries.Init();

            var context = new TestDbContext(optionsBuilder.Options);
            await context.Database.EnsureDeletedAsync();
            await context.Database.EnsureCreatedAsync();

            return context;
        }

        public class TestDbContext : DbContext
        {
            public DbSet<State> States { get; set; }

            public TestDbContext(DbContextOptions options) : base(options) { }
        }

        public class State
        {
            public int Id { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }

            public int CityId { get; set; }
            public City City { get; set; }
        }

        public class City
        {
            public int Id { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }
        }
    }    
}

**Comment by jsuag** [comment]
This is a simple console program to reproduce the error.

[Program.txt](https://github.com/borisdj/EFCore.BulkExtensions/files/7008878/Program.txt)

**Comment by borisdj** [comment]
Sqlite does not support IncludeGraph.
