### ISSUE TITLE
Support for non public setter of PK and 'PreserveInsertOrder'

### ISSUE THREAD

**Issue by MaciejWierzchowski** [borisdj/EFCore.BulkExtensions#62]
Hi,

I have an entity where the primary key has a public get and private set:

```
public class Entity 
{
    public int Id {get; private set;}
}
```

I'm not able to do a bulk insert on this with `PreserverInsertOrder`, because of this:
https://github.com/borisdj/EFCore.BulkExtensions/blob/6ecd7a798106090e07bae3982d74e69766b1a6b4/EFCore.BulkExtensions/TableInfo.cs#L279-L286

It creates the accessor that handles only fully public properties. 

I *think* that the fix should be as simple as changing to following:

`TypeAccessor.Create(typeof(T), true); `

**Comment by borisdj** [comment]
Fix incorporated into the library and NuGet 2.1.7 published.
