### ISSUE TITLE
BulkInsertOrUpdateOrDelete with IncludeGraph and duplicates

### ISSUE THREAD

**Issue by WORMrus** [borisdj/EFCore.BulkExtensions#621]
When a graph of entities is included, they are deduplicated at https://github.com/borisdj/EFCore.BulkExtensions/blob/b7559317540c3c6b2e21d5ae3e2982819da8152b/EFCore.BulkExtensions/DbContextBulkTransactionGraphUtil.cs#L69

This does not seem to work if there are UNIQUE constraints other than just the PK.

Consider this model:

```
    [Index(nameof(IPStart), nameof(IPEnd), IsUnique = true)]
    public class IPGeolocation
    {
        public int IpGeolocationId { get; set; }

        public uint IPStart { get; set; }
        public uint IPEnd { get; set; }

        public int CountryId { get; set; }
        public Country Country { get; set; }

        public int RegionId { get; set; }
        public Region Region { get; set; }

        public int CityId { get; set; }
        public City City { get; set; }

    }

    [Index(nameof(Name), IsUnique = true)]
    public class City
    {
        public int CityId { get; set; }

        [Column(TypeName = "varchar(128)")]
        public string Name { get; set; }
    }
    //Region and Country are defined in the same exact way
```

This represents IP rages and their respective geolocation. There can be many cities, regions, and, probably countries with the same name. 

Therefore the deduplication should probably be done not only by the PK but also by any other unique fields to avoid errors on insert. Is that correct? 

I could look into fixing this myself (and probably will for my local project), but I'm somewhat afraid of missing some non-trivial general cases.

**Comment by borisdj** [comment]
IncludeGraph feature was accepted as PR, so if you manage to make a test for reproduction and a fix you can make a new PR.
