### ISSUE TITLE
ArgumentOutOfRangeException on simple batch delete query

### ISSUE THREAD

**Issue by fschick** [borisdj/EFCore.BulkExtensions#623]
The exception occurs when using a PostgreSQL or MySQL database. Not sure, if you like to support databases other than SqlServer and Sqlite. At least, there is a comment in the code SqlServerDialect.cs, line 36:
`var isSqlServer = true;  // SqlServer : PostrgeSql; // TODO change to specific type`
A minimal example to reproduce the exception: [EFCore.BulkExtensions.ReproduceIssue532.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7019954/EFCore.BulkExtensions.ReproduceIssue532.zip)

_Originally posted by @fschick in https://github.com/borisdj/EFCore.BulkExtensions/issues/532#issuecomment-902504666_

**Comment by borisdj** [comment]
Dupe: https://github.com/borisdj/EFCore.BulkExtensions/issues/67
