### ISSUE TITLE
Multiple levels of owned entities cause incorrect state when doing bulk insert

### ISSUE THREAD

**Issue by armw1** [borisdj/EFCore.BulkExtensions#624]
Minimal reproduction is here:
https://github.com/armw1/BulkInsertBug

As you see in there repo bulk inserting Person_Bug causes FirstName and LastName to be null.

**Comment by borisdj** [comment]
Only first level of Composition is supported.
You could try a workaround explained: https://github.com/borisdj/EFCore.BulkExtensions/issues/167#issuecomment-476737959 Dupe
