### ISSUE TITLE
MissingMethodException: Constructor on type ‘xxx’ not found.

### ISSUE THREAD

**Issue by Nokecy** [borisdj/EFCore.BulkExtensions#627]
https://github.com/borisdj/EFCore.BulkExtensions/blob/f2c9b0fa8ea5fa072378b8a549ad936131c5798d/EFCore.BulkExtensions/Helpers/GenericsHelpers.cs#L21

my default Constructor  is be protected

**Comment by borisdj** [comment]
Fixed with v5.3.8
