### ISSUE TITLE
Shadow property of type DateTime causes null reference exception

### ISSUE THREAD

**Issue by jstorteboom** [borisdj/EFCore.BulkExtensions#630]
Hi,

When having an entity with shadow-properties configures as per sample in the attachment, a null reference exception occurs. 

I tracked this down to `TableInfo.cs line 225` where, from the given entity-type we do `'GetProperty'` with the name of that shadow-property. But since it's a shadow property, it doesn't actually exist on the type and therefore causes the null exception.

So the main question is how this property ends up in the `'propertiesWithDefaultValues' on line 218`.  I temporarily and locally fixed this by extending the `'Where-clause' on line 217` where I added the `' && !a.IsShadowProperty()'`. 

I do not quite oversee what the impact is on the rest of the code. Very likely I'm overseeing something, so I do not dare to create a PR for this.

The attached example is a minimalistic dotnet core 5 console application configured to talk to (localdb). You may wanna change connectionstring in the dbContext.cs to make it work on your own machine.

Thanks for your work and looking into this (if you get to it). If any questions, let me know.

[BulkInsert.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7131099/BulkInsert.zip)

**Comment by borisdj** [comment]
Proposed fix is fine so I've added it, v5.4.0 published.
Thx for contrib.

**Comment by jstorteboom** [comment]
Thanks for getting this done so quickly. Much appreciated.

Warm regards,

Johan
