### ISSUE TITLE
EFCore 6.0 support

### ISSUE THREAD

**Issue by angelaki** [borisdj/EFCore.BulkExtensions#632]
The latest version _(5.4.0)_ still gives a `method not found exception` for EFCore 6.0. Is support planned?

**Comment by borisdj** [comment]
It is planned.
Dupe of https://github.com/borisdj/EFCore.BulkExtensions/issues/485

**Comment by angelaki** [comment]
Oh, sorry .... Actually didn't find it - eventhough it obviously wasn't hard to find.
