### ISSUE TITLE
Question: IncludeGraph is slow

### ISSUE THREAD

**Issue by Montago** [borisdj/EFCore.BulkExtensions#633]
Hi 

I've recently started using EFCore BulkExtensions and find it to perform EXCELLENT when only inserting a single table. 

I need to bulk insert using the graph option and are experiencing a much lower performance.

The entities are created using Model First, and I've disabled Cascade Delete options. 
I've however noticed that this new version of Code First created a lot of Non-clustered indexes for each navigation property. 
- All tables have a normal incremental integer key... 
- Target SQL Server is MSSQL 2016 Standard (pretty beefy hardware)
- Target Database is though, only running SQL Server 2014 (120) Compatibility level.. 

My question is therefore what actions i could / should take to improve the Graph insertion performance.

**Comment by Montago** [comment]
hmm.. 

I've been reading through the code.

It seems that inserting a graph makes roundtrips for each node in the graph and updates every child with the newly created parent id .. 

I guess the only way to improve this is to code this recursive pattern in a smarter way which might use threading - or simply invent the ID's myself and do identity-inserts

**Comment by borisdj** [comment]
For large inserts to multiple related tables it is more efficient to create and set IDs in memory so no need for return IDs from Db (if its Guid then it simply to generate them, and if they are Int then last Sequence needs to be manually read from Db and then increment from that)
This way FKs can also be easily set.

Also to note then even in that case calling separately BulkInsert for all tables is little faster then using Graph.
The difference can determine whether it is worth changing code if.

**Comment by Montago** [comment]
Yeah - I'm currently rewriting my code to generate the ID's  in C# and then BulkInsert each collection of the generated types... 

I wonder if the graph tools could be used for this ? 

eg: if i have a list of 1000 root objects that it could do all the magic for me and generate all the BulkInserts - but do so with KeepIdentity = true

**Comment by borisdj** [comment]
You can try and test **Graph** with _KeepIdentity = true_

**Comment by Montago** [comment]
My question here is: does keeping identity prevent the roundtrip ?

**Comment by borisdj** [comment]
Actually no, because Graph sets _SetOutputIdentity = true_.
So if need max performance then best not to use Graph.

**Comment by Montago** [comment]
I managed to create a rather fast setup by leveraging the GraphUtil.GetTopologicallySortedGraph which is just awesome!

https://stackoverflow.com/questions/69253140/ef-core-net-5-efcore-bulkextentions-bulkinsert-to-sql-server-using-the-in/69253803#69253803

**Comment by borisdj** [comment]
Great solution #
