### ISSUE TITLE
Error: Insert bulk failed due to a schema change of the target table.

### ISSUE THREAD

**Issue by Montago** [borisdj/EFCore.BulkExtensions#635]
Every now and then i get this Exception when doing BulkInsert
Microsoft.Data.SqlClient.SqlException: 'Insert bulk failed due to a schema change of the target table.'

I'm 100% sure that the schema hasn't changed, since i JUST RAN Update-Database prior to doing the bulkinsert

I'm running BulkInsert in parallel and am wondering if this exception could stem from a different kind of clash ?

**Comment by borisdj** [comment]
Not sure but based on info from this Link: [docsMSsqlserverfaq](https://docs.microsoft.com/en-us/archive/blogs/sqlserverfaq/executing-bcp-fails-with-sqlstate-37000-nativeerror-4891-error-microsoftodbc-sql-server-driversql-serverinsert-bulk-failed-due-to-a-schema-change-of-the-target-table), issue could be caused some parallel index rebuilds.
