### ISSUE TITLE
Avoid creating and dropping temp tables.

### ISSUE THREAD

**Issue by AraHaan** [borisdj/EFCore.BulkExtensions#636]
It is possible in sql server to bulk update and remove without creating temp tables:

The way to do it is like so:

bulk insert:
```sql
INSERT INTO [dbo].[/* table name */](/* table columns */) VALUES
    (/* first value*/),
    (/* all the other values*/)
GO
```

bulk delete (condition):
```sql
DELETE FROM [dbo].[/* table name */] WHERE /* condition */
GO
/* db may or may not need reindexing after this to avoid fragmentation. */
```

bulk delete (all rows in table)
```sql
DELETE FROM [dbo].[/* table name */]
GO
/* db may or may not need reindexing after this to avoid fragmentation. */
```

These should be just as fast (if not faster) than creating the temp table and then dropping it later while avoiding the temp table, however like stated above the generated queries *may* need to include reindexing the db if it is tested to actually fragment the db.

**Comment by borisdj** [comment]
For Insert and Update Merge command is required.
But BulkOps are using SqlBulkCopy which first insert data into temp table so that Merge can be done.

**Comment by borisdj** [comment]
And generating pure sql then running _ExecuteSqlRaw_ is actually worse then using SqlBulkCopy. (for 100K rows about 10 times slower).
