### ISSUE TITLE
BulkInsertOrUpdateAsync throwing error

### ISSUE THREAD

**Issue by ChengYen-Tang** [borisdj/EFCore.BulkExtensions#637]
I get the following error when using `BulkInsertOrUpdateAsync`
`Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK_CoinData'. Cannot insert duplicate key in object 'dbo.CoinData'. The duplicate key value is (64d19119-3ab3-4f9a-b184-007d85ecbdad-2021-03-09T12:00:00)`
There are about 300,000 pieces of data in my source data collection. Some data exist in the database, and some data do not exist.
If pk already exists in the database, I want to update his content, if it does not exist, insert them.

```
  using BinanceDbContext db = new();
  await db.BulkInsertOrUpdateAsync(data);
```

```
    public class CoinModel
    {
        public CoinModel()
            => (Id, CoinData) = (Guid.NewGuid(), new List<CoinDataModel>());

        [Key]
        [Required]
        public Guid Id {  get; set; }
        [Required]
        public string Name {  get; set; }

        public ICollection<CoinDataModel> CoinData {  get; set; }
    }

    public class CoinDataModel
    {
        [Key]
        [Required]
        public string Key {  get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public decimal Open { get; set; }
        [Required]
        public decimal High { get; set; }
        [Required]
        public decimal Low { get; set; }
        [Required]
        public decimal Close { get; set; }
        [Required]
        public decimal Volume { get; set; }
        [Required]
        public decimal Money { get; set; }
        [Required]
        public int TradeCount { get; set; }
        [Required]
        public decimal TakerBuyBaseVolume { get; set; }
        [Required]
        public decimal TakerBuyQuoteVolume { get; set; }

        [Required]
        public Guid CoinId {  get; set; }
        [Required]
        public virtual CoinModel Coin {  get; set; }
    }
```

**Comment by borisdj** [comment]
When using BulkInsertOrUpdate decision what to Insert and what to update is made based of matcing PK or other custom defined Unique column.
From the example above it seems PK (type Guid) is used, so those for update should be set with appropriate values and ones for Insert should have newly generated values if Guid is created in memory, or left Empty if they are created in Db.

**Comment by ChengYen-Tang** [comment]
Thanks for your reply.
Do you mean that my source collection cannot contain the data I want to update and insert at the same time?

**Comment by borisdj** [comment]
It can, probably something isn't set of configured properly.
Go through ReadMe and take a look at Example:
https://github.com/borisdj/EFCore.BulkExtensions/blob/e6cea2398b64a3d81fd38860e79857f75a16913d/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs#L210
Also there are several usages of same method in _EFCoreBulkTestAtypical_.

**Comment by ChengYen-Tang** [comment]
I still get an error, is it because my pk is too long?
My pk is Guid+DateTime.
64d19119-3ab3-4f9a-b184-007d85ecbdad-2021-03-09T12:00:00

**Comment by ChengYen-Tang** [comment]
Alright!! If the database only has a small amount of data and there are few data waiting to be inserted or updated, everything is normal
However, there is a large amount of data in the database, and there are many data waiting to be inserted or updated, and errors will occur

**Comment by borisdj** [comment]
If you can write a Test where the issue would be reproducible.

**Comment by ChengYen-Tang** [comment]
Thank you for your help
I wrote a simple test program and packaged the test database
Use docker-compose to quickly start the test database. The sa password is P@ssw0rd.

Test database: https://ntutselab-my.sharepoint.com/:u:/g/personal/kenneth_kttw_xyz/EXZmj6vmybxCuTTyo6veFroBjfxe1nVl_EmgNJjOSSZsmQ?e=W4iEOG
Test code: https://github.com/ChengYen-Tang/SQL-Test/tree/master/SQL-Test

**Comment by borisdj** [comment]
There is duple Id in csv list, since PK is same guid prefix + Date and in exception it is stated:
`The duplicate key value is (64d19119-3ab3-4f9a-b184-007d85ecbdad-2021-03-09T12:00:00)`
So in cvs file you can find them (rows 721, 722):
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Boris/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Boris/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Date | Open | High | Low | Close | Volume | Money
-- | -- | -- | -- | -- | -- | --
1/1/2021 12:00 | 29313.49 | 29317.38 | 29299.59 | 29305.6 | 30.777838 | 902110.0613
1/1/2021   12:00 | 29313.49 | 29317.38 | 29299.59 | 29305.6 | 30.777838 | 902110.0613



</body>

</html>

**Comment by ChengYen-Tang** [comment]
Thank you, I also found this problem when writing other projects today. It seems that the binance api returns duplicate data.
I was about to reply that this problem has been resolved, but I did not expect you to find the problem for me.
Really thank you and sorry.

**Comment by frpatino6** [comment]
BulkInsertOrUpdateAsync tiene error al insertar estándo la tabla vacia, aclaro que la tabla tiene una llave compuesta,un campo es te tipo int y el otro string
