### ISSUE TITLE
SqlException : Incorrect syntax near the keyword 'EXCEPT'.

### ISSUE THREAD

**Issue by knikiforov** [borisdj/EFCore.BulkExtensions#638]
The error occurs when a query contains System.Linq.Queryable.Except method call
To reprocude use this test code.

`using var dbContext = new AppDbContext(optionsBuilder.Options);`
`dbContext.Database.EnsureCreated();`
`var query1 = dbContext.Products.Where(x => x.Price > 100);`
`var query2 = dbContext.Products.Except(query1);`
`query2.BatchUpdate(x => new Product { Status = "Some status" });`

**Comment by borisdj** [comment]
_Except_ is not supported for Batch, you could simple write direct oposite Query: `Where(x => x.Price <= 100)`

**Comment by knikiforov** [comment]
ok. I just inform you about the problem. I will use another library for my project.
