### ISSUE TITLE
MergeAsync / GetPropertiesDefaultValue tries to fetch `[NotMapped]`/get-only properties

### ISSUE THREAD

**Issue by pmccloghrylaing** [borisdj/EFCore.BulkExtensions#639]
After upgrading we're getting exceptions with some `[NotMapped]`/get-only properties where the default state isn't valid because they assume other properties are non-default (e.g. Id > 0, or navigation property is not null).

Is it reasonably to only look at properties with setters?

**Comment by borisdj** [comment]
It makes sense.
What exception are you getting? cause [NotMapped] props should be omitted from Insert.

**Comment by pmccloghrylaing** [comment]
The exceptions aren't from BulkExtensions. I've got get-only properties that do dictionary lookups based on another property and throw if a key isn't found, so when it tries to get the default value for that property there's an exception.

**Comment by borisdj** [comment]
Then just skip those as you suggested.
