### ISSUE TITLE
BulkRead with static BulkConfig only fetches data on first attempt

### ISSUE THREAD

**Issue by qvsmith** [borisdj/EFCore.BulkExtensions#640]
Just a question.

While testing `BulkRead` I noticed that if I use a **static** `BulkConfig` it only fetches the data the first time. All successive attempts while app was running resulted in no data being retrieved. I was using the same values to fetch data.

When using a new instance of `BulkConfig` each time it works as expected.

I was just wondering why this is the case?

**Comment by qvsmith** [comment]
Ah I see, thanks for the feedback 👍

**Comment by borisdj** [comment]
Fixed
