### ISSUE TITLE
Bulk Insert Async does not insert any record

### ISSUE THREAD

**Issue by pangyeeshen23** [borisdj/EFCore.BulkExtensions#642]
I am having some problem bulk inserting my records

![image](https://user-images.githubusercontent.com/8078664/136768313-264edbfc-4737-4693-b04c-e643e0ba72ce.png)

this is the code that i am using to bulk insert the recor,
i have tried using transaction.commit() but it does not insert any record as well.
i have check with SQL Profiler 
![image](https://user-images.githubusercontent.com/8078664/136768546-51a3e9c2-dc26-4eee-b883-0bbc498347b9.png)
which shows that there are rows affected but Select * does not show any new rows

**Comment by borisdj** [comment]
Glad you solved it.
