### ISSUE TITLE
GenericsHelpers should allow bypassing Activator.CreateInstance for Interfaces

### ISSUE THREAD

**Issue by sabrite** [borisdj/EFCore.BulkExtensions#644]
Hi, please consider this scenario where you have a class inheriting from an interface and that interface is passed to BulkInsertOrUpdateAsync method:

```
public class Product : IMessage
{
    [NotMapped]
    public string Action { get; set; }
    public string Name { get; set; }
}

public interface IMessage
{
    string Action { get; set; }
}
```

Now when calling bulk insert or update like this:

```
public static async Task InsertOrUpdate(List<IMessage> messageList, BulkConfig bulkConfig, DbContext context)
{
    await context.BulkInsertOrUpdateAsync(messagesToUpdate, bulkConfig);
}
```

the latest implementation of GetPropertiesDefaultValue() method in GenericsHelpers, tries to create an instance of incoming type. I understand that we want to handle default values there but what if the caller is not interested in passing default or has already handled them. In my example scenario, the type passed is an Interface (IMessage) and the following line will always fail when trying to create an instance (of interface)

`object defaultValue = field.GetValue(Activator.CreateInstance(type, true));`

I have been using this library in a .NET Core 3.1 application and the previous implementation didnt have this breaking change of creating the instance. I just migrated to .NET 6 and ran into this. So will it be possible to safely check for incoming type like this:

`object defaultValue = null;
if (!type.IsInterface)
    defaultValue = field.GetValue(Activator.CreateInstance(type, true));
`
so that previous implementations still work and code is more tolerant towards generic types. Thank you

**Comment by borisdj** [comment]
NuGet 6-rc2 published with merged PR.
Thx for contrib.
