### ISSUE TITLE
After bulkinsert() the list ids are coming 0 

### ISSUE THREAD

**Issue by RusheeMahorkar** [borisdj/EFCore.BulkExtensions#65]
I have the GenericEntityRepository in that I have -
` public virtual void BulkAdd(IEnumerable<T> BulkData)
{
 _context.BulkInsert<T>(BulkData.ToList(), new BulkConfig { PreserveInsertOrder = true });
 _context.SaveChanges();
 }`

Call from business layer to repository - 
`ProjectRepo.BulkAdd(Tasks.AsEnumerable());
                rd.DataToSend = Tasks;`   

I need to send the list data back with id (Primary key) 

Currently id is coming 0 after the commit. In database the rows are created with id.

**Comment by borisdj** [comment]
You should set `SetOutputIdentity` to `true` in _BulkConfig_.
More info is in README, segment **SetOutputIdentity**.

**Comment by RusheeMahorkar** [comment]
It worked. Thank you for the help.

**Comment by borisdj** [comment]
You're welcome.
