### ISSUE TITLE
Sqlite datetimeoffset default value bug.

### ISSUE THREAD

**Issue by nbelley** [borisdj/EFCore.BulkExtensions#651]
It seems, in GetSqlSetSegment, detecting changes on a datetimeoffset properties doesn't work properly. 

Those 2 lines:
    object propertyUpdateValue = property.GetValue(updateValues);
    object propertyDefaultValue = property.GetValue(defaultValues);

The first one get the 0 of the default DateTimeOffset converted to the Sqlite column type, but the second get the default DateTimeOffset actual default value, which is "0001-01-01 00:00:00 +00:00". Those values are the same, DateTimeOffset default values converts to 0 in the Sqlite datatbase. 

I'm not sure how to correct this.

**Comment by nbelley** [comment]
> I'm not able to reproduce the issue, can you write a Test for it.

I will try, I'm on Xamarin android app with a .net core project behind it for data access

**Comment by borisdj** [comment]
Try first to reproduce it within exiting tests to see if it happens generally or it's only on android.
