### ISSUE TITLE
NullReferenceException on BulkInsertOrUpdate -> Error found in TableInfo.cs

### ISSUE THREAD

**Issue by MarkusAtBD** [borisdj/EFCore.BulkExtensions#652]
Hi,

During BulkInsertOrUpdate i sometimes get a NullReferenceException. At the Moment i do not 100% know how to reproduce it but i downloaded the package and debugged it to find the cause of the exception (in Version 5.4.0).

it is in TableInfo.cs in the method:
**public static TableInfo CreateInstance<T>(DbContext context, Type type, IList<T> entities, OperationType operationType, BulkConfig bulkConfig)**

in line 225:
**bool listHasAllDefaultValues = !entities.Any(a => a.GetType().GetProperty(propertyWithDefaultValue.Name).GetValue(a, null)?.ToString() != instance?.ToString());**

It looks like _a.GetType().GetProperty(propertyWithDefaultValue.Name)_ can be NULL which results in the exception.

It can be fixed by Changing _a.GetType().GetProperty(propertyWithDefaultValue.Name).GetValue(a, null)?.ToString()_ to _a.GetType().GetProperty(propertyWithDefaultValue.Name)?.GetValue(a, null)?.ToString()_

The reason i did not create a Pull request for it is because i am not sure if this solution creates other issues.

**Comment by MarkusAtBD** [comment]
I created a Pull request for Master and EFCore5.0.

**Comment by borisdj** [comment]
Merged, thx for contrib.
I'll publish new version next week after .Net 6 Full release.
