### ISSUE TITLE
BulkReadAsync:  SQLite Error 1: 'unknown database [dbo]' 

### ISSUE THREAD

**Issue by DavidMartinezMC** [borisdj/EFCore.BulkExtensions#655]
Hello, I tried to run with this code a unit test code, with entity framework in which the table named "bottler" has a default schema (dbo). Try with BulkInsertAsync and other methods and it worked correctly with the default scheme, but with BulkReadAsync there are conflicts when performing the test

`

            var connection = new Microsoft.Data.Sqlite.SqliteConnection("DataSource=:memory:");
            connection.Open();

            var option = new DbContextOptionsBuilder<ABIDBwscContext>()
                .UseSqlite(connection)
                .EnableSensitiveDataLogging()

                .Options;
            var context = new ABIDBwscContext(option);
            if (context != null)
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }

            await context.AddAsync(new Bottler() { BottlerId = 1, BottlerNombre = "ANDINA" });
            await context.SaveChangesAsync();
            var entities = new List<Bottler>() { new Bottler() { BottlerId = 1 } };
            var ListConverted = entities.Select(x => new Bottler() { BottlerId = x.BottlerId, BottlerNombre = x.BottlerNombre }).ToList();
            await context.BulkReadAsync(ListConverted, new BulkConfig() { UpdateByProperties = new List<string> { nameof(Bottler.BottlerId) } });
            Assert.AreEqual("ANDINA", ListConverted.First().BottlerNombre);
        
`

**Comment by borisdj** [comment]
The issue might be due to **_DataSource=:memory:_**
There is a note in ReadMe:
`Bulk Tests can not have UseInMemoryDb because InMemoryProvider does not support Relational-specific methods.`

**Comment by DavidMartinezMC** [comment]
Hello again,
I tried again assigning the default schema "main" to the efcore modelbuilding and everything worked without problems, it seems that assigning the value "dbo" in the EFcore configuration generates some kind of problem with sqlite(memory), but luckily changing to "main" the library works correctly with sqlite in memory
In other words:
` default_scheme = scheme == string.Empty? "dbo" : "main";`
then
`entity.ToTable("bottler", default_scheme);`
in the context
and add the parameter in new context as optional:
`var context = new ABIDBwscContext(option, "test");`

**Comment by borisdj** [comment]
Glad you solved it, will close the issue.
Just to Note that Sqlite does not support schemas like SqlServer, at least not multiple different ones.
There schema name is the name of an [attached database](https://stackoverflow.com/questions/33960762/does-sqlite-support-multiple-schematas-within-the-same-database).
