### ISSUE TITLE
Update entity only on given condition (i.e. higher timestamp)

### ISSUE THREAD

**Issue by nbaser** [borisdj/EFCore.BulkExtensions#66]
We are using the BulkExtension for InsertOrUpdate data from file imports. How is it possible to add an condition for doing the bulk update? We would like to check if the entity timestamp property in the DB is larger or smaller than the entity coming from the fileimport and decide weather the db entity should be updated or dropped. 

Thanks in advance.

**Comment by borisdj** [comment]
It's explained in the README:

> **BulkInsertOrUpdate** method can be used when there is need for both operations but in one connection to database.
> It makes Update when PK(PrimaryKey) is matched, otherwise does Insert.

Also there is config **UpdateByProperties** 

> Additionaly there is UpdateByProperties that allows specifying custom properties, besides PK, by which we want update to be done.

So your Timestamp property could be added in UpdateByProperties, if I understood well that you want update done based on this property.

Now if by 'dropped' you mean Delete than what you could do is first SELECT (read REMARK form README for fast selecting only ones you need) those records from DB.
Then based on Timestamp comparison make 2 lists, one for AddOrUpdate and another for Delete, then call BulkInsertOrUpdate first first list and BulkDelete with second list.
