### ISSUE TITLE
Why are the columns altered to null in output table?

### ISSUE THREAD

**Issue by huer12** [borisdj/EFCore.BulkExtensions#661]
Hi 
Our database engineer complains, that this line 
`ALTER TABLE [dbo].[#ParentsTempOutput] ALTER COLUMN [Id] int; ...`
always triggers a recompile of the query, which is a problem for us. 
I was now looking where this statement is coming from. I have seen, that the statement is created in the SQLServerAdapter, if the flag `tableInfo.CreatedOutputTable` is set to true, then the following is called `SqlQueryBuilder.AlterTableColumnsToNullable`

Now I don't understand why it necessary to change the columns to nullable. Could this be removed or is there a special case where it is necessary? (In my little test program it works without this statement.)

I do a BulkInsertOrUpdateAsync with these settings:
` new BulkConfig()
            {
                UseTempDB = true,
                UniqueTableNameTempDb = false,
                SetOutputIdentity = true,
                PreserveInsertOrder = true,
                OmitClauseExistsExcept = true,
            };`

**Comment by huer12** [comment]
I have looked at the code again and I think this alter table is only needed in case the operation is 'Update'. If the operation is 'Insert' or 'InsertAndUpdate' it is safe to omit this code where the columns of the output table are made nullable. Do you agree?

**Comment by borisdj** [comment]
`AlterTableColumnsToNullable` was for fix for issue: [BulkInsertOrUpdateOrDelete with Output](https://github.com/borisdj/EFCore.BulkExtensions/issues/113#issuecomment-448950354)
So it could changed to be called only for that method and not for others.

**Comment by huer12** [comment]
Thanks for the explanation, now I see why this code has been introduced. The delete adds the null values to the output table in the merge statement.
For performance reasons it would be good to only call this code for BulkInserOrUpdateOrDelete. Do you mind adding this if case in the next release? Or do you prefer if I create a pull request?

**Comment by borisdj** [comment]
It was small change so I've added it.
NuGet v6.0.3 published.

**Comment by rondelward-pf** [comment]
@borisdj Hey Boris. We recently ran into a very similar issue but unfortunately we aren't able to use v6.X of the library yet because we aren't yet on .Net 6. 

Would it be feasible to include a similar patch for the v5.X version of this library if you have the time please?

**Comment by borisdj** [comment]
v5 is not actively maintained.
Best to switch to v6 which is also LTS.

**Comment by rondelward-pf** [comment]
> v5 is not actively maintained. Best to switch to v6 which is also LTS.

@borisdj The only issue with pivoting to v6 is the requirement to use .NET6 (and EF Core 6). Unfortunately we're still using .Net Core 3.1 (LTS) so we're unable to get to the latest version easily since it doesn't have a .NET Standard support.

In any case, I think we should be able to work around this in the short term if updates to the .NET Standard version are not feasible.
Thanks!
