### ISSUE TITLE
Question: Can i bulk delete with composite keys?

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#662]
Hiya,

I'm on the hunt for a performant way to Delete/Insert entities based on a composite key.
Basically i have several entities composed of:

``` csharp
    class MyEntity
    {
        public Guid Id { get; set; } // Key
        public Guid DomainId { get; set; }
        public long ExternalId { get; set; }
       .. other proops
    }
```

I'm fetching data from a different source and then i would like to do something along the lines of (pseudosharp):

``` csharp
 void Update(List<MyEntity> incomingNewEntities)
 {
     // incomingNewEntities will have their domainId and ExternalId set.
     
     // Start tran

     // Remove existing
     _repo.RemoveRange(c => incomingNewEntities.Contains(c)); // Ef core does not accept deleting entites from an in memory list with composite keys

    // insert new
     _repo.BulkInsert(incomingNewEntities);
     _repo.SaveChangesAsync(); 

     // End tran
 }
```

Would this library be able to handle this use-case?

I'm confident the bulk insert is accomplishable with this lib - but unsure about deleting.

NOTES: 
I would like to wrap my delete/insert in a transaction if possible. data integrity and all.
I'm using net6 Ef core 6 (just updated) 
I need a fast solution for delete/inserting about 1000 entities per couple minutes or so.

**Comment by borisdj** [comment]
Yes it would.
All BulkOps, including BulkDelete are done based on single or composite PK, both are supported.

Even custom unique colums can be used for matching with config UpdateByProperties, more info in the ReadMe.
But if you already have composite PK that no need for custom ones.

**Comment by sommmen** [comment]
Hiya, thanks for answering.

I gave this a try but in not really understanding how the delete would work still.

> Yes it would. All BulkOps, including BulkDelete are done based on single or composite PK, both are supported.
> 
> Even custom unique colums can be used for matching with config UpdateByProperties, more info in the ReadMe. But if you already have composite PK that no need for custom ones.

Hiya, thanks for answering.

I gave this a try but in not really understanding how the delete would work still.
This does not delete anything:

``` charp
private async Task DeleteAndInsertNewEntities(CancellationToken cancellationToken, IList<ShopPackaging> newShopPackagings)
{
    using var repository = _shopPackagingBulkRepository.NewScope();
    
    var itemsToDelete = newShopPackagings
        .Select(c => new ShopPackaging
        {
            DomainId = c.DomainId,
            ExternalId = c.ExternalId
        })
        .ToList();

    var deleteBulkConfig = new BulkConfig()
    {
        
    };

    await repository.BulkDeleteAsync(itemsToDelete, bulkConfig: deleteBulkConfig, progress: o => Logger.LogInformation("Bulk Progress: {o}", o), cancellationToken: cancellationToken);

    // TODO insert new data.
    //await repository.BulkInsertAsync(newShopPackagings, cancellationToken: cancellationToken);

}
``` 

I think an insertOrUpdate would also be nice here but could you provide me with a quick example?

**Comment by borisdj** [comment]
This code seems fine, it should work.
If you want to try make a test for your use case take a look at:
https://github.com/borisdj/EFCore.BulkExtensions/blob/5bc57476d99028e40813750246667ce1b1582114/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L229

And secondly as you mention you would get the same result if simply used `BulkInsertOrUpdateAsync`, which would be more efficient since only one Bulk method is required.

**Comment by sommmen** [comment]
Hm.. I'll try and see if i can inspect the SQL generated somewhere.

Would it matter if the properties chosen are not actual keys?

``` csharp
    public class ShopPackaging : IShopPackaging
    {
        [Key]
        public Guid Id { get; set; }
        public long ExternalId { get; set; }
        public Guid DomainId { get; set; }
        public Domain Domain { get; set; }
        .... 
````

``` Sql
CREATE TABLE "ShopPackagings" (
	"Id" UNIQUEIDENTIFIER NOT NULL,
	"ExternalId" BIGINT NOT NULL,
	"DomainId" UNIQUEIDENTIFIER NOT NULL,
	...
	PRIMARY KEY ("Id"),
	FOREIGN KEY INDEX "FK_ShopPackagings_Domains_DomainId" ("DomainId"),
	CONSTRAINT "FK_ShopPackagings_Domains_DomainId" FOREIGN KEY ("DomainId") REFERENCES "Domains" ("Id") ON UPDATE NO_ACTION ON DELETE CASCADE
);
```

**Comment by borisdj** [comment]
It does matter.
As I have mention in case of custom column they need to be configured explicitly.
```
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> {
  nameof(ShopPackaging.ExternalId),
  nameof(ShopPackaging.DomainId)
} };
```

**Comment by sommmen** [comment]
> It does matter. As I have mention in case of custom column they need to be configured explicitly.
> 
> ```
> var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> {
>   nameof(ShopPackaging.ExternalId),
>   nameof(ShopPackaging.DomainId)
> } };
> ```


That works great! Seems very fast too. I also tried `BulkInsertOrUpdate` but that gave me the following error:
`Cannot insert the value NULL into column 'Id', table 'opg-dotnet-api-dev.dbo.ShopPackagings'; column does not allow nulls. UPDATE fails.
The statement has been terminated.`

![image](https://user-images.githubusercontent.com/8641495/142495194-843ec40a-fb1b-4975-8949-d08ef5114dcf.png)

I did exclude it in the bulkconfig:

``` csharp
            var bulkConfig = new BulkConfig
            {
                PropertiesToExclude = new List<string>()
                {
                  nameof(ShopPackaging.Id)
                },
                UpdateByProperties = new List<string> {
                    nameof(ShopPackaging.ExternalId),
                    nameof(ShopPackaging.DomainId)
                }
            };
```

Do you spot anything i'm doing wrong here?

**Comment by borisdj** [comment]
For this use case you should instead of _PropertiesToExclude_ configure actually:
`PropertiesToExcludeOnUpdate = new List<string> { nameof(ShopPackaging.Id) } }`
