### ISSUE TITLE
Violation of PRIMARY KEY constraint, on SQL Server Database, using BulkInsertOrUpdate method

### ISSUE THREAD

**Issue by VoidTallica** [borisdj/EFCore.BulkExtensions#664]
Hello. I´ve been using this extension in .net core 6 and with a sql server database. It worked fine for some tables, but today i got this error:
![image](https://user-images.githubusercontent.com/48948797/143076189-fd4e272c-4564-4b89-af2f-187122a09d2a.png)
  
I checked my list for duplicate values and theres none. My key is based on three columns (descart, colcart, seqncha).
I added only two items with different keys and still got the same error.
![image](https://user-images.githubusercontent.com/48948797/143077332-0d3c2373-6b6f-48f9-8806-b7e9a79c8ac9.png)

But if i only do "BulkInsert", i dont get this error. I think there' s something wrong with "BulkInsertOrUpdate" method.
@borisdj hope someone can help me solve this. Thank you.

**Comment by borisdj** [comment]
Can you write a test where the issue would be reproducible.

**Comment by VoidTallica** [comment]
I was building a sample project with only this specific table in a different database, and i had no problems. The only difference is that the database im using has various tables and relations between them (Foreign Keys). Is it possible that the problem has to do with the foreign keys? Is it possible to disable this verification, when adding the data, in the InsertOrUpdate method Properties?

**Comment by borisdj** [comment]
Not sure, and without reproducible example, don't have more info.
