### ISSUE TITLE
BulkInsertOrUpdate on self referencing table does not work (MERGE statement conflicted with the FOREIGN KEY SAME TABLE constraint, MS SQL Server)

### ISSUE THREAD

**Issue by pjominet** [borisdj/EFCore.BulkExtensions#672]
```c#
await using var transaction = await Context.Database.BeginTransactionAsync();
await Context.BulkInsertOrUpdateAsync(funds, new BulkConfig { SetOutputIdentity = true });
var subfunds = new List<Fund>();
foreach (var fund in funds)
{
    foreach (var subFund in fund.SubFunds)
    {
        subFund.ParentFundId = fund.Id;
    }
    subfunds.AddRange(fund.SubFunds);
}

await Context.BulkInsertOrUpdateAsync(subfunds);

await transaction.CommitAsync();
```

the object in questions has a self refencing FK
```sql
create table [Master].[Fund]
(
    [Id] int identity (1, 1) not null,
    [ParentFundId] int null,
    [OfficialName] nvarchar(500) not null,
    [FundStatusId]  int not null,
    [DataIn] datetime2 generated always as row start not null,
    [DataOut] datetime2 generated always as row end  not null,
    period for system_time (DataIn, DataOut),
    constraint [PK_Fund] primary key clustered ([Id] asc),
    constraint [FK_Fund_ParentFund] foreign key ([UmbrellaFundId]) references [Master].[Fund] ([Id])
) with (system_versioning = on (HISTORY_TABLE = [History].[FundHistory]));
```

this throws me 

> "The MERGE statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_Fund_ParentFund". The conflict occurred in database "fund-data-db", table "Master.Fund", column 'Id'."

Idem when I replace the manual loop, with `IncludeGraph = true`
While debugging I found that all the parent IDs are always 0 or a negative value, as if `SetOutputIdentity` did nothing. I tried adding `TrackEntities` which doesn't help either.

Using version 5.4.1 still as we can't migrate to .Net6 yet. And I need to use `InsertOrUpdate` i.e. a merge, a simple insert doesn't cut it.

EDIT: Maybe this is a limitation of having a self referencing table and merges just do not work in that case, but I am not sure. Unfortunately I am no SQL guru, any clarification on this would already help a lot.

EDIT2: I did some digging, and it seems as it is not possible to do merges on self referencing tables, as a merge does not output newly inserted data/identities: [stackoverflow](https://stackoverflow.com/questions/14356844/complex-table-merge-scenario-that-involves-3-tables-and-self-referencing#:~:text=And%20no%2C%20you%20cannot%20just%20use%20a%20MERGE%2C%20since%20you%20can%27t%20use%20newly%20inserted%20data%20within%20the%20MERGE%20batch%20to%20pass%20on%20to%20subsequent%20inserts/updates.). So i will have to do separare Insert and Update request, albeit in the same transaction if possible. Any confirmation on this would be appreciated.

**Comment by VoidTallica** [comment]
i have the same problem

**Comment by borisdj** [comment]
It works, both on v5 and v6, fine with the following example:
```C#
public class Fund
{
	public int Id { get; set; }

	public int? ParentFundId { get; set; }
	public virtual Fund ParentFund { get; set; }

	public ICollection<Fund> SubFunds { get; set; }

	public string Name { get; set; }
}

public async Task TestFund()
{
	using var context = new TestContext(ContextUtil.GetOptions());

	using var transaction = await context.Database.BeginTransactionAsync();

	var funds = new List<Fund> {
		new Fund { Name = "F1", SubFunds = new List<Fund> { new Fund { Name = "S1" }, new Fund { Name = "S2" } } },
		new Fund { Name = "F2", SubFunds = new List<Fund> { new Fund { Name = "S3" }, new Fund { Name = "S4" } } } };
	await context.BulkInsertOrUpdateAsync(funds, new BulkConfig { SetOutputIdentity = true });
	var subfunds = new List<Fund>();
	foreach (var fund in funds)
	{
		foreach (var subFund in fund.SubFunds)
		{
			subFund.ParentFundId = fund.Id;
		}
		subfunds.AddRange(fund.SubFunds);
	}

	await context.BulkInsertOrUpdateAsync(subfunds);

	await transaction.CommitAsync();
}
```

**Comment by pjominet** [comment]
I found a workaround solution, by doing seperate Inserts & Updates. But I had to split my single input list into a liste with entity additions & one with entity updates

```c#
await using var transaction = await Context.Database.BeginTransactionAsync();
  // inserting new entities if any, with children (includeGraph = true)
  if (fundAdditions.Any())
  {
      await Context.BulkInsertAsync(fundAdditions, new BulkConfig
      {
          SetOutputIdentity = true,
          TrackingEntities = true,
          IncludeGraph = true
      });

      // workaround to ensure that the ParentFundIds are set properly, as BulkInsert does not
      await Context.BulkUpdateAsync(fundAdditions.Where(f => f.ParentFundId is not null).ToList());
  }

  // do any updates if any
  if (fundUpdates.Any())
      await Context.BulkUpdateAsync(fundUpdates);

  await transaction.CommitAsync();
```

I could not get the InsertOrUpdate call to work.

**Comment by borisdj** [comment]
Currently I'm not able to reproduce this.
If you manage to extend the example above with specifics that are using till it pops out.
PS
Equality operators should not have any effect, as for temporal tables they did not exist until v.6

**Comment by pjominet** [comment]
Unfortunately I can't provide the full entities as example here, as I am under NDA for the current project using this and do not know if I am allowed to, as i might give insights to the proprietary data structure (blame corporate...). Thx for the help anyway. As I found a passable workaround by doing seprarate inserts and updates, I leave it at that. Performance is still way better than with standard ef ops on big datasets. You can consider this issue closed on my behalf, tho you might let it open for visibility purposes :)

Anyhow, great lib, espcially as the other alternative is paid, keep up the good work :)

**Comment by borisdj** [comment]
Glad it's usefull.
