### ISSUE TITLE
Any concerns with concurrency?

### ISSUE THREAD

**Issue by tehmufifnman** [borisdj/EFCore.BulkExtensions#674]
Hey all!  

This package has been AMAZING so far!

I am working on a redesigned backend - and one of the things it does a lot of is bulk operations on very large tables.

Are there any concerns with say.... 10 processes trying to bulk insert/delete from the same table at the same time?

Any specific BulkConfig settings that make this more sensible?

**Comment by borisdj** [comment]
Not sure, maybe deadlocks, more info: https://github.com/borisdj/EFCore.BulkExtensions/issues/46
