### ISSUE TITLE
Importing a 1.3GB CSV file into sqlite via EF Core

### ISSUE THREAD

**Issue by dharmatech** [borisdj/EFCore.BulkExtensions#675]
@borisdj,

This is not an issue or complaint. Just wanted to say thank you!

I had an issue importing 1.3 GB of data as described here:

https://stackoverflow.com/questions/70207939/importing-a-1-3gb-csv-file-into-sqlite-via-ef-core/70211019#70211019

Your library made the import go from 48 minutes to 5.7:

https://stackoverflow.com/a/70211019/268581

Thank you!

PS: I sent you $20 via paypal (in two $10 transactions). 🥳

**Comment by borisdj** [comment]
One issue without issue, thx.
Glad it's useful...
