### ISSUE TITLE
After BulkInsert XxxTempXxxOutput tables not removed

### ISSUE THREAD

**Issue by jordyvaneijk** [borisdj/EFCore.BulkExtensions#68]
After calling the following piece of code

`TargetDataContext.BulkInsert(entitiesList.ToList(), new BulkConfig { BatchSize = PageSize, PreserveInsertOrder = true, SetOutputIdentity = true });`

Some of the TempOutput tables remain in databse and won't be deleted.
Is this something i need to do myself or is this a bug?

EFCore.BulkExtensions version  `2.1.7.0`
Microsoft.EntityFrameworkCore for .net Framework vesion `2.1.1.0`
MSSQL Server version `Microsoft SQL Server 2016 (RTM-GDR) (KB4019088) - 13.0.1742.0 (X64)   Jul  5 2017 23:41:17   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 6.3 <X64> (Build 17134: ) `

**Comment by borisdj** [comment]
You could set UseTempDB to True in BulkConfig so that SQL itself will do the Drop.
Are you having some Exception after which temp tables are not Droped or do they always remain in Db?
If error remains you should write code that reproduces it, or write it in a test.
