### ISSUE TITLE
BulkInsert with SetOutputIdentity set true returns empty list

### ISSUE THREAD

**Issue by salihvs** [borisdj/EFCore.BulkExtensions#681]
Hi,

I upgraded my project to .net6 and tried using EFCore.BulkExtensions version 6 - 6.1.4 they both have same bug. While using BulkInsertAsync with SetOutputIdentity = true, the list I give to insert returns empty.

Can you please check that?

**Comment by borisdj** [comment]
To reproduce the issue, can you write a test or alter existing one:
https://github.com/borisdj/EFCore.BulkExtensions/blob/2f9672a345833c96593d56925f84aced9c2c4d01/EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs#L101

**Comment by salihvs** [comment]
What is the entities length here? https://github.com/borisdj/EFCore.BulkExtensions/blob/2f9672a345833c96593d56925f84aced9c2c4d01/EFCore.BulkExtensions.Tests/EFCoreBulkTestAsync.cs#L149
