### ISSUE TITLE
Malwarebytes picking up Trojan.Downloader.MSIL.Generic

### ISSUE THREAD

**Issue by Tyler-V** [borisdj/EFCore.BulkExtensions#682]
Not sure why this is appearing after updating the package, can we get confirmation that nothing nefarious was introduced in the EFCore3.1 branch? I am using 3.6.3 and for some reason, Malwarebytes keeps quarantining the dll on start.

It appears to be the only one marking it suspicious, https://www.virustotal.com/gui/file/c26a006f72c34875e552aec80dc3d47bf59c735556202272953ddcdc9f0436e0?nocache=1

![image](https://user-images.githubusercontent.com/3893234/145143229-ada78175-0967-4145-a668-69d0bc5e8aed.png)

![image](https://user-images.githubusercontent.com/3893234/145143240-07503a02-f0f5-4a43-976a-bfc5766d065e.png)

**Comment by Tyler-V** [comment]
@borisdj

**Comment by borisdj** [comment]
Yes, 3.6.3 is no specific then version before.
You can check the source and last commits on branch v3.
It could be false positive: https://weblog.west-wind.com/posts/2016/oct/05/dealing-with-antivirus-false-positives
Also to note the prior to v5 package was not signed.
PS I have just tried to check same file and igot result without issue:
https://www.virustotal.com/gui/file/3ca7f3a7bed90b3db7201bdc8155d76ec0a98dc13c852d07d5eb8911b3dbc9b0?nocache=1
