### ISSUE TITLE
[Q] SetOutputIdentity and guids generated client-side

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#684]
Hello,

I'm using `BulkInsertOrUpdateAsync` to upsert entities from a public api.
This works great however after i upsert i'd like to get the ids.

It seems `SetOutputIdentity` was created for this purpose. However as i read the docs, this will only retrieve the latest id from the database if the id was set to null (the database generated id is then returned).

I'm however not generating the ID server-side but client-side because of ef core.

``` csharp
            using var repository = _shiftBaseUserBulkRepository.NewScope();

            // EF core generates the Guid client side, so for insertion we must generate our own Guids.
            // NOTE SequentialGuidValueGenerator generates a so called sequential GUID or COMB guid which is more performant 
            var sequentialGuidValueGenerator = new SequentialGuidValueGenerator();
            foreach (var incomingUser in incomingUsers)
            {
                incomingUser.Id = sequentialGuidValueGenerator.Next(null!);
            }

            var bulkConfig = new BulkConfig
            {
                SetOutputIdentity = true,
                // The Id shall not be changed for updates
                PropertiesToExcludeOnUpdate = new List<string>
                {
                    nameof(ShiftbaseUser.Id)
                },
                UpdateByProperties = new List<string>
                {
                    nameof(ShiftbaseUser.ExternalUserId),
                }
            };

            var swUpsert = new Stopwatch();
            await repository.BulkInsertOrUpdateAsync(incomingUsers, bulkConfig, o => Logger.LogInformation("Bulk Progress: {o}", o), cancellationToken: token);
            Logger.LogInformation("Upserted {Count} users in {Elapsed}", shiftbaseUserDtos.Count, swGetUsers.StopElapsed());

            return shiftbaseUserDtos;
```

It seems that this would require me to run an extra select call to gather the ids and then match them to my original... That seems a bit redundant - is there a way to get the ids from the database with `BulkInsertOrUpdate` if the id is generated client-side?

**Comment by borisdj** [comment]
If IDs are generated in App and not in Db then _SetOutputIdentity_ is not necessarily at all, since you already have them.

**Comment by sommmen** [comment]
Only if the entities are inserted. When they are updated your info is out of sync.

If I run that code twice on an empty db, the first time all entities get inserted - then I know the IDs.

The second time the entities get updated instead - the ids are skipped, and therefore the client does not know the IDs in the database...

**Comment by borisdj** [comment]
For this use case you would need to BulkRead after the insert.

**Comment by sommmen** [comment]
> For this use case you would need to BulkRead after the insert.

Yeah i think i'd need to fetch new ids from the database after an update.

Another option i'm considering would be to just always update the new ids;

``` csharp
var bulkConfig = new BulkConfig
{
    // NOTE we shall update the id always so ids client-side and server-side are in sync.
    //PropertiesToExcludeOnUpdate = new List<string>
    //{
    //    nameof(ShiftbaseUser.Id)
    //},
    UpdateByProperties = new List<string>
    {
        nameof(ShiftbaseUser.ExternalUserId),
    }
};
```

(i'm blindly assuming the code above should work)

Which perhaps could be somewhat slower since the index will have to be updated for the key but that should not be all too bad.

Anyways thanks a lot for sticking with me boris, thanks for all your advice so far.
