### ISSUE TITLE
Exception while inserting data with bulkinsert in a PostgreSQL database

### ISSUE THREAD

**Issue by SCASTEX** [borisdj/EFCore.BulkExtensions#685]
Hello,

Since version 6.1.4, this error occured while inserting data in a PostgreSQL database.

> A PostgreSQL type with the name character varying(3) was not found in the database
   at Npgsql.Internal.NpgsqlDatabaseInfo.GetPostgresTypeByName(String pgName)
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByDataTypeName(String typeName, Boolean throwOnError)
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByDataTypeName(String typeName)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param, Boolean async, CancellationToken cancellationToken)
   at EFCore.BulkExtensions.SQLAdapters.PostgreSql.PostgreSqlAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken, Boolean isAsync)

I'm using [StringLength()] or [MaxLength()] to set the length of string field in the entity class.

>
      public TestEntity
      {
            [Key]
            public int id { get; set; }
            [StringLength(3)]
            public string alias { get; set; }
            [MaxLength(60)]
            public string label { get; set; }
      }

I've also tried by overriding OnModelCreating but i still got the error above.
>     
       modelBuilder
            .Entity<TestEntity>()
            .ToTable("test")
            .Property("alias")
                  .HasMaxLength(3)
                        .IsFixedLength(true);

The last version without this error was 6.1.3.

Did i miss something or am i doing it wrong ?

Best Regards.

S.CASTEX

**Comment by borisdj** [comment]
Fixed with 6.1.7

**Comment by SCASTEX** [comment]
Hello,

It works perfectly. Thank you.

Best regards.

S.CASTEX

**Comment by SCASTEX** [comment]
Hello,

Well, I'm sorry but the BulkInsertAsync() has the same issue. :(

>System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (A PostgreSQL type with the name character varying(3) was not found in the database)
  Source=System.Private.CoreLib
  Arborescence des appels de procédure :
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à System.Threading.Tasks.Task.Wait()
   à Program.<Main>$(String[] args)
ArgumentException : A PostgreSQL type with the name character varying(3) was not found in the database

I've tested BulkUpdateAsync() which failed too. Nevertheless, BulkUpdate() works fine.

I'm sorry for previously missing these issues.

Best regards.

S.CASTEX

**Comment by borisdj** [comment]
Try with 6.2.0

**Comment by SCASTEX** [comment]
Helle,

It works fine.

Thanks a lot.

Best Regards.

S.CASTEX
