### ISSUE TITLE
Performance degradation BulkInsertOrUpdateAsync  [version 3.1.0 -> 6.0.0+]

### ISSUE THREAD

**Issue by Tealons** [borisdj/EFCore.BulkExtensions#687]
We recently upgraded one of our projects to .NET 6 and also upgraded this package from version 3.1.0 to 6.0.0+ (now running the latest version).

In our production environments we noticed a performance degradation that is causing execution timeouts of our Azure Functions. We did some digging and found that the cause of the performance issue is the `GetPropertiesWithDefaultValue `helper function in the `MergeAsync `function called via the `BulkInsertOrUpdateAsync`. 

In our case we are inserting or updating a list with approximately 32k entities. In `GetPropertiesWithDefaultValue `we noticed that 
this line will trigger `GetPropertiesDefaultValue `for each individual entity:

`var result = values.SelectMany(x => x.GetPropertiesDefaultValue(type)).ToList().Distinct();`

Changing the line to the following fixes our problems:

`var result = values.First().GetPropertiesDefaultValue(type).Distinct();`

We can create a pull request, but we are not sure if this will impact other scenarios? Maybe in case when T passed to GetPropertiesWithDefaultValue is an list of entities that are derived from an interface?

**Comment by Tealons** [comment]
Btw, after some further searching we now see the point of GetPropertiesWithDefaultValue. However, we would have expected this to be an option that's off by default? Because of the performance impact?

**Comment by borisdj** [comment]
Firstly list in some case is empty so fix should be like:
`var result = values.FirstOrdefualt()?.GetPropertiesDefaultValue(type)?.Distinct();`
Second it still fails the test `ComputedAndDefaultValuesTest` on _BulkInsertOrUpdate_ when in first entity Guid is set but others have default Guid.Empty.
There either logic should be changed, or to use FastProperty to make it more efficient.
Alternatively as you mentioned to make this call config-able.

**Comment by borisdj** [comment]
Btw the method was a PR: https://github.com/borisdj/EFCore.BulkExtensions/pull/588

**Comment by Tealons** [comment]
Thanks. We will be working on a PR on Monday.

**Comment by Tealons** [comment]
After some experimentation we decided to implement the configuration option. We are thinking of disabling this functionality by default because of the enormous performance impact that it has. Are you ok with that? It would mean a breaking change for the PR author..

**Comment by borisdj** [comment]
I have changed it currently to _.FirstOrDefault_, for PRs use case it will still work.
Published v6.2.1

**Comment by Tealons** [comment]
Yeah, that was a wrong suggestion. The piece of code introduced in #588 needs to look at the entire list to determine if some of the insert columns need to be omitted during the merge. We tried to speed this up, but reflection is to slow and the helper code causes a lot of GC activity. We could try expression trees, but because we don't use this functionality we thought of making a configuration option.

**Comment by borisdj** [comment]
I'm aware, for the moment it can stay, until find a way to improve it without config.
