### ISSUE TITLE
Identity Insert

### ISSUE THREAD

**Issue by Paxman23l** [borisdj/EFCore.BulkExtensions#69]
Is there a way to do bulk Identity insert?  I'm doing a regular push from an incoming file that needs specific PK's for a FK relationship, and I'm not sure what rows will or wont be duplicated as the file is updated randomly.  Ideally, I'd like to just do a bulk push and not worry about querying existing data to determine which needs to be updated/inserted.

**Comment by borisdj** [comment]
If you need to do insert or update based on some unique set of data (one or several specific columns) you can achieve that with `BulkInsertOrUpdate` method and in _BulkConfig_ set _UpdateByProperties_ with those columns.

**Comment by borisdj** [comment]
You're Welcome.
