### ISSUE TITLE
NullReferenceException in FastProperty.cs

### ISSUE THREAD

**Issue by danielkaczmarek** [borisdj/EFCore.BulkExtensions#690]
I have the following exception in some of the scenarios in my app. The ParentEntity returns null and that cause the exception. 

![image](https://user-images.githubusercontent.com/7963294/146180005-be9b2156-cf9a-4087-b642-d93512cee820.png)

![image](https://user-images.githubusercontent.com/7963294/146180021-1ce44ba3-a971-4d16-9be3-f14535e029aa.png)

A simple change to FastProperty.cs fixes it 

`        public object Get(object instance) { return instance == default ? default : GetDelegate(instance); }

        public void Set(object instance, object value)
        {
            if (value != default)
            {
                SetDelegate(instance, value);
            }
        }`

I'm just wondering if that could be implemented in this extention to fix that issue ?

Thank you

**Comment by borisdj** [comment]
Fix seems fine if you want to make a PR.

**Comment by danielkaczmarek** [comment]
> Fix seems fine if you want to make a PR.

The PR is done, hopefully I have done it corretly (this is the first time I've done a PR in GitHub)

**Comment by borisdj** [comment]
Thx for contrib.
Published v6.2.2
