### ISSUE TITLE
Triggers firing for PostgreSQL on insert/update

### ISSUE THREAD

**Issue by SteveHWork** [borisdj/EFCore.BulkExtensions#691]
My understanding from the README is that triggers should not fire by default for insert/update. However on PostgreSQL I am hitting an issue where the triggers are firing:

- Define trigger for insert on target table, which generates an error on insert
- Use dataContext.BulkInsert and dataContext.BulkUpdate on the table to insert some rows

Both insert and update cause the error, which means that the trigger is firing for both. I don't know if I can configure it somehow to disable the triggers, but the SqlBulkCopyOptions only seems to allow FireTriggers to be enabled, not disabled (or perhaps I am misunderstanding this)

I have attached a sample project which should demonstrate the issue (just change connection string in TestContextFactory).

Thanks!

[BulkExtensionsIssue.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7719974/BulkExtensionsIssue.zip)

**Comment by borisdj** [comment]
_SqlBulkCopyOptions_ is only for SqlServer.
I'm not familiar that npgsql has at all option for this.
What comes to mind as a way to make it work is to run pure sql before Bulk call to Disable it, and revert it after.
Try something like:
```C#
context.Database.ExecuteSqlRaw("ALTER TABLE table_name ENABLE TRIGGER ALL"); 
context.BulkInsert(list);
context.Database.ExecuteSqlRaw("ALTER TABLE table_name ENABLE TRIGGER ALL");
```
