### ISSUE TITLE
BulkInsertOrUpdate assigns wrong output IDs when PreserveInsertOrder = true and SetOutputIdentity = true

### ISSUE THREAD

**Issue by rubenanton90** [borisdj/EFCore.BulkExtensions#694]
Hi, I found this issue in BulkExtensions 5.X (I don't know how long it's been there), and it still happens in 6.X

If you have a list with N values that were already on the database (ex: 
`Foo { ID = 1, Name = "a", Surname = "alpha" }, Foo { ID = 2, Name = "b", Surname = "beta" } `
and you perform a BulkInsertOrUpdate with both PreserveInsertOrder and SetOutputIdentity set to true, with the items on a different order than the actual DB values, the populated IDs for each item will not correspond to the actual PKs from BD. Example:
`
List<Foo> bulkItems = new List<Foo> { new Foo { Name = "b", Surname = "brandon" }, new Foo { Name = "a", Surname = "aaronson" } };  
await context.BulkInsertOrUpdateAsync(bulkItems, new BulkConfig
    {
        SetOutputIdentity = true,
        PreserveInsertOrder = true,
        UpdateByProperties = new List<string> { nameof(Foo.Name) }
    });`
will return that the ID for the "a" item is 2 and the ID for the "b" item is 1, whereas the actual DB values are "a"=> ID=1, "b" => ID=2
 I think it may have to do with preserveInsertOrder erroneously applying to elements already existing on DB.
 I've uploaded a complete example here:
 [https://github.com/rubenanton90/BulkExtensionsBug](https://github.com/rubenanton90/BulkExtensionsBug)
 
 Thanks!

**Comment by borisdj** [comment]
Fixed with 6.2.3
