### ISSUE TITLE
PostgreSQL - BatchDelete syntax error

### ISSUE THREAD

**Issue by yury-sch** [borisdj/EFCore.BulkExtensions#696]
.NET 6, EFCore.BulkExtensions 6.2.3

`await _context.Set<Walker>().Where(w => w.WalkId == id).BatchDeleteAsync();`

```
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "w"

DELETE w
FROM walkers AS w
WHERE w.walk_id = @__Id_0
```

**Comment by borisdj** [comment]
I have tried existed test with line:
`int id = 1;  context.Items.Where(a => a.ItemId == id).BatchDelete();`
and it passes.

**Comment by yury-sch** [comment]
Yeah, you are right. I created an empty project and it works fine. Trying to find a problem on my side....
