### ISSUE TITLE
SQL Server: Error when using field of type XML

### ISSUE THREAD

**Issue by dsuesstr** [borisdj/EFCore.BulkExtensions#699]
When having a field of Type XML in the affected table,  I get the following error since moving to .NET 6, EF Core 6 and EFCore.BulkExtension > 5.*.
`The data type xml cannot be used as an operand to the UNION, INTERSECT or EXCEPT operators because it is not comparable.`

It doesn't matter whether the XML field is affected or not in the query.

FYI:
It worked when using Net 5, EF Core 5 and EFCore.BulkExtensions 3.*.
When I want to use EF Core 6 with EFCore.BulkExtensions 3.*, I get an error about a missing method (I guess EF Core 6 and BulkExtension 3.* are not compatible).

**Comment by borisdj** [comment]
Try to set _OmitClauseExistsExcept_: **_true_**  in config.

**Comment by dsuesstr** [comment]
Thanks, `OmitClauseExistsExcept: true` OmitClauseExistsExcept: true
