### ISSUE TITLE
Opened connections are not closed properly

### ISSUE THREAD

**Issue by Feoni4** [borisdj/EFCore.BulkExtensions#7]
If you try to ~200-300 insertations you will fail with exception - can not open new connection.

It can be fixed easy - wrap sqlBulkCopy into using in SqlBulkOperation.cs **Insert** method:

```
public static void Insert<T>(DbContext context, IList<T> entities, TableInfo tableInfo, Action<double> progress = null, int batchSize = 2000)
        {
            var sqlBulkCopy = new SqlBulkCopy(context.Database.GetDbConnection().ConnectionString)
            {
                DestinationTableName = tableInfo.InsertToTempTable ? tableInfo.FullTempTableName : tableInfo.FullTableName,
                BatchSize = batchSize,
                NotifyAfter = batchSize
            };

            using (sqlBulkCopy) // add using here
            {
                sqlBulkCopy.SqlRowsCopied += (sender, e) => { progress?.Invoke(e.RowsCopied / entities.Count); };

                foreach (var element in tableInfo.PropertyColumnNamesDict)
                {
                    sqlBulkCopy.ColumnMappings.Add(element.Key, element.Value);
                }
                using (var reader = ObjectReader.Create(entities, tableInfo.PropertyColumnNamesDict.Keys.ToArray()))
                {
                    sqlBulkCopy.WriteToServer(reader);
                }
            }
        }
```

Fix here: [commit](https://github.com/Feoni4/EFCore.BulkExtensions/commit/aa8ec60d6e4d3bcf3e8b013e65aa0b8a6558c2e1)

**Comment by borisdj** [comment]
I agree, and will commit the change soon with proposed fix.

**Comment by Feoni4** [comment]
And i'm interesting - why we can not use connection from context as SqlBulkCopy constructor parameter?
`(SqlConnection)context.Database.GetDbConnection()`

You are using almost the  same approach in _EFCore.BulkExtensions.TableInfo.CheckHasIdentity_ method.

I'v made a pull request for it: #10

**Comment by borisdj** [comment]
CheckHasIdentity was later added feature, but I did not refactor SqlBulkOperation at that time.
Meaning it can be used.
I have merged your request and made some more refactoring so pull the latest code repo.

**Comment by Feoni4** [comment]
Everything is working fine now, issue can be closed
I think that using context connection also solve #4 and #9, but i have not tested it.

**Comment by borisdj** [comment]
I did tested it and it is not connected with this.
So _Trusted_Connection=True;_ is still required in ConnectionString.
