### ISSUE TITLE
Temp table issue for BulkInsertOrUpdateAsync  when useTempDB = false

### ISSUE THREAD

**Issue by tedmax100** [borisdj/EFCore.BulkExtensions#701]
Hi, i need to use BulkInsertOrUpdateAsync to finish my task.

My db account for service only have Insert/Update/Select/Delete permission; 
when i excute BulkInsertOrUpdateAsync without UseTempDB, 
will receive the error message "CREATE TABLE permission denied in database "

I don't understand why no use tempdb but will receive the message, so that i need to grant more permission.

```c#
 await using (var tx = await _context.Database.BeginTransactionAsync(isolationLevel:System.Data.IsolationLevel.RepeatableRead ))
            {
                // xxxx
                await this._context.BulkInsertOrUpdateAsync(target, new BulkConfig() {
                    UseTempDB = false
                });
                await tx.CommitAsync();
            }
```
.Net Core3.1
EntityFrameworkCore.SqlServer v3.1.21
EFCore.BulkExtensions v3.6.3

**Comment by borisdj** [comment]
_UseTempDB_ is **false** by default and it means that temp tables are created as additional tables for which Permission is required.
If app does not have that permission then set `UseTempDB = false` and it will use [Temporary user objects](https://docs.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sql-server-ver15)

**Comment by borisdj** [comment]
When seto to True it does uses 'temp'.
You can check in the Tests.

**Comment by gianx10** [comment]
Hi Borisdj
This is the SqlServer user with low permission:
![image](https://user-images.githubusercontent.com/49390635/178200184-63bf189b-d67c-44ba-a8db-a86196a9c8c8.png)

End this is the error, using the code above in the previous post:
![image](https://user-images.githubusercontent.com/49390635/178200371-50bdd03e-952e-4435-b689-ea23daac1200.png)

**Comment by borisdj** [comment]
As exception states your table has some triggers or constraints and table with those requires Alter permission for direct _bulkcopy_ into it.
So you would need to grant that right.

One other thing that you could try is to set also config **SetOutputIdentity = true.** in which case instead of direct Bulk INSERT into destination table, it will do MERGE from Temp table, so maybe that way it will work.

**Comment by gianx10** [comment]
Hi borisdj

If I set also SetOutputIdentity = true i have this error:
![image](https://user-images.githubusercontent.com/49390635/178263777-41aff06c-a510-4b9a-a968-30edaef49abf.png)

My code is inside a TransactionScope, so I dont't have a SqlTransaction. 
What can I do if I can't give those permissions to the SqlServer user or how I can use the transaction?

**Comment by borisdj** [comment]
You can have Transaction inside a Scope.
```C#
using var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
using var transaction = await context.Database.BeginTransactionAsync();

var bulkConfig = new BulkConfig() { UseTempDB = true, SetOutputIdentity = true };
await  context.BulkInsertAsync(list, bulkConfig);

await transaction.CommitAsync();
```

**Comment by gianx10** [comment]
Are you sure borisdj?
I've already try, but I have this error:
![image](https://user-images.githubusercontent.com/49390635/178268276-35af61fc-067c-4968-b6ec-35ce2697bd53.png)

**Comment by borisdj** [comment]
You are right, seems then only option is to use Transaction but outside of scope.

**Comment by gianx10** [comment]
There is no way to set some property, for not use transaction in "BulkUpdateAsync" operation?
It does not seem correct to me, to force the use of a transaction. In a complex scenario, I will use a TransactionScope or I may decide not to use a transaction.

**Comment by borisdj** [comment]
Not that I know of.
BulkUpdate uses MERGE so it needs to create a table.
If it using direct table that certain permissions are required over db,
while if using temp tables that fails if not in Transaction.
