### ISSUE TITLE
When use BulkInsertOrUpdateAsync

### ISSUE THREAD

**Issue by radhe65gupta** [borisdj/EFCore.BulkExtensions#705]
Context.BulkInsertOrUpdateAsync(entities ,  op => op.IncludeGraph = true);
How i know that the my database table has Updated,
because BulkInsertOrUpdateAsync Or BulkUpdateAsync   not return any value that confirm me Your Table has Updated.

for Example SaveChangesAsync() return 1 or 0. 
1 for database update and 0 for not change

**Comment by borisdj** [comment]
You can use  _CalculateStats_, set it to **True**, more info in the ReadMe.

**Comment by radhe65gupta** [comment]
> You can use _CalculateStats_, set it to **True**, more info in the ReadMe.

var config = new BulkConfig
            {
                CalculateStats = true
            };
            if (entities != null)
            {
                await Context.BulkInsertOrUpdateAsync(entities.ToList(), config, operation => operation.IncludeGraph = true);
                var re = config.StatsInfo.StatsNumberUpdated;
                return re;
            }

i user like this, but getting error.
Help regarding this problem

**Comment by radhe65gupta** [comment]
> You can use _CalculateStats_, set it to **True**, more info in the ReadMe.

Thanks @borisdj
