### ISSUE TITLE
Net framework 4.7.2 integration

### ISSUE THREAD

**Issue by KPS-gp** [borisdj/EFCore.BulkExtensions#708]
Hi, I'm trying to integrate the BulkExtensions in old framework 4.7.2 projects, so I'm integating 3.6.x version (Net standard 2.0). But when I'm try to add mycontext.Bulk*** , extension is not accessible.

Could you tell me if I need to integrate something else ?

Thank you and thank you for the great job.

Jeff.

**Comment by borisdj** [comment]
Have you put
`using EFCore.BulkExtensions;`
