### ISSUE TITLE
Postgres bulk operation progress callback

### ISSUE THREAD

**Issue by SebastianBienert** [borisdj/EFCore.BulkExtensions#709]
I am not able to use progress callback in [BulkInsertAsync](https://github.com/borisdj/EFCore.BulkExtensions/blob/48dec0e10a77f3924c607a1dc1a9c05cbc89e090/EFCore.BulkExtensions/DbContextBulkExtensions.cs#L17) method - the callback is never called. I just looked into the source code of PostgreSqlAdapter and for me it looks like progress parameter is never used:

https://github.com/borisdj/EFCore.BulkExtensions/blob/48dec0e10a77f3924c607a1dc1a9c05cbc89e090/EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs#L27

Could you correct me if I'm wrong?

**Comment by borisdj** [comment]
That's correct.
**_progress_** was added only for SqlServer.
Not sure if _NpgsqlBinaryImporter_ has same event handler as SqlBulkCopy.

**Comment by SebastianBienert** [comment]
Nope, it does not, although we can simply add it on postgres adapter level. I've created proposal: #713

**Comment by borisdj** [comment]
Good idea,
Thx for contrib, v6.2.7 published.
