### ISSUE TITLE
SaveChanges in bulk

### ISSUE THREAD

**Issue by PeteJobi** [borisdj/EFCore.BulkExtensions#710]
```BulkSaveChanges``` is mentioned in the readme.md, but I couldn't find it. I'm guessing it was removed?

There's a useful feature of EF's ```RemoveRange()``` method that automatically deletes dependent entities when ```SaveChanges``` is called.

For example, when this is run:
```
context.Posts.RemoveRange(context.Posts.Where(p => p.SenderId == userId).Include(p => p.Replies));
context.SaveChanges();
//p.Replies is a navigation property in Post (public ICollection<Post> Replies { get; set; })
```
All the posts by ```userId``` is deleted as well as the replies belonging to each post. But of course, a query is run for each post and reply.

Is there a way to achieve this automatic deleting of dependent entities using ```BatchDeleteAsync```?

**Comment by borisdj** [comment]
**_BulkSaveChanges_** is not removed, it was actually recently added as new feature, so it only exist after version 6.0.7
As for direct Delete ops there are both _BatchDelete_ and _BulkDelete_, take a look in the ReadMe and Tests in source code for examples.

**Comment by PeteJobi** [comment]
Thanks. I did some reading on how EF cascade delete works and this isn't an issue for me anymore, so I'm going to close it.
