### ISSUE TITLE
Not able to use BulkExtension with IdentityDbContext

### ISSUE THREAD

**Issue by sanket-pattekar** [borisdj/EFCore.BulkExtensions#718]
Hi

I have a DBContext that inherits IdentityDbContext and not DBContext. How to use the BulkExtension with this database context

public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, string>
{
...

DBSet<> ... 
}

**Comment by borisdj** [comment]
There is no difference, it's used the same way.
