### ISSUE TITLE
Bug/Feature? NRTS don't work for navigation properties

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#719]
Hiya,

We can use nullable reference types for navigation properties by using a nullable backing field, like so:

``` csharp
public class Order
{
    #region Domain
    
    public Guid DomainId { get; set; }

    private Domain? _domain;

    public Domain Domain
    {
        get => _domain ?? throw new InvalidOperationException("Uninitialized property: " + nameof(Domain) + " try loading the entity with .Include()");
        set => _domain = value;
    }

    #endregion
...
}
```

See: https://docs.microsoft.com/en-us/ef/core/miscellaneous/nullable-reference-types

In this case the `Domain` is not nullable but an exception is thrown when someone accesses the property and forgot to call `.Include(c => c.Domain)`.

In EF this works because by default EF core access the property by the backend field:

> The default behavior is PreferField. Prior to EF Core 3.0, the default behavior was PreferFieldDuringConstruction.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.propertyaccessmode?view=efcore-5.0

I.e. the backend field is used instead of the property accessor. 

This poses an issue because this library does not use the same behaviour but tries to access the property directly:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Uninitialized property: Domain try loading the entity with .Include()
  Source=OPG.DAL
  StackTrace:
   at Company.DAL.Entities.Order.get_Domain() in C:\REDACTED\Order.cs:line 22
```

The debugger can do better with the stacktrace fortunately:

![image](https://user-images.githubusercontent.com/8641495/149348951-a2277315-4274-4747-9df1-34cc212da797.png)

Would it be possible to use the same logic as ef core and access properties by their backend value by default?

I'm also a bit puzzled why it would need to access the property value in the first place.

**Comment by borisdj** [comment]
Value is required for _SqlBulkCopy_ to work, and it is obtained from _FastProperty_ class for efficiency.
You can take a look at the source code.
Not sure how to get from field backend value.
