### ISSUE TITLE
Problem with BulkUpdateAsync() with MySQL

### ISSUE THREAD

**Issue by OculiViridi** [borisdj/EFCore.BulkExtensions#72]
I'm using EFCore.BulkExtensions `BulkUpdateAsync()` method within a `MediatR` handler to update a list of entities.
I'm getting the following exception:

> InnerException	{MySql.Data.MySqlClient.MySqlException (0x80004005): **FUNCTION db_machine_40.columnproperty does not exist** ---> MySql.Data.MySqlClient.MySqlException (0x80004005): FUNCTION db_machine_40.columnproperty does not exist
   at MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1169
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---

These are my `MediatR` methods

```c#
protected void SetStationLastComputedIds(List<LastComputedIdUpdateModel> lastComputedIds)
{
	using (DisposableMediator mediator = GetMediator())
	{
		mediator.Send(new LastComputedIdUpdateCommand { LastComputedIds = lastComputedIds }).Wait();
	}
}

public class LastComputedIdUpdateCommandHandler : BaseHandler, IRequestHandler<LastComputedIdUpdateCommand>
{
	public LastComputedIdUpdateCommandHandler(MyDbContext context, IMapper mapper)
		: base(context, mapper)
	{ }

	public async Task<Unit> Handle(LastComputedIdUpdateCommand request, CancellationToken cancellationToken)
	{
		List<LastComputedId> entities = Mapper.Map<List<LastComputedId>>(request.LastComputedIds);
		await Context.BulkUpdateAsync(entities); // Throws Exception!

		return Unit.Value;
	}
}
```

These are the entity and the corresponding model used for the update command

```c#
public class LastComputedId
{
	public int Id { get; set; }
	public int StationId { get; set; }
	public string TableName { get; set; }
	public long LastComputedId { get; set; }
	public DateTime Updated { get; set; }
}

public class LastComputedIdUpdateModel
{
	public int Id { get; set; }
	public long LastComputedId { get; set; }
	public DateTime Updated => DateTime.Now;
}
```

**Comment by borisdj** [comment]
MySql not supported https://github.com/borisdj/EFCore.BulkExtensions/issues/71

**Comment by borisdj** [comment]
MySql support added as of v6.
