### ISSUE TITLE
BulkInsertOrUpdateOrDeleteAsync always provokes versioned copies in the history table with EF6 temporal tables

### ISSUE THREAD

**Issue by jcasale** [borisdj/EFCore.BulkExtensions#720]
I am trying to add support for temporal tables to an EF6 project that uses EFCore.BulkExtensions v6.2.8.

When I pass a collection of objects without any changed data to `BulkInsertOrUpdateOrDeleteAsync`, I always get a new version in the primary table and an extra row in the history table.

I've tried setting the `PropertiesToInclude*` properties in the bulk config to only include the data columns, but it did not change the result.

Is this behavior expected with temporal tables? I looked at the tests for `BulkInsertOrUpdateOrDeleteAsync` and don't see anything different with what I am doing.

**Comment by borisdj** [comment]
That's how temporal tables work.
What you could do is to first BulkRead the data and remove same ones from the list, then call the Sync.
