### ISSUE TITLE
bulk read return entities with all properties not set at second query

### ISSUE THREAD

**Issue by kosaurang** [borisdj/EFCore.BulkExtensions#721]
My code :
I using version 5.4.1

var bulkConfig = new BulkConfig { BatchSize = 50000, BulkCopyTimeout = _bulkTimeout,
                UpdateByProperties = new List<string> { nameof(EntryMap.Columns.EntryId), } };

  var entries = EntryIds.Select(x => new Entry { EntryId = x }).ToList();
  var headers = EntryIds.Select(x => new Header { EntryId = x }).ToList();
  
  _dbContext.BulkRead(entries, bulkConfig);
  _dbContext.BulkRead(headers, bulkConfig);

The entries return with data, but the headers return without data (only have value on field EntryId).

As I check the profiler, the script is correct.

Would you please help me check it ?

Thank

**Comment by borisdj** [comment]
Can you a test where the issue would be reproducible.

**Comment by kosaurang** [comment]
I found the root cause.

Because I'm using the same bulkConfig for 2 entities.

My code update :

var bulkConfig = new BulkConfig { BatchSize = 50000, BulkCopyTimeout = _bulkTimeout,
                UpdateByProperties = new List<string> { nameof(EntryMap.Columns.EntryId) } };


  var bulkHeaderConfig = new BulkConfig
  {
      BatchSize = 50000,
      BulkCopyTimeout = _bulkTimeout,
      UpdateByProperties = new List<string> { nameof(EntryMap.Columns.EntryId), }
  };

var entries = EntryIds.Select(x => new Entry { EntryId = x }).ToList();
var headers = EntryIds.Select(x => new Header { EntryId = x }).ToList();

_dbContext.BulkRead(entries, bulkConfig);
_dbContext.BulkRead(headers, bulkConfig);

**Comment by borisdj** [comment]
Similar to: https://github.com/borisdj/EFCore.BulkExtensions/issues/640
