### ISSUE TITLE
Columns altered to null in output table during BulkInsert call (v5) SDK

### ISSUE THREAD

**Issue by rondelward-pf** [borisdj/EFCore.BulkExtensions#723]
Hey Boris,

This issue is related to this one https://github.com/borisdj/EFCore.BulkExtensions/issues/661. 

We recently updated to EF Core 5.X and EFCore.BulkExtensions 5.4.1. Unfortunately this has led to some performance degradation on our `BulkInsert` calls specifically. After a bit of digging, we noticed the new `Alter` statement that was introduced to fix [BulkInsertOrUpdateOrDelete ](https://github.com/borisdj/EFCore.BulkExtensions/issues/113#issuecomment-448950354). In our case we have some very wide tables (200+ cols) and this alter statement is taking upwards of 10 seconds on occasion so quite a bit of overhead for our specific use case.  

>AlterTableColumnsToNullable was fix for issue: BulkInsertOrUpdateOrDelete with Output
So it could be changed to be called only for that method and not for others.

This was fixed in https://github.com/borisdj/EFCore.BulkExtensions/commit/4c525151bbc24d97dfd1d532dba31a18eea067df but was only added to the v6 path. Unfortunately for us, we are using .Net Core 3.1 (.Net Standard 2.1) and so we're unable to upgrade to version 6.0.4 because that would require us to upgrade our stack to .NET 6 and EF Core 6 which may take us quite a while. 

You mentioned that version [5.X is no longer being maintained](https://github.com/borisdj/EFCore.BulkExtensions/issues/661#issuecomment-1007760252) but I'm wondering if it is possible to make an exception for this case since the change itself is rather small and could have a big performance impact for solutions which are still dependent on .Net Standard 2.1. 

I'd be happy to create the PR with the changeset into the `origin/EFCore5.0` branch if you think that is appropriate. I don't currently have the permission to do so however. 

Thanks for the awesome library though! Let me know what you think is best.

**Comment by rondelward-pf** [comment]
Thanks Boris! Linked the PR to this issue. Let me know if there are other changes you'd like to see

**Comment by borisdj** [comment]
Published v.3.6.5
