### ISSUE TITLE
`BatchDelete` and `BatchUpdate` operation for `Postgres` is not working correctly

### ISSUE THREAD

**Issue by ChebotkovDV** [borisdj/EFCore.BulkExtensions#726]
At the moment, the `BatchDelete` and `BatchUpdate` operation for `Postgres` is not working correctly. v.6.2.8

After a long debugging, I managed to find out the following:

When `GetRelationalCommandTemplate` is called, the alias for the table is determined as far as I understand based on the `first letter of the table name`. In my case it was "...AS a". During the cast of `RestructureForBatch`, "DELETE i" is replaced with "DELETE". It turns out that these methods will work only for tables whose name begins with "i". 

The tests pass because the table in the tests is called `Items`.

**Comment by borisdj** [comment]
Fixed with v6.2.9
