### ISSUE TITLE
Incorrect StatsInfo

### ISSUE THREAD

**Issue by sanket-pattekar** [borisdj/EFCore.BulkExtensions#728]
I using the 5.0.5.0 version for MSSql database. Getting incorrect value for StatsNumberInserted. 

My table has 4 rows and the input also has the same data (4 rows that have the same data for all columns including primary key). When calling the BulkInsertOrUpdate() method, it StatsNumberInserted=4. In this case I expect StatsNumberUpdated=4. The same stats are obtained using BulkInsertOrUpdateOrDelete() method.

Want the correct stats to be dispalyed to the user. Please update

**Comment by borisdj** [comment]
v5 is not actively maintained.
