### ISSUE TITLE
Q: refer temp table in SetSynchronizeFilter ?

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#730]
Hello,

I want to do a partial sync using `BulkInsertOrUpdateOrDelete` and i was wondering if i could somehow refer to the temp table.

Here's some (pseudo) code on what i'm trying to achieve:
``` csharp
class Order {
     Guid Id {get;set;} 
    int ExternalId { get;set;}
     List<OrderLine> OrderLines {get;set;}
}

class OrderLine {
    Guid Id {get;set;} 
    int ExternalId { get;set;}
    Guid OrderId {get;set;}
    Order order {get;set;}
}

...


// Orders are upserted (based on ext. id)
context.BulkInsertOrUpdate(entitiesList);

// Orderlines  are synced (based on ext. id), because orderlines can be deleted, created or updated.

var config = new BulkConfig();
config.UseTempTable = true;
config.UpdateByProperties = new List<string>() {  nameof(OrderLine.ExternalId)  }

config.SetSynchronizeFilter<OrderLine>(orderLine =>  tempTable.Select(c => c.OrderId).Contains(orderLine.OrderId) );

context.BulkInsertOrUpdateOrDelete(entitiesList, config);

```

In my sample, orderLines get inserted or update, orderlines in the database that are not in my input are deleted and the match for this is the OrderId.

Any other advice would also be very welcome of course.

**Comment by borisdj** [comment]
SyncFilter can't use tempTable, it only can query columns of it's table.
If I understand correctly you want to sync OrderLines only from Orders in list and not touch others.

You could use Upsert first also for OrderLines, then use BulkRead to get db OrderLines of your Orders from List, filter those for Delete and call BulkDelete with them.

**Comment by sommmen** [comment]
> SyncFilter can't use tempTable, it only can query columns of it's table. If I understand correctly you want to sync OrderLines only from Orders in list and not touch others.
> 
> You could use Upsert first also for OrderLines, then use BulkRead to get db OrderLines of your Orders from List, filter those for Delete and call BulkDelete with them.

Yes i think you're right. I was hoping to get around doing the extra read by doing it this way but that's not possible. Anyways thanks for taking a quick look!
