### ISSUE TITLE
Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Microsoft.Data.SqlClient.SqlConnection'

### ISSUE THREAD

**Issue by dario-hd** [borisdj/EFCore.BulkExtensions#731]
Hi guys, we are using .NET5 and https://www.npgsql.org/efcore/. We are trying to use `BulkInsertAsync`, but that's what we get. What are we missing?

**Comment by dario-hd** [comment]
It actually works with .NET 6 using the version 6.3.0 of your library. When using the version 5.4.2, I get the error mentioned in the title. You can check it out here: [EFCore.BulkExtensions.Evaluation.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7889987/EFCore.BulkExtensions.Evaluation.zip)

**Comment by borisdj** [comment]
v5 is not actively maintained.

**Comment by borisdj** [comment]
Actually Postgres support was added in v6, prior it was not supported at all.

**Comment by dario-hd** [comment]
Cool, then we will use it as soon as we upgrade to .NET 6, looking forward 😊
