### ISSUE TITLE
Cannot update identity column

### ISSUE THREAD

**Issue by doruxan** [borisdj/EFCore.BulkExtensions#734]
When using includeGraph option, it throws "Cannot update identity column 'FooBarProperty' " error for one of entity types. But if I exclude it, that way it throws the error of "PropertyName 'FooBarProperty' specified in 'PropertiesToExclude' not found in Properties." for another entity type.

**Comment by borisdj** [comment]
Can you write a test where the issue was reproducible.
Also to note that IncludeGraph feature was a PR, so not sure if it work for all complex cases.
