### ISSUE TITLE
Signed NuGet

### ISSUE THREAD

**Issue by romanrotter** [borisdj/EFCore.BulkExtensions#735]
Hello,

can you please sign assembly with snk so that we can use it with ClickOnce and other signed projects?

Thank you.
Roman

**Comment by borisdj** [comment]
It already is Signed https://github.com/borisdj/EFCore.BulkExtensions/issues/161

**Comment by romanrotter** [comment]
Thank you, I didn't test 6.x version. 
We are still using .net 4.8 so that stuck on 3.x EF. For now we signed by ourselves, but I saw that 3.x is still alive and updated.
Anyway, after migration to .net 6 it should be resolved.
