### ISSUE TITLE
Question: updating primary key?

### ISSUE THREAD

**Issue by projectje** [borisdj/EFCore.BulkExtensions#736]
Small question, is this the fastest way to update a part of a composite primary or is there a single command to do so?

 ```
 List<EXAMPLE> items_before = new();
 List<EXAMPLE> items_after = new();
 _mapper.Map(items, items_before);
  foreach (var item in items)  
        item.CompositePrimaryKeyPart = NewValue;
_mapper.Map(items, items_after);
  await localcontext.BulkDeleteAsync(items_before);
  await localcontext.BulkInsertAsync(items_after, new BulkConfig { SetOutputIdentity = true });
```

**Comment by borisdj** [comment]
If you have some other unique column(s) besides the one being updated it could be done with BulkUpdateAsync and using UpdateByProperties.
Otherwise Del and Insert as you have done it is the only way.

**Comment by projectje** [comment]
Thanks! Nice.
