### ISSUE TITLE
BulkInsertOrUpdateAsync doesn't populate identity property

### ISSUE THREAD

**Issue by oresttkachukd** [borisdj/EFCore.BulkExtensions#741]
I would like to get output identity for created entities. I've tried two sets of options:

- BulkInsertOrUpdateAsync(
                entities.ToList(),
                opts =>
                {
                    opts.SetOutputIdentity = true;
                });
                
Result: System.ArgumentNullException
Value cannot be null. (Parameter 'member')  at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)

- BulkInsertOrUpdateAsync(
                entities.ToList(),
                opts =>
                {
                    opts.IncludeGraph = true;
                });
                
Result: created entities don't have ids populated

Version: 3.4.0 
Newer versions (3.6.*) don't work with property ulong Version and following configuration (even in case it is added to ignored property list):
 .HasConversion(new NumberToBytesConverter<ulong>())
.HasColumnType("rowversion")
.IsRowVersion();
Result: System.InvalidOperationException
The given value '2001' of type UInt64 from the data source cannot be converted to type varbinary for Column 48 [Version] Row 1.
   at Microsoft.Data.SqlClient.SqlBulkCopy.ConvertValue(Object value, _SqlMetaData metadata, Boolean isNull, Boolean& isSqlType, Boolean& coercedToDataFeed)

Could you please suggest how such issues can be resolved?

**Comment by MelnikovVA** [comment]
Seems not to be working with BulkInsert in PostgreSQL either. After calling the method, the inserted entities retain the default value of the primary key data type (e.g. 0 in case of int).

**Comment by borisdj** [comment]
v3 is no longer maintained, you should try latest version.

**Comment by oresttkachukd** [comment]
@borisdj I've updated library to the last version and even BulkInsert 
 this.BulkInsertAsync(
                entities.ToList(),
                opts =>
                {
                    opts.SetOutputIdentity = true;
                    opts.PreserveInsertOrder = true;
                   });
 
still fails with the result: 
System.ArgumentNullException
Value cannot be null. (Parameter 'member') at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)

**Comment by oresttkachukd** [comment]
BulkInsertOrUpdateAsync(
entities.ToList(),
opts =>
{
opts.IncludeGraph = true;
});
Result: created entities don't have ids populated

It is still an issue as well, but created entities have ids populated with negative values, e.g -3, -2, -1.

Could you please help to identify what is done wrong with the operation configuration?
