### ISSUE TITLE
BulkInsertOrUpdateAsync Violation of PRIMARY KEY constraint

### ISSUE THREAD

**Issue by smallprogram** [borisdj/EFCore.BulkExtensions#748]
### My data collection and EFCore data entities
1. EFCore Entity
```C#
    public class yb_ml_code_1312
    {
        [Key]
        public string rid { get; set; }
        public string hilist_name { get; set; }
    }
```
2. dbcontext
```C#
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        public DbSet<yb_ml_code_1312> yb_ml_code_1312 { get; set; }
        

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
        }
    }
```

3. data collection
```C#
List<yb_ml_code_1312> data = new List<yb_ml_code_1312>()
{
    new yb_ml_code_1312
    {
        rid="1",
        hilist_name ="a"
    },
    new yb_ml_code_1312
    {
        rid="1",
        hilist_name ="b"
    },
    new yb_ml_code_1312
    {
        rid="2",
        hilist_name ="c"
    },
}
```

### Bulk operation
```C#
var bulkConfig = new BulkConfig {
                CalculateStats = true, 
                BulkCopyTimeout = 0, 
                WithHoldlock = false ,
                UpdateByProperties = new List<string> { "rid" } 
            };
await context.BulkInsertOrUpdateAsync(data , bulkConfig);
```
### Exception

**Microsoft.Data.SqlClient.SqlException (0x80131904): PRIMARY KEY constraint 'PK_yb_ml_code_1312' violated. Cannot insert duplicate key in object 'dbo.yb_ml_code_1312'. The duplicate key value is (1)**

### My Confusion
**In theory, I have set UpdateByProperties, and its primary key, using BulkInsertOrUpdateAsync, under normal circumstances, if a duplicate primary key is encountered, other fields other than the primary key should be updated directly, and the primary key duplicate error should not be reported.**

**Comment by borisdj** [comment]
Your `data` list has 2 elements with property `rid="1"` which is used as unique.
You should remove duplicates from the list before calling the Bulk ops.

**Comment by smallprogram** [comment]
> Your `data` list has 2 elements with property `rid="1"` which is used as unique and Bulk requires single occurrence. You should remove duplicates from the list before calling the Bulk ops.

Understood. That is to say, the update operation is based on the existing data in the database. rather than based on the data to be processed.
Thanks for your reply, thank you

**Comment by borisdj** [comment]
> the update operation is based on the existing data in the database

Not sure I would formulate it this way.

Better to say entities from the list are Inserted if not found in Db, or they are matched then Updated based on unique components which is PK or custom _UpdateByProperties_ .
Those unique component have to unique both in DB and in the input list.
