### ISSUE TITLE
Postgres BatchUpdate and BatchDelete issue - FromSqlRaw

### ISSUE THREAD

**Issue by IvanMarusic** [borisdj/EFCore.BulkExtensions#752]
Hi,

I get the following exception when trying to perform BatchUpdate and BatchDelete using the FromSqlRaw method. The following example contains the simplified code to easily reproduce the issue.

Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "("

Code example:

`await DbContext.Database.BeginTransactionAsync();`

`string squery = " SELECT * FROM bw.\"SomeEntity\" ";
var query = DbContext.Set<SomeEntity>().FromSqlRaw(squery);`

`await query.Where(p => p.Id == new Guid("f5615489-b349-45ab-b0d0-3810e99ccb43"))
                 .BatchUpdateAsync(new SomeEntity
                 {
                     DateUpdated = DateTime.UtcNow,
                 }, new List<string>() { nameof(SomeEntity.DateUpdated) });`

`await DbContext.Database.CommitTransactionAsync();`

Regards

**Comment by borisdj** [comment]
FromSqlRaw is not supported.
When creating query with raw sql then you can directly write sql update code there.
