### ISSUE TITLE
SetOutputIdentity for Postgres does not seem to work

### ISSUE THREAD

**Issue by douglasg14b** [borisdj/EFCore.BulkExtensions#753]
I'm generating entities, and then running 

```cs
        await _context.BulkInsertAsync(mineGroups, opt => {
            opt.SetOutputIdentity = true;
        });
        
        await _context.BulkSaveChangesAsync();
```

However, while they are all inserted, none of them come back with Ids.

The Ids are DB generated.

I swear this used to with with SQL Server before I switched to Postgres (And had to stop using this lib till v6). Is this now how it should work?

**Comment by borisdj** [comment]
If you are using Bulk ops directly then no need to call BulkSaveChanges.
Secondly output works, you can check it in Test on line:
https://github.com/borisdj/EFCore.BulkExtensions/blob/80a536da8210285a18ba5e79f824e1a2a3e87239/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs#L105

If still having issue write a test or alter this one where the issue would be reproducible.

**Comment by douglasg14b** [comment]
>  Secondly output works, you can check it in Test on line:

I'm not sure if I follow?

```
        await _context.BulkInsertAsync(mineGroups, opt => {
            opt.SetOutputIdentity = true;
        });
```

When I run this, the Id's for every entity passed in `mineGroups`  is `0`. Unless that's the expected result, I'm unsure of what you are saying?

**Comment by borisdj** [comment]
That is not expected.
I was saying that in the PG test referenced above I can confirm that it works, `ItemId` gets loaded with value '3'.
Meaning can't replicate your problem, so you should write entire example for test where it would be reproducible.

**Comment by douglasg14b** [comment]
Gotcha!

**Comment by margyl-orbitmi** [comment]
I'm having the same issue as @borisdj. 
Calling await db.BulkInsertAsync(items, new BulkConfig {SetOutputIdentity = true})
does not update the Id value on the entities

**Comment by borisdj** [comment]
Fixed with v.6.3.9

**Comment by douglasg14b** [comment]
@borisdj  Thanks for looking more into this!

For my own curiosity/knowledge, what was the problem?
