### ISSUE TITLE
Support for BulkRead from a sql view

### ISSUE THREAD

**Issue by topherZa** [borisdj/EFCore.BulkExtensions#757]
Is there support for reading from a sql View thats configured as a keyless entity in EF?

I get the following exception:

>  Error occurred while processing batch.System.ArgumentNullException: Value cannot be null. (Parameter 'name')
>    at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
>    at Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Table(String name, String schema)
>    at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
>    at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
>    at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)

- DbContext
```
public DbSet<SomeSqlView> SomeSqlViews { get; set; }

builder.Entity<SomeSqlView>()
                .ToView("SomeSqlView")
                .HasNoKey();
```
- My entity:
```
public class SomeSqlView
{
        public string Reference { get; set; }
}
```

- Bulk read code:
```
var viewReferenes = model.Select(x => new SomeSqlView { Reference = x.Reference }).Distinct().ToList();
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(SomeSqlView.Reference) } };
await dbContext.BulkReadAsync(viewReferenes, bulkConfig);
```

Example sql:
```
CREATE VIEW [TPO].SomeSqlView
As
(
	SELECT 
		t.Id,
		t.Name,
		t.Reference,
		CASE WHEN g.StatusId = 0 then 'Waiting'
			 when g.StatusId = 1 then 'Processing'
			 when g.StatusId = 2 then 'Processed'
		end StatusText,
	from [TPO].Tupper t
	OUTER APPLY
	(
		select top 1 StatusId
		from TPO.ZLower p on p.Id = t.ZLowerId
		Order by p.CreatedDate desc
	) AS g
			
)
```
It would be great if this could  work because there's a bunch of computed properties on the view I'd prefer not to have to work out again after doing a bulk read on the main single object.

Edit: updated by adding example sql to create the view.

**Comment by borisdj** [comment]
Not sure about this.
Can you also write sql code for creating the view in the example.

**Comment by topherZa** [comment]
@borisdj , have updated the question with example sql. The actual view is a bit more complex with a few more outer apply's and cross apply, with more computed columns, though they kind of all follow this concept/structure.

**Comment by borisdj** [comment]
I have tried with simple view over entity Item from Test.
View Definition:
```sql
CREATE VIEW SomeSqlView
As
(
	SELECT 
		t.ItemId,
		t.Name,
		t.Description
	FROM Item t
)
```

```C#
public DbSet<SomeSqlView> SomeSqlViews { get; set; }

public class SomeSqlView
{
    public string Name { get; set; }

    public string Description { get; set; }
}

//Test
public void OperationsTest(DbServer dbServer, bool isBulk)
{
    ContextUtil.DbServer = dbServer;
    using var context = new TestContext(ContextUtil.GetOptions());

    var list = new List<string> { "Name 1" };
    var viewReferenes = list.Select(x => new SomeSqlView { Name = x }).Distinct().ToList();
    var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(SomeSqlView.Name) } };
    context.BulkRead(viewReferenes, bulkConfig);
}
```
This passes, so the issue is something specific in your case, could be some joint.

**Comment by topherZa** [comment]
Ok, thanks, I haven't been able to figure out what the difference is. I've had to work around it. I appreciate the help.
