### ISSUE TITLE
SubChild foreign key issue

### ISSUE THREAD

**Issue by MrStamina** [borisdj/EFCore.BulkExtensions#759]
Hi,
I'm using  " context.BulkInsert(strips, b => b.IncludeGraph = true)" to add multiple items in my database but I have a problem, the foreignKey of subchild is not added 

![image](https://user-images.githubusercontent.com/8642891/154717725-76079f63-abd0-41e7-ab66-2a30bcd56aa0.png)
Am I missing an option in BulkConfig or is it my model who is not good ?

If I try to set the foreign key then I have a "Merge statement conflict with Foreign Key"
Thanks in advance

**Comment by borisdj** [comment]
Can you write reproducible example like a test for the issue.

**Comment by MrStamina** [comment]
Here a part of my code :


// Classes
	public class FunctioningPointV2
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }       
        public  int StripV2Id { get; set; }		
	public  ICollection<SubtableInfoV2> SubtableInfos { get; set; }
    }
	
	public class SubtableInfoV2
    {
        public int Id { get; set; }       
        public int EntryTempSensorId { get; set; }
        public int ExitTempSensorId { get; set; }
        public int ValveOpeningSequenceId { get; set; }
        public int FirstValveActiveTop { get; set; }
		
	}
	
	public partial class StripV2
    {
        public int Id { get; set; }
        public string StripCode { get; set; }
        public DateTime Date { get; set; }
        public DateTime? EndStripDate { get; set; }
		public ICollection<FunctioningPointV2> FunctioningPoints { get; set; }
	}

//Context

	public sealed class MyContext :  DbContext
    {
	
		public MyContext(string connectionString, bool creation) : base()
        {
            _connectionString = connectionString;
            if (creation)
            {
                Database.EnsureCreated();
            }
            else
            {
                Database.Migrate();
               
            }           

        }
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(_connectionString);
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
		 modelBuilder.Entity<FunctioningPointV2>(entity =>
            {               
               
                entity.HasMany(e => e.SubtableInfos)
                    .WithOne() 
						//Here I tried to add HasForeignKey but I have merge error
                    .OnDelete(DeleteBehavior.Cascade);
			};
					
			 modelBuilder.Entity<StripV2>(entity =>
            {              
                              
                entity.HasMany(p => p.FunctioningPoints)
                    .WithOne()
                    .HasForeignKey(s => s.StripV2Id)
                    .OnDelete(DeleteBehavior.Cascade);           


            });
			
			
		}
		
		 public DbSet<StripV2> Strips { get; set; }
		 public DbSet<FunctioningPointV2> FunctioningPoints { get; set; }
		 public DbSet<SubtableInfoV2> SubtableInfos { get; set; }
	}
		
//Save Strips

		public void SaveStrips(List<StripV2> strips)
        {
			using (var context = new MyContext(GetConnectionDataWorkingBase(), false))
            {
               
				
		var strip = new StripV2
                    {
                        StripCode = "2050269",
                        Date = DateTime.Now,
                        EndStripDate = DateTime.Now,
                        FunctioningPoints = new List<FunctioningPointV2>
                        {
                            new FunctioningPointV2
                            {
                                Date = DateTime.Now,
                                SubtableInfos = new List<SubtableInfoV2>
                                {
                                    new SubtableInfoV2{EntryTempSensorId = 1, ExitTempSensorId = 2, ValveOpeningSequenceId = 3, FirstValveActiveTop = 15},
                                    new SubtableInfoV2{EntryTempSensorId = 1, ExitTempSensorId = 3, ValveOpeningSequenceId = 3, FirstValveActiveTop = 15},
                                    new SubtableInfoV2{EntryTempSensorId = 1, ExitTempSensorId = 2, ValveOpeningSequenceId = 4, FirstValveActiveTop = 15}


                                }
                            }
                        }
                    };
                              strips.Add(strip);
                              var bulkConfig = new BulkConfig{IncludeGraph = true, PreserveInsertOrder = true};
		             context.BulkInsert(strips, bulkConfig);
                              context.SaveChanges();
			}
		}

**Comment by MrStamina** [comment]
I'm using EntityFrameworkCore 3.1.22 and EFCore.Bulkextensions 3.6.5

**Comment by MrStamina** [comment]
Hey, I decided to use the option 1 :  
// Option 1
using (var transaction = context.Database.BeginTransaction())
{
    context.BulkInsert(entities, new BulkConfig { SetOutputIdentity = true });
    foreach (var entity in entities) {
        foreach (var subEntity in entity.ItemHistories) {
            subEntity.ItemId = entity.ItemId; // sets FK to match its linked PK that was generated in DB
        }
        subEntities.AddRange(entity.ItemHistories);
    }
    context.BulkInsert(subEntities);
    transaction.Commit();
}


A lot of code line for my solution but it works perfectly.

**Comment by borisdj** [comment]
In v6 six it seems to work fine, not sure but I think that initially explicit definition of FK in entity class was required, that was later changed/enhanced.
Since v3 is not longer maintained, for now keep Option 1, until able to upgrade to v6 then you could try again with _IncludeGraph_.

**Comment by MrStamina** [comment]
Thanks for your anwser :)
