### ISSUE TITLE
BulkInsertOrUpdateAsync creates unique constraint even if one exists (pg)

### ISSUE THREAD

**Issue by cyril265** [borisdj/EFCore.BulkExtensions#761]
I tried executing the query generated by `SqlQueryBuilderPostgreSql.CountUniqueConstrain(tableInfo)` but it finds only the primary key constraint:

```sql
SELECT *
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
         INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE cu0
                    ON cu0.CONSTRAINT_NAME = tc.CONSTRAINT_NAME
WHERE (tc.CONSTRAINT_TYPE = 'UNIQUE' OR tc.CONSTRAINT_TYPE = 'PRIMARY KEY')
  AND tc.TABLE_NAME = 'person';
```
output: 
| constraint\_catalog | constraint\_schema | constraint\_name | table\_catalog | table\_schema | table\_name | constraint\_type | is\_deferrable | initially\_deferred | enforced | table\_catalog | table\_schema | table\_name | column\_name | constraint\_catalog | constraint\_schema | constraint\_name |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| masterdata | public | pk\_person | masterdata | public | person | PRIMARY KEY | NO | NO | YES | masterdata | public | person | id | masterdata | public | pk\_person |

I tried a different query to find unique constraints and it seems to work:

```sql
select idx.relname as index_name,
       insp.nspname as index_schema,
       tbl.relname as table_name,
       tnsp.nspname as table_schema,
       pgi.indisunique
from pg_index pgi
         join pg_class idx on idx.oid = pgi.indexrelid
         join pg_namespace insp on insp.oid = idx.relnamespace
         join pg_class tbl on tbl.oid = pgi.indrelid
         join pg_namespace tnsp on tnsp.oid = tbl.relnamespace
where pgi.indisunique
  and tbl.relname = 'person';
```
output:
| index\_name | index\_schema | table\_name | table\_schema | indisunique |
| :--- | :--- | :--- | :--- | :--- |
| pk\_person | public | person | public | true |
| ix\_person\_email\_address | public | person | public | true |
| tempUniqueIndex\_person\_email\_address | public | person | public | true |

Table definition:

```sql
create table person
(
    id            uuid default gen_random_uuid() not null
        constraint pk_person
            primary key,
    first_name    varchar(500)                   not null,
    last_name     varchar(500)                   not null,
    email_address varchar(500)                   not null,
    phone_number  varchar(500),
    mobile_phone  varchar(500),
    street        varchar(1000)                  not null,
    zip           varchar(10)                    not null,
    country_code  varchar(2)                     not null,
    tenant_id     uuid                           not null
        constraint fk_person_tenant_tenant_id
            references tenant
            on delete cascade
);
alter table person
    owner to postgres;
create index ix_person_tenant_id
    on person (tenant_id);
create unique index ix_person_email_address
    on person (email_address);
create unique index "tempUniqueIndex_person_email_address" --created by BulkInsertOrUpdateAsync 
    on person (email_address);
```

Bulk config
```c#
BulkConfig _bulkConfig = new()
    {
        BatchSize = 1000,
        TrackingEntities = false,
        UpdateByProperties = new() {nameof(Person.EmailAddress)},
        PropertiesToExclude = new() {nameof(Person.Id)},
    }
```

Postgres version: `PostgreSQL 14.1, compiled by Visual C++ build 1914, 64-bit`

**Comment by borisdj** [comment]
For Upsert On Postgres UniqueIndex alone is not enough, UniqueConstrain on that index is also required, so this query check for that.
Still you could have situation the you have Index, but do not have Constrain.
If that's the case could you add Constrain for this Index in DB permanently.

**Comment by cyril265** [comment]
Thank you for responding!
You are right about the missing constraint. I added it and it worked. I didn't know there was a difference between unique index and constraint.

**Comment by karlanke** [comment]
Could you help explain a bit why this is the case? By my reading, the postgres query builder uses `ON CONFLICT...` statements, which I would have thought would trigger on an existing unique index. I think this is relevant both because it's more idiomatic in EF Core to do `HasIndex().IsUnique()` and for things like partial indexes where we still might want to have upsert behavior.
