### ISSUE TITLE
Ambiguous call exception when updating to v6

### ISSUE THREAD

**Issue by karinehovhannisyan** [borisdj/EFCore.BulkExtensions#762]
Hi, We are updating BulkExtensions to v6.4.1 (latest at the moment). But the solution won't build and throws the following error:

Error	CS0121	The call is ambiguous between the following methods or properties: `'Microsoft.EntityFrameworkCore.SqlServerIndexBuilderExtensions.IncludeProperties<TEntity>(Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder<TEntity>, System.Linq.Expressions.Expression<System.Func<TEntity, object?>>)' and 'Microsoft.EntityFrameworkCore.NpgsqlIndexBuilderExtensions.IncludeProperties<TEntity>(Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder<TEntity>, System.Linq.Expressions.Expression<System.Func<TEntity, object>>)'`

Not only in Entity Configuration files but also in `.Designer.cs` files on the method `IncludeProperties`.

And when we use the 5.x.x. version on a .NET 6 project, the solution builds successfully but throws the following:

`System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IEntityType Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(Microsoft.EntityFrameworkCore.Metadata.IModel, System.Type)'.`

Can you help with this please?

**Comment by borisdj** [comment]
Dupe: https://github.com/borisdj/EFCore.BulkExtensions/issues/669

**Comment by karinehovhannisyan** [comment]
Oops, sorry.
