### ISSUE TITLE
V 3.6.6 does not contain BulkSaveChanges and OnSaveChangesSetFK

### ISSUE THREAD

**Issue by Djole1994** [borisdj/EFCore.BulkExtensions#765]
V 3.6.6 does not contain BulkSaveChanges and OnSaveChangesSetFK...
![image](https://user-images.githubusercontent.com/93575470/155969981-38a45cc4-8f6b-4cf3-ac55-59f30a3227f3.png)

**Comment by borisdj** [comment]
BulkSaveCh. was added in v6, after v3 was no longer actively maintained.
DUPE https://github.com/borisdj/EFCore.BulkExtensions/issues/754
