### ISSUE TITLE
Could not load file or assembly Microsoft.Extensions.DependencyModel

### ISSUE THREAD

**Issue by ta6636** [borisdj/EFCore.BulkExtensions#766]
Hi, I've installed v3.6.6 into my Azure Functions V3 project, where I use Serilog. By some reason this package conflicts with the package `Serilog.Settings.Configuration v3.3.0` (https://www.nuget.org/packages/Serilog.Settings.Configuration/3.3.0) by throwing the error during the startup process:

Could not load file or assembly `'Microsoft.Extensions.DependencyModel', Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')`

when using this line
`Log.Logger = new LoggerConfiguration().ReadFrom.Configuration(config).CreateLogger();`

I installed `Microsoft.Extensions.DependencyMode v3.0.0.0` but the issue remains. Any ideas where can I find the issue ?

**Comment by borisdj** [comment]
Not sure about this, haven't seen that exception before.

**Comment by brunocasarotti** [comment]
I am having the same problem and it started after I installed the EFCore.BulkExtensions.
`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

![image](https://user-images.githubusercontent.com/20110633/167932058-8e922b42-956c-41e2-8186-9d30184de575.png)

What is interesting is that it runs locally but fails when  I deploy my application to AWS, it's a lambda function

And the error also occurs when creating the log:

```
Log.Logger = new LoggerConfiguration()
    ReadFrom.Configuration(_configuration)
    WriteTo.Console(new JsonFormatter())
    CreateLogger();
```

**Comment by brunocasarotti** [comment]
Some news on this, I had enabled the `PublishReadyToRun` on my code and I was compiling it on windows and then publishing it to aws. Then I saw [this thread](https://github.com/aws/aws-lambda-dotnet/issues/631) and built my application on WSL instead of windows. Doing so, the error was gone and I was able to use the bulk extensions.
