### ISSUE TITLE
Unable to BulkInsertOrUpdateAsync

### ISSUE THREAD

**Issue by minkminktc** [borisdj/EFCore.BulkExtensions#773]
Hello my team received this error

"Cannot insert the value NULL into column 'TBL_ID', table 'CA_10300.dbo.DC_ADDRESS_DOPA_BIND_THP'; column does not allow nulls. UPDATE fails.\r\nThe statement has been terminated."

Our team has to read data from one database and insert or update into another MSSQL database in order to do this we do not use auto-increment for running PK then we received an error above. Has anyone got a solution for this?

**Comment by borisdj** [comment]
When InsertOrUpdate-ing data there needs to be unique column(s) by which Update is done.
If it is some column other then PK then try excluding PK with config.
If still having issue write a test with example where it would be reproducible.

**Comment by minkminktc** [comment]
@borisdj Thank you mate, my team try an alternative way, they execute a bulk delete then call for a bulk insert. Is it practical?

**Comment by borisdj** [comment]
That is also fine.

**Comment by minkminktc** [comment]
@borisdj Thank you so much
