### ISSUE TITLE
Issues with BatchDelete(), canceling itself?

### ISSUE THREAD

**Issue by SammyHeutz** [borisdj/EFCore.BulkExtensions#776]
Hi,

We use the EFCore.BulkExtensions in a daily process that runs multiple times each night.
This entails massive operations, in which BatchDelete() is used, and this deletes millions of rows.
However, the process seems to kill itself more often than not. Our logging just shows the delete operation has started, and then stops. No error is returned, but the process stops entirely, and we have to manually restart the process the next day. This manual restarting sometimes takes multiple attempts before it works.

In SQL Query Store, we can see that the operation is cancelled, for instance in below image:
![image](https://user-images.githubusercontent.com/101629816/158340873-674eb0e3-44fd-4665-81b0-66fbc1ba68e8.png)
We can see that the first automatic attempt cancelled itself and took longer. The manual restart of the process took less time and did complete succesfully.

Below the piece of code we use:
![image](https://user-images.githubusercontent.com/101629816/158339817-0a0f800b-5c82-41a4-89b2-df95bd4c4b66.png)

The predicate comes from below, and is basically a timerange from which data needs to be deleted (TimeBlock is indexed).
![image](https://user-images.githubusercontent.com/101629816/158341354-ccda7933-9872-4a2d-87c2-15ee51a01e51.png)

Here you can see our logging of the process. First example is a complete log, second example is where it stops during the BatchDelete() operation and cancels itself.

Success:
![image](https://user-images.githubusercontent.com/101629816/158343310-a57006de-b05c-4490-ad94-a01d91f0025d.png)

Fail:
![image](https://user-images.githubusercontent.com/101629816/158343160-ab5afde8-f137-4fed-a9ca-7480204638da.png)

The logging comes from this piece of code, as you can see, no error is logged and it basically just stops:
![image](https://user-images.githubusercontent.com/101629816/158343714-217042d0-c56e-4ac6-ab33-310eb4ca8ed9.png)

Does anyone have any idea why this is happening, and what we can do to improve this?

**Comment by SammyHeutz** [comment]
Additional information: I found we are using an old version:
  <PackageReference Include="EFCore.BulkExtensions" Version="2.4.7" />
  
  Would using a newer version perhaps solve the problem? And will our initial piece of code still work if I were to change versions?

**Comment by borisdj** [comment]
Few notes here.
You can first try updating latest version per group, from 2. to 6.x
In the ReadMe there it table with info regarding used version, target and compatibility.

Secondly you could also catch sql to be executed and test it with RawSql to see if the issue remains.
