### ISSUE TITLE
PostgreSQL PropertiesToExcludeOnUpdate not implemented?

### ISSUE THREAD

**Issue by suissois** [borisdj/EFCore.BulkExtensions#778]
Hi - love this library! Question, is PropertiesToExcludeOnUpdate not implemented for PostgreSQL ?

**Comment by borisdj** [comment]
That's right, currently it works only for SqlServer.

**Comment by MatiKloster** [comment]
Love this library as well ❤️ 
Any ETA on this?

**Comment by MatiKloster** [comment]
I couldn't wait so I cloned the repo and wrote a single line that makes the trick.

Perhaps what I did is naive and wrong. But it's working. 
I think it's worth taking a look at
Here you can see the changes

https://github.com/borisdj/EFCore.BulkExtensions/compare/master...MatiKloster:PropertiesToExcludeOnUpdatePostgres?expand=1

**Comment by bjermeland** [comment]
> Thx for contrib. Fix is Merged, and test passes. Will be published with next v.

When will it be published?

**Comment by borisdj** [comment]
NuGet v.6.5.1
