### ISSUE TITLE
BulkInsertAsync with IncludeGraph not inserting all subentities in 6.4.2 (Worked in 3.6.5)

### ISSUE THREAD

**Issue by jcoliz** [borisdj/EFCore.BulkExtensions#780]
Hi, has there been a change in how IncludeGraph works since V3? I recently upgraded my project from .NET Core 3.1 to .NET 6, and also updated BulkExtensions. In so doing, my usage of BulkInsertAsync no longer operates correctly.

## Given: A set of entities with subentities

As a test case, I've constructed data closely following the example on the README:

```C#
      var txs = new List<Transaction>();
      for(int i=1; i<=25; i++)
      {
          var tx = new Transaction() { Payee = i.ToString(), Timestamp = DateTime.Now - TimeSpan.FromDays(i) };
          var splits = new List<Split>();
          for (int j=1; j<=i; j++)
          {
              var split = new Split() { Amount = j };
              splits.Add(split);
          }
          tx.Splits = splits;
          txs.Add(tx);
      }
```

## When: Bulk inserting them with IncludeGraph

```C#
    await this.BulkInsertAsync(txs, b => b.IncludeGraph = true);
```

## Then: Not all subentities inserted

The result in the database is that all 25 transactions are added, and only ONE split is added per transaction. So 25 total. In memory, the Transaction's IDs are all set correctly on the entities. The TransactionID for all Splits is set correctly (even the ones which aren't showing up the DB), and Split IDs are set only for those splits which are in the database. Zeroes for all the others.

I also tried setting SetOutputIdentity and/or PreserveInsertOrder to true as well. No change in behavior.

Expected, of course, is that there are 25 transactions and 325 splits total saved. This worked as expected in 3.6.5.

## Generated SQL

This is what Microsoft.EntityFrameworkCore.Database.Command reports:

```SQL
      SELECT TOP 0 T.[ID], T.[AccountID], T.[Amount], T.[BankReference], T.[Category], T.[Hidden], T.[Imported], T.[Memo], T.[Payee], T.[ReceiptUrl], T.[Selected], T.[Timestamp] INTO [TransactionsTemp9e02f2e1] FROM [Transactions] AS T LEFT JOIN [Transactions] AS Source ON 1 = 0;
      SELECT TOP 0 T.[ID], T.[AccountID], T.[Amount], T.[BankReference], T.[Category], T.[Hidden], T.[Imported], T.[Memo], T.[Payee], T.[ReceiptUrl], T.[Selected], T.[Timestamp] INTO [TransactionsTemp9e02f2e1Output] FROM [Transactions] AS T LEFT JOIN [Transactions] AS Source ON 1 = 0;
      MERGE [Transactions] WITH (HOLDLOCK) AS T USING (SELECT TOP 25 * FROM [TransactionsTemp9e02f2e1] ORDER BY [ID]) AS S ON T.[ID] = S.[ID] WHEN NOT MATCHED BY TARGET THEN INSERT ([AccountID], [Amount], [BankReference], [Category], [Hidden], [Imported], [Memo], [Payee], [ReceiptUrl], [Selected], [Timestamp]) VALUES (S.[AccountID], S.[Amount], S.[BankReference], S.[Category], S.[Hidden], S.[Imported], S.[Memo], S.[Payee], S.[ReceiptUrl], S.[Selected], S.[Timestamp]) OUTPUT INSERTED.[ID], INSERTED.[AccountID], INSERTED.[Amount], INSERTED.[BankReference], INSERTED.[Category], INSERTED.[Hidden], INSERTED.[Imported], INSERTED.[Memo], INSERTED.[Payee], INSERTED.[ReceiptUrl], INSERTED.[Selected], INSERTED.[Timestamp] INTO [TransactionsTemp9e02f2e1Output];
      SELECT [y].[ID], [y].[AccountID], [y].[Amount], [y].[BankReference], [y].[Category], [y].[Hidden], [y].[Imported], [y].[Memo], [y].[Payee], [y].[ReceiptUrl], [y].[Selected], [y].[Timestamp]
      FROM (
          SELECT [ID], [AccountID], [Amount], [BankReference], [Category], [Hidden], [Imported], [Memo], [Payee], [ReceiptUrl], [Selected], [Timestamp] FROM [TransactionsTemp9e02f2e1Output] WHERE [ID] IS NOT NULL
      ) AS [y]
      ORDER BY [y].[ID]
      IF OBJECT_ID ('[TransactionsTemp9e02f2e1Output]', 'U') IS NOT NULL DROP TABLE [TransactionsTemp9e02f2e1Output]
      IF OBJECT_ID ('[TransactionsTemp9e02f2e1]', 'U') IS NOT NULL DROP TABLE [TransactionsTemp9e02f2e1]
      SELECT TOP 0 T.[ID], T.[Amount], T.[Category], T.[Memo], T.[TransactionID] INTO [SplitTemp04c3babb] FROM [Split] AS T LEFT JOIN [Split] AS Source ON 1 = 0;
      SELECT TOP 0 T.[ID], T.[Amount], T.[Category], T.[Memo], T.[TransactionID] INTO [SplitTemp04c3babbOutput] FROM [Split] AS T LEFT JOIN [Split] AS Source ON 1 = 0;
      MERGE [Split] WITH (HOLDLOCK) AS T USING (SELECT TOP 25 * FROM [SplitTemp04c3babb] ORDER BY [ID]) AS S ON T.[ID] = S.[ID] WHEN NOT MATCHED BY TARGET THEN INSERT ([Amount], [Category], [Memo], [TransactionID]) VALUES (S.[Amount], S.[Category], S.[Memo], S.[TransactionID]) OUTPUT INSERTED.[ID], INSERTED.[Amount], INSERTED.[Category], INSERTED.[Memo], INSERTED.[TransactionID] INTO [SplitTemp04c3babbOutput];
      SELECT [y].[ID], [y].[Amount], [y].[Category], [y].[Memo], [y].[TransactionID]
      FROM (
          SELECT [ID], [Amount], [Category], [Memo], [TransactionID] FROM [SplitTemp04c3babbOutput] WHERE [ID] IS NOT NULL
      ) AS [y]
      ORDER BY [y].[ID]
      IF OBJECT_ID ('[SplitTemp04c3babbOutput]', 'U') IS NOT NULL DROP TABLE [SplitTemp04c3babbOutput]
      IF OBJECT_ID ('[SplitTemp04c3babb]', 'U') IS NOT NULL DROP TABLE [SplitTemp04c3babb]
```

## Models

There are two models at play here, a Transaction (the main entity) and a Split (the sub-entity). The code is here: [Transaction.cs](https://github.com/jcoliz/yofi/blob/master/YoFi.AspNet/Core/Models/Transaction.cs) and [Split.cs](https://github.com/jcoliz/yofi/blob/master/YoFi.AspNet/Core/Models/Split.cs)

Snipped down to just the relationships:
```C#
    public class Transaction
    {
        public int ID { get; set; }
        public ICollection<Split> Splits { get; set; }
    };

    public class Split
    {
        public int ID { get; set; }
        public int TransactionID { get; set; }
        public Transaction Transaction { get; set; }
    }
```

## Tables

```SQL
CREATE TABLE [dbo].[Transactions] (
    [ID]            INT             IDENTITY (1, 1) NOT NULL,
    [AccountID]     INT             NULL,
    [Amount]        DECIMAL (18, 2) NOT NULL,
    [BankReference] NVARCHAR (MAX)  NULL,
    [Category]      NVARCHAR (450)  NULL,
    [Memo]          NVARCHAR (MAX)  NULL,
    [Payee]         NVARCHAR (MAX)  NULL,
    [Timestamp]     DATE            NOT NULL,
    [Hidden]        BIT             NULL,
    [Imported]      BIT             NULL,
    [ReceiptUrl]    NVARCHAR (MAX)  NULL,
    [Selected]      BIT             NULL
);

CREATE TABLE [dbo].[Split] (
    [ID]            INT             IDENTITY (1, 1) NOT NULL,
    [Amount]        DECIMAL (18, 2) NOT NULL,
    [Category]      NVARCHAR (MAX)  NULL,
    [Memo]          NVARCHAR (MAX)  NULL,
    [TransactionID] INT             NOT NULL
);

CREATE NONCLUSTERED INDEX [IX_Split_TransactionID]
    ON [dbo].[Split]([TransactionID] ASC);

ALTER TABLE [dbo].[Split]
    ADD CONSTRAINT [PK_Split] PRIMARY KEY CLUSTERED ([ID] ASC);

ALTER TABLE [dbo].[Split]
    ADD CONSTRAINT [FK_Split_Transactions_TransactionID] FOREIGN KEY ([TransactionID]) REFERENCES [dbo].[Transactions] ([ID]) ON 
```

**Comment by jcoliz** [comment]
Also I made a focused repro for this issue: https://github.com/jcoliz/bulkextensions-730

**Comment by borisdj** [comment]
Have you tried to set _OmitClauseExistsExcept_ = True.

**Comment by jcoliz** [comment]
Thanks for looking at this. I tried your suggestion just now. Unfortunately, it still fails in the same way. I updated the github repo repro linked above with this change.

```diff
-        context.BulkInsert(parents,b => b.IncludeGraph = true);
+        context.BulkInsert(parents,b => { b.IncludeGraph = true; b.OmitClauseExistsExcept = true; });
```

**Comment by borisdj** [comment]
First to note that **IncludeGraph** feature was a PR.
So workaround without Graph is good one, it is even more efficient.

Still have tried to alter test `RunDefaultPKInsertWithGraph` to reproduce the issue but it still passes
(_Student C_ gets added twice as expected)
https://github.com/borisdj/EFCore.BulkExtensions/blob/4e6669aee8bd65e72869e1be3cd3376169344122/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L76

New code is following:
```C#
private void RunDefaultPKInsertWithGraph(DbServer dbServer)
{
	using (var context = new TestContext(ContextUtil.GetOptions()))
	{
		var department = new Department
		{
			Name = "Software",
			Divisions = new List<Division>
			{
				new Division{Name = "Student A"},
				new Division{Name = "Student B"},
				new Division{Name = "Student C"},
			}
		};
		var department2 = new Department
		{
			Name = "Software 2",
			Divisions = new List<Division>
			{
				new Division{Name = "Student C"},
				new Division{Name = "Student D"},
			}
		};

		context.BulkInsert(new List<Department> { department, department2 }, new BulkConfig { IncludeGraph = true });
	};
}
```

**Comment by jcoliz** [comment]
Hi, the difference between your test case and my use case is that your "Division" object doesn't have an Equals/GetHashCode. It is that customized equality definition which triggers this bug. So in your case, the two Divisions with the same name are not equal once they get assigned different IDs.

Please have a look at my example repo now, I created a new data type "Pets", which the Parents also contain. The difference between Pets and Children is that the Pets DO NOT have the custom Equals/GetHashCode implementations. Therefore, everything works fine. Have a look at the passing "BulkAddParentsWithPets" test. It is exactly the same as the failing "BulkAddParentsWithChildren" test, except that Pets are added instead of Children. What causes Children to fail and not Pets is that Children defines Equals/GetHashCode and does not include ID.

This is the Chidrens' code which triggers the problem:

```c#
    public override bool Equals(object obj)
    {
        return obj is Child child &&
                Age == child.Age &&
                Name == child.Name;
    }

    public override int GetHashCode()
    {
        return HashCode.Combine(Name, Age);
    }
```

It would be nice for me to avoid the workaround, only because in my use case, the actual call to BulkInsertAsync is DEEP in my data layer, at which point it has no idea what types its operating on. In fact, I use Set&lt;T&gt;() everywhere exactly to avoid ever even knowing what type I'm operating on in that layer.

**Comment by borisdj** [comment]
Can you alter the test in example to reproduce the issue.
I have extended Division with:
```C#
public class Division
{
	public override bool Equals(object obj)
	{
		return obj is Division division &&
			   Name == division.Name &&
			   DepartmentId == division.DepartmentId;
	}
	public Guid Id { get; set; }
	public string Name { get; set; }

	public Guid DepartmentId { get; set; }
	public Department Department { get; set; }
}
```

**Comment by jcoliz** [comment]
Yup, I will. One quick note, in the example there, only Equals is implemented. You'd need GetHashCode too, which I suspect is the primary cause. Something like

```c#
    public override int GetHashCode()
    {
        return HashCode.Combine(Name, DepartmentId);
    }
```

The other thing I notice is that the test code uses Guid's, where I use ints. Though I still think it's GetHashCode.

Anyway, I'll write back when I have the change made.

**Comment by jcoliz** [comment]
Ok, please see PR #781.

**Comment by jcoliz** [comment]
Or you might prefer the approach in #782. 😁

**Comment by borisdj** [comment]
Overriding _GetHashCode_ is the cause.
And the issue come from this line:
https://github.com/borisdj/EFCore.BulkExtensions/blob/4e6669aee8bd65e72869e1be3cd3376169344122/EFCore.BulkExtensions/GraphUtil.cs#L54
List is loaded in Dict that uses Hash for identity.
Since this was a PR not sure how to change it even can be.

Also I think that _GetHashCode_ should always return unique value for Object, so maybe consider changing this.
Use just Equals or some custom function for comparing if that is needed.
