### ISSUE TITLE
BulkInsertOrUpdateAsync - Invalid column name Id

### ISSUE THREAD

**Issue by alexandretuee** [borisdj/EFCore.BulkExtensions#783]
When i try to BulkInsertOrUpdateAsync  with my model, it's says : "Invalid column name Id" but it was working properly before updating to version 6.0. 
I tried to exclude the column but still the same error. Here's my model :

```
public class DOC_tbModel
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Key]
        [Required]
        public string IdModel { get; set; }

        [MaxLength(20)]
        [Required]
        public string ModelCode { get; set; }

        public string CodeClient { get; set; }

        [MaxLength(255)]
        [Required]
        public string ModelName { get; set; }

        [Column(TypeName = "xml")]
        [Required]
        public string ModelXmlData { get; set; }

        [Required]
        public int ModelVersion { get; set; }

        [Required]
        public string ModelTypeId { get; set; }
        [Required]
        public string DocTypeId { get; set; }
        public string ModelParentId { get; set; }
        [Required]
        public string ModelStatusId { get; set; }
        public byte[] ModelPreview { get; set; }
        public int? OrderBy { get; set; }

        [Timestamp]
        public byte[] UpdatedAt { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTimeOffset CreatedAt { get; set; }

        [ForeignKey("DocTypeId")]
        public virtual DOC_tbDocType DocType { get; set; }
        [ForeignKey("ModelParentId")]
        public virtual DOC_tbModel ModelParent { get; set; }
    }
```

Take note that the column "Id" here is not the primary key but IdModel is.
I tried to do BulkInsert and BulkUpdate alone and it's only crashing in BulkUpdate..

**Comment by alexandretuee** [comment]
Before i tried to exclude the column Id I had this error
![image](https://user-images.githubusercontent.com/9531605/160624041-cc81ff68-f498-4ca7-b13e-89194194a4f2.png)
but if you look at my model its [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
Its should not try to update it..

**Comment by alexandretuee** [comment]
I ended up to exclude the id on compare and everything is working out...
![image](https://user-images.githubusercontent.com/9531605/160648883-a004560a-4c17-4f07-9fb9-6092d9869356.png)

**Comment by borisdj** [comment]
When having autoGen. ID column that is not PK then it needs to be excluded.
I don't think you need _PropertiesToExcludeOnCompare_, it should be enough just to set _**PropertiesToExclude**_:
```C#
BulkConfig config = new BulkConfig { PropertiesToExclude = new List<string> { "Id" } };
context.BulkInsertOrUpdate(entities2, config);

```
