### ISSUE TITLE
 KeepIdentity "Table does not have the identity property. Cannot perform SET operation"

### ISSUE THREAD

**Issue by ChristopherVR** [borisdj/EFCore.BulkExtensions#786]
I'm running into an issue where we are using HiLo sequences for Entities to generate primary keys beforehand. The problem is this bit of code tries to execute to set the Identity insert to ON:

![image](https://user-images.githubusercontent.com/28136629/161418647-497c07eb-5c40-4354-929f-a8725111d6a3.png)

This results in the error being thrown stated in the title. If I clone the repo and remove this code it resolves the issue.

Here is a few snippets I used to produce this issue:

Create an entity with a HiLo sequence:
![image](https://user-images.githubusercontent.com/28136629/161418735-88274f49-3220-4ff4-a4d7-76b052afee03.png)

![image](https://user-images.githubusercontent.com/28136629/161418763-7f4e34bb-3edc-45c3-a7bd-fed60be5aab2.png)

Insert entities with SqlBulkCopyOptions set to KeepIdentity:
![image](https://user-images.githubusercontent.com/28136629/161418782-6ad3b9ce-9b6c-4efa-be79-fb7f7597c3ab.png)

I believe the solution would be to use the Model MetaData on the DBContext to determine if this entity/entities we are trying to insert contains a HiLo sequence to prevent this code from executing while still preserving the identities.

**Comment by borisdj** [comment]
Fixed with 6.4.3
