### ISSUE TITLE
DbContextBulkTransactionSaveChanges.SaveChangesAsync outputs object not an instance of reference error with Owned entities

### ISSUE THREAD

**Issue by ChristopherVR** [borisdj/EFCore.BulkExtensions#787]
It seems that when using DbContextBulkTransactionSaveChanges.SaveChangesAsync method the code groups changed entities by EntityType using the Change tracker:
![image](https://user-images.githubusercontent.com/28136629/161419488-861f0b41-4337-4e65-86df-fbdb25dab732.png)

![image](https://user-images.githubusercontent.com/28136629/161419397-ddd4d5d9-c1b2-483a-947b-f48b0f3ee800.png)

The problem however is that this will also group OwnedEntities (cases where you have an Entity that owns another entity (ValueObject))) per type and causes an object is not an instance error later on when trying to Find the entity type using the context.Model

![image](https://user-images.githubusercontent.com/28136629/161419467-a796d73f-ebf2-4f0d-a2c1-c1f9bba79e3e.png)

Code snipper to create an entity with an owned entity:
![image](https://user-images.githubusercontent.com/28136629/161419517-bb46ac8b-a42c-4ba8-a20f-713bc07f2bcf.png)

Entity type configuration:
![image](https://user-images.githubusercontent.com/28136629/161419537-8ed4f9f2-bf8c-4c07-83ac-49c1e0308a73.png)

**Comment by borisdj** [comment]
Can you write entire test for this.

**Comment by ChristopherVR** [comment]
@borisdj ,

Here is the code I used for the EF Unit test project to test this issue:

Model:
`    public record InfoOwnedEntity(string Mobile, string AlternateMobile);
    public class Item
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        [MaxLength(50)]
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal? Price { get; set; }
        public DateTime? TimeUpdated { get; set; }
        public InfoOwnedEntity OwnedEntity { get; set; }
    }`

Entity configuration:
`modelBuilder.Entity<Item>().OwnsOne(p => p.OwnedEntity, s => s.WithOwner());`

Unit test:
`        [Fact]
        public async Task EF_OwnedEntityTest_SaveChangesAsync()
        {
            ContextUtil.DbServer = DbServer.SQLServer;
            using var context = new TestContext(ContextUtil.GetOptions());

            var entity = new Item
            {
                OwnedEntity = new("asd", "asdsd"),
                Name = "Name",
                Description = "info",
                Quantity = 100,
                Price = 5,
                TimeUpdated = DateTime.Now,
            };

            context.Items.Add(entity);
            await context.BulkSaveChangesAsync();

            // Validate Test
            int entitiesCount = await context.Items.CountAsync();
            Item firstEntity = await context.Items.SingleOrDefaultAsync(a => a.ItemId == 1);

            Assert.Equal(1, entitiesCount);
            Assert.Equal("asd", firstEntity.OwnedEntity.Mobile);
            Assert.Equal("asdsd", firstEntity.OwnedEntity.AlternateMobile);
        }`
        
       Error being produced:
       
![image](https://user-images.githubusercontent.com/28136629/163813986-85351e09-af3a-42ac-9e66-e4eea69eaf09.png)

**Comment by borisdj** [comment]
Owned in separate table is not directly supported.
DUPE: https://github.com/borisdj/EFCore.BulkExtensions/issues/114
Try workaround explained there.
