### ISSUE TITLE
Expose SqlBulkCopy.ColumnOrderHints property

### ISSUE THREAD

**Issue by altso** [borisdj/EFCore.BulkExtensions#789]
Is there a way to specify `ColumnOrderHints` on underlying `SqlBulkCopy` object?

I noticed that after inserting data with pre-generated ever increasing PK/Clustered Index the index get's fragmented fairly quickly. It seems like there is a way to avoid that by preserving the insertion order on `SqlBulkCopy` via setting the above property, but I cannot find a way of doing that in `EFCore.BulkExtensions`.

**Comment by borisdj** [comment]
Added in 6.4.3

**Comment by altso** [comment]
@borisdj thank you!
