### ISSUE TITLE
Question: Do EFCore.BulkExtensions support postgresql/postgis geometry type?

### ISSUE THREAD

**Issue by swidz** [borisdj/EFCore.BulkExtensions#790]
Hi,
Is PostgreSQL/PostGis geometry type supported?
When I try to bulk insert list of entities containing a geometry property I get the following error:
_A PostgreSQL type with the name geometry (point, 2180) was not found in the database_

Geometry type is defined using NetTopologySuite.
Postgis 3.2 Extension is installed.
There are no issues when adding entities using AddRange and SaveChanges.

Location property is defined as follows:

```
builder.Property(x => x.Location)
                .HasColumnType("geometry (point, 2180)")
                .HasSrid(2180);
```

**Comment by borisdj** [comment]
Support added, new Nuget will be published in a few days.
