### ISSUE TITLE
Iterations of BulkInsert take increasingly longer times to complete

### ISSUE THREAD

**Issue by dcadlereii** [borisdj/EFCore.BulkExtensions#799]
I am using .NET 6 with EFCore.BulkExtensions v6.44. I am working on an archive service that will iterate groups of records in an existing SQL Server database and generate new records from that data that is then bulk inserted into tables in an Azure SQL database. 

I start with a date rage of records, say 3 months worth. The records have a stockItem record which can have up to 10 associated records that represent various scan activity as it processes through a warehouse. In a given quarter, there may be 1M stockitem records with up to 8M scan records. I break this date range into batches of 1000 stockitem records, which would include up to 8,000 scan records and I then bulk insert that batch. Then I grab the next 1,000 stockitem records and process them. This continues until all stockitem records that were created within the specified date range have been processed and then I stop.

This, of course, generates hundreds of batches of a given date range. 

I log the elapsed time of each date range cycle. I can see the time it takes to complete the bulk insert, particularly on the larger quantity scan records, increasing over time.

After each date range is processed. I stop the service so I know there should not be any connection issues or memory for the DBContext issues carried over between iterations. 

For example, 
The first date range of records my take 55 minutes to complete, inserting 291K stockitem records and 1.9M scanevent records.
I stop the service, documents the results, update the date range in the config file and start the service again. 
The next date range would take 72 minutes, inserting 289K stockItem records and 1.9M scanevent records.
The next date range would take about 140 minutes, inserting 354K stockItem records and 2.5M scanevent records.
The next date range would take 256 minutes, inserting 321K stockItem records and 2.5M scanevent records.

This continues to get worse over time.

I have my Azure SQL server at 200 DTU and I can see that I am close to 100% but not exceeding it during the bulk inserts.
I have a BulkConfig with BulkCopyTimeout set to 0 and BatchSize set to 5000

Any ideas as to why this keeps increasing in duration?

**Comment by borisdj** [comment]
Hard to find a solution without working example.
Maybe try larger sets, say 100 000 record per group, then for 8 million rows it would require 80 iterations.
Also make sure that each iteration is independent new Transaction so it is not connected to previous.
And make a custom procedure where you would write Id of last row in a group so if procedure fails and some point, restarting it would continue from last group which coping was not finished.

**Comment by dcadlereii** [comment]
I ended up having to move my work from Azure SQL to a local SQL server and then set the database recovery model to "Bulk-logged" (Azure SQL doesn't have this option). The increasing time for each iteration was due to the log files when recovery model is set to "Full". I also increased the set to 10K. Finally, I disabled all of the indexes until after I complete the bulk loading. The BulkInsert is much faster and consistent now.

**Comment by borisdj** [comment]
Glad you solved it.

**Comment by jorgelaranjo** [comment]
> I am using .NET 6 with EFCore.BulkExtensions v6.44. I am working on an archive service that will iterate groups of records in an existing SQL Server database and generate new records from that data that is then bulk inserted into tables in an Azure SQL database.
> 
> I start with a date rage of records, say 3 months worth. The records have a stockItem record which can have up to 10 associated records that represent various scan activity as it processes through a warehouse. In a given quarter, there may be 1M stockitem records with up to 8M scan records. I break this date range into batches of 1000 stockitem records, which would include up to 8,000 scan records and I then bulk insert that batch. Then I grab the next 1,000 stockitem records and process them. This continues until all stockitem records that were created within the specified date range have been processed and then I stop.
> 
> This, of course, generates hundreds of batches of a given date range.
> 
> I log the elapsed time of each date range cycle. I can see the time it takes to complete the bulk insert, particularly on the larger quantity scan records, increasing over time.
> 
> After each date range is processed. I stop the service so I know there should not be any connection issues or memory for the DBContext issues carried over between iterations.
> 
> For example, The first date range of records my take 55 minutes to complete, inserting 291K stockitem records and 1.9M scanevent records. I stop the service, documents the results, update the date range in the config file and start the service again. The next date range would take 72 minutes, inserting 289K stockItem records and 1.9M scanevent records. The next date range would take about 140 minutes, inserting 354K stockItem records and 2.5M scanevent records. The next date range would take 256 minutes, inserting 321K stockItem records and 2.5M scanevent records.
> 
> This continues to get worse over time.
> 
> I have my Azure SQL server at 200 DTU and I can see that I am close to 100% but not exceeding it during the bulk inserts. I have a BulkConfig with BulkCopyTimeout set to 0 and BatchSize set to 5000
> 
> Any ideas as to why this keeps increasing in duration?

Isn't the culprit the constraint + index that needs to be created and then disposed of?
You could check the DB performance and debug it to confirm or just create that constraint + index before hand. It should then stop that increasing time to insert and become more linear.
