### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by ChristopherVR** [borisdj/EFCore.BulkExtensions#800]
I am following a Domain Driven design approach for our systems' projects and this is causing issues when trying to use the HiLo extension method when including EFCore.BulkExtensions.

Here is the list of packages I am using:
![image](https://user-images.githubusercontent.com/28136629/163958995-9450a563-7321-47e6-b0e8-da7fcee0fd4d.png)

This is the error being thrown when trying to use the UseHilo extension method:
![image](https://user-images.githubusercontent.com/28136629/163959068-a440bd4b-7ee0-48b1-9e1f-bfc970777d9e.png)

I believe one of the packages being used in the EFCore.BulkExtensions library is causing this ambiguous issue. Removing all the packages I am using and only including EFCore.BulkExtensions does not resolve this issue.

**Comment by borisdj** [comment]
DUPE https://github.com/borisdj/EFCore.BulkExtensions/issues/228

**Comment by borisdj** [comment]
Call it explicitly:
```C#
SqlServerPropertyBuilderExtensions.UseHiLo(modelBuilder.Entity<SequentialInfo>().Property(r => r.Id), name: "Seq", schema: "");
```
