### ISSUE TITLE
Cannot insert duplicate key row in object

### ISSUE THREAD

**Issue by rdkleine** [borisdj/EFCore.BulkExtensions#801]
Hi,

I'm trying to bulk insert/update records using the `BulkInsertOrUpdateAsync` method and I'm getting a 'Cannot insert duplicate key row in object' error. 

The CowDbEntity has a PK on Id. Unique index on ShipToId, InternationalCowId and Date. (IX_cows_ShipToId_InternationalCowId_Date)
   ```
 public class CowDbEntity
    {
        public int Id { get; set; }
        public int ShipToId { get; set; }
        public string Json { get; set; }
        public string InternationalCowId { get; set; }
        public DateTime Date { get; set; }
        public Species Species { get; set; }
        public decimal AgeInYears { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset Updated { get; set; }
    }
```

BulkConfig:
```
new EFCore.BulkExtensions.BulkConfig
{
    UpdateByProperties = new List<string>
    {
        nameof(CowDbEntity.ShipToId),
        nameof(CowDbEntity.InternationalCowId),
        nameof(CowDbEntity.Date)
    },
}
```

When running a batch which has entities needed to update instead of insert I'm getting the exception:
"Cannot insert duplicate key row in object 'cow.cows' with unique index 'IX_cows_ShipToId_InternationalCowId_Date'. The duplicate key value is (19318, DE0359391104, Apr 12 2022 12:00AM).\nThe statement has been terminated."

I've added a profiler and seeing this Merge query:
`MERGE [cow].[cows] WITH (HOLDLOCK) AS T USING (SELECT TOP 153 * FROM [cow].[cowsTemp211bbf1b] ) AS S ON 1=0 WHEN NOT MATCHED BY TARGET THEN INSERT ([Created], [Json], [Species], [Updated]) VALUES (S.[Created], S.[Json], S.[Species], S.[Updated]) WHEN MATCHED AND EXISTS (SELECT S.[Created], S.[Json], S.[Species], S.[Updated] EXCEPT SELECT T.[Created], T.[Json], T.[Species], T.[Updated]) THEN UPDATE SET T.[Created] = S.[Created], T.[Json] = S.[Json], T.[Species] = S.[Species], T.[Updated] = S.[Updated];`

I am a bit confused by the 1=0 because it means there wont be any matches and always run a Insert on the table? Maybe I'm missing something obvious?

**Comment by borisdj** [comment]
Regarding `1=0`, _it removes Identity constrain_, there is a comment in the code:
https://github.com/borisdj/EFCore.BulkExtensions/blob/904a4f6cd310b9545b7cc64ff64f9def4917db18/EFCore.BulkExtensions/SqlQueryBuilder.cs#L24

**Comment by rdkleine** [comment]
We we're using computed columns for the ShipToId, InternationalId and Date field. After changing them to regular columns the update works as expected:

```
MERGE [cow].[cows] WITH (HOLDLOCK) AS T USING (SELECT TOP 153 * FROM [cow].[cowsTemp7e9227e7] 
ORDER BY [ShipToId], [InternationalCowId], [Date]) AS S ON T.[ShipToId] = S.[ShipToId] AND T.[InternationalCowId] = S.[InternationalCowId] AND T.[Date] = S.[Date] 
WHEN NOT MATCHED BY TARGET THEN INSERT ([ShipToId], [InternationalCowId], [Date], [Json], [Species], [Updated]) VALUES (S.[ShipToId], S.[InternationalCowId], S.[Date], S.[Json], S.[Species], S.[Updated]) 
WHEN MATCHED AND EXISTS (SELECT S.[ShipToId], S.[InternationalCowId], S.[Date], S.[Json], S.[Species], S.[Updated] EXCEPT SELECT T.[ShipToId], T.[InternationalCowId], T.[Date], T.[Json], T.[Species], T.[Updated]) 
THEN UPDATE SET T.[Json] = S.[Json], T.[Species] = S.[Species], T.[Updated] = S.[Updated];
```
