### ISSUE TITLE
BulkInsertAsync throwing System.ObjectDisposedException: Cannot access a disposed object

### ISSUE THREAD

**Issue by subhadranair** [borisdj/EFCore.BulkExtensions#804]
Hi Boris,

Thank you for an amazing way to handle large volumes of data. 

Recently we had migrated our project from .Net 5.0 to .Net 6.0 and we used EFCore.BulkEntensions - BulkInsertAsync method to insert 8k data to SQL database. In the localhost/localmachine it runs absolutely fine without any issue. But while the code is deployed to Azure pipeline I encounter this exception while remote debugging

_System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances._

I am using UnitOfWork to handle transactions and no other method is encountering this issue other than the BulkInsert. 
![image](https://user-images.githubusercontent.com/90210451/164754738-51c55bc9-f0af-49d8-87a5-e3ac4168265b.png)

Is there a way to identify if the process is completed as this returns null.

**Comment by borisdj** [comment]
Not sure.
Maybe try encapsulating bulk operation into a transaction.
