### ISSUE TITLE
Does BulkExtensions honor EF ExecutionStrategy?

### ISSUE THREAD

**Issue by Relki** [borisdj/EFCore.BulkExtensions#805]
We're looking to start using EF Execution Strategy and we use this extension for a few locations and we didn't know if Bulk Extensions honors EF ExecutionStrategy. Anyone know for sure?

**Comment by borisdj** [comment]
Not sure what specific use case you have.
Anyhow multiple Bulk ops can be encapsulated into a transaction scope where should it behave like regular operations.
For example it one bulk operation fails in should rollback previous ones in the same transaction.

**Comment by Relki** [comment]
In our use case, we will be using EF Execution Strategy with it's default implementation of retrying known azure sql transient issues that are retriable as well as 1 custom sql exception that'd like to be retried. This all happens on the context level supported by EF and since we use this same context with BulkExtensions, we didn't know if there was any underlying behavior changing of the way execution strategy is honored.

**Comment by borisdj** [comment]
Don't know of any special changes.
It is simply using SqlBulkCopy.

**Comment by Tyler-V** [comment]
@borisdj if the library is using BeginTransaction as part of SqlBulkCopy then it would need to be wrapped with strategy.Execute(() => ...) to support it

https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency#execution-strategies-and-transactions
