### ISSUE TITLE
BulkInsert Foreign Key Issue

### ISSUE THREAD

**Issue by PosSystemSrl** [borisdj/EFCore.BulkExtensions#810]
Hello,

Using EF.Core.BulkExtensions 2.5.0 - SQL Server 2017 (cannot update .NET Core version in this project), I'm not able to assign the right foreign keys in third level (propagation detail barcode). Seems that primary keys of the second level (details) returned do not match with the ones in Database when the transaction is committed. What's wrong with my code implementation? 

```
var PropagationId = 0;
foreach(var propagationModel in propagationModelList)
{
	propagationModel.PropagationId = --PropagationId;
}

_propagationService.PropagationBulkInsert(propagationModelList);

var PropagationDetailId = 0;
foreach (var propagationModel in propagationModelList)
{                                                    
	foreach (var propagationDetail in propagationModel.PropagationDetailModelList)
	{
		propagationDetail.PropagationDetailId = --PropagationDetailId;
		propagationDetail.PropagationId = propagationModel.PropagationId;
	}

	propagationDetailModelList.AddRange(propagationModel.PropagationDetailModelList);
}

_propagationDetailService.PropagationDetailBulkInsert(propagationDetailModelList);


foreach (var propagationDetail in propagationDetailModelList)
{
	foreach (var propagationDetailBarcode in propagationDetail.PropagationDetailBarcodeModelList)
	{
		propagationDetailBarcode.PropagationDetailId = propagationDetail.PropagationDetailId;
	}
	propagationDetailBarcodeModelList.AddRange(propagationDetail.PropagationDetailBarcodeModelList);
}

if (propagationDetailBarcodeModelList.Any())
{
	_propagationDetailBarcodeService.PropagationDetailBarcodeBulkInsert(propagationDetailBarcodeModelList);
}
```

BulkInsert are defined as follow:
`_context.BulkInsert(entityList, new BulkConfig { SetOutputIdentity = true, PreserveInsertOrder = true });`

**Comment by borisdj** [comment]
Your initial order seems reversed, going from -1 to -n.
Try from -n to -1 :
```C#
counter = -list.Count();
foreach(...)
{
  propagationModel.PropagationId = counter--;
  ...
}
```

**Comment by PosSystemSrl** [comment]
> ```cs
> counter = -list.Count();
> foreach(...)
> {
>   propagationModel.PropagationId = counter--;
>   ...
> }
> ```

Since counter = -list.Count(), shouldn't it be propagationModel.PropagationId = counter++ or am I missing something?

**Comment by PosSystemSrl** [comment]
> yes, it's ++

Seems working (I have to check properly because I'm working on a big amount of records). 
Could you please explain me the reason behind it? I'm not getting the point, I mean, what's the difference?

Furthermore, before this I have tried to not set the Ids but it wasn't working. Is it correct?

(Anyway, I'll mark as closed as soon as I tested it properly)

Thanks a lot

**Comment by borisdj** [comment]
Glad you solved it.
Updating ID in memory is done based on position in list, so order needs to be keep.
Newer version can set these negative value automatically when _PreserveInsertOrder_ is configured, there a note in ReadMe:

> PreserveInsertOrder is true by default and makes sure that entites are inserted to Db as ordered in entitiesList.
> When table has Identity column (int autoincrement) with 0 values in list they will temporary be automatically changed from 0s into range -N:-1.
> Or it can be manually set with proper values for order (Negative values used to skip conflict with existing ones in Db).

But in older version you have to do it manually.

What might also work (without manual ID set) for your use case, if you do not need exact order in DB as in in the list:
To leave IDs with zeros 0 and call Bulk operation with:
`SetOutputIdentity = true, PreserveInsertOrder = false`
In this combination entire list would be reloaded, possible with different order, but itereting them would set FKs correctly.
ReadMe:

> SetOutputIdentity is useful when BulkInsert is done to multiple related tables, that have Identity column.
> ...
> When used Id-s will be updated in entitiesList, and if PreserveInsertOrder is set to false then entitiesList will be cleared and reloaded.
