### ISSUE TITLE
using bulkextensions optimally with IN clause (large list)

### ISSUE THREAD

**Issue by mkgn** [borisdj/EFCore.BulkExtensions#811]
I have a XL which has a large set of data. Let's assume it has only one column. In that dataset, there can be two types of data.

1) Data that already exists in the database
2) New data

First, I need to get the new data (that is not in the database) and add it to a separate table. 
Secondly, update the already existing data with any changes (this I have done already using this extension).

My issue is when trying to do the first step, I need to do a query like;

    select email from database_user_table where email not in (email list from XL)

Since the data passed to IN clause can be quite large, the best is to do the above query using a temp table. But I am not sure how can I explicitly use a temp table using this extension.

What are my options here?

**Comment by borisdj** [comment]
Use BulkRead and if matching is not by PK then configure custom unique col. in UpdateByProps.
After Reading you can separate new ones and add them in that separate table.
Then call BulkIUpdate with existing ones or if you new new ones in main table call BulkIInsertOrUpdate with entire list.

**Comment by mkgn** [comment]
My tried bulk read and got stuck. According to the documentation;

    BulkRead does SELECT and JOIN based on one or more Unique columns that are specified in Config UpdateByProperties.

As I understand this needs a unique column in the table to do the job. If that is the case I am kinda stuck.

Reason is I want to do a bulk read in AspNetUsers table (I am using .Net Identity framework for authentication). The problem is I need to match the Email column which is not marked as unique in the table itself (The framework supports duplicate emails, but in my application I don't allow that).

So does this mean my options are to create a unique index in Email column before I do the bulk read? The other issue is that the table has a CountryId, StateId foreign keys and it threw an exception telling me that it expects a value for these?

**Comment by borisdj** [comment]
It does not need to have Unique Index, just unique values, otherwise it throws exception.
As you said you don't have double mails it should work fine.
