### ISSUE TITLE
Why does not support virtual properties?

### ISSUE THREAD

**Issue by leehom0123** [borisdj/EFCore.BulkExtensions#82]
In SqlBulkOperation.cs, GetDataTable method,
`
 var properties = type.GetProperties().Where(a => !a.GetGetMethod().IsVirtual);   
`
Why the properties can't set virtual?

and recommend change set ownedEntityType value like this:
`
                    if (ownedEntityType == null) // when single entity has more then one ownedType of same type (e.g. Address HomeAddress, Address WorkAddress)
                    {
                        ownedEntityType = context.Model.GetEntityTypes().SingleOrDefault(a => a.DefiningNavigationName == property.Name && a.DefiningEntityType.Name == entityType.Name);
                    }
`

**Comment by borisdj** [comment]
I have assumed convention that virtual Properties are Navigation Props. so they are not columns.
Do you have a real case situation where you need virtual keyword on a basic Property that is a column, and could you elaborate it?

**Comment by leehom0123** [comment]
Assume I have a base class A, and class B extened A, and override some property.

I create some pull requests, fixed the code does not support owned entity property insert and update, pls review it.

**Comment by leehom0123** [comment]
Assume I have a base class A, and class B extened A, and override some property.

I create some pull requests, fixed the code does not support owned entity property insert and update, pls review it.

**Comment by borisdj** [comment]
Pull Merged.
