### ISSUE TITLE
Specialized Packages ?

### ISSUE THREAD

**Issue by Jerome-Liger** [borisdj/EFCore.BulkExtensions#828]
Hello, and thanks for this great library, years of use...
This is not a real issue, but it's more an architecture thinking for this NugetPackages... (that currently generates incompatibility/bad dependencies).

EFCore.BulkExtension is really great and I'm used to implement it on many of my Xamarin.Forms projects (with EFCore Sqlite 5.0.16, as the EFCore Sqlite 6.x will be for targeting .Net6/MAUI, not ready for production world yet).

But I have a lot of nuget incompatibility, due to EFCore.BulkExtensions dependencies :
When I add this package to my Xamarin.Forms .NetStandard (2.1) Library, it forces a dependency to "Microsoft.Data.SqlClient" (and others, but this particulary makes error later...)
As my XamarinForms Library is referenced in my Xamarin.Android native project, it load the dependencies tree on Android too...

And I encounter build errors (not warning -> unable to compile as it is) :
Microsoft.Data.SqlClient on Android Project need "Microsoft.Identity.Client"... (and SQLClient is loaded due to BulkExtensions dependencies)

But I don't want to reference (and configure) Microsoft.Identity.Client on Android.
And I don't need any reference to Microsoft.Data.SqlClient on a smartphone !!! (and it's useless, as I target EFCore.Sqlite)

So my question is : what do you think about creating "specialized-lightweight-lowDependencies" packages for BulkExtension ?
Kind of :
- EFCore.BulkExtensions.Sqlite
- EFCore.BulkExtensions.SqlServer
- (EFCore.BulkExtensions.PostgreSQL)
- ...

I'm even thinking why is there dependencies to DB Engines here (I suppose you need technically to have it, even if I don't see why...)
Is that really impossible to have dependency only on EF framework level ? (Core + Relationnal, without DB-Engines dependencies)

It would be really great for "developper that implement real-world applications" to avoid a headache when managing dependencies...
A third-party package is always better when his dependencies are minimal...

I don't know if I've been clear (sorry, I'm French ;-)), but do not hesitate to get back to me, I'm here to explain/discuss/debate if needed.

Thanks
Jérôme

**Comment by borisdj** [comment]
DUPE https://github.com/borisdj/EFCore.BulkExtensions/issues/669
Dependencies are required but separate packages with only those needed could be created.
It is in plan but requires larger refactoring so still no time frame.

**Comment by Jerome-Liger** [comment]
For those who are interested, I've forked and created a lightweight-low-dependency package special for Sqlite :
https://www.nuget.org/packages/EFCore.BulkExtensions.Sqlite/5.0.17

No more problems anymore with this package on Xamarin.Forms(Android) application (cause Microsoft.Data.SqlClient and Microsoft.Identity.Client)... compilation without error or warnings.

Thanks @borisdj for your great work, code is well structured and easy to read/modify... a real pleasure :-)

**Comment by borisdj** [comment]
@Jerome-Liger with latest version there are specialized packages but I'm not able to publish Nuget: EFCore.BulkExtensions.SQLite because of conflict with your nuget.
Is there a way to revoke a Nuget, and if so would you be willing to do that, in order to keep the naming consistent.
You could republish your under a slightly different name.
Otherwise I would have to make an exception from naming convention for this one.
Thx.

**Comment by Jerome-Liger** [comment]
Hi Boris and thanks for this great dependencies ehancement 👍 

Sorry, I didn't notice that I can't delete a package or rename it's Identifier... so I was too quick with my own "consistent naming" by "stealing" your EFCore.BulkExtension.Sqlite identifier... Next time I will fork/publish nugets, I'll try to avoid this naming conflicts... ;-)

I just give you the ownership from Nuget... it's yours now !
Once you've accepted the ownership, just delete me as the co-owner, no problem.

**Comment by borisdj** [comment]
No problem, when you published it I didn't even had this per provider naming convention.
Thx for the transfer, all the best.

**Comment by sommmen** [comment]
> New Structure (as of verion 6.6.0):
> 
> Num	Project	References	NuGet
> [0]	EFCore.BulkExtensionsCore		-
> [1]	EFCore.BulkExtensions.SqlServer	[0]	EFCore.BulkExtensions.SqlServer
> [2]	EFCore.BulkExtensions.PostgreSql	[0]	EFCore.BulkExtensions.PostgreSql
> [3]	EFCore.BulkExtensions.MySql	[0]	EFCore.BulkExtensions.MySql
> [4]	EFCore.BulkExtensions.SQLite	[0]	EFCore.BulkExtensions.SQLite
> [5]	EFCore.BulkExtensions.Common	[1,2,3,4]	EFCore.BulkExtensions
> [0] | _EFCore.BulkExtensions_ is shared core project that has no Nuget. Instead project [5] _EFCore.BulkExtensions.Common_ references all other projects thereby includes all providers and it has NuGet with base name: **EFCore.BulkExtensions** to keep full compatibility with previous versions.

@borisdj  hiya, quick question - i just changed my package import to EFCore.BulkExtensions.SqlServer 6.6.1 - but i'm getting this error:

```
Restoring packages for [REDACTED]\DAL.csproj...
  GET https://api.nuget.org/v3-flatcontainer/efcore.bulkextensionscore/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/efcore.bulkextensionscore/index.json 108ms
NU1101: Unable to find package EFCore.BulkExtensionsCore. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org
Package restore failed. Rolling back package changes for 'DAL'.
```

**Comment by borisdj** [comment]
v6.6.2
