### ISSUE TITLE
SQL SERVER XML column BulkInsertOrUpdateAsync broken at some point between  v2.6.3 && v6.5.0?

### ISSUE THREAD

**Issue by GuiraoR** [borisdj/EFCore.BulkExtensions#831]
Hi guys, 

Just upgraded recently all my projects to EF 6.0 and as part of that upgrade I bumped up the version of this package which now it turns out is breaking the same code that was working on old versions on this specific function:

context.BulkInsertOrUpdateAsync(list of objects), .... )

System.Private.CoreLib: Exception while executing function: whatever. Core Microsoft SqlClient Data Provider: The data type xml cannot be used as an operand to the UNION, INTERSECT or EXCEPT operators because it is not comparable.

I guess the current implementation of v6.5.0 on that function (and others?) is using behind the scenes some of those SQL operators which are not allowed for an XML column. Any ideas on how I could solve this breaking issue? is there in the radar a patch coming soon for XML columns ? 

Thanks a lot in advance for your comments/thoughts.

**Comment by borisdj** [comment]
There is config OmitClauseExistsExcept, 
more info in the ReadMe.
