### ISSUE TITLE
ArgumentException: Unable to determine Type

### ISSUE THREAD

**Issue by marekbomber** [borisdj/EFCore.BulkExtensions#834]
Given the following code:

**Entity from Assembly 1:**

```
public class ExampleEntity
{
    public long Id { get; set; }
    public string Name { get; set; }
    public AuditField Field { get; set; } // from external assembly (Assembly 2)
}
```
**Example:**

```
await query.BulkUpdateAsync(
    new ExampleEntity
    {
        Name= "Test"
    }
});
```
**The exception occurs:**
`ArgumentException: Unable to determine Type`
Problem is https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/TableInfo.cs#L501 when property is other assembly.

**Solution**
Variable `navOwnedType `is never used, remove it?
Type `navOwnedType `should be `navigationProperty.ClrType` ClrType will never be null.

**Comment by borisdj** [comment]
Removed, will be published with next v.

**Comment by marekbomber** [comment]
Thanks.

The same case is in https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs#L552 please remove
