### ISSUE TITLE
Postgresql BulkRead\BulkReadAsync usage of information_schema

### ISSUE THREAD

**Issue by ruslanfedoseenko** [borisdj/EFCore.BulkExtensions#835]
In Postgresql information_schema is available only in default database - postgres.
This library use information_schema for detecting primary key and unique constraints during BulkRead\BulkReadAsync operations.

If you create another db and connect with user who does not have access permissions for postgres database and information_schema schema you will face with error like 'information_schema.table_constraints' not found. 

The right place to get info you getting in https://github.com/borisdj/EFCore.BulkExtensions/blob/master/EFCore.BulkExtensions/SQLAdapters/PostgreSql/SqlQueryBuilderPostgreSql.cs#L193 is schema pg_catalog

And query would be 
```
SELECT COUNT(*)
      FROM pg_catalog.pg_namespace nr,
           pg_catalog.pg_class r,
           pg_catalog.pg_attribute a,
           pg_catalog.pg_namespace nc,
           pg_catalog.pg_constraint c
      WHERE nr.oid = r.relnamespace
        AND r.oid = a.attrelid
        AND nc.oid = c.connamespace
        AND r.oid =
            CASE c.contype
                WHEN 'f'::""char"" THEN c.confrelid
            ELSE c.conrelid
                END
            AND (a.attnum = ANY (
                CASE c.contype
            WHEN 'f'::""char"" THEN c.confkey
                ELSE c.conkey
                END))
            AND NOT a.attisdropped
            AND (c.contype = ANY (ARRAY ['p'::""char"", 'u'::""char""]))
            AND (r.relkind = ANY (ARRAY ['r'::""char"", 'p'::""char""]))"+
         $" AND r.relname = '{tableInfo.TableName}' AND a.attname IN ('{string.Join("','", primaryKeysColumns)}')"
```

I could create PR for this if you need.

**Comment by borisdj** [comment]
If you can make a PR that would be fine.

**Comment by borisdj** [comment]
Fix integrated.
