### ISSUE TITLE
BulkInsertOrUpdateAsync EF6 with temporal table fails

### ISSUE THREAD

**Issue by kkolo-ss** [borisdj/EFCore.BulkExtensions#837]
I'm using BulkInsertOrUpdateAsync on a table with 4 FK and enabled temporal tables

config property SetOutputIdentity seems to cause my problems
I need it to set it to true but if its true then method fails with such error:
**"Microsoft.Data.SqlClient.SqlException: 'Invalid column name 'PeriodEnd'.Invalid column name 'PeriodStart'.'"**
at line 1078 in EFCore.BulkExtensions.TableInfo.LoadOutputDataAsync

If i set SetOutputIdentity to false then bulkinsertorupdate works without any errors.

my configuration

config.PreserveInsertOrder = false;
config.UpdateByProperties = new List<string>()
{
prop1,
prop2,
prop3,
prop4
};
config.SetOutputIdentity = true;
config.PropertiesToInclude = new List<string>()
{
prop5
};
config.UseTempDB = true;

Table is just a standard table with 4FK and turn on versioning so
2 columns added as
[PeriodStart]               DATETIME2      GENERATED ALWAYS AS ROW START HIDDEN NOT NULL DEFAULT SYSUTCDATETIME(),
[PeriodEnd]                 DATETIME2      GENERATED ALWAYS AS ROW END HIDDEN NOT NULL DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),

PERIOD FOR SYSTEM_TIME ([PeriodStart], [PeriodEnd])
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = <table>))

Could you help me?

**Comment by rlzicar** [comment]
I was facing the same issue. As a temporary nasty hack to work around this, I added this piece of code at the beginning of the MergeAsync() method in SqlServerAdapter:
```
if (tableInfo.HasTemporalColumns)
{
    tableInfo.OutputPropertyColumnNamesDict["PeriodStart"] = "PeriodStart";
    tableInfo.OutputPropertyColumnNamesDict["PeriodEnd"] = "PeriodEnd";
}
```

...and this code in TableInfo.LoadOutputDataAsync() right before `UpdateEntitiesIdentity(tableInfo, entities, entitiesWithOutputIdentity);`

```
if (tableInfo.HasTemporalColumns)
{
    tableInfo.OutputPropertyColumnNamesDict.Remove("PeriodStart");
    tableInfo.OutputPropertyColumnNamesDict.Remove("PeriodEnd");
}
```
This seems to have fixed the problem at least for my use case.

**Comment by kkolo-ss** [comment]
I just removed package and started using stored procedure with **upsert 'pattern'**

**Comment by borisdj** [comment]
I'm not able to reproduce the issue.
I have altered test _TemporalTableTest_:
https://github.com/borisdj/EFCore.BulkExtensions/blob/5593d1d739a0ce80aa61a516cdf36f10fe65bcb9/EFCore.BulkExtensions.Tests/EFCoreBulkTestAtypical.cs#L52-L71
by replacing:
`context.BulkInsert(entities);`
with:
```C#
var bulkConfig = new BulkConfig() {
	PreserveInsertOrder = false,
	SetOutputIdentity = true,
	UseTempDB = true,
	UpdateByProperties = new List<string>() { "StorageId" },
	PropertiesToInclude = new List<string>() { "Data" },
};
using var transaction = context.Database.BeginTransaction();
context.BulkInsertOrUpdate(entities, bulkConfig);
transaction.Commit();
```
and it still passes.

**Comment by samoruk** [comment]
It does happen when you have INT Identity PK:
`public int StorageId { get; set; }`
and
` SetOutputIdentity = true`

**Comment by GOATS2K** [comment]
I can also reproduce this issue.

**Comment by SethVanderZanden** [comment]
I can also reproduce this issue, I had to turn off OutputIdentity and it was on an INT PK as well.
