### ISSUE TITLE
Performance degradation on Azure 

### ISSUE THREAD

**Issue by Tyler-V** [borisdj/EFCore.BulkExtensions#838]
Hi, @borisdj having trouble determining if this is something I introduced or not related to upgrading the project to EF6 / .NET6 or something else completely - any help would be greatly appreciated!

On Azure, we have a large SQL Elastic Pool (GeneralPurpose: Gen5, 8 vCores)

When I run the project locally pointing to the databases on that elastic pool (or when functions are running on Azure), I notice a significant performance degradation than previous to this upgrade where saving ~200k records takes 68 seconds. I am the only traffic interacting with the database during these tests, the database utilization is very low.

`[2022-05-27T16:25:33.870Z] File-Upload: Saved 100000 DataRecords, 100000 CaptureRequests, 20 CaptureResponses in 00:01:08.4466073`

When I run the project locally pointing at my local database, saving ~200k records takes the advertised 7 seconds.

`[2022-05-27T16:33:17.751Z] File-Upload: Saved 100000 DataRecords, 100000 CaptureRequests, 20 CaptureResponses in 00:00:07.3060584`

Packages,
```
    <PackageReference Include="BlazarTech.QueryableValues.SqlServer" Version="6.3.0" />
    <PackageReference Include="EFCore.BulkExtensions" Version="6.5.0" />
    <PackageReference Include="EntityFrameworkCore.Exceptions.SqlServer" Version="6.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.5">
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.5">
```

Startup,
```
            builder.Services.AddDbContext<FileCaptureContext>(options =>
                options.UseSqlServer(appSettings.ConnectionStrings.FileCapture,
                    sqlServerOptionsBuilder => { sqlServerOptionsBuilder.UseQueryableValues(); }), ServiceLifetime.Transient);
```

Executing service,
```
    public class DataRecordService : IDataRecordService
    {
        private readonly FileCaptureContext _fileCaptureContext;
        private readonly IBulkService<FileCaptureContext> _bulkService;

        public DataRecordService(FileCaptureContext fileCaptureContext)
        {
            _fileCaptureContext = fileCaptureContext;
            _bulkService = new BulkService<FileCaptureContext>(fileCaptureContext);
        }

        public async Task<List<DataRecord>> BulkInsertAsync(List<DataRecord> dataRecords)
        {
            var bulkConfig = new BulkConfig
            {
                SetOutputIdentity = true,
                WithHoldlock = false
            };

            var captureRequests = dataRecords.Select(dr => dr.CaptureRequest).ToList();
            await _bulkService.BulkInsertAsync(captureRequests, bulkConfig);

            var captureResponses = new List<CaptureResponse>();
            foreach (var captureRequest in captureRequests)
            {
                foreach (var captureResponse in captureRequest.CaptureResponses)
                {
                    captureResponse.CaptureRequestId = captureRequest.Id;
                    captureResponses.Add(captureResponse);
                }
            }
            await _bulkService.BulkInsertAsync(captureResponses, bulkConfig);

            foreach (var dataRecord in dataRecords)
            {
                dataRecord.CaptureRequestId = dataRecord.CaptureRequest.Id;
            }
            await _bulkService.BulkInsertAsync(dataRecords, bulkConfig);

            return dataRecords;
        }
    }
```

Bulk service,
```
    public class BulkService<TContext> : IBulkService<TContext> where TContext : BaseContext
    {
        private readonly BaseContext _context;

        public BulkService(TContext context)
        {
            _context = context;
        }

        public async Task BulkInsertAsync<T>(IList<T> entities, BulkConfig bulkConfig, Action<decimal> progress = null) where T : class
        {
            foreach (var entity in entities)
            {
                if (!(entity is BaseEntity baseEntity))
                {
                    continue;
                }

                var time = DateTimeExtensions.Now();
                baseEntity.DateCreated = time;
                baseEntity.DateModified = time;
                baseEntity.CreatedBy = "SYSTEM";
                baseEntity.UpdatedBy = "SYSTEM";
            }

            await _context.BulkInsertAsync(entities, bulkConfig);
        }
    }
```

Executing code,
```
            var sw = new Stopwatch();
            sw.Start();
            await _dataRecordService.BulkInsertAsync(dataRecords);
            sw.Stop();
            _log.LogInformation(
                $"Saved {dataRecords.Count} DataRecords, {dataRecords.Select(dr => dr.CaptureRequest).Count()} CaptureRequests, {dataRecords.SelectMany(dr => dr.CaptureRequest.CaptureResponses).Count()} CaptureResponses in {sw.Elapsed}");
```

Local connection string,
`Server=localhost; Initial Catalog=FileCapture; Integrated Security=SSPI; Persist Security Info=False; Trusted_Connection=True; TrustServerCertificate=True`

Azure connection string,
`Server=tcp:xxx.database.windows.net,1433; Initial Catalog=FileCapture; Persist Security Info=False; User ID=xxx; Password=xxx; MultipleActiveResultSets=False; Encrypt=True; TrustServerCertificate=False;`

**Comment by borisdj** [comment]
Not sure...
With what version did it works fast?
And could you tried version in betwean to find excetely one where slowing occurs.

**Comment by Tyler-V** [comment]
Adding some more context,

I tried business critical tier, elastic pools and serverless options and the only difference I can note is..

Using a General Purpose 2 vCore server I can insert 200k records in about ~120 seconds

Scaling to a General Purpose 10 vCore server I can insert 200k records in about ~50 seconds

I will continue to diagnose and see if making these calls on Azure from the same data center / region gets more desirable results but I'm a little bummed about the timings I am seeing

**Comment by Tyler-V** [comment]
@borisdj I did some additional testing on Azure and regardless of my Bulk settings and database allocation I am not able to see bulk inserts of 100k records under ~49 seconds.

I am using 
- Function Apps (~4)
- EntityFrameworkCore 6.0.6
- BulkExtensions 6.5.1

I have tried,
- BatchSize of 500 to 10,000
- WithHoldlock set to false and default (true)
- SqlBulkCopyOptions = SqlBulkCopyOptions.TableLock and default

Do you have any recommendations of where else to look or do you think a bulk insert on an empty table of 100k records in 49 seconds is appropriate - to me this seems like there is something wrong, thanks!

**Comment by borisdj** [comment]
It should be faster, but I haven't used it on Azure so can't say from experience.
Take a look at this issue https://github.com/borisdj/EFCore.BulkExtensions/issues/799

**Comment by borisdj** [comment]
@dcadlereii what is your avegare time for 100K Insert on Azure ?

**Comment by Tyler-V** [comment]
Any help or insight would be greatly beneficial @dcadlereii @borisdj - I'm at my witts ends with this issue and while it "works" it seems like we're leaving a lot of performance on the table here in our application

**Comment by jorgelaranjo** [comment]
@Tyler-V was this ever fixed? I am at odds with Posgresql lagging up to 100+ seconds for 250K records, which shouldn't take that much time.

**Comment by Tyler-V** [comment]
> @Tyler-V was this ever fixed? I am at odds with Posgresql lagging up to 100+ seconds for 250K records, which shouldn't take that much time.

Our solution was to not use bulk save changes.

We are using Durable Functions so instead of using one function to insert 200k records in bulk, we swapped it to execute N activities through fan-in / fan-out to process and save 10k records at a time using regular old AddRangeAsync + SaveChangesAsync and it's 20x faster
