### ISSUE TITLE
BulkReadAsync and Global Filters

### ISSUE THREAD

**Issue by oresttkachukd** [borisdj/EFCore.BulkExtensions#841]
Hi there!

In documentation it mentions that the library supports Global filters - https://docs.microsoft.com/en-us/ef/core/querying/filters

In EF it's possible to have use IgnoreQueryFilters to disable it for specific executions - https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.entityframeworkqueryableextensions.ignorequeryfilters?view=efcore-6.0

Is it possible to Ignore Global Query Filters in any version of BulkExtensions, currently they are applied to every bulk read? Maybe it would be possible to add such an option for BulkConfig?

**Comment by borisdj** [comment]
It can be added, will see to make it with next nuget version.

**Comment by borisdj** [comment]
Added config _IgnoreGlobalQueryFilters_
