### ISSUE TITLE
AOT compiling error on Xamarin IOS with .netstandard 2.0

### ISSUE THREAD

**Issue by AHComp** [borisdj/EFCore.BulkExtensions#842]
If you compile the current Version 6.0.0
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35998144/172141830-f4835df5-15bd-4c13-acd4-b996c9100d13.png)

It includes a dll which is not possible to AOT !

**Comment by borisdj** [comment]
What DB are you using, Sqlite ?
And do you know which dependency exactly is causing the problem?
It could be PostgreSql adapter.
I had planed to make separate packages per Db type.

**Comment by AHComp** [comment]
I don't  know which dependency caused the error.
I have a xamarin forms project with pcl.
Only the ios part not compiling with the nuget included.
I use the entityframework.sqlite provider.
In uwp and android I have no compiling error.
