### ISSUE TITLE
From version 3.4.4 SqlBulkCopyOptions.KeepNulls stopped working

### ISSUE THREAD

**Issue by lisabonde** [borisdj/EFCore.BulkExtensions#843]
Last working version for SqlBulkCopyOptions.KeepNulls  was 3.4.3. From version 3.4.4 this option does not override SQL Server constraint and inserted value is 0 instead of NULL.

Constraint that is used:
`ALTER TABLE [dbo].[some_table] ADD  DEFAULT (0) FOR some_fieldname)`

No error is thrown and records are inserted successfully when using BulkInsert method 
The table schema never changed and the table field has "Int" datatype allowing NULLs.

Tested with 
Microsoft.EntityFrameworkCore 5.0.4

Also tested with the latest Microsoft.EntityFrameworkCore 6.05 and EFCore.BulkExtensions 6.05 targeting NET 6.0 framework

**Comment by borisdj** [comment]
It is now simulating how regular EF itself works and EF Core can not insert Null when having Default defined:
https://stackoverflow.com/questions/41969303/ef-core-insert-null-value-to-nullable-column-that-has-default-value
