### ISSUE TITLE
MSSQL BatchDelete - support batch size option to avoid lock escalation

### ISSUE THREAD

**Issue by dahauns** [borisdj/EFCore.BulkExtensions#845]
This would be an enhancement/feature suggestion...

The problem is basically this (esp. the first example):
https://docs.microsoft.com/en-us/troubleshoot/sql/performance/resolve-blocking-problems-caused-lock-escalation

As it is, BatchDelete on MSSQL can run into/cause timeouts/deadlocks when deleting a sufficiently large number of rows in a table, because MSSQL escalates the row locks to a full exclusive(?) table lock when reaching a threshold of 5000 rows.

It's not a bug per se - the same can happen with a simple "delete from x where thedate < $aweekago", but it makes using BatchDelete a time bomb for housekeeping (arguably one of the primary use cases)

My current solution/workaround is something like this:
```
while (rowsAffected >= chunkSize) {
    rowsAffected =
        await _context.Database
            .ExecuteSqlInterpolatedAsync($"DELETE TOP ({chunkSize}) FROM table WHERE theDate < {deleteBefore}",
                cancellationToken);
        }
```

**Comment by borisdj** [comment]
Will consider it, can the same issue occur on BatchUpdate or is it only when Deleting?

**Comment by dahauns** [comment]
Sorry for the late answer! 
BatchUpdate wasn't part of my use case, but from the docs (and a quick browse on dba.stackexchange), lock escalation happens on any kind of large scale row changes, so yes, BatchUpdate would be affected as well.

**Comment by borisdj** [comment]
Тhis would require creating new class `BatchConfig` that would that be send to Batch ops, similar how BulkConfig works.

Before deciding what to do, have you tried making chunk iterations outside of the library, like:
```C#
int rowsAffected = 0;
int chunkSize = 4000;

using var transaction = context.Database.BeginTransaction(); // optionally encapsulate it into Transaction

var query = context.SomeDbSet.AsQueryable().Where(a => a.theDate < deleteBefore);
do
{
    rowsAffected = await query.Take(chunkSize).BatchDeleteAsync();
}
while (rowsAffected >= chunkSize);

transaction.Commit();
```

I thinks this would make the same result without the need to alter the library.

**Comment by dahauns** [comment]
Huh - I had blindly assumed that `IQueryable.Take().BatchDelete()` would have the problem of unnecessarily materializing the result, but after a quick look into the source - it doesn't!
So yeah, that looks like the solution to go when using BatchDelete with MSSQL.

I won't get to try it until next week, but this should do it - Thank you for the suggestion!
