### ISSUE TITLE
Untrusted certificate authority error

### ISSUE THREAD

**Issue by IeuanWalker** [borisdj/EFCore.BulkExtensions#849]
Get this error - 
```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.
```

Version `6.2.8` is fine updating to version `6.5.1` i get the above error.

Had this issue before, but you fixed it and left this comment - https://github.com/dotnet/efcore/issues/27062#issuecomment-1008437263

**Comment by Tyler-V** [comment]
I am using this connection string locally,

`"Server=localhost; Initial Catalog={database}; Integrated Security=SSPI; Persist Security Info=False; Trusted_Connection=True; TrustServerCertificate=True"`

And this connection string on Azure,

`"Server={server};Initial Catalog={database};Persist Security Info=False;User ID={user};Password={password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;"`
