### ISSUE TITLE
System.InvalidOperationException: 'When 'UseTempDB' is set then BulkOperation has to be inside Transaction. Otherwise destination table gets dropped too early because transaction ends before operation is finished.'

### ISSUE THREAD

**Issue by proc01** [borisdj/EFCore.BulkExtensions#867]
System.InvalidOperationException: 'When 'UseTempDB' is set then BulkOperation has to be inside Transaction. Otherwise destination table gets dropped too early because transaction ends before operation is finished.'
Step to reproduce
```
try
{
    using (TransactionScope scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
    {
        var core = new ZZZContext();
        ...
        await core.AuvyBulkUpdateAsync(objects);

        scope.Complete();
    }
}
catch (Exception)
{
    throw;
}
```

**Comment by borisdj** [comment]
Take a look at Test:
https://github.com/borisdj/EFCore.BulkExtensions/blob/4bb9fd3d4b28ad2c43009d2469b7758557692fd5/EFCore.BulkExtensions.Tests/EFCoreBulkTest.cs#L325-L334

**Comment by DaveVdE** [comment]
In my opinion, this is a bug.

The use of a System.Transaction will allow the database provider to create a transaction automatically, so the check that's built into TableInfo is not correct.

I've solved this by opening the database connection explicitly before using `BulkUpdateAsync`.

**Comment by tincann** [comment]
> In my opinion, this is a bug.
> 
> The use of a System.Transaction will allow the database provider to create a transaction automatically, so the check that's built into TableInfo is not correct.
> 
> I've solved this by opening the database connection explicitly before using `BulkUpdateAsync`.

@DaveVdE Thank you! Our code was also using an ambient transaction in combination with UseTempDb and SetOutputIdentity, which confusingly kept throwing the "When 'UseTempDB' is set then BulkOperation has to be inside Transaction" exception. Opening the db connection before calling the bulk operation solved my issue.

@borisdj Looking at the exception condition, would it make sense to add `|| Transaction.Current != null` to this expression? https://github.com/borisdj/EFCore.BulkExtensions/blob/03934e648db21b790f903b008d0deafb0a71cd1e/EFCore.BulkExtensions/TableInfo.cs#L126C21-L126C21
