### ISSUE TITLE
PropertyName 'IsDeleted' specified in 'PropertiesToExclude' not found in Properties.

### ISSUE THREAD

**Issue by amanshakya017** [borisdj/EFCore.BulkExtensions#869]
EFCore.BulkExtensions 6.3.9

at EFCore.BulkExtensions.TableInfo.ValidateSpecifiedPropertiesList(List`1 specifiedPropertiesList, String specifiedPropertiesListName)
   at EFCore.BulkExtensions.TableInfo.LoadData[T](DbContext context, Type type, IList`1 entities, Boolean loadOnlyPKColumn)
   at EFCore.BulkExtensions.TableInfo.CreateInstance[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig)
   at EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync[T](DbContext context, Type type, IList`1 entities, OperationType operationType, BulkConfig bulkConfig, Action`1 progress, CancellationToken cancellationToken)
   at 

`
    public void UpdateBulk(List<T> entities)
	{
		var propToExclude = new List<string> { "IsDeleted", "DeletedBy", "DeletedDate" };
		var config = new BulkConfig { PropertiesToExclude = propToExclude };
		_dbContext.BulkUpdate(entities, config);
	}
	public abstract class BaseEntity
        {
            public Guid Id { get; set; } = Guid.NewGuid();		
            public Guid CreatedBy { get; set; }
            public DateTime CreatedDate { get; set; }
            public Guid? UpdatedBy { get; set; }
            public DateTime? UpdatedDate { get; set; }
        }
	public interface ISoftDeletableEntity
        {
        }
	
	public class Contact : BaseEntity, ISoftDeletableEntity
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string PrimaryEmail { get; set; }
            public string EmailStatus { get; set; }
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		foreach (var relationship in modelBuilder.Model.GetEntityTypes().SelectMany(e => e.GetForeignKeys()))
		{
			relationship.DeleteBehavior = DeleteBehavior.Cascade;
		}

		foreach (var entityType in modelBuilder.Model.GetEntityTypes())
		{
			if (typeof(ISoftDeletableEntity).IsAssignableFrom(entityType.ClrType))
			{
				modelBuilder.Entity(entityType.ClrType).Property<bool>("IsDeleted").HasDefaultValue(false);
				modelBuilder.Entity(entityType.ClrType).Property<Guid?>("DeletedBy").IsRequired(false);
				modelBuilder.Entity(entityType.ClrType).Property<DateTime?>("DeletedDate").IsRequired(false);
				modelBuilder.SetSoftDeleteFilter(entityType.ClrType, "IsDeleted");
			}
		}
		
		base.OnModelCreating(modelBuilder);
		
		modelBuilder.Entity<Contact>(ConfigureContact);
	}
	
	 private void ConfigureContact(EntityTypeBuilder<Contact> builder)
	  {
		  builder.HasIndex(q => q.PrimaryEmail).IsUnique(true);
		  SqlServerIndexBuilderExtensions.IncludeProperties(builder.HasIndex(q => q.EmailStatus), r => new
			   {
				   r.FirstName,
				   r.LastName,
				   r.CreatedDate
			   });
		  builder.Property(x => x.IsSubscribed).HasDefaultValue(true);
	  }`

**Comment by borisdj** [comment]
Properties need to be explicitly exist in entity, add it like:
`public bool IsDeleted { get; set; }`

**Comment by amanshakya017** [comment]
> Properties should be explicitly defined in entity, add it like: `public bool IsDeleted { get; set; }`

@borisdj  Thanks a lot for the reply.
It works when the properties are explicitly defined. At present, it is not available for shadow properties, but hope to see this feature available in future.
Keep up the great work @borisdj  and all the team. 👍
