### ISSUE TITLE
MySql support

### ISSUE THREAD

**Issue by saeidbabaei-dev** [borisdj/EFCore.BulkExtensions#875]
In our company we need mysql bulk insert, i found this package and decided to add mysql support to this package.

**Comment by borisdj** [comment]
Dupe of: https://github.com/borisdj/EFCore.BulkExtensions/issues/553
If you make a PR you can continue discussion there.
Thx for contrib.

**Comment by saeidbabaei-dev** [comment]
Sure. Thanks.
