### ISSUE TITLE
BulkDelete attempts to read non-EF properties

### ISSUE THREAD

**Issue by Manthazar** [borisdj/EFCore.BulkExtensions#876]
Hi folks,

we have identified an issue with BulkExtensions which we cannot work properly around. It seems that bulk delete attempts to read non- EF properties. This is an issue for us because certain properties (navigation/ logical properties) cannot be read from a slim object which subsequently leads to a crash. We attempted to exclude these properties through a bulk configuration, but this just leads to an `InvalidOperationException` that the property is not in all-properties (which is correct).

Example:
Lets say we have an alert which has none or multiple state transitions:
```
class Alert
{
  IEnumerable<StateTransition> AlertStateTransitions {get;set;}
  StateTransition LatestStateTransition => AlertStateTransitions.OrderBy(t=> CreatedOn).FirstOrDefault();
}
```
--> the property LatestStateTransition is calculated. In case we want to delete the alert, we use a _slim_ object. these don't have/load navigation properties, i.e. AlertStateTransitions is null and leads to some exception (correctly).

The db context is properly understanding:
```
public void DbContext_Experiment()
{
   var dbContext = GetService<MyDbContext>();
   var entityType= dbContext.Model.FindEntityType(typeof(Alert));

   var entityProperties = entityType.GetProperties();

   entityProperties.Should().NotContain(ep => ep.Name == nameof(Alert.LatestStateTransition ), because: "this is a calculated property not visible to EF");
}
```
**Excluding** the property leads to an exception similar to this:
![image](https://user-images.githubusercontent.com/76886475/178442283-6c1fa2f5-5939-489c-8586-986cddf109c8.png)

**Not excluding** leads to an exception similar to this:
![image](https://user-images.githubusercontent.com/76886475/178442414-6fcf47db-adaf-48e0-81cf-5ee79890ba11.png)
![image](https://user-images.githubusercontent.com/76886475/178444180-e63169f5-9ad5-466d-b37a-41ab408758aa.png)
(it seems that GenericsHelpers is operating on an invalid instance of the model (i.e. newly created, not passed by us) -so basically all properties are unpopulated (outside of the default constructor?).

The only mitigation we have in the moment is to not let any logical property run into any exception which ain't fine for the reason being that BulkExtension wants always to read them (on delete).

Is there another trick we can apply?

Aron

**Comment by borisdj** [comment]
Can you write a test where the issue would be reproducible.

**Comment by Manthazar** [comment]
Hi Boris, 

doesn't work; it seems the check is too late; `field.GetValue` is called before the tableInfo is checked:
```
if (field.GetIndexParameters().Any()) // Skip Indexer: public string this[string pPropertyName] => string.Empty;
            {
                continue;
            }
            var name = field.Name;
            **var temp = field.GetValue(value);**
            object? defaultValue = null;

            if (!tableInfo.PropertyColumnNamesDict.ContainsKey(name)) // skip non-EF properties
            {
                continue;
            }
```

Cheers,
Aron

**Comment by borisdj** [comment]
Fixed with latest v.
