### ISSUE TITLE
Geometry , Geography 

### ISSUE THREAD

**Issue by Olbrasoft** [borisdj/EFCore.BulkExtensions#88]
https://blogs.msdn.microsoft.com/dotnet/2018/10/17/announcing-entity-framework-core-2-2-preview-3/

Example solution:
https://github.com/Olbrasoft/TravelCore/blob/master/src/Olbrasoft.Data.Entity.Framework.Bulk/ObjectReaderEx.cs

This solution is not optimal Nuget  System.Data.SqlTypes  for this code:
                  case NetTopologySuite.Geometries.Point dbPoint:
                    {
                        var chars = new SqlChars(dbPoint.AsText());
                        return SqlGeography.STGeomFromText(chars, dbPoint.SRID);
                    }
                case NetTopologySuite.Geometries.Polygon dbPolygon:
                    {
                        var chars = new SqlChars(dbPolygon.AsText());
                        return SqlGeography.STGeomFromText(chars, dbPolygon.SRID);
                    }
Throw warnning message not compatible net Core , but it works.

**Comment by borisdj** [comment]
What is the issue here exactly, did you have some exception with these Geo. types?

**Comment by Olbrasoft** [comment]
https://www.nuget.org/packages/Microsoft.SqlServer.Types
Only in Visual Studio is message :
This package may not be fully compatible with your project

comment:
In Entity Framework 6  DbGeography  => Translatet to SqlGeography
In Entity Framework Core https://github.com/NetTopologySuite/NetTopologySuite
I did not have time to examine it anymore, but I just cut the import and I hope you will solve the struggle with time :)

**Comment by borisdj** [comment]
When I catch enough time I'll take a look.

**Comment by acordmike** [comment]
FYI, the EntityFramework.BulkInsert project has this functionality, so you  may be able to look at the code for some guidance.
On specific file is https://github.com/ghost1face/EntityFramework.BulkInsert/blob/master/src/EntityFramework.BulkInsert/Helpers/MappedDataReader.cs

**Comment by 4nonym0us** [comment]
Would be great to have support for Geometry\Geography sql types. Is it still on the roadmap?
The issue became more relevant since EF Core supports working wit spatial data and is compatible with NetTopologySuite.

**Comment by lettucebo** [comment]
Have this functionality would be very helpful~

**Comment by hieuxlu** [comment]
@borisdj I was able to fix this using https://github.com/dotMorten/Microsoft.SqlServer.Types/issues/27. This is a known issue with NET Core SqlClient and SqlBulkCopy, and there's a known fix using dotMorten's  `Microsoft.SqlServer.Types` package to support NET Core. I could make a PR, are you interested in fixing this? 

For reference, a similar fix using this same library has been applied in linq2db project https://linq2db.github.io/articles/FAQ.html#how-can-i-use-sql-server-spatial-types

**Comment by miloszskalecki** [comment]
For those who cannot wait until fix is released I managed to find a workaround:
`  //  i created a generic adapter that allows to do all sorts of magic           
  static void configureConverters(TableInfo ti) => ti.ConvertibleProperties[nameof(Store.LatLong)] = new PointConverter(4326);
              SqlAdaptersMapping.SqlOperationAdapterMapping[DbServer.SqlServer] = new ConfigurableSqlOperationsAdapter(
                  configureInsert: configureConverters,
                  configureMerge: configureConverters);

class ConfigurableSqlOperationsAdapter : ISqlOperationsAdapter
    {
        private readonly Action<TableInfo> _configureTruncate = null;
        private readonly Action<TableInfo> _configureInsert = null;
        private readonly Action<TableInfo> _configureMerge = null;
        private readonly Action<TableInfo> _configureRead = null;

        public ConfigurableSqlOperationsAdapter(
            Action<TableInfo> configureTruncate = null,
            Action<TableInfo> configureInsert = null,
            Action<TableInfo> configureMerge = null,
            Action<TableInfo> configureRead = null)
        {
            _configureTruncate = configureTruncate;
            _configureInsert = configureInsert;
            _configureMerge = configureMerge;
            _configureRead = configureRead;
        }

        private readonly SqlOperationsServerAdapter _adapter = new SqlOperationsServerAdapter();

        public void Insert<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, Action<decimal> progress)
        {
            _configureInsert?.Invoke(tableInfo);

            _adapter.Insert(context, type, entities, tableInfo, progress);
        }

        public Task InsertAsync<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, Action<decimal> progress, CancellationToken cancellationToken)
        {
            _configureInsert?.Invoke(tableInfo);

            return _adapter.InsertAsync(context, type, entities, tableInfo, progress, cancellationToken);
        }

        public void Merge<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, OperationType operationType, Action<decimal> progress) where T : class
        {
            _configureMerge?.Invoke(tableInfo);

            _adapter.Merge(context, type, entities, tableInfo, operationType, progress);
        }

        public Task MergeAsync<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, OperationType operationType, Action<decimal> progress, CancellationToken cancellationToken) where T : class
        {
            _configureMerge?.Invoke(tableInfo);

            return _adapter.MergeAsync(context, type, entities, tableInfo, operationType, progress, cancellationToken);
        }

        public void Read<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, Action<decimal> progress) where T : class
        {
            _configureRead?.Invoke(tableInfo);

            _adapter.Read(context, type, entities, tableInfo, progress);
        }

        public Task ReadAsync<T>(DbContext context, Type type, IList<T> entities, TableInfo tableInfo, Action<decimal> progress, CancellationToken cancellationToken) where T : class
        {
            _configureRead?.Invoke(tableInfo);

            return _adapter.ReadAsync( context, type, entities, tableInfo, progress, cancellationToken);
        }

        public void Truncate(DbContext context, TableInfo tableInfo)
        {
            _configureTruncate?.Invoke(tableInfo);

            _adapter.Truncate(context, tableInfo);
        }

        public Task TruncateAsync(DbContext context, TableInfo tableInfo)
        {
            _configureTruncate?.Invoke(tableInfo);

            return _adapter.TruncateAsync(context, tableInfo);
        }
    }

    public class PointConverter : ValueConverter<Point, byte[]>
    {
        readonly static SqlServerBytesReader _reader = new SqlServerBytesReader
        {
            IsGeography = true
        };

        readonly static SqlServerBytesWriter _writer = new SqlServerBytesWriter
        {
            IsGeography = true
        };

        public PointConverter(int srid, ConverterMappingHints mappingHints = default) : base(
            point => ConvertTo(srid, point),
            point => ConvertFrom(srid, point), mappingHints)
        {
        }

        private static byte[] ConvertTo(int srid, Point point)
        {
            point.SRID = srid;
            return _writer.Write(point);
        }

        private static Point ConvertFrom(int srid, byte[] point)
        {
            return (Point)_reader.Read(point);
        }
    }
`

**Comment by miloszskalecki** [comment]
BTW could we have some extension points in the future (i.e. interface, virtual methods etc that can be easily overridden) as currently whole implementation is based on statics

**Comment by miloszskalecki** [comment]
I managed to find a fix:
https://github.com/borisdj/EFCore.BulkExtensions/issues/88#issuecomment-785884799

**Comment by borisdj** [comment]
Implemented with v3.3.3

**Comment by miloszskalecki** [comment]
> Implemented with v3.3.3

Will upgrade and let you know

**Comment by hieuxlu** [comment]
> Implemented with v3.3.3

The implementation seems to only support Geometry type. We also need to support Geography type as well. In some cases, there's also HierarchyId type.

**Comment by borisdj** [comment]
I am not that familiar with these types. This implementation was a PR https://github.com/borisdj/EFCore.BulkExtensions/pull/420
If someone can make these changes I am happy to merge them.

**Comment by hieuxlu** [comment]
I'll be happy to create a PR in the coming days. My project mostly uses Geography type for longitudes and latitudes. That addition should cover most usecases. For other types such as HierarchyId, there's some roadblocks ahead (https://github.com/efcore/EFCore.SqlServer.HierarchyId/issues/37), so I will leave that out, as I am also not familiar with that type.

**Comment by borisdj** [comment]
Then it's solved 👍
