### ISSUE TITLE
Cloud SQL Support?

### ISSUE THREAD

**Issue by vinothkhanna-s** [borisdj/EFCore.BulkExtensions#880]
Even though this extension is for SQL & Postgres, will this work in Google Cloud SQL? We are migrating from Azure SQL to Cloud SQL and we use the bulk insert, bulkinsertorupdate functions heavily. Hence want to verify if this will work.

**Comment by borisdj** [comment]
Haven't used it, but as I understand it, it is a service for SqlServer so it should work.
Still best to try and test it.

**Comment by vinothkhanna-s** [comment]
Alright, will update here after test results. Thanks.
