### ISSUE TITLE
Setting SetOutputIdentity = true will cause "System.ArgumentException: 'An item with the same key has already been added."

### ISSUE THREAD

**Issue by ognamala** [borisdj/EFCore.BulkExtensions#882]
Hi everyone,

We have been unsing this library flawlessly for a while now, however it seems that after upgrading from dotnet core 3.1 to dotnet6 we are getting issues when attempting to perform a BulkInsertOrUpdateAsync, when SetOutputIdentity is set to true it will end up causing "System.ArgumentException: 'An item with the same key has already been added."

This issue does not occur in version 3.X.X of the library, and seems to occur only if we switch SetOutputIdentity to true - could it be some entities being attached ? We have attempted to explicitly set TrackingEntities to false, however it feels like the entities are being attached anyway.

**EDIT: It does seem that if we switch from BulkInsertOrUpdateAsync to BulkInsertAsync this issue does not occur, however we cannot use BulkInsertAsync as we specifically require BulkInsertOrUpdateAsync**

**EDIT: Downgraded from 6.5.4 to 6.0.0 issue does not occur, will increase slowly to find breaking version**

Has anyone encountered this issue?

Any advice would be greatly appreciated 

Thanks !

**Comment by borisdj** [comment]
Can you write an example with test where the issue would be reproducible.

**Comment by ognamala** [comment]
@borisdj sorry been on holiday and will not have access to my machine for the next week, will try to reproduce as soon as I am back

**Comment by borisdj** [comment]
No problem, when you manage to make a test post it here and will reopen the issue

**Comment by mursel** [comment]
Hi there,

Yes, I have the same problem, but with BulkUpdateAsync method and I can't reproduce it as it seems that sometimes work without problem.

Here's the code

```
public async Task<int> UpdateRangeOfSerialNumbers(IList<SerijskiBrojevi> entities)
{
    var bulkConfig = new BulkConfig
    {
        SetOutputIdentity = true,
        BatchSize = 4000,
        CalculateStats = true
                
    };

    using (var transaction = await _dbContext.Database.BeginTransactionAsync())
    {
        await _dbContext.BulkUpdateAsync<SerijskiBrojevi>(entities, bulkConfig);
        await transaction.CommitAsync();
    }

    return bulkConfig.StatsInfo.StatsNumberUpdated;
}
```

**Comment by TofAtWork** [comment]
Hi,

I have the same issue which is linked to the following commit : https://github.com/borisdj/EFCore.BulkExtensions/commit/b3f5f5c9b77e3dde583b7bb0db5825663c928201#diff-a8eab425ec44046645a8112da55eaa9e082d8c13af26344337674e8c3dcf7691

-> At line 807, one try to add the same key several times in the entitiesDict dictionnary (due to the fact that only the first primary key has been taken into account)
