### ISSUE TITLE
Postgres context.Truncate generating SQL Server command

### ISSUE THREAD

**Issue by afust003** [borisdj/EFCore.BulkExtensions#903]
Hi,

I have a dbContext created using NpgSql driver via dbContextBuilder.UseNpgsql(connStr).
The problem is that calling context.Trucate<MyTable>();
Results in resulting incorrect CommandText SQL saying 
```csharp
TRUNCATE TABLE [dbo].[MyTable];
```
instead of (for postgres-SQL)
```csharp
TRUNCATE TABLE dbo."Mytable";
```

Any thoughts?

Currently using EFCore5. It appears EFCore6 supports Postgres. Does EFCore5 support postgres?
See: https://github.com/borisdj/EFCore.BulkExtensions/issues/67

**Comment by borisdj** [comment]
v5 does not, which is no longer actively maintained. PG support was added in v6,
