### ISSUE TITLE
BatchUpdateAsync   exception

### ISSUE THREAD

**Issue by ByZhouhang** [borisdj/EFCore.BulkExtensions#905]
``` C#
    
   //test 1
       await _repository.BatchUpdateAsync<VisitTask>(t => t.Id==Guid.Empty, u => new VisitTask() {
                SuggesteFinishedTime = u.IsUrgent ? DateTime.Now.AddDays(2) : DateTime.Now.AddDays(7),
            });

  Error :  variable 'u' of type 'IRaCIS.Core.Domain.Models.VisitTask' referenced from scope '', but it is not defined",

   //test 2     can generate sql
       await _repository.BatchUpdateAsync<VisitTask>(t => t.Id==Guid.Empty, u => new VisitTask() {
                Code= u.Code+1,
            });


```

**Comment by borisdj** [comment]
Can you write entire code for Test

**Comment by ByZhouhang** [comment]
> Can you write entire code for Test

I refer to your Usage，Incrementing a column is no problem.
But it is problematic to set the value of a column based on the value of another column.
You can try batch updates like the one I described in any project that uses EFCore.BulkExtensions

**Comment by jamesrwaugh** [comment]
Having the same issue, was following the docs as per OP

When I reference another column such as in a conditional, I get this error.

**Comment by swidz** [comment]
I have very similar issue. I am trying to trim column with Substring:

```
await _ctx.MyTables
  .Where(e => EF.Functions.Like(e.Name, "XXXXX %"))
  .BatchUpdateAsync(e => new MyTable { Name = e.Name.Substring(6) });
```

**Comment by zagoskin** [comment]
Having the same issue. `BatchUpdate()` does work if you want to set values to constants or operations on values that come from the functions scope, but it throws the same error for me if I want to make operations on the results returned by `Where()`

**Comment by borisdj** [comment]
Since Batch ops as of EF7 are now natively supported with _ExecuteUpdate_/_ExecuteDelete_ Batch extensions will become Deprecated here. Focus is only on **BULK** methods which is the main purpose of the lib.
