### ISSUE TITLE
Is there any retry stretagy in bulk operations?

### ISSUE THREAD

**Issue by anchurcn** [borisdj/EFCore.BulkExtensions#928]
I config EnableRetryOnFailure on my db context, I will retry internally on dbContext.SaveChanges() failed.
If I use dbContext.BulkInsertOrUpdate(), will it retry internally?

**Comment by borisdj** [comment]
Bulk ops are done immediately and do not wait for Save changes.
Still you could encapsulate it in a transaction, example in the ReadMe.
And there is BulkSaveChanges but that does track entities, so less efficient then direkt Bulk but faster them regular SaveChanges.
