### ISSUE TITLE
BulkInsert with temporal table and integer PK = Invalid column name

### ISSUE THREAD

**Issue by bdelmeire** [borisdj/EFCore.BulkExtensions#929]
Here is how to reproduce the issue.

1. Replace Guid by int in TestContext.cs (no problem with guid)

```
public class Storage
{
    public int StorageId { get; set; }

    public string Data { get; set; } = null!;
}
```

3. Alter the TemporalTableTest in EFCoreBulkTestAtypical.cs

```
var entities = new List<Storage>()
{
    new Storage { Data = "Info " + 1 },
    new Storage { Data = "Info " + 2 },
    new Storage { Data = "Info " + 3 },
};
context.BulkInsert(entities, new BulkConfig
{
    SetOutputIdentity = true,
});
```

![image](https://user-images.githubusercontent.com/12753346/185586167-d7531a22-e7f3-4270-8b22-de1ceb7daf55.png)

**Comment by borisdj** [comment]
Can confirm the bug.
Have found the fix but it does not load temporal columns since they are not accessible as direct property.

**Comment by bdelmeire** [comment]
Can you share the fix please ? (I don't need temporal columns for BulkInsert)

**Comment by stencelcool** [comment]
Are there any updates regarding mentioned issue ? I also met the problem mentioned by bdelmeire

**Comment by AhmedFay** [comment]
I have the same issue when using BulkOps with excluded columns, then I want to include them within the same transaction

**Comment by borisdj** [comment]
Fixed with latest v.
