### ISSUE TITLE
Does not support Generated Values

### ISSUE THREAD

**Issue by maxchu92** [borisdj/EFCore.BulkExtensions#93]
Using 2.1.9 version.
Does not work with GeneratedValue Data Annotation, or FluentAPI.
https://docs.microsoft.com/en-us/ef/core/modeling/generated-properties

Data Annotation
```
public class MyClass {
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public MyProp { get; set; }
}
```

FluentAPI
```
modelBuilder.Entity<My_Table>().Property(p => p.MyProp).ValueGeneratedOnAddOrUpdate();
```

**Comment by borisdj** [comment]
What exactly is not working?
I have just tested it by adding this attribute
`[DatabaseGenerated(DatabaseGeneratedOption.Identity)]`
on property
`public int ItemId { get; set; }`
of
`public class Item` in _TestContext.cs_
and it passes successfully.

**Comment by maxchu92** [comment]
Sorry for my late reply. The code i typed was incorrect. Its actually.

'''public class MyClass {
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public MyProp { get; set; }
}'''

**Comment by borisdj** [comment]
Computed columns are also supported.
In **_EFCore.BulkExtensions.Tests_** project in **_TestContext.cs_** class `Document` has:
```C#
// Computed columns have to be configured with Fluent API
[DatabaseGenerated(DatabaseGeneratedOption.Computed)]
public int ContentLength { get; set; }
```
which in FluentAPI is configured in the following way:
```C#
modelBuilder.Entity<Document>()
            .Property(p => p.ContentLength)
            .HasComputedColumnSql($"(CONVERT([int], len([{nameof(Document.Content)}])))");
```

And test for this passes successfully `InsertWithDbComputedColumnsAndOutput` in _**EFCoreBulkTestAtypical.cs**_

PS
You still haven't write all info how to reproduce your issue nor what Exception you are getting.

**Comment by maxchu92** [comment]
The program will throw error if DataAnnotation is used without FluentAPI configured.
