### ISSUE TITLE
[question] Bulk Read - load navigation property

### ISSUE THREAD

**Issue by kosaurang** [borisdj/EFCore.BulkExtensions#930]
I have 2 entities : Item and ItemDetail.

I want to use bulk read to load Item and ItemDetail.
```
var items = itemsIds.Select(a => new Item { ItemId= a }).ToList(); 

var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(Item.ItemId) } };

context.BulkRead(items, bulkConfig);
```

after run this code, the ItemDetail doesn't load.
So I don't know how to config to load navigation property for this case.

Would you please help me on this issue ?

**Comment by borisdj** [comment]
BulkRead works only with main table, so you would need to call BulkRead 2 times.
First to load list of Items, and then make load lists of ItemDetails based on ItemId.
