### ISSUE TITLE
Exception when using ToView in model

### ISSUE THREAD

**Issue by OH799** [borisdj/EFCore.BulkExtensions#933]
Bulkupdate doesn't use view as configured in model when updating data.
So exception occurs.

Table:
CREATE TABLE Test
 (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY
 )

View:
CREATE VIEW v_Test AS
SELECT id, 0 AS [Count] FROM test

Model:
  public class Test
  {
    public int id { get; set; }
    public int Count { get; set; }
  }

      modelBuilder.Entity<Test>(entity =>
      {
        entity.ToTable("test", "dbo");
        entity.ToView("v_test", "dbo");

        entity.Property(e => e.id)
        .ValueGeneratedOnAdd();

        entity.Property(e => e.Count).HasColumnName(null);
        entity.Property(e => e.Count).Metadata.SetBeforeSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
        entity.Property(e => e.Count).Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);

      }

**Comment by borisdj** [comment]
View-s do not work with Bulk ops.

**Comment by OH799** [comment]
Yeah, but can it be fixed?
Actual update is via table entity.ToTable("test", "dbo");
And in my case solution is quite simple. Instead of SELECT .... FROM dbo.test in update should it be SELECT ... FROM dbo.v_test

**Comment by borisdj** [comment]
Will consider it.

**Comment by borisdj** [comment]
What was exactly the exception here?
View is used for reading not input, so make no sense to BulkUpdate a View.
I have tested it with BulkUpdate a table and after getting data from its view and they are updated.
Check again with latest version.

**Comment by OH799** [comment]
Of course should not update a view, but when selecting it should be used.

There is still same problem with latest version.
Exception: "Invalid column name 'NegativeCount'
And here is why:
![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/112073065/67f7f7d8-5ba8-4bce-813f-167841c15cb0)
You should select from view if configured. Not from table because using all properties from entity.

Sample as an attachment

[EFGetStarted.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/12046566/EFGetStarted.zip)

**Comment by borisdj** [comment]
The issue here is that this configuration od DbContext generates NegativeCount column in main table if new migration were to be created. And your migration does not have.
Anyway you can make it work without this column in main table by using BulkConfig PropToExclude:
```C#
var bulkConfig = new BulkConfig { PropertiesToExclude = new List<string> { nameof(Test.NegativeCount) } };
await DbContextBulkExtensions.BulkInsertAsync(db, items, bulkConfig);
```

**Comment by OH799** [comment]
Yeah thanks. That fixed our problem. 

```
config = new BulkConfig();

var exludeColumns = entityType.GetProperties().Where(p => p.GetBeforeSaveBehavior() == PropertySaveBehavior.Ignore).Select(p => p.Name).ToList();

config.PropertiesToExclude = exludeColumns;
```
