### ISSUE TITLE
On exception TableTemp******** continue to exist

### ISSUE THREAD

**Issue by nemanjavicovicfz** [borisdj/EFCore.BulkExtensions#936]
When an exception happens for any reason (deadlock or whatever), Temp tables usually in format TableTemp******** (sample: GroupsTemp00644d9b) continue to exist. It would be really useful to have some kind of "clean up" or at least exception handler. We probably could do it ourselves but it's just not so easy to detect exact table name as it seems like it's randomly created

**Comment by borisdj** [comment]
You could set _BulkConfig_ **UniqueTableNameTempDb** to FALSE.

**Comment by nemanjavicovicfz** [comment]
Thanks! Quick one: does that mean that whenever temp table is created and because of some error it remains in DB, it will be overridden by the next etc. BulkInsertOrUpdateOrDelete?

**Comment by borisdj** [comment]
I think not, it would throw exception, that why random name was created to avoid conflicts.
Best to make sure it is deleted if error occurs.

**Comment by nemanjavicovicfz** [comment]
Thanks again. Makes sense
