### ISSUE TITLE
BulkInsertOrUpdate creates ans syntax error for tables without Non-Key columns 

### ISSUE THREAD

**Issue by manfredwippel** [borisdj/EFCore.BulkExtensions#94]
When a table consists of Key columns only the Merge Statement created is invalid.

CREATE TABLE [dbo].[r_attack](
	[codeid] [bigint] NOT NULL,
	[idclass] [bigint] NOT NULL,
	[codeidhost] [bigint] NOT NULL,
 CONSTRAINT [PK_r_attack] PRIMARY KEY CLUSTERED 
(
	[codeid] ASC,
	[idclass] ASC,
	[codeidhost] ASC
) 

leads to following Statement:
MERGE [dbo].[r_attack] WITH (HOLDLOCK) AS T 
USING [dbo].[r_attackTempb91bd167] AS S ON T.[codeid] = S.[codeid] AND T.[idclass] = S.[idclass] AND T.[codeidhost] = S.[codeidhost] 
WHEN NOT MATCHED BY TARGET THEN 
INSERT ([codeid], [idclass], [codeidhost]) 
VALUES (S.[codeid], S.[idclass], S.[codeidhost]) 
WHEN MATCHED THEN UPDATE SET ;

**Comment by borisdj** [comment]
I have confirmed the bug.
Will fix it soon.

**Comment by borisdj** [comment]
Fixed with NuGet 2.2.4
