### ISSUE TITLE
Per Provider Packaging

### ISSUE THREAD

**Issue by HClausing** [borisdj/EFCore.BulkExtensions#941]
Congratulations for this excelent job. It's very helpfull.

I would like to purpose an ideia: Instead of referencing many EfCore providers into a single Package, to split the projet with a Core classes, and one Package (project) per provider. It will help us to get smaller applications and avoid unused referencies.

- [EntityFrameworkCore.SqlServer.HierarchyId](https://www.nuget.org/packages/EntityFrameworkCore.SqlServer.HierarchyId/)
- [Microsoft.EntityFrameworkCore.Sqlite.Core](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Sqlite.Core/)
- [Npgsql.EntityFrameworkCore.PostgreSQL](https://www.nuget.org/packages/Npgsql.EntityFrameworkCore.PostgreSQL/)
- [Pomelo.EntityFrameworkCore.MySql](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/)

Into (for example):

EFCore.BulkExtensions.Core (shared classes)
EFCore.BulkExtensions.SqlServer
EFCore.BulkExtensions.Sqlite
EFCore.BulkExtensions.PostgreSQL.Npgsql
EFCore.BulkExtensions.MySql.Pomelo

I can do this job if you are accepting PR's.

**Comment by borisdj** [comment]
It was discussed in this issue https://github.com/borisdj/EFCore.BulkExtensions/pull/942 and was in plan.

**Comment by code-jar** [comment]
Is there any new progress?

**Comment by HClausing** [comment]
> Is there any new progress?

#942

**Comment by borisdj** [comment]
New Structure (as of verion 6.6.0):
| Num | Project | References | NuGet |
| - | - | - | - |
| [0] | EFCore.BulkExtensions                     |      | - |
| [1] | EFCore.BulkExtensions.SQLServer    | [0] | EFCore.BulkExtensions.SQLServer |
| [2] | EFCore.BulkExtensions.PostgreSQL  | [0] | EFCore.BulkExtensions.PostgreSQL|
| [3] | EFCore.BulkExtensions.MySQL         | [0] | EFCore.BulkExtensions.MySQL |
| [4] | EFCore.BulkExtensions.SQLite          | [0] | EFCore.BulkExtensions.SQLite |
| [5] | EFCore.BulkExtensions.Common      | [1,2,3,4] | EFCore.BulkExtensions

[0] | _EFCore.BulkExtensions_ is shared core project that has no Nuget.
Instead project [5] _EFCore.BulkExtensions.Common_ references all other projects thereby includes all providers and it has NuGet with base name: **EFCore.BulkExtensions** to keep full compatibility with previous versions.
