### ISSUE TITLE
Foreign Key Not saved

### ISSUE THREAD

**Issue by jlcarpenter** [borisdj/EFCore.BulkExtensions#944]
I am using the bulk insert and update on a table with a foreign key. The foreign key should already be I the table so I am retrieving the object from the database and assuming it to the object being inserted/updated. When I save and then look at the table the column for the foreign key is always null. Is there a setting I need to add to the save call for the column to be saved?

**Comment by borisdj** [comment]
Entity needs to have property of ForeignKeyId, implicit navigation relationship is not enough.
