### ISSUE TITLE
Whether relevant data can be carried when the exception is thrown

### ISSUE THREAD

**Issue by zhuangState** [borisdj/EFCore.BulkExtensions#945]
If Bulkxxx is used for batch update and creation, can you carry exception related data like "DbUpdateException"

![J4MU67U7ER(12JSH}B$R9FP](https://user-images.githubusercontent.com/98197028/190348448-191ad409-0d4e-44fa-a0a5-d6263ac9255b.jpg)

**Comment by borisdj** [comment]
Update Exception can easily be read from the Message.
For example if conflict happens on UniqueIndex it gives Index name and Value.
Sample:

> 'Cannot insert duplicate key row in object 'dbo.Customer' with unique index 'IX_Customer_Name'.
> The duplicate key value is (SomeCustomer).
> The statement has been terminated.'
