### ISSUE TITLE
BulkInsert does not populate foreign keys for child entities

### ISSUE THREAD

**Issue by jaybz** [borisdj/EFCore.BulkExtensions#95]
I have an set of POCOs that are set up like this:

```
public class Parent {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ParentID { get; set; }

        [ForeignKey("ChildAID")]
        public ChildA ChildA { get; set; }

        [ForeignKey("ChildBID")]
        public ChildB ChildB { get; set; }
}

public class ChildA {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ChildAID { get; set; }

        [ForeignKey("ChildBID")]
        public virtual ChildB ChildB { get; set; }
        public long? ChildBID { get; set; }

        public string SomeProperty { get; set; }
}

public class ChildB {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long ChildBID { get; set; }

        public string SomeProperty { get; set; }
}
```
My problem is that when using BulkInsert on Parent entities that have existing ChildA and ChildB entities, the keys for ChildA and ChildB are not populated on the Parent's table. My code does something like this:
```
var children = context.ChildA.Where(c => c.SomeProperty.Equals("somestring"));
var parentsToCreate = new List<Parent>();
foreach(var child in children) {
        parentsToCreate.Add(new Parent { 
                ChildA = child,
                ChildB = child.ChildB
        });
}
dataMatchingContext.BulkInsert(parentsToCreate);
```
This does insert to the Parent table, but both ChildAID and ChildBID is null. Replacing the BulkInsert call with the code below populates both child IDs properly but is obviously slow.
```
dataMatchingContext.AddRange(parentsToCreate)
dataMatchingContext.SaveChanges();
```

**Comment by borisdj** [comment]
For FKs in BULK you need FKId Properties in Parent class:
([ForeignKey] Attributes are not required if FKId Properties are named by convention ChildNavProp + 'ID'/'Id')
```C#
public class Parent
{
    [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long ParentID { get; set; }
    
    //[ForeignKey("ChildAID")]
    public ChildA ChildA { get; set; }
    public long ChildAID { get; set; }
    
    //[ForeignKey("ChildBID")]
    public ChildB ChildB { get; set; }
    public long? ChildBID { get; set; }
}
```
And you need to set them as well.
```C#
new Parent
{
    ChildA = child,
    ChildB = child.ChildB,
    ChildAID = child.ChildAID,
    ChildBID = child.ChildBID
}
```
Also if you don't need to use Navigation Properties you don't have to set them, you could just have:
```C#
new Parent
{
    ChildAID = child.ChildAID,
    ChildBID = child.ChildBID
}
```

**Comment by jaybz** [comment]
Is there no way to make it work without exposing the IDs? I don't actually need any of the IDs but I do need the navigation properties in my model.

**Comment by borisdj** [comment]
In that case, keep Navigation but add IDs also to Entity.

I find it good practice to always have explicit IDs.
One benefit is you can reference ID directly 'parent.ChildID' instead of `parent.Child.ChildID`.
Second is you sometimes need them explicit if ColumnName would be different from PropertyName.
And direct ID is more practical for writing Linq Join-s.

Anyway in the library column is mapped with the property and Navigation ones are ignored.
Theoretically FK property could be dynamically created from Nav. property (similar as EF is doing it) but I am not yet sure how that would be implemented.
