### ISSUE TITLE
BulkRead not working (> 1 entity)

### ISSUE THREAD

**Issue by Odraio** [borisdj/EFCore.BulkExtensions#955]
The `BulkRead` method doesn't seem to get the data from the database when `items` (first line) contains more than 1 item.

- In case of one item, the `BulkRead` does get the data and fills all properties.
- In case of multiple items (> 1), the `BulkRead` does nog get the data and all properties contain the default value.

Is this is a bug or is something missing in below code sample? (Is it somehow possible to view the generated query?)

Thank you in advance!

```
public class Item {
  [Key]
  public long Id {get;set;}
  public string Name {get;set;}
  public DateTime? StartDate {get;set;}
}

var items = myObjects.Select(x => new Item() { Id = x.Id}).ToList();
var bulkConfig = new BulkConfig { UpdateByProperties = new List<string> { nameof(Item.Id) } };
_context.BulkRead(items, bulkConfig);
```

**Update 1:** Above sample code didn't pass bulkConfig in BulkRead call.

**Comment by Systemko** [comment]
Hi [Odraio](https://github.com/Odraio)!

Could you please provide information what database do you use? Implementation details of BulkRead are far different.
As far as I know for MS SQL it works as expected.

P.S. You are creating bulkConfig but not providing it to BulkRead method.

**Comment by borisdj** [comment]
Try to write a test or take a look at existing tests with BulkRead and try to modify them to your use case.

**Comment by Odraio** [comment]
The issue has been resolved using `SetOutputIdentity = true` in case of a SQL Server database.
Using the same code doesn't work while using Microsoft.EntityFrameworkCore.**Sqlite** (6.0.9)... the properties still contain the default values.

**Comment by Systemko** [comment]
[Odraio](https://github.com/Odraio)

I investigated your problem, and you are right. It's not working correctly with Sqlite. But I'm sure it wll if you set SqlBulkCopyOptions like this:

`SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity`

It feels like a bug for me.

**Comment by Odraio** [comment]
@Systemko The provided solution works for BulkRead!

In addition, I am using BulkUpdate (sqlite - memory db). It seems the bulk changes are not persisted in the context. Do I need to apply another SqlBulkCopyOptions?
