### ISSUE TITLE
BulkRead with WHERE clause and ORDER BY

### ISSUE THREAD

**Issue by Odraio** [borisdj/EFCore.BulkExtensions#959]
Is it somehow possible to use the BulkRead method with a WHERE clause and ORDER BY?
I would like to get several entities in an efficient way.

`context.BulkRead(entities).Where(x => x.Status == "Test").OrderByDescending(x => x.Date);`

**Comment by borisdj** [comment]
No, when BulkRead is mean to load a list based on Unique column(s).
If you have WHERE then no need for BulkRead.
