### ISSUE TITLE
BulkRead (auto) remove non-existent items.

### ISSUE THREAD

**Issue by Odraio** [borisdj/EFCore.BulkExtensions#960]
Is it possible to (auto) remove items which are NOT present in the database?

E.g. `myIds` contains 1234 (an Id which doesn't exists in the database).
After executing the BulkRead method, the items list still contains the item... 
**Does EFCore.BulkExtensions provide a bulkConfig to remove the non-existent items?**

```
var items = myIds.Select(tmpId => new Item() { Id = tmpId }).ToList();
var bulkConfig = new BulkConfig { SetOutputIdentity = true, SqlBulkCopyOptions = SqlBulkCopyOptions.KeepIdentity};
_context.BulkRead(items, bulkConfig);
```

**Comment by Odraio** [comment]
I think the question/ request  will be resolved by pull request [Added ReplaceReadEntities property to BulkConfig (#571). #946](https://github.com/borisdj/EFCore.BulkExtensions/pull/946#issue-1376870677)

**Comment by borisdj** [comment]
This would not be base feature of the lib.
Better to implement it by overriding the BulkRead method, similir example just for Audit: https://github.com/borisdj/EFCore.BulkExtensions/issues/56
