### ISSUE TITLE
MERGE STATEMENT Conflicts Circumvention

### ISSUE THREAD

**Issue by YuriiMocherniuk** [borisdj/EFCore.BulkExtensions#961]
Hello,
Sometimes if an inserted record via BulkInsertOrUpdate references a non-existing primary key value, this results in "The MERGE statement conflicted with the FOREIGN KEY constraint..."  errors. Unfortunately, due to quality of data source it's not possible to achieve ER consistency in 100% of cases.
So is there any way to change the behavior of the EFCore.BulkExtensions, e.g. via BulkConfig either to ignore such errors or to skip inserting a record if the respective primary key value is invalid/missing?

**Comment by danbopes** [comment]
I'm running into this same issue. I'd like to bulk insert, but simply ignore if the company profile doesn't exist.

**Comment by borisdj** [comment]
Have you tried
_SqlBulkCopyOptions_ with [Flag](https://stackoverflow.com/questions/8447/what-does-the-flags-enum-attribute-mean-in-c) **_CheckConstraints_**: FALSE
