### ISSUE TITLE
PostgreSQL BulkInsert Error

### ISSUE THREAD

**Issue by dgsaoppps** [borisdj/EFCore.BulkExtensions#964]
Hi Team,
When we try to use bulk insert method for the PostgreSQL, we are getting an error like this "42601: syntax error at or near "0"".
We looked deeply exception details and there is a SQL query running background and this not available for the PostgreSQL. 
Is there any solution for the disable this query? Or Is there any property "BulkConfig" class to disable that?

SELECT 
T**OP 0**  //Not a correct syntax for the PostgreSQL
T.[Id], T.[Email], T.[Name] INTO [UsersTemp24499146] 
FROM [Users] AS T LEFT JOIN [Users] AS Source ON 1 = 0

var context = _userRepository.GetContext();
using (var ts = context.Database.BeginTransaction())
{
     var config = _userRepository.GetBulkConfig();
     config.PreserveInsertOrder = false;
     context.BulkInsert(users, config);
     ts.Commit();
}

"EFCore.BulkExtensions" Version="5.4.2"
"Microsoft.EntityFrameworkCore.Design" Version="5.0.7"
"Microsoft.EntityFrameworkCore.Tools" Version="5.0.7"
"Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7"

**Comment by borisdj** [comment]
Unable to reproduce it with current versions.
Try updating to newer v. and if still have issue write a test, new one or alter existing where it occurs.
