### ISSUE TITLE
MySQL error when using BulkInsertAsync (related to "load data local" feature)

### ISSUE THREAD

**Issue by eduflm** [borisdj/EFCore.BulkExtensions#968]
Greetings, 

I'm trying to use BulkInsertAsync in direct way. 

```cs
public async void InsertBulkAsync(List<MyEntity> listOfEntities)
{
    var context = await GetDbContextAsync();
    await context.BulkInsertAsync(listOfEntities);
    await context.BulkSaveChangesAsync();
}
```

After "BulkSaveChangesAsync" i'm getting the following error: 

`To use MySqlBulkLoader.Local=true, set AllowLoadLocalInfile=true in the connection string. See https://fl.vu/mysql-load-data`

As I saw in the link provided by the error, MySQL is using a feature to bulk data from a CSV or TSV file (which is not my case). 

Can I force MySQL though EFCore.BuilkExtensions to not use this feature? 

I'm using: 
MySQL Version: 8.0.27
.NET6
EntityFrameworkCore: 6.0

Also, using ABP Framework in version 6.0.

Thanks in advance!

**Comment by shamork** [comment]
I am looking for a work around too.
