### ISSUE TITLE
Insert identity class, with preserve insert order set true and excluding identity column via PropertiesToExclude.

### ISSUE THREAD

**Issue by erickcruzf** [borisdj/EFCore.BulkExtensions#971]
Hi there, I have debugged on my machine, and seems like it throws an error while trying to order the results, because the column is removed from the insert because I excluded the identity column. I just want to  let the db handle it, is it possible? Thanks. I'm trying to bulkInsert with these bulkconfigs => 
```
private static BulkConfig GetBulkConfig(string identityPropertyName)
        {
            var bulkConfig = new BulkConfig { SqlBulkCopyOptions = SqlBulkCopyOptions.CheckConstraints | SqlBulkCopyOptions.FireTriggers, UseTempDB = true };

            if (!string.IsNullOrEmpty(identityPropertyName))
            {
                bulkConfig.SetOutputIdentity = true;
                bulkConfig.PropertiesToExclude = new List<string> { identityPropertyName };
            }

            return bulkConfig;
        }
```

I'm getting this error log:

> Value cannot be null. (Parameter 'key') (System.ArgumentNullException)
>    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at EFCore.BulkExtensions.TableInfo.CheckToSetIdentityForPreserveOrder[T](TableInfo tableInfo, IList`1 entities, Boolean reset) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\TableInfo.cs:line 926
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 40
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.InsertAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, Action`1 progress, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 33
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 221
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, Boolean isAsync, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 310
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SQLAdapters\SQLServer\SqlServerAdapter.cs:line 123
>    at EFCore.BulkExtensions.SqlBulkOperation.MergeAsync[T](DbContext context, Type type, IList`1 entities, TableInfo tableInfo, OperationType operationType, Action`1 progress, CancellationToken cancellationToken) in ~\EFCore.BulkExtensions-6.5.6\EFCore.BulkExtensions\SqlBulkOperation.cs:line 74

**Comment by coolio986** [comment]
I also get this same error

`List<string> propsToExclude = new List<string>()
            {
                "ClusterID",
            };`

`database.BulkInsertOrUpdate(list, bulkConfig);`

ClusterID in this context is PK, int, not null with a non clustered index

The entity contains a "0" for ClusterID (again int, so 0), but props to exclude specifically excludes it. Since this property contains a non-nullable int, it should not get a nulled int sent when propsToExclude is set to a non-nullable PK.

**Comment by coolio986** [comment]
![image](https://user-images.githubusercontent.com/28740147/201778613-194374ae-eb28-4da0-b480-c26d870e350a.png)

**Comment by erickcruzf** [comment]
entity has the identity column mapped, and if I do not use the PropertiesToExclude I get [IDENTITY_INSERT is set to OFF] error, so the bug is on the entity side?
