### ISSUE TITLE
context.Items.Where(x => x.SomeString = searchValue).BatchUpdate(...) fails when searchValue has a single letter within square brackets

### ISSUE THREAD

**Issue by jaybz** [borisdj/EFCore.BulkExtensions#98]
My code is something like this:
```
context.Items.Where(x => x.SomeString == searchValue).BatchUpdate(new Item { BooleanValue = true});
```
When searchValue has contains like this "[x]" (where x is any character), it produces an exception with the following error message: "Incorrect syntax near the keyword 'AS'."

I also noticed that the "[x]" part gets replaced with "[a]" on the query. For example, if searchValue="Bo[o]p", the code produces a query like this:
```
UPDATE [tblItem] AS [x]
WHERE [x].[SomeString] = N'Bo[a]p'
```
Also note that the following code works:
```
var i = context.Items.Where(x => x.SomeString == searchValue).ToList()
```
This points to the problem being on how EFCore.BulkExtensions builds the query.

**Comment by borisdj** [comment]
I have implemented a fix for this.
Published NuGet 2.2.7

**Comment by jaybz** [comment]
I'm now getting this error message: "System.ArgumentOutOfRangeException: 'Index and count must refer to a location within the string.'"

This is the stacktrace outside of my app:
   at System.String.Remove(Int32 startIndex, Int32 count)
   at EFCore.BulkExtensions.BatchUtil.ReplaceLetterInBracketsWithA(String sql)
   at EFCore.BulkExtensions.BatchUtil.GetSqlUpdate[T](IQueryable`1 query, DbContext context, T updateValues, List`1 updateColumns)
   at EFCore.BulkExtensions.IQueryableBatchExtensions.BatchUpdate[T](IQueryable`1 query, T updateValues, List`1 updateColumns)

This error occurs whether or not the string contains the [x] pattern.

**Comment by borisdj** [comment]
Fix v2
NuGet 2.2.8
