### ISSUE TITLE
EF Core 3.1 version 3.6.6 is not working with proxy entities and IncludeGraph

### ISSUE THREAD

**Issue by CopyPasteRepeat** [borisdj/EFCore.BulkExtensions#981]
Hi @borisdj  I upgraded from version 3.1.3 to 3.6.6 to get navigation property support with the IncludeGraph option.
In my testing, the NuGet package always throws a null reference exception.

I installed the source code of EF Core 3.1 branch in our solution and debugged the issue. I detected that several usages of Model.FindEntityType were not able to get the enity type, because our entities are proxies. That was then causing the null reference exception on the next call on the entityType variables. 

After some investigation I found out that replacing FindEntityType with FindRuntimeEntityType solves the issue in all cases. I've added a screenshot of all the occurrences that I've adjusted in the source to make it work for us.

I would really appreciate getting a fixed version for this issue to avoid using the source code in our solution and keep upgradability to new versions. so @borisdj would that be possible? We would really like to continue using the nuget and upgrade it as soon as possible.

![image](https://user-images.githubusercontent.com/11267699/196965942-bf3636de-9092-4b49-b5d2-d5e46711cdce.png)

**Comment by borisdj** [comment]
I'm afraid that prior version are no longer actively supported.
