### ISSUE TITLE
Support Concurrency Checking in Postgres

### ISSUE THREAD

**Issue by dimgiatz** [borisdj/EFCore.BulkExtensions#987]
Support for concurrency token in Postgres with Npsql library is done by using the "xmin" system column (see more [here](https://www.npgsql.org/efcore/modeling/concurrency.html)).

However, this causes an "InvalidOperationException: The required column 'xmin' was not present in the results of a 'FromSql' operation." error being thrown when trying to update an entity that uses 'xmin' as a concurrency token with BulkSaveChanges.

My configuration is the following. I tried `PropertiesToExclude` in an effort to avoid the error to no avail.

```           
var _config = new BulkConfig()
            {
                PropertiesToExclude = new List<string> {"xmin"},
                SetOutputIdentity = true,
                EnableShadowProperties = true,
                OmitClauseExistsExcept = true,
                WithHoldlock = false,
                BulkCopyTimeout = 0,
                BatchSize = _options.BatchSize,
            };
```

Can we support concurrency checks in Postgres as we do in SQL Server with the DoNotUpdateIfTimeStampChanged setting? I understand it is a different and more difficult case in Postgres with the hidden shadow property but i believe it would be really beneficial if we do support this.

At the very least could we have a way to avoid this error being thrown? BulkUpdate don't have this issue, only with BulkSaveChanges we see this.

**Comment by borisdj** [comment]
Added Test **TimeStampPGTest** with _BulkSaveChanges_ and PG _TimeStamp_.
Unable to reproduce the issue with latest version.
