### ISSUE TITLE
 Error with shadow properties that are part of the primary key and a foreign key using Sqlite

### ISSUE THREAD

**Issue by gpinod** [borisdj/EFCore.BulkExtensions#990]
When you have an entity that has shadow properties that are part of the primary key and more importantly a foreign key, using Sqlite, you get an error when trying to use the BulkUpdate, regardless of setting the EnableShadowProperties to true and also having the ShadowPropertyValue.
The exception is:
$exception {"The given key 'PropertyName' was not present in the dictionary."} System.Collections.Generic.KeyNotFoundException.
And the error comes out in the method EFCore.BulkExtensions.SQLAdapters.SQLite.SqliteOperationsAdapter.LoadSqliteValues[T](TableInfo tableInfo, T entity, SqliteCommand command, DbContext dbContext)

**Comment by geis01** [comment]
I have the exact same issue with BulkInsert.

**Comment by borisdj** [comment]
Should be Fixed with latest v.
