### ISSUE TITLE
net7 support

### ISSUE THREAD

**Issue by sommmen** [borisdj/EFCore.BulkExtensions#993]
Hiya,

net7 is out so i though i'd make an issue to track net7 and ef core 7 support.

**Comment by Webreaper** [comment]
Bulkextensions already supports .Net 7. Unfortunately, though, it seems to be explicitly pulling in dependencies for RC2, which is causing a package downgrade compile failure when using the full .Net 7 GA. :(

**Comment by mkalinski93** [comment]
Net7 will be very nice.

@Webreaper I´ve tried implementing it, but as you´ve stated correctly the dependency downgrade is the main issue why it´s not working on my end. I think it was the Microsoft.EntityFrameworkCore.Relational library which causes a lot of trouble. I will fork it and try to overcome this issue

**Comment by bdbvb** [comment]
I'm getting the following build warnings after updating an existing project to .NET 7. The mentioned dependency is used by EFCore.BulkExtensions.

`Detected package version outside of dependency constraint: Pomelo.EntityFrameworkCore.MySql 6.0.2 requires Microsoft.EntityFrameworkCore.Relational (>= 6.0.7 && < 7.0.0) but version Microsoft.EntityFrameworkCore.Relational 7.0.0 was resolved.
`

**Comment by mikebrownNCDOT** [comment]
BulkExtensions can't be updated for net7 support until the Pomelo MySql library gets theirs working. If you want to follow that (should be very soon), go here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1717

**Comment by Webreaper** [comment]
I'm building fine now. Can't remember what I changed but it all works.

**Comment by Syzuna** [comment]
I've just got rid of the MySQL implementation as I dont need it anyway and I am using my own build for now. 
besides the MySQL driver issue everything else was smooth sailing

**Comment by jr01** [comment]
and if you update to .NET 7 and also target EF Core 7 and use BulkUpdateAsync, BulkInsertOrUpdate, or BulkInsertOrUpdateOrDelete you'll get a runtime exception:
```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommand Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression)'.
  Stack Trace: 
   IQueryableExtensions.ToParametrizedSql(IQueryable query)
    BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
```

**Comment by Webreaper** [comment]
Tbh, if you're using .net 7, it probably makes sense to switch to the new EFCore ExecuteUpdate etc APIs now.

(sorry @borisdj - we'll never forget that you plugged this gap until MSFT finally got their house in order!)

**Comment by mkalinski93** [comment]
@Webreaper they just support update and delete. This library, for example, can bulk read a lot of entities just by their id´s and populate them back into the list you´ve provided. They need more  than just 2 methods to compete with this library.

**Comment by Webreaper** [comment]
> @Webreaper they just support update and delete. This library, for example, can bulk read a lot of entities just by their id´s and populate them back into the list you´ve provided. They need more  than just 2 methods to compete with this library.

True!

**Comment by Syzuna** [comment]
Especially the Bulk Insert is important for me as I have need of importing large chunks of data from time to time and not doing it with using COPY in Postgres but with individual INSERT that are batched its just not feasable

**Comment by sommmen** [comment]
Update, the Pomelo MySql upgrade for net7 has been merged in master,
So we can expect an update to the MySql nuget soon.

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/commit/147559fcc81ec51020b142d1a0eb6c42dde8c82f

**Comment by mkalinski93** [comment]
this is great news.

**Comment by sommmen** [comment]
> This includes full support for all features of EF Core 7.
> While this is an alpha release, it is backed by over 26,000 tests.
> The current plan is to release a 7.0.0-beta.1 version in a week and a stable official version by the end of the month.

The alpha version can only be installed manually:

`NuGet\Install-Package Pomelo.EntityFrameworkCore.MySql -Version 7.0.0-alpha.1`

Aside from this unfortunately, including this package i'm getting issues with `BulkInsertOrUpdateOrDeleteAsync`

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommand Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression)'.
  Source=EFCore.BulkExtensions
  StackTrace:
   at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
   at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
   at EFCore.BulkExtensions.SqlQueryBuilder.MergeTable[T](DbContext context, TableInfo tableInfo, OperationType operationType, IEnumerable`1 entityPropertyWithDefaultValue)
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__4`1.MoveNext()
   at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__5`1.MoveNext()
   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
   at [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeSyncStrategy`1.<ExecuteAsync>d__6`1.MoveNext() in C:\Repos\dotnet-api\DAL\Repositories\Bulk\Strategy\BulkMergeSyncStrategy.cs:line 31

  This exception was originally thrown at this call stack:
    EFCore.BulkExtensions.BatchUtil.GetBatchSql(System.Linq.IQueryable, Microsoft.EntityFrameworkCore.DbContext, bool)
    EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, bool, System.Threading.CancellationToken)
    EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, bool, System.Threading.CancellationToken)
    EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, System.Threading.CancellationToken)
    EFCore.BulkExtensions.SqlBulkOperation.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, System.Threading.CancellationToken)
    EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.OperationType, EFCore.BulkExtensions.BulkConfig, System.Action<decimal>, System.Threading.CancellationToken)
    [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeSyncStrategy<TEnt>.ExecuteAsync<T>(System.Collections.Generic.IList<T>, Microsoft.EntityFrameworkCore.DbContext, [REDACTED].DAL.Repositories.Bulk.BulkMergeIO.BulkMergeOptions, System.Threading.CancellationToken) in BulkMergeSyncStrategy.cs
```

However the kind of entity matters, for example this class does not throw:

``` csharp
public class HarvestLLTimeSheet
{
    public Guid Id { get; set; }
    public DateTimeOffset Day { get; set; }
    public double Hours { get; set; }
    [StringLength(64)]
    public string? Task { get; set; }
    [StringLength(256)]
    public string? Note { get; set; } 
    [StringLength(32)]
    public string? User { get; set; }
}
``` 

Whilst this one does;

``` csharp
public enum EBlogStatus
{
    Unknown = 0,
    Publish = 1,
    Future = 2,
    Draft = 3,
    Pending = 4,
    Private = 5,
    Trash = 6, 
    Inherit = 7
}

public class Blog
{
    public Guid Id { get; set; }

    public long ExternalId { get; set; }

    #region Domain

    public Guid DomainId { get; set; }

    public Domain Domain { get; set; } = null!;

    #endregion

    public string? Title { get; set; }

    public DateTimeOffset CreationDateTime { get; set; }
    public DateTimeOffset ModifiedDateTime { get; set; }

    public EBlogStatus Status { get; set; }
    public string? Slug { get; set; }
}
```

So i think it has to do with navigation properties.

**Comment by sommmen** [comment]
> > This includes full support for all features of EF Core 7.
> > While this is an alpha release, it is backed by over 26,000 tests.
> > The current plan is to release a 7.0.0-beta.1 version in a week and a stable official version by the end of the month.
> 
> The alpha version can only be installed manually:
> 
> `NuGet\Install-Package Pomelo.EntityFrameworkCore.MySql -Version 7.0.0-alpha.1`
> 
> Aside from this unfortunately, including this package i'm getting issues with `BulkInsertOrUpdateOrDeleteAsync` (note i'm using MSSQL for this command, not mysql)
> 
> ```
> System.MissingMethodException
>   HResult=0x80131513
>   Message=Method not found: 'Microsoft.EntityFrameworkCore.Storage.IRelationalCommand Microsoft.EntityFrameworkCore.Query.QuerySqlGenerator.GetCommand(Microsoft.EntityFrameworkCore.Query.SqlExpressions.SelectExpression)'.
>   Source=EFCore.BulkExtensions
>   StackTrace:
>    at EFCore.BulkExtensions.IQueryableExtensions.ToParametrizedSql(IQueryable query)
>    at EFCore.BulkExtensions.BatchUtil.GetBatchSql(IQueryable query, DbContext context, Boolean isUpdate)
>    at EFCore.BulkExtensions.SqlQueryBuilder.MergeTable[T](DbContext context, TableInfo tableInfo, OperationType operationType, IEnumerable`1 entityPropertyWithDefaultValue)
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()
>    at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__4`1.MoveNext()
>    at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__5`1.MoveNext()
>    at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()
>    at [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeSyncStrategy`1.<ExecuteAsync>d__6`1.MoveNext() in C:\Repos\dotnet-api\DAL\Repositories\Bulk\Strategy\BulkMergeSyncStrategy.cs:line 31
> 
>   This exception was originally thrown at this call stack:
>     EFCore.BulkExtensions.BatchUtil.GetBatchSql(System.Linq.IQueryable, Microsoft.EntityFrameworkCore.DbContext, bool)
>     EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, bool, System.Threading.CancellationToken)
>     EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, bool, System.Threading.CancellationToken)
>     EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, System.Threading.CancellationToken)
>     EFCore.BulkExtensions.SqlBulkOperation.MergeAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.TableInfo, EFCore.BulkExtensions.OperationType, System.Action<decimal>, System.Threading.CancellationToken)
>     EFCore.BulkExtensions.DbContextBulkTransaction.ExecuteAsync<T>(Microsoft.EntityFrameworkCore.DbContext, System.Type, System.Collections.Generic.IList<T>, EFCore.BulkExtensions.OperationType, EFCore.BulkExtensions.BulkConfig, System.Action<decimal>, System.Threading.CancellationToken)
>     [REDACTED].DAL.Repositories.Bulk.Strategy.BulkMergeSyncStrategy<TEnt>.ExecuteAsync<T>(System.Collections.Generic.IList<T>, Microsoft.EntityFrameworkCore.DbContext, [REDACTED].DAL.Repositories.Bulk.BulkMergeIO.BulkMergeOptions, System.Threading.CancellationToken) in BulkMergeSyncStrategy.cs
> ```
> 
> However the kind of entity matters, for example this class does not throw:
> 
> ```cs
> public class HarvestLLTimeSheet
> {
>     public Guid Id { get; set; }
>     public DateTimeOffset Day { get; set; }
>     public double Hours { get; set; }
>     [StringLength(64)]
>     public string? Task { get; set; }
>     [StringLength(256)]
>     public string? Note { get; set; } 
>     [StringLength(32)]
>     public string? User { get; set; }
> }
> ```
> 
> Whilst this one does;
> 
> ```cs
> public enum EBlogStatus
> {
>     Unknown = 0,
>     Publish = 1,
>     Future = 2,
>     Draft = 3,
>     Pending = 4,
>     Private = 5,
>     Trash = 6, 
>     Inherit = 7
> }
> 
> public class Blog
> {
>     public Guid Id { get; set; }
> 
>     public long ExternalId { get; set; }
> 
>     #region Domain
> 
>     public Guid DomainId { get; set; }
> 
>     public Domain Domain { get; set; } = null!;
> 
>     #endregion
> 
>     public string? Title { get; set; }
> 
>     public DateTimeOffset CreationDateTime { get; set; }
>     public DateTimeOffset ModifiedDateTime { get; set; }
> 
>     public EBlogStatus Status { get; set; }
>     public string? Slug { get; set; }
> }
> ```
> 
> So i think it has to do with navigation properties.

@borisdj Hiya - do you have any time to take a look at this issue?

**Comment by vladop** [comment]
@sommmen so tomorrow we will have package you mentioned released since end of the month is tomorrow?

**Comment by benmccallum** [comment]
I'm also getting the runtime exception mentioned. Unfortunately, I don't have the bandwidth to look at it myself otherwise I'd dive in and see what could be done. I'm sure targeting this repo at net7.0 and building it would highlight the method being used that's no longer available.

**Comment by HClausing** [comment]
There's a possibilty on changing csproj's target to use more than one:

 `<TargetFramework>net6.0</TargetFramework>`
 to 
`<TargetFrameworks>net6.0;net7.0</TargetFrameworks>`

I did this on another project and works very well. It's also  possible to use conditional nuget packager for every target:

```
   <!-- target independent -->
  <ItemGroup>
    <PackageReference Include="DefaultDocumentation" Version="0.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EficazFramework.DocsApiPlugin" Version="1.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

   <!-- net 6.0 -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
  	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.11" />
  	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.11" />
  	<PackageReference Include="System.Security.Permissions" Version="6.0.0" />
  </ItemGroup>
  
   <!-- net 7.0 -->
  <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
  	<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
  	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.0" />
  	<PackageReference Include="System.Security.Permissions" Version="7.0.0" />
  </ItemGroup>
```

**Comment by pdevito3** [comment]
bump

**Comment by Webreaper** [comment]
Seriously, guys, two "bump" posts in 8 hours? Please stop. I'm sure @borisdj will get to this when he has time. If you really need it urgently, maybe raise a PR with the fix yourselves.

**Comment by mkamranaslam** [comment]
Getting this issue on 7.0.1
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.EntityFrameworkCore.Relational. Install/reference Microsoft.EntityFrameworkCore.Relational 7.0.1 directly to project MyPorject.EntityFrameworkCore to resolve this issue. 
 MyPorject.EntityFrameworkCore -> Microsoft.EntityFrameworkCore.Design 7.0.1 -> Microsoft.EntityFrameworkCore.Relational (>= 7.0.1) 
 MyPorject.EntityFrameworkCore -> EFCore.BulkExtensions 6.6.2 -> Pomelo.EntityFrameworkCore.MySql 6.0.2 -> Microsoft.EntityFrameworkCore.Relational (>= 6.0.7 && < 7.0.0).	MyPorject.EntityFrameworkCore	C:\MyPorject\src\MyPorject.EntityFrameworkCore\MyPorject.EntityFrameworkCore.csproj	1

**Comment by akonyer** [comment]
With EF7 and NpgSql 7.0.1 I am getting the following exception when trying to bulk insert data:

`System.InvalidOperationException: The binary import operation was started with 7 column(s), but 8 value(s) were provided. at Npgsql.ThrowHelper.ThrowInvalidOperationException_BinaryImportParametersMismatch(Int32 columnCount, Int32 valueCount) at Npgsql.NpgsqlBinaryImporter.CheckColumnIndex() at Npgsql.NpgsqlBinaryImporter.Write[T](T value, String dataTypeName, Boolean async, CancellationToken cancellationToken)`

This looks like the same issue described here was was supposedly fixed: https://github.com/borisdj/EFCore.BulkExtensions/issues/769

**Comment by adamhathcock** [comment]
I've made a private fork against EF7 and updated Pomelo as well.  Been working fine for me in production.  

Not sure what the direction for dotnet 7 support is.  Willing to help.

**Comment by benmccallum** [comment]
I also had to make a fork for us to keep moving (we have our target framework set across our whole mono repo). #1044 gets it targeting and working with net7.

**Comment by sommmen** [comment]
> I also had to make a fork for us to keep moving (we have our target framework set across our whole mono repo). #1044 gets it targeting and working with net7, just needs to be merged.

2 days ago i made the same decision because this was holding us back for too long.

If you too have this issue, you can use my .net package:

https://github.com/sommmen/EFCore.BulkExtensions/releases/tag/6.9.9-alpha

I've pasted this nuget package in my repo in `"~\LocalPackages\EFCore.BulkExtensions.SqlServer.6.9.9-alpha.nupkg"`.
Then i added the following NuGet.Config file, which defines a local nuget package feed:

``` xml
<?xml version="1.0" encoding="utf-8"?>

<configuration>
	<!-- Setup for local packages, not in a nuget source -->
	<packageSources>
		<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
		<add key="LocalPackages" value="$/../LocalPackages" />

	</packageSources>
	<activePackageSource>
		<!-- this tells that all of them are active -->
		<add key="All" value="(Aggregate source)" />
	</activePackageSource>

</configuration>
```

You may want to close and reopen visual studio because it has a tendency to aggresively cache things and the local package feed may not show up.

Then simply install the package;
`NuGet\Install-Package EFCore.BulkExtensions -Version 6.9.9-alpha`

If you're using the dotnet restore task in Azure pipelines to build your code, it may fail because it uses a temp nuget.config and that messes up the path. In that case refer to simply running `dotnet restore` which should work:

``` yaml
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: '$(solution)'
    custom: 'restore'
  displayName: "Restore"
```

**Comment by martonx** [comment]
I'm waiting the .Net 7 support.

**Comment by sportmoltas** [comment]
The Pomolo package have been released....
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/7.0.0

**Comment by angelaki** [comment]
I sure still use the lib for BulkInserts. But is there any advantage using BulkExtensions' `BatchDeleteAsync` over the new `ExecuteDeleteAsync`? Or is it actually quite the same?

**Comment by rick-palmsens** [comment]
> The Pomolo package have been released.... https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/7.0.0

Manually including this version will fix the nuget dependency warnings, which can be a good solution if you don't actually use MySQL.

**Comment by borisdj** [comment]
Sorry for the delay lately, I had to sort out some things.

Also Pomelo 7.0.0 is only as of few days in full release, and while in prerelease dependency it was blocking creation of production nuget.

v7 is published and for now has target .net6 since is works for app targeting both .net6 and .net7
While those using EF6 can use BulkExtensions v6 version (will consider later if multitarget if better approach because of maintaining it as it's LTS)

_Execute Update & Delete_ are analogous to BatchOps (_BatchUpdate / BatchDelete_) in the library, so those methods will probably later be marked as Deprecated.
But they were just a small part and were actually added latter.
*The main purpose of the lib are Bulk CRUD methods with advanced configurable features for dealing with large list of data, something that framework itself does not have.

-Last but not the least:
Also to note that License has some changes, more info in Issue: '_LICENSE change notice_'.

**Comment by borisdj** [comment]
@sommmen @HClausing @benmccallum and others ...
Regarding the version and compatibility, now v7 uses EF 7 and has target Net 6 so it can be used in project targeting both Net 6 and Net 7. While for EF 6 version v6 should be used.

I'm having considerations about making Multitarget as proposed.
It would be practical for maintenance since v6 is LTS.
However one scenario in this case could be problematic, and that is when application that is targeting .Net 6 but uses EF 7. There conditional nuget resolving would go Bulk-v6 when Bulk-v7 is needed.
Any ideas ??

**Comment by borisdj** [comment]
Just a note here:
Will not use multitarget because then it would not work properly in apps that are targeting .Net 6 but are using  EF7.
Instead since the code is same, will just change dependency versions before publish and build v6 Nugets.
Similar was already being done with per Provider packages.
Latest v6 is 6.7.1. and source in merged into Branch 6.0

**Comment by angelaki** [comment]
> I sure still use the lib for BulkInserts. But is there any advantage using BulkExtensions' `BatchDeleteAsync` over the new `ExecuteDeleteAsync`? Or is it actually quite the same?

Just to make sure - is there any advantage one over the other?

**Comment by borisdj** [comment]
Not sure about performances in all situations, but since both are using pure Sql should be pretty similar if not the same.
I have marked Batch obsolete as there are native now.
But they still work and can be used from the Lib. is one would need them for some specific situation or custom overriding.

Also there was a one or two usecases, that was found in Batch tests, with somewhat complex _Where_(..) in query, that does not work with Execute so for those situations Batch can be of use.

Btw, unrelated note, with .Net8 multiTarget is used.
