### ISSUE TITLE
BulkInsert fails with a list containing a single entity

### ISSUE THREAD

**Issue by TwigMonster81** [borisdj/EFCore.BulkExtensions#994]
We have been using this successfully for importing substantial amounts of data, after several tweaks to our EF configuration. However, our automated tests which pass in a list containing a single element fail with "Column [Id] does not allow DBNull.Value". The entities are complex, with server-generated Id values and we have set our BulkConfig accordingly (IncludeObjectGraph is enabled). We have determined, through much trial and error, that the single entity is the cause of the problem - if we add a second item with exactly the same object graph and values, both items and all of their children are successfully inserted. It is therefore not a mapping or DbContext configuration problem.  Is this a known issue, and if so is there an existing workaround?

Thanks in advance

**Comment by borisdj** [comment]
I have tried it with test _BulkInsertOrUpdate_EntityWithNestedObjectGraph_SavesGraphToDatabase_
By removing second object and leaving only WorkOrder1 and it passed.
